### ISSUE TITLE
Start Menu improvement N2: most frequently used apps

### ISSUE THREAD

**Issue by birdie-github** [lxqt/lxqt#100]
Keep the history of recently run applications and allocate a configurable number of them on the top sorted by their usage frequency:
- Most run app N1
- Most run app N2
- Most run app N3
- Most run app N4
-  -- separator --
- Normal Start Menu items below

**Comment by tsujan** [comment]
Apps are usually run with the file manager, and pcmanfm-qt supports this.

For other usages, you could use Fancy Menu (in git for now), which supports Favorites. I don't think there's a reason to keep this report open indefinitely.
