### ISSUE TITLE
lxqt-leave: GUIs flickering if invoked from lxqt-runner under Openbox

### ISSUE THREAD

**Issue by pmattern** [lxqt/lxqt#1009]
When the GUIs corresponding to invocations `lxqt-leave --foobar` are launched from the menu of lxqt-runner they come up sort of flickering, apparently due to rapidly getting and loosing focus.

Problem seems to be related to the window manager as it cannot be seen with KWin or Xfwm4 but Openbox, the latter using the vanilla configuration provided by upstream.
Finding can be made most of the time when lxqt-runner is placed at the top of the screen but always when it is placed in its middle.
Aside from looking odd the windows aren't really reactive due to the ever changing focus.

Today's checkout of all LXQt components, among other lxde/lxqt-session@3acb9fe and lxde/lxqt-runner@65d674e, on up to date Arch Linux x86_64 or i686, either "bare metal" or in a KVM/QEMU virtual machine.

**Comment by agaida** [comment]
can't reproduce anymore
