### ISSUE TITLE
plugin-statusnotifier: Make it possible to hide notifiers

### ISSUE THREAD

**Issue by RalfJung** [lxqt/lxqt#1012]
It would be great if individual icons could be hidden in the "status notifier" part of the panel, similar to what KDE does. As far as I understand, there is even the possibility for the application to communicate to the panel whether there is something interesting going on right now, which could provide a nice automatic show/hide behavior.

It was said in https://github.com/lxde/lxqt/issues/64#issuecomment-94001577 that this would happen for the status notifier, but at least with LXQt 0.10, I can't see any way to hide icons.

**Comment by paulolieuthier** [comment]
Yeah, it's actually part of the [specification](https://www.freedesktop.org/wiki/Specifications/StatusNotifierItem/StatusNotifierItem/) (see 'Status').

**Comment by paulolieuthier** [comment]
I didn't implement it because I wanted to make plugin popups consistent and standardized first, but never did.

**Comment by tsujan** [comment]
After some elementary ugly changes to the code:

![hidden](https://user-images.githubusercontent.com/981076/36354148-1329d4c4-14e5-11e8-8b6f-e15803baf33e.png)

This isn't a real implementation but just shows the idea. Hidden items should be made visible automatically when needed and should be made hidden again after a while when not needed. The container can be a `QFrame` as popup and can have configurable rows/columns.

Moreover, the size of icons should be made configurable on the status notifier, IMO.

**Comment by tsujan** [comment]
Started to do it — and more than it — without a side widget. Self-assigning...

**Comment by tsujan** [comment]
It seems finished (mostly a boring job of considering all possibilities):

![auto-hide](https://user-images.githubusercontent.com/981076/82745821-cfcd8380-9d9d-11ea-9019-1a4d136a9438.png)

If there are (auto-)hidden items, an extra button will appear, which shows all items when clicked; then (auto-)hidden items will be made hidden again after 2 seconds if the the mouse cursor leaves Status Notifier.

The auto-hidden items (in contrast to hidden ones) that need attention are shown for 5 minutes before being made hidden again.

Apart from explicit attention requests, I also interpreted an icon change as an attention request with auto-hiding. That's useful, for example, when the icon of battery charge or CMST is changed (= battery is charged/discharged or WiFi signal is weakened/strengthened).

I'll use it for a while before making a PR to see if additional practical ideas come to my mind or an issue surfaces.

**Comment by yan12125** [comment]
Thanks for @tsujan's awesome work hiding notifier icons is now possible. There is a few follow-up questions at https://github.com/lxqt/lxqt-panel/issues/1426 for remaining discussions.
