### ISSUE TITLE
LXQt Autostart Sesion Settings not saving

### ISSUE THREAD

**Issue by interwebjill** [lxqt/lxqt#1014]
I am on Beaglebone running Debian Jessie. I am trying to save Autostart settings to startup a python file in kiosk mode. I put these into the Session Settings dialog box and press close, but then when I reopen the dialog box they are gone. 

When I reboot, I get a message alert that says LXQt Session Reboot: Do you want to really restart your computer? All unsaved work will be lost...

**Comment by stefonarch** [comment]
There should be a corresponding .desktop file created in ~/.config/autostart, other autostart stuff works?
The "unsaved lost" alert can be disabled in session settings.

**Comment by tsujan** [comment]
As @stefonarch said, that alert can be disabled; it's a general alert and not related to your problem.

Do you add the script to the global or LXQT autostart? Will it appear in the global autostart if you manually create an appropriate desktop file in `~/.config/autostart`?

**Comment by pmattern** [comment]
Official LXQt repositories geared towards Debian jessie on ARM don't exist and an upstream problem resulting in your findings would probably have made it to this issue tracker before. So it's very likey a downstream issue.
You may want to let us know which way you installed LXQt.

Also, it would be good to know what exactly you've been filing in the forms of `lxqt-config-session` and what the content of an eventual file in `~/.config/autostart` that @stefonarch  was rightly asking for looks like.

**Comment by Bonzoo2525** [comment]
LXQT settings then Session settings. Uncheck the box ask before leaving. Case closed. Sparky 2020.06
