### ISSUE TITLE
lxqt-openssh-askpass : Completed French translations

### ISSUE THREAD

**Issue by paiiou** [lxqt/lxqt#1023]
I propose an zip archive 
[lxqt-openssh-askpass-translations_fr_FR.zip](https://github.com/lxde/lxqt/files/223285/lxqt-openssh-askpass-translations_fr_FR.zip)
with the completed French translations.
Be free to use them or to correct them.

**Comment by palinek** [comment]
Please, submit a pull request for all your recent prpoposals. thanks

**Comment by pmattern** [comment]
Agree. While any effort to help improve LXQt is welcome, dealing with those zip files isn't exactly handy for us.
There's an [article](https://github.com/lxde/lxqt/wiki/Translation) in the wiki which may eventually help you to get along with the approach we've got to take currently.

**Comment by paiiou** [comment]
thank you for your answer. I looked at the indicated page.
My control of the English language is quasi worthless and I am not familiarized with git.
I will only be able to propose the zip archives
at 72 years there is much evil with the innovations.

**Comment by stefonarch** [comment]
I could eventually trasform the .zips in commits in spare time, but my french is not at a level to check for eventual mistakes. 

This issue indicates again the urge of providing an easy way to contribute with translations, is there hope for pootle soon @jleclanche ?
