### ISSUE TITLE
Sound mixer volumes broken in git

### ISSUE THREAD

**Issue by jleclanche** [lxqt/lxqt#1029]
Testing the updated sound mixer, there seems to be some pretty bad regressions when allowing volume to go past 100%.

Messing with the volumes a bit between the two, they seem to "desync", to the point that the volume range, in pavucontrol, is very quiet at 95% and extremely loud at 100%.

If someone else can reproduce this we should get this fixed before release.

**Comment by technic** [comment]
Can't reproduce. Do you have pulseaudio in the lxqt volume control widget?

**Comment by tsimonq2** [comment]
@jleclanche Any chance you could be a bit more specific as to what the problem is? I would like to reproduce but I can't figure out how...

**Comment by agaida** [comment]
can reproduce it on ubuntu artful on my armhf machine - but nowhere else

**Comment by tsimonq2** [comment]
@agaida Were you able to reproduce it on an amd64 or i386 Artful system? I can't reproduce it on my amd64 Artful system.

**Comment by palinek** [comment]
Can this be reproduced? If not, I would suggest to close...

**Comment by agaida** [comment]
seems to be gone
