### ISSUE TITLE
liblxqt: please don't break abi compat with older versions ..

### ISSUE THREAD

**Issue by agaida** [lxqt/lxqt#1036]
.. without deprecating symbols for a release cycle or so. Doing so will make downstream hate us for a reason :)

```
- (c++)"LXQt::PageSelectWidget::sizeHint() const@Base" 0.9.0+20150911
+#MISSING: 0.10.0-22-gb4372f2-2# (c++)"LXQt::PageSelectWidget::sizeHint() const@Base" 0.9.0+20150911
```

I don't know which applications use this symbol, but they are successfully borked right now without an abi bump. This will affect lubuntu-daily, Arch Aur and some bleeding edge downstreams. As a rule of thumb: Adding symbols is ok, removing or altering without warning is a no go.
^^ @palinek

**Comment by paulolieuthier** [comment]
We must use [d-pointers](https://wiki.qt.io/D-Pointer) for all classes in liblxqt. See lxde/liblxqt#72.

**Comment by agaida** [comment]
@paulolieuthier: right

@palinek: in that case deprecating PageSelectWidget::sizeHint() would be enough for now - mark it as deprecated in both headers and implementation and don't use it anymore, remove the function in a year or two. That would make transitions a lot smoother.

**Comment by luis-pereira** [comment]
@paulolieuthier we should use d-pointers in all libraries :wink: We probably should state it in our development guide.

**Comment by paulolieuthier** [comment]
> @paulolieuthier we should use d-pointers in all libraries.

Yeah, sure.

**Comment by palinek** [comment]
> I don't know which applications use this symbol, but they are successfully borked right now without an abi bump. This will affect lubuntu-daily, Arch Aur and some bleeding edge downstreams. As a rule of thumb: Adding symbols is ok, removing or altering without warning is a no go.

Sorry, but I've changed an internal class (symbol) which can't be used directly by any user of this library. Did any app broke or the error is just from some "checker"?

Just tried to run the existing lxqt app (compiled/built against the "old" liblxqt) with the "new" liblxqt and everything is fine.

So in such cases (internal classes/symbols) we should not export them.

**Comment by agaida** [comment]
@palinek - full ack. if the class/symbol  is only for internal use we really should not export. :) I have seen no bugs so far, but i have to maintain some symbol files in debian - and changes or removements in the symbols trigger some panic attacs :D
