### ISSUE TITLE
Taskbar: custom mouse actions

### ISSUE THREAD

**Issue by Vladimir-csp** [lxqt/lxqt#104]
Migrating https://github.com/Razor-qt/razor-qt/issues/642 here with some improvements.
Add ability to customize mouse actions, assign actions to mouse events.

Actions:
- context menu
- iconify
- restore
- maximize
- {enable,disable,toggle} fullscreen
- close
- restore (from maximized) > iconify (depending on current window state)
- restore (from iconified) > maximize (depending on current window state)
- {enable,disable,toggle} always on top
- {enable,disable,toggle} sticky

Mouse events:
- left click
- double left click
- long left click
- right click
- long right click
- middle click
- long middle click
- wheel up
- wheel down

The idea is to be able to assign anything from first list to anything from the second

**Comment by yan12125** [comment]
Is it possible to add an option to disable application switching when mouse wheels? It's an annoying feature for me.

**Comment by pmattern** [comment]
> Is it possible to add an option to disable application switching when mouse wheels?

Could you elaborate what you mean by this? Is it cycling through the windows when the mouse wheel is incidentally turned while the pointer happens to be over an instance of plugin-taskbar which does feature some windows?

**Comment by yan12125** [comment]
For example, usually I make Firefox maximized, and move my cursor around when scrolling and browsing. There are times that I accidently move my cursor outside Firefox and into the region of taskbar, so I hope there's an option to disable this feature.

**Comment by palinek** [comment]
> Is it possible to add an option to disable application switching when mouse wheels? It's an annoying feature for me.

@yan12125 see the lxde/lxqt-panel#379

**Comment by tsujan** [comment]
The effect of mouse wheel and other things can be customized now.
