### ISSUE TITLE
LXQT Panel "weather plugin"

### ISSUE THREAD

**Issue by jenom1957** [lxqt/lxqt#1040]
there is very limited plugins are available for panel
really missing the "weather plugin"

**Comment by pmattern** [comment]
Do you know [meteo-qt](https://github.com/dglent/meteo-qt)?

**Comment by jenom1957** [comment]
yes, tried it.....needed to DL about 60  Mb python related pkges to satisfy dependencies
when run it still complained about  missing staff
did not work at the end

**Comment by agaida** [comment]
meteo-qt works great for me

**Comment by jenom1957** [comment]
not in my Debian-8 testing 4.5.0-1-amd64
what do you have?

**Comment by manjaro-lxqt** [comment]
I used meteo-qt in the past, but it brings with it a lot on dependencies on pyqt5 and some qt5 modules.

**Comment by tsujan** [comment]
@jenom1957 
Maybe it's not what you want, but I've always used Conky both for weather report and for gmail notification, even under KDE. You could write your own bash script or find one and use it in with Conky.

**Comment by jenom1957** [comment]
tried also gkrellm+weather........too simple for my taste
managed to install my-weather-indicator (ubuntu version)
it looks nice showing 4 days forecast
just need to figure out how to add to panel or start

**Comment by pmattern** [comment]
On systems where LXQt and its dependencies are already installed the additional runtime dependencies of meteo-qt are roughly 30MB which is Python stuff that can eventually be used by other applications, too. To update the translations locally another 50MB are needed which can get removed after installing again, though. But let's be honest, given the size of current storage devices even 80MB are close to nothing.

Following the instructions currently provided on the homepage meteo-qt is working well here on all distributions mentioned including Debian testing.

While I'd have agreed with complaints about lacking features, e. g. other data providers or better forecast functionality, I have to say I can't follow the arguments stated so far here.
Honestly I tend to close this as wontfix. Considering the software that's available by now any attempt to develop yet another panel plugin would be pretty much superfluous work.

**Comment by agaida** [comment]
@jenom1957: i will test it for a while and then make a package eventually

**Comment by jenom1957** [comment]
only xfce4 has a working weather plugin
lxde lxpanel 0.8.2 has one where location can not be set.....so it is useless
would be great to have it in lxqt
thanks
