### ISSUE TITLE
JDownloader 2 system tray icon heavily malformed in Panel

### ISSUE THREAD

**Issue by Atalanttore** [lxqt/lxqt#1041]
Hi,

the system tray icon of [JDownloader 2](http://jdownloader.org/download/index) is heavily malformed in LxQt Panel.

Screenshot:
![jd2_system_tray_icon](https://cloud.githubusercontent.com/assets/628474/14941591/2eb52176-0fa1-11e6-954d-27931faa81cd.png)
This screenshot is showing the JDownloader 2 icon on the left and the battery monitor icon on the right.

Regards,
Atalanttore

**Comment by pmattern** [comment]
Is this in `plugin-statusnotifier` or in `plugin-tray`? If in doubt you can find this out easily by looking through the panel configuration dialogue that can be invoked from the panel's context menu.

**Comment by stefonarch** [comment]
Old. Tray is deprecated. No further info.
