### ISSUE TITLE
Hande .desktop files in Weblate

### ISSUE THREAD

**Issue by luis-pereira** [lxqt/lxqt#1044]
It doesn't make much sense for a translator to translate the messages from the `.ts files` through Pootle and the ones coming from the `.desktop` files in another way (Pootle seems to not handle .desktop files, according to [this](http://docs.translatehouse.org/projects/translate-toolkit/en/stable-1.14.0/features.html).

Gettext version 0.19 can actually handle the `.desktop` format. I've played with it a little and it's possible to convert from `.desktop` to `.po` and vice-versa. The `.po` file can be handled by Pootle.

**Comment by agaida** [comment]
po sounds good

**Comment by stefonarch** [comment]
I found this,thinking about to use *.ts files to handle with weblate:
http://manpages.ubuntu.com/manpages/bionic/man1/deepin-desktop-ts-convert.1.html

Making some tests.

**Comment by stefonarch** [comment]
Created some scripts that [generates](https://github.com/stefonarch/menu-files/blob/main/lxqt-about/desktop_files/) the .desktop files in the same way their are present in the repositories.
Example:
```
#Translations
Name[de]=Über LXQt
GenericName[de]=Über LXQt
Comment[de]=Mehr über LXQt erfahren
```
I didn't check but probably the files are not all the same overall, using this script all files will follow this pattern (or another we can define).

**Comment by stefonarch** [comment]
@tsujan @yan12125  This is mostly ready.  My idea is:

* regenerate all desktop files following a standard  (example: https://github.com/lxqt/lxqt-admin/pull/213/files) 
* open translation for some components for testing

There will be a cronjob that every 24h

* monitors for .ts file changes in menu-files 
* copies over the modified or new ones into their repo 
*  makes a PR from inside weblate.

**Comment by yan12125** [comment]
The idea sounds good, but the repository status shown at https://translate.lxqt-project.org/projects/lxqt-menu/lxqt-about/#repository looks horrible. I haven't had time to check out what happens there. Any ideas? @stefonarch

**Comment by stefonarch** [comment]
No this repo isn't to look at, there is also garbage of testing  :)

lxqt-about is also the name of the  _main_ repo, as `config-session` is for session, leave and config-session:
```
weblate@weblate:~/git/lxqt-menu/lxqt-about$ l
total 152K
drwxr-xr-x  4 weblate weblate 4.0K Oct  8 15:00 lximage-qt
drwxr-xr-x  3 weblate weblate 4.0K Oct  6 19:42 lximage-qt-screenshot
drwxr-xr-x  5 weblate weblate 4.0K Oct  8 20:30 lxqt-about
drwxr-xr-x  4 weblate weblate 4.0K Oct  7 10:12 lxqt-admin-time
drwxr-xr-x  4 weblate weblate 4.0K Oct  7 10:12 lxqt-admin-user
drwxr-xr-x  3 weblate weblate 4.0K Oct  8 22:24 lxqt-archiver
drwxr-xr-x  3 weblate weblate 4.0K Oct  8 22:26 lxqt-config
drwxr-xr-x  3 weblate weblate 4.0K Oct  8 22:28 lxqt-config-appearance
drwxr-xr-x  3 weblate weblate 4.0K Oct  6 10:45 lxqt-config-appswitcher
drwxr-xr-x  3 weblate weblate 4.0K Oct  8 22:30 lxqt-config-brightness
drwxr-xr-x  3 weblate weblate 4.0K Oct  8 22:31 lxqt-config-file-associations
drwxr-xr-x  3 weblate weblate 4.0K Oct  8 22:31 lxqt-config-globalkeyshortcuts
drwxr-xr-x  3 weblate weblate 4.0K Oct  6 10:45 lxqt-config-input
drwxr-xr-x  3 weblate weblate 4.0K Oct  6 10:45 lxqt-config-locale
drwxr-xr-x  3 weblate weblate 4.0K Oct  6 10:45 lxqt-config-monitor
drwxr-xr-x  3 weblate weblate 4.0K Oct  6 10:45 lxqt-config-notificationd
drwxr-xr-x  3 weblate weblate 4.0K Oct  6 10:45 lxqt-config-powermanagement
drwxr-xr-x  3 weblate weblate 4.0K Oct  6 10:45 lxqt-config-session
drwxr-xr-x  3 weblate weblate 4.0K Oct  6 10:45 lxqt-hibernate
drwxr-xr-x  3 weblate weblate 4.0K Oct  6 10:45 lxqt-leave
drwxr-xr-x  3 weblate weblate 4.0K Oct  6 10:45 lxqt-lockscreen
drwxr-xr-x  3 weblate weblate 4.0K Oct  6 10:45 lxqt-logout
drwxr-xr-x  3 weblate weblate 4.0K Oct  6 10:45 lxqt-reboot
drwxr-xr-x  3 weblate weblate 4.0K Oct  6 10:45 lxqt-shutdown
drwxr-xr-x  3 weblate weblate 4.0K Oct  6 10:45 lxqt-suspend
drwxr-xr-x  3 weblate weblate 4.0K Oct  5 21:42 lxqt-xfwm-settings
drwxr-xr-x  3 weblate weblate 4.0K Oct  5 21:42 lxqt-xfwmtweaks
drwxr-xr-x  3 weblate weblate 4.0K Oct  5 21:42 lxqt-xfwm-workspaces
drwxr-xr-x  2 weblate weblate 4.0K Oct  6 10:45 menu-arch
drwxr-xr-x 22 weblate weblate 4.0K Oct  7 10:12 panel
```


It will contain untracked desktop files always, a file "<omponent>/languages" for all old and new languages and a file for the link to <component>/translations where the new desktop files have to be copied to. It will be updated based on the desktop file in /usr/share/applications of a fresh github checkout.

The deepin scripts take as input and  generates as output a complete .desktop file as those present in /usr/share/applications in LXQt installations.

There is another script which takes the <component>.new.desktop as input and generates all the <component>_[xz].desktop files as they are present in the repos for each language, each one formatted the same way as in the PR.

I'll update the repo/scripts with the new ones in use.

**Comment by stefonarch** [comment]
Made a cleanup, pushed also the modified scripts - in weblate all desktop files are now formatted in the same way.
https://github.com/stefonarch/menu-files

Ideally this repo has never to be updated, only if new components come in or for direct PR to the .desktop files.

**Comment by stefonarch** [comment]
I've changed idea: setting  up automatization is probably worse than commit the changes manually - one  issue is conserving  author credits, and the translations will be very few coming in anyway  I suspect, so it isn't worth the work.

Unlocked the translations and testing from now on.

**Comment by yan12125** [comment]
How about putting translated `*.ts` in individual git repos (lxqt-about, lxqt-admin, ...) and generate `*.desktop` files during compilation? For weblate they are as usual as other Qt translations, and future credits are preserved with `*.ts` files.

**Comment by stefonarch** [comment]
I don't know how the compile process works exactly, only that the .desktop files for each language at the end get composed to the one "component.desktop" file including desktop.in. 

So first desktop_xy.ts  > to component_xy.desktop and then all of them to the "main" desktop file?

Sure it would be easier and cleaner  at the end, but to reimport   in weblate it's not that easy I think, because they are so many again.
Maybe test it with on repo?
https://github.com/stefonarch/menu-files/tree/main/lximage-qt/ts_files

I saw now some translations coming in, will test the "manual" way atm.

**Comment by yan12125** [comment]
> Maybe test it with on repo?

Thanks for the pointer! I tried it out and the result looks good. With
```
deepin-desktop-ts-convert ts2desktop lxqt-about/resources/lxqt-about.desktop.in menu-files/lxqt-about/ts_files lxqt-about.desktop
```
the generated lxqt-about.desktop if identical to https://github.com/stefonarch/menu-files/blob/main/lximage-qt/lximage-qt.new.desktop. Here `./lxqt-about` and `./menu-files` are git clones for https://github.com/lxqt/lxqt-about/ and https://github.com/stefonarch/menu-files/, respectively.

So, a possible plan might be:

1. Move ts files from https://github.com/stefonarch/menu-files/ to individual repositories and replace translated desktop files (e.g., https://github.com/lxqt/lxqt-about/blob/master/translations/lxqt-about_ar.desktop)
2. Update https://github.com/lxqt/lxqt-build-tools/blob/master/cmake/modules/LXQtTranslateDesktop.cmake to make it handle ts files besides translated desktop files
3. Change URLs and filename masks for each Weblate component (yes, that is a pain - hopefully only one time pain)
4. Have fun with translating :D

**Comment by stefonarch** [comment]
I've little time atm, saw also server errors now with lxqt-about.
Testing manually I happened to see that qterminal is different (no single .desktop file and has also an option) and screengrab's original desktop.file misses a lot of Name= ...

So your way is to go, I'd say.

If we use .ts files there is no need at all to have still single *_xy.desktop files around - `ts2sdesktop` generates the final desktop file, only the[ ordering is ugly](https://github.com/stefonarch/menu-files/blob/main/lxqt-config-input/lxqt-config-input.new.desktop), I wonder if this python script could be modified to sort entries by language as usual. 

For importing into weblate  those ts.files should be in a separate  directory, eg. /translations/desktop_files, but this has to be tested, not sure, maybe filemask is enough.

**Comment by yan12125** [comment]
> ordering is ugly

I guess the deepin tool simply sorts all lines alphabetically. My argument is that those are generated files and nobody modifies it directly, so the order is not a big deal ;)

> I wonder if this python script could be modified to sort entries by language as usual, otherwise maybe using bash for this.

Just looked into the script. It's actually a Perl script [1] instead of Python. I know little about Perl, and bash is too hard for me :/

> Testing manually I happened to see that qterminal is different (no single .desktop file and has also an option) and screengrab's original desktop.file misses a lot of Name= ...

If the script from deepin is not good, I'd like to create another script from scratch for LXQt, preferably in Python or bash. That prevents dependency on an external project, too.

> I've little time atm

Same for me. No hurry :)

[1] https://github.com/linuxdeepin/deepin-gettext-tools/blob/master/src/desktop_ts_convert.pl

**Comment by stefonarch** [comment]
Found some time  and I think with this bash script it's possible to parse the *.ts files and generate the foo.desktop file, only piece missing is inserting desktop.in at the beginning and probably getting `$NAME` in another way, this is for the lxqt-menu folders.

```
#!/bin/bash
for file in ts_files/*
	do
		NAME=${PWD##*/} 
		language=$(cat $file | grep -o -P '(?<=language=\").*(?=\"\>)')
	
		cat $file |grep -oP '(?<=translation>)[^<]+' | sed -n 2p | sed 's/^/Name['$language']=/' >> /tmp/$NAME.desktop
		cat $file |grep -oP '(?<=translation>)[^<]+' | sed -n 3p | sed 's/^/GenericName['$language']=/' >> /tmp/$NAME.desktop
		cat $file |grep -oP '(?<=translation>)[^<]+' | sed -n 1p | sed 's/^/Comment['$language']=/' >> /tmp/$NAME.desktop
	done

```

**Comment by stefonarch** [comment]
I went over all *.ts files, this perl script has some defects (doubled lines, random ordered  and missing closing tag for type="untranslated", with help from bash I reformatted and corrected all files by now.

example:
```

<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1" language="es"><context><name>desktop</name><message><location filename="Desktop Entry]GenericName" line="0"/><location filename="Desktop Entry]Name" line="0"/><source>Hibernate</source><translation>Hibernar</translation></message><message><location filename="Desktop Entry]Comment" line="0"/><source>hibernate the machine</source><translation>Hibernar el sistema</translation></message></context></TS>

```
is now:
```
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1" language="es">
<context>
<name>Desktop Entry</name>
    <message>
      <location filename="Desktop Entry/Name" line="0"/>
      <source>Hibernate</source>
      <translation>Hibernar</translation>
    </message>
    <message>
      <location filename="Desktop Entry/GenericName" line="0"/>
      <source>Hibernate</source>
      <translation>Hibernar</translation>
    <message>
      <location filename="Desktop Entry/Comment" line="0"/>
      <source>hibernate the machine</source>
      <translation>Hibernar el sistema</translation>
    </message>
</context>
</TS>

```

At this point parsing should be easy, with a script in bash as above (all I can do) or cmake.
We could parse them to single desktop files for each language as they are used during compiling now, no other changes needed then, or parse the desktop*.ts files directly to the foo.desktop file (cleaner solution IMHO).

Qterminal is an exception, to look at properly, 2 desktop files and one containing the dropdown action too.

**Comment by yan12125** [comment]
Thanks a lot for the efforts! So, with that bash script (with improvements for actions?), deepin's script is not needed for those who build lxqt from sources? If so, I think "parse them to single desktop files for each language as they are used during compiling now" is still a good approach.

**Comment by stefonarch** [comment]
I was fighting some issues with lxqt-leave and archiver:
Both have the same source for 2 of the three entries, and weblate complained about each file.
So for those there is needed a different or improved script, or changing *.desktop.in making lines differ.

Lxqt-leave display "Comment" as tooltip while all other menu entries display "GenericName".

> I think "parse them to single desktop files for each language as they are used during compiling now" is still a good approach.

Not sure, the above script parse all  to a complete desktop file (lacks only find and include  *.desktop.in), and the *.desktop files should never be modified manually because *.ts files and weblate  don't take those changes automatically. So I'd prefer having only *.ts files around.

**Comment by yan12125** [comment]
Well, I should have said "parse `*.ts` to generate `*.desktop.in` for each language with a bash script". With this approach, both git and Weblate manage only `*.ts` files.

I haven't had time to look into issues in individual components, though. Anyway, we could start migrating some components with the current plan.

**Comment by stefonarch** [comment]
No idea how cmake builds $name.desktop, tried to look at some files but it's arabic to me :) 
$name.desktop.in contains the "header" and english source.

**Comment by stefonarch** [comment]
Finally my idea is to keep the actual building system with *.desktop files for each language.
All files are in foo/translations:
```
foo_xy.desktop
desktop-xy.ts
foo_xy.ts # translation of the component config or else
```
Lacks to figure out how making cmake calling this script in the lxqt-component directory before building foo.desktop:
```

#!/bin/bash

for file in translations/desktop_*.ts
	do
		Component=${PWD##*/} 
		language=$(cat $file | grep -o -P '(?<=language=\").*(?=\"\>)')
		echo "# Do not edit, file generated by lxqt-ts2desktop. Please edit only desktop_*.ts files in LXQt-Weblate or Qt-Linguist" >  translations/$Component"_"$language.desktop
  	        cat $file |grep -oP '(?<=translation>)[^<]+' | sed -n 1p | sed 's/^/Name['$language']=/' >> translations/$Component"_"$language.desktop
		cat $file |grep -oP '(?<=translation>)[^<]+' | sed -n 2p | sed 's/^/GenericName['$language']=/' >>  translations/$Component"_"$language.desktop
		cat $file |grep -oP '(?<=translation>)[^<]+' | sed -n 3p | sed 's/^/Comment['$language']=/' >>  translations/$Component"_"$language.desktop
	done

```

**Comment by stefonarch** [comment]
Looks working fine now here, cmake rewrites all single `foo_xy.desktop` files based on` desktop_xy.ts` files:
https://github.com/stefonarch/lxqt-admin/tree/ts2desktop
needs  
https://github.com/stefonarch/lxqt-build-tools/tree/ts2desktop
(script is a working draft atm)

qterminal, lxqt-leave and lxqt-archiver need  a different approach, for archiver I made a [PR](https://github.com/lxqt/lxqt-archiver/pull/204).

**Comment by palinek** [comment]
Finally I had a look into this topic. Do we really need the .ts here?
How about using .json? It is supported by weblate (https://www.i18next.com/misc/json-format) and we can directly process the files by `cmake` (https://cmake.org/cmake/help/latest/command/string.html#json) in https://github.com/lxqt/lxqt-build-tools/blob/master/cmake/modules/LXQtTranslateDesktop.cmake#L71

**Comment by stefonarch** [comment]
> Do we really need the .ts here?
> How about using .json?

I stumbled upon this deepin script to  convert the exiting .desktop files to .ts files and back, no idea if a similar tool exists for .desktop to .json

**Comment by stefonarch** [comment]
kservice's desktoptojson is quite unusable IMO:
```
$ desktoptojson -i lxqt-about_it.desktop -o lxqt-about_it.json         
Unknown property type for key "GenericName[it]" -> falling back to string
Generated  "lxqt-about_it.json"

$ cat lxqt-about_it.json                                         
{
    "GenericName[it]": "Informazioni su LXQt",
    "KPlugin": {
        "Description[it]": "Informazioni sull'ambiente grafico LXQt",
        "Name[it]": "Informazioni su LXQt"
    }
}

$ desktoptojson -i /usr/share/applications/lxqt-about.desktop  -o /tmp/test.desktop
Unknown property type for key "GenericName" -> falling back to string
Unknown property type for key "Categories" -> falling back to string
Unknown property type for key "OnlyShowIn" -> falling back to string
Unknown property type for key "GenericName[ar]" -> falling back to string
Unknown property type for key "GenericName[ca]" -> falling back to string
Unknown property type for key "GenericName[cs]" -> falling back to string
...
```

**Comment by yan12125** [comment]
For translators on Weblate using `*.ts` or `*.json` may be indistinguishable, but using `*.ts` for desktop files allows translators not on Weblate to continue to use their favorite tool.

**Comment by palinek** [comment]
Ok..I dived into it... and after several attempts I ended up with using YAML for the translated desktop files.

Generation of final .desktop file is updated in lxqt/lxqt-build-tools#59 and example of repo using it is in lxqt/lxqt-about#158.

@stefonarch @yan12125 Could you have a look if configuring YAML translations (https://docs.weblate.org/en/latest/formats.html#yaml-files) can be achieved for some example repo?

**Comment by stefonarch** [comment]
Well, I worked quite a lot for having well formatted .ts files for all components, if you dived into it earlier...

But not having single .desktop_xy.files around is a  better solution.
People could edit the yaml files also manually eventually making PR without problems.

Merge this and we try it out in weblate?

**Comment by stefonarch** [comment]
In weblate we can import also branches, trying out now.
![schermata-13-18-26-56](https://user-images.githubusercontent.com/10681413/99102106-e7aff280-25dd-11eb-82fb-3b1e695481fb.png)

**Comment by tsujan** [comment]
This page is about having identical extensions and translation methods; isn't it? `.ts` can be handled by Qt Linguist (offline) and Weblate (online) alike.

**Comment by yan12125** [comment]
> Do we really need the .ts here?

Is there anything wrong with ts files? Besides allowing users to choose their favorite translation tool, sticking with the TS format also allows putting translations for the application and desktop files in a single file. That allows managing desktop translations without creating additional Weblate components. There are already many Weblate components and I consider it a maintenance burden.

**Comment by stefonarch** [comment]
In the mean time I see that import of this branch isn't possible for several reasons.
* lack of original file with sources https://docs.weblate.org/en/weblate-4.2.1/admin/projects.html#monolingual-base-language-file
So weblate has no idea about source text.
* lack of template for new files

Actual  yaml files are wrong too:
```
weblate:
  Name: "Acerca de LXQt"
  GenericName: "Acerca de LXQt"
  Comment: "Saber más acerca LXQt"
```
For translating it should be in this format: https://docs.weblate.org/en/latest/formats.html#yaml-files
```
weblate:
  About LXQt: "Acerca de LXQt"
  Learn more about LXQt": "Saber más acerca LXQt"
```
Then there will be also  issues with 2 liners like lxqt-about and normal 3 liners with 3 different sources.

> sticking with the TS format also allows putting translations for the application and desktop files in a single file. That allows managing desktop translations without creating additional Weblate components.

 I don't think a single file can work, because translations end up as *.xy.qm files while desktop entries will be a text file.

I've done most for the ts.files, sure it needs a bash script afaik, it would be possible also to use a similar script to  generate directly <component>.desktop without keeping the single desktop files around  for each language. So in /translations would be only .ts files of 2 types.

**Comment by stefonarch** [comment]
Didn't think of it, testing my PR for lxqt-archiver in weblate:
https://translate.lxqt-project.org/projects/lxqt-desktop/lxqt-archiver-menu-entry/

**Comment by palinek** [comment]
> lack of original file with sources

I updated the PR to include also the base.

> Actual yaml files are wrong too:

I don't think so... I tried to configure the lxqt-about as new component for nm-tray in hosted.weblate.org... and seems to work as a charm -> https://hosted.weblate.org/projects/nm-tray/desktops-test/

**Comment by stefonarch** [comment]
You're right, all works now:
https://translate.lxqt-project.org/projects/lxqt-desktop/lxqt-about-menu-entry/

**Comment by yan12125** [comment]
> I don't think a single file can work, because translations end up as *.xy.qm files while desktop entries will be a text file.

Yes! So two commands will be used to genete `*.qm` and desktop files, respectively. Also, the lupdate step needs to be augmented with one more step for injecting entries for desktop files after `*.ts` are updated.

**Comment by stefonarch** [comment]
I've to admit that @palinek 's approach is _cleaner_ than mine, so I'd say better use the yaml files.
Needs to check how to implement this approach in 
* lxqt-session/lxqt-leave/
* qterminal
* panel (for plugins)

**Comment by palinek** [comment]
> Well, I worked quite a lot for having well formatted .ts files for all components, if you dived into it earlier...

I see, I'm sorry for that...but you may build on top of that knowledge in the future..

**Comment by stefonarch** [comment]
Sure, I've had fun and learned a lot, as you may know I'm not at all a programmer.

**Comment by palinek** [comment]
> Needs to check how to implement this approach in
>
> - qterminal

Updated the logic... to handle multiple sections..

**Comment by stefonarch** [comment]
Merged qterminal for testing, looks good.

Probably it's better  having menu entries and translations together in the same project, eliminating "LXQt Menu files", otherwise all repositories will be doubled. Importing is also easier, "from existing component"

https://translate.lxqt-project.org/projects/lxqt-desktop/

To verify if true (for adding informations for translators):

* All menu entries display "GenericName" as tooltip, except "LXQt-Leave which displays "Comment"
* Comments are really nowhere displayed? I suppose runner is searching them.

**Comment by stefonarch** [comment]
Looks working for lxqt-archiver, but weblate still pushed the empty template today  and didn't commit inserted strings before, changed setting from 24h to 1h for locat commit.

**Comment by stefonarch** [comment]
Something is still strange with LXQtBot which replies to itself to the normal push email:
`Re: [lxqt/lxqt-archiver] Translations update from Weblate (#209)`
and creates those commits:
https://github.com/lxqt/lxqt-archiver/commit/8aa0e288db83752e889749bd354cad92497cd48f
Any idea what's happening here @yan12125 ?

**Comment by yan12125** [comment]
Are those mails sent by Weblate or GitHub? If those are from GitHub, it seems a normal case as Weblate updates a branch when there are new translations.

**Comment by stefonarch** [comment]
Those are sent by the bot, but have Re: in the subject and refer to those out-of-any-branch commits.
The last push for qterminal .yaml file (and other *.ts) went smooth now, just sit and wait to see if it happens again.

**Comment by yan12125** [comment]
> refer to those out-of-any-branch commits.

Those commits are not reachable from current branches as GitHub rewrites commits (creates new commits with the same changes under the hood) when you merge a pull request by rebase or squash. If I'm correct, https://github.com/lxqt/lxqt-archiver/commit/8aa0e288db83752e889749bd354cad92497cd48f was on https://github.com/LXQtBot/lxqt-archiver/tree/weblate-lxqt-desktop-lxqt-archiver before https://github.com/lxqt/lxqt-archiver/pull/209 is merged. Anyway that branch contains a different commit now as Weblate pushes new translation to the same branch.

> Those are sent by the bot

Then I have no ideas :/

**Comment by stefonarch** [comment]
And all those in every repo: https://github.com/lxqt/lxqt-about/pull/158
