### ISSUE TITLE
Panel graphical artifacts on Network Manager Applet icon

### ISSUE THREAD

**Issue by LonCJr** [lxqt/lxqt#106]
Manjaro 64-bit 3.14 Kernel 
Nvidia GT430 Nvidia 331.67 drivers
Faenza icon theme
<a href="http://www.imagebam.com/image/23e767326027754" target="_blank"><img src="http://thumbnails109.imagebam.com/32603/23e767326027754.jpg" alt="imagebam.com"></a> 

Appears to be purely cosmetic and doesn't affect function of NMApplet.  Artifacts appear on the right and bottom and change each time the menu is opened or a mouseover tooltip is drawn.

**Comment by mdeneen** [comment]
I get this with hexchat as well.  http://i.imgur.com/9L6lMHp.png

This is running the latest available from the AUR.

**Comment by JohnnyComeL8ly** [comment]
Hi, I'm using the Oxygen icon set, and I have a similar problem.
![2015-03-17-125235_45x53_scrot](https://cloud.githubusercontent.com/assets/9731801/6854743/13a8b8a6-d3c1-11e4-82ca-0e22a94afdb6.png)


[cmd-output]
john@Ciderpress:~$ nm-applet

** (nm-applet:3327): WARNING **: Error retrieving accessibility bus address: org.freedesktop.DBus.Error.ServiceUnknown: The name org.a11y.Bus was not provided by any .service files
nm-applet-Message: using fallback from indicator to GtkStatusIcon

(nm-applet:3327): GLib-GObject-WARNING **: /build/buildd/glib2.0-2.42.1/./gobject/gsignal.c:3101: signal id '191' is invalid for instance '0x115f310'

(nm-applet:3327): GLib-GObject-WARNING **: /build/buildd/glib2.0-2.42.1/./gobject/gsignal.c:3101: signal id '191' is invalid for instance '0x115f310'

(nm-applet:3327): GLib-GObject-WARNING **: /build/buildd/glib2.0-2.42.1/./gobject/gsignal.c:3101: signal id '191' is invalid for instance '0x115f310'

(nm-applet:3327): GLib-GObject-WARNING **: /build/buildd/glib2.0-2.42.1/./gobject/gsignal.c:3101: signal id '191' is invalid for instance '0x115f310'

(nm-applet:3327): GLib-GObject-WARNING **: /build/buildd/glib2.0-2.42.1/./gobject/gsignal.c:3101: signal id '191' is invalid for instance '0x115f310'

(nm-applet:3327): GLib-GObject-WARNING **: /build/buildd/glib2.0-2.42.1/./gobject/gsignal.c:3101: signal id '191' is invalid for instance '0x115f310'

(nm-applet:3327): GLib-GObject-WARNING **: /build/buildd/glib2.0-2.42.1/./gobject/gsignal.c:3101: signal id '191' is invalid for instance '0x115f310'

(nm-applet:3327): GLib-GObject-WARNING **: /build/buildd/glib2.0-2.42.1/./gobject/gsignal.c:3101: signal id '191' is invalid for instance '0x115f310'

(nm-applet:3327): GLib-GObject-WARNING **: /build/buildd/glib2.0-2.42.1/./gobject/gsignal.c:3101: signal id '191' is invalid for instance '0x115f310'

(nm-applet:3327): GLib-GObject-WARNING **: /build/buildd/glib2.0-2.42.1/./gobject/gsignal.c:3101: signal id '191' is invalid for instance '0x115f310'

(nm-applet:3327): GLib-GObject-WARNING **: /build/buildd/glib2.0-2.42.1/./gobject/gsignal.c:3101: signal id '191' is invalid for instance '0x115f310'

(nm-applet:3327): GLib-GObject-WARNING **: /build/buildd/glib2.0-2.42.1/./gobject/gsignal.c:3101: signal id '191' is invalid for instance '0x115f310'

(nm-applet:3327): GLib-GObject-WARNING **: /build/buildd/glib2.0-2.42.1/./gobject/gsignal.c:3101: signal id '191' is invalid for instance '0x115f310'
[/cmd-output]

It just keeps going with that type of thing... the hex # in single quotes changes though, when you restart it by "pkill"-ing it, then executing it. (I think that is supposed to happen....)

**Comment by RalfJung** [comment]
I am seeing similar artifacts with the liferea RSS reader's tray icon. This is a try icon that KDE's xembed-sni-proxy has trouble with, too.

**Comment by RalfJung** [comment]
I noticed something potentially interesting: If I restart the panel, the tray icons of NetworkManager and Liferea come up correctly. (That is, if they do come up. Sometimes tray icons get lost when I restart the panel.) So, somehow, it seems like LXQt can get the image correctly when it sees the icon already while starting, but not when it changes later...?

**Comment by maces** [comment]
For me changing and then setting back the icon theme through LXQt appearance settings fixes the artefacts.

**Comment by RalfJung** [comment]
Actually, just opening the panel configuration is already enough. (Or, it was enough two times.)

**Comment by YamashitaRen** [comment]
This bug make some systrays like uim-toolbar-gtk(3)-systray almost unusable. (You see artifacts instead of the selected input method.)
I confirm @maces workaround. Though, in my case, the bug comes back as soon as I change the input method again.
I had similar artifacts with BMDC++ gtk3 tray, but I never really cared until today.

**Comment by RalfJung** [comment]
Things seem to have gotten much better with the update to GTK 3.20. The actual icon is now legible, only the rightmost column of the NM icon still sometimes shows garbage.

**Comment by agaida** [comment]
outdated, closing
