### ISSUE TITLE
Minor issues in the display of the main menu

### ISSUE THREAD

**Issue by GHLieven** [lxqt/lxqt#1092]
LXQt 0.10.0 Ubuntu 16.04

When pointing to a submenu, the submenu displays one or more pixels to low. It occurs with the following built-in themes: dark, ambiance and kde-plasma, and maybe also with frost (I can't tell because there seems to be no menu border). It's most visible with the dark theme, because the menu border is rather thick. See first image.

Also, the highlighting of a menu item stays one pixel off the right border of the menu, leaving a small white line with a width of one pixel. See first arrow in second image.

I don't know if it's intentional or not, but the submenu seems to overlap the main menu with one pixel. See second arrow in second image.

![dark](https://cloud.githubusercontent.com/assets/20442916/16838987/bfa22282-49cc-11e6-8759-12a41a05e8c5.png)
![light](https://cloud.githubusercontent.com/assets/20442916/16839263/82e83d70-49ce-11e6-8d0c-a70d2212e832.png)

**Comment by intialonso** [comment]
I cant reproduce it using the latest code.

**Comment by stefonarch** [comment]
Looking at the screenshot it's 0.10 release (no search in menu).

**Comment by tsujan** [comment]
> I cant reproduce it using the latest code.

Even if it was reproducible, it wouldn't be about a bug. Any theme can give a spacing between the highlighted area and the menu border or have a submenu overlap.

**Comment by pmattern** [comment]
All three findings can be reproduced running latest VCS checkouts on Arch Linux here like in this screenshot (Ambiance)
![lxqt-panel_main-menu-layout-woes](https://cloud.githubusercontent.com/assets/9860801/16868692/54942ab4-4a79-11e6-9ed0-2b529effa5f1.png)
That border right of the highlighting of a submenu item seems to be symmetric and as such alright, IMO.
But even that aside I'd personally consider this a really minor issue. Didn't even notice so far.

**Comment by intialonso** [comment]
Yes, the true is that the main menu is a little difficult to style. the icons and arrows are problematic. I will take a look to see if I can make this better.

**Comment by GHLieven** [comment]
Thanks for taking a look at it, intialonso. I reported this because I appreciate working in a good looking desktop environment. If it looks a bit awkward, it's not such a joy to use.
