### ISSUE TITLE
Crash upon exiting session

### ISSUE THREAD

**Issue by pmattern** [lxqt/lxqt#1115]
Since some weeks lxqt-globalkeysd is sporadically crashing and dumping core upon exiting LXQt sessions here.

Aside from the fact that the crashes happen upon exiting sessions I failed to figure out the conditions making them take place. It is definitely not necessary to tweak any settings in `lxqt-config-globalkeyshortcuts`, though.
A relation to lxde/lxqt-globalkeys@b7ca76e seems likely. The commit introduces changes affecting D-Bus which is involved according to backtrace and stack trace which can be found in [this Gist](https://gist.github.com/pmattern/d23018a76896912267aa64846e294039) and the problem started right after installing this commit.

Up to date Arch Linux x86_64, all LXQt components from recent VCS checkouts.

**Comment by tsujan** [comment]
On Manjaro and with Qt-5.7.0-2, I don't see a crash, although this version of Qt has more bugs than v5.6 (IMO).

No crash on Debian either (Qt-5.6).

**Comment by palinek** [comment]
Does the crash happen also if you start/stop the daemon manualy (e.g. in terminal) or does it occure only when stopping the session?

**Comment by pmattern** [comment]
Within a running LXQt session I could trigger crashes by restarting `lxqt-globalkeysd` several times in a row only. The traces looked somewhat different, though, see [Gist](https://gist.github.com/pmattern/fa9aa5ba2f1603f398b89ff8b4326cfc).

That aside the crash addressed in this issue can only be seen upon exiting the LXQt session. Btw. the latter applies to crashes of Qlipper ([Gist](https://gist.github.com/pmattern/56ff89ecfb23dbe506bdb5dad43670d3), not reported yet) and [RSS Guard](https://github.com/martinrotter/rssguard/issues/22) ([Gist](https://gist.github.com/pmattern/89282f5be04bdf45e1b42fc73b312db3)), too.

**Comment by agaida** [comment]
can't reproduce this anymore
