### ISSUE TITLE
lximage-qt: sorting order menu access

### ISSUE THREAD

**Issue by Vladimir-csp** [lxqt/lxqt#1116]
Currently to change sorting order in lximage-qt one has to enable thumbnails and use context menu in that area.
Sorting order is a basic feature, so it should be accessible from one of the main menus, "View" or "Go".

BTW:  Thumbnail context menu has unneeded generic FM items, like "Create new", "Open", "Folder Properties" "Folder first".

**Comment by tsujan** [comment]
→ https://github.com/lxqt/lximage-qt/issues/23
