### ISSUE TITLE
lximage-qt: keyboard shortcuts

### ISSUE THREAD

**Issue by Vladimir-csp** [lxqt/lxqt#1118]
Please allow editing keyboard shortcuts.

Also some defaults to consider:
up/down: zoom in/out
1-9: 1x-9x scale
Shift+2-Shift+9:  0.75-0.1 scale
0: scale to fit.

**Comment by pierrenopicnic** [comment]
this patch let you zoom in and out with the wheelmouse 

I tink getting next/previous file with the wheelmouse is kind of wierd.... plus when you have a lot of files it's buggy!!

 
`diff --git a/src/mainwindow.cpp b/src/mainwindow.cpp
index 16191d9..674688e 100644
--- a/src/mainwindow.cpp
+++ b/src/mainwindow.cpp
@@ -461,9 +461,9 @@ bool MainWindow::eventFilter(QObject* watched, QEvent* event) {
         if(wheelEvent->modifiers() == 0) {
           int delta = wheelEvent->delta();
           if(delta < 0)
-            on_actionNext_triggered(); // next image
+            on_actionZoomOut_triggered(); // zoomout
           else
-            on_actionPrevious_triggered(); // previous image
+            on_actionZoomIn_triggered(); // zoomin
         }
         break;
       }
`

**Comment by tsujan** [comment]
Good report but → https://github.com/lxqt/lximage-qt/issues/293#issuecomment-561002760
