### ISSUE TITLE
[Feature Request] app menu bar in window header

### ISSUE THREAD

**Issue by Gibbz** [lxqt/lxqt#1121]
I would love to see an option like ubuntu where the windows title contains the menu bar for the app. This saves screen space.
The window title is displayed, then when the mouse is hovered over the title bar, it switched to the menu bar.
A real saver for netbooks and low resolution devices!

**Comment by palinek** [comment]
I'm not sure how this can be doable in window manager agnostic way as window decorations are handled by window manager.

Is there any X11 or wayland spec, how the menu/actions can be propagated to WM?

**Comment by tsujan** [comment]
@palinek I'd once considered the same problem (with Kvantum) and couldn't find an implementation method independent of WM.

It would be really nice if LXQt had its own Qt5 WM so that such features could be implemented for it. But there is still the "wayland-will-come-soon" problem ;)

**Comment by jensreu** [comment]
We have some work on it in KDE land, or at least some thought on it which all ground down to "In Wayland it will be a totally different problem AND it's tricky to make it work for GTK and Qt apps (which would be a prerequisite)".
If someone from the Lxqt team wants to look at it with us Kai Uwe Broulik is the guy to talk to

**Comment by Gibbz** [comment]
plasma 5.9 with kwin has added something like this, but with a menu instead of integrated with the window title. Maybe its possible to see how they're doing that?

**Comment by tsujan** [comment]
LXQt is WM-agnostic and this report was about WM, not LXQt.
