### ISSUE TITLE
Add consistent minimum versions to our CMakeLists.txt

### ISSUE THREAD

**Issue by agaida** [lxqt/lxqt#1150]
in every package

**Comment by luis-pereira** [comment]
- [ ] libqtxdg https://github.com/lxde/libqtxdg/pull/107

**Comment by tsimonq2** [comment]
Bump, what else needs to happen for this to be done? 

Are there any more packages that need this added?

**Comment by agaida** [comment]
with having the minimum versions for Qt and glibc in lxqt-build-tools this is not so important any more. But it would be nice to have.

**Comment by agaida** [comment]
i was wrong - it's a must have

**Comment by agaida** [comment]
Right now it's a bit messed up - hard to grep

set(QT_MIN_VERSION "5.10.0")
set(REQUIRED_QT_VERSION "5.7.1")
set(QT_MINIMUM_VERSION "5.6.1")
set(QT_MINIMUM_VERSION "5.7.1")
set(REQUIRED_QT_VERSION "5.7.1")
set(REQUIRED_QT_VERSION "5.7.1")
set(QT_MINIMUM_VERSION "5.7.1")
set(QT_MIN_VERSION "5.4.0")

set(KF5_MIN_VERSION "5.25")
set(KF5_MIN_VERSION "5.36.0")

set(LXQTBT_MINIMUM_VERSION "0.5.0")
set(LXQTBT_MINIMUM_VERSION "0.5.0")
set(LXQTBT_MINIMUM_VERSION "0.5.0")
set(LXQTBT_MINIMUM_VERSION "0.5.0")
set(LXQTBT_MINIMUM_VERSION "0.5.0")
set(LXQTBT_MINIMUM_VERSION "0.5.0")

set(LIBFM_QT_MINIMUM_VERSION "0.14.0")
set(LIBFM_QT_MINIMUM_VERSION "0.14.0")
set(LIBFM_QT_MINIMUM_VERSION "0.14.0")
set(LIBFMQT_MINIMUM_VERSION "0.14.0")

set(REQUIRED_MENUCACHE_VERSION "1.1.0")
set(QTERMWIDGET_MINIMUM_VERSION "0.14.0")

**Comment by agaida** [comment]
#### List of needed versions in lxqt-build-tools
* lxqt-build-tools

#### Minimum versions in projects
* libfm-qt
* liblxqt 
* libqtxdg 
* libsysstat
* lximage-qt
* lxqt-about
* lxqt-admin
* lxqt-archiver
* lxqt-branding  
* lxqt-config
* lxqt-connman-applet
* lxqt-globalkeys
* lxqt-notificationd
* lxqt-openssh-askpass 
* lxqt-panel
* lxqt-policykit 
* lxqt-powermanagement
* lxqt-qtplugin
* lxqt-runner 
* lxqt-session 
* lxqt-sudo
* lxqt-themes
* obconf-qt 
* pavucontrol-qt
* pcmanfm-qt 
* qps
* qterminal
* qtermwidget
* screengrab

**Comment by agaida** [comment]
Done
