### ISSUE TITLE
[liblxqt] Remove XDG_CONFIG_DIRS workaround

### ISSUE THREAD

**Issue by palinek** [lxqt/lxqt#1158]
The proper implementation was merged to Qt (qt/qtbase@ee35fbb, qt/qtbase@4758555). 

Opening this to not forget to remove our homemade [workaround](/lxde/liblxqt/commit/b1b249e5e7aa7f85dd929ae4d0d32b50316aa774) when the Qt patches are released to some "widespread" Qt version.

ref. #250, #349, #385

**Comment by paulolieuthier** [comment]
Great work! Your patches will go in Qt 5.8, right?

**Comment by palinek** [comment]
> Your patches will go in Qt 5.8, right?

I realy have no clue how are the commits ported to particular version. Sometimes the reviewers change the destination version instantly ...but it wasn't the case this time.

**Comment by luis-pereira** [comment]
Will 5.8 be our minimum required qt versions for 0.12 ?

**Comment by paulolieuthier** [comment]
Probably, IMO.

**Comment by agaida** [comment]
@luis-pereira adn @paulolieuthier  - if you want LXQt Arch only - maybe. And please don't forget that 5.6 will be a long term version. 5.8 would take debian, ubuntu and all derivaties out of the game - dunno about the plans of other majors.

**Comment by paulolieuthier** [comment]
@agaida when do you believe 5.8 would reach Debian land?

**Comment by tsujan** [comment]
And what about Ubuntu-LTS? Do we want to deprive its users of the latest LXQt?!

**Comment by palinek** [comment]
> Will 5.8 be our minimum required qt versions for 0.12 ?

I've added this to next milestone just to have it on eyes.... it can (and probably will) be posponed before the 0.12 release..

**Comment by agaida** [comment]
after the freeze maybe - will ask in #d-qt-kde, don't know their plans

**Comment by agaida** [comment]
@tsujan - LTS and bleeding edge don't work well together

**Comment by tsujan** [comment]
@agaida 

> LTS and bleeding edge don't work well together

I have no problem with that (being on Manjaro).

I've installed an LTS on virtualbox to check Kvantum and FeatherPad in it because, IMO, using LTS shouldn't prevent benefiting from bleeding edge *as far as possible*. And I saw that libfm-qt respects older Qt5 too. But it's OK.

**Comment by palinek** [comment]
> IMO, using LTS shouldn't prevent benefiting from bleeding edge as far as possible.

In environment with the new Qt (including the XDG_.. patches) the workaround will be disabled and in environments with the "old" Qt we will use the workaround (just a simple #if like e.g. `#if QT_VERSION < QT_VERSION_CHECK(5, 8, 0)`. 

So there will be "no problem" with usage on LTS (as the required minimum Qt version is now 5.4).

**Comment by agaida** [comment]
@palinek - and this is exactly the point: we had to do some version checks - but if we check for Qt <= 5.6 we shouldn't set minimum Qt version to 5.8 - that would make these tests senseless. So i really don't see 5.8 as minimum in near future - we can use some of the shiny new things and have a big #if then mess :)

**Comment by agaida** [comment]
@tsujan: right now there would be no big problems - but please remember the life cycle of a LTS - if we want to support it right now we must make sure that our code compile and run on 16.04 at least until end of 2018 (and hope that the LTS LXQt users switch to the next LTS short after the release of new LTS)

**Comment by tsujan** [comment]
@agaida, Yes, I know. That's why I italicized "as far as possible".

**Comment by paulolieuthier** [comment]
@agaida OK, I've never used a LTS and didn't recall its cycle was of 2 years.

**Comment by agaida** [comment]
@paulolieuthier - the release cycle is two years, EOL is after three years for desktop editions and five years for server editions afaik.

**Comment by tsujan** [comment]
> @agaida OK, I've never used a LTS and didn't recall its cycle was of 2 years.

Me neither. Linux becomes old after 6 months, ancient after a year, and nostalgic after 2 years ;)

**Comment by pmattern** [comment]
Not following here.
As for LTS distributions it must be ensured that the LXQt components *they feature* can be maintained during their lifecycle. But in our last release we've created release branches for exactly this purpose and obviously Qt version bumps will not happen in these branches.
On the other hand we cannot seriously freeze the Qt version in master during the lifecycle of all those LTS distributions.
So why shouldn't we bump the Qt version *in master* right now already?

On a different note something that should definitely be avoided is requiring Qt version in master which aren't widely available in distributions yet.
Compiling Qt is PITA so requiring versions like this in master represents a serious limitation to testing.

**Comment by agaida** [comment]
we can bump it to 5.6, not higher

**Comment by luis-pereira** [comment]
> In environment with the new Qt (including the XDG_.. patches) the workaround will be disabled and in environments with the "old" Qt we will use the workaround (just a simple #if like e.g. #if QT_VERSION < QT_VERSION_CHECK(5, 8, 0).

>So there will be "no problem" with usage on LTS (as the required minimum Qt version is now 5.4).

That's the way to go.

**Comment by luis-pereira** [comment]
> we can bump it to 5.6, not higher

But only if needed, IMO.

**Comment by palinek** [comment]
Just FYI... I've got a reply about including in particular version from Qt guys:
`It's a new feature, that's why it is in 5.9 and doesn't apply to 5.8.` ... so the will not be even in the 5.8.

**Comment by agaida** [comment]
@luis-pereira right
@palinek erm, solved for now i think :(

**Comment by tsimonq2** [comment]
Qt 5.9.0 RC is landing in Debian Experimental bit-by-bit, and soon after, 5.9.0 final release. Following should be landing in Ubuntu Artful, if all goes well.

Seeing as it's starting to land and the commit doing this in liblxqt has landed, in my opinion we can revisit this issue once we have determined that everybody is using Qt 5.9.0 at the minimum.

**Comment by shlyakpavel** [comment]
Is this still relevant?

**Comment by tsujan** [comment]
> Is this still relevant?

It doesn't seems so.
