### ISSUE TITLE
shortcuts in colorpicker-plugin not working

### ISSUE THREAD

**Issue by stefonarch** [lxqt/lxqt#1160]
Selecting the color code all items in right click popup get activated, but not one of the indicated shortcuts works, only clicking the item does.
![schermata16 png](https://cloud.githubusercontent.com/assets/10681413/18932525/2c2e0b2e-85d1-11e6-9f5f-8c6833fc3750.jpg)

**Comment by pmattern** [comment]
Confirmed as depicted above running lxde/lxqt-panel@026638b on Arch Linux.

**Comment by stefonarch** [comment]
Works now all, has to be selected first.
