### ISSUE TITLE
keyboard indicator: add an option to display country flag

### ISSUE THREAD

**Issue by alex3kov** [lxqt/lxqt#1162]
... instead of two-letter indicators like "US" or "RU". When you switch between languages a lot, colorful flag is much easier to check.

**Comment by arisboch** [comment]
No change after more than two years?!

**Comment by tieugene** [comment]
> No change after more than two years?!

https://github.com/lxqt/lxqt-panel/pull/223

**Comment by agaida** [comment]
provide code and it will change - so it seems nobody really want this or care of it.

**Comment by tsujan** [comment]
It's as simple as this: a contributor who's motivated enough to add codes for flags is needed. Apparently, no LXQt dev has seen it worth the effort -- me included (I dislike flags on my panel).

**Comment by palinek** [comment]
Some dirty basic implementation is in lxqt/lxqt-panel#1282 ...

**Comment by stefonarch** [comment]
I tried compiling from master, it stops randomly now, as here

> /usr/include/qt/QtCore/qshareddata.h:184:59: error: invalid use of incomplete type ‘class XdgMimeTypePrivate’
> 
> note: forward declaration of ‘class XdgMimeTypePrivate’

up-to date arch
