### ISSUE TITLE
Wallpaper settings should treat multiple screens correctly

### ISSUE THREAD

**Issue by v-fox** [lxqt/lxqt#1175]
Right now multiple screens are treated as single giant one so wallpaper is disgustingly stretched on them. Normally it should mimic [nitrogen](https://github.com/l3ib/nitrogen) and:
- have option to stretch on entire screen space or treat each screen separately;
- allow setting separate wallpapers for each screen.

It also would be useful to mimic old "desktop cube" feature with [separate wallpapers for each virtual screen](https://forum.kde.org/viewtopic.php?f=17&t=117730). Although it seems that KDE in its newest iteration of degradation (4->5) has [removed that option](https://bugs.kde.org/show_bug.cgi?id=343246) but there is some "[movement](https://bugs.kde.org/show_bug.cgi?id=341143#c167)".

**Comment by tsujan** [comment]
One of the differences between LXQt and other DE's is that it's highly modular. For example, it works with kwin, Openbox and Compiz alike. The first problem that comes to my mind is that, for example, with Openbox, we have multiple virtual desktops but with Compiz, there's only one desktop but multiple viewports. Therefore, if this is possible at all, it won't work under all circumstances and will be against modularity.

**Comment by v-fox** [comment]
Yep, and this is why I used nitrogen instead of pcmanfm but it doesn't work under kwin and xcompmgr is barely alive. However, since on newest kwin 5.8.0 update its OpenGL rendering got broke on my system, I'm already regretting that. Kwin's windows managing and effects options and GUI for them are quite useful... when they work.

kwin and openbox seems to be on parity on virtual desktop side under LXQt but Compiz never worked for me after it got "merged" with Beryl. In fact, only Beryl ever worked for me right. If I'm not mistaken, Compiz nowadays is only maintained for Gnome 3, not sure if LXQt would ever be able to deal with it reliably.

I guess, how LXQt could approach that depends on what WM and compositor it suggests as the main one. On X compositor is unnecessary but with Wayland it's mandatory, is it not ? So, it would depend on how LXQt is going to handle Wayland.
By the way, as of now I'm able to launch working kwin_wayland/Xwayland LXQt session via `dbus-launch kwin_wayland --xwayland --exit-with-session startlxqt` in console but if launched from any DM that way it can't logout and is limited to 1024x768 box on the screen for some reason. It also hates QT_QPA_PLATFORM=wayland-egl and wants xcb but Qt apps may have visual glitches on menus without that variable.

**Comment by tsujan** [comment]
> kwin and openbox seems to be on parity on virtual desktop side under LXQt but Compiz never worked for me after it got "merged" with Beryl.

kwin is still buggy here (leaves coredumps on log-out and...). Openbox+Compton works fine. This Compiz also works fine here (I'm using it now): https://github.com/compiz-reloaded. Sometimes I also use LXQt minus its panel and desktop under Enlightenment just for fun.

As for wayland, I don't know -- I've had no reason to try it before it really becomes the default.

**Comment by v-fox** [comment]
Hm... I though anything besides Ubuntu branch is abandoned but openSUSE packages compiz-reloaded and it worked. And it actually provides exactly that wallpaper functionality really well ! Even has "zoom" scaling. BUT I'm unable to use it because if I set compiz (compiz-manager or fusion-icon that able to reliably launch it) as window_manager in lxqt/session.conf then LXQt tray is garbled up and half of it becomes unclickable. If I set openbox there but launch fusion-icon from autolaunch then tray is fine but compiz'es window placement rules are ignored and startup apps don't go into proper viewport >_< And it starts up really slow, especially with colour management. Also, with compiz textures are washed and blurry with every animation.

It seems kwin's bug is only on setting changes (compositing reinitialization), so I have to use that but then wallpaper-per-cube-side glory is lost.

**Comment by tsujan** [comment]
> if I set compiz (compiz-manager or fusion-icon that able to reliably launch it) as window_manager in lxqt/session.conf then LXQt tray is garbled up and half of it becomes unclickable.

Strange! I don't have that problem here. But I've compiled compiz-reloaded myself. When I want to use Compiz, I put `compiz --replace ccp` in Session Settings → Basic Settings → Window Manager, uncheck Compton in the same dialog, and log out and in. Moreover, I never use fusion-icon.

**Comment by v-fox** [comment]
Maybe not enough stuff in tray ? I have like 16 icons there and some of them take a long time to startup, some have `sleep`-delay in their desktop-files. Maybe that's because they want to draw while compiz halts almost all rendering on the screen and/or the startup of the panel.

**Comment by tsujan** [comment]
I have 6-8 and don't think the number is important. The problem may be in fusion-icon. "compiz --replace" has always been the safest way to start compiz with the session.

Anyway, this thread is about pcmanfm-qt. Let's keep it so!

**Comment by v-fox** [comment]
> I have 6-8 and don't think the number is important. The problem may be in fusion-icon. "compiz --replace" has always been the safest way to start compiz with the session.

I'll take a note on that for the future.

> Anyway, this thread is about pcmanfm-qt. Let's keep it so!

Yeah. But check out compiz' wallpaper + screensaver plugins with rotating cube and hovering windows. That's how the ultimate wallpapering goal looks like ! Add photo ("Photowheel") plugin and cube transparency "on mouse rotation only" for good measure but beware that "General -> Desktop size -> Number of desktops" should be '1' for correct switching with lxqt panel.

**Comment by tsujan** [comment]
> but beware that "General -> Desktop size -> Number of desktops" should be '1' 

That's related to what I said above: one virtual desktop but multiple viewports. Openbox has multiple virtual desktops, each with one viewport. E has one virtual desktop and one viewport but it divides it to multiple desktops somehow (E has its own world). Plasma can have both, I think.

> ... check out compiz' wallpaper + screensaver plugins with rotating cube and hovering windows. That's how the ultimate wallpapering goal looks like !

I've always liked Compiz vey much because it's both practical and beautiful. It'll be a shame if we couldn't have a wayland-based Compiz. Fortunately, Plasma will work with wayland.

I think my point is clearer now: pcmanfm-qt can't cover this diversity.

**Comment by v-fox** [comment]
> Openbox has multiple virtual desktops, each with one viewport. E has one virtual desktop and one viewport but it divides it to multiple desktops somehow (E has its own world). Plasma can have both, I think.
> I think my point is clearer now: pcmanfm-qt can't cover this diversity.

What a mess ! But is it really that much work to detect if there are multiple viewports and draw on them and otherwise handle virtual desktops ? lxqt-panel seems to always represent the correct ones unless there are multiple of both.
I guess it is if even KDE devs can't seem to come up with a clean solution of that for years. But then again, when did they for the last 5-8 years ?

> I've always liked Compiz vey much because it's both practical and beautiful. It'll be a shame if we couldn't have a wayland-based Compiz. Fortunately, Plasma will work with wayland.

And even if it is right now. As I wrote before, when completing support of Wayland, LXQt will have to aim for some compositor. Right now kwin_wayland is the most user-friendly and seems to be the only one with that support while openbox doesn't work natively there at all. So, shouldn't pcmanfm-qt adapt for it in the long run ?

Although, I'm not sure that using pcmanfm-qt for wallpapers is a good idea in the first place. But I never use "files on desktop" functionality. I would prefer that being a separate application like nitrogen, panel's "widget" like in Plasma (as much as I hate it) or part of WM as in Compiz. I guess kwin developers figuring that out is the best option for me... as long as it's not part of actual Plasma widgets, "activities" or other weird figment of their imagination.

For now, regardless of virtual screens, pcmanfm-qt seems as the only way to set wallpapers with kwin under LXQt and real multi-screen wallpaper support seems to be quite broken.

**Comment by tsujan** [comment]
> What a mess ! But is it really that much work to detect if there are multiple viewports and draw on them and otherwise handle virtual desktops ?

Detecting virtual desktops and viewports is quite easy but adds an X11 dependency, which I don't think anyone approves of. Conversely, it's preferable to remove X11 dependency from apps as far as possible because "wayland will come."

**Comment by paulolieuthier** [comment]
> As I wrote before, when completing support of Wayland, LXQt will have to aim for some compositor. Right now kwin_wayland is the most user-friendly and seems to be the only one with that support while openbox doesn't work natively there at all. So, shouldn't pcmanfm-qt adapt for it in the long run?

LXQt components (in which I include pcmanfm-qt, although it should remain DE-agnostic for modularity) should not depend on a single WM. That's how it is today, on X11. On Wayland we (the FOSS community) still lack a proper standard with which we could keep LXQt agnostic.

The way in which kwin_wayland is done paves the way for a standard, much like happened with status notifier items (aka. app indicators) in Plasma, and we hope that has enough momentum for other projects to follow. The ideal situation here would be Qt implementing the standard and pcmanfm-qt depending on Qt alone.

**Comment by pmattern** [comment]
@v-fox 
Talking about LXQt vs. Wayland in general you may also want to have a look at [Orbital](https://github.com/giucam/orbital). We recently [found](https://github.com/lxde/lxqt/issues/1011) it cannot be use in LXQt right now but IMO it's certainly a piece of software to keep an eye on.

**Comment by tsujan** [comment]
For reference:

kwin logout crashes are fixed and it can be used with LXQt without problem now. `kactivitymanagerd` can be stopped by a startup script like:
````
#!/bin/bash
sleep 15
kactivitymanagerd stop &
exit
````

**Comment by wxl** [comment]
@tsujan says:
> I think my point is clearer now: pcmanfm-qt can't cover this diversity.

If I may interject some words implied in this conversation, he says this is true unless we:

> [detect] virtual desktops and viewports…but  [that] adds an X11 dependency, which I don't think anyone approves of. Conversely, it's preferable to remove X11 dependency from apps as far as possible because "wayland will come."

Maybe we provide a compile time option to turn this on and leave it off by default? Then we can remain Wayland friendly while resolving more immediate needs?

**Comment by tsujan** [comment]
I can't help you with your script but you didn't say with which kind of virtual desktops it works; openbox, kwin, compiz-reloaded,...?

BTW, since my last comment above, KWin has become very stable. I switched to it from Compiz-reloaded.

**Comment by hmollercl** [comment]
I've tested it in Lubuntu wich uses openbox. I believe it should work in kwin, because the only thing it uses beside pcfmanfm-qt is xrandr to get the screens and desktop dimensions.

**Comment by wxl** [comment]
For posterity's sake: related issue here https://github.com/lxqt/pcmanfm-qt/issues/103

**Comment by hmollercl** [comment]
Hi, I have beeing looking around the code to see if/how can this be implemented. If I use KScreen:Output or kscreen-output in console (instead of xradnr) to get the displays/monitor sizes would it be more "agnostic"? Meaning that it could handle openbox, kwin, compiz, etc...?

**Comment by agaida** [comment]
:smile: - just make a working model and test it - really, it would help and it should be possible. /<sarcasm>Only one remark: have a short look at our </sarcasm>

**Comment by v-fox** [comment]
@hmollercl How running KDE-specific binaries could be more "agnostic" than actual generic system-side "interface" (rhetorical question: how is it there still no X's dbus interface for querying device info ?) ? Especially, when it requires running `/usr/lib64/libexec/kf5/kscreen_backend_launcher` at login (I'm not sure how you all are using lxqt-config-monitor without it) to work.

Anyway, you may be better off reimplementing what [`nitrogen`](https://github.com/l3ib/nitrogen/issues/112) did or patching it and replacing pcmanfm-qt's "desktop" mode with it altogether.

**Comment by hmollercl** [comment]
@v-fox kscreen has wayland suport. Also lxqt-config-monitor uses KScreen https://github.com/lxqt/lxqt-config/blob/master/lxqt-config-monitor/loadsettings.cpp#L23

**Comment by v-fox** [comment]
@hmollercl Oh, I've very much noticed that it uses KScreen. Because it was not fun figuring out that I now need to manually launch KDE's kscreen shim from libexec where it's not even searchable among normal binaries. Does LXQt even has native Wayland session support ? Because I had make:
* custom `startlxqt-wayland.sh` with:
 ```
 export QT_QPA_PLATFORM=wayland-egl
 export GDK_BACKEND=wayland
 export CLUTTER_BACKEND=wayland
 export SDL_VIDEODRIVER=waylan
 env QT_QPA_PLATFORM="" kwin_wayland --xwayland --exit-with-session --no-kactivities lxqt-session
 ```

* xsession desktop-file with `Exec=dbus-launch --exit-with-session kwin_wayland --xwayland --exit-with-session --no-kactivities startlxqt`
* wayland-session desktop-file with `Exec=env mesa_glthread=true nice -n -5 ionice -c 2 -n 0 -t chrt -v -r 5 kwin_wayland --xwayland --exit-with-session --no-kactivities startlxqt`

To test out Wayland which, surprisingly, worked but I abandoned anyway because of kwin's shortcomings like the lack of colour correction via native display profiles which they can't figure out since 2013. Is that what you're all doing ? Launching it in Wayland and configure your multiple monitors in lxqt-config-monitor ?

**Comment by tsujan** [comment]
@v-fox 

If we forget about viewports or virtual desktops and, instead, focus on screens, theoretically, it's possible to give different wallpapers to different screens only by using `QScreen` (which is already used by pcmanfm-qt for managing multiple screens). But I haven't tried to do it because it requires *lots of changes* to the current code and the final result isn't interesting to me -- in short, I'm not motivated to start testing the idea ;)

However, patches -- by a motivated developers -- are welcome.

**Comment by hmollercl** [comment]
@tsujan ooo QScreen is much easier than KScreen, I think I can do that.

**Comment by tsujan** [comment]
> @tsujan ooo QScreen is much easier than KScreen

Three things should be done, at least, and each of them is a lot of work

 1. pcmanfm-qt's desktop preferences should be changed so that the user can add different wallpapers to different screens. Their number should be updated when screens are added or removed.
 
 2. The selected wallpapers should be used appropriately for painting the whole desktop. They should be cached too.
  
 3. Painting should be updated whenever the number of screens and/or their alignment changes.

Moreover, all of this should be done in a backward compatible way, so that there's no change with a single screen. That's possible but not easy at all.

As for KScreen, there should be a really good reason for adding such dependencies and this isn't one.

**Comment by hmollercl** [comment]
On point 1, I would start with same wallpaper with selection in GUI between extended or indiviudual wp. Then enhance it to different wallpapers (more GUI would need to be updated).
On point 2, why are wp cached? So you don't need to resize image every time --desktop is launched? Or is there another reason? Because, you don't cache tiled and centered wp; but you cache stretched, fited and zoomed. https://github.com/lxqt/pcmanfm-qt/blob/master/pcmanfm/desktopwindow.cpp#L623 vs https://github.com/lxqt/pcmanfm-qt/blob/master/pcmanfm/desktopwindow.cpp#L636
I ask of the cache because the way I see the solutions is similar to tile but with different image sizes. It's a big pixmap which covers the xinerama extensions and then "paste" the wallpapers for the different individuals screens in the pixmap. That's how I did it in the bash script.

**Comment by tsujan** [comment]
> So you don't need to resize image every time --desktop is launched?

Right.

The main task is *giving N wallpapers to N screens and updating them appropriately when the screens are re-aligned/removed/added/resized.* Caching and adding preferences could be done later.

You could focus on "Stretch to fill the entire screen" for each screen. The other 5 modes could be dealt with later based on it.

**Comment by tsujan** [comment]
Oh, the slide-show should be covered too but, for now, we can ignore it.

**Comment by agaida** [comment]
While you are at it : A video wallpaper would be great - with sound of course - second step would be using the sound of a certain attached screen. And I don't make jokes - the multiscreen can come afterwards :D

**Comment by tsujan** [comment]
@agaida You told the reason why I had no motivation ;) If something needs a huge amount of code, it should be VERY desirable to be worth it. There are many examples but this isn't one of them, IMO. And I said nothing about maintainability...

**Comment by agaida** [comment]
@tsujan - sorry, don't want to depress you, but that's:
a) the logical consequence
b) it would be really cool - i know we have other things to solve first :smile:
c) i use only one little screen - so i would really appreciate this feature (ok, i should better run)

So if one comes up with some ideas or even better with ideas and a basic implementation - why not. The only thing about is: It will cause more work for us, because we should really review such contributions carefully - and maybe help with the implementation. Our morgue of dead or abandoned pull requests is already to big.

**Comment by hmollercl** [comment]
ok, here I have a branch with stretched support. Is very simple: without cache, only stretched and without expanded wallpaper. https://github.com/hmollercl/pcmanfm-qt/tree/multi_monitor

**Comment by tsujan** [comment]
> The only thing about is: It will cause more work for us

That's true. I'll review codes whenever I find the time -- and I won't let buggy codes enter pcmanfm-qt/libfm-qt.

@hmollercl 
It's a reasonable start (that needs tests: portrait+landscape, overlapping screens,...). Keep up the good work.

**Comment by hmollercl** [comment]
portrait/landscape works ok according to exif. When screens are overlapped, wallpapers are overlapped too (as I would expect) or a different behavior is expected?

Btw, there is a small bug wit exif because cache is reused based on image addres and size but w/o exif definition, so if one cache is stored with exif off, when putting exif on it uses the same cache that was created with exif off. I will take a look at it when I touch the cache, that would need new definitions and code.

@agaida you can use VLC for video wallpaper.

**Comment by agaida** [comment]
mehhhh - i just forgot the sarcasm tags :D

**Comment by tsujan** [comment]
> ...or a different behavior is expected?

No.

> Btw, there is a small bug wit exif

Yes, I'd noticed it. It's because of caching and doesn't show up with normal usage.

**Comment by hmollercl** [comment]
I finished it w/o cache but I really haven't seen the necessity for it. It has a QCheckBox (added in .ui) to decide the actual behavior (it's literally the same code in an else) or individual for each monitor. It also has a new setting entry to save that preference. I've tested it in several conditions and it work ok. How should I proceed? A pull request or you want something else first? https://github.com/lxqt/pcmanfm-qt/compare/master...hmollercl:multi_monitor

**Comment by tsujan** [comment]
Please make a PR. I'll review it as soon as I find the time (it might take a while). We discuss probable problems at the PR.

**Comment by tsujan** [comment]
Done in https://github.com/lxqt/pcmanfm-qt/commit/dfdf1fa0db00330d927e664c8e6829c0835adfa7 by @hmollercl as an option. The change is about treating each screen separately, not about giving different wallpapers to different screens (which won't be implemented because, otherwise, it'll clutter the code for no good reason).

**Comment by jubalh** [comment]
> The change is about treating each screen separately, not about giving different wallpapers to different screens (which won't be implemented because, otherwise, it'll clutter the code for no good reason).

so this means having one kind of wallpaper on all the screen but using the correct size their, fitting the same kind of wallpaper to each screen exactly and not stretching over multiple screens?

**Comment by tsujan** [comment]
> so this means having...

Exactly -- of course, if its option is enabled (disabled by default, like before). It covers slide show too.

Having that option was an automatic consequence of the current discussion and, especially, @hmollercl's patch, which was a good addition to the code.

**Comment by v-fox** [comment]
@tsujan 
> Done in [lxqt/pcmanfm-qt@dfdf1fa](https://github.com/lxqt/pcmanfm-qt/commit/dfdf1fa0db00330d927e664c8e6829c0835adfa7) by @hmollercl as an option. The change is about treating each screen separately, not about giving different wallpapers to different screens (which won't be implemented because, otherwise, it'll clutter the code for no good reason).

"No good reason" ? https://bugs.kde.org/show_bug.cgi?id=341143 - here's 5 years and 8 duplicates worth of reasons ! In short: visual differentiation of dedicated workspaces.

So, in the end, it's not a FIX but a WONTFIX. That's barely any better than putting some infinitely repeatable tiling nonsensical shape as wallpaper and letting it be repeated and stretched just to have something other than pure blackness from DOS days. Just "not broken out-of-the-box but is broken with default setting".

>Having that option was an automatic consequence of the current discussion and, especially, @hmollercl's patch, which was a good addition to the code.

Yeah, things not being completely broken is much more than just "a good addition to the code". But by stating that actual request "won't be implemented" means that, not only you not going to do it yourself, but also will willingly deny any completed and correct code from anyone else now just for sake "cleanliness" of incomplete code that you personally not using or improving.

KDE has excuse of their their codebase actually being insanely overcomplicated and being constantly rewritten Poettering-style, without ever achieving feature-parity with "bad", old versions, let alone, its new goals. But even they don't deny outside attempts in improvement on some misguided principle. Are you sure that's what you meant ?

Especially if you actually planning to be "compositor-agnostic" and use Wayland in the future and after already gluing lxqt-config-monitor to KScreen. It seems that Xinerama is completely abandoned on X11, it's only xrandr now. "Zoom", "center" (filling blanks with ugly colour) and ugly "tile" (usually only useful as placeholder textures to easily detect broken ugliness) are the only options for wallpaper "fitting" even if they 1:1 compatible by size, there is no point to having options that may potentially skew everything in ugly ways and have no benefit, and "zoom" is, pretty much, most practical option in all cases. We are not talking about running separate background videos (like VLC does), info-widgets (remember those ?), fractal generators or 3D scenes per screen here.

**Comment by tsujan** [comment]
> So, in the end, it's not a FIX but a WONTFIX.

You're free to look at it in any way you like.

> ... but also will willingly deny any completed and correct code from anyone else

Exactly.

**Comment by agaida** [comment]
@tsujan - you are a bad bad guy - and this should be my role here :D

And to all the others: Please, don't complain to loud and with to much words. If one has somethings to write - write patches, make the code and the functionality better, we will praise you for doing so. But don't write so damn long comments on bugs. thank you in advance

**Comment by tsujan** [comment]
@agaida Only a VERY concise and clean patch might be acceptable, and it's simply impossible for that job.

I won't allow cluttering a code that's written, debugged, cleaned and improved by dedicating so much time and energy to it. Even the merged patch took me a lot of time to make it good enough for our code....

**Comment by agaida** [comment]
fully agree  - my try was only about to much text - if there is a bug and on can point to without to much words - fine, appreciated. But at leas i - for myself - hate it if i had to read long tetxts without any reasons in __not__ may mothers tongue. Sorry for that, but plain truth.

**Comment by tsujan** [comment]
I don't read more that 3-4 lines if a comment seems irrelevant to me -- I don't have time to.

**Comment by hmollercl** [comment]
@v-fox you can create your own wallpaper stitching the images you want, the same way we do it for the per screen. Create a "canvas" of the size of the combine screens and put the wallpapers you want on it and then use it as wallpaper. You could even create a program for that and pass it to pcmanfm-qt with -w flag. You can use this bash script for inspiration https://git.launchpad.net/~hmollercl/stitchwp/tree/stitchWP.sh

**Comment by v-fox** [comment]
@agaida "Too Long Didn't Read" on bugs, seriously ? What is this, "The Hello-World DE for ADD 12-year olds" ? I'm going to write however I see fit (not my native language either, by the way) and if it's too much for your big engineering brains then you free to ignore it, lock the thread or ban me because, clearly, this is going nowhere. And, with such attitude, it seems like a whole project might be no more than a bare life-support for perpetually deficient code without any goals or plans to reach them, now with policy of ignoring feature pull-requests on principle.

The only thing I'm using from LXQt is panel, might as well take it as incentive to drop the whole thing. At least now I know why the only changes I've noticed for past years are breakages, after all the news-noise about "future of LXDE". Unbelievable.

@hmollercl Yeah. But disabling or rearranging differently-sized monitors changes layout and sizing of target image. Previously, `nitrogen` worked perfectly for that, (it also allowed for getting rid of desktop icon nonsense before there was an option in pcmanfm-qt) but now it doesn't. Thanks for the script but it would be easier to just run Plasma, or anything else, with nitrogen where it works. Especially now when we know that this is NOT a one-time decision but a consequence of general attitude for the whole project.

**Comment by tsujan** [comment]
@agaida, I pressed the magic button.

**Comment by agaida** [comment]
@v-fox - nice try, you will not see me unfriendly - and this should answer the whole thing. I'm sorry, i'm erman - fuck i wish i could say i'm from Finnlandia - so we could use perkele to solve that.

@tsujan - sorry that i maybe have the last word . was not planned so. But to be blunt about:
@ v.fox: english is not my mothers tongue, so please understand if I don't understand some things correctly. We talk about code. Not less, not more (my old teacher told me: The who to write much don't know anything (freely translated from german: Wer viel schreibt umschreibt und weiss nix!) - So please - if you have anything to complain about: Take it shorf. Thank you.

**Comment by palinek** [comment]
> I pressed the magic button.

For no good reason, I believe. @v-fox just told his opinion and I don't see anything bad or impolite in his comments.

my opinion
