### ISSUE TITLE
[FR] site: build order suggestion

### ISSUE THREAD

**Issue by ghost** [lxqt/lxqt#119]
I've built ALT Linux packages in this order and propose to add it to some page with prerequisites and build instructions:

libqtxdg
libsysstat
liblxqt
liblxqt-mount
menu-cache
libfm
lxqt-common
lxqt-about
lxqt-globalkeys
lxqt-notificationd
lxmenu-data
lxqt-panel
lxqt-powermanagement
lxqt-qtplugin
lxqt-runner
lxqt-session
pcmanfm-qt
lxqt-appswitcher
lxqt-lightdm-greeter
lxqt-openssh-askpass
lxqt-policykit
compton-conf
lxqt-config
lxqt-config-randr
obconf-qt
lximage-qt

The order is less critical after lxqt-globalkeys although pcmanfm-qt should be higher (I've added libfm-qt-devel subpackage in the process, needed for lximage-qt).

Just in case, my crop of specfiles is currently available here: http://fly.osdn.org.ua/~mike/RPM/SPECS/lxqt/ (will disappear over time).

**Comment by agaida** [comment]
long done
