### ISSUE TITLE
Clicking bottom pixels of panel doesn't activate anything on 4K display, right-click only gives desktop context menu

### ISSUE THREAD

**Issue by yaomtc** [lxqt/lxqt#1197]
I'm using lxqt on a 4K display (not sure if this happens on lower res displays too) and when I move the cursor to the bottom of the screen, I can't click any taskbar buttons, or click any quick launchers, or open the application menu. I have to slightly move the cursor upwards to click anything. The clickable areas should extend to the very bottom.

EDIT: Using Openbox 3.6.1, Frost theme, lxqt-common 0.11.0 on Arch Linux.

**Comment by yan12125** [comment]
Which window manager are you using? Openbox/xfwm4/kwin/...?

**Comment by tsujan** [comment]
In addition to answering @yan12125's question, please also tell which LXQt theme you use because this may about theme properties like margin.

**Comment by palinek** [comment]
...and the version of LXQt components, as this might be already solved (e.g. https://github.com/lxde/lxqt-common/commit/d0e0edaa486fcec13bab67eeaade6810eea8fe2f)

**Comment by yaomtc** [comment]
Openbox, Frost, lxqt-common 0.11.0 on Arch Linux.

**Comment by tsujan** [comment]
I can't reproduce this with Frost and the latest LXQt *but I don't have a 4K display*.

**Comment by yaomtc** [comment]
I just added a panel to my 1080p display and it works as intended. I guess it's only a problem at this kind of resolution?

**Comment by tsujan** [comment]
Qt5's support for 4K displays has a bug but I'm not sure this is about the same bug.

**Comment by agaida** [comment]
can't see a bug here, only a difference in behaviour between quicklaunch, taskbar, tray and status. will file a new bug for it
