### ISSUE TITLE
plugin-statusnotifier: Name in desktop entry is same as Comment

### ISSUE THREAD

**Issue by scootergrisen** [lxqt/lxqt#1207]
In lxqt-panel file statusnotifier.desktop.in it says:
```
Name=Status Notifier Plugin
Comment=Status Notifier Plugin
```
Suggest to write a comment that is not the same as the name.

**Comment by stefonarch** [comment]
Done https://github.com/lxqt/lxqt-panel/commit/9e5232e3860e82a3e95b4529de06b88f2c4e98be
