### ISSUE TITLE
Remove or add "." to desktop files "Comment=" string

### ISSUE THREAD

**Issue by scootergrisen** [lxqt/lxqt#1208]
I the different *.desktop files the comments (Comment=*) sometimes ends with a "." and sometimes not.

Suggest making alle det files use the same. With "." or without "." which ever people think is best.

Example:
```
Comment=Status Notifier Plugin
Comment=Show a DOM tree of the LXQt panel.

```

**Comment by stefonarch** [comment]
Done now all.
