### ISSUE TITLE
Making all desktop translation use the same style

### ISSUE THREAD

**Issue by scootergrisen** [lxqt/lxqt#1210]
The different *.desktop.in files don't seem to be using the same style.
Like som have the original english source text also in the translated files like *_da.desktop and some does not and some start with "# Translations" and some not.

Also the folder called translation dont always seem to be in the same path. Sometimes its in the same folder, some times it in the parent folder and i think i saw in src folder of parent folder to.

Maybe it would be nice is all the repositories could use the same style.

Also some translations use GenericName and some does not. I don't know if that should be in all the files.

Some use Icon and some seem to be missing them.

**Comment by stefonarch** [comment]
Fixed now by migrating to  *.desktop.yaml files.
https://github.com/lxqt/pcmanfm-qt/pull/1246
https://github.com/lxqt/lxqt/issues/1044
