### ISSUE TITLE
Missing info about translating translators.info.src and *.directory.in files

### ISSUE THREAD

**Issue by scootergrisen** [lxqt/lxqt#1211]
I see info about translating desktop files but i also found some other files that i don't see info about that should be translated:
```
./lxqt-about/translatorsinfo/translators.info.src
./lxqt-common/menu/desktop-directories/lxqt-leave.directory.in
./lxqt-common/menu/desktop-directories/lxqt-settings.directory.in
```

Would be nice to know about all the files that needs to be translated so we don't miss some.

**Comment by stefonarch** [comment]
.directory files have moved to lxqt-panel/menu/*.directory.yaml and translating is on the way in weblate.
https://github.com/lxqt/lxqt/wiki/Translation#panel-desktop-entry-files

**Comment by stefonarch** [comment]
Done in weblate and in the wiki.
>Credits for translations (shown in LXQt-About) can be inserted in [lxqt/lxqt-about/tree/master/translatorsinfo/translators_XY.info](https://github.com/lxqt/lxqt-about/tree/master/translatorsinfo).

https://translate.lxqt-project.org/projects/lxqt-desktop/#information
