### ISSUE TITLE
Both "Date and Time" and  "Time and Date" in Configuration Center

### ISSUE THREAD

**Issue by scootergrisen** [lxqt/lxqt#1215]
In Configuration Center i see both:
Date and Time
Time and Date

Don't know why there are both but i suppose only one of them should be there.

**Comment by agaida** [comment]
a clear maybe - it might be that the Center has picked up a configuration item from another installation / DE

**Comment by scootergrisen** [comment]
Yeah maybe. I installed all the DE's Debian offers with tasksel to test things so could be.

**Comment by agaida** [comment]
so the desktop files which provide bothe date and time should be easy to identify : 
cd /usr/share/applications and grep -ri date | grep -i time | grep and give
```
lxqt-admin-time.desktop:Name=Date and Time
lxqt-admin-time.desktop:GenericName=Date and Time Settings
lxqt-admin-time.desktop:Comment=Configure the date and time of your system
```
on my system

**Comment by scootergrisen** [comment]
The other might be time-admin from GNOME.
Why include the one from GNOME?

**Comment by agaida** [comment]
good question - we include some not LXQt specific things - we should eventually rethink this strategy

**Comment by Vladimir-csp** [comment]
Looks like an occasion to dig #580 up? That thing as a config center with lxqt filter applied by default would fit right in.

**Comment by scootergrisen** [comment]
Also "Users and Groups" appear twice.
Not sure if that is the exact string in english.

Also one "Date and Time" and one "Users and Groups" short cut appear in the menu under Settings > LXQt Settings. But if you look in the Configuration center dialog those short cuts appear under System Settings, not under LXQt Settings.
So i suppose those should be move up under LXQt Settings so that everyting in System Settings are the once that don't have a shortcut in the menu.

**Comment by luis-pereira** [comment]
@scootergrisen Can you post the .desktop file ?

**Comment by scootergrisen** [comment]
GNOME:
```
/usr/share/applications/time.desktop
/usr/share/applications/users.desktop
```
Don't know if the desktop file can be found at https://git.gnome.org//browse/

LXQt:
```
/usr/share/applications/lxqt-admin-time.desktop
/usr/share/applications/lxqt-admin-user.desktop 
```

https://github.com/lxde/lxqt-admin/blob/master/lxqt-admin-time/lxqt-admin-time.desktop.in
https://github.com/lxde/lxqt-admin/blob/master/lxqt-admin-user/lxqt-admin-user.desktop.in

**Comment by pmattern** [comment]
Indeed the files in question belong to the [GNOME System Tools (GST)](https://projects.gnome.org/gst/), exactly speaking there are "Network" (`network.desktop`), "Shared Folders" (`shares.desktop`), "Time and Date" (`time.desktop`) and "Users and Groups" (`users.desktop`).
None of these should make it into `lxqt-config` or plugin-mainmenu. As all of them are stating `GNOME` in key `Categories` this could be achieved easily by modifying `/etc/xdg/menus/lxqt-config.menu` (lxqt-config) like this
```
    <Menu>              
        <Name>System settings</Name>
        <Directory>lxqt-settings-system.directory</Directory>
        <Include>       
            <And>       
                <Not>
                    <Category>GNOME</Category>
                </Not>
                <Category>Settings</Category>
                <Category>System</Category>
            </And>
        </Include>
    </Menu>
```
and `/etc/xdg/menus/lxqt-applications.menu` (plugin-mainmenu) like this
```
        <!-- Settings -->
        <Menu>
        [...]
                <OnlyUnallocated/>
                <Include>
                      <And>
                        <Not>
                                <Category>GNOME</Category>
                        </Not>
                        <Or>
                                <Category>Settings</Category>
                                <Category>PackageManager</Category>
                        </Or>
                      </And>
                </Include>
```

This issue made me realize there are some more problems in `/etc/xdg/menus/lxqt-{config,applications}.menu`, though.
* `lxqt-config.menu` is providing an additional section "[Other settings](https://github.com/lxde/lxqt-config/blob/a54264c174c0d56d6a0de94ceaf29ed9f2e5a5ca/src/lxqt-config.menu#L47-L63)" which is implemented in a strange way right now.
Some [\<Include\> stanza](https://github.com/lxde/lxqt-config/blob/a54264c174c0d56d6a0de94ceaf29ed9f2e5a5ca/src/lxqt-config.menu#L10-L12) in the menu's top level is basically disabling the section, e. g. preventing `obkey.desktop` and `xscreensaver-properties.desktop` from appearing in this menu. I for one don't see any point in directives like `<Include>` at this level as it isn't reflected in GUI `lxqt-config` at all where only sections like "LXQt settings" and so on one level below appear.
Its section in `lxqt-config.menu` is stating a file `lxqt-settings-other.directory` which we don't provide.
A distinction like the one between "System settings" and "Other settings" in `lxqt-config` isn't made in plugin-mainmenu.
* As mentioned [above](https://github.com/lxde/lxqt/issues/1215#issuecomment-268039073) `lxqt-config-{time,user}.desktop` are listed in the LXQt specific section of plugin-mainmenu but not within `lxqt-config`.

Thoughts? E. g. remove the GNOME stuff as depicted above and address the other topics in an issue on its own?

**Comment by tsimonq2** [comment]
I'm :+1: on adding the given code to exclude the GNOME entries. There's no use having them there if they're just being duplicates...

I also think that addressing that in a separate issue would be beneficial because discussing that here distracts from the original purpose of this issue (although we should still discuss this, just in it's own place).

**Comment by agaida** [comment]
The problem is deeper. if there are some applications installed that have keywords in it that qualifies them to appear in the system section of lxqt-config it is fine. These things should simply don't be there in a clean installation. So it is a task for the distribution and the admin of the system in charge to prevent it. It is not our job to paint these things over.

However - This bug is an example for a not clean installed system. We should not accept bugs about these issues, there is nothing we can do about. The only thing that  would help is education.

**Comment by Vladimir-csp** [comment]
Some time ago I suggested how lxqt-config could be transformed into a versatile application browser, potentially fixing those kind of issues along the way: #580. Embracing underlying clockwork, not working against it or painting it over.

**Comment by agaida** [comment]
it's not about filtering things - its about installed things. Some desktop environments bring in tools that do the "same" thing - probably in an incompatible way. So, of course we could filter them out. But what is with legit system tools that do exactly what we want to?

**Comment by agaida** [comment]
PS: I just closed https://github.com/lxqt/lxqt/issues/1396 - basicly the same issue - two (or more) applications doing the same thing.

**Comment by Vladimir-csp** [comment]
> it's not about filtering things - its about installed things. Some desktop environments bring in tools that do the "same" thing - probably in an incompatible way.

Well, filtering can expose and clarify this: show/hide apps that do not have LXQt in their categories, or group them accordingly.

**Comment by agaida** [comment]
Thats what the system section is for - if one has a debian based thing at hand - galternatives is a fine example (A cool gtk system tool for managing debian alternatives) - So our stuff should be in the LXQt section - "all the other"™ things should go into system. If LXQt tools are in the system section this is a bug in our own things and should be solved by us.

**Comment by agaida** [comment]
Hmm. Now that SDDM Configuration is a LXQt project we should move that too :)

**Comment by stefonarch** [comment]
Hm not sure, for me date and time setting is  independent from the DE in use, same goes for sddm and users+groups. Moving those system settings will be almost empty.

**Comment by stefonarch** [comment]
My point is that this is  about  Desktop settings >< System settings - when I log in with another desktop session users/groups, time/date and so on  are the same  but appearance or window effects are  not. 
So renaming LXQt settings to Desktop settings would be more the way I see it.

**Comment by agaida** [comment]
you misunderstood something - 'Both "Date and Time" and "Time and Date" in Configuration Center'
Both things are different programs - that do (maybe) the same. My patch only move the LXQt things into the LXQt section - so a user should be able to see which tool is the LXQt tool. And i really don't care what is in the system section - We should make clear that tools listed there are no LXQt tools - thats all.

**Comment by agaida** [comment]
Next thing is - the whole Settings are not consistent - we have lxqt-config and some system settings in there. And we have a different set of tools under settings - the "system" things included - not the best situation. We should put all the stuff into lxqt-config and make config a main point imho.
