### ISSUE TITLE
Some strings are not translateable

### ISSUE THREAD

**Issue by scootergrisen** [lxqt/lxqt#1216]
I am working on translating LXQt and things are going well.
But there seems to be some strings here and there that are not translateable.
Like in the menu "Leave", "LXQt Settings" and button names here and there and text in authorization dialogs and just some strings in different applications that are missing.

Are people well aware of this and how do we make it so that they can be translated?
Should i report a issue for the strings i see is missing or what?

**Comment by tsujan** [comment]
> Are people well aware of this

I don't think so.

> Should i report a issue for the strings i see is missing?

It would be appreciated.

**Comment by scootergrisen** [comment]
Are there not some tools to help developers be away of text in the software that are not translateable?
Like lrelease has -markuntranslated so i can put "???" or something in front of a text i have not translated yet.

**Comment by tsujan** [comment]
> Are there not some tools to help developers be away of text in the software that are not translateable?

What I got from your report was that some strings miss `tr()` in the code. The function `tr()` makes it possible for lupdate to find translatable strings. I don't know of any automatic way to find strings in the code and add them to `tr()`.

**Comment by scootergrisen** [comment]
I don't know about tr() but would be nice to some how test a software for string that are not translatable instead of translators having to inform about strings here and there that they encounter.

So should i just report it here for everything i find in lxqt and the software is has?

**Comment by tsujan** [comment]
> So should i just report it here for everything i find in lxqt and the software is has?

Are there many? A rough estimation?

**Comment by scootergrisen** [comment]
I haven't looked much into it yet.
I'm translating LXQt to danish so i look for things that are not translated yet.

**Comment by tsujan** [comment]
Translatable programs should be written in a specific way. All LXQt apps are written so. But, as human beings, programmers are prone to mistakes and may leave some strings out of translation inadvertently. As far as I know, there's no tool for finding those missing cases. The only way I know of is running the app with a complete translation and seeing which strings are not translated.

**Comment by paiiou** [comment]
I think it's basically the standard buttons.
I found it in lxqt-config:Close Cancel Reset Save Apply
Also Yes No, I think in lxqt-session.

**Comment by palinek** [comment]
> I think it's basically the standard buttons.

These are the default qt texts and the translations are maintained directly by Qt. LXQt apps [use these translations](https://github.com/lxde/liblxqt/blob/master/lxqttranslator.cpp#L138) (if available).

E.g. in debian derivates the package providing these translations is `qttranslations5-l10n`.

**Comment by paiiou** [comment]
Thanks for the information. Installing the correct package solves my translation problem.
For information, the Mageia package is called qttranslations5.
Is this also the problem of scootergrisen?
