### ISSUE TITLE
Two monitors with different sizes enabled while only one attached and menu bar displays wrongly

### ISSUE THREAD

**Issue by tjadevries** [lxqt/lxqt#1228]
After startup, two displays are enabled in monitor settings (LVDS1 1024x768 and HDMI2 1920x1200), while only the HDMI is connected. Unfortunately, the lxqt bar displays halfway the screen.

I could solve this by specifying a proper lxqt-config-monitor.conf but what is the format for such a file?
So far I am unable to save the config that I have.

lxqt 0.11.0 on archlinux

**Comment by kuleszdl** [comment]
Did you define two displays statically somewhere? Are you using an `xorg.conf` configuration file or something like that?

**Comment by pmattern** [comment]
In addition the output of `xrandr` would be helpful as well as a screenshot. As for the latter you may simply use the tool of LXImage-Qt.

**Comment by tjadevries** [comment]
sorry that my response has taken so long.

```
$ xrandr
Screen 0: minimum 8 x 8, current 1920 x 1200, maximum 32767 x 32767
LVDS1 connected (normal left inverted right x axis y axis)
   1024x768      60.00 +
   800x600       60.32    56.25  
   640x480       59.94  
   512x384       60.00  
DP1 disconnected (normal left inverted right x axis y axis)
DP2 disconnected (normal left inverted right x axis y axis)
HDMI1 disconnected (normal left inverted right x axis y axis)
HDMI2 connected 1920x1200+0+0 (normal left inverted right x axis y axis) 520mm x 320mm
   1920x1200     59.95*+
   1600x1200     60.00  
   1280x1024     75.02    60.02  
   1280x960      60.00  
   1152x864      75.00  
   1024x768      75.03    70.07    60.00  
   832x624       74.55  
   800x600       72.19    75.00    60.32    56.25  
   640x480       75.00    72.81    66.67    59.94  
   720x400       70.08  
VGA1 connected (normal left inverted right x axis y axis)
   1024x768      60.00  
   800x600       60.32    56.25  
   848x480       60.00  
   640x480       59.94  
VIRTUAL1 disconnected (normal left inverted right x axis y axis)
```

And here's the screenshot of the desktop. 
![desktop](https://cloud.githubusercontent.com/assets/3439143/23092300/e37d46bc-f5c7-11e6-8c08-7805a0551b22.png)

LVDS1 and HDMI2 are enabled, VGA1 is not enabled.
After disabling LVDS1, the menu bar moves to the bottom of the desktop, as desired.

**Comment by tjadevries** [comment]
I do not have an xorg.conf.

As I said, I think I could solve this by specifying a proper lxqt-config-monitor.conf, because I simply need to disable LVDS1. But what is the format for such a file?

**Comment by selairi** [comment]
lxqt-config-monitor.conf is updated when you press save or apply button. It
is like:

[General]

...

[SavedConfigs]

...

[currentConfig]

...

You are interested in currentconfig settings. They are applied when session
is started:

settings\1\connected=false

settings\1\hash=

settings\1\name=DP1

settings\2\connected=true

settings\2\currentMode=71

settings\2\currentModeHeight=768

settings\2\currentModeRate=@Variant(\0\0\0\x87\x42o(})

settings\2\currentModeWidth=1366

settings\2\enabled=true

settings\2\hash=94f2749513e831f326a424ff51c084ef

settings\2\name=HDMI1

settings\2\primary=true

settings\2\rotation=1

settings\2\xPos=0

settings\2\yPos=0

settings\3\connected=false

settings\3\hash=

settings\3\name=VGA1

settings\4\connected=false

settings\4\hash=

settings\4\name=VIRTUAL1

settings\size=4


You can see numbers 1, 2, 3 and 4, one number per output. It is easy to
know each prperty. Hash property is EID number of your screen (don't change
it). CurrentModeRate is selected rate in Qt QVariant format.CurrentMode is
KScreen number for that mode, but it is lxqt-config-monitor tries to set
mode using width, height and mode rate.

**Comment by selairi** [comment]
Have you tried to set HDMI2 as primary instead LVDS1?

2017-02-19 14:52 GMT+01:00 P L. Lucas <selairi@gmail.com>:

> lxqt-config-monitor.conf is updated when you press save or apply button.
> It is like:
>
> [General]
>
> ...
>
> [SavedConfigs]
>
> ...
>
> [currentConfig]
>
> ...
>
> You are interested in currentconfig settings. They are applied when
> session is started:
>
> settings\1\connected=false
>
> settings\1\hash=
>
> settings\1\name=DP1
>
> settings\2\connected=true
>
> settings\2\currentMode=71
>
> settings\2\currentModeHeight=768
>
> settings\2\currentModeRate=@Variant(\0\0\0\x87\x42o(})
>
> settings\2\currentModeWidth=1366
>
> settings\2\enabled=true
>
> settings\2\hash=94f2749513e831f326a424ff51c084ef
>
> settings\2\name=HDMI1
>
> settings\2\primary=true
>
> settings\2\rotation=1
>
> settings\2\xPos=0
>
> settings\2\yPos=0
>
> settings\3\connected=false
>
> settings\3\hash=
>
> settings\3\name=VGA1
>
> settings\4\connected=false
>
> settings\4\hash=
>
> settings\4\name=VIRTUAL1
>
> settings\size=4
>
>
> You can see numbers 1, 2, 3 and 4, one number per output. It is easy to
> know each prperty. Hash property is EID number of your screen (don't change
> it). CurrentModeRate is selected rate in Qt QVariant format.CurrentMode is
> KScreen number for that mode, but it is lxqt-config-monitor tries to set
> mode using width, height and mode rate.
>
>
>

**Comment by tjadevries** [comment]
Thanks for your help.
HDMI2 is set as primary
I'm on Archlinux. I have created an lxqt-config-monitor.conf file in /etc/xdg/lxqt and one in ~/.config/lxqt
In my local config, an empty version of the file was present, which was saved a long time ago. I cannot seem to get such a config file saved with the current settings.

I have tried to create a proper config file myself, using your info. I have some problems:
- what should be the setting for currentMode? I have no idea and cannot find this info in the Monitor Settings UI or in the xrandr output
- how can I find the hash value? I guess it is the EISA device ID; in the Monitor Settings UI, this field is empty
- the current modeRate is 59.9502; how to encode this as a QVariant??

I have created the following file:
```
$ more /etc/xdg/lxqt/lxqt-config-monitor.conf 
[General]
__userfile__=true

[currentConfig]
settings\1\connected=false
settings\1\hash=
settings\1\name=LVDS1
settings\2\connected=false
settings\2\hash=
settings\2\name=DP1
settings\3\connected=false
settings\3\hash=
settings\3\name=DP2
settings\4\connected=false
settings\4\hash=
settings\4\name=HDMI1
settings\5\connected=true
settings\5\currentMode=59.9502
settings\5\currentModeHeight=1200
settings\5\currentModeRate=@Variant(\0\0\0\x87\x42o(})
settings\5\currentModeWidth=1900
settings\5\enabled=true
settings\5\hash=
settings\5\name=HDMI2
settings\5\primary=true
settings\5\rotation=1
settings\5\xPos=0
settings\5\yPos=0
settings\6\connected=false
settings\6\hash=
settings\6\name=VGA1
settings\size=6
```

copied it to ~/.config/lxqt as well
logged out and in again, does not seem to change anything
Any further pointers welcome.

**Comment by selairi** [comment]
> In my local config, an empty version of the file was present, which 
> was saved a long time ago. I cannot seem to get such a config file 
> saved with the current settings.
>

lxqt-config-monitor should save your settings in 
~/.config/lxqt/lxqt-config-monitor.conf when you press save button. 
Aren't there?

Could you be so kind as open lxpanel settings and set pannel position in 
the proper screen? It can help me to find the bug.

Thanks.

**Comment by pmattern** [comment]
I do not think you have to manually fiddle with `lxqt-config-monitor.conf` but can use `xrandr` to work around the problem.
E. g. an invocation like `xrandr --output LVDS1 --off --output HDMI2 --pos 0x0 --mode 1920x1200 --primary` while `lxqt-config-monitor` is *not* running and next using the latter to save the settings only should get you started.

Yet your problem seems strange to me.
Assuming your screenshot above is displaying what you see on the device that is attached to `HDMI2` the misplacement of the panel probably results from both `LVDS1` and `HDMI2` being placed at `0x0`. But the latter shouldn't happen with recent X servers like the one on Arch Linux any longer. E. g. when I launch an LXQt session running Arch Linux on my dual-monitor system without any preexisting files the two displays are placed adjacent at their native resolution and the panel behaves as expected.
Could you provide information about the device that's supposed to be attached to `LVDS1`?

Also, you definitely should make sure that no preexisting / old configuration files are around which may optionally cause artifacts. Just saying as you mentioned
> an empty version of the file was present, which was saved a long time ago.

**Comment by tjadevries** [comment]
@selairi : 
- lxqt-config-monitor.conf is not being saved. Also the list of saved settings in the Advanced Settings dialog is empty
- I have opened the Configure Panel dialog from the panel. Indeed it shows that the position of the panel is "Bottom of desktop 1"; I can change it to "Bottom of desktop 2" and then it switches to where I want it to be. So the LVDS1 monitor apparently displays Desktop 1 on top of the HDMI monitor with Desktop 2.

**Comment by tjadevries** [comment]
@pmattern 
That is the strange thing: I have connected only a single monitor, to the DVI port. I do not understand why the LVDS is enabled. It must be related to my hardware. I checked the bios settings, only DVI output is enabled. (there is also a DisplayPort and a CRT, both disabled)

I run an up-to-date Archlinux.

**Comment by pmattern** [comment]
This is indeed weird. To my knowledge LVDS is used as sort of underlying technology of DisplayPort, but neither of DVI nor HDMI. The line of LVDS1 is neither stating a resolution nor a position, `HDMI2 connected 1920x1200+0+0` but `LVDS1 connected (normal left inverted right x axis y axis)`.
This could hint that device LVDS1 is enabled in error besides DP is disabled and in addition presented in a way making it impossible to deal with it the regular way.
Are you seeing the problem under other desktop environments as well?

A while ago we've seen similar problems, see e. g. #650. But besides an LVDS device was involved there as well, I think it's a different story as that one did very well report a resolution and a position. Basically what we considered the underlying reason still isn't fixed according to #680. But on the other hand I just cannot provoke a faulty setup like the one you're seeing by running `lxqt-config-monitor` on my local system but only by `xrandr` invocations assigning `--pos 0x0` to all devices ("outputs").
@selairi Thoughts on this?

Oh, and just curious: did you try the workaround described in my previous comment?

**Comment by tjadevries** [comment]
Running ```xrandr --output LVDS1 --off``` helps. However, I cannot get ```lxqt-config-monitor``` to save anything...

**Comment by tjadevries** [comment]
Ah, but I can of course add such a command to Autostart in Session Settings. And that solves my problem.
But if I can still be of use to solve an issue, let me know

**Comment by selairi** [comment]
> @selairi <https://github.com/selairi> :
>
>   * lxqt-config-monitor.conf is not being saved. Also the list of
>     saved settings in the Advanced Settings dialog is empty
>

This is really strange. It could be something related to file 
permissions. I suggest running these commands:

ls -l ~/.config
ls -l ~/.config/lxqt

and check file permissions.

Thanks.

**Comment by pmattern** [comment]
> But if I can still be of use to solve an issue, let me know

You could, as asked before, try and see whether you run into the same problem under other desktop environments as well. You're running a proper Linux distribution so quickly installing these and getting rid of them again if unneeded shouldn't be too much work.
IMO in particular LXDE and Xfce would be interesting, not so much KDE as it is using KScreen as well.

**Comment by vtolstov** [comment]
I have similar issue n fedora and fresh lxqt install.
All windows when miximized not fill bigger monitor while second power off.

**Comment by tsujan** [comment]
Fixed in git lxqt-panel, after removing `QDesktopWidget`.

Except for xrandr panning, for which Qt has no signal yet, lxqt-panel never appears at the middle of screen.
