### ISSUE TITLE
Network management plugin/systray

### ISSUE THREAD

**Issue by jleclanche** [lxqt/lxqt#125]
Moving razor-qt/razor-qt#102 here.

**Comment by paulolieuthier** [comment]
I've started building one on my spare time (which has been close to zero).

**Comment by alfredobonino** [comment]
@paulolieuthier have you ben created the plugin?
This is a good plugin for connman written in qt5:
https://github.com/andrew-bibb/cmst

**Comment by paulolieuthier** [comment]
@alfredobonino it's still a work in progress, and it's going to take time. Good to know about cmst in qt5, but I'm building a NetworkManager plugin.

**Comment by MttCastelli** [comment]
A little thing on CMST, as it doesen't even worth an issue: CMST should be between System Tools or Preference>Settings in LXQt menu, not between Internet app. IMO, of course.

**Comment by pmattern** [comment]
@MttCastelli 
The location of CMST in LXQt panel's main menu is determined by two objects. First key "Categories" in `/usr/share/applications/cmst.desktop` which reads `Categories=Settings;System;Qt;Network` and second the Categories assigned to the menu topics in `/etc/xdg/menus/lxqt-applications.menu`. The latter do make sense like they are, IMO. Making changes here would rather mean to have the tail wag the dog. So this is an [upstream](https://github.com/andrew-bibb/cmst) issue you may want to address as such.
Regarding the location itself I absolutely agree that "Internet" (<--> `Network ` among the values of key `Categories`) doesn't make too much sense. CMST is about settings after all, it's not an application like a browser. Also, configuring a network interface isn't limited to using the internet.

**Comment by GreenLunar** [comment]
I think we can remove systray from title because it will soon be gone from all GNU/Linux desktops.

**Comment by Vladimir-csp** [comment]
> it will soon be gone from all GNU/Linux desktops.

Do not rush.

**Comment by tsujan** [comment]
@Vladimir-csp  +1 :)
systray is OK, unless something at least equally useful replaces it.

**Comment by pmattern** [comment]
This issue is about a plugin for LXQt's panel so we do not have to care about other desktop environments at all here.
In LXQt the focus should nevertheless be on plugin-statusnotifier implementing the new SNI and not on plugin-tray implementing System Tray Protocol as the latter will stop working with Wayland.

**Comment by tsujan** [comment]
Update: Now, Status Notifier Plugin is quite mature and systray has no job -- only obsolete apps may use it.
