### ISSUE TITLE
PCmanFM-QT format option needed

### ISSUE THREAD

**Issue by szg0000** [lxqt/lxqt#1260]
Right click on drive in PCmanFM-QT format option is needed. Also needed a properties option, where the disk space/usage is shown.

![rightclick_format_needed](https://cloud.githubusercontent.com/assets/18247040/23298796/4c7c0016-fa7f-11e6-95c6-4da6390eb410.png)

**Comment by pmattern** [comment]
An item "Properties" probably isn't too difficult to implement as there's already something similar available for FHS objects in tree view (left pane) and all kinds of objects in the right pane.

A GUI to partition storage devices is probably much harder to implement. LXQt does not feature anything similar so far and the existing tools aren't really suitable either. KDE Partition Manager depends on a lot of Tier 3 and 2 KDE Frameworks components, QTParted seems to be dead.

Yet I think these proposals deserve being discussed.

**Comment by szg0000** [comment]
For formatting drives is enough to call the **mkfs** shell command with the correct switches and with the choosed file system.

For showing the disk space/usage is enough to use the "df -h" shell command's output data.

**Comment by tsujan** [comment]
Showing disk space should be easy because it's shown on the status bar. Also the Properties dialog could be called on right clicking. But I think it's better to leave formatting to another app (I always use GParted).

However, nothing can be implemented for now because some structural changes are on the way.

**Comment by szg0000** [comment]
Can you send me a link, where are the structural changes under discussion?

**Comment by tsujan** [comment]
> Can you send me a link

https://github.com/lxde/libfm-qt/pull/63

**Comment by tsujan** [comment]
The disk usage was shown a long time ago. Disk formatting isn't the job of a file manger.
