### ISSUE TITLE
.gitmodules: Change to absolute URLs

### ISSUE THREAD

**Issue by Chocobo1** [lxqt/lxqt#1265]
The problem occurs when I fork this repo and then clone the forked one, then trying to build the project.
Because the urls are all in relative form, that means I should fork all the submodules before I can start building...
One would expect git always fetch lxqt repos instead of one's own repos.
Or this is the intended behavior?

##### Possible Solution

Change all urls .gitmodules to absolute form, pointing to lxqt repos.
I can open a PR to change this.

**Comment by palinek** [comment]
Assuming that someone/we might need to mirror the whole LXQt, IMO this is the intended behaviour.

**Comment by agaida** [comment]
right
