### ISSUE TITLE
Remove QUIET flags from all CMakeLists.txt manifests

### ISSUE THREAD

**Issue by yan12125** [lxqt/lxqt#1276]
This is from https://github.com/lxde/lxqt/issues/1272. Using QUIET in CMakeLists.txt can bring problems when debugging building failures.

##### Expected Behavior

Package names are reported during cmake invocations if a dependency is missing

##### Current Behavior

In some find_package or pkg_check_module calls, there are QUIET flags that hides useful information

##### Possible Solution

Remove QUIET flags from all CMakeLists.txt manifests

**Comment by agaida** [comment]
https://github.com/lxqt/compton-conf/issues/87
https://github.com/lxqt/lxqt-build-tools/issues/32
https://github.com/lxqt/lxqt-config/issues/263
https://github.com/lxqt/lxqt-globalkeys/issues/89
https://github.com/lxqt/qtermwidget/issues/203

**Comment by luis-pereira** [comment]
Ship it.

**Comment by agaida** [comment]
all PRs merged.
