### ISSUE TITLE
Menus do not display on second monitor

### ISSUE THREAD

**Issue by mjziebarth** [lxqt/lxqt#1300]
I run lxqt on parabola linux (arch derived).
I've got two high DPI monitors (3840x2160) which I run via an nvidia graphics card using nouveau.

Some dropdown menus do not get displayed properly if the window they originate from is on the right (secondary) monitor. This includes texmaker and the lxqt panel (start menu and context menus).

##### Expected Behavior
All menus get displayed properly.

##### Current Behavior
When the originating window is on secondary monitor (or the lxqt panel is on secondary monitor), the dropdown menus (or lxqt start and context menus) do not get displayed. A focus shift is visible but no menu is displayed.

Everything else works as expected.

Edit: Applications for which dropdown menus do not work include QTerminal (0.7.1), TeXMaker (4.5) and QtCreator (4.2.1). Notably, PCManFm menus work without problems.

##### Possible Solution
For texmaker, I can temporarily fix the behaviour by moving the window to the first monitor and opening all relevant menus. When moved back to second monitor, the menus then work as expected.

For the lxqt panel, I can unfortunately not fix the issue since the dialog to move it to the first monitor is one of the menus not displayed (I suspect that moving the panel fixes the problem). Could somebody tell me the config file to move it to first monitor?

##### Configuration
I start lxqt using `startx`. The .xinitrc file contains the following lines:
```bash
export QT_SCALE_FACTOR=2
exec startlxqt
```
I used to have an xrandr configuration beforehand, but removing that did not fix the problem. Currently, everything concerning the monitors is configured using the lxqt monitor configuration utility.

##### System Information
* Distribution & Version: Parabola linux (updated)
* Kernel: 4.10.12
* Qt Version: 4.8.7 and 5.8.0
* liblxqt Version:  0.11.1
* Package version: 1

I hope this is an LXQt bug and not related to something else - in that case I'd like to apologize and ask whether somebody could tell me how to move the lxqt panel to the first monitor without using the panel config menu itself.

**Comment by palinek** [comment]
> whether somebody could tell me how to move the lxqt panel to the first monitor without using the panel config menu itself.

The configuration file is (if not overridden by parameter) `$XDG_CONFIG_HOME/lxqt/panel.conf` -> `~/.config/lxqt/panel.conf`. Name of the parameter is `desktop` in the panel's name section (panel1, panel2 ...).

**Comment by mjziebarth** [comment]
Thanks, this does fix the urgent problems.
