### ISSUE TITLE
lxqt-config-monitor should be bigger

### ISSUE THREAD

**Issue by agaida** [lxqt/lxqt#1317]
##### Expected Behavior
Monitor vendor should fit in one line

##### Current Behavior
Monitor Vendor need two lines

##### Possible Solution
Add some width. Positive side effect: the tabbed object will look better too.
It might be that the font runs wider or is bigger at all in the settings - but we have enough room to grow.

##### Steps to Reproduce (for bugs)
no need to reproduce, see the attached picture
https://bugs.launchpad.net/ubuntu/+source/lxqt-config/+bug/1700896/+attachment/4904396/+files/2017-06-27-221516_1920x1080_scrot.png
https://bugs.launchpad.net/ubuntu/+source/lxqt-config/+bug/1700896

##### System Information
* Distribution & Version:  Ubuntu Artful
* Package version: 0.11.1

**Comment by selairi** [comment]
Hello,

Not only the number of lines that are needed by Monitor Vendor depends on
window size, but we also must consider the font size. On the other hand, if
your screen is small, example an eeepc 701 with WVGA 800x480 screen, a big
lxqt-config-monitor window will be a problem. Actually, lxqt-config-monitor
window size is 476x247.

A scrollbar is required. I also suggest using bold fonts:

*Name:* xxx
*Vendor:* xxx
*Serial:* xxx
*Display size:* xxx
*Serial number:* xxx
*EISA device ID:* xxx



2017-06-28 21:01 GMT+02:00 Alf Gaida <notifications@github.com>:

**Comment by agaida** [comment]
ok - to be honest - i guess we should be not bigger that 650x400 maximum.

**Comment by palinek** [comment]
Done long ago, e.g.: lxqt/lxqt-config#128
