### ISSUE TITLE
Reminder: Suppress new GCC7 compilation warnings

### ISSUE THREAD

**Issue by tsujan** [lxqt/lxqt#1318]
They're like this:
````
warning: this statement may fall through [-Wimplicit-fallthrough=] blah blah
````
and the most harmless way of suppressing them is adding this comment in appropriate places:
```cpp
/* Falls through. */
```
At least, libfm-qt has it -- might fix it later.

**Comment by agaida** [comment]
https://developers.redhat.com/blog/2017/03/10/wimplicit-fallthrough-in-gcc-7/

so i guess the warning might be helpful sometimes :)

**Comment by tsujan** [comment]
> so i guess the warning might be helpful sometimes :)

RedHat thinks all people are equally stupid except for its own people -- as Gnome shows.

**Comment by agaida** [comment]
Some years ago i hated lintian in debian wholehearted - now it is a tool that i really like - ok, it sucks too some times, but one is forced to have a look if lintian complains about things - and it is mostly right with the complaints. So i wouldn't see any of this as negative first hand :D

**Comment by agaida** [comment]
hmm - i see some potential falls through in my latest arch builds - will file some PRs

**Comment by agaida** [comment]
That comment will grow - just rebuild LXQt

```
/home/agaida/lxqt/lxqt-config-git/src/lxqt-config/src/qcategorizedview/qcategorizedview.cpp: In member function 'virtual QModelIndex QCategorizedView::moveCursor(QAbstractItemView::CursorAction, Qt::KeyboardModifiers)':
/home/agaida/lxqt/lxqt-config-git/src/lxqt-config/src/qcategorizedview/qcategorizedview.cpp:1195:17: warning: this statement may fall through [-Wimplicit-fallthrough=]
                 }
                 ^
/home/agaida/lxqt/lxqt-config-git/src/lxqt-config/src/qcategorizedview/qcategorizedview.cpp:1197:9: note: here
         case MoveUp: {
         ^~~~
```

**Comment by tsujan** [comment]
@agaida This warning doesn't necessarily show a problem. In most (or all?) cases I've suppressed it, there was no problem at all.

**Comment by tsujan** [comment]
Believe me or not, this is just how some people want to enforce their coding ideas in the name of ...

**Comment by agaida** [comment]
It's only about reducing the noise - normally i can scroll through build logs - and only get nervous if some messages occour that don't match the usual patterns :D

**Comment by tsujan** [comment]
Give me the names of all sources with this special warning (not another one) here and I'll suppress them whenever I find extra time.

**Comment by agaida** [comment]
this falling through thing is only on these two places - we should avoid things like not used varibles and these damned typecasts (formaterrror) as far as possible - as i wrote, i was bitten enough by these things like in: Somebody think that it is a good idea to switch a warning into a bug. Not nice, but these things happend, esp. in debian :P

**Comment by agaida** [comment]
will file one bug about casts and one about unused things

**Comment by tsujan** [comment]
Suppressed all compilation warnings for qterminal and its widget [here](https://github.com/lxqt/qtermwidget/pull/195) and [here](https://github.com/lxqt/qterminal/pull/448). Consulted Konsole's source in one case (`qstrncpy` instead of `strncpy`).

**Comment by tsujan** [comment]
What was new in 2017 is an old story now.
