### ISSUE TITLE
Automatic device switch in the volume control widget

### ISSUE THREAD

**Issue by Rikorose** [lxqt/lxqt#1321]
When I plug in some kind of usb audio card, e.g. an USB DAC or USB headphones the volume control widget does not switch to the audio device even though it is the default device and there is currently e.g. music playing.

##### Expected Behavior
It should control the currently used audio device.

##### System Information
Fedora 25, lxqt 0.11.1

**Comment by ypnos** [comment]
I suggest for implementing this to add an "Automatic" option in the "Device to control" settings dropdown. This can then be the default selection.

The current model is great because it allows to have separate control plugins for separate devices that are used in parallel.

**Comment by AdryanDs** [comment]
2025, still not implemented this feature

**Comment by Vandino86** [comment]
@Rikorose Was this feature ever implemented? If not, then why did you close it?

**Comment by stefonarch** [comment]
Using now a  USB audio device I see this would be a good feature.

**Comment by kmiernik** [comment]
Using different audio devices (external DAC, monitor with speakers etc.) I also found this behavior annoying. My solution is using shortcuts definitions. Here is a code for the XF86AudioRaiseVolume
```
sh -c 'pactl set-sink-volume @DEFAULT_SINK@ +5% && notify-send -a Volume -t 500 "` pactl get-sink-volume @DEFAULT_SINK@ | head -n 1 | awk '{print $5}'`"'
```
In short it uses PulseAudio pactl command (set-sink-volume) and automatically defined names for the currently used device (@DEFAULT_SINK@). The second part of command (after &&) is just to display notification using notify-send and may be skipped if not needed. Option -t 500 sets notification visibility time in ms, and may be tuned to the preference . The shortcut for lowering volume is same except of setting -5%. I also use the following XF86AudioMute command, quite similar in structure.
```
pactl set-sink-mute @DEFAULT_SINK@ toggle && notify-send -a Mute -t 500 "`pactl get-sink-mute @DEFAULT_SINK@ | awk '{print $2}'`"
```
