### ISSUE TITLE
Installed applications not showing when building from scratch

### ISSUE THREAD

**Issue by fulalas** [lxqt/lxqt#1326]
![open-with](https://user-images.githubusercontent.com/27843666/28400523-c3cb7308-6d67-11e7-8501-6b14323ea588.png)

It seems that in order to see the installed applications through Open with... -> Other Applications, you need to have _/etc/xdg/menus/lxde-applications.menu_. At least in all distros that use LXQt I've tested so far, if I remove this file then the dialog above doesn't show any installed applications.

1- since it's written lx**de** in the file, is it right?
2- it seems that building from current git master this file isn't created anymore;

There's another similar problem regarding _/usr/share/desktop-directories_: building from current git master we get just two files (lxqt-leave.directory and lxqt-settings.directory), however older LXQt versions include lots of other files.

**Comment by stefonarch** [comment]
Strange enough in ubuntu 17.04  I could it reproduce but  only once and then never again, but on arch both with latest git and official arch packages  packages removing lxde-applications.menu produces no change.

In /usr/share/desktop-directories I've only the two mentioned from lxqt, and I'm using it for many years and did never clean up this directory I think.

**Comment by agaida** [comment]
normally the package manager should do the needed things to update the needed™ parts  - i guess all packages manager do that, so we can close it here
