### ISSUE TITLE
Menu search corrupts sometimes

### ISSUE THREAD

**Issue by stefonarch** [lxqt/lxqt#1327]
It's an issue which I see on both my machines for many months but I'm not able to track it down or to trigger it.
It happens sometimes just after login (32bit arch packages), and for sure after some days of uptime (I frequently suspend the systems)
##### Expected Behavior

Research should show application(s)

![schermata-23-11-11-10](https://user-images.githubusercontent.com/10681413/28498261-90c78e90-6f99-11e7-8cd0-18e412a4185b.png)

##### Current Behavior

It shows only folders, but clicking the folder it opens the program which matches the research, in the screen below searching for "firefox" shows "accessories"  (with no opening symbol)  but it will actually launch firefox.
![schermata-23-11-10-14](https://user-images.githubusercontent.com/10681413/28498262-90cce610-6f99-11e7-9a0e-ef906fd59a80.png)
 

Restarting panel solves; the issue happens with all possible search results settings.

##### Steps to Reproduce (for bugs)

1. open menu
2. search for application
3. when only a folder is shown klick folder
4. 

##### System Information

* Distribution & Version: Up-to date Arch on 2 machines (64bit and 32 bit)

* Package version: 32bit official arch packages, 64bit latest git checkouts

**Comment by tsujan** [comment]
So strange! I use the search capability on a regular basis and have never seen such a thing. There should be something extra that causes that in your case. Could you think of anything? Any guess?

**Comment by stefonarch** [comment]
If I had any idea... it could be some kind of setting for panel ecc I use on both machines? Theming does not influence as I saw.   I never found out at what moment it happens. I actually use it very few times, always using runner for everything.

**Comment by tsujan** [comment]
Could you please back up your panel config, stop panel, remove its config file, start panel again, add your widgets to it as before and use it for a while?

**Comment by stefonarch** [comment]
I'll did so on my second machine, on my main it's too much work with 2 panel and all the settings ;)

**Comment by tsujan** [comment]
> it's too much work with 2 panel and all the settings

I know ;) I back up my panel config as you do and for the same reason. But if you do it, we might be one step closer to a solution.

**Comment by stefonarch** [comment]
Just removed panel.conf from tty, logged in again with a fresh virgin panel and searching with "fire" shows   "accessories".  What else is involved, menu cache?

**Comment by tsujan** [comment]
So, we can definitely rule out the config.

> What else is involved, menu cache?

I have menu cache too but not this problem. @palinek has a deeper knowledge of Runner. We should wait for him to read this issue.

**Comment by palinek** [comment]
>  @palinek has a deeper knowledge of Menu. We should wait for him to read this issue.

I have no clue. Just a blind guess ... does localization make a difference?

**Comment by tsujan** [comment]
@palinek Are categories allowed to be shown on searching at all? I've never seen a category on searching but @stefonarch sees them for some reason.

**Comment by palinek** [comment]
> Are categories allowed to be shown on searching at all?

That depends on the used configuration.... 'Filter menu entries', 'Show matching entries`, 'Hide menu entries while searching' ....

**Comment by tsujan** [comment]
Oh, you're right; having used one config for a long time, I'd forgotten about those settings.

**Comment by stefonarch** [comment]
Note that it's not the normal category which has a > symbol to navigate like in this screen:

![schermata-24-13-48-34](https://user-images.githubusercontent.com/10681413/28522086-eff04f8c-7076-11e7-8a18-5dceb3df7876.png)

The > symbol is missing in "accessories" in the other screenshot as you can see.

**Comment by l3x13** [comment]
After seeing this on behaviour on Fedora and Manjaro, I noticed not having this behaviour on Debian directly after install. Debian by default is using the Fusion witget, but after some theming I saw the same strange search behaviour on Debian as well. 

After some more testing, I can confirm this behaviour is happening when you're changing the witget style. I'm using Debian with Breeze witget, so I changed it back to Fusion witget and after a restart of the system, search is working well again.

Fedora and Manjaro are both using by default a different witget style then fusion. 
@stefonarch Are you using a different witget style as well?
@palinek @tsujan Are you able to reproduce this by using Breeze as witget style?

**Comment by tsujan** [comment]
@l3x13 Since the menu is drawn by the stylesheet engine for @stefonarch (and, perhaps, for you), this can't be about the active widget style (Fusion, Breeze, etc.), IMO.

With the theme I use (not among LXQt themes), I can't reproduce this because the menu is always drawn by Kvantum here, *not by the stylesheet engine*. This somehow confirms my suspicion about a problem in the Qt stylesheet engine.

**Comment by tsujan** [comment]
@stefonarch @l3x13 Do you use an LXQt theme with translucency?

**Comment by l3x13** [comment]
Just dit my testing again, with changing the witget style and see the difference:

Breeze:
![breeze_witget_style](https://user-images.githubusercontent.com/31522242/29947732-83ff296c-8eab-11e7-8d07-a67733566747.JPG)
Fusion:
![fusion_witget_style](https://user-images.githubusercontent.com/31522242/29947734-87388e0c-8eab-11e7-98d4-c8142a1cbfef.JPG)
Breeze:
![breeze_witget_style_2](https://user-images.githubusercontent.com/31522242/29947864-18581d44-8eac-11e7-9d9d-2bf29cff042e.JPG)
Fusion:
![fusion_witget_style_2](https://user-images.githubusercontent.com/31522242/29947902-43cd58f4-8eac-11e7-889e-e4bd768caba8.JPG)

**Comment by tsujan** [comment]
@l3x13 You say that it happens with breeze but doesn't happen with Fusion for you? However, in @stefonarch's screenshot, the menu is drawn by neither breeze nor fusion but the stylesheet.

**Comment by tsujan** [comment]
In `lxqtmainmenu.cpp`, we have:
```cpp
menu->setAttribute(Qt::WA_TranslucentBackground);
```
My theory is that stylesheet (and, perhaps, breeze) has a problem with `WA_TranslucentBackground`.

**Comment by l3x13** [comment]
@tsujan With Fusion witget style, search works indeed fine. 
But you can also in my screenshots notice , the black bar in the menu while searching with breeze witget style active. That's also is not happening with fusion active.

**Comment by tsujan** [comment]
OK. So, for some reason, Breeze and stylesheet have a problem with drawing a menu that has the `WA_TranslucentBackground` attribute but Fusion and Kvantum don't. My point is that the issue is not in the menu itself. Whether a workaround could be added for this is another question (about which I'll think).

**Comment by tsujan** [comment]
What about QtCurve?

**Comment by l3x13** [comment]
I think Breeze is not using a translucent menu, at least it is not visible. QtCurve has no problem, also Windows is having no problems.
So I think too this has something to do with Breeze, Fedora is using Breeze by default, Manjaro is using something what looks like breeze but with different colors, I believe it's called breathe. so i'm very curious what stefonarch is using as witget style.

**Comment by tsujan** [comment]
I won't be surprised if Breeze has a problem. However, stylesheet belongs to Qt itself and apparently, it has the same problem too. Most LXQt themes are drawn by stylesheet, so this is bad for LXQt.

**Comment by tsujan** [comment]
> so i'm very curious what stefonarch is using as witget style.

Whatever widget style he may have, his menu and panel aren't drawn by it. That's while your menu IS drawn by the active widget style.

**Comment by l3x13** [comment]
I not exactly know what he is using for panel drawning, but the behaviour is the same.
Maybe that is making it even stranger and more difficult to investigate.
I'm almost new to linux so have to learn a lot, but after seeing this behaviour and when it was happening and when not, I throught this could be helpfull information.

**Comment by l3x13** [comment]
This bug is the same: https://github.com/lxde/lxqt/issues/1333
from the screenshot I can see, he is using Manjaro.

**Comment by stefonarch** [comment]
I didn't understand anything, but will test fusion for some days. I've always this corrupted menu search after a day.

**Comment by tsujan** [comment]
> I didn't understand anything, but will test fusion for some days.

Your screenshot shows that you use an LXQt theme; don't you? Your main menu doesn't look like menus of VLC, pcmanfm-qt, qupzilla, etc. That means, there will be no difference if you use Fusion because the main menu isn't drawn by Fusion or Breeze in you case.

**Comment by l3x13** [comment]
@tsujan On what base you're assuming stefonarch is using something else for drawning the menu?
For what I can see from the screenshots, he is using the default dark theme with a different icon theme.
As he is saying, he will use Fusion now for some days, he confirms using normally a different style witget.

I'm now testing with Lubuntu Next, with breeze witget style and Lubuntu icons, search **was** working normal. With using Breeze witget style + Breeze or Oxygen icons, the strange search behaviour occurs again. So it seems icons are involved too. Even stranger is, after switching back to Breeze witget style and Lubuntu icons, I was not able to get search working again. So I did a fresh install, select Breeze witget style again, together with Lubuntu icons, and search was working well.

**Comment by tsujan** [comment]
> On what base you're assuming stefonarch is using something else for drawning the menu?

I explained above.

> For what I can see from the screenshots, he is using the default dark theme

Which is a stylesheet, neither breeze nor fusion.

**Comment by l3x13** [comment]
Maybe I'm not understanding you right, but he can use the following: 

Dark LXQt theme.
Different witget style (breeze?)
Different icons

I'm using:

KDE-Plasma LXQt theme
Breeze witget style
Breeze icons

So I can not see from his screenshot a difference between what he is using and what I'm using, until stefonarch is confirming he is using/doing something else for menu drawning.

@stefonarch Can you please tell us what are you using as LXQt theme, witget style, icons and font style and size?

**Comment by tsujan** [comment]
Qt doesn't consult the active widget style (fusion, breeze,..) for those parameters that are included in a stylesheet.

**Comment by stefonarch** [comment]
Just checked on my laptop: menu  search was usually corrupted after cold boot with breeze widget style,  it's   also with oxygen I see, but NOT with Kvantum or fusion. Could test the other widget styles after.

**Comment by tsujan** [comment]
It's hard to know how breeze/oxygen could cause this but I don't see any problem in our main menu. setting `WA_TranslucentBackground` to `true` is not only valid but needed; I still think that breeze's problem is with `WA_TranslucentBackground`.

**Comment by tsujan** [comment]
In the screenshot in https://github.com/lxde/lxqt/issues/1333 (resized and attached below) and also in @l3x13's screenshot, a part of the background is totally black, which shows the transparency isn't respected, while the menu size/position is wrong. My hypothesis can be tested by setting `Qt::WA_TranslucentBackground` to false in `lxqtmainmenu.cpp` temporarily and using breeze but I don't have time for that.

![mainmenu](https://user-images.githubusercontent.com/981076/29970257-1e651c18-8f39-11e7-90d7-c9845da62e50.png)

**Comment by stefonarch** [comment]
I could test this , but do not see where to set false in

```

static void setTranslucentMenus(QMenu * menu)
{
    menu->setAttribute(Qt::WA_TranslucentBackground);
    for (auto const & action : menu->actions())
    {
        if (QMenu * sub_menu = action->menu())
        {
            setTranslucentMenus(sub_menu);
        }
    }
}
```

**Comment by tsujan** [comment]
@stefonarch 
As this:
```cpp
menu->setAttribute(Qt::WA_TranslucentBackground, false);
```
It can also be removed but this is just for testing.

**Comment by stefonarch** [comment]
Done, rebooted, still the same issue. 
Actually it is always present when rebooting, but closing session and login again has the same result as restarting the panel: the issue disappears for some hours. There should be something which triggers it again, but as said in the beginning: no idea.

**Comment by tsujan** [comment]
Strange! Then, I have no clue how Breeze could do it.

**Comment by l3x13** [comment]
The application menu with breeze will horizontal always remains the same size when searching. With fusion it's variable on how much space is needed to display the search output. So the black part is actually the application menu with a part where nothing is to display. So when search is working and you're searching for an application with a verry short name, the black part is bigger then when searching for application with long name.

**Comment by stefonarch** [comment]
Maybe I've found some elements. The combination of sytem theme (or my own "simple" theme which is similar) + breeze widget style does not trigger this issue (for testing I have to use reboot, restart session does fix actually as said before).

So it's somehow the mix between all themes except system + breeze/oxygen widget style. What happens is that the visible menu get's just "lowered" leaving nly "accessories" at the end visible but in fact clicking it it's firefox. Some screens  explain more:
[coming have to reboot]

Interesting is the behavior when backspace is used to cancel just one letter:
![schermata02](https://user-images.githubusercontent.com/10681413/29986040-050dffa4-8f62-11e7-9f4b-84bd22b2adb9.png)

**Comment by stefonarch** [comment]
I've boiled it down to commenting out this part in theme (only  tested with the dark theme):
```

/*#MainMenu ActionView {
    border: none;
    background: black;
    color: white;
}
*/
```
Tested also for all the lines, all three have to be removed. Why this is connected to widget style it's sure not me who can answer that.

Visual effect is not very different, scrollbar is white, transparency is lost:
![schermata01](https://user-images.githubusercontent.com/10681413/29987697-c5f716b8-8f69-11e7-8d5e-4b274a05ff20.png)

**Comment by tsujan** [comment]
I remembered that this wasn't the first time we encountered a problem in Breeze. See [this](https://github.com/lxde/lxqt/issues/1109) and [this](https://bugs.kde.org/show_bug.cgi?id=368048).

The last time, it was said, "...this is some sort of conflict between setting a stylesheet, and setting the WA_TranslucentBackground flag. So really, something fishy with Qt..." However, I don't think that's correct because Kvantum didn't have the issue. Both then and now, the problem is in Breeze (and Oxygen).

For now, life problems may not let me look deeper into this issue (and also the workaround used for the previous one).

**Comment by tsujan** [comment]
An explanation about why I thought this was about translucency:

While handling translucency was a piece of cake with Qt4, it became tricky with Qt5 (https://bugreports.qt.io/browse/QTBUG-34064). The problem isn't acknowledged by Qt devs yet. It seems that only the developer of QtCurve and I (in Kvantum) had to deal with it (in different ways).

With that background, I had a strong reason to be suspicious about `WA_TranslucentBackground`. Actually, I haven't changed my mind completely yet.

**Comment by stefonarch** [comment]
I had still the panel runnign with 

`menu->setAttribute(Qt::WA_TranslucentBackground, false);
`
 and actually maybe something is changed: search is still corrupt at  reboot but then never seem to corrupt again - usually after some days I found it corrupted. So I recompiled now the original panel and will check it for some days.

**Comment by stefonarch** [comment]
Nothing, it is stable after restarting it once also without "false".

**Comment by technic** [comment]
Hi. We had similar shit some time ago https://github.com/lxde/lxqt/issues/1109

**Comment by micrococo** [comment]
Hi.

I can reproduce the corruption issue by using the Breeze widget theme **and** applying a color, background color, or alternate background color directly to the `QLineEdit` or `ActionView` in the main menu. For example:
```
/* This corrupts the menu and the QLineEdit */
QLineEdit  { background-color: whatever; }
ActionView { background-color: whatever; }

/* This works */
#MainMenu QLineEdit  { background-color: whatever; }
#MainMenu ActionView { background-color: whatever; }
```
If I run the panel from a terminal and open the menu, I can see messages like the one below when using the style that triggers the corruption:
```
(0x7fffc5fc1ee0) Warning: QXcbConnection: XCB error: 8 (BadMatch), sequence: 4166, resource id: 27263139, major code: 130 (Unknown), minor code: 3
```
Sometimes it fails just after selecting a theme applying the style directly to the `QLineEdit` or the `ActionView` (there is none among the themes supplied by LXQt), but sometimes it fails when you restart the panel. It seems that no other component is affected by this issue.

**Comment by tsujan** [comment]
> If I run the panel from a terminal and open the menu, I can see messages like...

You could find tons of those messages related to KDE and/or Qt stuff by using `journalctl -b` -- and also by googling. They aren't ours and are pretty harmless. I've suppressed them by adding this to "/home/pedram/.config/QtProject/qtlogging.ini":
```
[Rules]
*.warning=false
```
The problem is in Breeze and doesn't show up for all. Where is it in Breeze's code? I don't know (and don't care).

IMO, this issue can be closed.

**Comment by micrococo** [comment]
Not being a LXQt issue, I agree with @tsujan in that it should be closed. I just wanted to add a note for theme makers.

**Comment by tsujan** [comment]
@micrococo I think Breeze's behavior is random, although it may be predictable for certain users.

Anyhow, there is this open issue, whose link I'd attached above: https://bugs.kde.org/show_bug.cgi?id=368048
