### ISSUE TITLE
Application menu shows distorted results while performing search operation

### ISSUE THREAD

**Issue by aliwaris0572** [lxqt/lxqt#1333]
The 'application menu' widget under Panel shows distorted results when any search is performed.
Please have a look at the following [link](https://ptpb.pw/NE7A.png) for the issue.

##### Expected Behavior
The search results must be displayed properly without any distorted UI

##### Steps to Reproduce (for bugs)
1. Add application menu widget to LXQT panel.
2. Click on menu icon.
3. Under the search bar, type any existing installed application's name to search.
4. Observe the search results.

##### System Information
> uname -a

Linux manjaro-pc 4.9.39-1-MANJARO #1 SMP PREEMPT Fri Jul 21 08:25:24 UTC 2017 x86_64 GNU/Linux

**Comment by tsujan** [comment]
Do you use the Breeze widget style? Does the problem happens with another widget style too?
