### ISSUE TITLE
Calculator in lxqt-runner could use also "enter" beside  "=" for showing results

### ISSUE THREAD

**Issue by stefonarch** [lxqt/lxqt#1342]
It's a little annoying using the numlock pad and have to press shift+0 (italian layout for =)to complete results. It's more a feature request.

##### Expected Behavior

Would be nice if "enter" would do the calculation too.

##### Current Behavior

Only keysymbol = concludes calculation.

**Comment by tsujan** [comment]
Maybe, but we can't be sure or make an exception for "*".
