### ISSUE TITLE
plugin-taskbar: Please add window previews/thumbnails

### ISSUE THREAD

**Issue by wp9015362** [lxqt/lxqt#135]
Hello,

the Microsoft Windows 7 Taskbar for example has window previews, so called "Taskbar Thumbnails", see for example:

http://msdn.microsoft.com/en-us/library/windows/desktop/dd378460%28v=vs.85%29.aspx#thumbnails

and/or have a look at the following video for example:

http://www.youtube.com/watch?v=gWwJmc2tsVk

Additionally, and that's not shown in the pictures/video mentioned above, is that in Microsoft Windows 7, if the mouse cursor hovers over the previews/thumbnails, a close button (X) appears in the upper right corner of the preview/thumbnail, see the following picture for example:

http://blogs.msdn.com/blogfiles/e7/WindowsLiveWriter/SomeChangesSinceBeta_12A10/clip_image004_2.jpg

Please implement such a button as well, so that the windows are closable directly from the previews/thumbnails.

It would be much appreciated.

Regards

**Comment by YamashitaRen** [comment]
Hello,
Sorry for reopening the issue but is this really how it works ? (no-clue-guy, here)
Afaik, only Compiz works like that (and it's buggy).
On Cinnamon, you have to use a dedicated applet : https://github.com/linuxmint/Cinnamon/issues/2348
And on Plasma5, it is activated in the taskbar preferences : http://ubuntuforums.org/showthread.php?t=2275486&p=13273041#post13273041
Same in a certain dockbarx (never used it) : http://askubuntu.com/a/17291

All of this certainly rely on a compositing/window manager (like kwin), but doesn't it have to be "linked" to the taskbar, somehow ?

**Comment by jleclanche** [comment]
@PCMan I'm not sure this is a WM feature.. the WM doesn't know when we're hovering taskbar items does it?

**Comment by pmattern** [comment]
@PCMan 
> Just change your WM to compiz and you can have that. 

Could this eventually be some misunderstanding? Having a look at Compiz 0.9.12.2 on Arch Linux the only window preview I could find was the one from its "Application Switcher". But the panel which is what this issue is meant to address wasn't affected by Compiz in any way.

**Comment by YamashitaRen** [comment]
@pmattern 
http://askubuntu.com/a/227166
Don't remember if it's really there but I can confirm that I used this plugin no less than 3 months ago.

**Comment by pmattern** [comment]
@YamashitaRen 
Plug-in (?) "Thumbnail Window Previews" as described in the link you posted indeed does the trick so my assumption that Compiz isn't interacting with panel plugins was wrong.
@PCMan Sorry for the noise.

On a side note those previews don't seem to work when grouping is enabled in plugin-taskbar.
Also, if anything should be changed in LXQt with regards to this topic the feature should definitely be toggable and probably disabled by default as it tends to counteract LXQt's aim to be lightweight.

**Comment by kq01526** [comment]
Any update?

**Comment by palinek** [comment]
> Any update?

Nope.
