### ISSUE TITLE
[lxqt-panel] Remove the deprecated plugin-clock

### ISSUE THREAD

**Issue by palinek** [lxqt/lxqt#1356]
Just not forgetting to remove the plugin-clock in the 0.13.0 release.

##### Expected Behavior

No plugin-clock, only the plugin-worldclock will be available.

##### Current Behavior

There are 2 "clock" plugins.

##### Possible Solution

Remove plugin-clock completely from the source tree.

##### Steps to Reproduce (for bugs)

n/a

##### Context

n/a

##### System Information

n/a

**Comment by tsimonq2** [comment]
I can either do this in my upcoming PR or right before release.

When would be best?

**Comment by palinek** [comment]
IMO...it can be done ASAP, as the release was issued

**Comment by tsimonq2** [comment]
Before this can be done, worldclock lacks a couple of features that clock has. I plan on moving some code over and making worldclock completely functional **before** removing clock code.

Please, I'm self-assigning this and I plan on actually getting it done... I'm busy but it'll get done before the 0.13 release if not well before... don't steal my project... :wink:

**Comment by agaida** [comment]
it was not the project - it is a closed bug

**Comment by tsujan** [comment]
As someone who has always used worldclock, I'm curious to know what those features are.

**Comment by tsimonq2** [comment]
@agaida Project in the sense of task.

@tsujan Hovering should display what clock normally displays on hover, the widget should autoresize when the text is made bigger than the current space it is using, and the UI could do with some tweaking... that's just what I can think of now.

**Comment by tsujan** [comment]
OK. Looking forward to your PR(s).

**Comment by tsujan** [comment]
Oh, and I found a crashing bug, which I'll report and (probably) fix.

**Comment by tsimonq2** [comment]
@tsujan Please ping me when that's fixed, I think I've been having the same issue and it's preventing me from working on the PR...

**Comment by tsujan** [comment]
Sure. I encountered it 3 weeks ago. It was about (removing?) time zones.

**Comment by palinek** [comment]
> Hovering should display what clock normally displays on hover

This is a 5 minutes work :)

> the widget should autoresize when the text is made bigger than the current space it is using

As the author of this "feature" I think this shouldn't be pulled into the `worldclock`. As the `worldclock` provides "Advanced manual format" and the user should set it properly to show what needs to be shown.

**Comment by tsujan** [comment]
@palinek I don't know what you and @tsimonq2 mean by "auto-resizing" exactly but worldclock has a bug (other than the one I mentioned above) that cuts the text after the font size is made bigger in its format -- until the panel is restarted. IMHO, this should be fixed -- no widget should require panel restarting for proper functioning.

**Comment by tsujan** [comment]
The same thing happens when the text is made longer.

**Comment by stefonarch** [comment]
Worst is the truncated text until panel restarts.
It also doesn't apply some changes immediately (e.g. "without leading zero).

**Comment by palinek** [comment]
@tsujan @stefonarch  have a look in lxde/lxqt-panel#438, please

**Comment by tsujan** [comment]
@palinek Thanks! Will test it tonight.

**Comment by tsujan** [comment]
Now, with @palinek's patch, the size is updated correctly. So, only one problem remains -- which I'll try to remember ;) and fix -- and @tsimonq2 or @palinek could add that hover thing (of which I have no idea -- a tooltip?).

Almost perfect :) Even KDE doesn't have such a good clock (KDE's clock doesn't rotate with vertical panels, among other things).

**Comment by stefonarch** [comment]
Size works, but actually I wonder what time zones are for when only one is displayed and to change it you have to click three times. I don't use them bit I guess somebody would like to see them all, maybe with click together with the calendar  or on mouseover.

**Comment by tsujan** [comment]
@stefonarch Good point! Such details can be fixed/improved in PRs. No program is ever complete. By "perfect", I just expressed a good feeling ;)

**Comment by stefonarch** [comment]
Read again, I edited.

**Comment by stefonarch** [comment]
Thinking more about it: 
- the third tab in configuration dialog (containing only the rotarte option) could be eliminated and integrated in the first one.
- move  "time zones" in the second tab to the bottom to have the order hour > date > timezone
- change name just to "clock" at the end, "world clock" makes no sense when there is only one clock plugin IMHO

**Comment by tsujan** [comment]
> "world clock" makes no sense

I can't agree on this. It is a world-clock because of time zone functionality.

**Comment by tsimonq2** [comment]
@palinek Thanks for the PR, and it's no problem, but I kind of wanted to do it all in one PR so we don't have the trivial elements taking up time in separate PRs... In fact, I'd like to do this with the rest of the items myself :)

Again, I'd like to take this task... :)

> the third tab in configuration dialog (containing only the rotate option) could be eliminated and integrated in the first one.

I did this in my PR that I submitted (but got rejected) because of the rename in the panel plugin.

> move "time zones" in the second tab to the bottom to have the order hour > date > timezone

This is a good idea, I'll implement it unless anyone speaks up.

> bigger size for customization window showing all stuff

This should be done in the UI rework.

**Comment by palinek** [comment]
> Again, I'd like to take this task... 

@tsimonq2 go ahead, I just had a quick look on the "cut problem" and after few debugs the simple solution came...

> change name just to "clock" at the end, "world clock" makes no sense if there is only one clock plugin IMHO

@stefonarch we decided to rather not rename things (something existing to something other, that already existed also), because of user, configuration etc. confusion

**Comment by stefonarch** [comment]
Other small  issue to correct: the title of the custom display format window is misleading in lxqtworldclockconfiguration.ui" line="14" :
` <property name="windowTitle">
   <string>World Clock Time Zones</string>
  </property>`

Should be "Custom Date/Time/Timezone Format Syntax" or similar.

**Comment by excalibur1234** [comment]
while you improve the clock/worldclock, i have a couple of ideas to improve it:

when you right click on the clock, you get a calendar (this is really useful). the leftmost column shows the number of weeks (this is useful, too).
but when the number of weeks is below 30, it can be a little confusing to read the calendar. can you mark the number of weeks visually somehow (in order to differentiate it from the days of the month)?

----------------------------------

on my system, the calendar in "clock" marks today but "worldclock" does not (unless i do an extra left click on the calendar).
is the same bug present on your system, too?

**Comment by tsimonq2** [comment]
@stefonarch:

> Other small issue to correct: the title of the custom display format window is misleading in lxqtworldclockconfiguration.ui" line="14" :
> <property name="windowTitle"> <string>World Clock Time Zones</string> </property>
> 
> Should be "Custom Date/Time/Timezone Format Syntax" or similar.

Good point, I'll correct. Thanks!

@excalibur1234:

> but when the number of weeks is below 30, it can be a little confusing to read the calendar. can you mark the number of weeks visually somehow (in order to differentiate it from the days of the month)?

Good point, I can do that as well.

> on my system, the calendar in "clock" marks today but "worldclock" does not (unless i do an extra left click on the calendar).
> is the same bug present on your system, too?

Not here, but I'm running the latest tip of Git. What LXQt version are you running?

**Comment by tsujan** [comment]
> when you right click on the clock

You mean left-click.

> on my system, the calendar in "clock" marks today but "worldclock" does not

Not here.

> can you mark the number of weeks visually somehow

I don't understand. The calendar, here:

![calender](https://user-images.githubusercontent.com/981076/32092754-ab1cc86a-bb06-11e7-96a6-71a587f8f529.png)

**Comment by tsujan** [comment]
BTW, any change in colors should follow palettes and if the bg is set, the fg should be set too. Don't rely on Fusion or Breeze to see if colors are OK!

**Comment by Chiitoo** [comment]
Indeed, it can look like the week and day areas are one and the same, but it seems to depend upon the theme being used.  The 'Dark' theme is pretty good with regards to this, but for example 'Frost' and 'Kde-plasma'... not so much.  The light themes that I have are not much better.

There could be a 'hard line' between, I maybe guess.

As for 'marking today', it does seem to do that for me.

**Comment by tsujan** [comment]
Yes, it depends on the theme. That's the standard calendar of Qt and all colors are chosen based on the current palette when the widget isn't styled by stylesheets. Some themes have palettes that create low contrasts but that's *their* problem.

**Comment by tsujan** [comment]
More specifically, the background color for weak days is the alternate base color (`QPalette::AlternateBase`). The contrast between base and alternate base colors should be low but enough for them to be distinguished from each other visually. That's up to the theme.

**Comment by excalibur1234** [comment]
i use lxqt 0.12 from arch linux (=manjaro unstable branch) and not the git version of lxqt. i have switched from "clock" to "worldclock" in my panel.
i use the  breeze-dark as gtk2 widget theme and have set the lxqt theme to "system". as you can see, the day is not marked in the calendar:
https://i.imgur.com/AcIhntz.png
when i left click on the calendar, the day is marked.
i have seen the same bug in the config menu, which means it is probably a bug in the theme and not the clock/worldclock.

but you can also see in my screenshot above that it is really hard to differentiate the number of the week from the days of the month. in my opinion, this is the most important usability improvement.

**Comment by tsujan** [comment]
Yes, it should be a bug in that style engine, whether for the inactive highlight color (that marks the current day) or for the alternate base color (weeks).

Breeze and Oxygen may also show minor problems with some color schemes. Fusion and QtCurve are acceptable (except for their lack of support for symbolic icons -- arrows). Kvantum should be always OK (or I'll get a bug report). All in all, it seems that this Qt widget can be used as a test for different Qt style engines :)

**Comment by tsujan** [comment]
Now that we pay attention to such details, I should say that, actually, there's something that can hardly be seen as a problem but is worth considering. I explain it with images. This is the "real" Qt calendar:

![real_calendar](https://user-images.githubusercontent.com/981076/32108409-72678040-bb3e-11e7-8e4f-ade50a6b499e.png)

The background color of the current day (27) is the *active* highlight color of the Qt theme I use, which is OK. But, this is the LXQt calendar:

![calendar](https://user-images.githubusercontent.com/981076/32108450-97915922-bb3e-11e7-9c40-35a700100055.png)

Here, the background color of the current day is the *inactive* highlight color, which is different from the active one in the theme in question. This means that the days widget is inactive. IMO, it should be the active widget. There's no need to subclass the Qt calendar to "solve" this.

**Comment by tsujan** [comment]
In fact, it seems that the whole calendar is inactive on showing, which explains excalibur1234's observation about left clicking. Again, this isn't a bug, IMO, but is worth considering.

**Comment by tsimonq2** [comment]
@tsujan So the point about the week numbers is that it's not that obvious which is the week number or what.

I propose adding some text to the left of "Sat" (or whatever your locale chooses to be first) indicating that those are in fact week numbers.

**Comment by tsujan** [comment]
> So the point about the week numbers is that it's not that obvious which is the week number or what.

How? From all the above screenshots it's quite obvious the we're in the 43rd week of the year; isn't it? The problem @excalibur1234 mentioned is in the theme, not in the calendar.

Adding the string "Week" (or whatever its translation is) would clutter that nice GUI. I think it isn't worth subclassing.

**Comment by tsimonq2** [comment]
> How? From all the above screenshots it's quite obvious the we're in the 43rd week of the year; isn't it? The problem @excalibur1234 mentioned is in the theme, not in the calendar.

It gets confusing because when the week gets below 30 it looks peculiar.

Maybe it's a theming thing, I don't know, but I agree that (whatever it is) **something** should be changed there.

**Comment by tsujan** [comment]
> It gets confusing because when the week gets below 30 it looks peculiar.

I, for one, see nothing peculiar in that.

> something should be changed there.

I'd say "nothing" if I didn't find that "something" ;)  Let's pay attention to the practical side:

The calender's window flag is bad. When the calendar is shown, no shortcut can be used and still, its window is inactive. The `Qt::Popup` flag is there for hiding the calendar when somewhere is clicked. I think it's better to achieve the same result in another way. I also think this could be the subject of a bug report.

**Comment by dlocklear01** [comment]
I use LXQt 0.12 ( on ROSA R10 ).     I am not a novice, but my computering is limited to playing FreeCell in Aisleriot Solitaire, and surfing the web.     I probably have about 600 man-hours of usage in LXQt and about 1,000 man-hours in Linux overall doing those 2 simple task above.     I have not switched to another desktop environment, although I have briefly tried Gnome, Plasma, Cinnamon, MATE, Openbox, XFCE, LXDE, Lumina and Enlightenment.     However, I used my Android 6.0 phone extensively, and I also sometimes tinker with my kid's Chromebook ( and plan to buy one for regular use for myself ).   I am also planning on buying a really nice Android tablet in a few months.     What I mean, is I do not expect my desktop usage to increase.    I am 54 with little spare time.   I have no idea how to code or package.      I guess my point is that that is my background and I look forward to LXQt 0.13.     But I look around and see Plasma is almost lightweight and getting Wayland support.     So I wonder to myself, if I should distro-hop and give the newest Plasma a fair shake.     I really do not need more than LXQt has to offer ( as far as I know ).     Thank you all for making LXQt 0.12

**Comment by tsimonq2** [comment]
Good point, I'll open a separate issue about this.

Thanks @johndoe71rus.
