### ISSUE TITLE
more XDG like configuration handling

### ISSUE THREAD

**Issue by agaida** [lxqt/lxqt#1369]
##### Expected Behavior
We should improve our configuration handling at all - that means at least that configurations are read from these places (iirc):
I /usr/share/$foo/$bar.conf
II /etc/xdg/$foo/$bar.conf
III /etc/$foo/$bar.conf
IV /$HOME/.confit/$foo/$bar.conf

##### Current Behavior
/etc/xdg/ and /$HOME/.config are implemented mostly

##### Context
Making distributions and packagers love us isn't that bad, isn't it?

**Comment by agaida** [comment]
Suggestion - placing the configuration handling in qtxdg might be a good idea

**Comment by tsujan** [comment]
I agree.

**Comment by palinek** [comment]
There is nothing to do in this area.... the Qt's `QSettings` (which we're using) does support reading from multiple directories since 5.9. The only thing to do is properly set the `XDG_CONFIG_DIRS` ... in e.g. `startlxqt`

**Comment by agaida** [comment]
cool - so we should set them right if not done right now :)

**Comment by agaida** [comment]
@palinek - if there is nothing to do - why i don't see configurations read from
* /usr/share/$foo
* /etc/xdg/$foo
* /etc/$foo
* /$HOME/.config/$foo

in exactly this order? If there is "nothing" to do to achieve that, please let's do this "nothing". Now.

**Comment by palinek** [comment]
> If there is "nothing" to do to achieve that, please let's do this "nothing". Now.

As said before: _The only thing to do is properly set the `XDG_CONFIG_DIRS` ... e.g. in `startlxqt`_

**Comment by agaida** [comment]
@palinek thanks, the distribution packagers (me included) will love and praise you for that - serious, after that change we should move our upstream defaults to /usr/share and get out of the way so distributions can use /etc/xdg and or /etc (for leap distributions)

**Comment by agaida** [comment]
ok - solved (except lxqt-globalkeys and libfm-qt)
