### ISSUE TITLE
[feature-request] Configuration tool for all external applications

### ISSUE THREAD

**Issue by stefonarch** [lxqt/lxqt#1382]
At the moment there are 2 places for 2 (different) terminals: pcmanfm-qt and "default terminal" in session settings (no idea where the latter has any effect), another place for the window manager, in pcmanfm-qt the setting for archive tool and the default browser in session settings too.

##### Expected Behavior
It would be nice to have just one section in session settings or a new "Preferred applications" settings tool that includes them all and would also pop up at first run, similar as powermanagment does. 

It could include also [default screenlocker 
](https://github.com/lxde/lxqt/issues/1378#issuecomment-342027842), mail program and so on, I think to have seen a  similar tool  in LXDE.

**Comment by tsujan** [comment]
The default terminal of Session Settings and pcmanfm-qt Preferences are quite different. You might want to use a different terminal in pcmanfm-qt, especially when you use it under a different DE -- I always mention Enlightenment as an example because it's different from other DE's.

**Comment by stefonarch** [comment]
I have no idea where the "default terminal" should open, I open the terminal I want using the runner or the menu, usually I have always yakuake running. Can you give me an example where the "default terminal" opens?

**Comment by tsujan** [comment]
> Can you give me an example where the "default terminal" opens?

In Octopi, for example, although it also have a setting to override it. I guess the default terminal can't be as popular as the default browser.

**Comment by tsujan** [comment]
Also in desktop files, for which `Terminal` is `true`.

Should we close this?

**Comment by stefonarch** [comment]
Thanks, I'm not using either.
The terminal is only one of the external apps and I think that it pcmanfm-qt should open simply the default terminal too (maybe with an override option like octopi).
 I don't remember to which one it defaults at the moment, time ago I got an error message "xterm not found" or similar when hitting F4. 
Opened my LXDE VM, here is what I have in mind. In LXDE it's not perfect to as there are to item: "preferred applications"
![schermata-07-17-50-44](https://user-images.githubusercontent.com/10681413/32506322-8b767a7e-c3e4-11e7-878a-cb9c0dc40705.png)
 with just browser and email and the tool of the screenshot.

**Comment by tsujan** [comment]
> The terminal is only one of the external apps and I think that it pcmanfm-qt should open simply the default terminal too

I agree.

> Opened my LXDE VM, here is what I have in mind

I see now.

**Comment by tsujan** [comment]
Opened https://github.com/lxde/pcmanfm-qt/issues/594 for pcmanfm-qt.

**Comment by tsujan** [comment]
@stefonarch I was wrong about desktop files: every file manager may open them in its defined terminal when `Terminal` is `true` in them. However, that doesn't change anything.

Also, setting the default terminal as default in pcmanfm-qt was trickier than I thought.

**Comment by Vladimir-csp** [comment]
Terminal is a tricky thing to 'default' properly. It does not fit into a category of 'an application to open foo or bar'. There are issues of interoperability, configuration hierarchy, specific terminal emulator exec arguments and distinctive handling caveats.

There is a thread "Spec to define the default terminal?" on XDG lists and also my [proposal](https://github.com/Vladimir-csp/xdg-terminal-exec) of a spec and reference implementation.

Even if it will not manage to become a standard, feel free to adopt it's ideas.

For any other applications there is already XDG mime action spec, including 'x-scheme-handler' stuff, so there is no need to reinvent the wheel, just extend lxqt-config-file-associations in the right way.

**Comment by tsujan** [comment]
@Vladimir-csp I agree completely.

**Comment by tsujan** [comment]
We solved this last year.
