### ISSUE TITLE
Worldclock autorotate by default results in Clock the wrong way if panel is vertical

### ISSUE THREAD

**Issue by EinarMostad** [lxqt/lxqt#1386]
When I have a vertical panel and add the world clock, the clock is displayed in the wrong direction by default because "Autorotate" is set by default in the world clock settings.

![autorotate on by default means time is displayed wrong way](https://user-images.githubusercontent.com/33556631/32675399-255b53b6-c657-11e7-8e76-c22b253fe6eb.jpg)

##### Expected Behavior
A vertical panel should have the clock in a readable direction.

##### Current Behavior
The world clock is rotated.

##### Possible Solution
Set Autorotate to off by default

##### Steps to Reproduce (for bugs)
Add world clock to a vertical panel.

##### System Information

* Distribution & Version: Arch with LXQt 0.12
* Kernel: 
* Qt Version: 
* liblxqt Version:  0.12.0-1
* Package version: LXQt 0.12

**Comment by tsujan** [comment]
Left→Right becomes Bottom→Top. That's the right direction and quite readable -- I use it with a vertical panel for years. If you want a bigger font, you could use `font size="4"`, for example.

**Comment by EinarMostad** [comment]
I get that, but it just seems counter-intuitive to me. It is not a serious problem, and easy to fix if the user wants to, but it seemed like a strange default to me as a regular user.

**Comment by tsujan** [comment]
> it just seems counter-intuitive to me

The reverse would be counter-intuitive to many. Since this is subjective, the word "fix" couldn't be used, IMO. Maybe, an option for reversing the default could be added but it doesn't seem popular enough.

**Comment by tsujan** [comment]
IMO, not only the current behavior isn't a bug but the requested behavior would be an issue.

**Comment by agaida** [comment]
@tsujan - full ack
