### ISSUE TITLE
Power Management Settings miss an "Ask what to do" option when power is low.

### ISSUE THREAD

**Issue by ghost** [lxqt/lxqt#1392]
It would be useful to have another option in the "When power is low then" menu that asked what to do when the power is low with the options listed in menu now. This way, I did not have to decide what to do until I get the warning that the power is low. If I am in the middle of a game at home, I would choose nothing and plug in my power supply, but if I am on the train on my way home from work, I would choose to turn off the computer.

![missing ask what to do option when power is low](https://user-images.githubusercontent.com/33556631/32676692-da3ef8ec-c65b-11e7-86f3-f5a9f1c4a9a3.png)

##### Expected Behavior
One more option to get asked what to do when power is low.

##### Current Behavior
No such option

##### Possible Solution
Add a new option.

##### Steps to Reproduce (for bugs)
Open Power Management settings in the battery tab

##### System Information

* Distribution & Version: Arch Linux
* Kernel: 
* Qt Version: 
* liblxqt Version:   0.12.0-1
* Package version:  0.12.0-1

**Comment by tsujan** [comment]
Implemented more than a year ago.
