### ISSUE TITLE
Desktop settings open dialogue does not default to my pictures folder

### ISSUE THREAD

**Issue by ghost** [lxqt/lxqt#1394]
I think it would be useful for new users not to have to go through their entire file system to find a desktop background. I think this open dialogue should use the Pictures folder set as a Personal folder by default, or maybe where the wallpaper is stored in the theme in use.

![open dialogue does not default to my pictures folder or lxqt wallpaper folder](https://user-images.githubusercontent.com/33556631/32677094-700a78aa-c65d-11e7-89ff-eab01f0133bb.png)

##### Expected Behavior
Open dialogue should go to the pictures folder set as a personal folder by default

##### Current Behavior
The dialogue opens at / (or was it ~?)

##### Steps to Reproduce (for bugs)
Right click desktop
Click "Browse" button to change wallpaper

##### System Information

* Distribution & Version: Arch Linux
* Kernel: 
* Qt Version: 
* liblxqt Version:   0.12.0-1
* Package version:  0.12.0-1

**Comment by tsujan** [comment]
With that file dialog (LXQt file dialog), I really don't think it's hard to find one's own wallpaper collection, unless one doesn't know where they are, in which case, finding them inside the file dialog is as easy as finding them with pcmanfm-qt.

**Comment by EinarMostad** [comment]
Yes, it is quite easy, but if I was a new user coming from Windows or Mac OS X, these kinds of small things would matter to me. Personally, I have no trouble finding my wallpaper folder, it is just that it would be even better if it was loaded by default.

**Comment by tsujan** [comment]
Ideally, it's good to:

(1) remember the last folder/file in all GUI elements that search for them; and
(2) have reasonable defaults.

This is about (2) and I agree with it.

**Comment by tsujan** [comment]
> it would be even better if it was loaded by default.

That's not possible because most users may not have a "wallpaper folder". Some LXQt themes come with a wallpaper.

However, it's acceptable to search for the Pictures folder and open it if it exists and if no wallpaper is set yet.

**Comment by Vladimir-csp** [comment]
There exists XDG_PICTURES_DIR which is the perfect default for opening file dialog in case the context is images.

**Comment by tsujan** [comment]
Qt also has its methods, which should be based on that. This is straightforward, I think.

**Comment by tsujan** [comment]
Was fixed a looong time ago.
