### ISSUE TITLE
Switching desktop with ctrl+F2 etc does not work. Openbox settings issue?

### ISSUE THREAD

**Issue by ghost** [lxqt/lxqt#1396]
I had LXDE installed before installing LXQt. Some of the keyboard shortcuts in the Global Actions Manager did not work for me. I could not switch desktops or task with the default keyboard shortcuts.

I tried changing the settings and changing them back to the defaults to force overwrite of a config file from the GUI, but they still did not work. I wonder if maybe the settings for Openbox in LXDE and LXQt somehow interer with each other?

![switching desktop with ctrl f2 etc does not work](https://user-images.githubusercontent.com/33556631/32677443-bcdb8f7e-c65e-11e7-871a-b7d0353ec482.png)

##### Expected Behavior
Default keyboard shortcuts should work.

##### Current Behavior
They do not.

##### Steps to Reproduce (for bugs)
Have LXDE installed. Install LXQt. Try keyboard shortcuts. Only some of them work.

##### System Information

* Distribution & Version: Arch Linux
* Kernel: 
* Qt Version: 
* liblxqt Version:   0.12.0-1
* Package version:  0.12.0-1

**Comment by agaida** [comment]
Installing multi DEs is never be considered a good idea. It might be that shortcuthandling is done by a different daemon like lxshortcuts (or how it is named) - so bad luck, nothing we want to do or can do.
