### ISSUE TITLE
Global Actions Manager window is too small by default

### ISSUE THREAD

**Issue by ghost** [lxqt/lxqt#1402]
The window is too small to display its contents by default. 

![window too small by default](https://user-images.githubusercontent.com/33556631/32678237-d5f082f0-c661-11e7-97f5-648fa4d22d4f.png)

Even after changing the size of the window to be large enough to show its content, the next time I open the same window, it is back to its original too narrow size.

![even after changing the size of this window on last open it opens too narrow next time](https://user-images.githubusercontent.com/33556631/32678287-0def44ca-c662-11e7-82f7-cb07170be67d.png)

##### Expected Behavior
Large enough window and wide enough columns to display most of the text in the window.

##### Current Behavior
Too narrow window and too narrow columns to display all the text.

##### Steps to Reproduce (for bugs)
Open Global Actions Manager

##### System Information

* Distribution & Version: Arch Linux
* Kernel: 
* Qt Version: 
* liblxqt Version:   0.12.0-1
* Package version:  0.12.0-1

**Comment by tsujan** [comment]
The window remembers its size now.
