### ISSUE TITLE
Power Management Settings should default to "Use icons from theme"

### ISSUE THREAD

**Issue by ghost** [lxqt/lxqt#1403]
When a user changes the icon theme, it would be intuitive that the icon of the battery applet on the panel changes as well. That is why I think "Use icons from theme" should be ticked by default in the Power Management Settings.

![use icons from theme should be ticked by default](https://user-images.githubusercontent.com/33556631/32678410-84d8f2de-c662-11e7-8209-02acfd5e4b82.png)

##### Expected Behavior
"Use icons from theme" should be selected by default

##### Current Behavior
It is not selected by default.

##### Steps to Reproduce (for bugs)
Open Power Management Setting in Battery tab

##### System Information

* Distribution & Version: Arch Linux
* Kernel: 
* Qt Version: 
* liblxqt Version:   0.12.0-1
* Package version:  0.12.0-1

**Comment by tsujan** [comment]
The settings are there. What should be the default is a matter of taste.
