### ISSUE TITLE
lxqt-runner: Switching entries fast after lauching lxqt-runner bring you back to top

### ISSUE THREAD

**Issue by tjbrn** [lxqt/lxqt#1406]
##### Context

After openning `lxqt-runner` and typing something, switching entries fast will bring you back to top

##### System Information

* liblxqt Version: `0.12.0-1`

#### Demonstration
![1](https://user-images.githubusercontent.com/10359351/32710743-70578664-c819-11e7-9387-101dc93f8ceb.gif)

Note that the expected behavior is, in this example, `PCMan File Manager` to be selected, but something bring the the focus back to the top.

##### lxqt-runner configuration
* Positioning: `Top edge of the screen`
* Show on: `Focused screen`
* Show list with: `5 items(s)`
* Store/show history: `false`

**Comment by tsujan** [comment]
Those items are `pcmanfm-qt-desktop-pref.desktop` and `pcmanfm-qt.desktop`, so the behavior is correct, at least in this case.

**Comment by tjbrn** [comment]
The unexpected behavior isn't the displayed options, is that, after pressing the `down` key, the focus move to top automatically, causing confusion when the user press the keys very fast

##### Example
I want to open `PCMan File Manager`, so I launch `lxqt-runner` , type `pcman`, press the `down` key and press `enter`.
In this case, the `Desktop` entry is the one that will be selected
(like in the gif)

**Comment by palinek** [comment]
I'm not able to reproduce this... the first item is selected only upon changing searched text

**Comment by stefonarch** [comment]
Cannot reproduce either. Maybe yo could test the behavior on a fresh user account?

**Comment by tjbrn** [comment]
> Maybe yo could test the behavior on a fresh user account?

I reproduced this in my usual desktop(from the gif demo) and in a semi-fresh `arch linux` installation(fresh lxqt), with few packages installed.

However, the unexpected behavior occurred much less in the semi-fresh setup.
While in one the behavior happens like 9/10 times, the other is 1/10 times(it was more hard to reproduce)

`ixqt` is default configured in the later mentioned

**Comment by tsujan** [comment]
OK, I can reproduce it now. If the arrow key is pressed fast, the second item won't be selected: it jumps to the first one. IMO, there's something wrong here.

BTW, my computer is very fast.

**Comment by tsujan** [comment]
> I suppose this happens because lxqt-runner still refresh the entries after pressing down key

This may be a correct explanation. When the down key is pressed, the app should wait until the view is refreshed completely and *only then*, the item should be selected.

**Comment by tsujan** [comment]
Off Topic:

The new LXQt was released and we're getting various reports about things we hadn't seen before. This is very good. IMO, (minor) releases should be made regularly, at least, for the sake of feedback.

**Comment by agaida** [comment]
Off Topic - you are absolutely right

**Comment by stefonarch** [comment]
Cannot reproduce in debian buster and in arch/latest github
Reopen if still present.
