### ISSUE TITLE
Gif/animated-wallpapers don't move

### ISSUE THREAD

**Issue by Serkan-devel** [lxqt/lxqt#1419]
I set a gif as wallpaper 

![](https://derpicdn.net/img/2015/9/3/972042/large.gif)

##### Expected Behavior

The wallpaper moves
##### Current Behavior

![2017-12-03-185130_1366x768_scrot](https://user-images.githubusercontent.com/16866642/33528064-9bbee66a-d85b-11e7-9b8c-db3197b31b40.png)
The wallpaper stands still
##### Steps to Reproduce (for bugs)

1. Download gif
2. set it as wallpeper
3. 
4. 

##### Context

Some people showed off wallpaper engine on Windows, while I thought that Linux and are open source, it could be implemented by default because it wouldn't have much overhead from the OS.
##### System Information

* Distribution & Version: Debian GNU/Linux 9.2 (stretch)
* Kernel: 4.9.0-4-amd64
* Qt Version: 5.7.1
* liblxqt Version: 
* Package version: 0.11.1

**Comment by tsujan** [comment]
The desktop module of pcmanfm-qt doesn't support gif animation. I added git animation to `lximage-qt` a long time ago but doing the same thing with pcmanfm-qt isn't possible.

**Comment by tsujan** [comment]
BTW, your LXQt is very old, although it would make no difference in this regard.

**Comment by Serkan-devel** [comment]
Is there a workaround on loser lxqt versions?

**Comment by Serkan-devel** [comment]
*lower

**Comment by tsujan** [comment]
> Is there a workaround on older lxqt versions?

No, there isn't.

Gif animation isn't something that can work automatically. A gif file consists of multiple images/frames. Gif animation on desktop would require -- among other things -- that the whole desktop would be updated in milliseconds, which might mean a significant CPU usage -- not a good idea for a lightweight file/desktop manager, IMO.

I haven't tried an animated gif background with KDE; does it work there? Do you know of a DE that supports gif animation for wallpaper?

> Some people showed off wallpaper engine on Windows

MS Windows users usually don't know about CPU usage ;) 8 years ago, you could show off Compiz (you can still have Compiz reloaded, which works smoothly with LXQt here); now you can show off KWin...

**Comment by Serkan-devel** [comment]
Would kwin be engough to influence the desktop background? KDE seems to utilize alot of dependancies.

**Comment by Serkan-devel** [comment]
But what does pcmanfm have to do with the desktop background?

**Comment by aleex5** [comment]
@Serkan-devel 
"pcmanfm" is what makes it possible to put a wallpaper and see the icons on the desktop

in lxde it's the same, the only way they could add something like that, would be to modify pcmanfm-qt, and if they add something like that, it should be able to be disabled, because "lxqt" is a stable and lightweight desktop, like lxde, but more modern

although something like this I do not find it important, it's more like something extra or optional
because things like that, even if you do not believe it, consume system resources and this desk is designed to be lightweight

**Comment by tsujan** [comment]
> Gif/animated-wallpapers don't move

In short, the won't ever. Even if someone implements gif animation for LXQt desktop, that will be against its being lightweight.
