### ISSUE TITLE
Improve lxqt-admin-user

### ISSUE THREAD

**Issue by agaida** [lxqt/lxqt#1423]
##### Expected Behavior
We should provide several fields for the comment or a hint which contents are expected.
Related to lxde/pcmanfm-qt/issues/617, see also https://www.cyberciti.biz/faq/understanding-etcpasswd-file-format/

##### Current Behavior
The name field is plain wrong, it is a combi field that can contain a set of comma-separated values. See picture 

##### System Information
* Distribution & Version: current, doesn't matter

**Comment by stefonarch** [comment]
No idea what this refers to, no "field" found.
