### ISSUE TITLE
Appearence: The default style for toolbar buttons isn't good

### ISSUE THREAD

**Issue by tsujan** [lxqt/lxqt#1424]
The default style is text beside icon and can take a lot of space. Please change it to "Only display the icon"!

When I fix https://github.com/lxde/pcmanfm-qt/issues/619, pcmanfm-qt's toolbar will be a spectacle with the current default ;)

**Comment by tsujan** [comment]
I think pcmanfm-qt's toolbar buttons shouldn't follow the general style (see https://github.com/lxde/pcmanfm-qt/issues/619#issuecomment-352194949) but, still, text-beside-icon isn't a good default. IMHO.

**Comment by stefonarch** [comment]
Maybe I'm some old-school but I'd like rather only text than only icons - you have to learn them but reading you should know from school.

One thing I'd change immediately is default button size of 400px to 250px >(just installed an arch from scratch with LXQt, 174mb after login)
But at the end I remember that on similar topics the answer was "that up to distros" -  although they  often don't care at all and use take defaults...

**Comment by tsujan** [comment]
> Maybe I'm some old-school but I'd like rather only text than only icons

The style can be changed by the user. What's somehow important is the default itself. IMO, the icon-only style is the most "natural" and text-beside-icon is the most terrible ;)

Moreover, as I explained elsewhere, this setting is easily overridden by the app and also by the style plugin, so it may be confusing to the user -- he/she changes it and sees no effect on many Qt5 apps. An explanation in the form of a tooltip isn't bad.

**Comment by aleex5** [comment]
@tsujan 
I have the same opinion, lxqt should only show the icons in the open applications by default, they should also change the width of the buttons, because by default they are too wide, this would give a more elegant and ordered to lxqt

**Comment by tsujan** [comment]
> they should also change the width of the buttons

That depends on the Qt style you use and isn't set by LXQt.

**Comment by aleex5** [comment]
@tsujan 
in fact, in the configuration of the taskbar it can be changed, by default it comes with a width of 400, I change it to 46 (when I have it in see only icons) and it looks pretty good

**Comment by tsujan** [comment]
@aleex5 This page isn't about the (panel) taskbar but about toolbars of Qt apps.

**Comment by aleex5** [comment]
@tsujan 
ok I got confused 
although what I said the same would give a better appearance to lxqt
