### ISSUE TITLE
No QML in LXQt

### ISSUE THREAD

**Issue by tsujan** [lxqt/lxqt#1433]
This isn't an issue report but my argument against QML in LXQt -- fortunately, it isn't used by any LXQt app up to this date. It might be followed by counter-arguments.

There is a logical rule that's very easy to understand; yet it's contradicted here and there:

**Don't presuppose any fixed value for any QStyle parameter -- whether it is an integer, a color or a Boolean -- because it is a PARAMETER!**

That means If you make a style hard-coded by setting a QStyle parameter in your GUI app, you should either consider the fact that the other related parameters aren't fixed (don't suppose that one of them should be 3px or `#fff`, as it may be in Fusion or Breeze) or set them to fixed values yourself. Otherwise, your app will have a bug -- it's a *GUI* app, after all (for a bug-free app -- in this sense -- with hard-coded styles see Cantata).

Now, this simple rule is contradicted by all QML apps. Perhaps, Qt developers realized that and started to make QtQuickControls2 independent of QStyle. However, that means a discrepancy in Qt and so, the inappropriateness of QML for desktop environments. To work around it, KDE devs want QML apps to "follow" QStyle by making programs like `qqc2-desktop-style` (because their Plasma is already based on QML) and I'm sure their work will be buggy in the above-mentioned sense because they've already proven that in Plasma5. Why QStyle is so difficult to grasp for some devs, I don't know.

And why am I pointing to this problem? Because I've made the best use of QStyle parameters in Kvantum by seeing them as what they're supposed to be, namely parameters, not fixed constants.

**Comment by tsujan** [comment]
BTW, our pcmanfm-qt is also bug-free, in this sense.

**Comment by tsujan** [comment]
Strangely enough, I haven't found a single section in Qt doc saying *explicitly* that QML has problem with QStyle, while I know for sure that it does. As if, the issue is swept under the carpet.

However, there is `QQC2StyleBridge`, which is, supposedly, "a style for QtQuickControls 2 that uses QWidget's QStyle for painting, making possible to achieve an higher degree of consistency between QWidget-based and QML-based apps." This, on the one hand, admits that there is an inconsistency and, on the other hand, is impossible as far as I know.

KDE is absorbing QML more and more. Even Breeze can't hide the visual discrepancy it creates. Whether KDE devs know about the issue and sweep it under the carpet or this is caused by an irreversible ignorance, I don't know. Apparently, the only pure Qt desktop environment is ours: LXQt. I hope it'll remain immune to similar mistakes.

**Comment by jubalh** [comment]
Actually I think something like this, after some polishing, might be good for the blog?

**Comment by tsujan** [comment]
@jubalh There's a suspicious silence (IMO) about serious side effects of QML. If you google it, you'll find pages that say how cool it is; KDE says the same thing while its platform integration is damaged by it. I try to break that silence from the my viewpoint, which is currently limited to QStyle. However, I think QML's disadvantages go beyond it -- a glance at the current state of KWin and Plasma5 proves that. If QML is discussed by others, I could learn more about other things -- memory/CPU usage, flexibility (Qt devs say it isn't so flexible), etc. So, an active blog would be ideal.

**Comment by jubalh** [comment]
Personally I think https://blog.lxqt.org/ is a good fit for such things, showing also the thoughts of the developers and not just announce new features or changes.

**Comment by tsujan** [comment]
It's OK to me too.

I'll try to mention more technical and not just descriptive reasons. I'll also try to code in QML and see it first hand but, of course, not for any real app. There's also the difference between QM1 and QML2. The latter seems not to use QStyle at all and, if so, can't be good for desktop apps under Linux.

**Comment by agaida** [comment]
blog entries are welcome :D

**Comment by tsujan** [comment]
As for me, whenever I find enough time.

**Comment by kupiqu** [comment]
I referred to these arguments in https://www.reddit.com/r/kde/comments/9p8uwm/open_a_friendly_and_constructive_discussion_about/

I hope KDE and LXQt devs participate in an open and friendly discussion, so both ecosystems benefit. From the user point of view I hope I can learn on these topics as well.

**Comment by tsujan** [comment]
@kupiqu I don't have time to reply on reddit but when I said "I'm sure their work will be buggy", it wasn't about KDE devs' *abilities* but about QML: it's simply impossible. However, KDE devs may think it's possible, so their work will have bugs.

I think QML fans will curse someone who doesn't want to accept QML. Not my concern, unless someone speaks in terms of `QStyle` as it is, not as it's used in Breeze or Fusion.

**Comment by kupiqu** [comment]
> @kupiqu I don't have time to reply on reddit but when I said "I'm sure their work will be buggy", it wasn't about KDE devs' _abilities_ but about QML: it's simply impossible. However, KDE devs may think it's possible, so their work will have bugs.
> 
> I think QML fans will curse someone who doesn't want to accept QML. Not my concern, unless someone speaks in terms of `QStyle` as it is, not as it's used in Breeze or Fusion.

I think this clarification is relevant, can I transcribe this to the reddit discussion?

**Comment by tsujan** [comment]
OK, I'll sign in to reddit and try it to see if the discussion could continue professionally. However, I've seen lots of cheap reddit comments here and there; so, no promise!

**Comment by kupiqu** [comment]
Thank you.

I tried to open the discussion in the most respectful way I could. I realy hope it continues that way.

**Comment by tsujan** [comment]
A year after I made this page, I have a better perspective, IMO.I summarize it here to use its link instead of repeating myself later.

Truths that Qt Quick fans usually don't tell:

Qt Quick for desktop means adding the overhead of QML/JS, creating an ugly discrepancy by introducing mobile-like UIs into a desktop environment, and being at the mercy of QQ's developers when problems happen. On the bright side, coding becomes like having fast food and you could have fancy animations without making them.

The overhead is usually rationalized by saying that "modern computers" don't have problem with it, as if you're free to waste resources once you know something is "modern". Also, ready-made animations are often used as a red herring (but I agree they may be important for mobiles).

The fast food part is the main attraction. Quite understandably, a closed-source programmer likes to spend less time on coding for the money he makes.

On the other hand, Qt with C++ means being closer to the source, knowing what happens under the hood, having more control, being able to work around most problems in Qt, and making faster and lighter apps while ensuring native looks for them. You have to be more patient, of course. I think all open-source programmers enjoy coding; otherwise, why sharing their codes?

**Comment by travankor** [comment]
Is there an update on this for Qt6? Currently, the only two ways to get hardware acceleration with Qt6 is either with QtQuick or QOpenGlWidget, the latter which is much more low-level. I don't think I've seen any QOpenGlWidget desktop apps yet. Secondly, QOpenGlWidget does not use the Qt scene graph renderer, which was one of the big features of Qt6.

Is having hardware acceleration even important from LXQt's POV? Gtk4 and Qt6 both touted hardware acceleration as a major improvement for custom animations and mobile/embedded hardware, but software rendering is of course fine for desktops (as long as you don't want graphical animations in your application). Laptops are similar to desktops, with the exception that  power consumption is higher with software rendering (how much depends on what and how you are testing..).

**Comment by tsujan** [comment]
LXQt doesn't decide on these matters. Any app can be used under LXQt, QtQuick apps included.

This page was only about (not) using QtQuick/QML in LXQt's *code*. LXQt doesn't use animations anywhere — except for a simple and optional panel animation. Of course, you could use KWin with LXQt, with all its fancy animations; LXQt is "agnostic" toward these things.

**Comment by travankor** [comment]
I guess my question was whether it's possible to use hardware acceleration with LXQt apps, just to perform better. But since Qt essentially locked the feature to QtQuick/QML, this seems unlikely.
