### ISSUE TITLE
Normalize signal/slot signatures

### ISSUE THREAD

**Issue by luis-pereira** [lxqt/lxqt#1438]
QObject::connect() brings a severe performance penalty when not using
    normalized signatures. Signal lookup is first attempted with the signature
    as-is, and if that fails QMetaObject::normalizedSignature() called.
    
    That means, when using non-normalized signal/slot signatures, you not only
    pay for a strcpy(), but also for a doomed-to-fail first lookup attempt.
    Sure, connects are usually done during startup, and a profiler won’t show
    you, but using non-normalized signatures is hereby firmly put into the
    realm of premature pessimisation.

##### Expected Behavior
Normalized signal/slot signatures

##### Current Behavior
Some signatures are not normalized.

##### Possible Solution
Normalize it.

##### System Information

* Distribution & Version: all
* Kernel: all
* Qt Version: all
* liblxqt Version:  git
* Package version: git

**Comment by palinek** [comment]
This all is about the old Qt SIGNAL()/SLOT() notation, right?
Shouldn't we better move directly to the Qt5 C++11 notation, which is even faster?

**Comment by tsujan** [comment]
Like @palinek, I can't think of a scenario where it could be relevant to us. Could you please be more specific?

There are signal-slot connections with the old format in the panel code. I encountered them but didn't have time to change them.

**Comment by luis-pereira** [comment]
@palinek Right, the issue here was dev time to move to the new syntax. The normalization process is automated so, it would take almost no time.
Still can't reliably convert to the Qt5 C++11 signal/slot in an automated way, of course.

@tsujan Although I did understand @palinek  comment and you refer to it, I could not understand what you meant. p.s. no pun intended.

**Comment by tsujan** [comment]
@luis-pereira You almost quoted https://marcmutz.wordpress.com/effective-qt/prefer-to-use-normalised-signalslot-signatures/ and it's an old article about the old format/syntax.

**Comment by luis-pereira** [comment]
@tsujan Yeap. That's it. It's based on clazy warnings. That in turn are based on that article.
Old or not old, we are still using the old format so we are still [running that code](https://github.com/qt/qtbase/blob/41cdfbe3a473a4f691c193a58206d860cb9c676d/src/corelib/kernel/qobject.cpp#L2689).

**Comment by tsujan** [comment]
> we are still using the old format

That was why I agreed with @palinek : We should change the old syntax to the new one instead.

**Comment by luis-pereira** [comment]
@tsujan Me too. But that has to be done "by hand". I don'k know of any reliable automated way to do it. KDE has one script but... it's far from being reliable. Transition will take some time, unless we make a effort to make it happen.
The idea was to not suffer unnecessary penalties while we are moving to the new syntax.

**Comment by tsujan** [comment]
@luis-pereira I think there's a misunderstanding here, although I have no clue what it might be.

Anyhow, the correct approach is using the new C++11 syntax , as @palinek is doing it (and I'll do so if I find time). Of course, it should be done by hand; there's no automatic way for that.

**Comment by tsujan** [comment]
All signal/slots have been changed to the Qt5 syntax by @adjamhub. This can be closed.
