### ISSUE TITLE
Touchscreen support

### ISSUE THREAD

**Issue by valery-labuzhsky** [lxqt/lxqt#1459]
Precondition to all of below: do it using touchscreen

##### Steps to reproduce
1. Click the menu launcher
2. Select a submenu item, e.g. Preferences
3. Select a submenu, e.g LXQt settings
Current: LXQt settings disappears after a second or so along with Preferences
Expected: The submenu stay put, or at least doesn't disappear so quickly

### Can't resize dragging by corner
I've tried it many times and I'm sure it's shown me an arrow icon, but it just leave a window without any effect

### Simulate RMB
E.g. like in Windows: holding activates some interface feedback (gray square), RMB on releasing. Simply RMB on holding would be enough IMHO.
I know there is some Xorg settings that does it, but enabling it in some GUI, or autodetecting touchscreen would be great.

##### System Information
* Distribution & Version: Debian GNU/Linux 9 \n \l
* Kernel: 4.9.0-4-amd64
* Qt Version: not sure
* liblxqt0 Version: 0.11.1-1 
* lxqt version: 13

**Comment by tsujan** [comment]
Just wanted to add that I've seen the disappearance of submenus with *ordinary screens* and under some window managers too. It doesn't happen with GTK or Qt4 menus, so I think it may be a bug in how Qt5 handles X11.

**Comment by valery-labuzhsky** [comment]
It doesn't happen if you open a menu with touchpad btw, not sure what's the difference.

**Comment by tsujan** [comment]
> It doesn't happen if you open a menu with touchpad btw, not sure what's the difference.

Here, it doesn't happen with kwin but does with compiz. It isn't limited to submenus but happens with all windows with the "popup" flag. More interestingly, it doesn't happen when there's no other window.

We may be talking about different things but I think they're related to each other.

**Comment by tsujan** [comment]
On my 2nd computer, with Openbox, the Qt submenus also disappear shortly after their selection is cleared (by moving the cursor outside them). Touchscreen aside, this may be an annoying behavior of Qt5 menus -- as mentioned above, it happens neither with gtk nor with Qt4 menus -- because when the user opens a submenu, he/she wants to see it! Whether this behavior can be changed in `QStyle`, I don't know yet.

**Comment by tsujan** [comment]
Not reproducible anymore. And it was a Qt issue in the first place.
