### ISSUE TITLE
Library to control back light

### ISSUE THREAD

**Issue by selairi** [lxqt/lxqt#1460]
Hi,

I have written a library to control back light. It can be found in:

[https://github.com/selairi/lxqt-backlight](https://github.com/selairi/lxqt-backlight)

It is simple and it works in X11 and Wayland.
I would like to include in liblxqt. Then a simple widget for lxqt-panel could be written or back light can be changed when the laptop is unpluged.

What do you think?

**Comment by tsujan** [comment]
It would be great :)

**Comment by palinek** [comment]
Go ahead... consult the place, where to put it with @agaida

**Comment by tsujan** [comment]
I tried your program with Asus+Intel and it passed my tests. With an external monitor, it correctly saw there was no backlight setting and with the laptop monitor, it changed the backlight correctly (the setting persisted after a reboot). So, IMO, this should be included in LXQt.

BTW, if you add `Categories=Qt;Utility;Settings;DesktopSettings;LXQt;` to its desktop file, it'll appear on the Configuration Center, where it really belongs to.

**Comment by selairi** [comment]
> BTW, if you add Categories=Qt;Utility;Settings;DesktopSettings;LXQt; to its desktop file, it'll appear on the Configuration Center, where it really belongs to.

I have just updated. But the GUI is only an example. First of all, I want to include the library. Then, I think that the back light control should be a widget in lxqt-panel. But it could be in lxqt-config-brightness or in lxqt-powermanager. I would like to write a widget for lxqt-panel and a knob for lxqt-config-brightness. But, we must think about it.

**Comment by tsujan** [comment]
> Then, I think that the back light control should be a widget in lxqt-panel

An lxqt-panel widget would be nice. And yes, it could belong to the power management, on the panel too as a unified widget.

**Comment by selairi** [comment]
I have just added a new branch called "backlight" in liblxqt and in lxqt-config. Then I have added a new backlight control to lxqt-config-brightness.

If it is OK, I will push to master (pull-request) and I will start to write a lxqt-panel widget.

Thanks

**Comment by tsujan** [comment]
Yes, please make PRs!

**Comment by selairi** [comment]
> Yes, please make PRs!

I have just done it.

**Comment by selairi** [comment]
I think that the PR is stable enough, and it could be merged to master branch. 

Could I merge it to master branch?

**Comment by tsujan** [comment]
We usually wait for @agaida to test and merge PRs. He seems busy with the site now.

**Comment by selairi** [comment]
OK

**Comment by agaida** [comment]
i think this can be closed - @selairi?
