### ISSUE TITLE
Task manager does not always refresh icons

### ISSUE THREAD

**Issue by ChlorideCull** [lxqt/lxqt#1468]
##### Expected Behavior
Icon in the task manager widget of the panel should always reflect the icon of the window, assuming default settings.

##### Current Behavior
Icon sometimes doesn't update, unless you check and uncheck "Use icons by WindowClass, if available".

##### Steps to Reproduce (for bugs)
1. Install [Discord](https://discordapp.com/)
2. Enable "Open Discord" under Linux Settings, System Startup Behavior
3. Reboot
4. Note that Discord keeps the default icon in the task manager, but has a proper icon in the window bar

##### System Information
* Distribution & Version: Arch Linux
* Kernel: 4.15.12-1-ARCH
* Qt Version: 5.10.1
* liblxqt Version: 0.12.0
* Package version: 0.12.0-1

**Comment by agaida** [comment]
hmm - tbh i would call it expected behaviour.

**Comment by ChlorideCull** [comment]
@agaida: Even if not updating the icon in the task manager was expected behavior, it isn't consistent, because it *does* update if you launch Discord after boot by just running it.

Not updating would also be quite unexpected, it's something Windows does, and LXDE, KDE Plasma and XFCE does. Would be odd to not do it.

**Comment by tsujan** [comment]
I agree that if icons aren't updated correctly, that's a bug. We had a problem with texts but it's fixed now. BTW, I can't install Discord to test but other devs may know the cause.

**Comment by ChlorideCull** [comment]
![Visual example](https://i.imgur.com/1x2UOPe.png)

Attached a visual example.

I think the core thing which triggers it is that the window is open before the panel, so I'm not sure if the events which the panel expects to arrive actually do, since they might have already fired. `updateIcon()` seems to only be called when the `LXQtTaskButton` is created, and when a window change even occurs.

So, hypothetically, if `KWindowSystem::icon` returned null (maybe because `KWindowSystem` was unaware of the window), it would get the default icon, and it would stay that way because no window change events with a new icon would be sent.

That's just a hypothesis though, from looking at the code a bit and what could cause it to trigger.

**Comment by tsujan** [comment]
@ChlorideCull Do have this [commit](https://github.com/lxqt/lxqt-panel/commit/563d6bf3c66647554c90b7f490abee12dd294575)?

**Comment by ChlorideCull** [comment]
I'd assume not, since 0.12.0 was released before that commit. I'm building from git right now to test.

**Comment by ChlorideCull** [comment]
Yeah, seems like that commit (or some other one) fixed it.

**Comment by tsujan** [comment]
In the case of LXQt, the latest git is always the best.

**Comment by YamashitaRen** [comment]
Hello, I'm getting a similar issue on LXQt 14.1...
![Discorde](https://user-images.githubusercontent.com/4103637/57158358-85b8df00-6de3-11e9-902f-17b303c9e61b.jpg)

I am starting Discord after LXQt has fully started.
Discord starts with the proper icon in the taskbar. Once it has finished starting up, it switches to the default icon and stays like this.

**Comment by tsujan** [comment]
> Discord starts with the proper icon in the taskbar. Once it has....

The bug is fixed. What Discord may do is out of our control.

**Comment by YamashitaRen** [comment]
@tsujan To me, it looks like a LXQt issue.
Discord keeps the proper taskbar icon in Plasma and Cinnamon.
![screenplasma](https://user-images.githubusercontent.com/4103637/57184183-ceda6300-6eb7-11e9-8c3d-d4c3c947eed2.png)
![screencina](https://user-images.githubusercontent.com/4103637/57184184-d3068080-6eb7-11e9-89b2-f636e8d674dd.png)

**Comment by tsujan** [comment]
Then, please open another issue by filling in the issue template. The problem reported here is fixed.

**Comment by YamashitaRen** [comment]
Will do !
Sorry for the bother :/

**Comment by tsujan** [comment]
I installed discord, made an account, did the other things related to Discord and saw the icon changed.

Maybe that's related to the app, maybe not; I don't know but Discord's behavior is like that of the latest version of Skype.

**Comment by YamashitaRen** [comment]
This only happens when using StatusNotifier instead of System tray (libappindicator-gtk3 is installed).

**Comment by tsujan** [comment]
> This only happens when using StatusNotifier instead of System tray

System Tray may be used only by old codes.

Discord and Skype are both closed-source. So, the only thing we might be able to do in this case is trial and error.

**Comment by YamashitaRen** [comment]
Yeah, I know.
What I think it does is : 
- If libappindicator-gtk3 is installed, it uses StatusNotifier and bug happens.
- If libappindicator-gtk3 is not installed, it uses System Tray and bug doesn't happen.

Now, as you're saying, debugging this may be hard since Discord is closed source...

**Comment by tsujan** [comment]
Please open an issue at https://github.com/lxqt/lxqt-panel/issues for it and I'll confirm the problem. This page is really not related to it.

**Comment by tsujan** [comment]
@YamashitaRen Do not open an issue anymore; just follow https://github.com/lxqt/lxqt-panel/issues/1061
