### ISSUE TITLE
Audio Device Settings in Sound&Video instead of Preferences

### ISSUE THREAD

**Issue by Notsonoble** [lxqt/lxqt#1474]
##### Expected Behavior
The application that controls which audio device (Pulseaudio Mixer, Jack etc) the system is using should be in the preferences section of the menu and/or also populate the configuration center.

##### Current Behavior
Currently these only show in the sound and video section of the menu.
##### Possible Solution
The menu change is probably the simplest, I don't know enough about how the configuration center works to make a suggestion there. 
##### Steps to Reproduce (for bugs)
1. Start LXQt
2. Open Menu
3. Look expected sound setting application
4. 

##### Context

Mostly I find it a little confusing when moving back and forth between DEs, the choice of sound device (so speakers vs hdmi out) in other DEs is usually in what each DE labels as settings (gnome's settings application, kde's systemsettings application and menu). So its really a consistency thing. This could also be a distro thing, as I've only installed lubuntu next and debian to play with lxqt. 

##### System Information
* Distribution & Version: Lubuntu Next & LXQt 0.11

**Comment by tsujan** [comment]
> I don't know enough about how the configuration center works to make a suggestion there.

The app itself determines where its menu item should be and LXQt just accepts that. For example, `pavucontrol` says, in its desktop file:
```
Categories=AudioVideo;Audio;Mixer;GTK;
```
Those with `Categories=Settings;DesktopSettings;...` will appear in the Config Center.

So, the current behavior is correct.

**Comment by Notsonoble** [comment]
So report this behavior for discussion to the people responsible for the applications? Or is this a config choice that deb/ubuntu have made and I just need to adjust a config file or two?

**Comment by tsujan** [comment]
> So report this behavior for discussion to the people responsible for the applications?

Pulseaudio Mixer (Pavucontrol) definitely wants to be in the Audio/Multimedia category in Manjaro (my distro) but I think that's in its source. Other apps have their choices too but, very rarely, distros may add their own desktop files when packaging apps.

> So report this behavior for discussion to the people responsible for the applications?

Most probably but @tsimonq2 could give a better answer about how Ubuntu packages Pavucontrol or Jack.

**Comment by antis81** [comment]
LXQt packages `pavucontrol-qt` which is part of LXQt (think it is even default now). Setting the XDG category there would help quite a number of users. :slightly_smiling_face:

**Comment by tsujan** [comment]
This should have been closed. The categories are correct.

**Comment by antis81** [comment]
My "little dictatorious" friend (aka maintainer :slightly_smiling_face:):

From an LXQt user's perspective the menu still appears "unorganized" and having audio settings in the multimedia section instead of "audio settings" (or better "audio/video") logically makes no sense at all. The following issue (dating back to 2016) addresses that asking the right questions: https://github.com/lxqt/pavucontrol-qt/issues/3

Moving the discussion to the sub-project is a good idea though leaving this one closed here!
