### ISSUE TITLE
Environment variables vs. LXQt applications

### ISSUE THREAD

**Issue by aramazano** [lxqt/lxqt#1475]
Hello,

While I have installed and used my system (Debian Buster with LXQt) with Turkish as default language for a while, I had changed my user interface to English in order to precisely communicate about messages, menus, etc. on international platforms. For this change I did:

Preferences -> LXQt Settings -> Session Settings -> [Environment (Advanced)] ::
	Variable Name: LC_MESSAGES
	Value: C.UTF-8

So far so good, but when I try to launch an LXQt application with Turkish UI from within a terminal such as:

~$ LC_MESSAGES=tr_TR.UTF-8 pcmanfm-qt

user interface and messages are still presented in English. OTOH, non-LXQt applications (like claws-mail, xfce4-terminal, etc.) revert back to Turkish UI as expected.

This makes me think that LXQt applications are reading their environment variables not from the actual run-time environment, but from somewhere within LXQt.

Is there a way to specify UI language per application basis in LXQt? Or alternatively, is it possible to make LXQt applications get their environment variables upon launch from the actual environment, instead of getting it from LXQt?

Note: I need switching between English and Turkish UI *per application* basis for translation works. E.g. I plan to volunteer for translation of Featherpad, so I need to be able to run featherpad arbitrarily in either language. There may also be other use-cases for overriding environment variables per application basis.

Thanks and regards,

##### System Information

* Distribution & Version: Debian/Buster, amd64
* Kernel: Linux 4.9.0-4-amd64
* Qt Version: 5.9.2
* liblxqt Version: 0.12.0-5
* Package version: 25 (lxqt)

**Comment by Vladimir-csp** [comment]
Show the output of:
```
locale
LC_MESSAGES=tr_TR.UTF-8 locale
```

**Comment by tsujan** [comment]
Here, I use this command to change the language exactly for checking FeatherPad's translations (this is for french) under LXQt, KDE and Enlightenment:
```
LANGUAGE=fr fpad
```
And it works correctly. The same is true for other apps but I never install LXQt translations ;)

BTW, your Turkish FeatherPad translation will be very welcome as a PR at https://github.com/tsujan/FeatherPad

**Comment by tsujan** [comment]
> but LXQt applications run still in English UI.

They shouldn't be different. LXQt Turkish translations are missing?

**Comment by aramazano** [comment]
I remember running pcmanfm-qt in Turkish in the past, so at least for pcmanfm-qt there shouldn't be a translation problem. I am going to double check by deleting the forced setting of LC_MESSAGES in "LXQt Environment Settings (Advanced)" and re-login.

**Comment by aramazano** [comment]
After clearing LC_MESSAGES off LXQt session settings and re-logging in, now pcmanfm-qt, lximage, etc. (all the system with a few exceptional apps) has Turkish UI now.

**Comment by aramazano** [comment]
@agaida only tr localization is installed, and I am switching only between Turkish and English.

Now I have re-reverted back to my usual LC_MESSAGES=C.UTF-8 in lxqt session settings -> environment, and now both pcmanfm-qt and lximage-qt is launching in English by default. I just launch and then quit both applications, so I don't expect they would have residual processes running in background for a while. Nevertheless, I am going to check that with "ps".

Now by default upon logging in:
~$ locale
LC_MESSAGES=C.UTF-8
~$ lximage-qt --> English UI
~$ pcmanfm-qt --> English UI
~$ claws-mail --> English UI

~$ export LC_MESSAGES=tr_TR.UTF-8
~$ locale
LC_MESSAGES=tr_TR.UTF-8
~$ lximage-qt --> Turkish UI
~$ pcmanfm-qt --> English UI
~$ claws-mail --> Turkish UI

~$ ps ax | grep pcman
 1502 ?        Sl     0:01 pcmanfm-qt --desktop --profile=lxqt

OMG!

~$ killall pcmanfm-qt
~$ ps ax | grep pcman
<nothing>
~$ pcmanfm-qt --> Turkish UI! :)

So yes, agaida you are rigth. pcmanfm-qt lingers in the backgroung for some reason and thus doesn't get the new env variable. Thank you very much! You saved me a sleepless night. :)

I don't know whether the fact that pcmanfm-qt is lingering in the b.g. is a problem or not. It's up to your decision. :)

**Comment by agaida** [comment]
I wouldn't call painting the desktop a general problem :)

**Comment by aramazano** [comment]
Update: Now that I have killed pcmanfm-qt *for once*, it doesn't linger in the background any more. So that I can instanly switch between pcmanfm-qt languages depending on from where I launch it. (but can't run both English and Turkish versions in parallel, naturally)

**Comment by agaida** [comment]
but you have lost the Desktop functionality - backgrounds, placing files on the desktop and so on

**Comment by tsujan** [comment]
> so I don't expect they would have residual processes running in background for a while

As @agaida mentioned, it is. So, there was no problem in the first place.

**Comment by aramazano** [comment]
@agaida and @tsjuan you are both correct. By killing pcmanfm-qt once, I have lost the desktop features. And yes, there was no problem per-se. :)

**Comment by tsujan** [comment]
@aramazano You don't need to kill it manually. Use Session Settings and stop/start it from there.

**Comment by palinek** [comment]
> but can't run both English and Turkish versions in parallel, naturally

Right, because pcmanfm-qt is singleprocess app and ivoking its binary for next time just notifies the running instance to show you another window.
