### ISSUE TITLE
Main menu entry disappears after every app update

### ISSUE THREAD

**Issue by tsujan** [lxqt/lxqt#1477]
I'm sure bugs like this are reported here and there but I couldn't find them.

When I update an app, its main menu entry disappears until I log out and in again.

This annoying, hateful, goddamn bug happened a long time ago, then it was fixed automagically, and now it happens again!

The missing menu entries are shown correctly in `pcmanfm-qt` → `menu://applications/`.

**Comment by tsujan** [comment]
OK, this is caused by `menu-cache`; I'll never compile the panel with it again.

Please remove `menu-cache` because it's nothing but a hassle! The main menu code might need some modifications without it (I'll do them here).

**Comment by agaida** [comment]
@tsujan - what is the practical impact if we don't use menu-cache? Any numbers?

**Comment by tsujan** [comment]
@agaida On my computer(s), there's no impact, except for ugly menu items (GenericNames were added to item texts inside parentheses). However, I fixed that (for myself) with a simple change to `libqtxdg`, so that it's exactly like when menu-cache was used (GenericNames as tooltips):

![screengrab-20180417-193630](https://user-images.githubusercontent.com/981076/38878999-8b84b87a-4277-11e8-9f20-381109ff25c5.png)

**Comment by agaida** [comment]
erm - and btw - if the panel can work reasonable well without the menu-cache - whats about lxqt-runner

**Comment by tsujan** [comment]
>  if there is noticeable performance penalty

You meant, "if there is *no* noticeable performance penalty...". Here, there isn't any; @luis-pereira knows about such things though. IMHO, even if there *is* a "penalty" (which may be only theoretical) we should drop menu-cache for the reasons you mentioned. Of course, `libqtxdg` -- and the panel itself -- should be modified a little; Runner too (I never use it).

> whats about lxqt-runner

Other devs should look into it; I never use it.

Anyhow, I purge my system from menu-cache.

**Comment by tsujan** [comment]
Another thing:

If we don't drop it, distros (like Arch) might do so sooner or later -- I may make PRs out of my patches.

**Comment by agaida** [comment]
hmm - i should have somewhere in the basement an old laptop with an ancient 32 bit processor - the slowest machine i own. If there is no difference ... - really, if we need any kind of caching mechanism we should implement it ourself.

**Comment by tsujan** [comment]
> hmm - i should have somewhere in the basement an old laptop with an ancient 32 bit processor

That would be a very practical test but you'd be bothered by installing a lot of things -- a 32-bit Debian, LXQt, compiling panel without menu-cache.... If you do it and see ugly menu-items or no icon in the search view, don't worry! They can be cured easily.

**Comment by tsujan** [comment]
Dammit! `libfm-qt` calls menu-cache in `AppMenuView` and `AppChooserDialog`. I should rewrite them.

**Comment by agaida** [comment]
right

and regarding a 32 bit debian - not exactly an problem, just pushing the "Build the i386 lxqt iso with latest git packages" in jenkins and wait for approx. 5 mins :P - ok, the installation will also take some minutes.

**Comment by tsujan** [comment]
Cool. With it you'll surely see a difference if any -- although I don't know how many minutes you should wait for each compilation ;) -- the question is "is the difference tangible to the user on such a computer?" IMO, a practical answer would be valuable.

**Comment by agaida** [comment]
tools like pbuilder and sbuild was invented long before ...

**Comment by agaida** [comment]
with the ancient single core the is also no penalty - at least i noticed none. and the very best is - panel and runner are optional, in pcmanfm-qt menu-cached is only used in the application menu. In more clear words - menu-cached jumps in, when the application menu is clicked. So if panel and runer are compiled without menu-cached there is no process for menu-cached running. And thats a good thing, because sudo reboot works right now without any magic. So my suggestion is to default to menu-cached off in both panel and runner. Will prepare the needed PRs.

**Comment by agaida** [comment]
IMHO we should just ignore the usage of menu-cached in pcmanfm-qt for now, no clue if there is any other component in LXQt using it - maybe lximage-qt. Will have a look.

**Comment by tsujan** [comment]
Glad to know you reached the same conclusion so quickly! It may show that the benefits of such a caching have been a myth, at least, for a decade. If there's no penalty with a single-core computer, there's none at all and the rest is just theory. Now:

(1) Removing menu-cache needs a small change in Panel's code and another in libqtxdg's (otherwise, menu-items would be ugly and there would be no icon in the search view). I'll make PRs as soon as I find some time.

(2) With pcmanfm-qt, it isn't easy. One or 2 classes should be rewritten totally and that needs more time.

(3) I haven't looked into Runner's code yet (as said above, I don't use it).

**Comment by agaida** [comment]
as far as i can see it is a two liner for the panel and maybe an two liner for the runner - to make both changes obvious. And as i said i would suggest to ignore pcmanfm-qt right now. The usage of menu-cached is not permanent and the process will not respawn permanently - long term we should ofcurse get rid of it in pcmanfm-qt too.

**Comment by tsujan** [comment]
> as far as i can see it is a two liner for the panel

Do that as a PR but, for the reasons mentioned above, a little more is needed -- I'll do them as 2 other PRs.

> And as i said i would suggest to ignore pcmanfm-qt right now

As a lazy dev, happy to hear that :P

**Comment by agaida** [comment]
^^ should be sufficient for now - and those who don't want to follow are free to set it to ON

**Comment by tsujan** [comment]
> should be sufficient for now

Yes. Tomorrow, or the day after it, I'll may those PRs

**Comment by tsujan** [comment]
@yan12125 Did it [here](https://github.com/lxqt/libqtxdg/pull/153) and [here](https://github.com/lxqt/lxqt-panel/pull/464).

**Comment by tsujan** [comment]
The last step (not so important) is getting rid of menu-cache in `libfm-qt`. It's possible, of course, but (1) takes time and  (2) may need changes in other places (I'm not sure yet).

**Comment by agaida** [comment]
IMHO the biggest blocker was the damn permanent respawning of the cache - beside of the usual bugs. As long as a user don't touch pcmanfm-qt application menu menu-cached will not even start. In my tests the cache stopped gracefully every time. So i tend to ignore the remaining bits right now.

**Comment by tsujan** [comment]
@agaida I know it isn't a blocker but, at some point, that job should be done too.

**Comment by tsujan** [comment]
This isn't closed yet?! It's fixed.

**Comment by tsujan** [comment]
To be thorough: Fixed in https://github.com/lxqt/lxqt-runner/pull/72, https://github.com/lxqt/lxqt-panel/pull/464 and https://github.com/lxqt/libqtxdg/pull/153

**Comment by agaida** [comment]
nice

**Comment by tsujan** [comment]
Oh, I meant this: https://github.com/lxqt/lxqt-panel/commit/d7a441cc7150b73adae1cf69114f5d8e3ac87a15

The number of weblate commits is so big that it isn't easy to find a commit without using github's search ;)

**Comment by agaida** [comment]
nah - it dramatically decreased in the last days - so i guess it will not disturb us much in the future - far more as we are don't forced to merge these things as far as possible - the pull requests can grow some days before getting merged.  That doesn't mean that we are done with the translations, but ...

**Comment by tsujan** [comment]
There was no disturbance at all. The hard job was and is yours; I meant it was enormous and I don't know how you did it. It's good that translation is organized now.

**Comment by agaida** [comment]
it wasn't that hard - ok, boring some times :P

**Comment by tsujan** [comment]
LOL... I knew you'd say that if I said anything about the diffculty :D

**Comment by PCMan** [comment]
Menu cache was born in 2008. At that time, adding the cache significantly improved the startup speed of LXDE (my experiments at that time showed improvement more than 70%, which is a lot).
The xdg menu is not well designed. Each time you need a menu, you have to traverse the many dirs and parse every file. Finally, merge them by some xml rules.
This can be painfully slow if you have a non-ssd slow hard disk and single core CPU.
Nowadays it might not help that much so I'm +1 on removal if benchmarks show it useless.
Please remember, to simulate colds boot, you need to drop filesystem cache so your test can be accurate. With filesystem cache, parsing the whole dir looks fast since it's in memory string parsing instead of frequent I/O.

**Comment by tsujan** [comment]
> This can be painfully slow if you have a non-ssd slow hard disk and single core CPU.

I don't know about single core CPUs but with the non-ssd hard and the duo core of a 10-11-year-old computer and after a cold boot, it made no practical difference. @agaida had tested it too.

menu-cache is there and people could compile the panel against it if they want it. But the cost (annoying bug) isn't acceptable.

**Comment by agaida** [comment]
Right - and i tested it with single core i386 - LXQt was fine and usable. And to my very surprise i found LXQt a bit faster without menu-cached. Might be bias or somewhat else. But the panel was fast without menu-cache. Given that menu-cached is used only in the application menu of pcmanfm-qt i would suggest to make it optional or drop it completely as fast as possible.

if there are doubts and menu-cached can be replaced by a new native and maybe a bit simpler solution - nothing speak against. There is only one big BUT: The old and f§$%ing slow single core machines are more or less dead so i wouldn't care about. Rationale - i386 is about to die soon, Arch dropped it already, Ubuntu dropped it, Lubuntu resist to drop it right now, nobody knows how long. We (siduction) dropped i386 with 2017-1 as official release architecture (with the option for our users to ask for a fresh build, if they really need a i386 image) - there was exactly 5 requests in nearly two years.

And thats exactly the point: Only the entry level lowest budged Notebooks ten years ago have 32 bit single core processors - desktops and normal laptops was at least Athlon X2 or Duo core, if not core2duo. In other words - the "market share" of slow mobile single core i386 is not really relevant any more. ymmv.

**Comment by tsimonq2** [comment]
> Lubuntu resist to drop it right now, nobody knows how long

https://lubuntu.me/this-week-in-lubuntu-development-7/

The short of it is, as soon as there's no more testing and people don't want to fix the bugs with the platform, it's gone.
