### ISSUE TITLE
LXQt Settings "lazy" menu items

### ISSUE THREAD

**Issue by aramazano** [lxqt/lxqt#1484]
I think this has started with the last upgrade or the one before.

Both LXQt Settings submenu items and LXQt Control Center icons are intermittently not responding to mouse click. Sometimes they work as expected, sometimes I need to click (doubleclick in control center) several times to activate them, sometimes they won't activate at all.

##### System Information
* Distribution & Version: LXQt [experimental-snapshots](https://lxqt.debian.net/) on top of Debian Testing (Buster)
* Kernel: 4.9.0-4-amd64
* Qt Version: 5.10.1
* liblxqt Version: liblxqt0 / 0.12.1~8-g80f9324-1
* lxqt-admin Version: 0.12.1~10-ga9b0ffc-1

**Comment by tsujan** [comment]
Can't confirm this at all.

**Comment by aramazano** [comment]
E.g. "keyboard and mouse" setting is particularly stubborn. Never been able to activate it.
"Brightness" never activates but I'm on desktop PC. That maybe a reason.
"Appearance" *usually* runs at the second attempt. (Sometimes at first, sometimes never)
"Power Management" , "Desktop Notifications" , "File Associations" and "Shortcut Keys" are usually OK.

On System Settings section, "Date and Time" and "Print Settings" are stubborn also.

I am going to run them from command line and see the console messages.

This never runs:
```
aramazan@torik:~$ system-config-printer
Traceback (most recent call last):
  File "/usr/share/system-config-printer/system-config-printer.py", line 84, in <module>
    import jobviewer
  File "/usr/share/system-config-printer/jobviewer.py", line 76, in <module>
    NETWORK_PASSWORD = Secret.Schema.new("org.system.config.printer.store", Secret.SchemaFlags.NONE,
NameError: name 'Secret' is not defined
```

This one too:
```
aramazan@torik:~$ LANG=C lxqt-admin-time 
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
İptal edildi		---> translation: cancelled
```
(LANG=C had no effect, no idea why.)

This one when it runs (message issued after closing the app):
```
aramazan@torik:~$ LANG=C lxqt-config-locale 
free(): invalid next size (fast)
İptal edildi		---> translation: Cancelled
```

This one when it won't run:
```
aramazan@torik:~$ LANG=C lxqt-config-locale 
corrupted size vs. prev_size
İptal edildi		---> translation: Cancelled
aramazan@torik:~$ LANG=C lxqt-config-locale
Parçalama arızası	---> translation: Segfault
```

This never runs:
```
aramazan@torik:~$ LANG=C lxqt-config-input 
lxqt-config-input: symbol lookup error: lxqt-config-input: undefined symbol: _ZN4LXQt26ConfigDialogCmdLineOptionsD1Ev
```

This is when it runs (message issued after closeing app):
```
aramazan@torik:~$ LANG=C lxqt-config-appearance 
free(): invalid next size (fast)
İptal edildi		---> tr: Cancelled
```

This is when it won't:
```
aramazan@torik:~$ LANG=C lxqt-config-appearance 
Parçalama arızası (segfault)
```

etc.

**Comment by aramazano** [comment]
```
aramazan@torik:~$ LC_MESSAGES=C lxqt-config-appearance
 (0x7ffc71f588f0) Warning: QSocketNotifier: Invalid socket 1215602560 and type 'Read', disabling...
munmap_chunk(): invalid pointer
İptal edildi		---> alternative translation: Aborted
```

Let me know if you want me do a particular test.

**Comment by tsujan** [comment]
Something has gone wrong with the upgrade. I don't think these are LXQt issues. I guess you might even not be able to log into LXQt after a log-out. Wait for another upgrade!

**Comment by aramazano** [comment]
I always do `echo $?` at each intrusive apt command. They were all 0. No apt errors at all. Now I'ö going to logout and in. No messages in 5 mins means I was unable to log back in. :)

**Comment by aramazano** [comment]
I logged out and back in. Then logged out again, rebooted and logged in again. So LXQt runs OK.

**Comment by tsujan** [comment]
If I were you, I'd also check whether `~/.config/lxqt` belongs to root. If not, perhaps, not all LXQt components were upgraded (correctly) or, maybe, the new packages have some problem or...

I'd recommend you install an elementary DE beside your main DE (== LXQt or any other one) to be able to do repairs/upgrades more easily.

**Comment by aramazano** [comment]
```
aramazan@torik:~$ ll -d .config/lxqt/
drwxr-xr-x 2 aramazan aramazan 4096 May  2 05:07 .config/lxqt/
aramazan@torik:~$ ll .config/lxqt/
toplam 4408
-rw-r--r-- 1 aramazan aramazan 4437410 May  2 05:08 debug.log
-rw-r--r-- 1 aramazan aramazan      73 Nis 25 06:03 filedialog.conf
-rw-r--r-- 1 aramazan aramazan    5833 May  2 05:07 globalkeyshortcuts.conf
-rw-r--r-- 1 aramazan aramazan     286 May  2 02:14 lxqt.conf
-rw-r--r-- 1 aramazan aramazan      31 May  2 04:54 lxqt-config.conf
-rw-r--r-- 1 aramazan aramazan      28 Ara 14 12:12 lxqt-config-locale.conf
-rw-r--r-- 1 aramazan aramazan    1932 Ara 17 09:58 lxqt-config-monitor.conf
-rw-r--r-- 1 aramazan aramazan     375 Oca 31 16:19 lxqt-powermanagement.conf
-rw-r--r-- 1 aramazan aramazan     100 Nis 30 01:21 lxqt-runner.conf
-rw-r--r-- 1 aramazan aramazan      28 Ara 11 02:18 notifications.conf
-rw-r--r-- 1 aramazan aramazan    8377 May  2 05:07 panel.conf
-rw-r--r-- 1 aramazan aramazan      28 Ara 11 02:18 power.conf
-rw-r--r-- 1 aramazan aramazan     365 May  2 04:30 session.conf
-rw-r--r-- 1 aramazan aramazan      28 Ara 14 12:18 TimeDate.conf
-rw-r--r-- 1 aramazan aramazan     700 Ara 11 02:18 windowmanagers.conf
```

I have both Xfce4 and LXQt (but only use LXQt). So I have the fallback as you suggested. :)

**Comment by aramazano** [comment]
Update: Downgraded lxqt-admin (from /var/cache/apt/archives) to 0.12.0-4 in two stages and the behavior is -almost- same. I say "almost" because it can be subjective. Lower versions seems to be just a bit better than the latest one, but they retain the same behavior. This is not that old a bug, so I think this is not (just) related to lxqt-admin. Had it been so, then downgrading should have the problem, I think.

Apt archives also tell about my version upgrade history.

```
aramazan@torik:/var/cache/apt/archives$ LANG=C ll lxqt-admin*
-rw-r--r-- 1 root root 33794 Jan  2  2017 lxqt-admin-l10n_0.11.2-1_all.deb
-rw-r--r-- 1 root root 33604 Dec  6 22:10 lxqt-admin-l10n_0.12.0-3_all.deb
-rw-r--r-- 1 root root 33656 Feb 10 07:57 lxqt-admin-l10n_0.12.0-4_all.deb
-rw-r--r-- 1 root root 36800 Apr  1 16:05 lxqt-admin-l10n_0.12.1~51-g32b5fff7-1_all.deb
-rw-r--r-- 1 root root 48188 Jan  2  2017 lxqt-admin_0.11.1-1_amd64.deb
-rw-r--r-- 1 root root 51272 Dec 14 20:45 lxqt-admin_0.12.0-4_amd64.deb
-rw-r--r-- 1 root root 54284 Apr 30 23:24 lxqt-admin_0.12.1~10-ga9b0ffc-1_amd64.deb
-rw-r--r-- 1 root root 54336 Apr  1 20:29 lxqt-admin_0.12.1~9-gdf1f85d-1_amd64.deb
```

Stage-1:
`~# dpkg -i lxqt-admin_0.12.1~9-gdf1f85d-1_amd64.deb lxqt-admin_0.12.1~9-gdf1f85d-1_amd64.deb`
Effect: Subtly (possibly psychological) better response, but mainly the same.

Stage-2:
`~# dpkg -i lxqt-admin_0.12.0-4_amd64.deb`
Effect: None.

**Comment by agaida** [comment]
@tsujan - for current things i would suggest a insane siduction paintitblack with the newest things integrated - not a testing based thing. i can't reproduce this - not in kvm, not in vbox, not any of my machines

**Comment by tsujan** [comment]
@agaida You're completely right.

@aramazano As @agaida implied, when you use Testing and install experimental packages, such things could happen because LXQt uses private Qt headers. There are 2 ways out of this: (1) upgrade to sid; or, (2) make you own deb packages from the latest git LXQt based on Testing. I did (2) when I was a Debian user. Making deb packages will be fun once you find your way in that territory.

**Comment by aramazano** [comment]
It was my vague guess, now you confirmed it. I will wait for a couple of weeks to allow any package pending Sid -> Testing migration. It ought to solve itself in short time, I expect.

As for building my own packages, I will start doing it when I have some free time.

**Comment by tsujan** [comment]
> As for building my own packages, I will start doing it when I have some free time.

I highly recommend that. When you master it, it'll become a piece of cake in most cases and you'll be the master of your Debian system.

**Comment by agaida** [comment]
erm - that has nothing to do woth Qt private symbols - thats why we have pure virtual dependencies in exactly four packages - qtbase-abi-5-10 or similar - to lazy to look right now. That make sure that the needed packages are installed. Really - i tested it :P 
But there can be some other glitches with the installation - so it is really better to use a dev system to do dev-work or run bleeding edge - if any thing hurt you - ok, it's really bleeding edge...

**Comment by agaida** [comment]
> 2018-05-02  17:23:46 <siduction-ci> Project Build Next LXQT amd64 build #274: SUCCESS in 7 Minuten 42 Sekunden: http://ci.siduction.org/job/Build%20Next%20LXQT%20amd64/274/

user: logview pass: logview

>2018-05-02 17:23:46,272 INFO  - Links to current build:
2018-05-02 17:23:46,272 INFO  -  * https://isobuilds.siduction.org/lxqt/amd64/siduction-18.3.0-paintitblack-lxqt-amd64-201805021516.iso
2018-05-02 17:23:46,272 INFO  -  * https://isobuilds.siduction.org/lxqt/amd64/siduction-18.3.0-paintitblack-lxqt-amd64-201805021516.sources
2018-05-02 17:23:46,272 INFO  -  * https://isobuilds.siduction.org/lxqt/amd64/siduction-18.3.0-paintitblack-lxqt-amd64-201805021516.iso.sha256
2018-05-02 17:23:46,273 INFO  -  * https://isobuilds.siduction.org/lxqt/amd64/siduction-18.3.0-paintitblack-lxqt-amd64-201805021516.amd64.manifest
2018-05-02 17:23:46,273 INFO  -  * https://isobuilds.siduction.org/lxqt/amd64/siduction-18.3.0-paintitblack-lxqt-amd64-201805021516.iso.md5

**Comment by aramazano** [comment]
FWIW, just restored lxqt-admin to its original version (0.12.1~10-ga9b0ffc-1) and did an upgrade from experimental-snapshots only (no upgrade from other repositories).
```
root@torik:~# apt-get install featherpad liblxqt0 libqt5xdg3 libqt5xdgiconloader3 lxqt-admin qps
...
Paket açılıyor: featherpad (0.9~45-g82fafe6-1) üzerine (0.9~46-gaa6e535-1) ...
Paket açılıyor: libqt5xdgiconloader3:amd64 (3.1.1~13-gb5ddbd4-1) üzerine (3.1.1~14-g01f283b-1) ...
Paket açılıyor: libqt5xdg3:amd64 (3.1.1~13-gb5ddbd4-1) üzerine (3.1.1~14-g01f283b-1) ...
Paket açılıyor: liblxqt0 (0.12.1~8-g80f9324-1) üzerine (0.12.1~15-g11ce2c6-1) ...
Paket açılıyor: lxqt-admin (0.12.0-4) üzerine (0.12.1~10-ga9b0ffc-1) ...
Paket açılıyor: qps (1.10.18~2-g0ddce0e-1) üzerine (1.10.18~5-g4a97e61-1) ...
...
```
And the problem disappeared! :)

(Except system-config-printer, which is not related to LXQt.)

**Comment by tsujan** [comment]
@agaida Some facts about private headers:

Neither in FeatherPad nor in Kvantum, I use private headers (in some places, I had to do some hard work to avoid them) and so, they've never needed a recompilation when, for example, Qt was upgraded from 5.9 to 5.10 -- whether under Debian or under Manjaro.

However, each time Qt's second version number changed, I had to recompile (and repackage) almost the whole LXQt because almost everything stopped working. That's normal because we use private headers -- no other cause comes to my mind.

@aramazano As for deb packages, @agaida is much more knowledgeable than I was. So, if our words are different, his words are the correct ones.

**Comment by agaida** [comment]
in Debian it is easy - having a look at the dependencies (and not fair, but also convenient, let the KDE-Qt-Team do the work :P ) - they take care about the needed rebuilds within transitions. Ok, i test it mostly before with experimental Qt.
``` % aptitude search '~i~Dqtbase-abi-5-10' | egrep 'xdg|fm|plugin|theme' 
i  libfm-qt5 - file management support for pcmanfm-qt
i  libqt5xdgiconloader3 - Implementierung des »XDG Iconloader« für Qt (Laufzeitbibliothek)
i  lxqt-qtplugin - LXQt system integration plugin for Qt
i  qt5-gtk-platformtheme - Qt 5 GTK+ 3 platform theme
i A qt5-qmltooling-plugins - Qt 5 qmltooling plugins
i  qt5-style-plugins - Qt 5 extra widget styles
i A qtwayland5 - QtWayland platform plugin
```

**Comment by tsujan** [comment]
Related to all this:

If just `lxqt-admin` could cause such a big problem, we should be alarmed. I've never installed it -- not because I have any problem with it but only because I've had no use for it.

**Comment by agaida** [comment]
no - we should not be alarmed - we should be alarmed if something segfaults - may the lxqt-admin thing related to systemd, polkit, dbus - we will never know it until we can debug it ourself.

**Comment by aramazano** [comment]
But the damage was strictly confined to the package itself. Other parts of LXQt was working excellent. Just lxqt-admin faltered.

**Comment by agaida** [comment]
and lxqt-admin is the part of LXQt that highly depends on polkit and other obscure things

**Comment by tsujan** [comment]
@aramazano `lxqt-config-locale` and `lxqt-config-appearance` don't belong to `lxqt-admin`.

> and lxqt-admin is the part of LXQt that highly depends on polkit and other obscure things

A bad sign to me.

**Comment by agaida** [comment]
even on my brand new Pentium M single core it runs fast enough - so i really see no problem. Hmm - changing the appearance of a running LXQt with some windows take a while (approx 0,2-0,5 s) until propagated to the last window/application - but thats fine for a single core.

**Comment by tsujan** [comment]
I try to use `QSharedMemory` or `QDBus` only when inevitable, while others take them for granted; hence my attitude.

**Comment by aramazano** [comment]
Hmmm perhaps I need to admit a possible fault of mine. In order to do selective upgrades (i.e. just upgrade experimental-snapshots, leaving other repositories alone) I do a dirty hack:

* First do a `apt-get update`
* Then from user session `~$ apt-get -s dist-upgrade`
* Note the `experimental-snapshots` packages in the provided list of "to be installed" packages,
* Install them explicitly by an `apt-get install`

Just a possibility: I may have omitted some experimental-snapshots packages from my explicit package install list in my previous upgrade (prior to this problem surfaced) leading to uneven/mismatching upgrade of experimental repository.

You can see if this is the case from my last upgrade list: https://github.com/lxqt/lxqt/issues/1484#issuecomment-386065459

It lists both previous and latest versions of the packages. If the previous versions of the packages don't match lxqt-admin 0.12.1~10-ga9b0ffc-1 (except lqqt-admin itself, which I had deliberately downgraded) then this may be the case. I honestly apologize for the distress I've caused in this case.

Next time I will selectively upgrade by explicitly givin distribution (experimental-snapshots) name to prevent such a risk.

**Comment by tsujan** [comment]
@aramazano Experimental is experimental, after all -- you could expect problems with it. However, if A and B are needed for C to work OK, C should depend on both. That shouldn't happen outside experimental but I clearly remember that it happened once in a while. And it happens in all distros here and then.

**Comment by agaida** [comment]
and also again - experimental-snapshots have nothing to do with debian/experimental - the name is just to scare beginners away - and also because it is the latest git stuff. So a simple apt dist-upgrade should be sufficient.

**Comment by agaida** [comment]
erm - ok - dead serious - you want dist-upgrades. Everytime. And in case that some things are not installable you want apt upgrade (or apt-get upgrade --with-new-pkgs). And you don't want synaptic. Maybe you want synaptic - to have a reason to re-install the systems after some cool synaptic actions.

**Comment by aramazano** [comment]
> Maybe you want synaptic - to have a reason to re-install the systems after some cool synaptic actions.

:)) Yes you may have point there. :)

**Comment by agaida** [comment]
and also again - it is much easier to run sid than a mixed testing/sid environment.

**Comment by aramazano** [comment]
There's no going back from Testing to Stable, but as Testing is following Sid with a small lag, the return path is always open from Sid back to Testing. It should take a month or so at most. I will seriously think about upgrading to Sid.

Though I wouldn't be the happiest man on the earth if all my data has gone with the wind, or if I can no longer connect to Internet. These kind of risks are what essentially holds me back from Sid. But I will think about it.

I wish apt did transaction based package management with roll-back function. GNU (Guix?) is working on such a pkg manager AFAIK.

**Comment by agaida** [comment]
Even if a system crashes - in most cases™ no datas are lost. For me it was easy, i started with nearly zero Debian knowledge and Sid. But the difference between sid and testing is that testing tend to be longer broken and need to be repaired with sid packages in certain cases. Thats all - and on should learn to read apt output before hitting \<y>
