### ISSUE TITLE
Desktop shortcut open a menu for open/execute/execute in terminal

### ISSUE THREAD

**Issue by hifi25nl** [lxqt/lxqt#1486]
I have switched from xfce4 to lxqt, but I have now this big problem:
Clicking on all .desktop shortcuts will open a menu for open/execute/execute in terminal

How to fix this?

I have the very last version of all applications (updated today) in archlinux.

**Comment by tsujan** [comment]
> I have now this big problem

... whose opposite was called a big problem 2 years ago. Anyhow, it's configurable in pcmanfm-qt's Preferences.
