### ISSUE TITLE
Qt 5.11 beta bugs and PRs

### ISSUE THREAD

**Issue by agaida** [lxqt/lxqt#1487]
Only a place for maybe needed changes and pull requests in LXQt until Qt 5.11 is finally released.
To be true - i don't want to merge any fixes for Qt 5.11 until it is released.

**Comment by tsujan** [comment]
@agaida I never use beta and don't know about changes yet. However, if Qt has become so backward incompatible when its second version changes, we should start to worry ;) Personally, I won't be surprised if that's the case, having seen irresponsible behavior from Qt devs many times in recent years.

IMO, this situation means that we should wait until a stable Qt 5.11 comes out and only then release the next LXQt.

**Comment by tsujan** [comment]
We still don't know what will happen with a stable Qt. If something bad happens, we won't be alone -- although that might not affect this new generation of devs.

**Comment by agaida** [comment]
right

**Comment by Chiitoo** [comment]
5.11.0 beta is already old news, as the release candidate is out since Tuesday, and if all goes as expected, 5.11.0 should be out on the 22nd.  I do believe they are quite serious about these changes.

Aside from the few things I've reported or otherwise mentioned, things build and run well with regards to LXQt (I don't use the about, admin, l10n, openssh-askpass, policykit, powermanagement, or sudo packages though, so I can't talk about those).

One additional weird thing that I noticed a while ago, is that the application order in my application menu changed at some point.  Not sure that's about Qt though.

I only needed to add the missing headers.

**Comment by tsujan** [comment]
> I do believe they are quite serious about these changes.

While they aren't serious at all when it comes to fixing critical bugs that have persisted for a long time...

GTK+ is crap, Qt is suspicious, EFL is good only under E,... I guess I should forget about GUI programming at some point ;)

**Comment by palinek** [comment]
>  if Qt has become so backward incompatible when its second version changes, we should start to worry ;) 

Those missing includes have nothing to do with compatibility. It's about the cleanup in Qt and speeding up the compile time. There is no harm to include needed headers even with current/older Qt versions.

**Comment by agaida** [comment]
@palinek - those missing includes break compatibility :P - my definition of compat. is slightly different :P - anyways, thats a simple question of definitions - so: without the compat. patches our current code in distributions FTBFS and shit hit the fan (if i understand it right)

In other words: We can and must apply the compat pull requests and hope that we fix every place where changes are needed - and release before Qt 5.11 hit distributions. And if i understand you right the needed includes, code changes etc will not break older Qt versions, so we don't have to care.

Is that summary correct?

**Comment by tsujan** [comment]
I know nothing about the status of `lxqt-connman-applet` -- have never used it -- but it hasn't had a single commit for several months. Although CMST exists (and I use it), if `lxqt-connman-applet` is a good program, it might deserve more attention. IMHO, connman is a very good choice with LXQt (actually, I use it everywhere).

Sorry if `lxqt-connman-applet` isn't related to CMST -- it had no README and I didn't install it.

**Comment by agaida** [comment]
it isn't related - its a independent implementation

**Comment by tsujan** [comment]
By "related" I meant "doing the same job", in the sense that pcmanfm-qt and dolphin are related.

**Comment by agaida** [comment]
don't know the current state - never used it

**Comment by agaida** [comment]
Time for a good joke: https://blog.qt.io/blog/2018/05/24/porting-from-qt-1-0/

> Qt guarantees source and binary compatibility between minor releases, and we take that seriously. Making sure that you don’t have to rewrite (or even recompile) your application when you upgrade to a newer version of Qt is important to us.

**Comment by agaida** [comment]
The best marketing is if the marketing guys don't know the own product - so they can't tell no lies (or better: not the full truth)

**Comment by palinek** [comment]
> or some includes don't really count as code

As I've said previously... those missing includes were our faults, not Qt's. We use some types, that we didn't explicitly include headers for (the headers were previously (by luck) included via other includes). It's not a Qt bug/fault if they did a cleanup (compile speedup optimization) and that did broke our "fragile" code.

**Comment by agaida** [comment]
still not yet convined, but ok - in that case they are right and we was to lazy - so it will not break again wirh future releases of Qt hopefully

**Comment by tsujan** [comment]
At last, I got Qt 5.11 and recompiled the whole LXQt against it from inside KDE. Everything works fine. And KDE feels so heavy compared to LXQt ;)
