### ISSUE TITLE
New package icons don't load after install, only after log out / restart

### ISSUE THREAD

**Issue by jollyjester** [lxqt/lxqt#1489]
##### Expected Behavior

After installing the package, the icon of the said package would appear on the "application menu"

##### Current Behavior

There's a gear icon and the package icon only appears after log out / restart

##### Steps to Reproduce (for bugs)

1. Install a GUI package
2. Open up the "application menu"

##### Context

I want the package's icon to appear without log out / restart

##### System Information

* Distribution & Version: Debian GNU/Linux unstable (sid) x86_64
* Kernel: 4.16.0-1-amd64
* Qt Version: I can't find how to get this information, but my lxqt version is 0.12.0
* liblxqt Version: 0.12.0-7 * Package version: 0.12.0-7

**Comment by tsujan** [comment]
Thanks for reporting but this issue is already fixed in git LXQt.

**Comment by jollyjester** [comment]
How can I installed the git LXQt on Debian Sid? @tsujan

**Comment by agaida** [comment]
if you are really brave you could install the experimental-snapshots from lxqt.debian.net - The packages are build against sid and should work most of the time.
