### ISSUE TITLE
Optional unread notification systray widget

### ISSUE THREAD

**Issue by jleclanche** [lxqt/lxqt#149]
Something that came up as a feature request today: An "unread notifications" widget, think in a similar style as the G+ notifications widget. We may want to tune what kind of notification priorities go in there.
A notification would go in there when it automatically fades out iff it hasn't been manually dismissed or the user didn't interact with it in some way.

**Comment by tsujan** [comment]
Superseded by https://github.com/lxqt/lxqt/issues/1573
