### ISSUE TITLE
Unable to get the lxqt-panel after logging in

### ISSUE THREAD

**Issue by pourpier** [lxqt/lxqt#1491]
##### Steps to Reproduce (for bugs)

1. 
2. 
3. 
4. 

##### System Information

* Distribution & Version: 
* Kernel: 
* Qt Version: 
* liblxqt Version: 
* Package version:

**Comment by tsujan** [comment]
Is this report a joke?

**Comment by pourpier** [comment]
When I log in I get the message you'll see in the picture.
When I launch it from the terminal I get the following error message:
QPaintDevice : Cannot destroy paint device that is being painted.
If I type sudo lxqt-panel the panel does appear but I get the following messages:
QStandardPaths: XDG_RUNTIME_DIR not set defaulting to /tmp/runtime-root
Plugin statusnotifier not found
![lxqt_panel](https://user-images.githubusercontent.com/33185945/40272034-e473c60e-5ba6-11e8-9b3b-f3927e54d865.PNG)

**Comment by tsujan** [comment]
Your problem may have 1000 causes and no one is telepathic here; instead, there's a template you didn't touch.

**Comment by pourpier** [comment]
I edited the template. I was looking after the directory where I had put the image of the panel crash which happens each time after I log in. And it took me a while

**Comment by jubalh** [comment]
Chances are high, that this is not a problem of lxqt-panel but of your Gentoo configuration.
It will be hard to diagnose this for us. Please check all the useflags you set, and their effects. Maybe you missed something important.

**Comment by pourpier** [comment]
I was told on an iec channel that I had to go to the issue tracker of LXQt if it was related to an LXQt issue which is the case as I can't have the lxqt-panel as a standard user while if I launch sudo lxqt-panel I get the panel back.

**Comment by tsujan** [comment]
> I edited the template

Good. The version of lxqt-panel you have is too old. Please update your LXQt installation to the latest git and report back if there's any problem. A backtrace will be needed if you encounter a crash (with the latest git).

**Comment by agaida** [comment]
there are ebuilds numbered with 999 iirc - and one should wake up the maintainer(s) of the LXQt port(s) - the winter is over and we have 0.12.0 since more than 6 month

**Comment by tsujan** [comment]
The minimum required info  would be a backtrace but that wouldn't be helpful either because of the old version.

**Comment by tsujan** [comment]
> I don't have enough experience to create an ebuild from a git package.

You could acquire that experience little by little if you listen to the motto on your desktop: "If it moves, compile it!"

**Comment by agaida** [comment]
https://github.com/gentoo/qt/tree/master/lxqt-base

**Comment by jubalh** [comment]
@pourpier please keep in mind that the ebuilds @agaida points you to are from the Qt overlay. You will first have to add this overlay to portage and configure its priority higher than the standard so that you install the ebuilds from there.

See [wiki](https://wiki.gentoo.org/wiki/Ebuild_repository#Repositories)

Since regular ebuilds are not updated to latest version of LXQt it is possible that also the git ebuilds are not updated (dependencies, use flags..). So it might be that even after installing them you will have issues.

**Comment by tsujan** [comment]
@jubalh The problem of this report is the lack of info; otherwise, even older versions of lxqt-panel shouldn't crash. If a backtrace was provided, we could read it and say, for example, "Oh, this is related to X, which is fixed in Y," or, perhaps, we could find an overlooked bug, etc.

**Comment by jubalh** [comment]
@tsujan Agreed.
In above statement I was not really talking about this bug report. But about the ebuilds he can choose from and what effect it might have, since ebuilds in official tree are not up to date.

**Comment by pourpier** [comment]
@agaida
 You didn't help me in reality. I know what an overlay is and how to add one. I just don't want to add overlays. The main dev of Redcore has a solution for this issue he found himself. He told me which packages I had to install but there are a lot of dependencies which I don't want.
@tsujan 
If you could tell me exactly what file(s) you'd like to have the output of, that would be more helpful. 
What can you infer from the fact that I can get the lxqt-panel as root and not as a standard user? What kind of warnings/messages would give you more clues? Which files related to LXQt contain these warnings/errors?
@jubalh 
Someone told me to try Alt + F2 but when I start typing lxqt-panel in it, it crashes. Does it give you a clue? Do you think that deleting some files under ~/.config/lxqt/ would help?

**Comment by tsujan** [comment]
@pourpier It's too late. lxqt-panel 0.13.0 is released.

You should consult the doc of your distro to know how you could add a meaningful backtrace. Crash reports without backtrace aren't helpful and will be closed unless there is a step-by-step way to reproduce the crash in question.

**Comment by tsujan** [comment]
BTW, in case we didn't make it clear before: Old versions of LXQt aren't supported.

**Comment by jubalh** [comment]
> It's too late. lxqt-panel 0.13.0 is released.

That's why we told him about the overlays.
Because right from the start this bugreport was about an older version of lxqt-panel :-)
Gentoo only has 0.11.0 in tree.

**Comment by tsujan** [comment]
I know. He received a few advises, none of which he wants to follow. Hence, "wont-process-this".
