### ISSUE TITLE
lxqt-panel mainmenu search: clear filter

### ISSUE THREAD

**Issue by jubalh** [lxqt/lxqt#1492]
Refresh the mainmenu search in lxqt-panel.

##### Expected Behavior
When using the search in mainmenu in lxqt-panel, after executing (search for qterminal, press enter/left click on entry) the filter should be cleared, so that after opening the mainmenu the next time it is fresh.

##### Current Behavior
mainmenu search still contains last search entry.

##### Possible Solution
Actually I'm looking at the code since a time so that I can send a PR with the change.
I would prefer if someone could help me (give me some hints) and I send the PR so that I get used to the code.

##### Steps to Reproduce (for bugs)
- open menu
- click in search
- enter a program name (qterminal)
- click on the result
- open the menu again

##### Context
I think chances are low that a person wants to search for the same thing again when he reopens the menu ;)

##### System Information
* Distribution & Version: openSUSE Tumbleweed
* Kernel: 4.16.8
* Qt Version: 5.10
* liblxqt Version: latest git
* Package version: latest git

**Comment by jubalh** [comment]
@palinek, @tsujan maybe you guys can help. I'm looking at `lxqtmainmenu.cpp` since some time. I thought it must be as simple as clearing the filter when I get an enter or click event.

Or just clearing it every time the menu is opened. However I'm not sure why we have `mFilterClear(false),` in the `LXQtMainMenu` constructor.

Actually I wanted to debug the:
```
    if (mFilterMenu || mFilterShow)
    {
        if (mFilterClear && !mSearchEdit->text().isEmpty())
        {
            mSearchEdit->setText(QString{});
        }
```
part.

Usually I run the openSUSE git packages.
So now I checked out git locally, and opened lxqt-panel cmake file with qt-creator. Intended to debug the above part.

Panel appears, but no plugins in it.
Application output is:
```
(0x7fffffffdf50) Warning: "Plugin \"mainmenu\" not found."
(0x7fffffffdf50) Warning: "Plugin \"taskbar\" not found."
(0x7fffffffdf50) Warning: "Plugin \"desktopswitch\" not found."
(0x7fffffffdf50) Warning: "Plugin \"tray\" not found."
(0x7fffffffdf50) Warning: "Plugin \"statusnotifier\" not found."
(0x7fffffffdf50) Warning: "Plugin \"mount\" not found."
(0x7fffffffdf50) Warning: "Plugin \"volume\" not found."
(0x7fffffffdf50) Warning: "Plugin \"worldclock\" not found."
(0x7fffffffdf50) Warning: "Plugin \"showdesktop\" not found."
```

Not sure what's happening here?

**Comment by agaida** [comment]
![Clear search](https://i.imgur.com/QNTByFV.png)

**Comment by jubalh** [comment]
Thanks @agaida.

Is setting https://github.com/lxqt/lxqt-panel/blob/master/plugin-mainmenu/lxqtmainmenu.cpp#L64 to true the only thing that needs to be changed to have from now on the default value in so that this is on?

If yes I would like to create a PR for it, as I think this should be the default behaviour Probably this is what most users want.

**Comment by tsujan** [comment]
@jubalh IMHO, it's better to leave defaults as they are. A user might say, "I want it to remember the search because I want to use the searched item again and again." Both arguments are good; so, there is a setting.

**Comment by jubalh** [comment]
Okay if you guys are for leaving it as is, its fine.

I tend to think that its highly unlikely that a person wants to start 5 instances of the same application in a row. I think that it should be cleared after each search as a default setting. Probably more users are like this. Additionally I think all other DEs do it like clearing immediately and thus new users would be used to that too.

But I'm okay with leaving it too.

**Comment by tsujan** [comment]
That was just my opinion but, in this case, I can accept the opposite opinion too ;) I just don't think it's important.

**Comment by agaida** [comment]
in panel.conf
```
[mainmenu]
alignment=Left
filterClear=true
filterShowMaxItems=20
ownIcon=false
type=mainmenu
```

**Comment by jubalh** [comment]
@tsujan in any case: would changing the value like described above be the only thing thats needed? As I understand the code, yes.

**Comment by jubalh** [comment]
@agaida yeah I'm aware of the config option, and already prepared to change it for openSUSE. But still curious.

However what's your opinion, are you for letting the setting as it is?

**Comment by agaida** [comment]
i change my mind from time to time - depending on what i do in the moment - so I'm fine with both settings. With my LXQt hat on i would say - configurations are a distribution thing, just place a config file with your changes into /etc/xdg/lxqt :D (we moved our stuff to /usr/share/lxqt exactly to make this possible)

**Comment by tsujan** [comment]
> @tsujan in any case: would changing the value like described above be the only thing thats needed?

I don't remember. I think @palinek wrote it.

**Comment by jubalh** [comment]
@agaida yeah configuration is distributions thing. But it is the nature of things that upstream always provides defaults.

As LXQt we should think about what defaults we would like.

I know many here don't like GNOME, but they try to give some sane defaults. And let the user/distro decide about specifics. They try to use the defaults that makes the workflow easiest (yeah it is all debatable what is easy). In general I think they make a good job.

**Comment by tsujan** [comment]
> I know many here don't like GNOME,

I hate that crap...

@jubalh Feel free to make a PR for the defaults you see more appropriate.

**Comment by agaida** [comment]
nah - they don't leave much options to the user lately ...

**Comment by agaida** [comment]
+1 for pull requests, discussions and to postpone it :)

**Comment by jubalh** [comment]
@tsujan out of curiosity. Do you have an idea what I did wrong when I wanted to debug lxqt-panel? The thing with the plugins.

**Comment by tsujan** [comment]
> @tsujan out of curiosity. Do you have an idea what I did wrong when I wanted to debug lxqt-panel?

I can't be sure but opening a cmake project in Qt Creator can result in all kinds of weird things.

**Comment by jubalh** [comment]
@tsujan how then do you usually debug a project? You don't use QtCreator?

**Comment by palinek** [comment]
@jubalh have a look into https://forum.lxqt.org/t/lxqt-panel-is-not-showing-any-plugins/192/6

**Comment by tsujan** [comment]
> You don't use QtCreator?

Almost never; I use QTerminal+FeatherPad. For debugging, I compile the program with debug symbols (`-DCMAKE_BUILD_TYPE=debug`).

However, debugging is needed only when there's a problem. If you want to know what's done by which part of the code, use `qDebug()` and do NOT use Qt Creator (it suppresses `qDebug()`, `qCritical()`,...; a bad decision by Qt devs).

**Comment by jubalh** [comment]
@palinek, @tsujan Thanks guys :)

**Comment by stdcerr** [comment]
@yan12125 dug this thread up for me today as I was - just like @jubalh - looking into the modification of the search field behaviour as the application menu is re-opened. 
I was happy to learn though, that it is configurable. What the default setting is, is less important to me. I should have checked for a config option before I started looking into `lxqtmainmenu.cpp` about how to change the behaviour... I'm happy with the way it is! :)

**Comment by MartinX3** [comment]
I almost opened a new issue ticket about this behaviour, luckily I found this issue ticket and now I know I can activate this behaviour.
In my opinion it would be good, if the "clearing" behaviour would be the default one.

**Comment by stefonarch** [comment]
> I almost opened a new issue ticket about this behaviour, luckily I found this issue ticket and now I know I can activate this behaviour.
> In my opinion it would be good, if the "clearing" behaviour would be the default one.

I agree, but default settings can easily be shipped  by the distributions.

**Comment by tsujan** [comment]
Too much discussing about the default value of a setting that can be changed by the user and can be set by distros doesn't make sense. Also, those who prefer the current default don't feel a need to comment here.
