### ISSUE TITLE
Lxqt-panel 0.13.0 cannot be built on Archlinux - broken in main-menu/actionview.cpp:91:38

### ISSUE THREAD

**Issue by FredBezies** [lxqt/lxqt#1494]
I was trying to build lxqt 0.13.0 in an Archlinux virtualbox machine, and I cannot get past lxqt-panel.

Every single time, build process is crashing in plugin-mainmenu/actionview.cpp

See attached screenshot to get the full error log.

![virtualbox_lxqt 0 13 0_24_05_2018_22_51_21](https://user-images.githubusercontent.com/8571419/40513080-0641448a-5fa5-11e8-93ff-af145d4a82e2.png)

Tried both gcc 8.1.0 and clang 6, without luck. Both compiler cannot go past this file. Annoying :(

**Comment by tsujan** [comment]
You should upgrade libqtxdg before lxqt-panel.

**Comment by FredBezies** [comment]
I don't understand why libqtxdg was not upgraded to 3.2.0... What the?

**Comment by jeremywh7** [comment]
The build order is [here](https://github.com/lxqt/lxqt/wiki/Building-from-source), under Compiling -> General/Build Order.

**Comment by tsujan** [comment]
Without you being specific, as @FredBezies was, we can't say anything.

**Comment by tsujan** [comment]
@jeremywh7 Very sorry! I thought you couldn't build it either.

Yes, the order is mentioned there.

**Comment by agaida** [comment]
@jeremyh7 - hmm - i can't really belive that - https://www.archlinux.org/packages/?sort=&q=lxqt-panel&maintainer=&flagged=
it seems that you don't use the community packages. There was a change after the release  - so in case you have -Dsomething-with-plugin-clock=ON that will break the build.

**Comment by agaida** [comment]
Upps, my bad  -  @jeremyh7 - just file this: https://github.com/lxqt/lxqt-l10n/issues/352 and testing for other reasons that might wreck the build.
