### ISSUE TITLE
Add an option to Minimize / Restore windows with mouse scroll over their taskbar entry

### ISSUE THREAD

**Issue by thinslice** [lxqt/lxqt#1496]
I would like an option to change the mouse scroll / mousewheel behavior to minimize and unminimize windows when I scroll hovering the window buttons/entries/boxes in the taskbar.

There is a similar closed ticket (https://github.com/lxqt/lxqt/issues/1149) but the outcome was not what I want.

When the option is enabled:
Scrolling down should minimize the hovered window.
Scrolling up should restore the hovered window.

I want to transition from using LXDE to LXQt, and I miss this feature a lot. I very much like it in LXDE.

Sometimes the user wants to keep a window open while minimizing a lot of others, this way you can do it in one "move", and you don't need to check whether the other windows are visible, because it is a one-way action.

**Comment by tsujan** [comment]
Done in commits related to https://github.com/lxqt/lxqt-panel/pull/1161
