### ISSUE TITLE
WIP: Migrate translations into the right™ places

### ISSUE THREAD

**Issue by agaida** [lxqt/lxqt#1497]
Right now our translations of all components are located in lxqt-l10n - it was a good idea in former times. but would become real pita with weblate. Hence we should move it.

##### Expected Behavior
Having the translations in the repositories they belong to.

##### Current Behavior
Translations are in lxqt-l10n

##### Possible Solution
Just move it. Forked the whole project to https://github.com/4sid and created then needed translation-move branches there. 

###### Script to create the needed branches: 
* https://github.com/4sid/translation-move/blob/master/translations
* https://github.com/4sid/translation-move/blob/master/move-translations

###### Protocol ot the script run (TL;DR)
* https://gist.github.com/agaida/1d6fe61ce2bb92a726ee281b47452c1c

###### Translation Move PRs
* [compton-conf](https://github.com/lxqt/compton-conf/pull/69) (x)
* [libfm-qt](https://github.com/lxqt/libfm-qt/pull/201) (x)
* [liblxqt](https://github.com/lxqt/liblxqt/pull/144) (x)
* [lximage-qt](https://github.com/lxqt/lximage-qt/pull/134) (x)
* [lxqt-about](https://github.com/lxqt/lxqt-about/pull/51) (x)
* [lxqt-admin](https://github.com/lxqt/lxqt-admin/pull/63) (x)
* [lxqt-config](https://github.com/lxqt/lxqt-config/pull/155) (x)
* [lxqt-globalkeys](https://github.com/lxqt/lxqt-globalkeys/pull/71) (x)
* [lxqt-notificationd](https://github.com/lxqt/lxqt-notificationd/pull/81) (x)
* [lxqt-openssh-askpass](https://github.com/lxqt/lxqt-openssh-askpass/pull/31) (x)
* [lxqt-panel](https://github.com/lxqt/lxqt-panel/pull/473) (x)
* [lxqt-policykit](https://github.com/lxqt/lxqt-policykit/pull/40) (x)
* [lxqt-powermanagement](https://github.com/lxqt/lxqt-powermanagement/pull/69) (x)
* [lxqt-runner](https://github.com/lxqt/lxqt-runner/pull/75) (x)
* [lxqt-session](https://github.com/lxqt/lxqt-session/pull/127) (x)
* [lxqt-sudo](https://github.com/lxqt/lxqt-sudo/pull/35) (x)
* [obconf-qt](https://github.com/lxqt/obconf-qt/pull/43) (x)
* [pavucontrol-qt](https://github.com/lxqt/pavucontrol-qt/pull/52) (x)
* [pcmanfm-qt](https://github.com/lxqt/pcmanfm-qt/pull/688) (x)
* [qterminal](https://github.com/lxqt/qterminal/pull/424) (x)
* [qtermwidget](https://github.com/lxqt/qtermwidget/pull/182) (x)

###### Additional PRs
* [Remove not needed pavucontronl-qt/src/.gitignore](https://github.com/lxqt/pavucontrol-qt/pull/53) (x)
* [Remove obsolete and potential harmful panel/transtaltions/.gitignore](https://github.com/lxqt/lxqt-panel/pull/474) (x)
* [Remove translation related git stuff from build tools](https://github.com/lxqt/lxqt-build-tools/pull/30) (x)
* [remove pull/clean from compton-conf CMakeLists.txt](https://github.com/lxqt/compton-conf/pull/70) (x)
* [remove pull/clean from libfm-qt CMakeLists.txt](https://github.com/lxqt/libfm-qt/pull/202) (x)
* [remove pull/clean from liblxqt CMakeLists.txt](https://github.com/lxqt/liblxqt/pull/145) (x)
* [remove pull/clean from lximage-qt CMakeLists.txt](https://github.com/lxqt/lximage-qt/pull/135) (x)
* [remove pull/clean from lxqt-about CMakeLists.txt](https://github.com/lxqt/lxqt-about/pull/52) (x)
* [remove pull/clean from lxqt-admin CMakeLists.txt](https://github.com/lxqt/lxqt-admin/pull/64) (x)
* [remove pull/clean from lxqt-config CMakeLists.txt](https://github.com/lxqt/lxqt-config/pull/156) (x)
* [remove pull/clean from lxqt-globalkeys CMakeLists.txt](https://github.com/lxqt/lxqt-globalkeys/pull/72) (x)
* [remove pull/clean from lxqt-notificationd CMakeLists.txt](https://github.com/lxqt/lxqt-notificationd/pull/82) (x)
* [remove pull/clean from lxqt-openssh-askpass CMakeLists.txt](https://github.com/lxqt/lxqt-openssh-askpass/pull/32) (x)
* [remove pull/clean from lxqt-panel CMakeLists.txt](https://github.com/lxqt/lxqt-panel/pull/475) (x)
* [remove pull/clean from lxqt-policykit CMakeLists.txt](https://github.com/lxqt/lxqt-policykit/pull/41) (x)
* [remove pull/clean from lxqt-powermanagement CMakeLists.txt](https://github.com/lxqt/lxqt-powermanagement/pull/70) (x)
* [remove pull/clean from lxqt-runner CMakeLists.txt](https://github.com/lxqt/lxqt-runner/pull/76) (x)
* [remove pull/clean from lxqt-session CMakeLists.txt](https://github.com/lxqt/lxqt-session/pull/129) (x)
* [remove pull/clean from lxqt-sudo CMakeLists.txt](https://github.com/lxqt/lxqt-sudo/pull/36) (x)
* [remove pull/clean from obconf-qt CMakeLists.txt](https://github.com/lxqt/obconf-qt/pull/44) (x)
* [remove pull/clean from pavucontrol-qt CMakeLists.txt](https://github.com/lxqt/pavucontrol-qt/pull/54) (x)
* [remove pull/clean from pcmanfm-qt CMakeLists.txt](https://github.com/lxqt/pcmanfm-qt/pull/689) (x)
* [remove pull/clean from qterminal CMakeLists.txt](https://github.com/lxqt/qterminal/pull/425) (x)
* [remove pull/clean from qtermwidget CMakeLists.txt](https://github.com/lxqt/qtermwidget/pull/183) (x)

**Comment by PCMan** [comment]
@agaida Everything looks good except but I have one question.
Why we need an additional subfolder named "l10n"?
Isn't translation enough? What's the purpose of making it translation/l10n, which seems to be redundant.

**Comment by jleclanche** [comment]
There's Crowdin, I dunno if you looked at it: https://crowdin.com/page/open-source-project-setup-request

I've been using it for work stuff and it is.. frankly, better than everything else. And it handles translation-monorepos just fine (which I am 100% convinced are a much better system than embedding translations within the same repo and spamming the commit history with those).

**Comment by agaida** [comment]
@PCMan - that was intentional - just let desktop translations live in /translations/ and the ts things in /l10n/ - thats also a fine filter for possible translation updates with subcomponents aka
```
find . type -d -name l10n | do something
```
@jleclanche - wild guess: crowdin is not a viable option - like transifex - you remember the discussions some times ago? (not open, lock in etc) - even pootle is fine, but not for our use case.

**Comment by PCMan** [comment]
@agaida OK, but that l10n sub folder looks a little bit confusing at the first glance. If the pupose of that folder is for *.ts files only, then It's better to name it `ts_files` or something similar instead of `l10n`.
People will think that l10n folder should contain everything that needs to be localized (including translations for *.desktop files) but actually it only contain *.ts files.

Another issues is, how are we going to translate *.desktop files? In the past, we created one *.desktop file per locale and merge them later but there might be better tool for this task.
For example, I know there are tools to generate *.po files from *.desktop, and manage the translations with *.po so it can only be translated using the web ui. That's how gettext & intotools handle *.desktop files. With Weblate, dowe have a better way to manage the translations for *.desktop? Or we keep the current one *.desktop per language approach?

**Comment by agaida** [comment]
ok - lets drop the l10n dirs, no problem - just another run ot the modified script - have to read about the desktop files. afaik native support for desktop files was added to gnu gettext a while ago. and the translate toolkit contain the tools ts2po and po2ts - so there might be a way to script this if there is no native way.
To be honest - i would right now separate both cases.

**Comment by PCMan** [comment]
@agaida This looks pretty good now. Awesome! Thanks for the hard work.
IMHO, it's OK to leave the *.desktop files as they are now. I'm just curious if there are better tools to handle them since managing all translatable strings in one place is easier for translators. If there are no better ways, it's reasonable to keep the current workflow.
Waiting for others' feedback on Weblate.

@jleclanche Crowdin really looks nice, but using proprietary services indeed incurs some potential risks. We all remembered what happened to Transifex years ago. It might be safer for us to use something like pootle or weblate.

**Comment by agaida** [comment]
@PCMan - removing some /l10n with search and replace isn't that hard. And regarding the desktop files i found a not really answered question by @luis-pereira https://blog.du-a.org/2014/03/17/gettext-desktop/

Re: Crowdin - bitten once, twice shy - but there is another point about. Some translators are not willing to work with non-free services in FOSS projects, leave alone some developers. Personally i prefer a self hosted solution too, but are not limited to. In the end we have the translations in our git repos. And it was a really good experience to work on the featherpad translations with weblate, even if some features are not enabled right now. Ok, some things can be improved. And to answer @jleclanche - we can even squash the translation pull requests if we don't want to mess up our commit history to much. Even these workflows should be possible with a little bit help of upstream.

**Comment by tsujan** [comment]
> IMHO, it's OK to leave the *.desktop files as they are now.

I think so too.

**Comment by jleclanche** [comment]
Regarding the risks with proprietary software, I don't quite see them in this case. Crowdin doesn't store the data in proprietary formats or anything like that; if it goes under or anything like that happens, a migration can happen pretty easily. We shouldn't forget that Github itself is proprietary software.

But I hear @agaida's concerns on contributors' willingness to work (or not work) with proprietary platforms. If that is the case, I believe Crowdin can handle two-way sync on a git repository, so you could theoretically accept pull requests from there.

I don't have a stake in this at this point, and as you all know I'm much more an advocate of open platforms than closed ones, but I do want to share that I've had an excellent experience with Crowdin for work and will recommend it in a heartbeat. Weblate, in the mean time, doesn't even load for me in Chromium...

**Comment by agaida** [comment]
intltool sounds fine - never ever worked with - but i know at least that it exist.
Hmm - tested our weblate instance - works just fine with lynx, min, midori ...

**Comment by tsujan** [comment]
"Microsoft is acquiring GitHub!" I hope that won't be a bad news for us.

**Comment by agaida** [comment]
Why should it be? a) there is gitlab, gitea, the atlassian suite - so there are a lot of opportunities. and btw. we have an own git mirror running (gitea as backup) - and if it go in the gitlab direction - we could trust them or host it ourself (my private gitlab, just for fun: https://git.g-com.eu or gitea: https://git.siduction.org).

But i don't expect Microsoft to wreck github to be honest.

**Comment by tsujan** [comment]
I won't have any problem with microsoft if I don't see its ads.

**Comment by jleclanche** [comment]
@nijel 

![image](https://user-images.githubusercontent.com/235410/40929628-030b02ec-682e-11e8-8f10-7406a07531d6.png)

**Comment by agaida** [comment]
@nijel - confirmed with chrome, firefox redirects fine in my case to https://weblate.org/de/

**Comment by nijel** [comment]
Do you have up to date chrome? Googling this error I've found several workarounds in Chrome, but nothing for the server...


4. června 2018 18:32:37 SELČ, Jerome Leclanche <notifications@github.com> napsal:
>@nijel 
>
>![image](https://user-images.githubusercontent.com/235410/40929628-030b02ec-682e-11e8-8f10-7406a07531d6.png)

**Comment by tsujan** [comment]
> Do you have up to date chrome?

Mine is 67.0.3396.62 and I see the same error. Moreover, I see it with Falkon and `Mozilla/5.0 (X11; Linux x86_64; rv:57.0) Gecko/20100101 Firefox/57.0` as its user agent too. Only Firefox works fine.

**Comment by agaida** [comment]
google-chrome --version
Google Chrome 67.0.3396.62

**Comment by nijel** [comment]
Okay, I've figured it out - it was misconfigured nginx what caused problems only in Chrome based browsers.

**Comment by agaida** [comment]
Ok - all needed PRs are in place and tested - could not resist just to build an experimental iso with the changed sources/packages. Runs fine on real iron and kvm, kernel 4.17 and the current X seems to be to new for virtualbox.
![](https://i.imgur.com/lYJ9qJK.png)
Disclaimer: I *_really_* wouldn't suggest this as daily driver unless one know what one do.
  http://isobuilds.siduction.org/lxqt/amd64/siduction-18.3.0-paintitblack-lxqt-amd64-201806052047.iso

**Comment by agaida** [comment]
anything against merging this?
@PCMan  @luis-pereira @palinek @tsujan

**Comment by palinek** [comment]
No objections here.
(I hope you did double-check everything....as I didn't have much time to review it thoroughly)

**Comment by agaida** [comment]
@palinek - i even do the needed modifications in the packaging to see how it works with debian and derivatives - and run the resulting packages on my own main machine - right now i see no regressions.

**Comment by palinek** [comment]
Then go ahead.

**Comment by luis-pereira** [comment]
@agaida I didn't had the time to review it. Can't be of any help here.

**Comment by agaida** [comment]
@luis-pereira - ok, the cmake part was easy and far better - it works after my changes, so i don't see a problem

**Comment by PCMan** [comment]
@agaida no concerns. Please go ahead, and we need to update the wiki regarding to the new translation system. :-)

**Comment by agaida** [comment]
@PCMan - the changes was the funny and not so boring part - setting up weblate projects is easy, but not exactly funny. And yes, the wiki need an adjustment too.

**Comment by agaida** [comment]
@all - the migrated repos work fine with Debian and Arch AUR (full rebuild) - so it seems i managed it not to destroy everything. Hmm, maybe parts, but i didn't noticed these parts yet,

**Comment by palinek** [comment]
Great job!

**Comment by yan12125** [comment]
Awesome! Sorry had no time to test them before merging. Just rebuilt all LXQt components and everything looks good :)
