### ISSUE TITLE
Only informal:  Upstream realized their mistake and will restore qt5_use_modules in 5.11.1

### ISSUE THREAD

**Issue by agaida** [lxqt/lxqt#1503]
> Davide Pesavento gentoo-dev 2018-06-14 15:43:46 UTC
>
>(In reply to Andreas Sturmlechner from comment #0)
>> - CMake Error at CMakeLists.txt:95 (qt5_use_modules): Unknown CMake command
>> "qt5_use_modules". This is easily fixed by using
>> target_link_libraries(<target> Qt5::<modulename>) instead.
>
>Upstream realized their mistake and will restore qt5_use_modules in 5.11.1 https://codereview.qt-project.org/232367
@all

**Comment by tsujan** [comment]
Good.

**Comment by luis-pereira** [comment]
@agaida Where do we use `qt5_use_modules()` ?

**Comment by agaida** [comment]
dunno - it was only in case that we encounter problems with third parties etc - just informal

**Comment by tsujan** [comment]
It shows that they care and that's good.

**Comment by luis-pereira** [comment]
Thanks @agaida. Any new code should not use it.
I actually got rid of it years ago.

**Comment by agaida** [comment]
right now it is used in lxqt-connman-applet iirc
