### ISSUE TITLE
[lxqt-sudo] Non enough room for password prompt

### ISSUE THREAD

**Issue by SchweinDeBurg** [lxqt/lxqt#1505]
![lxqt-sudo](https://user-images.githubusercontent.com/2083917/41649211-87ce42d0-746a-11e8-84ee-ff4a972570ae.png)

"Please enter **your password**." - last two words are out of space here. My system font is Segoe UI, 12.

**Comment by tsujan** [comment]
Wrong size policy for that label, at least.
