### ISSUE TITLE
lxqt-runner does not use correct path to find executables

### ISSUE THREAD

**Issue by bleverett** [lxqt/lxqt#1506]
Lxqt-runner does not seem to use my $HOME/bin path.  That path is exported in both $HOME/.bashrc and $HOME/.bash_profile.  I have a couple of other computers with the same setup where lxqt-runner does find executables in my $HOME/bin directory. I can't find out where things are going wrong.

##### Expected Behavior

Pressing ALT-F2 and entering a command in $HOME/bin should run the command.  But only system commands are being launched from the ALT-F2 dialog.

##### Current Behavior

When I press ALT-F2 and enter the name of a command in $HOME/bin and press return, nothing happens.  I can launch these commands from the command line.

##### Steps to Reproduce (for bugs)

1. 
2. 
3. 
4. 

##### System Information

* Distribution & Version:   Gentoo
* Kernel:  4.9.95
* Qt Version: 5.9.4
* liblxqt Version: 0.11.0
* Package version:

**Comment by E5ten** [comment]
I think that would only make it applies in your terminal, to make it more universal you should put it in your .xprofile

**Comment by bleverett** [comment]
Thanks, that worked.  I've been using linux as my work desktop since 2000, and have never heard of .xprofile.  I looked it up and it seemed like the right place for the path, so that's a bug fixed.
