### ISSUE TITLE
Not enough room for the description message 

### ISSUE THREAD

**Issue by luis-pereira** [lxqt/lxqt#1507]
See the picture

##### Expected Behavior
Enough room for the message

##### Current Behavior
![screen-2018-06-26-14-02-47 png](https://user-images.githubusercontent.com/62877/41939295-379db7dc-798d-11e8-8029-a83de5b643ab.jpg)

##### System Information

* Distribution & Version: Manjaro
* Kernel: Not relevant
* Qt Version: 5.11
* liblxqt Version: git
* Package version: git

**Comment by luis-pereira** [comment]
I understood password prompt in another way and didn't open the report.
A layout policy thing, most likely. Don't have time, now to fix it. Opened it, to not be forgotten.
Closing it, at it was already reported.

**Comment by tsujan** [comment]
I had fixed it offline but saw other issues too and left it temporarily -- was working on other things. Should have made a PR then :(

**Comment by tsujan** [comment]
Ah, found it: This "sizePolicy" was wrong in the ui file and should be removed:
```
<sizepolicy hsizetype="Fixed" vsizetype="Fixed">
```
A few simple things could also be added.
