### ISSUE TITLE
pcmanfm-qt sorting error

### ISSUE THREAD

**Issue by verndog** [lxqt/lxqt#1508]
After setting sorting to "ascending", on reboot it is set back to "descending"

##### Expected Behavior
Expects sorting settings to be respected.
##### Steps to Reproduce (for bugs)

1. 
2. 
3. 
4. 

##### System Information

* Distribution & Version: 
* Kernel: 
* Qt Version: 
* liblxqt Version: 
* Package version:

**Comment by tsujan** [comment]
This may be about an old systemd issue or a problem in an old version of LXQt. Sorting is respected here after restarting the desktop.

Closing this because there's no version info.

**Comment by palinek** [comment]
It may also be the problem with config file permissions -> #874

**Comment by verndog** [comment]
This fixed it:

> It may have something to do with an old config file. Please

back up the folder '~/.config/pcmanfm-qt/',
close pcmanfm-qt and stop desktop from LXQT session settings,
remove the contents of '~/.config/pcmanfm-qt/' (with another file manager or in terminal),
start desktop again and see what happens.
