### ISSUE TITLE
Window positions are needlessly enforced

### ISSUE THREAD

**Issue by Vladimir-csp** [lxqt/lxqt#1509]
Most lxqt applications enforce their window positions without reason.
##### Expected Behavior

Applications that do not require specific window placement (like lxqt-panel or lxqt-leave do) leave their window placement for WM to decide.
##### Current Behavior

Applications force centered position of their windows. So far I found only `lxqt-config` and `lxqt-admin-user` not affected.
##### Possible Solution

Do not enforce window position where it is not needed. Make applications work like `lxqt-config` or `lxqt-admin-user` which arent affected by this bug.
##### Steps to Reproduce

1. Set window positioning policy in your favorite WM to something other than center.
2. Launch any `lxqt-config-something` application.
3. Application window appears at center regardless of WM policy.

**Comment by tsujan** [comment]
Depends on the perspective and is subjective. A counterargument is quite possible.

**Comment by tsujan** [comment]
No consensus will be reached about this. Forcing positions may not be a good practice but it isn't a sin either. You could be happy that it's impossible under wayland for now (a wayland regression that wayland devs might call a "feature").

**Comment by Vladimir-csp** [comment]
You might be conflating some things here. 
Ability to tell WM to give a window a specific geometry and position is a feature that has some use cases. If Wayland lacks this feature, that is unfortunate (although I understand the reasoning behind it). This bug is about lxqt-config apps abusing this feature and basically hijack WM's task of deciding where to place new windows all the time.

**Comment by tsujan** [comment]
Let's see what others might say.

**Comment by tsujan** [comment]
Update:

Except for lximage-qt, I don't think we enforce a centered position in our codes. WMs usually center dialogs. Also see https://github.com/lxqt/lxqt/issues/1691#issuecomment-472613180

**Comment by Vladimir-csp** [comment]
It's possible that "dialog" type is the reason, but also looking into xprop output I see this for lxqt-config-globalkeys, but not for lxqt-config-user-admin:

```
WM_NORMAL_HINTS(WM_SIZE_HINTS):
		user specified location: 929, 523
```
I do not know if it is possible disable special handling of "dialog" type in openbox. But here is some testing results:
Setting coordinates to `default` for dialog type in openbox rc.xml has no effect.
Setting coordinates to some value, like 40x40 with `force=yes` places the window at 40x40, but does not affect values seen in WM_NORMAL_HINTS above: those values are still shown as if window would be in the center
Setting coordinates to some value with `force=no`: window appears centered again.

Some time ago I goofed around with pyqt, if that has any similarities, I remember there were two functions that could be used for resizing windows. One of them affected only size (QWidget.resize), the other one (I think it was QWidget.geometry?) affected position, even if position arguments were omitted.

Looking at lxqt-config-locale/localeconfig.ui:

```
...
 <widget class="QWidget" name="LocaleConfig">
  <property name="geometry">
   <rect>
    <x>0</x>
    <y>0</y>
    <width>600</width>
    <height>450</height>
   </rect>
</property>
...
```
That property name and zeros inside look suspicious.

**Comment by tsujan** [comment]
> That property name and zeros inside look suspicious.

They aren't; they have no effect.

> but not for lxqt-config-user-admin

Because it's `QMainWindow`, not a dialog.

> I do not know if it is possible disable special handling of "dialog" type in openbox

Openbox is just one possible WM with LXQt. I use KWin and parentless dialogs are centered.

I think this can be closed again, although for the opposite reason: it's what (some) WMs do.

**Comment by tsujan** [comment]
As a non-LXQt example, consider this elementary program I use for color picking:

[qcolorpicker.zip](https://github.com/lxqt/lxqt/files/2963935/qcolorpicker.zip)

It can be compiled with `qmake && make`. It's window is always centered although its whole code is as simple as this:
```c++
#include <QApplication>
#include <QColorDialog>
#include <QIcon>

int main(int argc, char *argv[])
{
    QApplication app(argc, argv);

    QColorDialog dialog;
    dialog.setWindowTitle("QColorPicker");
    dialog.setWindowIcon(QIcon::fromTheme("kcolorchooser"));
    dialog.show();

    return app.exec();
}
```

**Comment by tsujan** [comment]
@Vladimir-csp 

I was wrong about what WMs might do; they were innocent ;) The "culprit" is `QDialog` itself: Qt source → `qdialog.cpp` → `QDialog::adjustPosition` (just read the code comments: 
```c++
    if (w) {
        // Use pos() if the widget is embedded into a native window
        QPoint pp;
        if (w->windowHandle() && w->windowHandle()->property("_q_embedded_native_parent_handle").value<WId>())
            pp = w->pos();
        else
            pp = w->mapToGlobal(QPoint(0,0));
        p = QPoint(pp.x() + w->width()/2,
                    pp.y() + w->height()/ 2);
    } else {
        // p = middle of the desktop
        p = QPoint(desk.x() + desk.width()/2, desk.y() + desk.height()/2);
    }
```

It was a surprise to me to see that Qt enforces a global position in this case.

**Comment by Vladimir-csp** [comment]
I just knew there was something fishy in this behavior.
OK, dialog centering against the parent makes sense. Dialog centering on desktop when it's standalone kinda makes sense too.
Why are lxqt-config apps presented as dialogs?

**Comment by tsujan** [comment]
> Dialog centering on desktop when it's standalone kinda makes sense too.

Our roles are reversed ;) I think Qt itself shouldn't override WM in this way; Qt users could.

> Why are lxqt-config apps presented as dialogs?

It's simply a valid usage of `QDialog`. When you don't need extra things that are provided by `QMainWindow` (especially menubar), you could use a parentless `QDialog`.

**Comment by tsujan** [comment]
That being said, one can ask: "why isn't lxqt-config itself so?"

My guess: when LXQt was being created, there was no time to pay attention to such extremely minute details. Personally, I think they're still unimportant.

**Comment by Vladimir-csp** [comment]
> I think Qt itself shouldn't override WM in this way; Qt users could.

I agree with this, I'm just rambling. 

> It's simply a valid usage of QDialog. When you don't need extra things that are provided by QMainWindow (especially menubar), you could use a parentless QDialog.

If "dialog" is conceptualized as something that demands attention and input + it is a subordinate to some app or daemon, then it makes sense to center it.  But Qt kinda mixed this with "just a lighter kind window".

How much of an overhead would `QMainWindow` have over `QDialog`?

I guess, a completely proper fix would be to convince upstream to add an optional parameter to `QDialog` that disables positioning.

**Comment by tsujan** [comment]
> How much of an overhead would QMainWindow have over QDialog?

Negligible.

> I guess, a completely proper fix would be to convince upstream to add an optional parameter to QDialog that disables positioning.

Believe me: that will never happen.

I opened https://github.com/lxqt/lxqt/issues/1692 because I became obsessed by this like you ;)

**Comment by tsujan** [comment]
One thing about `QDialog` is that it *should* be centered over its parent. Qt4 had bugs in this regard but, as far as I know, all of them were fixed in Qt5.

However, that means *relative positioning*. Why Qt devs decided that a parentless `QDilaog` should be centered over the whole desktop (by using the obsolete class `QDesktopWidget` and while every Qt user can do it in his/her code), I don't know.

**Comment by Vladimir-csp** [comment]
Unnecessary enforcement, done with an obsolete class, with easy alternatives. The pile doesn't stop from getting taller, this warrants a bug report upstream.

**Comment by tsujan** [comment]
> Unnecessary enforcement, done with an obsolete class...

Qt's source needs a vast update. For example, you could see the old connection syntax or `0` as `nullptr` here and there. Qt's doc needs update too -- they've removed lots of explanations from Qt5.12 doc for reasons unknown to me.

I guess they will do code updates for Qt6, which won't come soon.
