### ISSUE TITLE
Windows go under panel

### ISSUE THREAD

**Issue by verndog** [lxqt/lxqt#1511]
Moving any windows up or down to the panel, and they go undrneath.. In xfce it stops, not allowingws windows t go any further.
##### Expected Behavior
Expect windows to go above panel or stop once reaches panel
##### Current Behavior
Windows go behind panel
##### Possible Solution
unknown. This error has been made know in the past without any fixes. All know error reporting has been closed. 
##### Steps to Reproduce (for bugs)
grab any open window and drag it to panel and it goes behind
##### Context
trying to move a window out of the way
##### System Information
* Distribution & Version: Manjaro 17.1.9 LXQT
* Kernel: 4.9.110-1-MANJARO
* Qt Version: 0.13.0
* liblxqt Version: 0.13.0-1
* Package version: 0.13.0

**Comment by agaida** [comment]
not a bug, expected behaviour if the panel don't reserve space on screen - there is a setting for it.

**Comment by verndog** [comment]
This is a bug, and you better get use to others complaining. Once LXDE starts replacing LXDE you will get more of the same. If you think its not a bug, its a very POOR design!

**Comment by tsujan** [comment]
@verndog As said above, this ins't a bug; whether people want to complain about such things is another question. If you can put a part of a window out of the screen, you should be able to put it under a panel/ dock too. I'd consider the opposite as an annoying bug.

Anyhow, this is related to the window manager. You could report it to the developers of the WM you use, although I can't recommend that.

**Comment by agaida** [comment]
i mentioned the option in the panel settings, didn't i?

**Comment by tsujan** [comment]
@agaida What he said may also happen with that option enabled. We can reserve space for a panel/dock but we can't control what WMs do.

**Comment by agaida** [comment]
oh - at least it works fine with xfwm4

**Comment by tsujan** [comment]
@agaida It should never happen when a window is opened and, as far as I know, it doesn't with any WM. However, it 's allowed to happen with garbing and moving windows. The (X11) moving code is inside the WM source, not in LXQt.

**Comment by agaida** [comment]
@tsujan - you are right, but as you said, it is up to the WM

**Comment by tsujan** [comment]
> it is up to the WM

Exactly!

**Comment by verndog** [comment]
Actually, the "resistance strength" is the answer. Setting mine to '300' gave enough pressure resistance to work well. 
Just curious though, why it was chosen for windows to go under vs go over the panel. Or was this not chosen at all, and is the characteristic of the WM.

**Comment by Vladimir-csp** [comment]
It depends on what layer panel resides, what WM hints assigned to panel's window, as far as I remember.
