### ISSUE TITLE
cant create desktop shortcuts & default browser & network icon

### ISSUE THREAD

**Issue by joksik** [lxqt/lxqt#1512]
1) first bug - after i install fresh lxqt latest version 0.13 under arch i see that i can`t create shortcuts on  desktop when i drag icon from menu to desktop i choose copy but on desktop nothing happen

2) second - i install chromium browser and every time when i run browser i have messages to set default browser but i set default browser in lxqt settings so something is wrong because my settings is ignored

3) when i change few icons theme for example: adwaita and papirus all icons in lxqt change but only wifi icon in network manager applet on taskbar remains unchanged

* Distribution & Version: Arch with LxQT 0.13 
* Kernel: 4.17.4 
* Qt Version: 5.11.1
* liblxqt Version: 0.13.0-1

**Comment by tsujan** [comment]
(1) is definitely a bug to fix. I have nothing to say about (2) and (3).

Please don't report several bugs as one issue!

**Comment by tsujan** [comment]
Update:

This is an old bug in `libqtxdg` (will fix it soon). It has surfaced only after menu-cache is removed from the main menu.
