### ISSUE TITLE
Session should be locked prior to suspend, not after

### ISSUE THREAD

**Issue by tsimonq2** [lxqt/lxqt#1515]
It seems to be a common problem that when you open a laptop lid after suspend, the contents of the screen are visible shortly before displaying a lock screen. This can be classified as a security issue.

GNOME's solution, at least as patched in Ubuntu, is to lock the screen and only once the screen is locked, suspend.

I'm going to experiment with solving this in Lubuntu, but an upstream solution doing exactly this would be very ideal.

Thanks.

**Comment by tsujan** [comment]
I don't use screen locking but when I tested it with xscreensaver last year, I saw the flash, searched the Internet and found that it's a known problem with xscreensaver.

**Comment by tsimonq2** [comment]
I confirmed with the Ubuntu Desktop Team that the way they fixed GNOME and Unity is they ensured the lock screen was painted __before__ suspend kicked in. Otherwise, suspend kicks in before the screen is painted, thus resulting in the delay on resume.

**Comment by Vladimir-csp** [comment]
It is a common problem and has nothing to do with any particular screensaver. It's just a matter of ordering events.
I lock screen on sleep with a combination of xss-lock, i3lock, and loginctl. Adding a time delay to locking unit helped me avoid this problem.
```
[Unit]
Description=Lock sessions before sleep
Before=sleep.target

[Service]
Type=oneshot
ExecStart=-/bin/loginctl lock-sessions
ExecStartPost=/bin/sleep 1

[Install]
WantedBy=sleep.target
```

**Comment by agaida** [comment]
@Vladimir-csp - interesting approach - but normally xdg-screensaver lock at the right place should be enough.

**Comment by agaida** [comment]
@tsujan @palinek @luis-pereira - i need a bit help, i'm blind (as usual) - we have a checkbox `lxqt-config-session/basicsettings.ui:       <widget class="QCheckBox" name="lockBeforePowerActionsCheckBox">
` but i don't find any corresponding value in any config file  - is it just me or missed we something?

**Comment by tsujan** [comment]
Will look into it later.

**Comment by tsujan** [comment]
@agaida Sorry, I was wrestling with 2 problems. The check-box is here:

![session](https://user-images.githubusercontent.com/981076/46102335-e68f9180-c1da-11e8-8dd3-82723bdae48b.png)

**Comment by tsujan** [comment]
And the corresponding key is `lock_screen_before_power_action`, under `General`. For me:
```
[General]
__userfile__=true
leave_confirmation=true
lock_screen_before_power_actions=false
window_manager=kwin_x11
```

**Comment by agaida** [comment]
that do the trick - and make me not happy :(

**Comment by tsujan** [comment]
> that do the trick

Apps may not write values that are equal to their defaults. If a value is changed from the default, it'll be written; if it's reverted, it'll also be written.

**Comment by agaida** [comment]
Hmm, maybe a few more words - the box was checked all the time. I guess that what users with older installations will see, have to check it with a new installation - and that lead to a thing that don't make me happy: if  "lock_screen_before_power_actions"  is read from the setting (and not set, if not found in any setting) - the LXQt locking behaviour will be pure and utter crap - until a user uncheck and check this damn box again. See forum.

**Comment by tsujan** [comment]
>  the box was checked all the time

Then, the default should be `true` and so, you didn't have that value while I had it. Otherwise, there will be a bug.

I use this opportunity to say something about `QSettings` -- it's not very related to the above question.

`QSettings` writes an *unchanged* value to the config file. This kind of writing is annoying to me because it happens when there's no change. In my apps, I always subclass `QSettings` to avoid redundant writings. I do so with some LXQt apps too but in personal patches.

**Comment by tsujan** [comment]
> if "lock_screen_before_power_actions" is read from the setting (and not set, if not found in any setting) - the LXQt locking behaviour will be pure and utter crap

Not being found in any setting is NOT a problem. If LXQt's behavior is wrong with `true` as default (supposing that `true` is default), then there should be a bug somewhere.

**Comment by tsujan** [comment]
I haven't checked the code but if the code needs the setting for `true` while `true` is the default (supposedly), then a boolen may haven't been initialized.

**Comment by agaida** [comment]
i mean that bug - and it isn't happend if i lock the screen with `xdg-screensaver lock` and then hibernate or suspend the machine

**Comment by tsujan** [comment]
I think it was known before LXQt was created. I tried so many tricks I'd found on Internet; none of them worked. Then I said, "Who needs this?" and uninstalled xscreensaver.

GNOME uses its own locker; am I right?

**Comment by agaida** [comment]
an xscreensaver fork iirc

but thats not the point: if i lock the screen manually and suspend after - the screen don't show for a second. Discussed that with @luis-pereira and @palinek a year or so ago.

**Comment by tsujan** [comment]
> but thats not the point: if i lock the screen manually and suspend after - the screen don't show for a second

I knew that a year ago and this was my thought (and it may be wrong): When suspend/hibernation is going to happen, it's too late. What comes immediately before suspend/hibernation, I don't know.

**Comment by Vladimir-csp** [comment]
> but thats not the point: if i lock the screen manually and suspend after - the screen don't show for a second. 

It just takes more time to show the locker, than to suspend the system if both processes start at the same time.

**Comment by tsujan** [comment]
Or, maybe, a minimum interval is required by xscreensaver. When you lock the screen manually, that interval exists for sure.

**Comment by tsujan** [comment]
All in all, I still think this is an xscreensaver bug and a workaround can be adding a `QTimer` by trial and error -- ugly but practical.

**Comment by agaida** [comment]
again @tsimonq2:
> I confirmed with the Ubuntu Desktop Team that the way they fixed GNOME and Unity is they ensured the lock screen was painted before suspend kicked in. Otherwise, suspend kicks in before the screen is painted, thus resulting in the delay on resume.

So the culprit seems to be that the saver is painted and the state of the saver is saved.

**Comment by tsujan** [comment]
After/before == timer + trial and error

**Comment by Vladimir-csp** [comment]
> All in all, I still think this is an xscreensaver bug and a workaround can be adding a QTimer by trial and error -- ugly but practical.

Xscreensaver has no control over when to start suspend, how can it be its bug?

**Comment by tsujan** [comment]
> Xscreensaver has no control over when to start suspend, how can it be its bug?

A screen locker should know about such things.

**Comment by agaida** [comment]
jwz would see it not as a bug and is probably right - ok, i'm not one of his fans, but i guess he is right.

**Comment by agaida** [comment]
@tsujan - it's all about the state of the saver - if the state is not locked, the screen come up unlocked  and will be locked afterwards.

**Comment by Vladimir-csp** [comment]
> A screen locker should know about such things.

Why? it is a locker, not a suspender. Power management or session tool invokes a locker and a suspender. If it does so in sequence instead of in parallel, everything should work fine.

**Comment by tsujan** [comment]
> Why? it is a locker, not a suspender

It's too late for such a discussion. If xscreensaver was going to made right now and it didn't know about suspend/hibernation, I would tell its developers that a screen locker is used mostly in relation to suspend/hibernation.

**Comment by tsujan** [comment]
Use Google with "xscreensaver lock screen brief moment"

**Comment by agaida** [comment]
erm - jmz might be the bigges moron on earth (some people say so) - but he is the only one who does the X screenlocking right and secure - most of the people who forked his code done it wrong :sunglasses:

**Comment by tsujan** [comment]
systemd didn't exist when xscreensaver was made.

Anyhow, theoretically, we can add a setting for "Wait before suspend: SPIN_BOX" when `lock_screen_before_power_actions` is `true`.

**Comment by Vladimir-csp** [comment]
> It's too late for such a discussion. If xscreensaver was going to be made right now and it didn't know about suspend/hibernation, I would tell its developers that a screen locker is used mostly in relation to suspend/hibernation.

You use the tool that locks screen to lock screen, then you use the tool that suspends the system to suspend the system. Nothing can go wrong in this case. Why one tool should know anything about the other tool?

**Comment by tsujan** [comment]
> Why one tool should know anything about the other tool?

Continuing a discussion like that doesn't help solving this issue.

**Comment by tsujan** [comment]
I remember that I read somewhere that xscreensaver worked well with `pm-util` -- which means it's too old.

**Comment by agaida** [comment]
erm - @tsujan - wrong. yesterday xscreensaver works just fine with systemd on my machine - the fault was not in the wake-up - that was perfectly fine. The fault was the before going into suspend or hibernation. And in this no systemd is involved.

**Comment by tsujan** [comment]
> The fault was the before going into suspend or hibernation.

Which is handled by systemd, about which xscreensaver knows nothing; or does it?

**Comment by tsujan** [comment]
Really, we (or anyone who wants to solve this problem and not just work around it) should see how Gnome fixed it. Or, perhaps, Gnome didn't need to fix anything with its locker.

**Comment by agaida** [comment]
the trick is: start the lock, wait until the lock is happend, trigger systemd to take over.

in my case i started the lock wit xdg-screensaver start, wait until the screen is locked and triggered the suspend by closing the lid.

**Comment by tsujan** [comment]
> the trick is: start the lock, wait until the lock is happend, trigger systemd to take over.

Exactly! But we can't know when the lock happens ;)

**Comment by agaida** [comment]
we can :P

**Comment by tsujan** [comment]
How?

**Comment by agaida** [comment]
xdg-screensaver status?

**Comment by palinek** [comment]
> xdg-screensaver status?

yes, and we do use it ... IIRC

**Comment by tsujan** [comment]
> xdg-screensaver status

Qt should be able to get the output through `QProcess`.

**Comment by tsujan** [comment]
> yes, and we do use it

If we use it but it's still soon, then... long live, sxreensaver ;)

**Comment by agaida** [comment]
```cpp
bool LockScreenManager::startup(bool lockBeforeSleep)
{
    mProvider = new LogindProvider;
    if (!mProvider->isValid())
    {
        mProvider->deleteLater();
        mProvider = new ConsoleKit2Provider;
        if (!mProvider->isValid())
        {
            mProvider->deleteLater();
            mProvider = nullptr;
        }
    }

    if (!mProvider)
    {
        qCDebug(SESSION) << "LockScreenManager: no valid provider";
        return false;
    }

    qCDebug(SESSION) << "LockScreenManager:"
            << mProvider->metaObject()->className()
            << "will be used";

    connect(&mScreenSaver, &LXQt::ScreenSaver::done, &mLoop, &QEventLoop::quit);

    connect(mProvider, &LockScreenProvider::lockRequested, [this] {
        mScreenSaver.lockScreen();
        mLoop.exec();
    });

    if (lockBeforeSleep)
    {
        connect(mProvider,
                &LockScreenProvider::aboutToSleep,
                [this] (bool beforeSleep)
        {
            if (beforeSleep)
            {
                qCDebug(SESSION) << "LockScreenManager: system is about to sleep";

                mScreenSaver.lockScreen();
                mLoop.exec();
                mProvider->release();
            }
            else
                mProvider->inhibit();
        });

        if (!mProvider->inhibit())
            qCDebug(SESSION) << "LockScreenManager:"
                    << "could not inhibit session provider";
    }

    return true;
```
@palinek - where

**Comment by ckrzen** [comment]
Also:  xscreensaver has a setting that is _very_ detrimental to this
issue:  "Fade to Black when Blanking" induces a delay that, as @Vladimir-csp
points out, when calling screen-locker and suspend in parallel causes the
locker to activate _after_ suspend which leads to the screen exposures upon
wake-up.

SOURCE:  https://askubuntu.com/a/454295/443610

and:  https://bugs.launchpad.net/ubuntu/+source/unity-2d/+bug/830348

and:  https://bbs.archlinux.org/viewtopic.php?id=222027

and:  https://bbs.archlinux.org/viewtopic.php?id=206840

and:  https://bugzilla.xfce.org/show_bug.cgi?id=13761

**Comment by tsujan** [comment]
Can anyone having xscreensaver try @ckrzen suggestion, namely disabling "Fade to Black when Blanking"?

**Comment by tsujan** [comment]
> When the system is already being suspended, it's too busy to draw anything in time.

But @palinek said that the order is correct.

**Comment by agaida** [comment]
done yesterday - also set to pure black screen - result: we should wait until locked + fade to black time - should be possible - and we are not limited to xscreensaver. And it doesn't matter how fast the screen is locked - the only thing that is of interest is that the screen is really locked before trigger the suspend or hibernation.

**Comment by tsujan** [comment]
> And it doesn't matter how fast the screen is locked - the only thing that is of interest is that the screen is really locked before trigger the suspend or hibernation.

I don't think we can differentiate between "locked" and "really locked" in the code.

I have never read the code. Will seet it when I have a lot of energy ;)

**Comment by ckrzen** [comment]
Not sure if this is true, but by my observations:  suspend with LXQt or
XFCE4 or just plain Openbox happens in ~1.0 seconds on my Thinkpad T420
laptop. Same install on same laptop in a gnome-session takes ~4.0 to 5.0
seconds. That is, until the little crescent moon icon is lit on the
outside of the laptop lid to indicate it has reached the suspended state.
So:  would it be correct to just inject a 4.0 to 5.0 second delay after
calling the xdg-screensaver script while inhibiting(blocking) the
logind "lid-actions" process? I.e.:  $ systemd-inhibit --list

**Comment by palinek** [comment]
Hm... I was wrong about the `xdg-screensaver status` ..., but based on the man page, it isn't the action we need:
```
       status
           Prints enabled to stdout if the screensaver is enabled to turn on after a period of inactivity and prints disabled if the screensaver is not enabled.
```

**Comment by tsujan** [comment]
> So:  would it be correct to just inject a 4.0 to 5.0 second delay after calling the xdg-screensaver script while inhibiting(blocking) the logind "lid-actions" process?

Basically, that's the same as my suggestion; the difference is just that I thought the delay should be configurable (between 0 and 15 sec.). On second thought, I don't like my suggestion; it's too ugly.

**Comment by agaida** [comment]
ok - @Vladimir-csp made  suggestion in the other issue which sounds resonable - as in "forget about xdg, just use the needed commands directly" https://github.com/lxqt/lxqt/issues/1378#issuecomment-424864747

for xscreensaver the needed command would be xscreensaver-command -watch, here is the output:
``` 
% xscreensaver-command -watch
LOCK Wed Sep 26 22:56:48 2018
UNBLANK Wed Sep 26 23:04:17 2018
```

**Comment by agaida** [comment]
the remaining thing is: how to catch lid and other actions - lxqt-leave is easy i guess

**Comment by Vladimir-csp** [comment]
> the remaining thing is: how to catch lid and other actions

doesn't lxqt-powermanagement inhibit and overtake these?

**Comment by tsujan** [comment]
> for xscreensaver the needed command would be xscreensaver-command -watch, here is the output

If (1) the command exists and (2) its output is really "LOCK" immediately after locking -- and not just after unlocking -- it could be used by Qt.

**Comment by tsujan** [comment]
Sorry, I meant "exits", not "exists"... :D

**Comment by palinek** [comment]
Just made some testing... and the problem is following:
- upon the first "suspend" in session, the logind suspend logic is delayed properly (suspend after dimming the screen by xscreensaver)
- but `lxqt-session` is unable to take the inhibitor lock once the session is restored

The session output with some added debugs:
- first suspend in session
```
(0x7ffcec73bf58) Debug: LockScreenManager: system is about to sleep
(0x7ffcec73bf58) Debug: LockScreenManager: after lock
(0x7ffcec73bf58) Critical: auto LXQt::ScreenSaverPrivate::_l_xdgProcess_finished(int, QProcess::ExitStatus)::(anonymous class)::operator()() 19 true
(0x7ffcec73bf58) Debug: LockScreenManager: after exec
(0x7ffcec73bf58) Debug: LockScreenManager: after release
(0x7ffcec73bf58) Debug: LockScreenManager: could not inhibit session provider
```
... but we are doing it like in doc: https://www.freedesktop.org/wiki/Software/systemd/inhibit/#takingdelayLocks

**Comment by palinek** [comment]
Please, test with lxqt/lxqt-session#175 .... (I don't know if it is enough...because I tested it here with some changes in `liblxqt` logic)

**Comment by luis-pereira** [comment]
@palinek 
Should one test

- https://github.com/lxqt/lxqt-session/pull/175
- https://github.com/lxqt/liblxqt/pull/175

in conjunction ?

I will first test without any patch. This issue oddly vanished in my system, some time ago. I was under the impression it was fixed. 

p.s. The PR's happened to have the same PR number (175).

**Comment by palinek** [comment]
...after many attempts to solve the suspend postponing here is some resume:
- while waiting for the screensaver to completely do it's job we can't use `ScreenSaverPrivate::isScreenSaverLocked()` in liblxqt -> IMO the whole X is "somehow frozen" and we don't get any X response in application (`lxqt-
session`) 
- even if we try to log the lock status by e.g.: `QProcess::startDetached(QL1S("/bin/sh"), {QL1S("-c"), QL1S("xprop -root | egrep '_SCREENSAVER_STATUS'")});` in the recurring timer.... we don't get any result until the X is unlocked (no X replies in the "locked" state)
- when the "dimming" is active in xscreensaver settings xscreesaver doesn't show the real screen content but is fading a screenshot (no changes are shown while fading)
- it seems that `systemd` does not allow to delay the suspend for too long (the system is going to supend even if the inhibitor FD is not closed) -> the maximum seems to be 5 seconds

So if there is no other mean to know if the screensaver/locker did finish its fancy dimming (some DBus call or other kind of IPC). IMO there is really nothing better we can do than to add configuration for the "delay_suspend_after_lock_for_x_seconds" (and document the state and behavior for our users).

**Comment by palinek** [comment]
>  there is really nothing better we can do than to add configuration for the "delay_suspend_after_lock_for_x_seconds" 

Done in lxqt/lxqt-session#175

**Comment by palinek** [comment]
> it seems that systemd does not allow to delay the suspend for too long (the system is going to supend even if the inhibitor FD is not closed) -> the maximum seems to be 5 seconds

I was right and it is configurable :) -> https://www.freedesktop.org/software/systemd/man/logind.conf.html#InhibitDelayMaxSec=

**Comment by agaida** [comment]
@palinek - nearly right - a look into login conf shows:
```
e /etc/systemd % cat logind.conf
#  This file is part of systemd.
#
#  systemd is free software; you can redistribute it and/or modify it
#  under the terms of the GNU Lesser General Public License as published by
#  the Free Software Foundation; either version 2.1 of the License, or
#  (at your option) any later version.
#
# Entries in this file show the compile time defaults.
# You can change settings by editing this file.
# Defaults can be restored by simply deleting this file.
#
# See logind.conf(5) for details.

[Login]
#NAutoVTs=6
#ReserveVT=6
KillUserProcesses=yes              <--- i recommend this for desktop usage, debian default is no 
#KillOnlyUsers=
#KillExcludeUsers=root
#InhibitDelayMaxSec=5            <---
#HandlePowerKey=poweroff
#HandleSuspendKey=suspend
#HandleHibernateKey=hibernate
#HandleLidSwitch=suspend
#HandleLidSwitchExternalPower=suspend
#HandleLidSwitchDocked=ignore
#PowerKeyIgnoreInhibited=no
#SuspendKeyIgnoreInhibited=no
#HibernateKeyIgnoreInhibited=no
#LidSwitchIgnoreInhibited=yes
#HoldoffTimeoutSec=30s
#IdleAction=ignore
#IdleActionSec=30min
#RuntimeDirectorySize=10%
#RemoveIPC=yes
#InhibitorsMax=8192
#SessionsMax=8192
```

**Comment by agaida** [comment]
screen locking works reliable now - so i guess this can be closed as solved - I guess it is worth to take a closer look at Vladimirs suggestion in the next release cycle aka after the upcoming release.

**Comment by tsujan** [comment]
Having had time to test it, I confirm that screen locking works reliably with a 3-s delay in LXQt Session Settings; didn't test shorter delays though.

**Comment by agaida** [comment]
meanwhile i'm much wiser than before - erm, we should really the  (insert some swearwords here) FAQs of things we plan to support - found it one or two years to late :smile:
https://www.jwz.org/xscreensaver/faq.html#cpu-halt

The FAQs are a good read at all.

**Comment by tsujan** [comment]
Quoting from there:

"I gather that some Linux systems have a way for a script to run between steps 2 and 3, to run "xscreensaver-command -lock" and wait for it to complete before halting the CPU, which would solve this problem."

That's the problem: there's no logic to that waiting; hence adding a configurable delay;

**Comment by agaida** [comment]
yeah - thats what we did - but we should have read this years ago :D

**Comment by agaida** [comment]
yes :)
