### ISSUE TITLE
Volume control plugin confuses volume readings from other devices

### ISSUE THREAD

**Issue by ypnos** [lxqt/lxqt#1516]
##### Expected Behavior
I have two volume control plugins in the panel, one I set up to control "HDA NVidia Digital Stereo (HDMI 3), the other to control "Built-in Audio Analog Stereo".

Up until recently I could control both volumns independently from each other and use `pavucontrol-qt` to send application streams to where I want to hear them.

##### Current Behavior
When I change the volume on the first plugin instance, it works as expected.
When I change the volume on the second plugin instance, it adjusts the volume of both outputs (HDMI and Analog Stereo).

Now it gets more tricky but this will help to better understand the bug:
When I use `pavucontrol-qt` to change the volume of Analog Stereo, both plugin instances update to the new volume; when I change the volume of HDMI, only the corresponding plugin instance is updated.

##### Possible Solution
I would assume when volume updates from PulseAudio come in, the check needs to be improved whether the update is corresponding to the plugin instance's output device.

##### Steps to Reproduce
1. Add volume plugin and setup to track/control one output device
2. Add another plugin for another output device
3. Change volumes of said devices with the plugin sliders or in an external program and watch values of other plugin instances

##### System Information
* Distribution & Version: Arch Linux
* Kernel: 4.17.2
* Qt Version: 5.11.1
* liblxqt Version: 0.13.0
* Package version: 0.13.0

**Comment by palinek** [comment]
> Up until recently 

What package/application/configuration has changed?

**Comment by ypnos** [comment]
Cannot recover that information, I don't know since when the erratic behavior was present. I do regular updates and I can't remember when I used the Analog Stereo output the last time before recently (sometimes I don't use it for months).

**Comment by tsujan** [comment]
I think it's very likely that the issue isn't related to LXQt but a result of the above-mentioned upgrade. Please close it if so.

**Comment by ypnos** [comment]
Indeed that seems to have solved my issue. Thank you for your help!
