### ISSUE TITLE
Decreasing the volume when it's muted shouldn't unmute it

### ISSUE THREAD

**Issue by tsimonq2** [lxqt/lxqt#1520]
When something plays way too loud on my system, I'd like to be able to mute it and adjust it to a safe level via the scroll wheel before unmuting.

I remember at minimum my TV doing it this way, and in other desktops as well.

**Comment by tsujan** [comment]
I agree that the described behavior is desirable.

**Comment by palinek** [comment]
Done in lxqt/lxqt-panel#596
