### ISSUE TITLE
LXQt apps can find system-wide config when XDG_CONFIG_DIRS globally set to "/etc/xdg"

### ISSUE THREAD

**Issue by amoskvin** [lxqt/lxqt#1521]
When a new user logs in for the first time, they get prompted to manually find a window manager on the filesystem, and then they're presented with a black desktop and an invisible panel with no widgets.

This is because session/panel tries to find the config in e.g. `/etc/xdg/lxqt/windowmanagers.conf` but the config is installed into `/usr/share/lxqt/windowmanagers.conf`.

##### Expected Behavior

Configs should be installed into `${LXQT_ETC_XDG_DIR}/lxqt` rather than `${CMAKE_INSTALL_DATADIR}/lxqt`.

`$XDG_CONFIG_DIRS` is the base dir for `~/.config` (`$XDG_CONFIG_HOME`), so default configs
should be installed there.

`/usr/share` (`$XDG_DATA_DIRS`) is meant to be the base for files in `$HOME/.local/share` (`$XDG_DATA_HOME`).

See: https://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html

##### Current Behavior

If `$XDG_CONFIG_DIRS` is already set, startlxqt correctly verifies that `LXQT_ETC_XDG_DIR` is in `$XDG_CONFIG_DIRS` and moves along.
https://github.com/lxqt/lxqt-session/blob/77d90116456f4b19d0bcbecee9767671709c72b5/startlxqt.in#L26-L32

However, the config files are not installed there, but instead into the data directory, resulting in poor behavior for new users.
https://github.com/lxqt/lxqt-panel/blob/3a073425121de24c18070d6ae71493e13b4c8f63/panel/CMakeLists.txt#L107

##### Possible Solution

The following commits should be rolled back:
https://github.com/lxqt/lxqt-session/commit/3e39f49465f9b7b73261ba69e3b83a27fb6b9253
https://github.com/lxqt/lxqt-panel/commit/ddd62e07914feda21c01e712647ffd6cc4caaff7

And this should be updated: https://github.com/lxqt/liblxqt/blob/master/CMakeLists.txt#L361

lxqt-globalkeys is fine, but I might have missed some others.

##### Steps to Reproduce (for bugs)

1. Log out of LXQt and move `~/.config/lxqt`
2. Set `XDG_CONFIG_DIRS=/etc/xdg`
3. Start LXQt

##### Context

Testing proposed Gentoo package for LXQt 0.13.0 (https://github.com/gentoo/gentoo/pull/9202)

##### System Information

* Distribution & Version: Gentoo
* Qt Version: 5.11.1
* liblxqt Version: 0.13.0

**Comment by agaida** [comment]
nope, want fix - two choices: add /usr/share to XDG_CONFIG_DIRS - or place the files in the folders you want. We moved these basic configurations to /usr/share/lxqt exactly for a reson: get out of the way of distributions - so this is up to you.

**Comment by agaida** [comment]
https://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html#variables

^^ So this is clearly a pure downstream problem

**Comment by tsimonq2** [comment]
@amoskvin I guess we're similar as distributors :)

I made [a pull request](https://github.com/lxqt/lxqt-session/pull/126) adding some very simple verification but upstream wasn't having it.

Oh well, at least it serves as some type of documentation for other distributors in similar situations.
