### ISSUE TITLE
prompt when launching shortcuts from desktop

### ISSUE THREAD

**Issue by joksik** [lxqt/lxqt#1523]
i install libqtxdg from git and now i can create desktop icons so one bug from this [issue](https://github.com/lxqt/lxqt/issues/1512) was fixed but now always when i launch apps from desktop i have popup windows with message:

> This file 'Falkon' seems to be a desktop entry. What do you want to do with it? 

how can i disable this irritating messages?

Distribution & Version: Arch with LxQT 0.13
Kernel: 4.17.7
Qt Version: 5.11.1
liblxqt Version: 0.13.0-1

**Comment by stefonarch** [comment]
You can disable it in PCmanfm > preferences > Launch executable files without prompt

**Comment by tsujan** [comment]
As @stefonarch explained. And please don't open issues for questions.
