### ISSUE TITLE
lxqt-panel doesn't care about volumes above 100%

### ISSUE THREAD

**Issue by tsimonq2** [lxqt/lxqt#1526]
OK, maybe this is an edge case and maybe I'm hurting my ears... :D

When the system volume goes above 100%, let's just say 103%, it just shows 100%.

**Comment by tsimonq2** [comment]
Just confirmed; pavucontrol-qt goes to 153%.

**Comment by tsujan** [comment]
Happens here too. pavucontrol-qt is OK but panel's volume control doesn't show volumes above 100%.

I guess no one had tested this rare case before.

**Comment by Chiitoo** [comment]
Heh, well I mean with just ALSA, I'm not sure how one would go over 100% which made me curious.  I've never /really/ used PulseAudio, so I'm not exactly sure about that either... but I can only imagine it's different.  :]

**Comment by tsujan** [comment]
:)

Yes, with PulseAudio, you could go over 100%.

Between you and me: PulseAudio isn't like systemd anymore. it tortured us until it really became mature and reliable :D

**Comment by Chiitoo** [comment]
Makes sense then, yeah.  Thanks!

(I've been without it mostly just because I haven't felt the need for it, but yeah, I've seen many mentions of it being rather okay these days.)

**Comment by tsujan** [comment]
Gentoo: a distro that kindly lets its users remain far from harms but, sometimes, forgets that the bad years are over.... just joking.

**Comment by palinek** [comment]
With the "Allow volume beyond 100% (0dB)" enabled...plugin-volume's slider shows 66% for pavucontrol's 100% and 100% for pavucontrol's 153%.

**Comment by tsujan** [comment]
> With the "Allow volume beyond 100% (0dB)" enabled...

Oh, now I remember :) @tsimonq2 and I both missed that option. I think this can be closed because it's quite reasonable to show 100% as the max; the detailed settings can be done by using `pavucontrol-qt`.

**Comment by tsimonq2** [comment]
> @tsimonq2 and I both missed that option

TIL that has settings O_o
