### ISSUE TITLE
Develop a command line Mime Apps tool

### ISSUE THREAD

**Issue by luis-pereira** [lxqt/lxqt#1528]
We can't rely on `xdg-open` `open_generic()` as it's faulty. See https://github.com/lxqt/lxqt/issues/1513

##### Expected Behavior
Open a File or URL with the user's preferred applications correctly.

##### Current Behavior
Faulty in some cases. See  https://github.com/lxqt/lxqt/issues/1513.

##### Possible Solution
A command line tool in the spirit of `gio`, `exo-open`, etc.
Already developed interface:
```
[lpereira@Faisca tools]$ ./qtxdg-mat --help
Usage: ./qtxdg-mat [options] command
QtXdg MimeApps Tool

Options:
  -h, --help     Displays this help.
  -v, --version  Displays version information.

Arguments:
  command        Command to execute.

Available commands:
  open          Opens files or URLs in the user's preferred applications

[lpereira@Faisca tools]$ ./qtxdg-mat open --help
Usage: ./qtxdg-mat [options] [Files | URLs...]
QtXdg MimeApps Tool

Options:
  -h, --help  Displays this help.

Arguments:
  open        Files URLs to open
```

**Comment by agaida** [comment]
Sounds good

**Comment by tsujan** [comment]
Good idea.

**Comment by selairi** [comment]
OK

El miércoles, 25 de julio de 2018, tsujan <notifications@github.com>
escribió:
> Good idea.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci5.googleusercontent.com/proxy/HpdI88tfoLhtXFD96bdgiK_EB4cHWyPUJPeSzaBkRqUBDXQfhx7ZxlswYa2FJbMG29X38C_mRxK6kuulVZkf0ZMbXZzCv04IsKQdXYufUj1n8PwTPE7ID2GMzGRR_uJVty5A3Q_GMv0UtwWwj5MYT_iRSHnn9A=s0-d-e1-ft#https://github.com/notifications/beacon/ABG_g8lwex90Ebqg6gnr-OIBJeflDB66ks5uKMWIgaJpZM4Vgnwn.gif>

**Comment by luis-pereira** [comment]
Done
