### ISSUE TITLE
Can't use themes from ~/.themes in gtk_appearance branch of lxqt-config

### ISSUE THREAD

**Issue by E5ten** [lxqt/lxqt#1529]
Themes manually installed to .themes are common and should be detected

##### Expected Behavior
The list of possible gtk themes includes those in ~/.themes

##### Current Behavior
Themes manually installed to ~/.themes are not detected

##### Steps to Reproduce (for bugs)
1. Put a theme folder in ~/.themes
2. Open lxqt-config-appearance
3. See that it isn't in the list of available themes

##### Context
I use an altered GTK theme in ~/.themes and don't want to have to put it in /usr/share/themes for it to be used

##### System Information
* Distribution & Version: Arch Linux
* Kernel: 4.17.9
* Qt Version: 5.11.1
* liblxqt Version: 0.13.0
* Package version: lxqt-config#gtk_appearance

**Comment by tsujan** [comment]
`~/.themes` is deprecated. Use `~/.local/share/themes`.

**Comment by E5ten** [comment]
Ok, good to know. In addition it doesn't detect gtk 3 themes in <theme directory>/<theme>/gtk-3.20 which lxappearance detects.

**Comment by tsujan** [comment]
> I still think it would be good to detect themes in ~/.themes given that there are people who are unaware or prefer it.

As an old-fashioned coder, I might agree with you but I *completely* agree with the LXQt team that we should stick to standards (as far as they are reasonable). Qt recognizes `~/.local/share` as a special place but not `~/.ANYTHING`.

**Comment by E5ten** [comment]
Qt sure, but I was talking about GTK themes which are commonly manually placed in ~/.themes.

**Comment by tsujan** [comment]
All kinds of themes (GTK themes, icon sets, etc.) are data and, according to [freedesktop specs](https://specifications.freedesktop.org/basedir-spec/basedir-spec-0.6.html), go into `$XDG_DATA_DIRS` or `$XDG_DATA_HOME`.
