### ISSUE TITLE
Move all IRC references over

### ISSUE THREAD

**Issue by tsimonq2** [lxqt/lxqt#1530]
We have migrated from #lxde on freenode to #lxqt and #lxqt-dev on OFTC. #lxqt is for user support and #lxqt-dev is for development talk and commit notifications.

I have changed the settings for all of the Git repositories to point to #lxqt-dev but if there's something else hardcoded somewhere, let's move it.

Pinging @all to move your IRC clients.

Thanks.

**Comment by agaida** [comment]
PS: freenode #lxqt is registered as backup channel or for people who don't know/like OFTC

**Comment by tsimonq2** [comment]
https://lxqt.org/release/2018/07/26/moving-to-oftc/

**Comment by jubalh** [comment]
Yay, 4 possible channels on two networks to hang around in ;)

Thanks for the ping.

**Comment by tsimonq2** [comment]
@lxqt/lxqt Closing this, please join us on IRC!
