### ISSUE TITLE
lxqt-sudo failing to handle command

### ISSUE THREAD

**Issue by luis-pereira** [lxqt/lxqt#1534]
##### Current Behavior
A picture is worth a thousand words

![screen-2018-08-07-16-43-58](https://user-images.githubusercontent.com/62877/43789321-91f1897a-9a67-11e8-9378-b7cadd9ccdd6.png)
![screen-2018-08-07-16-44-51](https://user-images.githubusercontent.com/62877/43789358-aca742c8-9a67-11e8-99fe-ca3c7a2d7644.png)

##### Possible Solution
At first glance seems introduced by commit https://github.com/lxqt/lxqt-sudo/commit/406a20279e24539e04cab1c96ff808b3e4e2d163 

##### Context
Founded while testing https://github.com/lxqt/lxqt-sudo/pull/49.
My previous lxqt-sudo version was prior to https://github.com/lxqt/lxqt-sudo/commit/406a20279e24539e04cab1c96ff808b3e4e2d163 

##### System Information

* Distribution & Version: Manjaro
* Kernel: Not relevant 
* Qt Version: 5.11
* liblxqt Version: git
* Package version:   https://github.com/lxqt/lxqt-sudo/pull/49

**Comment by luis-pereira** [comment]
@palinek Can you pls take a look ?

**Comment by palinek** [comment]
Will have a look tomorrow...now I'm too "tired"...but at first glance it looks like some escaping/quoting problem in octopi.

**Comment by palinek** [comment]
How is octopi configured to use `lxqt-sudo`? It seems as it's invoking the command like:
```
$ lxsu 'echo -e test'

bash: line 0: exec: echo -e test: not found
```
, but it should use:
```
$ lxsu echo -e test

test
```

**Comment by palinek** [comment]
I had a look into octopi implementation...

@luis-pereira 
Can you, please, check the octopi behavior with this patch:
```diff
diff --git a/src/wmhelper.cpp b/src/wmhelper.cpp
index 141ebfb..64a0840 100644
--- a/src/wmhelper.cpp
+++ b/src/wmhelper.cpp
@@ -255,6 +255,7 @@ QString WMHelper::getLXQTSUCommand(){
   QString result = ctn_LXQTSU;
 
   result += " -s ";
+  result += ctn_ROOT_SH;
 
   return result;
 }
```

**Comment by luis-pereira** [comment]
Will try ASAP.

**Comment by luis-pereira** [comment]
Will check octopi behavior later.

Running master
```
lxsu 'echo -e test'
lxqt-sudo: Stripping child environment except for: DISPLAY, LANG, LANGUAGE, LC_ADDRESS, LC_ALL, LC_COLLATE, LC_CTYPE, LC_IDENTIFICATION, LC_MEASUREMENT, LC_MESSAGES, LC_MONETARY, LC_NAME, LC_NUMERIC, LC_PAPER, LC_TELEPHONE, LC_TIME, PATH, QT_PLATFORM_PLUGIN, QT_QPA_PLATFORMTHEME, WAYLAND_DISPLAY, XAUTHORITY

bash: line 0: exec: echo -e test: not found
```

but running master with commit lxqt/lxqt-sudo@406a20279e24539e04cab1c96ff808b3e4e2d163 reverted  ``` git revert 406a20279e24539e04cab1c96ff808b3e4e2d163```
results in:

```
lxsu 'echo -e test'
lxqt-sudo: Stripping child environment except for: DISPLAY, LANG, LANGUAGE, LC_ADDRESS, LC_ALL, LC_COLLATE, LC_CTYPE, LC_IDENTIFICATION, LC_MEASUREMENT, LC_MESSAGES, LC_MONETARY, LC_NAME, LC_NUMERIC, LC_PAPER, LC_TELEPHONE, LC_TIME, PATH, QT_PLATFORM_PLUGIN, QT_QPA_PLATFORMTHEME, WAYLAND_DISPLAY, XAUTHORITY

test
```

That's a change of behavior not referenced in the commit message. It's a intended change ?

**Comment by luis-pereira** [comment]
patched octopi with lxqt-sudo works Ok
![screen-2018-08-08-22-40-40-octopi-patched png](https://user-images.githubusercontent.com/62877/43868185-48e4b2ea-9b64-11e8-9a06-42503e858950.jpg)


Not patched octopi with lxqt-sudo with  lxqt/lxqt-sudo@406a202 reverted also works Ok
![screen-2018-08-08-22-52-21-octopi-not-patched-lxqt-sudo-reverted png](https://user-images.githubusercontent.com/62877/43868264-bc388e42-9b64-11e8-9115-b9aa8b2c15ea.jpg)

**Comment by tsujan** [comment]
Sorry if this sounds obvious but we can't expect devs to patch their apps specifically for lxqt-sudo.

**Comment by palinek** [comment]
> That's a change of behavior not referenced in the commit message. It's a intended change ?

I didn't think of passing the script for interpretation for the `su` flavor of `lxqt-sudo`. As I see it, it was a undocumented feature of `lxqt-sudo` (a security flaw?). Even the man page states clearly, that `lxqt-sudo` is for:
```
SYNOPSIS
       lxqt-sudo option [command [arguments]]
       lxsu [option] [command [arguments]]
       lxsudo [option] [command [arguments]]

DESCRIPTION
       lxqt-sudo (and symlinks lxsu, lxsudo) is a graphical QT frontend for plain sudo(8) or su(1) (for requesting optional password in GUI fashion).
       When  invoked  it simply spawns child sudo or su process with requested command (and optional arguments). If sudo/su requests user's password, the GUI password dialog is shown and (after submit) the password is
       provided to backend.
```

So yes, we changed the (undocumented) `su` backend behavior and IMO it's now even more secure (if you want to inject script for interpretation, you need to do it explicitly and there is a better chance for the user to notice it). And the behavior (external interface) is the same no matter if the backend is `su` or `sudo`.


> Sorry if this sounds obvious but we can't expect devs to patch their apps specifically for lxqt-sudo.

Even if they use undocumented features ("...it works somehow, let's use it...")? ... but we made the patch for them.



Of course, this is only my point of view and you can disagree. Then we need to add the "next shell spawning" into the `su` logic.

**Comment by jubalh** [comment]
I strongly am with @palinek on this one.

They use an undocumented feature so there is no guarantee from us that this stays like it is. Now lxqt-sudo is more secure and more correct. octopi should adjust its usage, which @sudobaal tried to upstream to them.

I propose to close this issue as fixed.

**Comment by jubalh** [comment]
I think this can be closed now, since https://github.com/aarnt/octopi/pull/356 got merged.
