### ISSUE TITLE
[lxqt-config] Can't get rid of extra commas in user's Full Name

### ISSUE THREAD

**Issue by tsimonq2** [lxqt/lxqt#1536]
![screenshot_20180808_202148](https://user-images.githubusercontent.com/3689821/43872718-b3b88504-9b48-11e8-9a65-8d288893bd38.png)

When editing the full name and removing those extra commas, they don't go away after saving.

**Comment by agaida** [comment]
duplicate of #1423

We display right now the full combi field.
