### ISSUE TITLE
[lxqt-policykit] Username prefixed by unix-user by default

### ISSUE THREAD

**Issue by tsimonq2** [lxqt/lxqt#1539]
For an advanced user who knows what Unix is, this isn't a problem. But for others, the `unix-user:` prefix is a bit confusing.

Here's a screenshot a user gave me:

![image](https://user-images.githubusercontent.com/3689821/43872964-18879d0c-9b4a-11e8-8003-1cf60aa68248.png)

I would even argue that instead of displaying the short name, it should display the full name ("Simon Quigley" instead of "simon").

**Comment by palinek** [comment]
@tsimonq2 
I changed the title...as this has nothing to do with `lxqt-sudo`, but is a `lxqt-policykit` dialog.

**Comment by palinek** [comment]
Closing this as we `lxqt-policykit` does not generate the identity description.
1. The list of identities is generated and provided to the agent by the polkit deamon, see the API https://www.freedesktop.org/software/polkit/docs/latest/eggdbus-interface-org.freedesktop.PolicyKit1.AuthenticationAgent.html.
2. We use the `PolkiQt` library ... here is the generation of string representation of the identity https://github.com/KDE/polkit-qt-1/blob/master/core/polkitqt1-identity.cpp#L115.

So if you want the behavior as described in OP, you need to go upstream.
