### ISSUE TITLE
[lxqt-panel] provide hint about acceptable values for filterShowMaxWidth

### ISSUE THREAD

**Issue by wxl** [lxqt/lxqt#1544]
When setting the maximum width of the displayed entries, there are hard limits on acceptable values. You can see by looking at the minimum and maximum properties, this is [currently][1] 40-1000px:
```xml
       <widget class="QSpinBox" name="filterShowMaxWidthSB">
        <property name="suffix">
         <string> px</string>
        </property>
        <property name="minimum">
         <number>40</number>
        </property>
        <property name="maximum">
         <number>1000</number>
        </property>
       </widget>
``` 

##### Possible Solution
Change "max. item width" to "max. width (>40)." The word item really isn't necessary because the largest item is going to define the width for all the items. Also interesting is that you cannot set a value higher than 1000.

##### Steps to Reproduce
 1. Right click menu
 1. Click "Configure Application Menu"
 1. Under Search → Show matching entries → max. item width, double click text box containing value to highlight it
 1. Type some value less than 40
 1. Click close
 1. Repeat steps 1 and 2 and note the value has reverted

##### System Information
* Distribution & Version: Lubuntu 18.10 daily
* Kernel: 4.17.0-6-generic
* Qt Version: 5.9.5
* liblxqt Version: 0.13.0-0ubuntu1
* Package version: 0.13.0-0ubuntu3

<sup>1</sup> If you hit tab/enter or click some other element instead of clicking close, it willl revert back. To fair, if you watch very closely, you'll notice that before the dialog closes, it reverts back, too.

[1]: https://github.com/lxqt/lxqt-panel/blob/2331e19dfc214bfb6a5958cc38547cfc814c5534/plugin-mainmenu/lxqtmainmenuconfiguration.ui#L195-L205

**Comment by tsujan** [comment]
> Steps to Reproduce....

There's nothing wrong here. The value should revert to the minimum if set < min. The user can know about the minimum by paying attention to the state of the spin-box --  ">40" would be redundant. And "max. item width" is correct because it's the *item* width, not the widget width; the latter is determined by the active widget style.

**Comment by wxl** [comment]
@agaida told me to file this, so I guess you should argue with him.

**Comment by wxl** [comment]
To be clear, this is not a *bug* report, but a *suggestion* to provide the user a hint about what values will be acceptable.

**Comment by tsujan** [comment]
> a suggestion to provide the user a hint about what values will be acceptable.

Already replied.

BTW, closing an issue doesn't mean it was wrong to open it ;) Looking forward to more reports from you.

**Comment by agaida** [comment]
@tsujan @wxl is right, there should be a tool tip - so we can point user (who will file bugs about) to - it's only about closing these possible upcoming bugs fast or to prevent them.

**Comment by tsujan** [comment]
Spin-boxes speak for themselves ;) When you hit the max/min, the corresponding arrow becomes disabled (it depends on the widget style). It's better to avoid redundant info/texts, IMO. Moreover, even in the case of really important info, you know how tooltips may be ignored (-> pcmanfm-qt).

**Comment by wxl** [comment]
> Spin-boxes speak for themselves ;)

…unless, as I said in the report, you use the keyboard, which a
perfectly reasonable means of interacting with a computer, contrary to
modern belief.

**Comment by tsujan** [comment]
> unless, as I said in the report, you use the keyboard,

Then, as you've seen, Qt corrects it for you.

**Comment by wxl** [comment]
> Then, as you've seen, Qt corrects it for you.

However, if you click close, you are left with the expectation that it
accepted your input.

**Comment by tsujan** [comment]
... And a keyboard has arrow keys.

> However, if you click close, you are left with the expectation that it accepted your input.

Once it loses focus *or* `Enter` is pressed, its value will be corrected. I can't think of a better behavior but if you see it uncomfortable, you could open an issue at Qt's bug tracker (I wouldn't do so).

**Comment by agaida** [comment]
put a big red warning flag into - or just sanitize manual input would help to.

**Comment by tsujan** [comment]
There's nothing to warn about. Otherwise, we should also add texts, saying, "You could use mouse or arrow keys to change the value, etc." and our GUI will be a Qt doc.
