### ISSUE TITLE
Fatal error when using NVIDIA driver

### ISSUE THREAD

**Issue by FloFlo93** [lxqt/lxqt#1545]
I installed CUDA 9.2 (x86_64 for Fedora 27) using the official rpm package on the NVIDIA page. This package seems to also download the latest NVIDIA driver (to be used instead of nouveau). After rebooting, I was not able to login anymore (the screen stayed black after the login). The issue did not occur when using GNOME instead of LXQt. After I uninstalled CUDA and all dependencies (including the official NVIDIA driver), I was able to use LXQt again. 

In my opinion, this is a serious bug, as many people rely on the usage of CUDA and would also like to continue to use their desktop environment of choice. 

##### System Information

* Distribution & Version: Fedora 27
* Kernel: 4.17.14-102.fc27.x86_64
* Qt Version: 5.9.6
* LXQt version: 0.11.1

**Comment by tsujan** [comment]
LXQt doesn't have a compositor of its own; almost any compositor can be used with it. The bug you mentioned is either in the nVidia driver or in the compositor you use with LXQt.
