### ISSUE TITLE
Files Association dialog is poor

### ISSUE THREAD

**Issue by tsujan** [lxqt/lxqt#1546]
The Files Association dialog has no way of removing associations or ordering them.

I hadn't seen this issue only because I always changed associations manually.

**Comment by hollysheep** [comment]
That mean at the moment i can edit this submenu?

**Comment by tsujan** [comment]
> That mean at the moment i can edit this submenu?

Oh, yes! I've done it a lot. I don't remember if the order is kept (will look into it later) but, for adding/removing associations, you could edit `~/.config/mimeapps.list`. There can be 3 headers there: `[Added Associations]`, `[Default Applications]` and `[Removed Associations]`. You should know the format (by reading an explanation on the Internet), of course.

**Comment by Vladimir-csp** [comment]
Already covered by #1004

**Comment by tsujan** [comment]
> Already covered by #1004

Thanks!

Strange! A serious lack of features is known for a long time.
