### ISSUE TITLE
[lxqt-config] GTK configuration cut off when using default window size

### ISSUE THREAD

**Issue by tsimonq2** [lxqt/lxqt#1547]
This says it all:

![image](https://user-images.githubusercontent.com/3689821/44610195-c70ede80-a7c0-11e8-8287-b59517bb5013.png)

**Comment by tsujan** [comment]
Most probably, a simple mistake in the ui file, like what was fixed in lxqt-sudo's dialog: a fixed/max. width/height shouldn't be used.

**Comment by tsujan** [comment]
Will be fixed in https://github.com/lxqt/lxqt-config/pull/280 -- I forgot to mention the issue in the PR; please close this after the PR is merged.
