### ISSUE TITLE
[lxqt-config] GTK 3 configuration doesn't apply

### ISSUE THREAD

**Issue by tsimonq2** [lxqt/lxqt#1548]
Adapta is fugly, but [I can't seem to get off of it](https://youtu.be/Lx0f4_QjfTk).

**Comment by selairi** [comment]
I don't understand what is the problem:

GTK2 and GTK3 themes are applied to GTK2 and GTK3 applications. Example,
GIMP is a GTK3 app, if you select a GTK3, this theme will be applied to
GIMP. Maybe you will need to restart GIMP to apply the settings.

**Comment by Vladimir-csp** [comment]
Please show the contents of `$XDG_CONFIG_HOME/gtk-3.0/settings.ini`
Does it change when you select various GTK3 themes?

**Comment by agaida** [comment]
@selairi - there is a chance to understand if one download an daily image and run it in a virtual machine of choice - there are a few (kvm. vbox, vmware, xen) or on real iron. Sorry, please don't call me Captain Obvious - the thing is called distribution fun and maybe some side effects.

**Comment by tsujan** [comment]
OK, I got suspicious about something, installed the latest lxqt-config, and my suspicion was proved: there are 2 bugs which can be seen only when `~/.config/gtk-3.0` doesn't exist -- exactly as @tsimonq2 told.

Since this is very bad for lxqt-config, I'll try to fix it.

**Comment by tsujan** [comment]
On second thought, I have no time for this (didn't follow it from start) but give these hints:

(1) In `ConfigOtherToolKits::writeConfig` these lines should be added:
```c++
    QDir dir;
    dir.mkpath(path.section("/", 0, -2)); // create the parent dir if needed
```
The reason: `QFile::open` doesn't create the parent dir automagically.

(2) These lines under `StyleConfig::initControls()` are wrong:
```c++
    ui->gtk2ComboBox->setCurrentText(mConfigOtherToolKits->getGTKThemeFromRCFile("2.0"));
    ui->gtk3ComboBox->setCurrentText(mConfigOtherToolKits->getGTKThemeFromRCFile("3.0"));
```
The reason: there may be no "rc file".

**Comment by selairi** [comment]
(1) I have just upload a push request.
(2) If no "rc file" getGTKThemeFromRCFile returns QString(), an empty
QString, then setCurrentText selects the first item in the list.

**Comment by tsujan** [comment]
> (1) I have just upload a push request.

Good!

> (2) If no "rc file" ...  then setCurrentText selects the first item in the list.

Wrong! It should select the active GTK+ theme.

**Comment by selairi** [comment]
(2) I have just sent a push request about it.

**Comment by selairi** [comment]
(2) I have just upload some changes. It sets the default GTK theme if no
gtk rc file.

**Comment by tsujan** [comment]
> (2) I have just upload some changes. It sets the default GTK theme if no gtk rc file.

Thanks!

**Comment by tsujan** [comment]
Fixed by @selairi's PRs.
