### ISSUE TITLE
[lxqt-panel] Uneven spacing around configuration items

### ISSUE THREAD

**Issue by tsimonq2** [lxqt/lxqt#1550]
![image](https://user-images.githubusercontent.com/3689821/44621613-a8672100-a86e-11e8-912e-78c7b776ab19.png)

I've seen this with several themes.

**Comment by tsujan** [comment]
Yes, it can be seen as a GUI problem. I can't find another place with the same issue; could you?

**Comment by tsujan** [comment]
@tsimonq2  Thanks to your report, I found that `LXQT::HtmlDelegate` (belonging to liblxqt) has several size/positioning problems. I'll try to fix them.

**Comment by tsujan** [comment]
Please test https://github.com/lxqt/liblxqt/pull/170 and restart the panel.
