### ISSUE TITLE
[lxqt-panel] Feature Request: Clipboard manager

### ISSUE THREAD

**Issue by softwaresale** [lxqt/lxqt#1556]
##### Expected Behavior

Would a clipboard manager be a welcomed plugin for the lxqt panel? I was thinking
something simple similar to XFCE's clipman. It seems like a lot of desktops have a clipboard
manager, and I figured that LXQt might want one as well. I was planning on making it pretty
standard to start. Down the line, it would be interesting to add sharing capabilities so that a user can share clips between desktops.

This will be my first contribution, so I will probably need some help, but I am eager to help out if I can.
Let me know what you think. Thanks!

**Comment by palinek** [comment]
@Vladimir-csp agreed.
@softwaresale you can have a look on qlipper issues and begin to work on some. Contribution is appreciated.

**Comment by tsujan** [comment]
I also think that making Qlipper better - fixing its bugs and, probably, adding features to it -- is a good idea.

**Comment by agaida** [comment]
I fully agree

**Comment by softwaresale** [comment]
@palinek Alright. That's probably a better idea. I'll try to help out over at qlipper.
