### ISSUE TITLE
[Lxqt-policykit] - Authentication window opens unfocused

### ISSUE THREAD

**Issue by ahmed-h-ayyad** [lxqt/lxqt#1558]
it's not related to the software that need authentication and occur every time 
the problem is that I have to activate the window through clicking on it by mouse before writing password

![lxqt](https://user-images.githubusercontent.com/37955014/45637590-6f4f5480-ba9a-11e8-9219-ae1058818359.png)

the window should be focused when open as each other window

##### System Information
* Distribution & Version: Arch linux
* Kernel: 4.14.69-1-lts
* Qt Version: 5.11.1
* liblxqt Version: 0.13.0-1
* Package version: 0.13.0-1

**Comment by tsujan** [comment]
Most window manages -- KWin included -- has "focus stealing prevention". It does what it says. Simply disable it (for KWin: KDE's systemsettings5 → Window Behavior → Focus).

Please close this after you see the effect.

**Comment by ahmed-h-ayyad** [comment]
Thanks for your prompt reply
