### ISSUE TITLE
build_all_cmake_projects.sh fails when /bin/sh is not bash

### ISSUE THREAD

**Issue by igordsm** [lxqt/lxqt#1559]
`build_all_cmake_projects.sh` is run with /bin/sh but relies on the `source` command, which is a bash extension. The build script fails when /bin/sh points to dash, which is the default in my recent Lubuntu 18.04 install even though lxterminal actually uses bash.

##### Expected Behavior
`build_all_cmake_projects.sh` compiles all projects. 

##### Current Behavior

Returns the error: `./build_all_cmake_projects.sh: 20: ./build_all_cmake_projects.sh: source: not found`

##### Possible Solution
[This link](https://bugs.launchpad.net/ubuntu/+source/dash/+bug/65046) on Dash's issue tracker points out that `source` is a bash extension and that the cross-shell solution would be to use the `.` command. 

I can confirm this solution works in both bash and dash.

##### Steps to Reproduce (for bugs)

Run `build_all_cmake_projects.sh` with `/bin/sh` pointing to `dash`. Running the script with bash also works. 

##### System Information
* Distribution & Version: Lubuntu 18.04.1 
* Kernel: 4.15.0-34
* Package version: code from master

**Comment by agaida** [comment]
you are right, valid finding - only a hint: Never ever use build_all on debian/ubuntu-based systems. Please do such things the ubuntu way.

**Comment by igordsm** [comment]
What would be the Ubuntu way? I followed the i[nstructions from the wiki](https://github.com/lxqt/lxqt/wiki/Building-from-source) and I did not find any warning tellinge not to use ./build_all.sh... 

I encountered this issue when my students were not able to compile lxqt on Ubuntu by following the instructions I linked above. I can send a PR with the (very simple) fixes if needed.

**Comment by agaida** [comment]
Dead easy again and obvious too - never circumvent the package management. Just build current packages, compile them local or even better in a clean environment and install via apt.

**Comment by igordsm** [comment]
> Just build current packages, compile them local or even better in a clean environment and install via apt.

Then the question is how to install locally compiled packages via apt. I did not find how to build a .deb package from the lxqt sources in the wiki. I have found info on how to use CPack to generate deb packages, but lxqt does not use it. I can add this to the wiki after testing, as it really improves the installation experience in Ubuntu/Debian.

Thank you for the responses.

**Comment by tsujan** [comment]
@igordsm Each Linux distro has its method for making installable packages from sources, the most well-known methods being about Arch's `pkg.tar.xz` (a piece of cake), deb (it's relatively easy to make a deb folder and build a deb package with it -- moreover, deb folders can be downloaded from https://www.debian.org/distrib/packages and customized) and rpm (perhaps not as easy as deb but manageable). Those methods cannot be explained in the Wiki; distros have their own wiki pages for them.

Generally, `build_all` isn't a good idea in any distro because, at least, the package manager won't be "aware" of the installed programs if `build_all` is used.

**Comment by agaida** [comment]
As @tsujan said, packaging is a distribution thing - for .deb i would recommend the NM guidelines

**Comment by selairi** [comment]
I have just sent a simple push request that solves the problem. I have seen
that our shell scripts follows the bash syntax and other shells (dash or
ash) can not read them properly.

**Comment by agaida** [comment]
That doesn't change the fact that it is a very bad idea in the most cases to use the shell scripts as they are now. Tbh, bash is the slightest problem.

**Comment by igordsm** [comment]
Closed by #1561
