### ISSUE TITLE
Default application setting does not record selected app

### ISSUE THREAD

**Issue by stefonarch** [lxqt/lxqt#1560]
Selecting default apps from /usr/bin will display eg /usr/bin/falkon but not remember it, sometimes even not alert about "some settings will have effect on next login". 
But typing "falkon" in the field everything works, alert and setting is remembered. 
Similar can be  seen for terminal app.
The dropdown list does not update either, time ago it showed any previous setting.

##### Expected Behavior
It should remember it.

##### Current Behavior

Typing directly the executable name is   working only for changing default app.

##### Steps to Reproduce (for bugs)

1. Go to Systemsettings > default applications, click select
2. Choose a browser|terminal in /usr/bin/
3. Close
4. Reopen same setting, it will be as before

 

##### System Information

up to date arch and lxqt git

**Comment by wxl** [comment]
Though not on master, I can confirm this behavior on the 0.13 version in Ubuntu. [Bug here](https://bugs.launchpad.net/lxqt/+bug/1795539) for the curious. This is linked, so when we finally fix this bug, that should get auto updated.

**Comment by agaida** [comment]
confirmed on latest git - it really sucks

the description by @stefonarch is incomplete - it works fine if one enter the terminal or browser field and switch to some other field afterwards - so we should really check our detection of modifications here.

**Comment by palinek** [comment]
Please, test with lxqt/lxqt-session@176

**Comment by wxl** [comment]
Just FYI I can confirm this is resolved on 0.14.1.
