### ISSUE TITLE
Per monitor Desktop Settings

### ISSUE THREAD

**Issue by softwaresale** [lxqt/lxqt#1562]
It would be nice to have per-monitor desktop settings. I use two desktop monitors with my computer. Currently, both monitors act as one unit. What I would like to have different settings on each one. For example, they might have different wallpapers. I believe that XFCE4 does this, although I may be mistaken.

**Comment by agaida** [comment]
@tsujan @palinek - i guess we should close this (again). To do this we must re-introduce some X dependencies i guess.

**Comment by tsujan** [comment]
> To do this we must re-introduce some X dependencies i guess.

I think so.

**Comment by tsujan** [comment]
BTW, libfm-qt already has X11 dependencies and doesn't work on wayland. At some point, that should be fixed too. It can't be difficult.

**Comment by agaida** [comment]
erm - we worked on reducing X dependencies in the past iirc :D - joke aside, we should not shoot us into one or both feets with such actions - if we can handle wayland different later and it is not to much overhead - nothing against it.

**Comment by tsujan** [comment]
I didn't mean to reduce X11 dependencies but to skip the current X11 codes when under wayland, so that the library/app works under wayland too. I've done so with FeatherPad, FeatherNotes and Kvantum, all of which contain X11 codes.

**Comment by agaida** [comment]
cool

**Comment by tsujan** [comment]
For reference, related to https://github.com/lxqt/pcmanfm-qt/issues/865 somehow. It depends how monitors are used: an extended screen or a unified view. With the first, there can be only one big desktop (whose problems will be fixed later).

I should experiment with `QSreen` and replace `QDesktopWidget` with it completely to see what can be done without an X11 dependency. Unfortunately, my external monitor can be connected only to a laptop with a broken graphic cable that, sooner or later, will show nothing; for now, it shows a reddish screen that can be used for testing.

**Comment by jdiazaz** [comment]
So far the only way I've found, to at least be able to center my wallpaper, is to have a 3-monitor configuration.  I'd love to be able to have different wallpapers on each monitor.  Does LXQT 0.14 support it?  I have the 0.13 release that came with Lubuntu 18.10

**Comment by tsujan** [comment]
Real problems in Desktop update with multiple screens are fixed in 0.14.

I won't complicate the code just for a per-screen setting. Of course, everyone is free to make a PR.

**Comment by tsujan** [comment]
→ https://github.com/lxqt/pcmanfm-qt/commit/dfdf1fa0db00330d927e664c8e6829c0835adfa7
