### ISSUE TITLE
C++14 support in LXQt

### ISSUE THREAD

**Issue by agaida** [lxqt/lxqt#1568]
##### Expected Behavior
We should use C++14 as standard

##### Current Behavior
We use max C++11 as standard

##### Possible Solution
Change it?

##### Context
Was about to write the initial CMakeLists.txt for sddm-config-editor. Lambdas and auto are used - so qmake runs fine, cmake complain about not set -std=c++14. To be honest - we are in late 2018 now, c++14 is supported since gcc6 iirc - rigth now in all stable distributions 7.x should be default, if not 8.x.

Btw - nothing against backward compat, but we should not take care about to old  things. If one like to run a current LXQt an anncient Ubuntu 12.04, 14.04 or and ancient RH, debian old-old-stable - not our problem. Beside of that these environments will mostly lack the minimum Qt version, so we should be less conservative in that point.

@luis-pereira @palinek @PCMan @tsimonq2 @tsujan @yan12125 - what do you think?

**Comment by tsujan** [comment]
> ... but we should not take care about to old things

I completely agree.

**Comment by palinek** [comment]
Full ack.

**Comment by PCMan** [comment]
GCC seems to have full c++ 14 support since 5.0.
Quote: 

https://www.gnu.org/software/gcc/projects/cxx-status.html#cxx14
> C++14 Support in GCC
GCC has full support for the previous revision of the C++ standard, which was published in 2014.
This mode is the default in GCC 6.1 and above; it can be explicitly selected with the -std=c++14 command-line flag, or -std=gnu++14 to enable GNU extensions as well.

The current Debian old stable released in 2015 is shipped with gcc 4.9.
https://packages.debian.org/jessie/gcc
However the Qt 5 it provides is 5.3, which is not supported by LXQt.

So we at least require the current Debian stable (stretch) which has gcc 6.3.
Then it's safe to assume full c++ 14 support.

I'm +1 on fully switching to C++ 14 by default. \o/

**Comment by agaida** [comment]
@PCMan - you noted an important fact - the software stack around. (cmake, Qt) - while we are at it we should change our minimum for cmake too.

https://tracker.debian.org/pkg/cmake - oldstable is on 3.0.2, 3.6.2 is backported - we can assume that it is save to bump to 3.6.2

**Comment by agaida** [comment]
only the relevant part of a build log with https://github.com/lxqt/lxqt-build-tools/pull/35 applied:

```
dh build --buildsystem cmake
   dh_update_autotools_config -O--buildsystem=cmake
   dh_autoreconf -O--buildsystem=cmake
   debian/rules override_dh_auto_configure
make[1]: Entering directory '/home/agaida/work/code/pkg-main/lxqt-about/snapshot'
dh_auto_configure -- \
        -DUPDATE_TRANSLATIONS=OFF \
        -DCMAKE_BUILD_TYPE=RelWithDebInfo
        cd obj-x86_64-linux-gnu && cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=None -DCMAKE_INSTALL_SYSCONFDIR=/etc -DCMAKE_INSTALL_LOCALSTATEDIR=/var -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON -DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON -DCMAKE_INSTALL_RUNSTATEDIR=/run "-GUnix Makefiles" -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_INSTALL_LIBDIR=lib/x86_64-linux-gnu -DUPDATE_TRANSLATIONS=OFF -DCMAKE_BUILD_TYPE=RelWithDebInfo ..
-- The C compiler identification is GNU 8.2.0
-- The CXX compiler identification is GNU 8.2.0
-- Check for working C compiler: /usr/lib/ccache/cc
-- Check for working C compiler: /usr/lib/ccache/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/lib/ccache/c++
-- Check for working CXX compiler: /usr/lib/ccache/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test COMPILER_SUPPORTS_CXX14
-- Performing Test COMPILER_SUPPORTS_CXX14 - Success
-- Configuring done
-- Generating done
....
Successfully signed dsc, buildinfo, changes files
```
