### ISSUE TITLE
Since no help me on the forums for notifications

### ISSUE THREAD

**Issue by lhorace** [lxqt/lxqt#1572]
Before I abandon LXQT, can you guys store notifications?

**Comment by agaida** [comment]
No.

**Comment by agaida** [comment]
ok - let us discuss the word *rude* a bit:
* The issue title is sensless and says nothing about your problem
* You deleted the issue form instead giving a little bit background - i call this rude
* The answer is right  - no, we don't store notifications.

If you think we should - file a complete feature request why you want/need this - maybe a developer think it's a good idea. We would likely accept working patches too.

**Comment by tsujan** [comment]
Agreeing with @agaida, I add:

You asked a question on the forum and the developer(s) who had worked on notifications couldn't answer it as fast as you expected. You asked the same question here, adding that you wanted to abandon LXQt, and it was answered.

Actually, having a method of saving notifications is a good idea. LXQt doesn't have it and might not have it in the near future but opening a feature request could have been much more productive.

**Comment by tsujan** [comment]
I opened https://github.com/lxqt/lxqt/issues/1573.

**Comment by lhorace** [comment]
I apologize about the title, I will take responsible for that. I usually do better than that but I was just upset at the time. Delete what issue form? You mean the pre-text? I am sorry if that was rude. I waited 5 days
