### ISSUE TITLE
WIP: Cleanup our CMakeLists a bit

### ISSUE THREAD

**Issue by agaida** [lxqt/lxqt#1574]
With our latest changes in lxqt-build-tools there are many not needed things in our project CMakeLists.txt that are already set in the build tools:
* cmake minimum required -  damn, has to be in the main project file (CMP0000)
   ``` 
  cmake_minimum_required(VERSION 3.1.0 FATAL_ERROR)
  # CMP0000: Call the cmake_minimum_required() command at the beginning of the top-level
  # CMakeLists.txt file even before calling the project() command.
  # The cmake_minimum_required(VERSION) command implicitly invokes the cmake_policy(VERSION)
  # command to specify that the current project code is written for the given range of CMake
  # versions.
   ```

* default release
* superfluous definitions

##### Possible Solution
* Clean it up

##### Need Cleanup
* [x] compton-conf   lxqt/compton-conf/pull/105
* [x] libfm-qt   lxqt/libfm-qt/pull/312
* [x] liblxqt   lxqt/liblxqt/pull/189
* [x] libsysstat   lxqt/libsysstat/pull/30
* [x] lximage-qt  lxqt/lximage-qt/pull/204
* [x] lxqt-about  lxqt/lxqt-about/pull/86
* [x] lxqt-admin  lxqt/lxqt-admin/pull/104
* [x] lxqt-archiver
* [x] lxqt-config  lxqt/lxqt-config/pull/337
* [x] lxqt-globalkeys  lxqt/lxqt-globalkeys/pull/96
* [x] lxqt-notificationd  lxqt/lxqt-notificationd/pull/113
* [x] lxqt-openssh-askpass lxqt/lxqt-openssh-askpass/pull/43
* [x] lxqt-policykit lxqt/lxqt-policykit/pull/57
* [x] lxqt-powermanagement  lxqt/lxqt-powermanagement/pull/109
* [x] lxqt-qtplugin  lxqt/lxqt-qtplugin/pull/42
* [x] lxqt-runner   lxqt/lxqt-runner/pull/103
* [x] lxqt-session  lxqt/lxqt-session/pull/189
* [x] lxqt-sudo  lxqt/lxqt-sudo/pull/68
* [x] lxqt-themes  lxqt/lxqt-themes/pull/12
* [x] obconf-qt    /lxqt/obconf-qt/pull/79
* [x] pavucontrol-qt   lxqt/pavucontrol-qt/pull/103
* [x] pcmanfm-qt   lxqt/pcmanfm-qt/pull/825
* [x] qps   lxqt/qps/pull/96
* [x] qterminal  lxqt/qterminal/pull/513
* [x] qtermwidget  lxqt/qtermwidget/pull/230

**Comment by agaida** [comment]
https://github.com/lxqt/lxqt-panel/pull/747

so we only need 3.1.0 right now as minimum

**Comment by shirishag75** [comment]
The version seems to be pretty obsolete one, as even stable mentions cmake 3.7.2 so guess you would make it yourself. 

https://tracker.debian.org/pkg/cmake

**Comment by agaida** [comment]
and you **_really_** know what you are talking about?

**Comment by shirishag75** [comment]
aha... right. My concern is and was if you run into problems with cmake how and where you will get support ?  As cmake upstream just seems to support the unreleased (in relation to Debian) cmake 3.13, 3.12 and cmake 3.11 

I was thinking where you would get it and then saw https://github.com/Kitware/CMake/releases?after=v3.1.3 . I guess the idea is to get the release out of the door and then at some point work on a newer version of lxqt-build-tools with a newer/modern version of cmake. I tried to figure out if there is/was some documentation which gives some sort of roadmap but couldn't find one. 

Sorry for the noise. I will just report any bugs that get triggered when you make the changes.

**Comment by agaida** [comment]
The idea is: it doesn't matter which cmake version will be used - we only set the behaviour and policies - and yes, we re-evaluate the needed things.

**Comment by agaida** [comment]
#### later
* libqtxdg (Standards crap included) (don't touch right now)
* lxqt-connman-applet  lxqt/lxqt-connman-applet/pull/21 * #still needed c++14, check compiler includes
* lxqt-panel - later
* screengrab
* sddm-config-editor

**Comment by agaida** [comment]
screengrab done, sddm-config-editor can be ignored for now.
