### ISSUE TITLE
lxqt-config: Missing Qt styles in the list

### ISSUE THREAD

**Issue by j8r** [lxqt/lxqt#1577]
In `/usr/share/color-schemes`, there are available Qt styles.
For example on Manjaro and Lubuntu, the directory contains:
- Breeze.colors
- BreezeLight.colors
- KritaDark.colors
- BreezeDark.colors
- KritaBlender.colors
- KritaDarker.colors
- BreezeHighContrast.colors
- KritaBright.colors
- KritaNeutral.colors

But none are displayed in the `Widget Style` section of `Appearance`, in `lxqt-config`.
For now, I need to have this symlink to use the`Breeze Dark` style:
`ln -s /usr/share/color-schemes/BreezeDark.colors ~/.config/kdeglobals`

**Comment by tsujan** [comment]
Those aren't Qt styles but different "color schemes" for one and the same Qt widget style that's called "Breeze". See them as a part of Breeze's settings.

**Comment by j8r** [comment]
@tsujan Thanks for the explanation, but there no easy way to change the color scheme - not possible on `breeze-settings5` and `systemsettings5` (do I miss something)?

**Comment by tsujan** [comment]
>  (do I miss something)?

I don't know. Here, `systemsettings5 → Colors` always works for changing KDE color schemes under LXQt (please note that Breeze is a KDE widget style). If you can't do it from  `systemsettings5 → Colors`, some (KDE?) packages may be missing from your system.
