### ISSUE TITLE
how do I change the background colors. 

### ISSUE THREAD

**Issue by shirishag75** [lxqt/lxqt#1578]
![lxqt-background-color-black](https://user-images.githubusercontent.com/727626/47063428-88156c00-d1f8-11e8-9318-46c90a1c44c9.jpeg)

I wanted a white background with black letters instead of the other way around as the current scheme looks ugly, at least to me. 

I tried to change it but failed. I tried putting different values in background colors but the colors remain the same. 

Can anybody help ?

**Comment by tsujan** [comment]
> I wanted a white background with black letters

Panel's background?

> I tried to change it but failed.

You could do it in `Appearance → LXQt Theme`. You could also make other themes, with or without translucency; they are CSS (QSS).

**Comment by shirishag75** [comment]
Worked for me, thank you. The default theme should not be dark but that I guess would be a personal opinion.
