### ISSUE TITLE
Add screengrab

### ISSUE THREAD

**Issue by agaida** [lxqt/lxqt#1581]
##### Expected Behavior
Should be checked out and build

##### Current Behavior
it don't

**Comment by shirishag75** [comment]
screengrab is something like mate-screenshot. I did see some similar tool in lxqt too or is this supposed to be different ? Mate-screenshot is interactive and so was the utility in lxqt.

**Comment by shirishag75** [comment]
My bad, the application is/was `lximage-qt --screenshot`

**Comment by tsujan** [comment]
@shirishag75 
lximage-qt is an image viewer but it can take screenshots too. Screen Grab is LXQt's screenshot utility. You could use either to take screenshots.

**Comment by agaida** [comment]
@shirishag75 - and this bug is about something completely different - our (in)famous thing to checkout and build all the things.
