### ISSUE TITLE
Make our WM list (lxqt-session) more complete

### ISSUE THREAD

**Issue by agaida** [lxqt/lxqt#1584]
##### Expected Behavior
We should have much more WMs in our list, as in: we should be able to detect more of them

##### Current Behavior
We haven't

##### Possible Solution
Add them

##### Context
lxqt/lxqt/issues/1583

**Comment by agaida** [comment]
% LANG=C aptitude search '~Pwindow-manager' | grep -v i386
*  aewm - minimalist window manager for X11
*  aewm++ - minimal window manager written in C++
*  afterstep - window manager with the NEXTSTEP look and feel
*  amiwm - Amiga look alike window manager
*  awesome - highly configurable X window manager
*  blackbox - Window manager for X
*  bspwm - Binary space partitioning window manager
*  cinnamon - Innovative and comfortable desktop
*  clfswm - A(nother) Common Lisp FullScreen Window Manager
*  compiz - OpenGL window and compositing manager
*  ctwm - Claude's Tab window manager
*  cwm - lightweight and efficient window manager for X11
*  dwm - dynamic window manager
*  **e16**/e17 
*  enlightenment - X11 window manager based on EFL
*  evilwm - minimalist window manager for X11
*  fluxbox - Highly configurable and low resource X11 Window manager
*  flwm - Fast Light Window Manager
*  fvwm - F(?) Virtual Window Manager
*  fvwm-crystal - Pretty Desktop Environment based on FVWM
*  fvwm1 - Old version of the F(?) Virtual Window Manager
*  **fvwm2**   - in list
*  herbstluftwm - manual tiling window manager for X11
*  i3-wm - improved dynamic tiling window manager
*  icewm - wonderful Win95-OS/2-Motif-like window manager
*  icewm-experimental - wonderful Win95-OS/2-Motif-like window manager
*  icewm-lite - transitional package for icewm
*  jwm - very small lightweight pure X11 window manager with tray and menus
*  **kwin-**x11 - KDE window manager, X11 version
   kwin-wayland - wayland version
*  lwm - lightweight window manager
*  marco - lightweight GTK+ window manager for MATE
*  matchbox-window-manager - window manager for resource-limited systems
*  **metacity** - lightweight GTK+ window manager
*  miwm - minimalist window manager with virtual workspaces
*  muffin - lightweight window and compositing manager
*  mutter - lightweight GTK+ window manager
*  mwm - Motif Window Manager
*  notion - tiling tabbed window manager designed for keyboard users
*  olvwm - OpenLook virtual window manager
*  olwm - Open Look Window Manager
*  **openbox** - standards-compliant, fast, light-weight and extensible window manager
*  oroborus - A lightweight themeable windowmanager for X
*  pekwm - very light window manager
*  qtile - Small, simple, extensible X11 window manager written in Python
*  ratpoison - keyboard-only window manager
*  sapphire - A minimal but configurable X11R6 window manager
*  **sawfish** - window manager for X11
*  spectrwm - dynamic tiling window manager
*  stumpwm - tiling, keyboard driven Common Lisp window manager
*  subtle - grid-based manual tiling window manager
*  tinywm - tiny window manager
*  tritium - tabbed/tiling window manager
*  twm - Tab window manager
*  ukwm - lightweight GTK+ window manager
*  vtwm - Virtual Tab Window Manager
*  w9wm - enhanced window manager based on 9wm
*  windowlab - small and simple Amiga-like window manager
*  wm2 - small, unconfigurable window manager
*  wmaker - NeXTSTEP-like window manager for X
*  wmii - lightweight tabbed and tiled X11 window manager, version 3
*  **xfwm4** - window manager of the Xfce project
*  xmonad - Lightweight X11 window manager written in Haskell

@palinek @tsujan - please don't shoot at me or throw explosives in my direction, i just couldn't resist :sunglasses:  - thats the list of X11 window managers in debian - it might be a good start for windowmanagers.conf

**Comment by tsujan** [comment]
Most of them should work but enlightenment and e16/e17 can be removed -- Enlightenment only works with Enlightenment (DE and WM have the same name) and e16/e17 is old Enlightenment.
