### ISSUE TITLE
Qt Quick Controls Desktop Style not loaded correctly

### ISSUE THREAD

**Issue by c-cesar** [lxqt/lxqt#1585]
Related upstream bug: https://bugs.kde.org/show_bug.cgi?id=399883

LXQt configure widget styles, but seems to not load styles correctly for Qt Quick Controls applications, like Plasma Discover.

##### Current Behavior
Text area don't have border and focus indication on LXQt, but have on Plasma. Upstream developer reports that application is styled with qqc2 desktop style: https://phabricator.kde.org/source/qqc2-desktop-style/

##### Steps to Reproduce (for bugs)
1. Open Plasma Discover
2. Open a installed application
3. Open the new review form

##### System Information
* Distribution & Version: Manjaro Linux
* Kernel: 4.9.133
* Qt Version: 5.11.2
* liblxqt Version: 0.13.0
* Package version: 0.13.0

**Comment by agaida** [comment]
Why should this be a LXQt problem?

**Comment by c-cesar** [comment]
Because configuring the widget styles is done in session management.

LXQt session sets QWidgets style (QT_QPA_PLATFORMTHEME environment variable) , but not Qt Quick Controls style (QT_QUICK_CONTROLS_STYLE environment variable).

qqc2-desktop-style provides a way to make Qt Quick controls applications to use QWidget style, but there are other styles (Qt ships Universal and Material). None are set on LXQt session and QQC2 applications are not styled correctly.

**Comment by tsujan** [comment]
@c-cesar Please take a look at https://www.reddit.com/r/kde/comments/9p8uwm/open_a_friendly_and_constructive_discussion_a and https://github.com/lxqt/lxqt/issues/1433

**Comment by tsujan** [comment]
Warning! This has an emotional tone:

Now we should apologize for what KDE devs do.

**Comment by agaida** [comment]
Hmmm - i don't know if i understand or translated it right - but a DE that has nothing to do with Quick Controls should set things for something that is not used in the DE - strange, to put it mild.

**Comment by c-cesar** [comment]
I will not debate the wontfix status. This topic was debated in the forums @tsujan pointed.
My last comment had the only purpose to clarify that nobody is requesting apologies.

**Comment by tsujan** [comment]
> Only to clarify, Qt Quick Controls styles are from Qt, not KDE. Qt ships...

qqc2-desktop-style is KDE's impossible concept. I've got really tired of explaining that; I'm trying my best at that reddit page but I can't speak about so many QStyle parameters one by one.

**Comment by palinek** [comment]
> LXQt session sets QWidgets style (QT_QPA_PLATFORMTHEME environment variable) , but not Qt Quick Controls style (QT_QUICK_CONTROLS_STYLE environment variable)

You are free to configure setting of any env. var in lxqt-config-session
