### ISSUE TITLE
should double-clicking on desktop shortcuts have this dialog box ?

### ISSUE THREAD

**Issue by shirishag75** [lxqt/lxqt#1586]
I made a couple of desktop shortcuts for my mum. When she double-clicked on them, she got the following dialog box and didn't know what to do next. 

![double-clicking-on-desktop-icons](https://user-images.githubusercontent.com/727626/47213003-5bf41980-d3b7-11e8-8dfa-d7067156e77c.png)

```
Package: lxqt-session
Version: 0.13.1~181-gab84e77-3
Severity: normal



-- System Information:
Debian Release: buster/sid
  APT prefers testing
  APT policy: (990, 'testing'), (500, 'unstable-debug'), (500, 'testing-debug'), (500, 'unstable'), (1, 'experimental-debug'), (1, 'experimental')
Architecture: amd64 (x86_64)

Kernel: Linux 4.18.0-2-amd64 (SMP w/4 CPU cores)
Locale: LANG=en_IN, LC_CTYPE=en_IN (charmap=UTF-8), LANGUAGE=en_IN:en (charmap=UTF-8)
Shell: /bin/sh linked to /bin/dash
Init: systemd (via /run/systemd/system)
LSM: AppArmor: enabled

Versions of packages lxqt-session depends on:
ii  libc6                     2.27-6
ii  libkf5windowsystem5       5.49.0-1
ii  liblxqt0                  0.13.0-1
ii  libqt5core5a              5.11.1+dfsg-9
ii  libqt5dbus5               5.11.1+dfsg-9
ii  libqt5gui5                5.11.1+dfsg-9
ii  libqt5widgets5            5.11.1+dfsg-9
ii  libqt5x11extras5          5.11.1-2
ii  libqt5xdg3                3.2.1~11-g374f418-1
ii  libstdc++6                8.2.0-7
ii  libudev1                  239-10
ii  libx11-6                  2:1.6.7-1
ii  lxqt-qtplugin             0.13.0-2+b1
ii  lxqt-themes [lxqt-theme]  0.13.0-1
ii  x11-xkb-utils             7.7+4

Versions of packages lxqt-session recommends:
ii  lxqt-config           0.13.1~502-gfd3b8c7-4
ii  lxqt-notificationd    0.13.1~90-g41123bd-1
ii  lxqt-policykit        0.13.1~50-g5c1a745-1
ii  lxqt-powermanagement  0.13.1~139-g3b1b74d-1
ii  lxqt-session-l10n     0.13.1~181-gab84e77-3
ii  lxqt-sudo             0.13.1~78-ga571dda-1
ii  pcmanfm-qt            0.13.0-2
ii  qlipper               1:5.1.2~13-g0e90641-1
ii  qps                   1.10.19~84-g38c3fe1-1
ii  xscreensaver          5.40-1

lxqt-session suggests no packages.

-- no debconf information

```

**Comment by tsujan** [comment]
That's called a prompt message box. Supposing that you have the latest git versions of libfm-qt and pcmanfm-qt:

(1) You could check `Preferences → Behavior → Launch executable files without prompt`. Not recommended for obvious reasons but a possibility. Or

(2) You could right click the desktop file or any executable and check "Trust this executable" on the context menu.

**Comment by shirishag75** [comment]
I can't use the latest experimental-snapshots because of the virtual ABI thing. Doing update in either way is going to leave things in a broken state.

**Comment by tsujan** [comment]
You could use the first method until the next release. As far as I remember, it should exist in older versions too. I just hope that desktop files are treated as executables in older versions.

**Comment by agaida** [comment]
@shirishag75 - you can, but a bit patience is needed (if not patient, recompile the packages with the new Qt just trickled in)

**Comment by shirishag75** [comment]
I am seeing that - 

```
$ sudo apt-get upgrade
[sudo] password for shirish: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
The following packages have been kept back:
  libqt5xdg-dev libqt5xdg3 libqt5xdgiconloader-dev libqt5xdgiconloader3
0 upgraded, 0 newly installed, 0 to remove and 4 not upgraded.

```

**Comment by shirishag75** [comment]
Dunno if I should close it or not, for now can use the trust this executable shortcut, which IMO is not the solution as most people will not discover it .

**Comment by agaida** [comment]
it is the solution

**Comment by tsujan** [comment]
> which IMO is not the solution as most people will not discover it

It's very accessible and if someone can't find it after a while, they should blame themselves, not the GUI.

> it is the solution

Without doubt.
