### ISSUE TITLE
Icons are missing/not showing even after changing them.

### ISSUE THREAD

**Issue by lhorace** [lxqt/lxqt#1587]
##### Expected Behavior
When changing Icon themes in `lxqt-config-appearance`, changes are not applied and/or reflected on screen immediately or after reboot.

##### Current Behavior
Nothing happens, icons are still missing.

##### Steps to Reproduce (for bugs)

1. Launch `lxqt-config-appearance` and select Icon Themes
2. Toggle between icon themes

##### Context

Additional info, I'm running git versions of https://aur.archlinux.org/packages/pcmanfm-qt-git and https://aur.archlinux.org/packages/libfm-qt-git/ which I suspect might be the source of the problem.

##### System Information

* Distribution & Version: `ArchLinux`
* Kernel: `x86_64 Linux 4.18.14-zen1-1-zen`
* Qt Version: `Qt 5.11.2 (x86_64-little_endian-lp64 shared (dynamic) release build; by GCC 8.2.1 20180831) on "xcb" `
* liblxqt Version: `local/liblxqt 0.13.0-1`
* Package version:

**Comment by tsujan** [comment]
Most probably, you haven't installed an LXQt component. Check them here: https://github.com/lxqt/lxqt/wiki/Building-from-source#generalbuild-order

**Comment by lhorace** [comment]
You want me to build the entire stack to simply test pcmanfm-qt-git? Or is there a *-git lxqt component that's missing that pcmanfm-qt-git might require to get icons working again?

**Comment by tsujan** [comment]
If you do it, do it in the order shown at https://github.com/lxqt/lxqt/wiki/Building-from-source#generalbuild-order

**Comment by agaida** [comment]
@lhorace - it isn't that time consuming, but - ok, one maybe should use ccache and configure makepkg right (aka not using one core to build) - and maybe script the whole thing respecting the recommended build order.

**Comment by lhorace** [comment]
Yeah, it isn't, about 80% complete.
