### ISSUE TITLE
Finally drop all Qt 4 support

### ISSUE THREAD

**Issue by agaida** [lxqt/lxqt#1588]
Qt 4 EOLed end of 2015 - we are now end of 2018. We do us and our users a dis-service if we support his dead horse any longer.

http://blog.qt.io/blog/2014/11/27/qt-4-8-x-support-to-be-extended-for-another-year/

##### Possible Solution
Remove all Qt 4 support.

**Comment by tsujan** [comment]
How is that possible when our codes require Qt >= 5.7 (or more)?

**Comment by agaida** [comment]
We have parts that still build with Qt4 - the build tools support Qt4, some cmake scripts support still Qt4, even if Qt5 is default and so on

**Comment by tsujan** [comment]
Oh, I knew nothing about that. Anyhow, LXQt isn't usable with Qt < 5.7.

**Comment by agaida** [comment]
https://github.com/lxqt/compton-conf/blob/master/CMakeLists.txt
same for obconf-qt and maybe other places
