### ISSUE TITLE
pcmanfm-qt Open as Root Error

### ISSUE THREAD

**Issue by eirenicon** [lxqt/lxqt#1593]
PCmanfm-qt: open as root function does not open a new 'root' filemanager window. It asks for the root password but does not open a file manager window. 

The LXQt system default command attempting to execute is: lxqt-sudo %s

##### Expected Behavior
Open Root pcmanfm-qt filemanager window.

##### Current Behavior
Nothing happens

##### Steps to Reproduce (for bugs)

1. access Open as Root from fm tool bar.
2. 
3. 
4. 

##### System Information
System:
  Host: LXQt Kernel: 4.18.16-1-MANJARO x86_64 bits: 64 
  Desktop: LXQt 0.13.0 Distro: Manjaro Linux 
Machine:
  Type: Virtualbox System: innotek product: VirtualBox v: 1.2 
  serial: <root required> 
  Mobo: Oracle model: VirtualBox v: 1.2 serial: <root required> 
  BIOS: innotek v: VirtualBox date: 12/01/2006 
Battery:
  ID-1: BAT0 charge: 50.0 Wh condition: 50.0/50.0 Wh (100%) 
CPU:
  Topology: Single Core model: Intel Core i5-6300U bits: 64 
  type: MCP L2 cache: 3072 KiB 
  Speed: 2496 MHz min/max: N/A Core speed (MHz): 1: 2496 
Graphics:
  Device-1: InnoTek Systemberatung VirtualBox Graphics Adapter 
  driver: vboxvideo v: 5.2.20 r125813 
  Display: x11 server: X.org 1.20.3 driver: modesetting 
  resolution: <xdpyinfo missing> 
  Message: Unable to show advanced data. Required tool glxinfo 
  missing. 
Audio:
  Device-1: Intel 82801AA AC97 Audio driver: snd_intel8x0 
  Sound Server: ALSA v: k4.18.16-1-MANJARO 
Network:
  Device-1: Intel 82540EM Gigabit Ethernet driver: e1000 
  IF: enp0s3 state: up speed: 1000 Mbps duplex: full 
  mac: 08:00:27:78:c3:f2 
  Device-2: Intel 82371AB/EB/MB PIIX4 ACPI type: network bridge 
  driver: piix4_smbus 
Drives:
  Local Storage: total: 10.00 GiB used: 9.02 GiB (90.2%) 
  ID-1: /dev/sda vendor: VirtualBox model: VBOX HARDDISK 
  size: 10.00 GiB 
Partition:
  ID-1: / size: 9.78 GiB used: 9.02 GiB (92.2%) fs: ext4 
  dev: /dev/sda1 
Sensors:
  Message: No sensors data was found. Is sensors configured? 
Info:
  Processes: 130 Uptime: 1m Memory: 3.85 GiB 
  used: 421.0 MiB (10.7%) Shell: zsh inxi: 3.0.27

**Comment by tsujan** [comment]
Thanks but please read this: https://github.com/lxqt/pcmanfm-qt/issues/774 (the first comment only) and see if it solves your problem. If you want to add a comment, please do it there.

BTW, although you could report pcmanfm-qt bugs here, https://github.com/lxqt/pcmanfm-qt/issues is a better place for them (some LXQt components have their own issue tracker).

**Comment by tsujan** [comment]
I know that you've started to report bugs and we're very grateful. Please just don't open duplicate issues. Thanks in advance!
