### ISSUE TITLE
Distinguish pcmanfm-qt Root Window visually (feature request)

### ISSUE THREAD

**Issue by eirenicon** [lxqt/lxqt#1598]
It would (to my mind) be helpful if there was an obvious indicator of elevated privs in pcmanfm-qt. Perhaps a banner message colored red or similar.

##### Expected Behavior
pcmanfm-qt windows to obviously indicate elevated privs.

##### Steps to Reproduce (for bugs)

1. 
2. 
3. 
4.

**Comment by tsujan** [comment]
Yes, this feature is needed.

**Comment by agaida** [comment]
+1 - i would go a step further - if it is possible we should have it as default behaviour in all of our applications

**Comment by tsujan** [comment]
It's more about finding a good place for a warning bar. Changing the palette isn't good because it would interfere with styles and could result in an ugly window or even non-readable texts.

**Comment by tsujan** [comment]
Is this good?

![root](https://user-images.githubusercontent.com/981076/47619920-17742680-daf9-11e8-8413-9d3239bef444.png)

**Comment by agaida** [comment]
looks good - second option would be the window title root: pcmanfm - or $user: pcmanfm if started with an other than logged in user

**Comment by tsujan** [comment]
The title always shows the (active) folder name ("pcmanfm" in the above screenshot, by chance). No one could miss that red bar.

**Comment by tsujan** [comment]
BTW and by mere chance, I found a bug in the root instance that no one will encounter in a century ;) It exists in featherpad too. should fix both.

**Comment by agaida** [comment]
i'm fine with the red bar
