### ISSUE TITLE
Conky does not execute/run

### ISSUE THREAD

**Issue by eirenicon** [lxqt/lxqt#1599]
I have installed conky-manager 2.4 on my most recent build of LXQt from yesterday 28 Oct. 
None of several dozen scripts execute at all.  In my previously installed LXQt versions, conky worked. 

##### Expected Behavior
conky should run... work. ;)

##### Current Behavior
conky does not run/work at all. No errors are thrown.

##### Steps to Reproduce (for bugs)

1. install conky-manager
2. attempt to run any available script
3. 
4. 

##### System Information
System:
  Host: LXQt Kernel: 4.18.16-1-MANJARO x86_64 bits: 64 
  Desktop: LXQt 0.13.0 Distro: Manjaro Linux 
Machine:
  Type: Virtualbox System: innotek product: VirtualBox v: 1.2 
  serial: <root required> 
  Mobo: Oracle model: VirtualBox v: 1.2 serial: <root required> 
  BIOS: innotek v: VirtualBox date: 12/01/2006 
Battery:
  ID-1: BAT0 charge: 50.0 Wh condition: 50.0/50.0 Wh (100%) 
CPU:
  Topology: Single Core model: Intel Core i5-6300U bits: 64 
  type: MCP L2 cache: 3072 KiB 
  Speed: 2496 MHz min/max: N/A Core speed (MHz): 1: 2496 
Graphics:
  Device-1: InnoTek Systemberatung VirtualBox Graphics Adapter 
  driver: vboxvideo v: 5.2.20 r125813 
  Display: x11 server: X.org 1.20.3 driver: modesetting 
  resolution: <xdpyinfo missing> 
  Message: Unable to show advanced data. Required tool glxinfo 
  missing. 
Audio:
  Device-1: Intel 82801AA AC97 Audio driver: snd_intel8x0 
  Sound Server: ALSA v: k4.18.16-1-MANJARO 
Network:
  Device-1: Intel 82540EM Gigabit Ethernet driver: e1000 
  IF: enp0s3 state: up speed: 1000 Mbps duplex: full 
  mac: 08:00:27:78:c3:f2 
  Device-2: Intel 82371AB/EB/MB PIIX4 ACPI type: network bridge 
  driver: piix4_smbus 
Drives:
  Local Storage: total: 10.00 GiB used: 7.96 GiB (79.6%) 
  ID-1: /dev/sda vendor: VirtualBox model: VBOX HARDDISK 
  size: 10.00 GiB 
Partition:
  ID-1: / size: 9.78 GiB used: 7.96 GiB (81.4%) fs: ext4 
  dev: /dev/sda1 
Sensors:
  Message: No sensors data was found. Is sensors configured? 
Info:
  Processes: 132 Uptime: 4m Memory: 3.85 GiB 
  used: 404.4 MiB (10.2%) Shell: zsh inxi: 3.0.27

**Comment by tsujan** [comment]
I close this because Conky isn't related to LXQt at all.

Conky works fine with LXQt. I have it with several scripts and it has always worked here better than KDE or Gnome.

You could search for something about Conky which is missing/changed in your new installation.
