### ISSUE TITLE
Scrollbar appears in lxqt-config-appearence

### ISSUE THREAD

**Issue by stefonarch** [lxqt/lxqt#1606]
With recent changes (introducing gtk-styles  settings) there is now   a scrollbar present in the left sidebar menu. Not sure if this affects all languages/systems.

##### Possible Solution

Increase window height slightly. I didn't find the file...

![schermata-02-09-54-42](https://user-images.githubusercontent.com/10681413/47904777-d9269080-de85-11e8-8c99-54374565566c.png)

**Comment by tsujan** [comment]
Adjusting the height/width with respect to a special font/icon size or style is never a good practice. The scroll-bar is a valid part of every GUI -- you shouldn't be frightened by it ;)

![screenshot](https://user-images.githubusercontent.com/981076/47906767-2fec9400-de9f-11e8-9da4-3a8f6fe93551.png)

**Comment by stefonarch** [comment]
Well I'm not frightened that's not the problem ;)
The scrollbar here appears for all fonts bigger as 9px the same way, cutting of only a small part at the bottom.
If changing a default window size adding only 5px can avoid it... it's not even needed...

**Comment by tsujan** [comment]
Generally, it's wrong to avoid scrollbars in the code -- it isn't really possible and any attempt can make the window too wide/tall for some.

> If changing a default window size adding only 5px can avoid it

In *your case*. 5px, 4px,... all are wrong in the code. Qt designer sets the window width and height depending on who has used it first and with which font/style/icon sizes; even those dimensions may need to be decreased manually.

Last but not least, there's a reason that all toolkits have srollbars.

**Comment by tsujan** [comment]
The width is what's needed for showing the text and icon. But we may want a parameter to tell the code about the wrapping position, so that, for example, "Icons Theme" is drawn on a single line but "Icons Theme Is Beautiful" is drawn on 2 lines. It isn't urgent though.

**Comment by agaida** [comment]
We could make it wider without problems - would look better even with the short englisch texts - i remember an open bug by PcMan about

**Comment by Vladimir-csp** [comment]
Also keep in mind that other l10ns may have more lengthy labels.

**Comment by tsujan** [comment]
> We could make it wider without problems

Yes, I think so but I still don't know how easy it might be. A reasonable number of characters should be chosen. I think we could find the number in libfm-qt (although it isn't related to that dialog at all).

**Comment by tsujan** [comment]
Oh, https://github.com/lxqt/lxqt/issues/1510 shows we're dealing with a real bug here (I didn't know that). A fix may be somehow urgent.

**Comment by tsujan** [comment]
Found the cause; will try to fix it later.

**Comment by tsujan** [comment]
OK, I set the max number of characters to ~13 (as in libfm-qt) and got this, which looks better:

![13](https://user-images.githubusercontent.com/981076/47937744-f5164a80-def6-11e8-80e6-75cb0686d431.png)

I don't know how it will look with German or Chinese but using an empty `QRect` in `liblxqt` → `PageSelectWidget::updateMaxTextWidt()` was the cause. Is 13 enough or should it be more?

**Comment by tsujan** [comment]
Please test https://github.com/lxqt/liblxqt/pull/185 with your language!

**Comment by stefonarch** [comment]
Perfect now :)
![schermata-03-18-08-03](https://user-images.githubusercontent.com/10681413/47955141-9357ee00-df93-11e8-9792-1ea86f113992.png)

**Comment by tsujan** [comment]
@stefonarch Thanks! So, 13 is enough.
