### ISSUE TITLE
Language selector flag stays raised

### ISSUE THREAD

**Issue by venik212** [lxqt/lxqt#1607]
##### Current Behavior
When I select a language, the "flag" (the white rectangle with the languages names) remains raised, and no matter what I do I cannot get rid of it, except by rebooting.  What am I doing wrong?  Is this a bug?
##### Expected Behavior
The flag should be lowered as soon as I choose a language, as it does when I use LXDE, or XFCE.

##### Steps to Reproduce (for bugs)
1. Click on the language selector in the panel 
2. Choose a language
3. Observe that the flag remains raised.
4. Get frustrated and return to LXDE, where it works correctly.

##### Context
I was trying to choose a language and continue to work
##### System Information
Lenovo Yoga 2 Pro (8 gb RAM), (kernel: ), with LXQT, 2048X1152 

* Distribution & Version: Lubuntu 18.10 
* Kernel: 4.18.0-10
* Qt Version: ‎0.13.0 
* liblxqt Version: 
* Package version:

**Comment by agaida** [comment]
Sounds like an downstream problem

**Comment by tsimonq2** [comment]
...furthermore, what language selector? How are you changing the language here?

**Comment by venik212** [comment]
In the panel I have the letters EN when I am using English, CZ when I am using Czech, etc.  When I click on EN to change the language, the list of chosen languages pops up, but never goes down again unless I reboot.
I am using Lubuntu (LXQT) 18.10 on a Lenovo Yoga 2 Pro.

**Comment by venik212** [comment]
Yes, it was in the panel, in LXDE and now in the LXQT. 
I installed several languages that I need from time to time.  
In the meantime I had discovered that if I click on that stubborn "flag" twice or three times, it does go down. 
When I right-click on the language selector and choose Preferences the dialog that opens up is:
IBus preferences.  If I click on ABOUT I get: IBus 1.5.19.

**Comment by venik212** [comment]
I am not sure how one might document a long delay after touchpad click, or the need to repeat the click several times before it is effective.  I only bothered you with it because I thought that others might have had  similar issues.
I do not know for a fact that it has anything to do with LXqt-- but as I said, it does not happen with the other environments.
