### ISSUE TITLE
Bugfixing: We should speed up things

### ISSUE THREAD

**Issue by agaida** [lxqt/lxqt#1608]
@all 
and fix the most important bugs soon. If possible we should release latest first half of December 2018. Anything else will be hard if we want the upcoming release in Debian and Derivatives that are built on Debian Stable. Transition Freeze is January 2019 - so we should have our release in Sid before.

**Comment by tsujan** [comment]
> and fix the most important bugs soon

pcmanfm-qt and libfm-qt are stable. I think the same is true for lximage-qt, panel and most other components, if not all.

I have 4 PRs to be reviewed. If there's a really blocking bug somewhere, please tell me (but I can't promise anything).

As for release notes, I really don't remember how the last release was. It's very hard to find code commits among so many translation commits and I have no idea how release notes are going to be written.

**Comment by agaida** [comment]
https://github.com/orgs/lxqt/projects/2 - i guess the high prio things will be enough - if some other things are really needed before the release please put it in this row. Maybe is should be more clear about: Transition freeze means that there should be no new libraries after. Soname bumps included.

We can make a release and fix things that will come up afterwards - but we should leave our libs untouched. (Ok, oversimplified, but generally ok)

**Comment by tsujan** [comment]
I saw https://github.com/lxqt/lxqt/issues/534 for the first time.

https://github.com/lxqt/pcmanfm-qt/issues/701 shouldn't have a high priority -- it's only about my obsession with CPU.

https://github.com/lxqt/lxqt/issues/812 isn't a release blocker -- actually, I can't see it as a problem (although, as you once said, I shouldn't see myself like a typical user).

https://github.com/lxqt/lxqt/issues/1583 is @palinek's realm but I can't see a it as a release blocker either.

I don't think we could fix HDPI issues before the next release unless a dev starts to work on them actively.

**Comment by tsujan** [comment]
BTW, lxqt-archiver is almost forgotten. So many programs are beyond my time but I can do multitasking if I'm reminded. This page was a good reminder.

**Comment by agaida** [comment]
it became really helpful in the past year

**Comment by agaida** [comment]
@tsujan - and if i finished (probably tomorrow) i have a really nice surprise for you - changelogs shouldn't be a big problem anymore.

**Comment by tsujan** [comment]
Good!

I'll fix the "Enter-without-selection" problem tomorrow too.

**Comment by agaida** [comment]
@tsujan: Cool - i've played a bit with github yesterday and today - that's what i've done:
* Created a project with PRs for each repo and sorted it a bit  - sorted without any archived things it will look like this
  * https://github.com/lxqt/pcmanfm-qt/projects/1
  * https://github.com/lxqt/lxqt-panel/projects/1

If we archive translations, old and ancient stuff the remaining things in **Done** should be a good base for a changelog:
* https://github.com/lxqt/lxqt-sudo/projects/1
* https://github.com/lxqt/lxqt-runner/projects/1

What do you think?

**Comment by tsujan** [comment]
> What do you think?

That's great! Everything is nicely arranged.

I don't know how time-consuming it was/is but does it include all commits since the last release?

**Comment by agaida** [comment]
i had to process all pull requests since the very beginning :sunglasses: - was a bit boring

**Comment by tsujan** [comment]
Can it be automatized since now?

**Comment by tsujan** [comment]
I ask because, apart from release notes, finding previous commits easily is a big help.

**Comment by agaida** [comment]
yes, kind of - the github guys have done a very good job here - adding new things don't work perfect right now, but once the card are in it is automated - and the best is: when the work is done we just have to clean the Done (and any additional rows we might need) and there will be only new pull requests in - that was my plan. And once  the automation is improved we have nearly nothing to do with anymore - just a bit of filtering.

**Comment by agaida** [comment]
the downside right now is: it is js - so the more cards are in it will slow down and make the operations a pain in the arse. But the good news is: github has improved the speed of the handling a lot. So i think it will be the way to go in the future. One feature they will implement hopefully is to move issues and such things between trackers.

**Comment by tsujan** [comment]
That was very good news.

**Comment by tsujan** [comment]
I also saw nice beta features while opening issues.

**Comment by agaida** [comment]
ok, done for now - so we just have to fix the few remaining open bugs :D

**Comment by tsujan** [comment]
I'll make a PR for https://github.com/lxqt/pcmanfm-qt/issues/887 today and then investigate https://github.com/lxqt/pcmanfm-qt/issues/902
