### ISSUE TITLE
wishlist - have something like mate-netspeed applet. 

### ISSUE THREAD

**Issue by shirishag75** [lxqt/lxqt#1613]
It would be nice if we could have something similar to mate-netspeed applet. 

![mate-netspeed](https://user-images.githubusercontent.com/727626/48052036-d3ee7c00-e1cc-11e8-9465-1caed498a747.png)

This is what we currently have AFAIK in lxqt-panel 

![network-monitor-lxqt](https://user-images.githubusercontent.com/727626/48052054-e2d52e80-e1cc-11e8-987b-c1f237a8730f.png)

See https://github.com/mate-desktop/mate-applets/tree/master/netspeed . Maybe a similar netspeed applet can be designed around the lxqt codebase ?

**Comment by tsujan** [comment]
Already existing. See system statistics.

**Comment by shirishag75** [comment]
I just wasn't downloading anything at the time. I did see the system stats and while it kinda works, having numbers in kB/mB is usually more helpful as well as total traffic. Network monitor also does that but it doesn't do it for variety of use-cases. The most used option at least here is data packs and daily bandwidth allowance. Most operators count both download and upload as a single unit. As it stands now, as a user I have no idea about the stats being shared in either. At least with kb/mb notation I am able to have a bit of guesswork as to how much bandwidth was used let's say in last couple of hours or so.

**Comment by tsujan** [comment]
I use conky for that but I think the current panel widget can be modified to show more info. I'm very busy right now but will open an issue for it later.

**Comment by tsujan** [comment]
Opened https://github.com/lxqt/lxqt/issues/1615
