### ISSUE TITLE
pcmanfm-qt should either depend or recommend lxqt-archiver. 

### ISSUE THREAD

**Issue by shirishag75** [lxqt/lxqt#1614]
I installed the new version of pacmanfm-qt from experimental snapshots. After installing, logging out and logging back in, I found out that I could no longer decompress archives . While I'm not at liberty to share the archive,  file called it - 

`Zip archive data, at least v2.0 to extract`

I did look at all the dependencies and found everything to be current. Did come to know about lxqt-archiver and installed it but even after installing it, wasn't able to extract the archive. Using caja was able to extract the zip archive and carry on my work. 

I did see that lxqt-archiver does have some important issues reported against them as well, would be good to keep it in mind. 

```
Package: pcmanfm-qt
Version: 0.13.1~202-g7014a03-1
Severity: normal

-- System Information:
Debian Release: buster/sid
  APT prefers testing
  APT policy: (990, 'testing'), (500, 'unstable-debug'), (500, 'testing-debug'), (500, 'unstable'), (1, 'experimental-debug'), (1, 'experimental')
Architecture: amd64 (x86_64)

Kernel: Linux 4.18.0-2-amd64 (SMP w/4 CPU cores)
Locale: LANG=en_IN, LC_CTYPE=en_IN (charmap=UTF-8), LANGUAGE=en_IN:en (charmap=UTF-8)
Shell: /bin/sh linked to /bin/dash
Init: systemd (via /run/systemd/system)
LSM: AppArmor: enabled

Versions of packages pcmanfm-qt depends on:
ii  dbus-user-session [default-dbus-session-bus]  1.12.10-1
ii  dbus-x11 [dbus-session-bus]                   1.12.10-1
ii  desktop-file-utils                            0.23-4
ii  libc6                                         2.27-8
ii  libfm-qt6                                     0.13.2~278-g3ecb989-1
ii  libglib2.0-0                                  2.58.1-2
ii  libqt5core5a                                  5.11.2+dfsg-4
ii  libqt5dbus5                                   5.11.2+dfsg-4
ii  libqt5gui5                                    5.11.2+dfsg-4
ii  libqt5widgets5                                5.11.2+dfsg-4
ii  libqt5x11extras5                              5.11.2-2
ii  libstdc++6                                    8.2.0-9
ii  libxcb1                                       1.13.1-1
ii  lxqt-sudo                                     0.13.1~78-ga571dda-1

Versions of packages pcmanfm-qt recommends:
ii  breeze-icon-theme  4:5.49.0-1
ii  eject              2.1.5+deb1+cvs20081104-13.2
ii  faenza-icon-theme  1.3.1-1
ii  ffmpegthumbnailer  2.1.1-0.2+b1
ii  gvfs-backends      1.38.0-2
ii  gvfs-fuse          1.38.0-2
ii  lximage-qt         0.14.0~141-g7ea87b8-2
ii  lxqt-policykit     0.13.1~51-gbd2134e-1
ii  lxqt-qtplugin      0.13.1~4-g7065c43-4
ii  oxygen-icon-theme  5:5.49.0-1
ii  pcmanfm-qt-l10n    0.13.1~202-g7014a03-1

Versions of packages pcmanfm-qt suggests:
pn  cdtool       <none>
ii  libfm-tools  1.3.0.2-1

-- no debconf information

```

**Comment by tsujan** [comment]
pcmanfm-qt doesn't depend on `lxqt-archiver` -- you could use many archivers with it; check Preferences → Advanced →Archiver Integration.

"Recommendation" is a distro (downstream) concept and isn't related to LXQt itself. For example, deb packages can recommend other packages; the same is true for Arch and rpm packages.

`lxqt-archiver` is very new and has room for heavy development. It was created by PCMan, based on file-roller. I'll work on it if I find the required time.

If you find unreported bugs in lxqt-archiver (I'm sure you do), please report them at https://github.com/lxqt/lxqt-archiver/issues

**Comment by agaida** [comment]
@tsujan is right - and my other self as debian downstream is not willing to recommend lxqt-archiver or any program that is not even released yet anyway - no way. This will change with the first release of lxqt-archiver.

**Comment by tsujan** [comment]
> This will change with the first release of lxqt-archiver.

Exactly. `lxqt-archiver` is a nice app but not ready for use yet.
