### ISSUE TITLE
lxqt-globalkeys never shows a binding for lxqt-runner in the configuration

### ISSUE THREAD

**Issue by wxl** [lxqt/lxqt#1616]
Right out of the bat, it seems `lxqt-runner` is set to <kbd>Alt</kbd>+<kbd>F2</kbd> but the globalkeyshortcuts.conf shows it as unset. Instead I'm seeing:

```
[.36]
Comment=Show/hide runner dialog
Enabled=true
path=/runner/show_hide_dialog
```

Similarly, if you change it to some other value (example: <kbd>Alt</kbd>+<kbd>R</kbd>), it remains unset and no additional entry appears in the configuration file.

##### System Information
* Distribution & Version: Lubuntu 18.10
* Kernel: 4.18.0-10-generic
* Qt Version: 5.11.1
* liblxqt Version: 0.13.0-0ubuntu1
* Package version: 0.13.0-0ubuntu2 (for the lib, too)

**Comment by pcmagno** [comment]
I think this has been fixed. I just tested this on my machine.

System Information
    Distribution & Version: Fedora 31
    Kernel: 5.4.13-201.fc31.x86_64
    Qt Version: 5.13.2
    liblxqt Version: 0.14.1
    Package version: liblxqt-0.14.1-4.fc31.src.rpm

**Comment by tsujan** [comment]
Should have been fixed last year.
