### ISSUE TITLE
lxqt-panel mainmenu - also search in executable names

### ISSUE THREAD

**Issue by agaida** [lxqt/lxqt#1617]
Current Git

Just try to search gimp (or any other program with a binary-name != display name). Examples:
* gimp  (GNU Image ...)
* bcompare (Beyond Compare)

It might be that there are users in the wild who would call us insane if they really have to type in GNU to start gimp :dark_sunglasses:

**Comment by agaida** [comment]
![](https://i.imgur.com/NOeQtZD.jpg) vs ![](https://i.imgur.com/WVQwffG.jpg)

**Comment by tsujan** [comment]
The title surprised me because it meant "launch certain programs...." ;) But you mean "Also search in executable names...".

Yes, for GIMP I had to type "gnu" but isn't that a problem in GIMP desktop file? Searching in executable names would double the CPU time. I don't think we should compensate for mistakes in desktop files. There was another case of desktop file error in Krita, that prevented opening of images with Krita from pcmanfm-qt but it's fixed now.

**Comment by chriswyatt** [comment]
Though, you can type 'gimp' if you use Alt-F2. I wasn't even aware that search box was there, and have no desire to use it, as Alt-F2 is quicker.

**Comment by agaida** [comment]
@tsujan - ok, the subject is misleading - but i wouldn't call it a problem of the desktop file - you will see this often in esp. KDE applications. In KDE it become even worse if one show the descriptions instead of names.

**Comment by Vladimir-csp** [comment]
> I don't think we should compensate for mistakes in desktop files. 

I do not see how it is an error in desktop file. Name and Exec are distinct fields and there is no rule for them to contain the same substrings.

**Comment by tsujan** [comment]
OK, convinced; bombardment is enough ;) More CPU time will be taken willy-nilly; sequential or non-sequential will make no difference. It should be tested.

**Comment by tsujan** [comment]
Terra inkognita to me; the time I start to get familiar with the code, @palinek would have done it. So, please assign it to @palinek!

**Comment by tsujan** [comment]
I got obsessed by this (damn!), supposed it should have a simple solution, totally ignored menu-cache, subclassed `QSortFilterProxyModel` in `lxqt-panel → plugin-mainmenu → actionview.cpp`, and succeeded in doing it only for actionview:

![gimp](https://user-images.githubusercontent.com/981076/48280989-84c57700-e46a-11e8-8c98-0cd17c85dfab.png)

But that isn't a complete solution.

**Comment by agaida** [comment]
hihihi :)

**Comment by tsujan** [comment]
The PR is here: https://github.com/lxqt/lxqt-panel/pull/784

Didn't have time to respect the code style and ignored menu-cache (which means those who use it will see the old filtering).
