### ISSUE TITLE
[worldclock] option to not display week numbers

### ISSUE THREAD

**Issue by bjlockie** [lxqt/lxqt#1620]
Ad an option to WorldClock to not display the week numbers.

Eg. don't display the numbers that are circled in the linked picture:
http://lockie.ca/lxqt/calendar_config.jpg

##### System Information
LXQt About Version | 0.13.0
LXQt Version | 0.13.0
Qt | 5.11.1
Build type | Release
System Configuration | /etc/xdg
Share Directory | /usr/share/lxqt
Translations | /usr/share/Lubuntu/lxqt/translations/usr/local/share/lxqt/translations/usr/share/lxqt/translations/var/lib/snapd/desktop/lxqt/translations

**Comment by tsujan** [comment]
Implemented in https://github.com/lxqt/lxqt-panel/commit/a84bdd6c55b0f2069661f9966540c0718b35f6a4
