### ISSUE TITLE
several man pages are not installed

### ISSUE THREAD

**Issue by thx1111** [lxqt/lxqt#1622]
Arch Linux
lxqt-policykit 0.13.0-1

"make install" from the Makefile generated by cmake fails to install the man page.  Did you not want the man page installed?  Or, can we have the man page installed automatically?  "lxqt-policykit-agent.1" is referenced from SEE ALSO in lxqt-session(1), so it would be nice to install it.

**Comment by palinek** [comment]
done in lxqt/lxqt-policykit#56

**Comment by agaida** [comment]
will make a list and PRs - i will shameless "borrow" @palinek s code

**Comment by agaida** [comment]
All man pages i know right now

./lxqt-config/upstream/lxqt-config-appearance/man/lxqt-config-appearance.1
./lxqt-config/upstream/man/lxqt-config.1
./lxqt-config/upstream/liblxqt-config-cursor/man/lxqt-config-mouse.1
./lxqt-openssh-askpass/upstream/man/lxqt-openssh-askpass.1
./lxqt-panel/upstream/panel/man/lxqt-panel.1
./lxqt-policykit/upstream/man/lxqt-policykit-agent.1
./lxqt-runner/upstream/man/lxqt-runner.1
./lxqt-session/upstream/lxqt-session/man/lxqt-session.1
./lxqt-session/upstream/lxqt-leave/resources/lxqt-leave.1
./lxqt-session/upstream/lxqt-config-session/man/lxqt-config-session.1
./lxqt-session/upstream/startlxqt.1
./lxqt-sudo/upstream/man/lxqt-sudo.1
./pcmanfm-qt/upstream/pcmanfm-qt.1.in
./qps/upstream/qps.1
