### ISSUE TITLE
Tray menu for nextcloud-client disappears immediately after appeared

### ISSUE THREAD

**Issue by yan12125** [lxqt/lxqt#1624]
##### Expected Behavior
When clicking on the tray icon of nextcloud-client, a menu appears.

[xfce4-statusnotifier-plugin 0.2.1](https://git.xfce.org/panel-plugins/xfce4-statusnotifier-plugin/) works fine.

##### Current Behavior
The menu disappears immediately after appeared

##### Possible Solution
Looks like the nextcloud-client program added a menu item "Apps" after the tray menu is shown. Maybe that's a case not correctly handled in lxqt-panel.

Here are two screenshots from xfce4-panel, which might help understand the situation. The tray menu looks like this at first:

![default](https://user-images.githubusercontent.com/1937689/48662162-06e01c00-eab9-11e8-9a5b-752e1e460dd7.png)

After roughly 0.3 seconds, an item "Apps" is added:

![default](https://user-images.githubusercontent.com/1937689/48662166-1ceddc80-eab9-11e8-8c5f-7356005ccca6.png)

##### Steps to Reproduce (for bugs)
1. Install [nextcloud-client 2.5.0](https://github.com/nextcloud/desktop/releases/tag/v2.5.0) and run it
2. Enable StatusNotifierItem plugin for lxqt-panel
3. Right click on the icon of nextcloud-client

##### Context
Most functions of nextcloud-client are available in the tray menu only.

##### System Information
* Distribution & Version: Arch Linux up-to-date
* Kernel: 4.19.2
* Qt Version: 5.12 beta 4
* liblxqt Version: git-master
* Package version: git-master

**Comment by tsujan** [comment]
> Looks like the nextcloud-client program added a menu item "Apps" after the tray menu is shown. Maybe that's a case not correctly handled in lxqt-panel.

I've seen cases where a tray menu was open and items were added to it without problem (in desktop notification menu).

**Comment by yan12125** [comment]
Maybe the way nextcloud-client modifies the tray menu is problematic. I'll try to do more tests.

**Comment by agaida** [comment]
@yan12125 it is more likely that the ownclient/nextcloud client desktop file is borked - Search for an entry need systray or so - the only thing i noticed was a 3s delay for gnome - btw, started with a bit delay and systray availabe the client works just fine.

**Comment by agaida** [comment]
Erm - it is upstream - better, it is xdg. I kind of solved this issue with adding nextcloud to autostart and set the systray hook - so nextcloud client wait for the systray.

**Comment by DavidBreuer** [comment]
Hi @agaida, can you explain your fix in bit more detail? Thanks and best!

**Comment by agaida** [comment]
```
[Desktop Entry]
Categories=Network
Exec=/usr/bin/nextcloud
GenericName=File Synchronizer
Icon=nextcloud
Name=Nextcloud
StartupNotify=false
Terminal=false
Type=Application
X-GNOME-Autostart-enabled=true
X-LXQt-Need-Tray=true
```

**Comment by DavidBreuer** [comment]
Perfect, thanks for the quick reply.

**Comment by agaida** [comment]
it isn't really a fix - should be a built in

![](https://i.imgur.com/NbaDlVa.png)

**Comment by yan12125** [comment]
This issue also affects KDE (https://github.com/nextcloud/desktop/issues/833#issuecomment-439071032) and XFCE (https://github.com/nextcloud/desktop/issues/1126) users, so this is more likely their issue than ours. As a response they changed how the tray menu is constructed (https://github.com/nextcloud/desktop/pull/1477). With git-master of nextcloud-client, the tray menu plays fine with lxqt-panel.

Closing as Not Our Bug.
