### ISSUE TITLE
LXQt Appearance should have an Apply button

### ISSUE THREAD

**Issue by tsujan** [lxqt/lxqt#1625]
When something can change fast and an update is done after every change, a config dialog shouldn't apply changes immediately but should have an Apply button instead. 
##### Expected Behavior

An Apply button for LXQt Appearance (and, probably, some other config dialogs).
##### Current Behavior

The changes are applied immediately.
##### Possible Solution

It should be easy to apply changes only after an Apply button is clicked.
##### Steps to Reproduce (for bugs)

1. Go to LXQt Appearance → Font
2. Play with the font point size spin-box with mouse wheel.

You'll regret you've listened to me.

##### System Information

Latest git LXQt.

**Comment by agaida** [comment]
hihihi :see_no_evil: :hear_no_evil:  :speak_no_evil: 

> An Apply button for LXQt Appearance (and, probably, ~some other~ **all** config dialogs).

**Comment by tsujan** [comment]
Agreed.

**Comment by tsujan** [comment]
Ah..., it seems to be a lot of work.

**Comment by tsujan** [comment]
OK, I added the Apply button to LXQt Appearance, so that it's enabled once something is changed, no change is applied without clicking it, all changes are applied in all sections by clicking it, and it has no effect when all changes are reversed:

![appearance](https://user-images.githubusercontent.com/981076/48669094-bb0d9100-eb11-11e8-90ae-fda6dba14ae7.png)

However, since liblxqt is changed a little and comprehensive tests are needed, this should wait until the next release is published -- we don't want probable new issues in the next release.

In the meanwhile, I noticed that we use Windows layout for dialog buttons. I have no problem with the Windows layout but I think that the GTK or KDE layout is more appropriate under Linux.

**Comment by stefonarch** [comment]
Hm, I cannot see why this should change, it's one click more but for which benefit?
I like much the current behavior, you can see immediately how it looks.

**Comment by tsujan** [comment]
> for which benefit?

Please read the report! Also, KDE is wise enough to do the same thing.

**Comment by Vladimir-csp** [comment]
Apply button is the sanest thing ever. Far better than things flying around after  click on an option.

**Comment by agaida** [comment]
+1 for apply button

**Comment by tsujan** [comment]
The lack of an Apply button is an annoyance for the reason explained in the first comment of this report.

In some places, there may be no need to an Apply button but, since it's definitely needed in LXQt Appearances (I've finished the job) and in any config dialog with a combo-box/spin-box, it's better to add it everywhere for the sake of consistency.

**Comment by tsujan** [comment]
Moreover, the lack of an Apply button where data are in combo-boxes/spin-boxes can be seen as a bug -- whether Gnome or Apple use it or not.

**Comment by tsujan** [comment]
Done for `Appearance` and `Keyboard and Mouse`. They should be patched together because they share `liblxqt-config-cursor`. The other config dialogs need to be treated separately.

Ready for making a big PR after 0.14.0 is released. The PR will be big because code structures are changed from immediate applying to waiting for a click.
