### ISSUE TITLE
Main menu DND from search item-view

### ISSUE THREAD

**Issue by tsujan** [lxqt/lxqt#1626]
Of course, it's possible to drag items of the main menu and drop them somewhere (on Desktop, for example). But finding a specific item may not be easy and the search functionality may be needed.
##### Expected Behavior

It would be good if items could be dragged from the search item-view too.
##### Current Behavior

The search item-view doesn't support DND.
##### Possible Solution

Very easy! Add DND to the search item-view. (It may not be easy at all.)
##### Steps to Reproduce (for bugs)

1. Search for an app inside the main menu.
2. Try to drag and drop it from the search item-view.

You'll be disappointed if you're as lazy as I am.
##### System Information

Latest git LXQt.

**Comment by agaida** [comment]
that would be cool

btw - we should (re)open a bug for dragging menus/submenus too

**Comment by tsujan** [comment]
> we should (re)open a bug for dragging menus/submenus too

Why? It works.

**Comment by agaida** [comment]
good joke

**Comment by tsujan** [comment]
Done by @slidinghotdog in https://github.com/lxqt/lxqt-panel/commit/93ae12f6f82162c33ed147d028b5c8029c3dd003
