### ISSUE TITLE
Lxqt-leave reboot and logout do not work

### ISSUE THREAD

**Issue by roman-buntsevich** [lxqt/lxqt#1627]
##### Expected Behavior
System reboot or shutdown after I pressed corresponding UI button (or input a command from a terminal).

##### Current Behavior
When I press Leave -> Reboot or Leave -> Shutdown nothing happens (visually). Also I can't use commands from content of .desktop files in terminal - I get an error

roman@debian:~ lxqt-leave --reboot
** Dbus error **************************
Error name  "org.freedesktop.DBus.Error.AccessDenied"
Error msg   "Permission denied"
****************************************
systemd: "CanReboot" = "Permission denied"
dbusCall: QDBusInterface is invalid "org.freedesktop.ConsoleKit" "/org/freedesktop/ConsoleKit/Manager" "org.freedesktop.ConsoleKit.Manager" "CanReboot"

##### Possible Solution
As workaround you can use systemctl (from terminal or with edititing Exec /usr/share/applications corresponding .desktop files).

##### Steps to Reproduce
Install fresh debian 9.6 stretch from netinst iso (https://www.debian.org/CD/netinst/) and programs from the list below with apt-get install --no-install-recommends, reboot and login to LXQt session.

##### Context
This is very annoying and strange issue. I have tried solutions from google search result but nothing helped. I am sure I did everything right during software installation, so this is a definitely unexpected behavior.

##### System Information
Software list:
vim less man openssh-server
xserver-xorg xdg-utils openbox openbox-menu obconf sddm pcmanfm-qt lxqt-core lxqt-panel lxqt-qtplugin lxqt-globalkeys lxqt-notificationd lxqt-config lxqt-runner libfm-qt terminator xarchiver unzip bzip2 lbzip2

* Distribution & Version: I have a fresh debian 9.6 "stretch" from netinst iso (https://www.debian.org/CD/netinst/) with nothing standard (last setup screen with choice).
* Kernel: Linux debian 4.9.0-8-amd64 #1 SMP Debian 4.9.130-2 (2018-10-27) x86_64 GNU/Linux
* Qt Version: don't know how to find out, mostly installed llibs' names end with qt5
* liblxqt Version: liblxqt0/stable,now 0.11.1-1 amd64 [installed,automatic]
* Package version: lxqt-core 13

**Comment by agaida** [comment]
not an upstream issue - and not a debian issue.  And there is nothing we will fix neighter in upstream nor in debian. My vague guess is that you had installed the lxqt-core meta package with --no-install-recommends. if so - it was **your** decision so only **you** had to deal with it.

It might sound harsh - but this is called reality. Another hint: If one would install the "bloated" lxqt meta-package it would work. 

More verbose: The meta-packages currently in stable are really stripped down to the point where nothing left to remove. And core is meant as the LXQt core - after we had experienced the users forcefully wrecked their installations we changed both lxqt and lxqt-core to make it more "user-proof" aka we added packages that are not really dependencies to the dependencies just to have a working system the most users would expect to have after an fresh installation. 

```
% LANG=C apt show lxqt-core/stable
Package: lxqt-core
Version: 13
Priority: optional
Section: metapackages
Source: lxqt-metapackages
Maintainer: LXQt Packaging Team <pkg-lxqt-devel@lists.alioth.debian.org>
Installed-Size: 10,2 kB
Depends: lxqt-common, lxqt-panel, lxqt-session, pcmanfm-qt, desktop-file-utils, xfwm4 | x-window-manager
Recommends: lxqt-sudo | gksu, qterminal | x-terminal-emulator, xscreensaver
Suggests: firefox | www-browser, lxqt, lxqt-runner
Homepage: http://www.lxqt.org/
Download-Size: 3.330 B
APT-Sources: http://ftp.debian.org/debian stable/main amd64 Packages
Description: Metapackage for the LXQt core
 LXQt is an advanced, easy-to-use, and fast desktop environment based on Qt
 technologies. It has been tailored for users who value simplicity, speed, and
 an intuitive interface. Unlike most desktop environments, LXQt also works
 fine with less powerful machines.
 .
 This package is a metapackage meant to provide the core components
 of LXQt. These include pcmanfm-qt, lxqt-panel, lxqt-session and xfwm4 (or
 a window manager of choice).
```
vs 
```
% LANG=C apt show lxqt-core/unstable
Package: lxqt-core
Version: 29
Priority: optional
Section: metapackages
Source: lxqt-metapackages
Maintainer: LXQt Packaging Team <pkg-lxqt-devel@lists.alioth.debian.org>
Installed-Size: 9.216 B
Depends: lxqt-themes | lxqt-theme, lxqt-system-theme, lxqt-config, lxqt-notificationd, lxqt-globalkeys, lxqt-panel, lxqt-policykit, lxqt-qtplugin, lxqt-runner, lxqt-session, pcmanfm-qt, qterminal | x-terminal-emulator, desktop-file-utils
Recommends: featherpad, lximage-qt, lxqt-about, lxqt-powermanagement, lxqt-sudo, pavucontrol-qt | pavucontrol, qlipper | clipit | xfce4-clipman, xterm, qttranslations5-l10n, lxqt-archiver | xarchiver | ark | engrampa, xscreensaver
Suggests: firefox | www-browser, lxqt, lxqt-openssh-askpass, preload
Breaks: lxqt-common (<< 0.12.0)
Replaces: lxqt-common (<< 0.12.0)
Homepage: http://www.lxqt.org/
Download-Size: 2.760 B
APT-Manual-Installed: yes
APT-Sources: https://packages.siduction.org/fixes unstable/main amd64 Packages
Description: Metapackage for the LXQt core
 LXQt is an advanced, easy-to-use, and fast desktop environment based on Qt
 technologies. It has been tailored for users who value simplicity, speed, and
 an intuitive interface. Unlike most desktop environments, LXQt also works
 fine with less powerful machines.
 .
 This package is a metapackage meant to provide the core components of LXQt.
 These include pcmanfm-qt, lxqt-panel, lxqt-runner, lxqt-session and esp.
 lxqt-qtplugin (needed for communication between session, components and
 applications).
 .
 Recommend for lean and/or parallel installation with other desktop
 environments.
```
So yes - i use my maintaier super powers to force working installations upon the meta-packages users. I really know and admit that i'm a very bad guy.

**Comment by agaida** [comment]
PS: at least want to install `lxqt-policykit` or any other pk-handler to have the needed rights as a user to perform tasks like shutdown or reboot - obvious, isn't it?

**Comment by jenshenk** [comment]
Pretty old issue but still one of the first hits on google. I ran into this issue by installing lxqt with task-lxqt-desktop, which actually installs lxqt-policykit but not policykit-1. This is what fixed this issue for me: 

- Install policykit-1 
(on debian etc:) sudo apt install policykit-1  

- add the following into a new file /etc/polkit-1/rules.d/60-lxqt-shutdown.rules
```
polkit.addRule(function(action, subject) {
	if (subject.isInGroup("users")) {
    	if (action.id == "org.freedesktop.login1.power-off" ||
        	action.id == "org.freedesktop.login1.reboot" ||
        	action.id == "org.freedesktop.login1.suspend" ||
        	action.id == "org.freedesktop.login1.hibernate") {
        	return polkit.Result.YES;
    	}
	}
});
```
- restart policykit 
sudo systemctl restart polkit
