### ISSUE TITLE
Easier way to move buttons in quick launch

### ISSUE THREAD

**Issue by BaumGuard** [lxqt/lxqt#1629]
It'll be nice if you could move programs in the task bar around with the mouse, because it's getting on my nervs always to click several times till the program is on the position where I want it to be.

**Comment by tsujan** [comment]
Buttons can already be moved inside taskbar by DND.

**Comment by agaida** [comment]
i guess @BaumGuard  talk about our quickstarter - if so it is valid

**Comment by chriswyatt** [comment]
Though I doubt your average user shuffles the quick start icons around very often. Still, it was my first intuition to drag and drop, so probably helps with the initial first impression.

**Comment by tsujan** [comment]
> Still, it was my first intuition to drag and drop

Correct. It's a hassle to right click, click Move Left/Right, right click again, click Move Left/Right again, etc. I guess it was the easiest implementation but no one changed it later.

**Comment by poikilos** [comment]
You can drag while holding **Ctrl** to rearrange Quick Launch icons in LXQt 0.13.0.

**Comment by tsujan** [comment]
> You can drag while holding Ctrl to rearrange Quick Launch icons in LXQt 0.13.0.

Right. I saw it after reading the code. It's a hidden feature.
