### ISSUE TITLE
Mainmenu button has non-transparent background in some themes that come with LXQt

### ISSUE THREAD

**Issue by brzegorz** [lxqt/lxqt#1631]
* Left side of the screenshot present's the issue, which I find unaesthetical
    * Screenshot attached is from the "dark" theme, other are affected to lesser extent
    * System used is Arch, lxqt is taken from official repositories, compton is the used compositing manager
##### Expected Behavior

    * The mainmenu/app finder should have the same transparency as the rest of the panel,
see the right-hand of the screenshot
##### Current Behavior

    * Left-hand of the screenshot
##### Possible Solution

    Version 1: Change the transparency in #MainMenu background section of the lxqt-panel.qss in the /usr/share/lxqt/themes to full for the dark theme. That way it will have the same transparency as the panel. Other themes might have different setting based on the particular style design. 
    Version 2: Make it configurable in the "Application menu" configuration
    Version 3: Document it somewhere searchable. Despite being competent computer user I've had to spend a lot of time to find this: https://forum.lxqt.org/t/is-it-possible-to-make-menu-background-transparent/347
##### Steps to Reproduce (for bugs)

1. Install lxqt
2. Install compositing manager(suggested: compton/xcompmgr, I've encountered the issue on those two. It should behave the same way regardless of the compositor used)
3. Set theme to dark in Preferences -> LXQT Settings -> Appearance
4. Right-click on the panel and set opacity to below 70%

##### Context

It just looks bad and inconsistent

##### System Information

* Distribution & Version: Arch Linux
* Kernel: 4.19.4-arch1-1-ARCH
* Qt Version: 5.11.2
* liblxqt Version: ?
* Package version: 0.13.0-1
![lxqt_mainmenu_transparency](https://user-images.githubusercontent.com/23345044/49005440-01dd3580-f167-11e8-9bd9-ddab23f23f9b.png)

**Comment by palinek** [comment]
Are you talking "just" about the "menu button" (not about the application menu that appears upon the "menu button" triggering)?

**Comment by tsujan** [comment]
This is about some LXQt themes, not the main menu itself. Also, tastes differ: what one user sees ugly may not seem so to another user.

**Comment by brzegorz** [comment]
@palinek 
Yes, exactly. The part on the panel with the lxqt logo and "Applications" text, with black background on the left side.

@tsujan 
I'm sorry if this post is in the wrong place. Tastes differ, that's right. I can obviously speak only for myself. However, this doesn't make discussion about tastes meaningless, and doesn't make all defaults and base themes equally good. Because of that I've decided to voice my opinion, so you can take it into consideration.

**Comment by agaida** [comment]
@brzegorz - as far as i remember the non-transparen menu is cruft of the past - some elements could not be styled with qss in former Qt versions. And no one noticed it / complained about. But the good news is: We accept patches :D

**Comment by tsujan** [comment]
@brzegorz I didn't mean such discussions were meaningless. Sometimes, we search in issue titles to fix bugs or add features. I corrected the title.

**Comment by brzegorz** [comment]
If the sentence about patches is a suggestion - I would be glad to send one. I have no idea where are the qss files stored/generated though, so I would need to br pointed in the right direction

**Comment by tsujan** [comment]
No patch was sent. Why is this still open?
