### ISSUE TITLE
Changelog branches for all projects

### ISSUE THREAD

**Issue by agaida** [lxqt/lxqt#1632]
Releasestuff, we don't create changelogs automagically

* [ ] compton-conf https://github.com/lxqt/compton-conf/blob/changelog/CHANGELOG
* [ ] libfm-qt https://github.com/lxqt/libfm-qt/blob/changelog/CHANGELOG
* [ ] liblxqt https://github.com/lxqt/liblxqt/blob/changelog/CHANGELOG
* [ ] libqtxdg  https://github.com/lxqt/libqtxdg/blob/changelog/CHANGELOG
* [ ] libsysstat https://github.com/lxqt/libsysstat/blob/changelog/CHANGELOG
* [ ] lximage-qt https://github.com/lxqt/lximage-qt/blob/changelog/CHANGELOG
* [ ] lxqt-about https://github.com/lxqt/lxqt-about/blob/changelog/CHANGELOG
* [ ] lxqt-admin https://github.com/lxqt/lxqt-admin/blob/changelog/CHANGELOG
* [ ] lxqt-build-tools https://github.com/lxqt/lxqt-build-tools/blob/changelog/CHANGELOG
* [ ] lxqt-config  https://github.com/lxqt/lxqt-config/blob/changelog/CHANGELOG
* [ ] lxqt-globalkeys https://github.com/lxqt/lxqt-globalkeys/blob/changelog/CHANGELOG
* [ ] lxqt-notificationd https://github.com/lxqt/lxqt-notificationd/blob/changelog/CHANGELOG
* [ ] lxqt-openssh-askpass https://github.com/lxqt/lxqt-openssh-askpass/blob/changelog/CHANGELOG
* [ ] lxqt-panel  https://github.com/lxqt/lxqt-panel/blob/changelog/CHANGELOG
* [ ] lxqt-policykit  https://github.com/lxqt/lxqt-policykit/blob/changelog/CHANGELOG
* [ ] lxqt-powermanagement https://github.com/lxqt/lxqt-powermanagement/blob/changelog/CHANGELOG
* [ ] lxqt-qtplugin  https://github.com/lxqt/lxqt-qtplugin/blob/changelog/CHANGELOG
* [ ] lxqt-runner  https://github.com/lxqt/lxqt-runner/blob/changelog/CHANGELOG
* [ ] lxqt-session   https://github.com/lxqt/lxqt-session/blob/changelog/CHANGELOG
* [ ] lxqt-sudo  https://github.com/lxqt/lxqt-sudo/blob/changelog/CHANGELOG
* [ ] lxqt-themes https://github.com/lxqt/lxqt-themes/blob/changelog/CHANGELOG
* [ ] obconf-qt   https://github.com/lxqt/obconf-qt/blob/changelog/CHANGELOG
* [ ] pavucontrol-qt   https://github.com/lxqt/pavucontrol-qt/blob/changelog/CHANGELOG
* [ ] pcmanfm-qt  https://github.com/lxqt/pcmanfm-qt/blob/changelog/CHANGELOG (WIP)
* [ ] qps  https://github.com/lxqt/qps/blob/changelog/CHANGELOG
* [ ] qterminal  https://github.com/lxqt/qterminal/blob/changelog/CHANGELOG
* [ ] qtermwidget  https://github.com/lxqt/qtermwidget/blob/changelog/CHANGELOG
* [ ] screengrab  https://github.com/lxqt/screengrab/blob/changelog/CHANGELOG

There are current changelog branches for all the listed packages, so it might be a good idea to write the changelog directly in the editor or just checkout and write them locally - if finished the changelogs should be merged/squashed into master - so it doesnt really matter how much commits are generated. I prepared project pages with some pre-filtered pull requests - one should use the relevant ones and maybe put the used in a new column "Changelog" or so (or just **archive** the not used)

We should try to only list relevant changes. And maybe mark the changelogs we are working on with our name here

##### Not ready yet

* [ ] lxqt-archiver (not release ready yet)
* [ ] sddm-config-editor (not release ready yet)

**Comment by agaida** [comment]
* [ ] compton-conf
* [ ] libfm-qt
* [ ] liblxqt
* [ ] libqtxdg
* [ ] libsysstat
* [ ] lximage-qt
* [ ] lxqt-about
* [ ] lxqt-admin
* [ ] lxqt-archiver
* [ ] lxqt-build-tools
* [ ] lxqt-config
* [ ] lxqt-globalkeys
* [ ] lxqt-notificationd
* [ ] lxqt-openssh-askpass
* [ ] lxqt-panel
* [ ] lxqt-policykit
* [ ] lxqt-powermanagement
* [ ] lxqt-qtplugin
* [ ] lxqt-runner
* [ ] lxqt-session
* [ ] lxqt-sudo
* [ ] lxqt-themes
* [ ] obconf-qt
* [ ] pavucontrol-qt
* [ ] pcmanfm-qt
* [ ] qps
* [ ] qterminal
* [ ] qtermwidget
* [ ] screengrab
* [ ] sddm-config-editor

**Comment by tsujan** [comment]
What can I do for libfm-qt and pcmanfm-qt -- and how?

**Comment by tsujan** [comment]
@agaida, 2 questions:

  * Can/should I make PRs for https://github.com/lxqt/libfm-qt/blob/master/CHANGELOG and https://github.com/lxqt/pcmanfm-qt/blob/master/CHANGELOG ?

  * What is the next version? 0.14.0 ?

**Comment by agaida** [comment]
you can push directly to the changelog branch - my plan is to squash the changelogs into master when ready - and yes, 0.14.0 will be the next version

**Comment by tsujan** [comment]
OK. I did it badly for libfm-qt -- made another branch and merged the PR -- but it should be OK because the change log is complete. Will do as you told next time.

**Comment by agaida** [comment]
No problem at all and no need to fix anything. It seemst that the combination of a permanent changelog-branch and projects could provide a good workflow.

**Comment by jubalh** [comment]
Hi, I just skimmed over the existing changelogs. Very good job! Much better than in previous releases! Thank you all :)

**Comment by yan12125** [comment]
> The big bump was needed to prevent conflicts with translations that *was* former built out of lxqt-l10n and have version xyz

s/was/were/

I'll fix them for qterm*

**Comment by agaida** [comment]
Release is done
