### ISSUE TITLE
lxqt-notifications incompatible with i3

### ISSUE THREAD

**Issue by unmellow** [lxqt/lxqt#1633]
##### Expected Behavior
notifications should appear on the right corner of my screen
no matter what window manager I'm using

##### Current Behavior
when I use i3 notifications appear in the middle of the screen
I don't have this problem when using Openbox and I haven't 
tried anything else

##### Possible Solution
I'm not sure what causes this problem 
but depending on my i3 config my objects 
on the screen appear to be larger or smaller

##### Steps to Reproduce (for bugs)

1. install manjaro lxqt edition
2. install i3 set it up using [these instructions](http://feeblenerd.blogspot.com/2016/08/walkthrough-for-lubuntu-with-i3-tiling.html)
3. afterwords trigger a notification in any way possible and it is in the middle of the screen

##### Context
I have a volume control  widget in the corner of my screen
when I click on it the popup to change the volume appears in 
the middle and there's no way to get my mouse on it

##### System Information
* Distribution & Version: manjaro Linux 18.0.0 illaria
* Kernel: 4.19.4-1 
* Qt Version: qt5-base  5.11.2-3
* liblxqt Version: 0.13.0-1
* Package version: don't know what this means

##### examples
![screenshot from 2018-11-29 15-08-43](https://user-images.githubusercontent.com/30985587/49249714-fbf78680-f3ea-11e8-9399-043729857463.png)

**Comment by tsujan** [comment]
Not an LXQt issue. Also see https://github.com/lxqt/lxqt/issues/1345.
