### ISSUE TITLE
Theoretical problem with `QLatin1String` in LXQt codes

### ISSUE THREAD

**Issue by tsujan** [lxqt/lxqt#1637]
According to [Qt doc](http://doc.qt.io/qt-5/qlatin1string.html):

> If the function you're calling with a `QLatin1String` argument isn't actually overloaded to take `QLatin1String`, the implicit conversion to `QString` will trigger a memory allocation, which is usually what you want to avoid by using `QLatin1String` in the first place. In those cases, using `QStringLiteral` may be the better option.

I've encountered several places in LXQt sources where `QLatin1String` should be replaced by `QStringLiteral`. For example, `QSettings::value()` doesn't have an overload with `QLatin1String`, so that it should be used like:
```c++
... = settings->value(QStringLiteral("this_key"));
```
I recently started to use `QStringLiteral` wherever appropriate in a program with many strings but, contrary to Qt doc's overemphasis, I didn't find any tangible difference. However, since LXQt sticks to these rules, it may be better to replace `QLatin1String` with `QStringLiteral` in such places.

**Comment by shlyakpavel** [comment]
I strongly believe that such things are compiler-optimized. However, QStringLiteral still makes sense in terms of readability

**Comment by tsujan** [comment]
> I strongly believe that such things are compiler-optimized

It isn't what I've seen in practice and I think it's overemphasized, although there may be special places where it's really needed.

However, I didn't want to discuss that here but just wanted to mention the difference between `QLatin1String` and `QStringLiteral` -- as Qt doc claims -- and that we don't always use them "correctly" -- again, as Qt doc says.

**Comment by luis-pereira** [comment]
@tsujan IMO the reason to use `QLatin1String/QStringLiteral` is to avoid / make the implicit cast visible. Performance gains are  more a side effect than anything else.

From: http://blog.qt.io/blog/2014/06/13/qt-weekly-13-qstringliteral/

> Avoid duplicated QStringLiterals
> 
> Avoid having multiple QStringLiterals with the same content. For plain literals and QLatin1String, compilers try to consolidate identical literals so that they are not duplicated. For QStringLiteral, identical strings cannot be merged.

Usually there is a pair of `QSettings::value()/QSettings::setValue()` with the same strings. In those cases I use `QLatin1String` for the reason above.

**Comment by tsujan** [comment]
That old article contradicts the Qt doc. Although these performance gains are mostly like myths to me, following the Qt doc seems more acceptable in the absence of a firsthand proof.

Anyhow, I don't want to be more catholic than the pope ;) Feel free to close this if it has no pertinence to LXQt!

**Comment by luis-pereira** [comment]
As I said before, performance is a secondary effect. The main reason to use `QLatin1String / QStringLiteral` is to explicitly handle  a cast to UTF-16, IMO.

The article is old but still accurate. QStringLiteral can't share the data, QLatin1String can. Some documentation seems to be wishful thinking.
``` cpp
#include <QCoreApplication>
#include <iostream>

int main(int argc, char *argv[])
{
    QCoreApplication a(argc, argv);
    std::cout << qPrintable(QStringLiteral("Hello, World"));
    std::cout << qPrintable(QStringLiteral("Hello, World"));
    return 0;
}```
`
objdump -s -j .rodata ./strings 

./strings:     file format elf32-i386

Contents of section .rodata:
 0cc0 03000000 01000200 00000000 00000000  ................
 0cd0 00000000 00000000 00000000 00000000  ................
 0ce0 ffffffff 0c000000 00000000 10000000  ................
 0cf0 48006500 6c006c00 6f002c00 20005700  H.e.l.l.o.,. .W.
 0d00 6f007200 6c006400 00000000 00000000  o.r.l.d.........
 0d10 00000000 00000000 00000000 00000000  ................
 0d20 ffffffff 0c000000 00000000 10000000  ................
 0d30 48006500 6c006c00 6f002c00 20005700  H.e.l.l.o.,. .W.
 0d40 6f007200 6c006400 00000000           o.r.l.d.....    
``` 

VS

``` cpp
#include <QCoreApplication>
#include <iostream>

int main(int argc, char *argv[])
{
    QCoreApplication a(argc, argv);
    std::cout << qPrintable(QLatin1String("Hello, World"));
    std::cout << qPrintable(QLatin1String("Hello, World"));
    return 0;
}
```

```
objdump -s -j .rodata ./strings 

./strings:     file format elf32-i386

Contents of section .rodata:
 0d68 03000000 01000200 48656c6c 6f2c2057  ........Hello, W
 0d78 6f726c64 00                          orld. 
```

**Comment by tsujan** [comment]
These things are just subjective choices, depending on which code is used in which app and under what circumstances. They don't have real impact. Closing.
