### ISSUE TITLE
Configuring the network is not "user-friendly"

### ISSUE THREAD

**Issue by Delgan** [lxqt/lxqt#1643]
Hi.

I just installed Lubuntu 18.10 which comes with lxqt and I love the performances, the beauty and the simplicity of the desktop environment you created.

I would like to install it everywhere and to advise it to my non-techy-Windows-user friends, but I hesitate to do so because there are few things that are not as polished as on other distributions.

One problem, in my opinion, is the configuration of the network. This is the first thing we do after installing an OS, so this is the first interaction of the user with the distribution, and it means so much on his first impression of this new environment.

I made this gif right after installing Lubuntu, while Internet is not yet working.

![ezgif-4-b5b31f1d8fba](https://user-images.githubusercontent.com/4193924/50548291-6863e080-0c4a-11e9-87b8-8651f7da8ca4.gif)

I wanted to denote a few things:
* Clicking on the "Wi-Fi network" does nothing
     * I guess it should either not be clickable or open a window information / configuration about the network
* Clicking on the network in "Known connection" disconnect me
     * Why does it do so while clicking on the same network under "Wi-Fi network" did nothing?
     * How can it disconnect me while I'm not even connected?
     * What actually changed? The icon stays the same. The network list stays the same.
* The "Connection Information" open an empty window
    * I suppose it should display a message like "You are not currently connected to any network". Otherwise, the user may think "Is it a bug? Is it loading data info in the background?"
* The "Edit connections" open a Shell rather that a graphical window
    * I know that this is easily configurable and that there is not even one command line to type, but this would be much more welcoming if configuring the network was made trough a graphical window, and if it just required to type the WPA key in a input box.

I know it may sound like detail and that lxqt is already very easy to use, but I sincerely believe that the graphical interface would benefit a lot for being as user-friendly as possible.

I hope it makes as much sense to you as it makes to me.

##### System Information
* Distribution & Version: Lubuntu 18.10
* Kernel: 4.18.0-13-generic
* Qt Version: 5.11.1
* liblxqt Version: 0.13.0

**Comment by agaida** [comment]
Use a different networkmanager, applet or distribution - we are in no way responsible for downstream decisions. Launchpad might be the right place to complain - and btw: We are not happy with the choice too, but the choice of components is a downstream thing.

**Comment by Delgan** [comment]
I was not sure where to open this issue. Sorry for the inconvenience, and thanks for the suggestions.

For information, here is the corresponding ticket I opened on Launchpad: [Bug #1810095](https://bugs.launchpad.net/ubuntu/+bug/1810095)

**Comment by agaida** [comment]
There is only one problem with nm-tray:  in the current state it is fine for experienced users who don't mind the interface and maybe some integration problems (aka one should know how to configure networks with the basic interface). Maybe just replace nm-tray with network-manager-gnome and be done with. Ok, it will throw in some dependencies - nothing i would be affraid of.

**Comment by Delgan** [comment]
> There is only one problem with nm-tray: in the current state it is fine for experienced users who don't mind the interface and maybe some integration problems (aka one should know how to configure networks with the basic interface).

That was my primary concern. 

> Maybe just replace nm-tray with network-manager-gnome and be done with. Ok, it will throw in some dependencies - nothing i would be affraid of.

That works fine, thanks!

> We are not happy with the choice too, but the choice of components is a downstream thing.

I am not very experienced with Linux development. Do you mean you are not happy with `Lubuntu` using `nm-tray` as the default network manager (although you contributed to it)?

**Comment by agaida** [comment]
I contributed to it, i maintain it in debian - neverless i don't think it's a good choice for Lubuntu :sunglasses:  - the interface is maybe not the best choice for the targeted audience. Otherwise: It works fine and has only very few Qt dependencies that are used in other components too. And throw not in additional GTK things. Never looked in the needed GTK things for the gnome applet, but i wouldn't care. Thats my private opinion, i avoid n-m where ever i can since over ten years.

**Comment by Delgan** [comment]
@agaida Thanks for your explanation! I'm starting to better understand how the Linux environment works, its different components, and its relationship with lxqt.

@tsimonq2 Do you mean this is related to https://github.com/palinek/nm-tray/issues/23?

**Comment by tsimonq2** [comment]
Somewhat. Please do file concerns separately on that repo if you have them.

Thanks!

**Comment by motocyklista** [comment]
@agaida how it is look now? nm-tray is good choice? If I want to install network-manager-gnome this will be safe for the system? This network manager works good with LXQt? How much additional packages I will must install (dependencies reason) to start network-manager-gnome?

**Comment by tsujan** [comment]
Please ask distro questions from your distro. Here is upstream; your question is about downstream.

**Comment by motocyklista** [comment]
@tsujan ok, I will ask in website dedicated for distro but I apreciate that you answered me. It is very positive that developer are very active and answer for the questions.

P.S. Do you have polish language support for LXQt? I can help with translate. My english is not the best but it is not disaster so I can help with it. Maybe in the future I will can help more because I will try learn C++ :)

**Comment by tsujan** [comment]
I don't have Ubuntu/Lubuntu. Use any network manager that works for you. I use CMST.
