### ISSUE TITLE
Qt 5.12 tooltips are not OK; not our fault

### ISSUE THREAD

**Issue by tsujan** [lxqt/lxqt#1645]
This is just an explanation in case users see the regression in Qt5.12 tooltips: their texts are seen to be rich by Qt5.12, even when they aren't so (in most programs, they aren't) and so, they're broken into two or more lines. For example, you might see a tooltiip with 4 lines when putting the cursor over a file in pcmanfm-qt or, in the case of Panel's taskbar, this ugliness:

![taskbar](https://user-images.githubusercontent.com/981076/50708221-ce9c9900-1078-11e9-8dfb-c0e71b83f4c9.png)

There's a simple workaround but I don't think it's worth the effort because it should be done everywhere.

**Comment by tsujan** [comment]
Another screenshot that shows the problem with Panel more clearly:

![ugly](https://user-images.githubusercontent.com/981076/50708724-9433fb80-107a-11e9-8a6e-71d6b586a9fc.png)

**Comment by Chiitoo** [comment]
I had not really paid attention to that before now, but I have noticed that tooltips, over panel for example, won't stay out at first, but when I move the mouse just a little bit after them first appearing, they do.

Does that happen to you, too, and is it new as well?

**Comment by tsujan** [comment]
Oh, I see a similar thing (after playing with task-button tooltips): when I move the mouse cursor from a button to another one, the second tootip disappears quickly and I should move the cursor a little for it to show up again.

**Comment by Chiitoo** [comment]
Is that with 5.12.0?  I'm on the current git master for 5.12, so there might be something betwixt that's triggering it for me.  :]

I'll see if I can get to finding out where it starts happening, or if it's something completely different.

**Comment by tsujan** [comment]
> Is that with 5.12.0?

Yes.

> I'll see if I can get to finding out where it starts happening

There are only a few changes in `qtooltip.cpp` and they've caused these problems. One of them is:
```c++
setWordWrap(true);
```
inside `QTipLabel::reuseTip`; its effect is that all texts are considered like rich texts when it comes to wrapping. Previously, it was:
```c++
setWordWrap(Qt::mightBeRichText(text));
```
so that, wrapping of plain texts correctly depended on the existence of `\n` in them.

**Comment by kkoehne** [comment]
Note that this will be fixed in 5.12.1 : https://bugreports.qt.io/browse/QTBUG-72568

**Comment by tsujan** [comment]
@kkoehne Thanks for the info!
