### ISSUE TITLE
Missing device label in "removed" notification

### ISSUE THREAD

**Issue by stefonarch** [lxqt/lxqt#1646]
When a removable media gets connected and "show info" is selected in preferences when removing the device the "label" field is empty.

(see screenshots)
##### Expected Behavior

The device label should be shown also on remove action.

recent git version, also on arch 32bit 

![schermata02](https://user-images.githubusercontent.com/10681413/50709477-3a2a3a80-1068-11e9-94a3-590a0afbce5e.png)

![schermata04](https://user-images.githubusercontent.com/10681413/50709475-3991a400-1068-11e9-9a66-c5d6fcae6f6f.png)

**Comment by tsujan** [comment]
Yes, I've noticed that too; don't know if it's an old issue or not.

**Comment by palinek** [comment]
The problem here is that at the time of removal, we don't get the description of the "just removed" device from solid (kf5).

Are we going to store device names on our own (to show it later)?

**Comment by tsujan** [comment]
> Are we going to store device names on our own (to show it later)?

If possible.

**Comment by palinek** [comment]
done in lxqt/lxqt-panel#903

**Comment by stefonarch** [comment]
Works perfectly here thanks!
