### ISSUE TITLE
brightness not remembered

### ISSUE THREAD

**Issue by ghost** [lxqt/lxqt#1647]
starts at maximum brightness every time after boot.. annoying

**Comment by cubetronic** [comment]
"about lxqt" says version 0.13.0

**Comment by tsujan** [comment]
0.13.0 -> May 21, 2018. Now -> Jan, 2019

We haven't had a release for a long time but LXQt was and is being developed actively. If you want to have fixes as soon as possible, always use the latest git version of LXQt (in your distro).

Anyway, 0.14 will be released soon.
