### ISSUE TITLE
lxqt-runner command list items text color style isn't applied

### ISSUE THREAD

**Issue by micrococo** [lxqt/lxqt#1649]
Hi.

I'm making a new theme and it seems that the command list items color defined in lxqt-runner.qss is ignored. This is the CSS:
```
#commandList::item {
   color: #EFF0F1;
   border: 1px solid transparent;
   margin: 0px;
   padding: 6px;
}

#commandList::item:selected {
   background: #345A6E;
   border-color: #3DAEE9;
   border-radius: 2px;
}
```
And this is the result (it should look like the `#actionButton` menu items):

![lxqt-runner](https://user-images.githubusercontent.com/7717273/50734037-88d6f200-1198-11e9-915b-b4843ac6db8d.jpg)

##### Expected Behavior

The color defined in lxqt-runner.css should be applied.

##### Current Behavior

The color defined in lxqt-runner.css is ignored.

##### Steps to Reproduce (for bugs)

1. Open lxqt-runner
2. Type something so the command list is shown
3. The items text color in the command list should be using the controls defined colors instead of the qss ones

##### Context

It causes visual issues because the text color may be unreadable or have insufficient contrast to be read easily.

##### System Information

* Distribution & Version: openSUSE Tumbleweed version 20181224
* Kernel: 4.19.11
* Qt Version: 5.12.0
* liblxqt Version: 0.13.0+git113.7a2ae47
* Package version: 114

**Comment by stefonarch** [comment]
Can confirm this, it's an old issue, ran into it with my themes too.

**Comment by palinek** [comment]
This is most probably an issue in `LXQt::HtmlDelegate`...

@tsuja You're the style & painting guru, can you have a look into it (https://github.com/lxqt/liblxqt/blob/master/lxqthtmldelegate.cpp#L50)?

**Comment by tsujan** [comment]
@palinek I found the cause a year ago but didn't work on it due to lack of free time; will refresh my memory by reading the code again.

**Comment by palinek** [comment]
Could it be (just a wild guess)?
```diff
diff --git a/lxqthtmldelegate.cpp b/lxqthtmldelegate.cpp
index 2f5535b..80f30df 100644
--- a/lxqthtmldelegate.cpp
+++ b/lxqthtmldelegate.cpp
@@ -100,6 +100,7 @@ void HtmlDelegate::paint(QPainter* painter, const QStyleOptionViewItem& option,
 
     // set text color to red for selected item
     QAbstractTextDocumentLayout::PaintContext ctx;
+    ctx.palette = style->standardPalette();
     if (option.state & QStyle::State_Selected)
     {
         QPalette::ColorGroup colorGroup = (option.state & QStyle::State_Active) ? QPalette::Active : QPalette::Inactive;
```

**Comment by palinek** [comment]
...well just tested... not the `style->standardPalette()`, but the `options->palette` :)... and it seems to work

**Comment by tsujan** [comment]
Will read the code and tell you -- if the solution isn't found until then -- but, in short, if a widget is going to be styled by a stylesheet self-consistently, the methods of the widget style shouldn't be called. In this case, they are `PE_PanelItemViewRow`, `CE_ItemViewItem` and `SE_ItemViewItemText`.

**Comment by tsujan** [comment]
OK, saw the code -- it was familiar -- and found that it's about the lack of `option.features & QStyleOptionViewItem::Alternate` -- at least, part of it. Will investigate further.

**Comment by tsujan** [comment]
I found it; no useful `QPalette::Text` was really defined in the code. This is the modified Runner with a silly stylesheet and a *light* widget style (whose text color is dark, of course -- ignore the text editor in the background; it's a root instance);

![runner](https://user-images.githubusercontent.com/981076/50760459-27d51a00-127d-11e9-8258-0a18023d0416.png)

Will make a PR later.

**Comment by tsujan** [comment]
Or more reasonably:

![runner](https://user-images.githubusercontent.com/981076/50762106-53f29a00-1281-11e9-953b-42c039b21123.png)

We should change LXQt themes after the fix.
