### ISSUE TITLE
New Feature (proposal and code): Bulk rename

### ISSUE THREAD

**Issue by ceever** [lxqt/lxqt#1652]
There is this nice project: https://launchpad.net/nautilus-renamer
I adjusted the code to be more robust for various files list inputs. Also, it supports overwriting now: https://pastebin.com/wZQceGEcI

Put the code into (or elsewhere): /opt/nautilus-renamer.py
Put the following ".desktop" into ~/.local/share/file-manager/actions/ :
<pre>
[Desktop Entry]
Type=Action
TargetToolbar=true
ToolbarLabel=Bulk Rename
Name=Bulk Rename
Profiles=foo;

[X-Action-Profile foo]
Exec=python3 /opt/nautilus-renamer.py %F
</pre>

Restart pcmanfm-qt ... done.

Cheers ...

**Comment by tsujan** [comment]
pcmanfm-qt already has a built-in bulk renamer.

Please tell about such things on the forum. Here is for bug tracking.
