### ISSUE TITLE
Cannot launch desktop files with an Exec key of the form xdg-su -c "<command with parameters>"

### ISSUE THREAD

**Issue by micrococo** [lxqt/lxqt#1653]
I'm not sure whether this is a LXQt issue or not, but when I try to run a program containing an `Exec` key of the form `xdg-su -c "<command with parameters>"`, it fails from both the programs menu and lxqt-runner. For example
```
Exec=xdg-su -c "/sbin/yast2 sw_single"
```
By running the command directly in a terminal I get an error message:
```
> xdg-su -c "/sbin/yast2 sw_single"
> /bin/sh: /sbin/yast2 sw_single: No such file or directory
```
That is the same error that you get if you run `lxqt-sudo "/sbin/yast2 sw_single"`. However, `lxqt-sudo /sbin/yast2 sw_single` (without quotes) works fine. Commands without parameters doesn't have the problem. For example:

```
Exec=/usr/bin/xdg-su -c /sbin/yast2
```
##### Expected Behavior
The command of the desktop file should run.

##### Current Behavior
The command of the desktop file doesn't run.

##### Possible Solution
I don't know. I think it is something related to quotes because it works fine if I remove the quotes around `$cmd` in the line containing `$LXQTSU -s "$cmd"` of the `su_lxqt()` function in the `xdg-su` script. The LXQt sudo dialog shows a different quotation around the command when I remove the aforementioned quotes. For example:
```
Command: '/sbin/yast2 sound'   → xdg-su not modified, it doesn't work
Command: '/sbin/yast2' 'sound' → xdg-su modified, it works
```

##### Steps to Reproduce (for bugs)

This is an example desktop file exhibiting the issue:
```
[Desktop Entry]
Type=Application
Categories=Settings;System;Qt;X-SuSE-YaST;X-SuSE-YaST-Software;

X-KDE-ModuleType=Library
X-KDE-HasReadOnlyMode=true
X-SuSE-YaST-Call=sw_single

X-SuSE-YaST-Group=Software
X-SuSE-YaST-Argument=
X-SuSE-YaST-RootOnly=true
X-SuSE-YaST-AutoInst=
X-SuSE-YaST-Geometry=
X-SuSE-YaST-SortKey=20
X-SuSE-YaST-AutoInstResource=
X-SuSE-YaST-Keywords=software,packages,rpm,repositories,installation,deletion

Icon=yast-sw_single
Exec=xdg-su -c "/sbin/yast2 sw_single"

Name=Software Management
GenericName=Install or remove software packages and manage software repositories
StartupNotify=true
```
##### Context
The problem is that I cannot launch YaST modules from their desktop files. I have to run the control center first and from there the desired module.

##### System Information

* Distribution & Version: openSUSE Tumbleweed version 20190112
* Kernel: 4.19.12-1-default
* Qt Version: 5.12.0
* liblxqt Version: 0.13.0+git115.b3d6d27
* Package version: 115
* xdg-utils version: 20180510-1.1

**Comment by tsujan** [comment]
How can this be an LXQt problem? Try `Exec=lxsudo bash -c "COMMAND"` or something like it.

**Comment by micrococo** [comment]
> How can this be an LXQt problem? Try `Exec=lxsudo bash -c "COMMAND"` or something like it.

Because it works in other desktops (at least in LXDE, Xfce, GNOME, and Plasma). `xdg-su` is used to select the password dialog according to the desktop (`gnome-su`, `kdesu`, ...). Since I didn't know whether it is `lxqt-sudo` or `xdg-su` the one to blame, and it seems to happen only in LXQt, I created this bug report.

The `Exec` command you suggest works, but YaST is a SUSE/openSUSE system configuration tool, so I think that its desktop files are well tested. It's not that I made a desktop file by myself or something. If you think `lxqt-sudo` is OK, then it must be a bug in `xdg-su`. Support for LXQt was introduced not long ago AFAIK.

**Comment by tsujan** [comment]
As far as I know, we don't have control over `xdg-su` or how it may support LXQt. LXQt's privilege program is `lxqt-sudo` and it should work with all GUI apps.

**Comment by micrococo** [comment]
Yes, `xdg-su` is part of the `xdg-utils`¹ package. As I thought, support for LXQt was introduced not long ago and it seems to be a work in process². Maybe someone from the LXQt team could guide them in order to have a better support for LXQt.

[1] https://freedesktop.org/wiki/Software/xdg-utils/
[2] https://cgit.freedesktop.org/xdg/xdg-utils/log/scripts?qt=grep&q=lxqt

**Comment by tsujan** [comment]
> xdg-su is part of the xdg-utils¹ package

It is not.

LXQt had sent a patch to `xdg-utils` and they applied it. The patch was minimal and didn't provide the best LXQt support but it works fine.

However, `xdg-utils` and `xdg-su` are different things and I don't think we have any need for the latter.

**Comment by agaida** [comment]
```
% apt-file search xdg-su                                                                                                                                   :(
apt-file search xdg-su  3,69s user 1,83s system 143% cpu 3,850 total
``` 
so we can stop this finally.

**Comment by micrococo** [comment]
> > xdg-su is part of the xdg-utils¹ package
> 
> It is not.
 
> LXQt had sent a patch to `xdg-utils` and they applied it. The patch was minimal and didn't provide the best LXQt support but it works fine.
> 
> However, `xdg-utils` and `xdg-su` are different things and I don't think we have any need for the latter.

The freedesktop web page was last updated in 2015 and even then I think it wasn't up to date and complete. It is in the code tree and it has been shipped with the package for years (in openSUSE it was included before 2015 for sure). But it doesn't really matter. Now at least I know that it is not `lxqt-sudo` fault, so the bug is correctly closed. Thanks.

**Comment by micrococo** [comment]
> ```
> % apt-file search xdg-su
> :(
> apt-file search xdg-su  3,69s user 1,83s system 143% cpu 3,850 total
> ```
> 
> so we can stop this finally.

OK, it was not my intention to annoy anyone. I just posted the issued with the knowledge I have and I have never used Debian.

**Comment by jubalh** [comment]
@micrococo thanks for you very detailed bug report.

We received this bug in the openSUSE [bugzilla](https://bugzilla.suse.com/show_bug.cgi?id=1120397) some time ago, but I didn't yet have the time to look at it.

**Comment by zimtsui** [comment]
2022 right now, still not working...

**Comment by Barba-Q** [comment]
Theres a patch for this: https://bugzilla.opensuse.org/attachment.cgi?id=836306&action=diff
just remove the quotes from this line in /usr/bin/xdg-su and you're done: $LXQTSU -s "$cmd"

Hopefully this will be implemented some time.

**Comment by Barba-Q** [comment]
Theres a patch for this: https://bugzilla.opensuse.org/attachment.cgi?id=836306&action=diff
just remove the quotes from this line in /usr/bin/xdg-su and you're done: $LXQTSU -s "$cmd"

Hopefully this will be implemented some time.
