### ISSUE TITLE
no option to select/change color-scheme in lxqt appearance

### ISSUE THREAD

**Issue by librewish** [lxqt/lxqt#1655]
lxqt appearance settings has no option to set color scheme  

##### Expected Behavior

the appearance setting should have color-scheme changing option setting
##### Current Behavior
some icons are color-scheme specific like papirus icon theme when set on lxqt dark theme panel items are too dark 
and this happens because of color scheme is breeze light 
 but when color scheme is breezedark panel icons are shown correctly

i set the color scheme by this command

cp -b -f /usr/share/color-schemes/BreathDark.colors ~/.config/kdeglobals 

##### Steps to Reproduce (for bugs)
1.using lxqt on kwin window manager
2.using light colorscheme and lxqt dark theme ,papirus icon theme

##### System Information

* Distribution & Version: manjarowish lxqt-kwin
* Kernel: 4.19.13
* Qt Version: 5.12
* liblxqt Version: latest git
* Package version: latest git

**Comment by tsujan** [comment]
> lxqt appearance settings has no option to set color scheme

And I don't think it will. "Color scheme" is a KDE concept for KDE styles.

**Comment by tsujan** [comment]
I think we really shouldn't add KDE stuff as part of LXQt. Users could use KDE apps/settings in LXQt -- as I do with KWin.

> some icons are color-scheme specific like papirus icon theme when set on lxqt dark theme panel items are too dark

If you have the latest LXQt, you could change the Panel icon theme independently from other apps

@agaida I close this. Feel free to reopen it if you think it's valid.

**Comment by agaida** [comment]
it isn't valid - esp. the colorscheme settings for kwin. there is a kcm module for it - embedded in plasma.
you remember https://github.com/lxqt/lxqt-wm-integration? :smile:

**Comment by tsujan** [comment]
FYI

We can set the window palette in the latest git LXQt now (will be in 0.16). Breeze and Fusion follow it and the other palettes are set by Qt automatically. So, KDE "color schemes" don't apply to LXQt anymore.
