### ISSUE TITLE
[Homepage of LXQT] suggested Build Order 

### ISSUE THREAD

**Issue by rubyFeedback** [lxqt/lxqt#1659]
I was reading the recent blog entry, and there was a link to this page:

https://forum.lxqt.org/t/build-order-release-plan-0-14-0/292

That page has the suggested Build Order, along these lines:

libqtxdg 
qps
lxqt-build-tools
screengrab

And so on. It confuses me a bit though.

Have a look at this FTP listing that you lxqt-folks also offer:

https://downloads.lxqt.org/current.html

To me, the order on the page current.html seems simpler;
I also already compiled lxqt from source according to the 
current.html page.

My suggestion would be to, no matter which way you guys
go with, to be consistent. My personal recommendation 
would be to mirror both in the very same manner, ideally
in the exact order that current.html shows (since that is
the one I am using right now, and this one actually
works; perhaps the other one works too but I have not
yet tried it).

The reason why I would suggest to use the same recommendation
everywhere is because otherwise people may get a bit confused.

Right now the only page that confuses me is the listing on
https://forum.lxqt.org/t/build-order-release-plan-0-14-0/292, but I
believe either way, making the suggestions coming from the lxqt
team directly consistent (and recommended), would be the
best solution in the long run.

Thanks and feel free to close this issue if you feel it is not worth
to resolve (which may be the case since it is quite minor too; I
just think it would be better to be consistent and recommend
the same build order, even if it may not be a linear one, it may
still be the "best" as in the most recommended one - people can
deviate from it on their own anyway; so I see it more as a "best
practice" guideline. I will stick with current.html since I know that
this one works).

**Comment by agaida** [comment]
![](https://www.pioneermilitaryloans.com/~/media/images/desktop/content/valiant-voices/h-l-mencken-2.ashx)

**Comment by tsujan** [comment]
It's here: https://github.com/lxqt/lxqt/wiki/Building-from-source

Those who are familiar with the sources can change the order.

**Comment by agaida** [comment]
@tsujan - and it's mentioned in the release notes - so what,

**Comment by tsujan** [comment]
And about "simple solutions for complex problems". I like the quote but this is also correct:

For every complex problem, search for an answer whose logic is simple, although you might find nothing.
