### ISSUE TITLE
Notification icon doesn't update

### ISSUE THREAD

**Issue by drum445** [lxqt/lxqt#1660]
When an application shows notifications the first image is used for all said app's notifications.
This is a problem when something like spotify is showing what song is being played, as it will only show the album art  of the first song played for all future songs - presumably it's cached on first display.

Version: 0.13

**Comment by stefonarch** [comment]
Using clementine and a playlist with different artist all covers displayed in the notifications are correct and change. So this looks like related to spotify?

**Comment by drum445** [comment]
@stefonarch just checked clementine and yes it's working as expected, something wrong with spotify by the looks. Spotify doesn't have this problem on other DEs however

Cheers

**Comment by agaida** [comment]
It's easy - not filled out issue form, no processing.

**Comment by drum445** [comment]
@agaida Yes my mistake, but you don't have to be so flippant about it. I just won't bother posting issues next time.

Awful attitude.

**Comment by tsujan** [comment]
> Awful attitude.

Awful report; as if we're spotify's devs and should make magic.

**Comment by tsujan** [comment]
@drum445 Please understand our situation! We should attend to so many reports. Descriptions like "When an application shows notifications..." waste time.

And please don't mistake closing of a report for an insult; if it was so, I'd have insulted myself several times ;)
