### ISSUE TITLE
pcmanfm-qt: Annoying "Root Instance" bar should be optional

### ISSUE THREAD

**Issue by imrn** [lxqt/lxqt#1661]
It is clearly annoying and distracting for advanced users. It also wastes
screen space. Please make it optional so that I can be turned off by
those who doesn't want it.

**Comment by agaida** [comment]
nope

**Comment by tsujan** [comment]
> It also wastes screen space.

Sorry that your precious screen space is wasted by that thin strip but if you use the root instance often, you might have mistaken Linux with MS Windows.

Anyway, not only that bar won't be removed but also it might be added to root instances of other LXQt apps.

**Comment by imrn** [comment]
> Sorry that your precious screen space is wasted by that thin strip but if
> you use the root instance often, you might have mistaken Linux with MS Windows.
> Anyway, not only that bar won't be removed but also it might be added to
> root instances of other LXQt apps.

I've already got your point. But probably I'm one of few who wouldn't need
such an advice. Note that, I kicked MS windows more than 15+ years ago
and my main reason for the migration was it's unnecessary and unreliable
interventions to my actions. I hope, lx** would not want go down the same
road of forced baby sitting. Ironically, that may only work for windows users.

**Comment by tsujan** [comment]
> I hope, lx** would not want go down the same road of forced baby sitting.

It won't. A simple red strip isn't something you want to worry about. Advance users often don't need to use root instances of file managers either.

**Comment by imrn** [comment]
> Advance users often don't need to use root instances of file managers either.
Agreed. But it is not something that can be decided by pcmanfm.
Do you have any bold red strip reading "Warning you are in control. Drive responsibly."
on our car's windshield? I guess comparing possible consequences of driving and
root access is not needed. Or is it?

**Comment by agaida** [comment]
I don't know if i count as experienced user - but i really appreciate the reminder if a graphical application with elevated rights is open. And this reminder should not be optional.

**Comment by imrn** [comment]
I've read the strip. ;)
