### ISSUE TITLE
[Feature request] Button to reset to default settings

### ISSUE THREAD

**Issue by moliss** [lxqt/lxqt#1662]
I accidentally imported my openbox configuration and now my Firefox windows are still themed and changing the theme in either the lxqt or openbox settings doesn't work. I wish I could reset to default so I can see what lxqt would look like without modification.

**Comment by moliss** [comment]
I just realized how to fix it. I had not noticed that the LXDE "Customize Look and Feel" menu exists alongside the LXDE Appearance Settings, at least in my installation. This seems kind of confusing and I still have no way to get the default values.

**Comment by tsujan** [comment]
First, this isn't LXDE. Second,.. forget it.

**Comment by moliss** [comment]
I was implying that a similar menu as LXDE existed inside my LXQT installation. I no longer need this feature as I figured out how to work the program, but would it have been hard to implement?
