### ISSUE TITLE
Unable to change volume from lxqt-panel

### ISSUE THREAD

**Issue by lephonet** [lxqt/lxqt#1665]
##### Expected Behavior

Volume changes when I move the slider up or down

##### Current Behavior

It doesn't change the volume at all

##### Steps to Reproduce (for bugs)

1. Click on an empty space between the clock and the battery icon on the panel
2. move the volume slider up or down
3. 
4. 

##### Context

I installed lxqt on a Samsung Chromebook running archlinux and encountered some problems while doing so.
I've managed to change the audio with these instructions https://archlinuxarm.org/platforms/armv7/samsung/samsung-chromebook but it requires a terminal to use alsamixer.

##### System Information

* Distribution & Version: Arch Linux ARM armv7l
* Kernel: Linux alarm 4.20.5-1-ARCH
* Qt Version: 5.12.0
* liblxqt Version: community/liblxqt 0.13.0-1
* Package version: 0.13.0

**Comment by tsujan** [comment]
Not reproducible.  The latest LXQt is 0.14.

**Comment by agaida** [comment]
one should select the right sound source to manage - and in case of alsa configure it right. Downstream or user problem.
