### ISSUE TITLE
missing Qt-native Unicode character map application

### ISSUE THREAD

**Issue by ziep** [lxqt/lxqt#1666]
LXQt should have a Qt-based Unicode character map application.

A desktop operating system needs some application to choose occasionally needed characters that are not available on the hardware keyboard.

##### Currently,
we are missing a good option for LXQt: LXQt users are depending on _GNOME Character Map_ aka _gucharmap_ which is GTK+ (see e.g. dependency in Debian package <code>lxqt</code>), _GNOME Characters_ is GNOME, _KCharSelect_ has extensive KDE dependencies, the rest is not even open source – except maybe for this code example from the Qt docs: https://doc.qt.io/qt-5/qtwidgets-widgets-charactermap-example.html

##### LXQT needs
an application like gucharmap, except based on Qt instead of GTK+.

**Comment by tsujan** [comment]
LXQt "should" have a Unicode character map app/audio player/office suite/browser/... No,it shouldn't! LXQt isn't an app suite. If there is a good app, whether it is written in GTK+ or in Qt, you could use it in LXQt.

**Comment by agaida** [comment]
thanks :)
