### ISSUE TITLE
PCmanfm-qt doesn't respect folder settings sometimes

### ISSUE THREAD

**Issue by stefonarch** [lxqt/lxqt#1668]
Under some circumstances Pcmanfm-qt shows always hidden files on opening the home, which is set to "remember settings for this folder", detailed list, folders first, sort by name. 
Ctrl+h and closing doesn't change nothing - next time it opens again with hidden files shown. 
Only way to fix it is to unset  "remember", hit ctrl+h and reset it to "remember".
##### Expected Behavior

It should never change the remembered display settings by itself.
##### Current Behavior

In some circumstances it does, see below

##### Steps to Reproduce (for bugs)

Finally I think I've found how to reproduce:
1. set home directory in pcmanfm-qt to "remember display for this folder"
2. move to some subfolder
3. hit cltr+h to show hidden files
4. close and reopen it.

* Distribution & Version: 
arch+ latest LXQt from git

**Comment by tsujan** [comment]
> 2. move to some subfolder

Why should the setting change when you go to its subfolder? Try to toggle it inside the custom folder itself and report back.

**Comment by stefonarch** [comment]
Read above. Example: going to a server over  ftp, show hidden files to modify .htaccess, close pcmanfm-qt. and it has  changed the settings for the home folder forever to "show hidden files" until you unset "remember".

**Comment by tsujan** [comment]
For now, I can't test the official source -- mine is patched and doesn't have this problem -- but will do so tonight. However, I won't be surprised if the problem exists because I found similar issues in the official source (like https://github.com/lxqt/pcmanfm-qt/issues/887).

**Comment by tsujan** [comment]
Investigated. This has the same cause as https://github.com/lxqt/pcmanfm-qt/issues/887 (showing hidden files is done by `ProxyFolderModel`, which also sorts items). Please follow that report!

Soon, I'll make a PR to fix all sorting issues. I've made a patch with the correct logic but should first test it under various circumstances.

**Comment by tsujan** [comment]
@stefonarch I'd appreciate it if you could test https://github.com/lxqt/pcmanfm-qt/pull/906 before it's merged.

**Comment by stefonarch** [comment]
Looks good, this bug here is fixed in branch sort_logic. But it remembers "show hidden files" per folder also if not checked "remember for this folder", not sure if there is now any difference between checking this option or not...

 Is there other behavior to test?

**Comment by tsujan** [comment]
> But it remembers "show hidden files" per folder also if not checked "remember for this folder",

If the folder is customized, showing hidden files inside it will be (remembered) only for it and not for other folders.

If the folder is *not* customized, showing hidden files inside it will be (remembered) for all *ordinary* folders but not for customized ones. That's the case with other sorting properties too.

This is the most logical behavior when we have special folders, which we call "customized" and for which that checkbox is checked.

> Is there other behavior to test?

Nothing more comes to my mind. Thanks a lot for testing!

**Comment by stefonarch** [comment]
Yes I see, only "show hidden" is remembered, other display settings turn to defaults.
Btw LXQt 0.14 is in arch32 repo now :)

**Comment by tsujan** [comment]
All sort settings have the same behavior. View settings are different. PCMan decided to change them for ordinary folders only from Preferences and I think that's a good decision. An old discussion, anyhow...

**Comment by tsujan** [comment]
BTW, I started to suppress may stubbornness, forget about my patch and use PCMan's per-folder design. As far as I see, it works like a charm but, from now on, if there is a bug in it, I'll see it firsthand :)

The only thing I've added here is removal of deleted folders from the list on quitting. I might make a PR if a user complains about it but, IMO, it isn't important in practice.
