### ISSUE TITLE
Option to force lxqt-leave --suspend

### ISSUE THREAD

**Issue by tanius** [lxqt/lxqt#1669]
When executing `lxqt-leave --suspend`, it currently displays a confirmation dialog:

> Do you want to really suspend your computer?
> 
> Suspends the computer into a low power state. System state is not preserved of the power is lost.
> 
> <kbd>Yes</kbd> <kbd>No</kbd>

However for custom menu entries, custom shortcuts or scripting application (like [this](https://askubuntu.com/a/1117018)) it would be great to also have a variant without that dialog, suspending the computer immediately.

As a proposal, it could be accessed with `lxqt-leave --suspend-now` or maybe `lxqt-leave --suspend -y`.

**Comment by stefonarch** [comment]
You missed the checkbox "session settings > ask for confirmation".

Have to check the english string - in italian it says about "leaving session" which is not quite right in the case of suspend or hibernate.

**Comment by tanius** [comment]
Yes right, I missed that, and indeed it prevents the confirmation dialog for both logout and suspend / hibernate (I just tested it).

The English string is "Ask for confirmation to leave session", so that would be something to adapt :)

I think a way to override that setting with a command line option for `lxqt-leave` would still make sense, but it's a minor point. Just unchecking that is a workable solution for me already.
