### ISSUE TITLE
Distribute as Snap package

### ISSUE THREAD

**Issue by cunidev** [lxqt/lxqt#1670]
Having an official Snapcraft package for the LXQT desktop would allow for a faster distribution of LXQT on potentially any distro, as happens currently with KDE: https://community.kde.org/Plasma/Snap

**Comment by tsujan** [comment]
Thanks for the info but, here, we don't make installable packages.

@agaida If I'm right, please close it.

**Comment by jubalh** [comment]
I don't see any benefit in this.

LXQt is in most, if not all, major distros. So I don't think we have a problem with adoption.

As for some distros having older versions, if you prefer having the latest you need to use rolling release distros.

**Comment by tsujan** [comment]
I agree.

Even if there was a motivation, who would want to do it? I don't think any of us has time for it.

**Comment by agaida** [comment]
thanks, just came home from work - and i fully aggree

**Comment by tsujan** [comment]
> btw, the idea is not exactly new

Excellent memory!
