### ISSUE TITLE
Some translation bugs global short keys dont wana close on 'sluiten' button

### ISSUE THREAD

**Issue by ringo32** [lxqt/lxqt#1674]
##### Expected Behavior
If i want to make a short key, that works, but if i want to close with 'sluiten' it should close the window.
I notice Lxqt-aprereance and session the button is stil in english also with lxqt-about and other lxqt apps is stil in english also 'close' that works.

with Global keys set to sluiten does not work, some translaten path what ever bug ?

##### Current Behavior

If i press sluiten, it does not close the window i have to use the corner decoration 'x' button

Translations also bit mixed up, generaly it uses the close as in english only shortkeys has dutch translation

##### Possible Solution

Dont know, some link to translation has some bug ?

##### Steps to Reproduce (for bugs)

I use antergos/arch in dutch language so i dont know if in other language also got..

##### Context

is not that i boder about just want to note it for sure.

##### System Information

screenshot : https://i.imgur.com/MvUr2aE.jpg

you see short keys  named sluiten , but probably is on the shortkey, because if i make a screenshot with lximage-qt and there is also sluiten it do work on that.

**Comment by tsujan** [comment]
I didn't understand the language used in this report but: Is qt5-translations installed?

**Comment by ringo32** [comment]
i checked but seems not installed but stil got it here a gif : https://i.imgur.com/rYSpysF.gif

**Comment by tsujan** [comment]
> i checked but seems not installed

You can't expect localization to work correctly without `qt5-translations`.

**Comment by ringo32** [comment]
after install & boot also ?

**Comment by tsujan** [comment]
A log-out and log-in should be enough after installing `qt5-translations`.

**Comment by ringo32** [comment]
ok  shall try to dig, runnig from terminal didnt gave something :)  i did just a reboot to make sure. Have too look for stuf i gues.
hopefully clear the info

**Comment by agaida** [comment]
@tsujan - we should really fix it :sunglasses: 

try `LANG=nl_NL.utf-8 lxqt-config-globalkeyshortcuts`
try `LANG=de_DE.utf-8 lxqt-config-globalkeyshortcuts`

after please try 
`LANG=nl_NL.utf-8 lxqt-config-file-associations`
`LANG=de_DE.utf-8 lxqt-config-file-associations`

maybe the close button should really send a close ...

**Comment by ringo32** [comment]
shall try

**Comment by tsujan** [comment]
@agaida All of them work fine here. Tearing my hair out over translations... they've always worked for me but not for others!

**Comment by agaida** [comment]
hmm - maybe we should diff your sources and the git ones

**Comment by ringo32** [comment]
https://i.imgur.com/yXkf58O.gif   translation seems worked better on the buttons  but it doesnt close , as on apereance it keeps say close  most applications buttons are in english but further translation is dutch

**Comment by ringo32** [comment]
Mayby a in future a -d debug options would be awesome.

**Comment by tsujan** [comment]
@agaida I received a report about FeatherPad too! And with German! I checked the German translation and it worked OK. They said it was "fixed" in the latest version (I'd removed lots of shortcut translations and used keys instead) but not when they used a command-line (I don't remember what it was).

It's too confusing to me when I can't reproduce it -- actually, never.

**Comment by ringo32** [comment]
for featherpad it hold up on the translation also  its correct  'sluiten' and 'afsluiten'  the working of translations works here as it should

**Comment by agaida** [comment]
and i don't understand the slot close() in the ui file - can't we define a Qt$fooButton::Close or so?

**Comment by tsujan** [comment]
> and i don't understand the slot close() in the ui file

It's correct; it's what Qt Designer provides. I have a bad habit of not using these functionalities of Qt Designer in my apps but they should work regardless of the localization.

**Comment by ringo32** [comment]
is just translations in globalshortkeys config is ok and featherpad on other like session the button most of it is enlgish but it works only shortkey does not work closing button
is not big deal but stil :)

**Comment by agaida** [comment]
@tsujan - yeah, should work, just read the documentation

**Comment by tsujan** [comment]
> and featherpad on other like session the button most of it is enlgish

@ringo32

It shouldn't be in English if you use the Dutch localization. In FeatherPad, `Close` is translated into `Sluiten`:

![dutch](https://user-images.githubusercontent.com/981076/52812385-9000f200-30ac-11e9-80d3-8e42daa1111a.png)

Something may be missing on your system.

**Comment by ringo32** [comment]
i mean transmlation in global short keys and featherpad is correct, so dutch local ( nl_BE )  but other like lxqt-appereance openbox-settings lxqt-config-session  the buttons are Close. but the buttons works atleast pcmanfm-qt looks good but if you like install new-theme from openbox-settings it has also the english button translation on that file screen  https://i.imgur.com/ue9EyG6.jpg    is bit mixed.  lximage-qt have also good translations

**Comment by tsujan** [comment]
> i mean transmlation in global short keys and featherpad is correct

OK. I'm happy to know that. If you found a problem with FeatherPad's Dutch translation, please report it at FeatherPad's GitHub page!

Actually, I found a problem with `Alt+pijltje omlaag` and `Alt+pijltje omhoog` in FeatherPad but that may be because I don't have Dutch keyboard layout here.

**Comment by ringo32** [comment]
i dont know what that do, only notice short keys f featherpad translation , alt-b    'bestand' is file, in english is like file and , Bewerken is like edit, if you do alt it underline b Bestand and Bewerken , if you do alt-b it open the submenu of bewerken.  but alt-arrow up or down i dont know what it does ?

**Comment by ringo32** [comment]
but main issue is just the button dont work

**Comment by agaida** [comment]
lxqt/lxqt-globalkeys/issues/107 to continue
