### ISSUE TITLE
Lximage-qt auto-save to a screenshot map when send screenshot

### ISSUE THREAD

**Issue by ringo32** [lxqt/lxqt#1675]
##### Expected Behavior
When send a screenshot is handy if it auto-save the picture on configured place you config.
Since screenshot of lximage-qt need to save first before you can use a service like imgure

##### Current Behavior

you take a screenshot you have to save it first manually to a map of liking the you can upload a picture to a Service.

##### Possible Solution

Make the upload service also make auto-save, when you push the button it auto-save when you selected on Preferences and set a save mapwhere the picture comes in. 
If you dont want that then you dont need to check it that the option works manual, but when option enabled auto-save it save the picture on your set map  en set prefered format. but auto-save files get mostly like scrot, or screenshots-date-time.jpg or set wat you set.

##### Context

Is more handy if it can auto save, if its not saved upload dont work when manual it works.

**Comment by agaida** [comment]
Thanks for the reminder, we should really fix it.

**Comment by tsujan** [comment]
Done in https://github.com/lxqt/lximage-qt/commit/b337344b95d4a902b2a0c09e6d27ce70cce816e4

BTW, if good reports are buried under bad ones -- as is the case with https://github.com/lxqt/lxqt/issues -- the bug tracker will be useless. I've prevented that in https://github.com/lxqt/pcmanfm-qt/issues. Maybe, this one could be rescued too.
