### ISSUE TITLE
Search in mainmenu is slower since last lxqt update.

### ISSUE THREAD

**Issue by githubtefo** [lxqt/lxqt#1676]
Since the last big update in Arch, when I search an application in the mainmenu, it takes some time to show the results and introduce the text in comparison to the previous version (it was immediately).

##### Steps to Reproduce (for bugs)

1. Open the main menu
2. Type some text
3. Wait a couple of seconds to see the text typed.
4. See the search results

##### System Information

* Distribution & Version: Arch Linux.
* Kernel: 4.19.4
* Qt Version: 
* liblxqt Version: 0.14.0-1
* Package version: lxqt-panel-0.14.0-1

**Comment by tsujan** [comment]
If it was reproducible, one of us would know. Incomplete upgrade?

**Comment by githubtefo** [comment]
All of the lxqt packages seems to be up to date (https://www.archlinux.org/groups/x86_64/lxqt/) as same as in my laptop.
It looks more like a performance issue for me between one version and the other, given I am using an intel atom netbook.

**Comment by tsujan** [comment]
> All of the lxqt packages seems to be up to date (https://www.archlinux.org/groups/x86_64/lxqt/) as same as in my laptop.

That list doesn't contain important components like `liblxqt`, `libqtxdg`, ...

**Comment by githubtefo** [comment]
I see. I checked those two that you mentioned and are updated to 0.14.0-1 and 3.3.0-2 respectively.
I will wait a couple of months to see if the behaviour changes.

**Comment by tsujan** [comment]
> I will wait a couple of months to see if the behaviour changes.

There's no need to wait at all. If you log out and log in after upgrade and see a delayed filtering, the problem exists and won't disappear by itself.

How many items do you have inside `/usr/share/applications` and `~/.local/share/applications`?

**Comment by githubtefo** [comment]
I have 110 items in /usr/share/applications and 28 in ~/.local/share/applications

I tried lxqt-runner and this works fine as before the updates. So I can go back to use it instead of the mainmenu search.

**Comment by tsujan** [comment]
> I have 110 items in /usr/share/applications and 28 in ~/.local/share/applications

Then, the search itself should be immediate in your case; I guess the delay you see may be related to GUI updates.

**Comment by tsujan** [comment]
I close this old report for 2 reasons:

 * It's not reproducible.
 * The reported "delay" may be just about the fact that the search starts only when the user stops typing: a feature that was implemented for not taking the CPU time needlessly.
