### ISSUE TITLE
username as display for homedir icon 

### ISSUE THREAD

**Issue by agaida** [lxqt/lxqt#1677]
Only an idea  "Benutzerverzeichnis" look fugly

![](https://i.imgur.com/lu9IPzi.png)
 
@tsujan - what do you think - a plus would be that the same name as in pcmanfm-qt is used for the place

**Comment by tsujan** [comment]
I have nothing against user name instead of "Home". Assign me to it if that's more logical.

**Comment by agaida** [comment]
logical not, but more consistent - and it will not need any translation that can/will be to long :sunglasses:

**Comment by agaida** [comment]
![](https://i.imgur.com/pIXiqy0.png)

perfect :D
