### ISSUE TITLE
[feature request] The menu items of the taskbar allow you to manage the position of the windows.

### ISSUE THREAD

**Issue by Cybermaxrus** [lxqt/lxqt#1678]
It would be convenient to have menu items that allow different windows to be arranged: horizontally, vertically, or cascade.
https://static.techspot.com/articles-info/226/cascade-menu.jpg

**Comment by agaida** [comment]
That's strictly a WM task - so, no.

**Comment by Vladimir-csp** [comment]
NetWM/EWMH compatible WMs can be governed via external tools. Like [x-tile](https://www.giuspen.com/x-tile/), or scripting via wmctrl.

**Comment by agaida** [comment]
https://tracker.debian.org/pkg/x-tile ...
