### ISSUE TITLE
Tag some point releases

### ISSUE THREAD

**Issue by agaida** [lxqt/lxqt#1681]
functional updates

* [x] libqtxdg
* [x] liblxqt
* [x] libfm-qt
* [x] lxqt-config
* [x] lxqt-globalkeys
* [x] lxqt-runner
* [x] lxqt-sudo
* [x] pcmanfm-qt

translation only updates:

* [x] compton-conf  
* [x] lximage-qt  
* [x] lxqt-about 
* [x] lxqt-admin  
* [x] lxqt-notificationd   
* [x] lxqt-openssh-askpass  
* [x] lxqt-panel  
* [x] lxqt-policykit 
* [x] lxqt-powermanagement 
* [x] lxqt-session  
* [x] obconf-qt  
* [x] pavucontrol-qt  
* [x] qps
* [x] qterminal  
* [x] qtermwidget  
* [x] screengrab

**Comment by agaida** [comment]
All packages tagged and tarballs uploaded to gitub

downloads.lxqt.org and and release notes will follow tomorrow

**Comment by rubyFeedback** [comment]
Ah - I was already wondering why e. g. distrowatch tracked it and github had the links but the website at lxqt.org would not. That delay was a bit confusing (to me).

**Comment by agaida** [comment]
done
