### ISSUE TITLE
Lxqt 0.14 all icons with exclamation mark

### ISSUE THREAD

**Issue by hifi25nl** [lxqt/lxqt#1682]
After the last update of lxqt to version 0.14 all application icons and shortcuts on Desktop and other folders are with an exclamation mark.
Application icons in /usr/share/applications are fine.

My archlinux system is fully updated.
The same is happening in another system with both Plasma and lxqt. In plasma icons are fine, in lxqt not.
So this is a specific problem of lxqt.

What I have already tried:
1) Change theme and icon set
2) Editing the application shortcuts trying various parameters
3) Installing pcmanfm-qt git version
4) Removing both lxqt and pcmanfm-qt configuration

Nothing seems to fix the problem.

**Comment by tsujan** [comment]
"exclamation mark" is just an icon (emblem) in your icon set and indicates that you haven't trusted those files explicitly by right clicking on them. Either upgrade to 14.1 or:

(1) Uncheck Preferences → Launch executable files without prompt;
(2) Restart pcmanfm-qt; and
(3) Right click on those files and trust them once for all.

The above-mentioned option (about promptless launch) might be removed in a future version of pcmanfm-qt.

**Comment by chriva** [comment]
Everyone says the same thing. "Uncheck launch executable files without prompt" and right click on said icons to allow them. There is no such option in the context menus! And what about that annoying "Root instance" nag in the file manager? All I do is stuff that requires root access on my machines. The _ONLY_ thing. This madness has gone too far. If users wreck their machines it's their fault and their fault only.

**Comment by tsujan** [comment]
In the same spirit:

> There is no such option in the context menus!

Intentionally hidden to annoy users.

> And what about that annoying "Root instance" nag in the file manager?

Read below.

> This madness has gone too far.

It'll go further.

Thanks for sharing your wisdom!

**Comment by agaida** [comment]
@tsujan - you are far to sarcastic - do you really think that someone who is in need of a graphical environment to do root stuff will understand you?
@chriva do you really think we will change our mind because your message? And if you need someone to blame - it was my decision not to make the root notification optional. And i'm still convinced that it was the right decision - we allow to do such things and not limit them, but the big red bar should remind people to close the root window as soon as possible.

**Comment by agaida** [comment]
Not so nice - we really should adjust showing of the emblems - esp in pcmanfm-qt/applications - it is misleading at best

**Comment by tsujan** [comment]
> esp in pcmanfm-qt/applications

Good point! Why didn't you tell me before? I never use Applications because it's based on menu-cache and I don't like menu-cache running here. Will remove the emblem in that place later -- very busy with another code now...

**Comment by agaida** [comment]
my bad, i mentioned it one or two years ago, but was not verbose of

**Comment by tsujan** [comment]
Emblems shouldn't be there... It's menu-cached's fault ;)

BTW, I should really replace menu-cached at some point (https://github.com/lxqt/libfm-qt/issues/417).

**Comment by agaida** [comment]
yes - please :D

**Comment by tsujan** [comment]
@agaida It's done in https://github.com/lxqt/libfm-qt/pull/455. Three kinds of places are excluded -- "Applications" is one of them. Please test it thoroughly!

**Comment by agaida** [comment]
@tsujan - the handling of the exclamation marks is perfect now imho - the handling of places no, will write a new bug

**Comment by tsujan** [comment]
> the handling of places no

Disagreed -- left a comment there.
