### ISSUE TITLE
Welcome to LXQt - Please select your default Window Manager 

### ISSUE THREAD

**Issue by tirafesi** [lxqt/lxqt#1684]
I’m trying to install LXQt, but I cannot.

I tried it on Ubuntu, I tried it on Kubuntu and I tried it on Lubuntu. They all had the exact same problem! (all version 18.04.2)

Here’s how I installed it:

1. sudo apt-get install lxqt
2. Logout
3. Select LXQt Desktop
4. Login

After step 4, I’m met with [this](https://forum.lxqt.org/uploads/default/original/1X/269ac4a961c9026f3dbd4f87287d8be5166c9c02.png) window.

How can I solve this? All I want is to get the look of Lubuntu 18.10 on other OS versions >_<

I’m using Virtualbox in case it matters.

**Comment by tsujan** [comment]
If I were you, I'd say to myself, "Lesson learned! I won't use Ubuntu."

Ubuntu problems should be reported to Ubuntu.

**Comment by jubalh** [comment]
Hahaha :-)
While I agree with @tsujan, I have to say: This is not a real issue @tirafesi. You just didn't install a Window Manager, like the dialog clearly states.
So what you should do is install for example Openbox, Kwim, xfwm. Once you have installed it you can select it in this dialog.

If you want Lubuntu look and feel then you shouldn't ask us, you should ask Lubuntu guys how they changed theme and what they installed.

**Comment by tirafesi** [comment]
@jubalh But I did install a window manager... I tried both open box and kwin and none of them showed on that dialog. I followed every single guide I found on google on how to install lxqt and the result is always the same >_<

As for asking to lubuntu, I already did, and the answer I was given was *lubuntu does not officially support lxqt*...

**Comment by stefonarch** [comment]
The problem here is that ubuntu also doesn't ship  _any_ settings... 
there is a panel without elements at the bottom. So after installing openbox or else click at the bottom, the panel settings should show up, add widgets/elements (menu, systray, volume and so on). From the menu you can costumize all settings.

**Comment by jubalh** [comment]
@tirafesi then it is clear to me: dont use Lubuntu :-)

Use Debian, openSUSE, Arch, Gentoo.

**Comment by agaida** [comment]
Erm - not that true, the Lubuntu team don't support upgrading from Lubuntu LTS to later versions nor "switching" from LXDE to LXQt. Both reasonable. Thats all, nothing to see here.

**Comment by gsbhasin123** [comment]
In the file chooser dialog, choose /etc/X11/default-display-manager. Or try sudo apt install lubuntu-qt-desktop. Or try Lubuntu 19.04

**Comment by droidkita** [comment]
ubuntu上の問題なら、Ubuntuの提供先に問い合わせるべきじゃないの？
Debianは、全く問題ない。

**Comment by zcrayfish** [comment]
> ubuntu上の問題なら、Ubuntuの提供先に問い合わせるべきじゃないの？
> Debianは、全く問題ない。

Please check the dates on the comment(s) you are replying to.

**Comment by droidkita** [comment]
５年前の事だから、
放置して良いのでは？
