### ISSUE TITLE
[feature request]lxqt-infocenter something like kinfocenter

### ISSUE THREAD

**Issue by librewish** [lxqt/lxqt#1686]
i have installed kinfocenter in lxqt but it does not show up in lxqt although it may show up in lxqt if i edit . desktop file
but we should also have an info center which gives system information graphical way like kinfocenter.
i know inxi gives all the info about system but its cli.

**Comment by tsujan** [comment]
> i have installed kinfocenter in lxqt but it does not show up in lxqt

It shouldn't and you already know why.

> but we should also have an info center

Disagree. `kinfocenter` shows a small part of the info that can be gathered. There's a huge amount of commands for finding various info and they can't be included in any GUI. Does `kinfocenter` show you which I/O scheduler you use? The best way of finding relevant info is using relevant commands. Moreover, there are other GUI apps for various kinds of info.

LXQt isn't supposed to be an app suite.
