### ISSUE TITLE
Columns of lxqt-config-globalkeyshortcuts are a mess

### ISSUE THREAD

**Issue by tsujan** [lxqt/lxqt#1688]
I intentionally took this screenshot with Breeze to show that the problem is independent of the widget style:

![shortcuts](https://user-images.githubusercontent.com/981076/54074931-11176780-42ae-11e9-8882-58e63126f364.png)

The info column is a mess because its texts are multi-line, instead of being elided. Of course, they become OK if the window width is made bigger.

**Comment by tsujan** [comment]
Actually, the problem isn't limited to the last column but is more visible there.

**Comment by stefonarch** [comment]
Another annoying thing is that the window does not remember the sizes of columns, one can arrange them to  a clear look (shortcuts can be small and so on).
Here it opens always like this:
![schermata-09-22-30-27](https://user-images.githubusercontent.com/10681413/54077597-fac3d880-42ba-11e9-9632-3915219c0c3c.png)
and reopening all is lost.

**Comment by tsujan** [comment]
> Another annoying thing is that the window does not remember the sizes of columns

Right! I noticed that too. IMO, columns should fit their longest texts (but not if its too long) -- no need to remember column sizes in this kind of GUI, IMO.

**Comment by tsujan** [comment]
It was caused by small mistakes: https://github.com/lxqt/lxqt-globalkeys/pull/114
