### ISSUE TITLE
Pcmanfm-qt opens not in focus

### ISSUE THREAD

**Issue by stefonarch** [lxqt/lxqt#1695]
When opening pcmanfm-qt by shortcut (alt+p here) it opens transparent and doesn't receive focus, so I have to click the window. 

It doesn't happen opening it from the menu or lxqt-runner.
It happens only when compton is running.
It happens only with pcmanfm-qt, other apps open regularly.
Window manager is openbox, it happens on laptop with arch 32bit packages and latest git checkout on two different machines.

##### Expected Behavior

There should be not difference how pcmanfm is opened.
##### Current Behavior

Opening with shortcut it is not focused.

##### Steps to Reproduce (for bugs)

1. assign a shortcut for pcmanfm-qt
2. activate compton in session settings, 
3. dim inactive windows with transparency in compton settings
3. use the shortcut

##### System Information

* Distribution & Version: arch 32bit packets | 64 bit arch & git checkout

**Comment by tsujan** [comment]
Confirmed.

Focusing on showing is a piece of cake but, first, I should see what's different here and why it only happens when a shortcut is used.

**Comment by tsujan** [comment]
BTW, it isn't related to Openbox or compton.

**Comment by tsujan** [comment]
Back to this:

It's about what they call "focus stealing prevention". Minutes ago, I changed it to "None" in KWin and the window was focused with shortcut.

Why is pcmanfm-qt different from other apps? It isn't different; it's already running, drawing the desktop on all virtual desktops. If you stop its process and press the shortcut, its behavior will be like other apps -- at least it's so with KWin.

Why does "focus stealing prevention" have such a behavior with shortcuts. Frankly, I didn't find it interesting enough to search for the reason in jungles of WM codes.

Having removed the "enhancement" tag, I leave the decision to @agaida: Should I enforce the focus in the code?

**Comment by agaida** [comment]
erm - no, imho. But if you do, make it optional please. Maybe wrong - but what happend is: one open a window for an already running application - so the focus will remain on the active window if focus stealing prevention is activated. We should not override it, unless it is optional. (Default off)

**Comment by tsujan** [comment]
> We should not override it

I agree.

> unless it is optional.

It's too small to deserve an optional setting of its own. IMO, we can't add an option for every minute detail; some things should be left to other programs, like WM.

**Comment by stefonarch** [comment]
Ok, found a workaround because I use it often and tings not working
 are  annoying, my shortcut calls this script now:
```
#!/bin/bash
pcmanfm-qt
xdotool click 1
```

`

**Comment by tsujan** [comment]
Yes. You could also use`wmctrl`:
```
pcmanfm-qt && wmctrl -i -a $(wmctrl -l | tail -n 1 | cut -d ' ' -f1)
```
What's after `&&` focuses the last window, which is that of `pcmanfm-qt` in this case.

**Comment by stefonarch** [comment]
well that's above my capabilities ;)
globalshortcuts doesn't understand && - so it has to be always a script.

**Comment by tsujan** [comment]
> globalshortcuts doesn't understand &&

It understands everything when you use `bash -c "COMMAN"`.

I just meant it as an example; otherwise, your method is better and you could add it to shortcuts as:
```bash
bash -c "pcmanfm-qt && xdotool click 1"
```

**Comment by stefonarch** [comment]
Cool the bash -c "comand", didn't think of this.

**Comment by stefonarch** [comment]
Hm, trying the above workarounds on the 32 bit arch-packages laptop and they are all not working, another difference I see is the title bar  "blinking".

**Comment by tsujan** [comment]
The only thing I can say with certainty is that it isn't pcmanfm-qt's fault. Most probably, it's about WM and/or compositor. They work fine with KWin.

**Comment by stefonarch** [comment]
Noticed that wmctrl wasn't installed, your line works as a script.
