### ISSUE TITLE
Screengrab mockup

### ISSUE THREAD

**Issue by micrococo** [lxqt/lxqt#1697]
I think that Screengrab isn't very appealing currently, so I've been playing a bit with the layout and got this mockup. The options panel is a QDockWidget, and the lock button would hide the title bar and lock the dock in the current position (left or right only). I have added a checkbox to make the capture on click because sometimes you need a delay but don't know how long it should be. The options for the capture type would always be visible but disabled if not needed. The design leaves more vertical space available, which I think is good for small screens like the one in my netbook. What do you think? It's only a mockup, there's nothing implemented.

![screengrab-mockup-right](https://user-images.githubusercontent.com/7717273/55276349-24d54d00-52f3-11e9-87a7-e0448cf3b461.png)
![screengrab-mockup-left](https://user-images.githubusercontent.com/7717273/55276351-2737a700-52f3-11e9-8a80-ed6ce63bd8de.png)

**Comment by tsujan** [comment]
The horizontal space is wasted in your mockup just for saving a little more vertical space. And "appealing" is a subjective matter.

> I have added a checkbox to make the capture on click

Please make a PR for it.

**Comment by micrococo** [comment]
> The horizontal space is wasted in your mockup just for saving a little more vertical space.

Yes, but most screens are widescreen today, so I think that the vertical space is more important to preserve than the horizontal one.

> And "appealing" is a subjective matter.
> 

Of course it is. I meant it isn't very appealing to me, but as you say "appealing" is a subjective matter and the current design may indeed be more appealing than my proposal. Sorry for the misswording.

> > I have added a checkbox to make the capture on click
> 
> Please make a PR for it.

I only added it to the mockup. As I wrote, there's nothing implemented, the issue is just and idea. :)

**Comment by tsujan** [comment]
> so I think that the vertical space is more important to preserve 

In your screenshot, the area given to controls is too big. In comparison, the current UI is really sleek (= appealing -- of course, that's subjective).

**Comment by tsujan** [comment]
> Yes, but most screens are widescreen today

Exactly! So, the current design is better for them: you could see the screenshot preview of a wide screen more easily, while, with your mockup. the upper and lower parts of preview would be empty.

**Comment by tsujan** [comment]
Just for a visual comparison:

![nice](https://user-images.githubusercontent.com/981076/55276985-b905db00-5318-11e9-8c91-1408af0abcd2.png)

Almost no space is wasted.

**Comment by micrococo** [comment]
Ok, let's close the issue then. Thanks for the hints and the constructive discussion.

**Comment by tsujan** [comment]
Thanks for the sharing your ideas! My counter-argument wasn't about sharing, of course.
