### ISSUE TITLE
Plugin directory-menu > open in terminal doesn't work

### ISSUE THREAD

**Issue by stefonarch** [lxqt/lxqt#1700]
I don't know when this item in the menu of the plugin appeared exactly, I'm sure it wasn't there before.It is present in every subfolder and it does nothing. In pcmanfm-qt it works and it's translated too.

![schermata-01-15-31-09](https://user-images.githubusercontent.com/10681413/55331570-d7441600-5493-11e9-972e-1d8a150fbba2.png)

##### Expected Behavior

If present it should work.
##### Current Behavior

It doesn't.

##### Context

IMHO it should not be present in this plugin as it was before.
##### System Information

git packages and arch

**Comment by tsujan** [comment]
It was added here: https://github.com/lxqt/lxqt-panel/commit/e08186635d0175213069a8f35cf3f2cc49ce5fd7

I guess you need to define the default terminal.

**Comment by stefonarch** [comment]
> you need to define the default terminal
As said above it works in pcmanfm-qt... it's set.

**Comment by tsujan** [comment]
> EDIT: ok, I missed the separate config in the plugin, but actually why doesn't it take the setting from pcmanfm-qt?

Because neither Panel nor pcmanfm-qt should presuppose each other. LXQt is modular.

> So the default was empty instead of qterminal.

I've used neither this new feature nor directory-menu but I think it's better to choose qterminal as the default and warn user if it's missing (by showing a dialog that says, "Please choose a default terminal emulator!").

**Comment by tsujan** [comment]
Or, at least, that option should be disabled if no terminal is chosen yet.

**Comment by stefonarch** [comment]
For me it's something I'll never use I think, would be fine if it would be optional.

**Comment by ssrublev** [comment]
Happy New Year everybody! Now I am here and am wondering what to choose in ""Directory Menu Settings" → "Appearance" → "Terminal" in order to function "Open in terminal" work properly? I can't get it working.

**Comment by ssrublev** [comment]
Sorry, I have found the fix: "/usr/bin/qterminal". I failed to enter it properly at first attempt.
