### ISSUE TITLE
Make debug.log location configurable

### ISSUE THREAD

**Issue by zabbal** [lxqt/lxqt#1701]
##### Expected Behavior
The debug.log should be located either in ~/.cache/lxqt or in ~/.local/log/lxqt

##### Current Behavior
By default debug.log is located in ~/.config/lxqt which is definitely wrong place as it has nothing to do with configs.

##### Possible Solution
Make debug.log placement configurable (in lxqt.conf?) so users won't have to pollute config directory with unrelated files.

##### Steps to Reproduce (for bugs)
Login to lxqt.

##### Context
Config files should be trivial to backup. It's natural to expect only config files in ~/.config

##### System Information
* Distribution & Version: Lubuntu 18.10
* Kernel: 4.18.0
* Qt Version: 5.11.1
* liblxqt Version: 0.13.0
* Package version: 27

**Comment by agaida** [comment]
Feel free to provide a PR.

**Comment by tsujan** [comment]
Personally, I think the debug log is useless and should be removed. I've linked it to `/dev/null`. Frankly, I dislike the idea of everything adding a log -- systemd's is more than enough.

**Comment by zabbal** [comment]
> Personally, I think the debug log is useless and should be removed. I've linked it to `/dev/null`. Frankly, I dislike the idea of everything adding a log -- systemd's is more than enough.

That would be even better - journalctl ismore convenient anyway.

**Comment by tsujan** [comment]
In years I've worked with LXQt, I haven't seen a use for that log. Users should attach backtraces provided by `coredumpctl` when they report a crash. Devs use terminal + `qDebug()` + ... to test programs.

**Comment by agaida** [comment]
@tsujan - we should use the reminder to finally get rid of this if no one speak up against.

**Comment by tsujan** [comment]
I agree. Let's wait for @palinek and @luis-pereira .

**Comment by luis-pereira** [comment]
`~/.config/` is not the right place, of course.
It should be removed, IMO. I even forgot that it existed.

**Comment by palinek** [comment]
> It should be removed, IMO. I even forgot that it existed.

I even didn't know about this kind of output :)

I think, that we should completely remove the `dbgMessageOutput(..)` here -> https://github.com/lxqt/liblxqt/blob/master/lxqtapplication.cpp#L58... and use the standard Qt technique to format output (if necessary) -> https://doc.qt.io/qt-5/debug.html#warning-and-debugging-messages

Should I make PR?

**Comment by tsujan** [comment]
@palinek Please remove it!
