### ISSUE TITLE
[RFE] Expand window manager config docs

### ISSUE THREAD

**Issue by zabbal** [lxqt/lxqt#1702]
There's some documentation available in https://github.com/lxqt/lxqt/wiki/ConfigWindowManagers but it could be improved.

Most notably it's rather odd that windowmanagers.conf is not mentioned at all. Would be great to clarify it's format, interaction with session.conf window_manager parameter etc.

Especially interesting are things like absolute vs relative paths, preference/relation with /etc/xdg/lxqt etc.

**Comment by agaida** [comment]
Feel free to send a PR

**Comment by zabbal** [comment]
> Feel free to send a PR

I'd love tobut that requires understanding of inner workings of lxqt which I hoped to aquire through aforementioned wiki pages.
