### ISSUE TITLE
Battery status not updating

### ISSUE THREAD

**Issue by tsimonq2** [lxqt/lxqt#1707]
This is using the latest versions of LXQt, with no patches cherry-picked.

On my laptop, the battery indicator will not update sometimes. It'll be at 50%, I'll lose track of time, then a few hours later my laptop will shut off with no warning because my battery has died. All while the indicator (and thus the associated suspend functions) stay at 50%. This isn't dependent on 50%, sometimes it'll be more or less.

It triggers an update if I go to the settings and toggle "Enable Battery Watcher" off and then on again. It just isn't doing it automatically.

**Comment by wxl** [comment]
I wonder if this might not be some sort of core system issue, or potentially a bad battery. We've had some other testing of this downstream and could not reproduce.

**Comment by tsujan** [comment]
It has never happened to me either.

Since @tsimonq2 said he could correct it manually, I don't think it's about a bad battery.

**Comment by podlech** [comment]
@tsimonq2 this might be related to https://bugzilla.kernel.org/show_bug.cgi?id=199981. The battery issue was gone after upgrading to linux kernel 5.x. Let me know if that works.

**Comment by tsujan** [comment]
Please follow or add info to https://github.com/lxqt/lxqt/issues/1761
