### ISSUE TITLE
lxqt-leave still showing "hibernate" and "suspend" although they're configured as "NoDisplay"

### ISSUE THREAD

**Issue by je-vv** [lxqt/lxqt#1708]
Hi, I'm using LXQt on Arch GNU+Linux up to date:

> liblxqt 0.14.1-1
> lxqt-config 0.14.1-1
> lxqt-powermanagement 0.14.1-1

I've also set both:

> .local/share/applications/lxqt-hibernate.desktop
> .local/share/applications/lxqt-suspend.desktop

Such that they both include:

`NoDisplay=true`

That according to the [Arch Wiki](https://wiki.archlinux.org/index.php/LXQt#Customizing_Leave).  That really helped hiding the hibernate and suspend icons from **Application/Start Menu -> Leave**.  However when calling `lxqt-leave`, which I do through a shortcut (ctr-alt-del), then both lxqt-hibernate and lxqt-suspend are shown.

My understanding was that `NoDisplay=true` actually made the entries hidden on all menus, not just the **Application/Start** one.  Is there another configuration to be used for such purpose?  If not, can one be added, or at least make the current one apply for all menus?

Thanks !

**Comment by tsujan** [comment]
What you see in "Leave" is a different GUI. Its contents aren't desktop files (but "Leave" has a separate desktop file of its own), so nothing should change there.

You could also hide "Leave" (lxqt-leave.desktop) in the same way you did it for other items. Actually, I did it for myself 2 years ago.

**Comment by tsujan** [comment]
My menu:

![menu](https://user-images.githubusercontent.com/981076/56388142-778f8e00-623b-11e9-9c45-e7e51ce08b63.png)

**Comment by luis-pereira** [comment]
@tsujan I seems to me @je-vv might be talking about the "menu" the `lxqt-leave` command pops up.

**Comment by tsujan** [comment]
Maybe but If so and if it's a bug, he should provide a step-by-step way of reproducing it. We can't rely on our interpretations.

**Comment by je-vv** [comment]
@tsujan, what you're showing is what I experience with the applications/start menu.  That part works well for me as well.  No need to hide the "Leave" menu from the "Start" one.
The problem is when you call from the command line lxqt-leave, or when you call lxqt-leave from a shortcut.  Only then you'll notice hibernate and suspend still there.  I'll attach 1st what correctly show from the start menu, and then from shortcut/command-line...

**Comment by agaida** [comment]
it's getting philospphical in the sense of:

```
# lxqt-leave --logout
# lxqt-leave --reboot 
```
will work when lxqt-leave will be called that way - it might be a good idea to use the hints from the desktop file, but i'm not really sure that this is a good idea. what about a general lxqt-leave config file?

**Comment by je-vv** [comment]
Well, I spoke too fast, I can't take a screenshot when going through the start menu.  But believe me, it's the same as what you're showing.  I'll paste the lxqt-leave command then.

**Comment by je-vv** [comment]
![lxqt-leave-call](https://user-images.githubusercontent.com/10799432/56391226-4c7d4e00-61eb-11e9-9b47-8fd315a96066.png)

**Comment by tsujan** [comment]
@je-vv A command never disappears when you hide its corresponding desktop files.

Your screenshot shows that I had the correct interpretation of your report. Please reread my first comment.

**Comment by Vladimir-csp** [comment]
...if only logout dialog was implemented the way described in #580.

**Comment by je-vv** [comment]
Is ther a way to configure **lxqt-leave**, the command?  I understand now it's different than the **applications/start** menu, but I what I'm looking for is to hide it from the command as well, so there's no way to hit those buttons...

**Comment by tsujan** [comment]
> Is there a way to configure lxqt-leave, the command?

No. See `man lxqt-leave`.
