### ISSUE TITLE
Desktop settings does not rotate wallpapers correctly

### ISSUE THREAD

**Issue by EinarMostad** [lxqt/lxqt#1714]
##### Expected Behavior
When setting an image in portrait orientation as wallpaper, the image should show up in portrait orientation on screen.

##### Current Behavior
The image shows up in landscape orientation even if it is in portrait orientation.

![Wrong rotation of picture](https://user-images.githubusercontent.com/50294848/57194643-7c498700-6f49-11e9-8898-67b347aba72d.png)

##### Possible Solution
I suspect the problem is with images where the orientation is set in EXIF data instead of the image data actually being rotated. LXImage-Qt shows these images correctly, so maybe you could copy some code from it that checks the orientation in EXIF data? (I am not a coder, so I cannot help you more than suggest what I think is the cause of the problem.)

##### Steps to Reproduce (for bugs)
1. Right click the desktop.
2. Choose an image in portrait orientation as wallpaper. I used "zoom wallpaper to fill the whole screen"-mode. As stated above, this might only apply to pictures with rotation set in EXIF.

##### Context
I think most mirrorless cameras deliver JPGs with orientation set in EXIF instead of rotated image data. If I remember correctly, DarkTable and DigiKam also does this by default when exporting a RAW file to another image format if you do not change a setting.

##### System Information
* Distribution & Version: Arch Linux, updated today, 5th May 2019
* Kernel: 5.0.11-arch1-1-ARCH
* Qt Version: 5.12.3
* liblxqt Version: 0.14.1
* Package version: 0.14.1

**Comment by tsujan** [comment]
Desktop settings aren't supposed to rotate the image. What happens under KDE Plasma?

**Comment by EinarMostad** [comment]
I don't know about Plasma, but if an image is in portrait orientation and always shows up that way in every other program, then you would sort of think that it should be possible to use it as a wallpaper in the same orientation. I have never had this issue when using LXDE in the past...

**Comment by agaida** [comment]
erm - no, we don't want to buy it, i guess - we don't rotate pictures, we don't edit them, we just display them. Maybe i'm wrong, but think a bit further - we handle svg and such things too and sometime the needed exif informations will be plain wrong. So i guess the user has to take care about his wallpaper folder.

**Comment by EinarMostad** [comment]
But you DO rotate images to show up in the right orientation in PCManFM-Qt previews... I know this is not a very important bug, but it when a picture is in portrait orientation everywhere else than when used as a desktop wallpaper, it seems like a bug to me.

**Comment by tsujan** [comment]
> I am just trying to help out by pointing out something that seems like a bug to me.

We know and appreciate that. Please don't mistake a discussion with a denial. We should determine whether it's worth adding extra codes or not. Thumbnail previews are't related to this and lximage-qt is an image viewer with its separate code.

**Comment by EinarMostad** [comment]
OK. :-)

**Comment by agaida** [comment]
@EinarMostad - maybe we should enhanche our discussion style - i don't know the code to set wallpapers, but when we use exif informations regarding orientation it should be at least optional.

**Comment by EinarMostad** [comment]
From a user's perspective, I am very happy with LXQt and the wallpaper settings in general, but if there was a radio button where I could choose to "Use EXIF rotation flag", that would be a wonderful addition and very helpful in situations like this. Sorry for getting defensive.

**Comment by rubyFeedback** [comment]
> Sorry for getting defensive.

I don't think or interprete as defensive; I actually concur with your comment. I don't need a radio button but the example with PCManFM-Qt showed that the earlier comment about "we never rotate any images" could not be correct (nor do I think it would make any sense, anyway).

That of course may not necessarily mean that code is added, since the more code you have, the more you may have to maintain said code base; but this seems really a very minor change anyway. In my opinion it would be very simple and easy to add.

> lximage-qt is an image viewer with its separate code.

This is mostly a chicken-egg situation. You could say the same about all KDE add-ons too. For example, "split screen" functionality used to be different in quadkonsole, regular KDE konsole and yakuake. The default in KDE konsole always used to confuse me, whereas both quadkonsole and yakukae behaved more logically (in my opinion). Should similar functionality behave differently, in different applications? What constitutes "core" functionality for any DE? In my opinion EinarMostad's comment appears to be significantly more user centric (and more logical/compelling). That does not negate the other point of views, but from a usability point of view, I am more convinced by his comment than the alternative variants given. Of course this still does not mean that the functionality may have to be added (I would not need it), but this is more a principle-comment here from me.

**Comment by tsujan** [comment]
@rubyFeedback If you have a patch please make a PR, instead of telling long stories no one reads.

**Comment by agaida** [comment]
@tsujan - thanks for the reply, thought the same :)

**Comment by wxl** [comment]
> What happens under KDE Plasma?

I need an example image to really verify behavior (ahem @EinarMostad and what I mean is something that is rotated correctly in pcmanfm-qt and lximage-qt but not on the desktop), but what I can tell you is there's no rotate option in the dialog, whether or not it's based on EXIF data. If KDE is the gold standard, then that's not the right approach. Doesn't mean they don't deal with it correctly, though.

> we handle svg and such things too and sometime the needed exif informations will be plain wrong

@agaida Do we have an example of this? Maybe EXIF is the wrong approach altogether.

> Thumbnail previews are't related to this and lximage-qt is an image viewer with its separate code.

@tsujan maybe I misunderstand this comment, but though it should be obvious this code can't be directly applied here, they do seem to have some way of detecting orientation that could be adapted, no? And if there's a logic to do it there, is there not logic to do it here?

**Comment by tsujan** [comment]
@wxl Doubtlessly, there's a logic to it :) But logic isn't enough. For now, my coding time is taken by more important matters. Sometimes, I do 3 or 4 things at the same time but can't do more than that — actually, I can't do it continuously either.

When a report remains open, that means it'll be attended to at some point but, maybe, not soon.

**Comment by EinarMostad** [comment]
![P1120930](https://user-images.githubusercontent.com/50294848/57646327-9f66dd00-75c0-11e9-9ebf-0ce82b9b41ac.JPG)
@wxl This image was the one I was trying to use. You see below how PCManFM-Qt and LXImage-Qt shows it and in the picture at the top of this thread how it shows up sideways on the desktop.
![PCManFM-Qt_showing_picture](https://user-images.githubusercontent.com/50294848/57646495-05ebfb00-75c1-11e9-9373-d3cfcbe15383.png)
![LXImage-Qt_showing_picture](https://user-images.githubusercontent.com/50294848/57646582-33d13f80-75c1-11e9-855e-c544fa2d2437.png)

**Comment by tsujan** [comment]
> you might look at it in the future. :-)

I'll surely do. No report about pcmanfm-qt has been forgotten so far.
Another developer might do it sooner though.

**Comment by EinarMostad** [comment]
@tsujan Perfect! Thank you! :-)

**Comment by tsujan** [comment]
For the record:

This requires libexif dependency but since libfm-qt already depends on libexif, there's no problem. The code should be written and tested with jpeg images, whether they're of this kind or not.

**Comment by tsujan** [comment]
The PR is here: https://github.com/lxqt/pcmanfm-qt/pull/965. It uses purely Qt methods.

The new option:

![rotate_image](https://user-images.githubusercontent.com/981076/57728815-03b19b80-76aa-11e9-83ed-57e670534bd9.png)

The PR needs adequate tests — I could test it *only* with the image attached to this page. Please also pay attention to memory/CPU usage when testing and compare it with the usual usage!

**Comment by stefonarch** [comment]
I tested it, but I didn't find any image on which checking or unchecking the box did any effect at all:  all were displayed as the were, tried also some sent to me from iphone and android.

If the above is correct I don't see a reason to have this checkbox, it has to be a rare case.

**Comment by EinarMostad** [comment]
@stefonarch Did you test with images in portrait orientation where the data was not rotated, but where only the EXIF flag was used? The point isn't to rotate every image with this checkbox, but to be able to rotate it if the EXIF data says it should be rotated. I think most mirrorless and DSLR cameras do not rotate the image data, but just sets an EXIF flag. At least my Panasonic Lumix GX8 does. Maybe phones actually rotate the data and that is why the checkbox does nothing? 

@tsujan Maybe the text on the checkbox should be clearer as to what it actually does: "Rotate if EXIF rotation flag is set" or something like that?

**Comment by tsujan** [comment]
> I don't see a reason to have this checkbox

@stefonarch The difference is an extra reading for each image, especially with slide-show. Personally, I don't want/need it here and the same may be true for most users; hence the checkbox.

> Maybe the text on the checkbox should be clearer...

Maybe. That was the shortest description I found without using technical terms but your suggestion is also good.

**Comment by tsujan** [comment]
I found another example: https://s.idigbio.org/idigbio-images-prod-fullsize/d7ce7fda69335db5966a2265e8771e1e.jpg

It is also rotated correctly with the checkbox.

@stefonarch After checking the box, you might need to change the mode and apply because pcmanfm-qt uses cache.

However, I need more complex examples to test the code: images that are not only rotated but also mirrored and/or "flipped".

**Comment by tsujan** [comment]
OK, found the tool: `exiftool` (perl-image-exiftool in Arch). With it, the orientation of any jpeg image can be manipulated. The results were good.

I'll change the text to `Auto-rotate image based on EXIF info` and limit it to jpeg.

**Comment by palinek** [comment]
> I'll change the text to Auto-rotate image based on EXIF info and limit it to jpeg.

You were talking also about flipping/mirroring before.... so my humble proposal would be: `Transform image based on EXIF info`

**Comment by tsujan** [comment]
> Transform image based on EXIF info

Yes, that's better.

**Comment by tsujan** [comment]
Done:

![modified_settings](https://user-images.githubusercontent.com/981076/57779800-1f658200-773c-11e9-9d51-049f6ad4b261.png)

**Comment by tsimonq2** [comment]
I disagree that the wording here is intuitive. In my opinion, we should read the EXIF data when a new image is selected and then trigger a change to a dropdown menu such as "wallpaper rotation"

Many people don't know what an EXIF is, let alone know what that checkbox will mean.

**Comment by tsujan** [comment]
> Many people don't know what an EXIF is, let alone know what that checkbox will mean.

Then, they won't check it or google for it.

Unlike in gnome, we do see our users stupid.

**Comment by wxl** [comment]
I have to say I'm in agreement with @tsujan. Well, not about seeing people— any one— as stupid, but about the wording. This is technically about the response to EXIF data. You could have an image that is not right side up and yet there is no EXIF data to suggest doing something different. If such a case existed, users would be frustrated if they checked the "wallpaper rotation" and got no change. I think it's good to have non-technical language but where it is the only way to adequately and concisely explain something, it should be used. Also, how many times have you seen some software vaguely describe some action and you wished they had merely explained more concretely rather than being vague for the sake of being "friendly?"

**Comment by tsujan** [comment]
lximage-qt has an action that says, "Show EXIF Data". Such data usually don't exist. A config GUI is not a teaching tool and users can always search the Internet to know what they need to know.

As for gnome and…, I said that because it has become a "tradition" there: remove anything that may be confusing. Their definition of "confusing" covers most of things Linux users have used for ages. Doing the same thing in LXQt? Over my dead body ;)

**Comment by micrococo** [comment]
How about "Transform images according to their metadata" (but in proper English)? EXIF is just one type of metadata, and at a later stage some metadata specific to image formats might be used as a fallback.

**Comment by tsujan** [comment]
JPEG metadata is EXIF and this is only for JPEG.

I really don't think choosing this or that word is important. This is how I made the PR. After it's merged, another PR could be made for such details.

**Comment by agaida** [comment]
> JPEG metadata is EXIF and this is only for JPEG.

Btw - that isn't true. Webp can also contain exif data

**Comment by tsujan** [comment]
> Btw - that isn't true. Webp can also contain exif data

So, it *is* true. Read it again ;)

I limited it to jpeg to not read metadata for every format. Even with jpeg, it's rare.

**Comment by agaida** [comment]
every cellphone camera write exif, all cameras write exif

**Comment by tsujan** [comment]
Every image that's rotated by lximage-qt and thumbnail generator is also rotated for desktop, and conversely. The patch can do more but I limited it for the sake of consistency. The limitation could be removed easily.

What's the problem here?

**Comment by EinarMostad** [comment]
Thank you for your work with fixing this issue! :-)

**Comment by tsujan** [comment]
Thank you for your report! Without it, I wouldn't try to find a more reliable way to do it in other places either.

**Comment by EinarMostad** [comment]
Your welcome! :-)

**Comment by ulliperk** [comment]
the above discussed issue still exists in pcmanfm-qt. 
On kubuntu 20.04 in a plasma wayland session pcmanfm -- desktop does not rotate the screen correctly. Desktop would not focus in the middle of the screen and be cut into half or quarter when flipping back to the original position. Also desktop can be moved freely by left mouse click.
The expexted behaviour is: desktop has its focus in the middle of the screen and desktop rotates according to the device's rotation direction. It should be impossible to move the entiere desktop by a mouse click

**Comment by tsujan** [comment]
@ulliperk 
Your comment doesn't have any relation to this report.

Instead, please answer the questions at https://github.com/lxqt/pcmanfm-qt/issues/1602, where you opened a vague report.
