### ISSUE TITLE
{Only,Not}ShowIn attributes for entries in ~/Desktop are ignored

### ISSUE THREAD

**Issue by artixnous** [lxqt/lxqt#1715]
Not sure if this should go to pcmanfm-qt's issues or elsewhere more appropriate, sorry.
I'm trying to make a uniform-looking desktop for both LXQt and KDE/Plasma, but I can't hide KDE-specific icons from the LXQt desktop. I'm using standard .desktop files with `OnlyShowIn` and `NotShowIn` keys, which are ignored by LXQt.
I've tried all possible combinations of keys/values. `NoDisplay` is also ignored. The only respected attribute is `Hidden=true`, which hides an icon from both KDE and LXQt. Example entry and screenshot below.
````
[Desktop Entry]
Name=Home
Type=Application
Exec=dolphin
Icon=user-home
OnlyShowIn=LXQt
NotShowIn=KDE
````
All LXQt components are version 0.14.1.
![LXQt desktop](https://user-images.githubusercontent.com/6310912/57199874-f3ecd580-6f8c-11e9-9cc2-3024a838e63c.png)

##### System Information
* Distribution & Version: Artix (rolling)
* Kernel: 5.0.9
* Qt Version: 5.12.3
* liblxqt Version: 0.14.1

**Comment by agaida** [comment]
Not an LXQt bug.

**Comment by artixnous** [comment]
Thanks for the prompt reply, I would appreciate a pointer to the cause.

**Comment by tsujan** [comment]
> I would appreciate a pointer to the cause.

@agaida added an explanation to his comment above.

**Comment by artixnous** [comment]
Thanks, people, I'll use autostart entries to control the presence of icons.

**Comment by tsujan** [comment]
It seems that only `NoDisplay=true` works in LXQt main menu.

@agaida Was there a discussion about why `OnlyShowIn` and `NotShowIn` don't work in LXQt main menu? I know it isn't directly related to this report but I don't know why we don't support them -- or I may be mistaken.

**Comment by tsujan** [comment]
Oh, my bad: `OnlyShowIn=KDE;` DOES work under LXQt. I just had to wait for the main menu to be updated. Sorry....

**Comment by agaida** [comment]
It works in the LXQt menu, in the Config Center, in Autostart folders - so i don't get the question

**Comment by agaida** [comment]
ok, and i was to fast

**Comment by tsujan** [comment]
Yes, I was wrong.

The thing was just that if you edit a desktop entry inside `~/.local/share/applications`, it might not work at first but if you restart Panel, it'll work.

**Comment by agaida** [comment]
@artixnous - Imagine the bunch of upset bug reports if the Desktop would respect these triggers :smile:

you put pictures, text file, svg - all kind onto the Desktop. Then you drag and drop a desktop file to the desktop and it silently disappear :sunglasses:

**Comment by tsujan** [comment]
That's completely right. Neither desktop nor any ordinary folder should respect `OnlyShowIn`, `NotShowIn` or `NoDisplay`.

**Comment by agaida** [comment]
But it would be pure fun - if pcmanfm-qt would respect it for the desktop one could make an experiment:
Install openbox, pcmanfm-qt to draw the desktop, run the panel and runner - looks exactly like LXQt, but without the Session - voila, the files will be there. Start a lxqt-session - upps the files are gone and vice versa.

**Comment by artixnous** [comment]
I'm creating 2 installation ISOs, one MATE/LXDE and the other Plasma/LXQt; `*ShowIn` work in the fat DEs and hide the other desktop's icons. So, I got confused a little there until you made it clear it's intentional. :D

**Comment by tsujan** [comment]
@artixnous If you want to hide any item on LXQt desktop, there is a simple way:

Make the file `.hidden` on desktop and add the names of files you want to hide to it. For desktop entries, it should be their real file names, not their visible names. Then refresh desktop from pcmanfm-qt window. That's it.

In this way, you could make redundant items hidden in LXQt desktop but not in KDE.

That's also true for any other folder.

**Comment by artixnous** [comment]
It works perfectly, cheers!
