### ISSUE TITLE
Appearance Configuration Off Screen Buttons

### ISSUE THREAD

**Issue by jo3sn0w** [lxqt/lxqt#1716]
Made a change to GUI window option "LXQt Appearance Configuration: Widget Style : QT Style".  After selecting a style and clicking 'Apply' button, the changes were made instantaneously.  My problem now is that all the "LXQt Appearance Configuration" window response buttons are displaying well below the taskbar.  The window does not allow vertical resizing - only horizontal.  Essentially, there is no way to 'Apply' any new changes since the button is off screen.

In the '.config/lxqt/lxqt.conf' file, I have the following entries:

[General]
__userfile__=true

[Qt]
style=bb10dark

Assuming I can just change 'style=Fusion' to undo the change, yet this doesn't help me with the buttons being off screen.  I've been viewing the files in '.config/lxqt/' directory for clues on fixing the issue.  Before doing any serious damage to my settings, I would like your feedback on possible solutions or other files/folders I should focus my attention.

OS: Debian GNU/Linux buster/sid x86_64
Kernel: 4.19.0-4-amd64
Image: Clean install LXQt build Buster RC1 2019-04-13
Host: Dell Inspiron 1121
CPU: Intel i3 U 330 (4) @ 1.2GHz
GPU: Intel Core Processor
Resolution: 1366x768
lxqt-config:
  Installed: 0.14.1-2
lxqt:
  Installed: 29
![LXQt_Appearance_Configuration_Off_Screen_Buttons](https://user-images.githubusercontent.com/50341113/57256492-bfc4f380-7024-11e9-9cc4-4e27b62ecc2d.png)

**Comment by tsujan** [comment]
Most window managers have Alt+left-mouse-button for grabbing and moving windows.

bb10dark is not only buggy but also not for desktop computers/laptops. Don't use it.

Closing because this isn't an LXQt issue but you could add comments.

**Comment by jo3sn0w** [comment]
Thanks for the feedback.  Jumped into vim and reverted back to 'style=Fusion' in lxqt.conf file.  Wasn't sure if the files in this folder were safe to modify manually.  Going forward, I'll back them up with other configs.  BTW, just to prove your point, I went back into the GUI and selected 'bb10dark' again.  The buttons immediately went off screen and no vertical resizing allowed.  Updated the file and then log out/in and all is back to normal.  Truly bizarre behavior coming from bb10dark.  Hopefully, this will be useful for anyone else who manages to select bb10dark on a small screen.

I'd also like to say thank you for such a great DE experience.  Other than this minor hiccup, it has been running flawlessly on my meager laptop.  Resource load has been very light weight and performance better than expected.  Have been using XFCE for a while, so I'm just getting used to the core applications provided by LXQt.  Paired with the latest Debian release, the combination of the two make a very stable OS.

![LXQt_Appearance_Configuration_Restored](https://user-images.githubusercontent.com/50341113/57258496-97d88e80-702a-11e9-9be6-b5cf9dcc460f.png)

**Comment by tsujan** [comment]
> Wasn't sure if the files in this folder were safe to modify manually.

Oh, yes! I forgot to tell you about that file.

bb10 themes also have something called "kinetic scrolling", which can cause random crashes in some Qt apps. Kinetic scrolling isn't reading for use in style engines yet.

Debian sid is a very good distro for having a standard LXQt experience. LXQt is being made better continuously. I hope you'd use its latest git version and help us to find and fix its probable issues.

**Comment by agaida** [comment]
Only a remark: Talked with the qt5-style-plugins maintainer two weeks ago - there will be a cleanup and the bb-styles will be removed. The other styles will likely remain until they break. We both agree that it is not worth to put much work into a thing that is dead and abandoned upstream. So - as long the styles build the will be part of the distribution ...
