### ISSUE TITLE
Add a desktop number indicator in the panel, to avoid the desktop switcher

### ISSUE THREAD

**Issue by je-vv** [lxqt/lxqt#1717]
Hello, on latest lxqt under Arch (0.14.1) I don't have option to enable a small widget showing the current desktop number or label.  The only option I have to know the current desktop is to enable the "desktop switcher" widget.  I really don't use the desktop switcher at all, other than to recognize which desktop I am under.  I'd prefer a current desktop indicator, and much better a number indicator.  It's like having just one desktop in the "desktop switcher" with the number of the current window.

Or it can be pretty much the same "desktop switcher" just showing the current one, and then upon click showing the rest, which can be selected with pressing on the required one, like another mode of the same "desktop switcher", but using way less space (as opposed of the one currently used, which uses the space a pager would).

Thanks !

**Comment by palinek** [comment]
@je-vv please, test with lxqt/lxqt-panel#1075

**Comment by je-vv** [comment]
That does it !  Thanks a lot !  I do agree with @stefonarch on his comment on that PR, that once **show only active desktop** is selected it seems there's no way to get the pager back at all (logouts+logins don't help).  But getting to show just the current desktop is working just fine.

Thanks again !
