### ISSUE TITLE
Strange window position with xdotool

### ISSUE THREAD

**Issue by VTiTux** [lxqt/lxqt#1719]
xdotool is a great tool to simulate mouse/keyboard events and to get window location and properties.

The command "~$ xdotool getactivewindow getwindowgeometry" returns the size and the position of the active window (the virtual terminal where you are entering this command).
(and 'xdotool getmouselocation' is usefull to check the coordinates of the screen, with the mouse)

But the windows positions are not the same on all the window manager.
With KDE, the top position of the window is just below the title bar (the window decoration isn't returned).
But with LXQt (I'm using Lubuntu), the top is underneath the menu bar ('File'/'Edit'/'View'...).
This is especially strange with firefox, while the menu bar is hidden but the offset is still present! So, the tabs bar seems to be outside the window!!!

Is this a normalized freedesktop property?
Where to report that? The tool (xdotool)? Its backend (X11)? or the WM (LxQt)?

**Comment by tsujan** [comment]
LXQt is not a window manager, as KDE isn't either. You could use any WM with LXQt.

You use KWin under KDE. You could also use KWin under LXQt.

**Comment by VTiTux** [comment]
So, which is the default window manager of LXQt? How can I know the WM I'm using?
xdotool use XGetWindowAttributes(), from the XLib, to querry the window position.
Why the XLib behavior isn't the same on all the distribution?
Which part of my system is responsible to give these data to the XLib? The Window Manager? The Desktop Environment? Or XLib itself?

**Comment by tsujan** [comment]
> So, which is the default window manager of LXQt?

LXQt doesn't have a default WM — like it doesn't have a default browser, email client or bittorrent app. You could use any DE-agnostic WM with LXQt.

> How can I know the WM I'm using?

Session Settings → Window Manager

**Comment by VTiTux** [comment]
KDE has KWin, GNOME has Mutter. I thought LXQt also had his own window manager.
The default WM of the latest Lubuntu is OpenBox. But this project is dead since 2015. Strange choice.
I will install KWin.
Thank you.

**Comment by tsujan** [comment]
> I will install KWin.

KWin and xfwm4 are good choices. Personally, I prefer KWin because it comes with a rich config, various effects and support for more effects with JS scripts.

**Comment by tsujan** [comment]
> I thought LXQt also had his own window manager.

There have been long discussions about why it isn't a good idea to reinvent the wheel, especially with Wayland.

BTW, KDE can work with Openbox too. GNOME isn't modular enough.

**Comment by VTiTux** [comment]
Outside of KWin, do you know an other `light` Qt-based window manager? It's for an old, slow, computer.

**Comment by tsujan** [comment]
I don't know of any but kwin *is* light.

**Comment by VTiTux** [comment]
I had some bad experiences on this computer, with kde-based distributions. And the boundary between the DE and the WM is confusing for me.
KWin has lot of features and compize-like effects, so its lightness is not obvious for me.
I installed it, and it came with lot of dependencies (159 packages!), including a task manager, kmenuedit, plasma, kwallet, the KDE Configuration Center and so forth...

I will wait and see...

At least, it is still maintained and its xdo/xlib coordinates are right (I experienced some others flaws about the OpenBox coordinates).
And since, me too, I'm using the Qt framework to develop my apps, I'm happy to use a Qt-based WM and DE.

Thanks you.

**Comment by tsujan** [comment]
> KWin has lot of features and compize-like effects, so its lightness is not obvious for me.

Compiz still exists (and can be used with LXQt) but it isn't as light as KWin. KWin is optimized in many ways and is actively developed. Here, it uses about 27 MiB of memory and its CPU usage is negligible when, for example, the desktop cube is rotated. Of course, it needs proper settings.

As for dependencies, yes, several extra KDE packages are needed but you said, "With KDE, the top position...", so I supposed you already had a KDE installation.

**Comment by VTiTux** [comment]
> Compiz still exists (and can be used with LXQt) but it isn't as light as KWin. KWin is optimized in many ways and is actively developed. Here, it uses about 27 MiB of memory and its CPU usage is negligible when, for example, the desktop cube is rotated. Of course, it needs proper settings.

That's a great information.

> As for dependencies, yes, several extra KDE packages are needed but you said, "With KDE, the top position...", so I supposed you already had a KDE installation.

Yes, on my main, recent machine, I'm using OpenSuse/KDE/KWin.
But for my secondary core2duo computer, I'm looking for a light distro/DE/WM.
For now, LXQt/KWin seems very well.

Unfortunately, I have still problems with xdotool.
When I move my window on Lubuntu/LXQt/KWin, the position I get is not the same:
```
$ xdotool getactivewindow windowmove x 500
$ xdotool getactivewindow getwindowgeometry
```
The returned position is [x] 532.
(32 is the height of my title bar).
On OpenSuse/KDE/KWin, I read [x] 500 (except if I move my window above 32, ie: 
`$ xdotool getactivewindow windowmove x 0 (return [x] 32)`

Is it possible the problem located on the DE? Or do I have bad KWin settings?

**Comment by tsujan** [comment]
> Is it possible the problem located on the DE?

No. `xdotool` excludes the title-bar and gives the window geometry. Here, with KWin, when I put QTerminal at the top right corner (without tiling it), the output of `xdotool getactivewindow getwindowgeometry` is this in LXQt:
```
Position: 0,32 (screen: 0)
Geometry: 637x474
```
And in KDE:
```
Position: 0,27 (screen: 0)
Geometry: 637x474
```
The 5-px difference in title-bar height is because of different icon and font handling in LXQt and KDE (LXQt's is better, IMO).

**Comment by tsujan** [comment]
I also tested these in VirtualBox + Manjaro:
```sh
xdotool getactivewindow windowmove x 300
xdotool getactivewindow getwindowgeometry
```
In LXQt:
```sh
Position: 0,332 (screen: 0)
Geometry: 637x474
```
In KDE
```sh
Position: 0,327 (screen: 0)
Geometry: 637x474
```
So, the behavior of `xdotool` is the same.

Now, why `xdotool` excludes the frame when giving the geometry but includes it when moving is a question that should be asked from its developers but the DE doesn't play a role in that.

**Comment by VTiTux** [comment]
> No. `xdotool` excludes the title-bar and gives the window geometry. Here, with KWin, when I put QTerminal at the top left corner (without tiling it), the output of `xdotool getactivewindow getwindowgeometry` is this in LXQ [...]:

Yes, we agree.



> I also tested these in VirtualBox + Manjaro:
> 
> ```shell
> xdotool getactivewindow windowmove x 300
> xdotool getactivewindow getwindowgeometry
> ```
> 
> In LXQt:
> 
> ```shell
> Position: 0,332 (screen: 0)
> Geometry: 637x474
> ```
> 
> In KDE
> 
> ```shell
> Position: 0,327 (screen: 0)
> Geometry: 637x474
> ```
> 
> So, the behavior of `xdotool` is the same.

It's strange.
To be sure, I burned the latest OpenSuse Tumbleweed KDE live DVD:
```
xdotool getactivewindow windowmove x 300
xdotool getactivewindow getwindowgeometry
Window 142606359
  Position: 2464,300 (screen: 0)
  Geometry: 1278x717
```


> Now, why `xdotool` excludes the frame when giving the geometry but includes it when moving is a question that should be asked from its developers but the DE doesn't play a role in that.

According to the source code, xdotool call the XLib directly.
So, why does X11 behave differently on different platforms?
Which part of the OS can influence that?

**Comment by tsujan** [comment]
> Which part of the OS can influence that?

I don't know. Tell me if you found the answer.

**Comment by tsujan** [comment]
Arch gets the source from https://github.com/jordansissel/xdotool. I downloaded Tumbleweed's source from https://software.opensuse.org/package/xdotool. Apart from OpenSUSE's extra patches, the sources are different (Arch's seems to be more up-to-date, although `xdotool` is old itself).

Debian's source (https://packages.debian.org/sid/xdotool) is (almost) identical to that of Tumbleweed but Debian applies two different patches.

That may explain the difference in behavior but I'm not sure because the differences between sources don't seem related to window moving.
