### ISSUE TITLE
lximage-qt drawings not always visible

### ISSUE THREAD

**Issue by guiverc** [lxqt/lxqt#1720]
This initiated with https://askubuntu.com/questions/1148764/lubuntu-19-04-why-dont-drawing-tools-work-in-lximage-qt

Using images (or screenshots just taken) you can add drawings (arrows, rectangles, circles..) that are either visible or invisible depending on whether you are viewing 'fit' or 'original size'

This was noted on Ubuntu 19.04 & 19.10, but also confirmed on debian-testing, plus opensuse-tumbleweed.

Ubuntu bug report: https://bugs.launchpad.net/ubuntu/+source/lximage-qt/+bug/1831847

##### Expected Behavior

Added drawings (arrows, rectangles, circles or numbered-labels) should remain visible on both 'fit-to-screen' and 'original-size' (using either icons or [view] menu changes.

##### Current Behavior

I can view my drawings when I display using 'fit to screen', but added drawings disappear when I select 'original size'

##### Steps to Reproduce (for bugs)

For this I'm copying from my Ubuntu bug report (
1. hit printscreen to save image
2. i select whole screen
3. image-viewer (lximage-qt) opens, I maximize to use a whole screen
4. draw an arrow over part of display (you won't see it drawn)
5. switch to 'fit' (view fit or icon) and the arrow drawn will show
6. if you switch back to original size; drawings made will disappear, however re-appear if you fit-to-window

This was tested using Lubuntu 19.10's daily (ISO) qa-test image, plus installed systems for 19.04 (stable) & an installed 19.10.  Also opensuse-tumbleweed, and debian-testing. In some of these tests I just loaded an image instead of using printscreen for step 1.

##### System Information

* Distribution & Version: 
Lubuntu 19.10 (eoan ermine) opensuse tumbleweed 20190601
* Kernel: 
5.0.0-15-generic  (Lubuntu 19.10),  5.1.3-1-default (opensuse-tumbleweed)
* Qt Version: 
5.11.3 (Lubuntu 19.10) 5.12.3 (opensuse-tumbleweed)
* liblxqt Version: 
liblxqt   0.14.1 (both Lubuntu & opensuse-tumbleweed)
* Package version: 
guiverc@d960-ubu2:/de2900/lubuntu_64$   apt-cache policy lximage-qt
lximage-qt:
  Installed: 0.14.1-1ubuntu1
  Candidate: 0.14.1-1ubuntu1
  Version table:
 *** 0.14.1-1ubuntu1 500
        500 http://ftp.iinet.net.au/pub/ubuntu eoan/universe amd64 Packages
        100 /var/lib/dpkg/status

_guiverc@d960-ubu2:/de2900/lubuntu_64$   lxqt-about --version
lxqt-about 0.14.1
liblxqt   0.14.1
Qt        5.11.3_

** Please note: I've only provided details for one of my installed Lubuntu 19.10 systems, plus some details for opensuse tumbleweed, and none from debian-testing.  I can provide if helpful (and requested in next few days as values may change..)
I have NOT filed with debian or opensuse, but can do so if helpful (for completeness)

**Comment by tsujan** [comment]
Those annotations have many problems; the issues mentioned in this report are just a small part of them.

I didn't like annotations from start because lximage-qt is an image *viewer*, not an image editor. The PR that introduced them was incomplete but was merged by mistake.

**Comment by tsujan** [comment]
FYI:

The accidental merge happened here: https://github.com/lxqt/lximage-qt/pull/180#issuecomment-438052925. Also, IMO, the most basic functionality that it needed was undo/redo. Later, I found many bugs in it and so, hid it in a recent PR.

**Comment by guiverc** [comment]
It's much better to have the functionality in my opinion, even if imperfect, as the *foibles* are easily worked around. The annotation functions are great.  Thanks.

**Comment by tsujan** [comment]
> It's much better to have the functionality in my opinion

I'm not against that, especially now that it isn't visible by default (in the git source). Maybe, someone could fix its issues at some point.

**Comment by tsujan** [comment]
OK, we decided to keep annotations as an experimental feature and hide its toolbar from the user by default (that can be changed in Preferences).

Patches are welcome.

**Comment by tsujan** [comment]
Fixed in https://github.com/lxqt/lximage-qt/commit/e6e0fc9a86758659efd802e1b467d40fefaf4750
