### ISSUE TITLE
Game mode (virtual desktop).

### ISSUE THREAD

**Issue by alexzk1** [lxqt/lxqt#1721]
##### Expected Behavior
So, I like to play games using wine. Common problem there is - they don't like window switch and just crash.
So I suggest to add "game mode" or "virtual desktop mode" to desktop manager. This will prevent ANY kinds of popups/message boxes/etc. that should be contained inside original window like "virtual box". I.e. if mail program is minimized and tries to pop any urgent notify - it must not - that super urgent message will be visible only if i restore main window again. If any program wants to show me message box  - it must not.
Should be some simple counter in tray which shows how many attempts done.

That could be useful in other situations, like I type fast something just to see I was chatting with message box from somewhere ... 

##### Current Behavior
I think none current
##### Possible Solution
Sorry, If I knew ...Something like WINE does in "virtual desktop" mode.

**Comment by tsujan** [comment]
> Common problem there is - they don't like window switch and just crash.

If so, that's a bug that should be fixed by Wine developers.

> So I suggest to add "game mode" or "virtual desktop mode" to desktop manager…

"desktop manager"?! It isn't clear what you try to describe here. If you don't want notifications, you could stop them. If you want us to work around a bug in Wine, then sorry, that isn't our job.
