### ISSUE TITLE
Generic Battery Widget for any power management tool like TLP

### ISSUE THREAD

**Issue by sporadiccrash** [lxqt/lxqt#1722]
It is restrictive to install lxqt-powermanagement just to get a battery indicator widget.

##### Expected Behavior
A configurable widget would be helpful to bind any power manageement tool like TLP. TLP is so far most recommended power management tool with high accuracy.

##### Current Behavior
Currently the only way to get a widget on LXQt-panel is to install lxqt-powermanagement tool.

I would have expected that I can  choose any power manageement tool i want.

##### Possible Solution
If TLP is installed,  run tlp on command line to get battery status.

##### Steps to Reproduce (for bugs)
n/a

##### Context
With this new widget you can open way to plugin any power management tool you like.

##### System Information
Lubuntu 19.04
* Kernel: 5.0.0-16-generic
* Qt Version: 5.12.2
* LXQt Version: 0.14.1

**Comment by palinek** [comment]
> Currently the only way to get a widget on LXQt-panel is to install lxqt-powermanagement tool.

There is no such thing as "battery widget" in LXQt panel. The battery tray indicator is part of the lxqt-powermanagement.

> I would have expected that I can choose any power manageement tool i want.

You are free to choose anything you want. And if you require a tray icon, chose a tool/application which provides it.

That being said LXQt has lxqt-powermanagement and IMO we're not going to implement other tool.
