### ISSUE TITLE
Unable to Scroll Window Content in Most Applications While an Object is Selected via Holding Down Left Mouse Button

### ISSUE THREAD

**Issue by bongochong** [lxqt/lxqt#1723]
**Expected Behaviour**:
In most desktop environments I have used, one is able to select an object in a window (E.g. a file in a file manager), and at-least use the mouse wheel to scroll through the contents of said window while that object remains selected (via holding down the left mouse button).

**Current Behaviour**:
In the majority of Qt applications under LXQt, if one holds down the left mouse button to select an object in a window and wishes to scroll through the contents of that window with the mouse wheel while doing so (E.g. in order to more quickly move a file to a subdirectory), they are unable to. Occasionally an application will initially scroll a few lines then cease to respond to the wheel (which is obviously undesirable as well), though most of the time scrolling appears to be completely disabled when the left mouse button is held down for the purpose of maintaining a selection. The mouse wheel does not scroll. Using the keys on one's keyboard does not activate scrolling. Using a secondary input device like a touchpad does not activate scrolling. Nothing seems to at all, except releasing the button (and as a result, the selection).

**Notes**:
This issue is present in components of the LXQt DE like PCManFM-Qt and Ark, along with other Qt applications as well. A list of third party applications that I have experienced this issue with are as follows:
- QtPass
- Clementine
- Krusader
- QuiteRSS
- Double Commander (Qt UI, obviously).

Applications which use GTK for their UI seem completely unaffected. Nearly every GTK application I have tried does not have the issue in discussion. This includes the GTK version of Double Commander, Nautilus, and many others. Though I am enjoying being near-completely GTK-free, I felt it was a good idea to see if this was an issue in those applications.

I should also mention that scrolling with a selection by simply dragging a file or set of files to the edge of a window in PCManFM-Qt is also tortuously slow, regardless of mouse settings.

**Steps to Reproduce**:
1. Open up an application that ships with LXQt, like PCManFM-Qt.
2. Enter a directory which contains enough files to necessitate scrolling through them.
3. Select a file with your mouse or trackpad and maintain that selection by continuing to hold the left / main mouse button.
4. Attempt to scroll by any conventional means and watch nothing happen.

**System Information**:
Distribution & Version - Lubuntu 19.04 with the Stable Continuous Integration PPA (https://launchpad.net/~lubuntu-ci/+archive/ubuntu/stable-ci) for updated LXQt applications and libraries.
Kernel - 5.0.0-16-generic
Qt Version - 5.12.2
liblxqt Version - 0.14.1

P.S. I did a lot of searching and was unable to figure out whether or not this is an LXQt issue in particular, or a general issue with Qt itself. Regardless, having it affect the file manager that ships with LXQt is - I assume - undesirable for you wonderful devs.

*Edited to correct a syntactical error, further clarify, and include one extra example.*

**Comment by stefonarch** [comment]
Never used this above  method (which doesn't work as you describe): to keep selected a file I always use cltr+left click.
No idea  also what this method would be useful for.

**Comment by tsujan** [comment]
What you want is DND to a folder that becomes visible only after scrolling. It has nothing to do with LXQt or any DE but may be implemented in apps. OK, Qt could have supported it by default but it doesn't.

This report has a good point but isn't helpful in its current form -- it's too long and mixes unrelated apps with each other. If you want the above-mentioned property in Qt's scroll views by default, you should open a feature request at Qt bug tracker (but if it's like this one, they might close it).

I close it but, since it contains an interesting feature request, I'll open an issue at pcmanfm-qt's issue tracker. As for Qt, in general, we can't do anything.

**Comment by bongochong** [comment]
Shoot. I searched for at-least 45 minutes and didn't come across that.
