### ISSUE TITLE
Extracting archive from the context menu do not work

### ISSUE THREAD

**Issue by Polynnel** [lxqt/lxqt#1724]
##### Expected Behavior
Options from the context menu should extract files from an archive.

##### Current Behavior
'Extract here' and 'Extract to...' buttons from the context menu do not work. Extracting works only when using Ark extract button.

##### Steps to Reproduce (for bugs)
1. Have an archive in some catalog.
2. Try to extract it by clicking on it and using the context menu options.

##### Context
It is really annoying that an archive cannot be extracted using the context menu. Instead opening archive in Ark and extracting it from there is needed.

##### System Information
* Distribution & Version: Fedora 30 Workstation
* Kernel: 5.1.11
* Qt Version: 5.12.1
* liblxqt Version: 0.14.1
* Package version: liblxqt.x86_64  0.14.1-1.fc30

**Comment by tsujan** [comment]
Not reproducible.

**Comment by tsujan** [comment]
Check pcmanfm-qt → Preferences → Advanced → Archive integration and make sure "ark" is selected.

**Comment by Polynnel** [comment]
> Check pcmanfm-qt → Preferences → Advanced → Archive integration and make sure "ark" is selected.

Ark wasn't selected and everything works just fine right now.

**Comment by tsujan** [comment]
Good.

pcmanfm-qt supports integration of 7 archive managers and more can be added but the integration should be defined first. A mechanism could be added for detecting and selecting the first installed archive manager automatically but it would take extra CPU time at startup, which we don't want.

**Comment by Kitsune64** [comment]
Personally I have encouted exactly the same issue about lxqt-archiver. I have attempt few ways to use it correctly but that doesn't working on Debian 13 (trixie).

What doesn't work:
sudo dpkg-reconfigure lxqt-archiver
sudo apt autoremove --purge lxqt-archiver
(and after) sudo apt install lxqt-archiver.

So "ark" must be installed for the solution proposed here but an other way is to get a working archiver software is to use this one **xarchiver** instead of lxqt-archiver.
So...
sudo apt autoremove --purge lxqt-archiver
sudo apt install xarchiver

and put the pcmanfm-qt preference to use xarchiver in the advanced tab options instead of lxqt-archiver or ark.

**Comment by stefonarch** [comment]
> Personally I have encountered exactly the same issue about lxqt-archiver. I have attempt few ways to use it correctly but that doesn't working on Debian 13 (trixie).


Did you install the recommended packages too for lxqt-archiver? E.g. if `rar` isn't installed in can't extract rar files and so on. It works perfectly on Trixie here.

**Comment by Kitsune64** [comment]
Usually not but I have try this just now:
sudo apt autoremove --purge xarchiver
sudo apt install --install-recommends lxqt-archiver

Same issue about lxqt-archiver
I use a *.7z file (password protected) for the test and p7zip-full is already installed.

By this way lxqt-archiver don't ask me about password for the archive and don't extract it. No issue with xarchiver about this 7z archive.

**Comment by isf63** [comment]
Not sure if it'll work, but you may want to try the `7zip`/`7z` package, there's subtle differences between that and `p7zip`. I don't remember the details but some major distros were moving towards the official 7z and we made a change.

**Comment by Kitsune64** [comment]
I have installed p7zip, p7zip-full,7zip and 7zip-standalone packages with lxqt-archiver:
the same issue as mentionned before continue to exist.
I have selected lwqt-archiver in pcmanfm-qt but same issue.
