### ISSUE TITLE
Fresh install on Arch

### ISSUE THREAD

**Issue by alexzk1** [lxqt/lxqt#1726]
Fresh install of lxqt group on archlinux with latest qt 5.12 (full qt5 group):
![IMG_2927](https://user-images.githubusercontent.com/4589845/60227860-84fb7100-9899-11e9-8076-c061c0903d74.JPG)

(sometimes same happens on another machine which I do periodical upgrades during last 4 years, but I forgot how I fixed that last time in winter).

> pacman -Qs lxqt
> local/liblxqt 0.14.1-1
>     Common base library for LXQt components.
> local/lximage-qt 0.14.1-1 (lxqt)
>     The LXQt image viewer and screenshot tool
> local/lxqt-about 0.14.1-1 (lxqt)
>     LXQt about dialog.
> local/lxqt-admin 0.14.1-1 (lxqt)
>     LXQt system administration tool.
> local/lxqt-config 0.14.1-1 (lxqt)
>     LXQt system configuration.
> local/lxqt-globalkeys 0.14.1-1 (lxqt)
>     LXQt daemon and library for global keyboard shortcuts registration.
> local/lxqt-notificationd 0.14.1-1 (lxqt)
>     LXQt notification daemon and library.
> local/lxqt-openssh-askpass 0.14.1-1 (lxqt)
>     LXQt openssh password prompt
> local/lxqt-panel 0.14.1-1 (lxqt)
>     The LXQt desktop panel
> local/lxqt-policykit 0.14.1-1 (lxqt)
>     The LXQt policykit authentication agent
> local/lxqt-powermanagement 0.14.1-1 (lxqt)
>     LXQt power management daemon
> local/lxqt-qtplugin 0.14.0-1 (lxqt)
>     LXQt platform integration for Qt
> local/lxqt-runner 0.14.1-1 (lxqt)
>     The LXQt application launcher
> local/lxqt-session 0.14.1-1 (lxqt)
>     The LXQt session manager
> local/lxqt-sudo 0.14.1-1 (lxqt)
>     LXQt privilege program (lxsu).
> local/lxqt-themes 0.14.0-1 (lxqt)
>     LXQt themes, graphics and icons.
> local/obconf-qt 0.14.0-1 (lxqt)
>     Openbox configuration tool. Qt port of ObConf
> local/openbox 3.6.1-4 (lxde lxde-gtk3 lxqt)
>     Highly configurable and lightweight X11 window manager
> local/pcmanfm-qt 0.14.1-1 (lxqt)
>     The LXQt file manager, Qt port of PCManFM
> local/qterminal 0.14.1-1 (lxqt)
>     A lightweight Qt-based terminal emulator
> local/screengrab 1.101-1 (lxqt)
>     Crossplatform tool for grabbing screenshots of your desktop.
>

**Comment by tsujan** [comment]
Something very basic should be missing or corrupt to make such a spectacle, most of which is pitch-black. Although it piques curiosity it doesn't belong to LXQt issue tracker.

**Comment by alexzk1** [comment]
Missing icons theme (since fresh installation - none was installed).
Shouldn't it rollback to something very basic or at least print message to syslog - no icons.
Was only 1 related message there, QFont reported negative sizes.

**Comment by tsujan** [comment]
In an ideal world, AUR lxqt packages should recommend (optionally depend on) basic packages that prevent your screenshot *if you install all optional dependencies*. Whether that's the case or not, I don't know but if it isn't, it should be reported to Arch.

**Comment by alexzk1** [comment]
That is common tendency of bad coding ... qt (or lxqt) breaks with no icons ..(still think default algo of qt fails, and you don't expect it), openjdk fails if some fonts are missing, while whole system OK... my all current PCs (5 different years, youngest is 2014) fail with "CPU damaged" if rebooted without poweroff (hello specter/firmware fixes) ...
..many examples during last years. I just tired to be honest to fight.

**Comment by tsujan** [comment]
> That is common tendency of bad coding

Or, better said, a tendency to ignore "Optional Deps/Recommends" while taking no responsibility.

**Comment by alexzk1** [comment]
While we're chatting here...can I ask why it wants JS60 dependency? >: Hope you're not going to replace widgets by qml ...or you did already ? >:
I quit KDE because of it.

**Comment by tsujan** [comment]
> why it wants JS60 dependency?

"It"? JavaScript interpreter may be required by several packages, like polkit.

> Hope you're not going to replace widgets by qml

If LXQt does that, I'll say goodbye to it ;) See https://github.com/lxqt/lxqt/issues/1433

As for "bad coding", you may already know that, generally, Linux/Unix doesn't prevent users from doing stupid things, while guiding them through various tasks. It's up to them to learn from their mistakes.

In comparison, some OS's have "good coding", preventing users from making any mistake — other than installing them.

**Comment by alexzk1** [comment]
Yeh, nice 1433 .. in general, it is bad idea to use any interpreter for day-by-day repeated tasks ... IT scientists found in 1980's yet, that best way is to prototype something using interpreter then compile. That's why it was both for BASIC/PASCAL/etc. back that days ... now history wheel turned and everybody love interpreters again...

**Comment by tsujan** [comment]
Some tools may encourage coding by making it easier for newbies but at the expense of good coding. That *may be* a subjective point of view but the discrepancy QML/QQC2 creates in a DE is quite objective. Frankly, I hate it.
