### ISSUE TITLE
Icons of Audio, Notifications, and Removable devices not visible in panel 

### ISSUE THREAD

**Issue by r2011** [lxqt/lxqt#1727]
##### Expected Behavior

The icons for Audio, Notifications and Removable devices should be seen in the panel.

##### Current Behavior

When I log into Lxqt, these icons are not visible in the panel though they are perfectly usable and functional. Only the icons are not getting displayed.

##### Steps to Reproduce (for bugs)

1. 
2. 
3. 
4. 

##### Context

Not a problem as the Audio, Notifications and Removable devices widgets do work in the panel. But it feels ugly while using the desktop. 

##### System Information

* Distribution & Version:  Manjaro Linux [Rolling release distribution]
* Kernel: Linux 4.19.49-1-MANJARO
* Qt Version: 0.14.1-1
* liblxqt Version: 0.14.1-1
* Package version: 0.14.1-1

![Screenshot_2019-07-06_17-48-20](https://user-images.githubusercontent.com/926672/60756065-578b9180-a016-11e9-8f10-0ff4ea096e08.png)

**Comment by agaida** [comment]
we are not willing to follow:
a) not fully filled out bug reports
b) poor installed LXQt

Please don't take it as offense - but we know manjaro working fine, one of our main developers use it. And (beside the fact that i'm a debian guy and prefer pure Arch linux otherwise) i know it to work too, if all optional packages installed like iconsets and so on.

So there is nothing we can or want to do. @tsujan: Thoughts?

**Comment by tsujan** [comment]
> @tsujan: Thoughts?

Even an icon set as poor as Adwaita has the required icons. The problem may be in the icon theme or incomplete installation.

And yes, LXQt definitely works well on Manjaro -- I'm a Manjaro user and even if I wasn't, I'd know that because LXQt works well on Arch.

**Comment by agaida** [comment]
and i know the poor appearance with debian before i made some icon themes recommended - when installed from within another DE it might be that the only installed icon set is GNOME :dark_sunglasses:

So in harsh words: Not really our problem and you might have be missed other things too ...
Not so harsh: Install and chose papirus, faenza, oxygen, breeze and be done with exactly this problem - we don't know your installation. (With all of my distribution hats on)

**Comment by tsujan** [comment]
> and i know the poor appearance with...

Yes, the appearance may be poor with some gtk icon sets -- and that's expected -- but the lack of some icons can be a sign of a bad/incomplete installation too (or, perhaps, a problematic icon set, although I can't be sure).
