### ISSUE TITLE
Replace deprecated Qt methods

### ISSUE THREAD

**Issue by tsujan** [lxqt/lxqt#1728]
Qt 5.13 deprecated several old methods at last, as was expected. For example, I'd removed `QDesktopWidget` from pcmanfm-qt before but now it should be removed from other LXQt components (like lxqt-notificationd) too because, otherwise, it could cause serious problems (which I'd seen in older versions of pcmanfm-qt). There are also other deprecated methods here and there, like `QFontMetrics::width`, `QModelIndex::child`, `QImage::byteCount`, etc. All of them could be found during compilations against Qt 5.13.

I'll update libfm-qt soon. I opened this issue as a reminder for other LXQt components: We need to update LXQt's code (in a backward compatible way, in some places).

EDIT: I also checked KDE. Their amount of deprecated methods is enormous. Ours is quite manageable.

**Comment by yan12125** [comment]
> QFontMetrics::width

This function might be a problem. Qt recommends `QFontMetrics::horizontalAdvance()` as a replacement [1]. However, the latter function requires Qt 5.11+ [2]. In qtermwidget, I use macros in the WIP patch to keep compatibility with older Qt versions [3]. My approach is ugly - not sure if it's a good idea to drop support for Qt < 5.11 to get clean codes.

[1] https://github.com/qt/qtbase/blob/v5.13.0/src/gui/text/qfontmetrics.h#L106-L113
[2] https://doc.qt.io/qt-5/qfontmetrics.html#horizontalAdvance
[3] https://github.com/lxqt/qtermwidget/blob/eliminate-warnings/lib/TerminalDisplay.cpp#L214-L222

**Comment by tsujan** [comment]
@yan12125 

Today, in Kvantum, I replaced it like:
```c++
#if (QT_VERSION >= QT_VERSION_CHECK(5,11,0))
...
```
Without dropping support for Qt < 5.11. IMHO, such lines couldn't be avoided in the long run but, once in a while, there should be a cleanup.

**Comment by tsujan** [comment]
Closing this because it'll be an everlasting problem. More Qt methods have been deprecated since 2019 and we'll replace them when our minimum required version of Qt allows that. They can be easily tracked by a glance at compilation warnings.
