### ISSUE TITLE
konsole as console

### ISSUE THREAD

**Issue by alphaonex86** [lxqt/lxqt#1729]
##### Expected Behavior
I have configured konsole as console, use it when I click on .desktop file to ssh command, with checkbox checked: open in terminal

##### Current Behavior
Actually it open into xterm

##### System Information
* Distribution & Version: Gentoo
* Qt Version: 5.12
* liblxqt Version: 0.14.1
* Package version: 0.14.1

##### Other
konsole is well registred into the config file

**Comment by tsujan** [comment]
> I have configured konsole as console

How? If you select konsole as the terminal emulator in pcmanfm-qt, your command will be run in konsole, not xterm.

Not reproducible.

**Comment by alphaonex86** [comment]
Into the default app:
/home/user/.config/lxqt/session.conf
[Environment]
TERM=/usr/bin/konsole
 I open .desktop on desktop folder list.

**Comment by tsujan** [comment]
> /home/user/.config/lxqt/session.conf... TERM=/usr/bin/konsole...

Ignore that! Instead, go to `pcmanfm-qt → Preferences → Advanced → Terminal emulator` and choose a terminal.

I agree that `TERM` is confusing and might need to be removed. However, all files are opened by pcmanfm-qt, so the real setting is in its Preferences dialog.
