### ISSUE TITLE
Shortcuts aren't save from one session to another

### ISSUE THREAD

**Issue by BenoitPingris** [lxqt/lxqt#1732]
I configured my shortcuts throught the `lxqt-config-globalkeyshortcuts` so I can use `Meta+{key}` to switch to particular workspace.

##### Expected Behavior
My custom shortcuts should stay the same from one session to another

##### Current Behavior
Some shortcuts aren't saved or are even different than the default ones.

##### Context
I configured 4 shortcuts for 4 workspaces:
- `Meta+ampersand` : wk 1
- `Meta+eacute`: wk 2
- `Meta+doublequote`: wk 3
- `Meta+apostrophe`: wk 4
Once I did this everyting works well.

However once I logout here are my shortcuts:
![image](https://user-images.githubusercontent.com/29386109/61325713-97702700-a815-11e9-9a75-a4cea3a11985.png)
You can see that my shortcut for the workspace 1 is now `Meta + 1` (but `Meta+ampersand` works) and some are the same and so on.

##### System Information
* Distribution & Version: Manjaro Linux x86_64 
* Kernel:  Linux 4.19.56-1-MANJARO
* Qt Version:  5.12.1
* liblxqt Version: 0.14.1

**Comment by BenoitPingris** [comment]
## Update

I tried to edit the file `lxqt-rc.xml` located in `$HOME/.config/openbox` and added keybindings in it as following:
```xml
    <keybind key="W-ampersand">
            <action name="GoToDesktop">
                    <to>
                            1
                    </to>
            </action>
    </keybind>
    <keybind key="W-eacute">
            <action name="GoToDesktop">
                    <to>
                            2
                    </to>
            </action>
    </keybind>
    <keybind key="W-doublequote">
            <action name="GoToDesktop">
                    <to>
                            3
                    </to>
            </action>
    </keybind>
    <keybind key="W-apostrophe">
            <action name="GoToDesktop">
                    <to>
                            4
                    </to>
            </action>
    </keybind>
```

It turns out it works, and works even after the end of a session. I'll close this issue but I'm not sure this behavior is normal :smile:

**Comment by agaida** [comment]
This behaviour is normal for openbox - not for lxqt-globalkeyshortscuts - what you did: You delegated the shortcuts from globalkeys to the WM
