### ISSUE TITLE
question of how|where to find

### ISSUE THREAD

**Issue by alexzk1** [lxqt/lxqt#1733]
So, there are some "long starting" applications, like steam. They may startup 5-10-15 seconds and then bring their main window.
Usually I don't wait and keep typing somewhere/something in another program..
So question is, is any way to disable their pop-up on top ? I tried to disable open box setting "focus new window", but that works only for keyboard.

So basically question is better, if user activly interacts witth window Z-order top, then any new window must be Z-order (top -1) and not (top). Any ideas what to google or to set? >:

**Comment by tsujan** [comment]
Most window managers have settings for what's usually called "focus stealing prevention". How effective a WM's focus stealing prevention is depends on its code. However, GUI apps can ignore it (for example, I've included s simple code in FeatherNotes to bypass it).

Please also note that WM settings aren't a part of LXQt. You could use any DE-agnostic WM with LXQt.

**Comment by alexzk1** [comment]
Yeh, problem is "focus" and "window top" are 2 different calls to xserver. Guess my openbox just keeps focus but allows window to draw top in z-order.

**Comment by tsujan** [comment]
> Guess my openbox just keeps focus but allows window to draw top in z-order.

For windows that can have focus, that's a little weird. An openbox user might be able to answer your question.
