### ISSUE TITLE
"DesktopSwitch Settings" 

### ISSUE THREAD

**Issue by pvasegh** [lxqt/lxqt#1736]
I can not add another Row. When increasing "Number of Rows" field to "2", I'm expecting to see additional line under "Desktop names"; but that doesn't happen. Also, missing "Apply" button.
I am stuck with only one desktop and can not add more!?

##### Steps to Reproduce (for bugs)

1. 
2. 
3. 
4. 

##### System Information

* Distribution & Version: Arch (Namib) latest
* Kernel: 5.2.6 (not related)
* Qt Version: 5.13.0
* liblxqt Version: 0.14.1
* Package version: 0.14.1

**Comment by palinek** [comment]
Desktoswitch is only a pager for the window manager. It doesn't anyhow set the number of virtual desktops. Number of desktops needs to be configured in your VM settings.
