### ISSUE TITLE
UPS not showing as battery

### ISSUE THREAD

**Issue by tenplus1** [lxqt/lxqt#1739]
The lxqt-powermanagement doesn't appear showing my UPS (APC ES550) as a battery where xfce, gnome, kde and even icewm all do...  Could this be fixed ?

**Comment by bjlockie** [comment]
I think it is for laptops not UPSes,

Do the other window managers interface with NUT to interface with a UPS?

**Comment by tsujan** [comment]
→ https://github.com/lxqt/lxqt-powermanagement/issues/169
