### ISSUE TITLE
lxqt-globalkeys fails to detect the combinations of meta with E, D and R

### ISSUE THREAD

**Issue by zyxdef** [lxqt/lxqt#1740]
When I tried to create new keyboard shortcuts, I noticed that the box beside the title *Shortcut* in the *Edit action* dialog was not able to detect (and, therefore, to associate) the combination of meta key with three specific letters (viz., E, D and R).

Since I am using the pt-br translation of lxqt-globalkeys, I am presuming from the terms in Portuguese the original names and texts of the dialogs and windows in English.  Please, bear that in mind in case it seems I am naming things through oddly.

##### Expected Behavior

I expected to shortcut RStudio to `meta`+`R`, so I would have to add a new action and, in the dialog window that followed, I would click in the shortcut button in order to capture the `meta`+`R` keystroke. That button was supposed to show as its text from capture on the value "meta+R".

##### Current Behavior

The shortcut capture does not seem to notice `meta`+`R` was stroke, since it neither show "meta+R" as its new text nor allows to conclude with the inclusion of the new actions once you fill the other fields. After noticing that oddity, I tried to capture `meta` key with every other letter, numeral or punctuation key.  Every other key was detected in combination with `meta`, except for `R`, `E` and `D`.

##### Possible Solution

I have no idea whatsoever. I have been searching this problem for at least a month and have not found any reference to this problem, so I ended up filling this issue report.

##### Steps to Reproduce (for bugs)

1. In the *lxqt-globalkeys* window, click on `Add...` button
2. In the *Edit action* dialog, click on the button to the right of *Shortcut:* text
3. Wait until the start of the countdown of the keystroke combination capture
4. Hit `meta` and `F` keys, in this order

##### Context

This issue impacted in the slightest, since I use the shortcut `meta`+`Alt`+`R` instead, since `meta` and `Alt` are neighbors and can be stroke together with the left thumb, leaving `R` to the index finger.

Nevertheless, that quirky kind of behavior described above is unexpected, undesirable and should not occur in any serious piece of software

##### System Information

* Distribution & Version: Lubuntu 19.04
* Kernel: 5.0.0-25-generic
* Qt Version: 5.12.2
* liblxqt Version: 0.14.1
* Package version: 0.14.1

**Comment by tsujan** [comment]
Not reproducible.

If the shortcut you type is consumed elsewhere, you might not be able to add it. For example, here `Meta+E` is taken by KWin for showing all virtual desktops, so that I can't type it but, once I remove it from KWin, I can.

**Comment by agaida** [comment]
@wxl - we should really rewrite the bug form

Here not reproducible too

**Comment by agaida** [comment]
@zyxdef - unfortunatelly your last sentence made your whole bug report worthless - beside the fact that we can't reproduce - if you are thinking about you will agree that:
* a bunch of people who are to dumb to notice __your__ problem for over five years can't be serious - same for the software they work on
* if they are so dumb/ignorant/anything else - why you are filing a bug, it don't make any sense

Ok, and now to some real world problems with the next bug
