### ISSUE TITLE
World clock widget text doesn't fit into the taskbar panel

### ISSUE THREAD

**Issue by janprunk** [lxqt/lxqt#1741]
Package: lxqt-panel
Version: 0.14.1-1
Severity: normal

Dear Maintainer,

I experienced a bug with the World clock widget in LXQt in the stable
Debian buster release. If I try to configure the world clock widget by using 
time in seconds, minutes and hour it fits well on the right side of the 
taskbar panel. If I try to add the date on the top or bottom of the time 
widget it will not render the text nicely, it overlaps. Placing date on 
the left or right side of the time widget works fine. I have tested this 
also on another machine (arm port) and the problem is the same.

Kind regards, 
Jan Prunk

-- System Information:
Debian Release: 10.0
  APT prefers stable
  APT policy: (500, 'stable')
Architecture: amd64 (x86_64)

Kernel: Linux 4.19.0-5-amd64 (SMP w/4 CPU cores)
Locale: LANG=en_US.UTF-8, LC_CTYPE=en_US.UTF-8 (charmap=UTF-8), LANGUAGE=en_GB:en (charmap=UTF-8)
Shell: /bin/sh linked to /bin/dash
Init: systemd (via /run/systemd/system)
LSM: AppArmor: enabled

Versions of packages lxqt-panel depends on:
ii  libasound2              1.1.8-1
ii  libc6                   2.28-10
ii  libdbusmenu-qt5-2       0.9.3+16.04.20160218-1
ii  libkf5solid5            5.54.0-1
ii  libkf5windowsystem5     5.54.0-1
ii  liblxqt-globalkeys-ui0  0.14.1-1
ii  liblxqt-globalkeys0     0.14.1-1
ii  liblxqt0                0.14.1-1
ii  libpulse0               12.2-4
ii  libqt5core5a            5.11.3+dfsg1-1
ii  libqt5dbus5             5.11.3+dfsg1-1
ii  libqt5gui5              5.11.3+dfsg1-1
ii  libqt5widgets5          5.11.3+dfsg1-1
ii  libqt5x11extras5        5.11.3-2
ii  libqt5xdg3              3.3.1-2
ii  libqt5xml5              5.11.3+dfsg1-1
ii  libsensors5             1:3.5.0-3
ii  libstatgrab10           0.91-1+b2
ii  libstdc++6              8.3.0-6
ii  libsysstat-qt5-0        0.4.2-1
ii  libx11-6                2:1.6.7-1
ii  libxcb-xkb1             1.13.1-2
ii  libxcb1                 1.13.1-2
ii  libxcomposite1          1:0.4.4-2
ii  libxdamage1             1:1.1.4-3+b3
ii  libxkbcommon-x11-0      0.8.2-1
ii  libxkbcommon0           0.8.2-1
ii  libxrender1             1:0.9.10-1
ii  lxmenu-data             0.1.5-2
ii  lxqt-policykit          0.14.1-1

Versions of packages lxqt-panel recommends:
ii  lxqt-about          0.14.1-1
ii  lxqt-config         0.14.1-2
ii  lxqt-notificationd  0.14.1-1
ii  lxqt-panel-l10n     0.14.1-1
ii  lxqt-qtplugin       0.14.0-3
ii  lxqt-runner         0.14.1-1
ii  lxqt-session        0.14.1-2
ii  pavucontrol         3.0-4
ii  pavucontrol-qt      0.14.1-1
ii  qlipper             1:5.1.2-1

Versions of packages lxqt-panel suggests:
ii  lxqt       29
ii  lxqt-core  29

-- Configuration Files:
/etc/xdg/lxqt/panel.conf changed:
[General]
iconTheme=Papirus-Dark
[kbindicator]
alignment=Right
type=kbindicator
[quicklaunch]
alignment=Left
apps\1\desktop=/usr/share/applications/pcmanfm-qt.desktop
apps\2\desktop=/usr/share/applications/qterminal.desktop
apps\3\desktop=/usr/share/applications/featherpad.desktop
apps\size=3
type=quicklaunch
[quicklaunch2]
alignment=left
apps\1\desktop=/usr/share/applications/lxqt-leave.desktop
apps\size=1
type=quicklaunch
[panel1]
plugins=mainmenu, showdesktop, desktopswitch, quicklaunch, taskbar, kbindicator, tray, statusnotifier, mount, volume, worldclock, quicklaunch2
[taskbar]
buttonWidth=200
raiseOnCurrentDesktop=true

-- no debconf information

**Comment by tsujan** [comment]
Go to `Configure Panel` and increase the value of the `Size` spin-box.

**Comment by tsujan** [comment]
BTW, this report didn't seem to have been written for LXQt. Please use the template!
