### ISSUE TITLE
When perform "git submodule update" command with this repository git asks me for username

### ISSUE THREAD

**Issue by TrachIvan** [lxqt/lxqt#1742]
This is not a bug, but I cant find any solution so I ask here how I can resolve such issue. Could any one help me with this?
**git submodule update
Клонування в 'compton-conf'...
remote: Enumerating objects: 39, done.
remote: Counting objects: 100% (39/39), done.
remote: Compressing objects: 100% (24/24), done.
remote: Total 1119 (delta 26), reused 21 (delta 15), pack-reused 1080
Отримання об’єктів: 100% (1119/1119), 250.56 KiB | 0 bytes/s, виконано.
Обробка відмінностей: 100% (765/765), виконано.
Перевірка з’єднання… виконано.
Підмодуль за шляхом «compton-conf»: забрано стан «e71ee4c9a6e3a3b579543bb0e6d969b585ff3209»
Клонування в 'libfm'...
remote: Enumerating objects: 22074, done.
remote: Total 22074 (delta 0), reused 0 (delta 0), pack-reused 22074
Отримання об’єктів: 100% (22074/22074), 14.03 MiB | 5.39 MiB/s, виконано.
Обробка відмінностей: 100% (16834/16834), виконано.
Перевірка з’єднання… виконано.
Підмодуль за шляхом «libfm»: забрано стан «b08218e2311dc52465ef92502061738701f298c1»
Клонування в 'libfm-qt'...
remote: Enumerating objects: 49, done.
remote: Counting objects: 100% (49/49), done.
remote: Compressing objects: 100% (41/41), done.
remote: Total 7052 (delta 18), reused 13 (delta 8), pack-reused 7003
Отримання об’єктів: 100% (7052/7052), 3.07 MiB | 2.52 MiB/s, виконано.
Обробка відмінностей: 100% (5542/5542), виконано.
Перевірка з’єднання… виконано.
Підмодуль за шляхом «libfm-qt»: забрано стан «ff6beead85f37830c08a59592883b649ecda0733»
Клонування в 'liblxqt'...
remote: Enumerating objects: 4075, done.
remote: Total 4075 (delta 0), reused 0 (delta 0), pack-reused 4075
Отримання об’єктів: 100% (4075/4075), 1.45 MiB | 1.49 MiB/s, виконано.
Обробка відмінностей: 100% (2950/2950), виконано.
Перевірка з’єднання… виконано.
Підмодуль за шляхом «liblxqt»: забрано стан «24c1c943b87ffc4492ca0db1747691534ce3e77e»
Клонування в 'libqtxdg'...
remote: Enumerating objects: 76, done.
remote: Counting objects: 100% (76/76), done.
remote: Compressing objects: 100% (51/51), done.
remote: Total 2475 (delta 37), reused 52 (delta 25), pack-reused 2399
Отримання об’єктів: 100% (2475/2475), 846.98 KiB | 0 bytes/s, виконано.
Обробка відмінностей: 100% (1637/1637), виконано.
Перевірка з’єднання… виконано.
Підмодуль за шляхом «libqtxdg»: забрано стан «fc6b455a7ede30a4b3db73c2af06dfa44af585ea»
Клонування в 'libsysstat'...
remote: Enumerating objects: 24, done.
remote: Counting objects: 100% (24/24), done.
remote: Compressing objects: 100% (21/21), done.
remote: Total 435 (delta 17), reused 4 (delta 2), pack-reused 411
Отримання об’єктів: 100% (435/435), 127.20 KiB | 0 bytes/s, виконано.
Обробка відмінностей: 100% (280/280), виконано.
Перевірка з’єднання… виконано.
Підмодуль за шляхом «libsysstat»: забрано стан «9e644cbcbeb9723714431598cd254dac448efb15»
Клонування в 'lximage-qt'...
remote: Enumerating objects: 66, done.
remote: Counting objects: 100% (66/66), done.
remote: Compressing objects: 100% (41/41), done.
remote: Total 2810 (delta 43), reused 33 (delta 24), pack-reused 2744
Отримання об’єктів: 100% (2810/2810), 965.01 KiB | 0 bytes/s, виконано.
Обробка відмінностей: 100% (2197/2197), виконано.
Перевірка з’єднання… виконано.
Підмодуль за шляхом «lximage-qt»: забрано стан «7d7260744543710e89e7f09d53757a18b6825ac4»
Клонування в 'lxmenu-data'...
remote: Enumerating objects: 1203, done.
remote: Total 1203 (delta 0), reused 0 (delta 0), pack-reused 1203
Отримання об’єктів: 100% (1203/1203), 519.97 KiB | 0 bytes/s, виконано.
Обробка відмінностей: 100% (991/991), виконано.
Перевірка з’єднання… виконано.
Підмодуль за шляхом «lxmenu-data»: забрано стан «54261d21636580597467b960a58c5329de1b089e»
Клонування в 'lxqt-about'...
remote: Enumerating objects: 105, done.
remote: Counting objects: 100% (105/105), done.
remote: Compressing objects: 100% (64/64), done.
remote: Total 1402 (delta 67), reused 65 (delta 40), pack-reused 1297
Отримання об’єктів: 100% (1402/1402), 344.57 KiB | 0 bytes/s, виконано.
Обробка відмінностей: 100% (1001/1001), виконано.
Перевірка з’єднання… виконано.
Підмодуль за шляхом «lxqt-about»: забрано стан «7153a71e061113d9daea3b7d4c22cf83c987b97d»
Клонування в 'lxqt-admin'...
remote: Enumerating objects: 22, done.
remote: Counting objects: 100% (22/22), done.
remote: Compressing objects: 100% (18/18), done.
remote: Total 2209 (delta 11), reused 6 (delta 4), pack-reused 2187
Отримання об’єктів: 100% (2209/2209), 720.44 KiB | 1.36 MiB/s, виконано.
Обробка відмінностей: 100% (1763/1763), виконано.
Перевірка з’єднання… виконано.
Підмодуль за шляхом «lxqt-admin»: забрано стан «5d8678a974e5832fea9e1f6f871b21e05cc9fbc3»
Клонування в 'lxqt-archiver'...
Username for 'https://github.com': 
Password for 'https://github.com':**

**Comment by ito32bit** [comment]
I was the same, too.
You can change `lxde` to `lxqt`.

<https://github.com/lxqt/lxqt/wiki/Building-from-source#scripts-to-build-in-one-step>
```
git clone https://github.com/lxde/lxqt.git ->
git clone https://github.com/lxqt/lxqt.git
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^~~~~~~~~~
```

**Comment by TrachIvan** [comment]
> I was the same, too.
> You can change `lxde` to `lxqt`.
> 
> https://github.com/lxqt/lxqt/wiki/Building-from-source#scripts-to-build-in-one-step
> 
> ```
> git clone https://github.com/lxde/lxqt.git ->
> git clone https://github.com/lxqt/lxqt.git
> ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^~~~~~~~~~
> ```
Hi,

Thank you very much for help, it worked for me. 

But I have one more question, I would like to build lxqt with LST qt build QT 5.6 is it possible? Latest support version is Qt5.7, when I am trying to build lxqt-0.10.0, submodules can not be initialized.

There is any way to do this?

Thanks, Ivan

**Comment by agaida** [comment]
i don't understand the need to build a several years old release - anyways, building LXQt that way from a checkout is the worst thing one can do. It bring no real benefit and we should just remove the scripts. Just see it as a historical artefact we don't have removed yet.

**Comment by TrachIvan** [comment]
Hi Agaida, 

I just wanted to buld lxqt with LTS Qt version 5.6.1 but latest version requires at list 5.7.3 so I just wondered is it possible and can I do it by building previous lxqt version.

Thank you very much for yours answers, they were very helpful.

Thanks, Ivan

**Comment by tsujan** [comment]
> I just wondered is it possible and can I do it by building previous lxqt version.

Previous versions are considered deprecated; no support at all.
