### ISSUE TITLE
Idleness watcher not working anymore

### ISSUE THREAD

**Issue by stefonarch** [lxqt/lxqt#1744]
After recompiling latest git it looks like the idleness watcher doesn't work. Tested also on a newly created user
##### Steps to Reproduce (for bugs)

1. Activate idleness watcher in power settings, set to 1 minute (suspend)
2. wait
3. nothing happens...

##### System Information

* Distribution & Version: arch & latest git checkout

EDIT: lock screen is working, suspend not, other to test yet
EDIT 2: setting it to 1 min and 1 sec suspend works, with 0 sec no.

**Comment by tsujan** [comment]
Not reproducible here with the latest git `lxqt-powermanagement `. Suspend after a 1-min idleness works without problem here.

Except for code clean-ups, `lxqt-powermanagement` hasn't changed. Maybe, you had other updates and your system needed a reboot.

**Comment by stefonarch** [comment]
Reboot was the first I did, then testing another user, with .config/lxqt deleted first.
Dunno why but now it's working again also with 0 seconds.
