### ISSUE TITLE
compiling lxqt

### ISSUE THREAD

**Issue by bjlockie** [lxqt/lxqt#1745]
I did this:

    $ cd /hdd-storage/temp-downloads
    $ git clone https://github.com/lxqt/lxqt.git
    $ git submodule init
    $ git submodule update --remote --rebase

    ./build_all.sh

I got this error:

`-- Build files have been written to: /hdd-storage/temp-downloads/lxqt/libqtxdg/build
[  3%] Building CXX object xdgiconloader/CMakeFiles/Qt5XdgIconLoader.dir/xdgiconloader.cpp.o                                                                    
In file included from /hdd-storage/temp-downloads/lxqt/libqtxdg/xdgiconloader/xdgiconloader.cpp:34:
/hdd-storage/temp-downloads/lxqt/libqtxdg/xdgiconloader/xdgiconloader_p.h:56:10: fatal error: private/qicon_p.h: No such file or directory
`

**Comment by tsujan** [comment]
The recommended compilation method is distro package building.

@agaida Apart from this, are `build_all.sh` and related scripts worth maintaining? IMVHO, a big warning may be needed in the documentation.

**Comment by bjlockie** [comment]
I had hoped to compile and run it from my hard drive.

**Comment by agaida** [comment]
@tsujan - it might be nice for advanced users and not yet supported distributions - and we have to live with users who are not able to read the wiki and solve problems themself - aka installing the needed dependencies before. 

@bjlockie - you would need qt private headers to go on - and i recommend not to do.

**Comment by tsujan** [comment]
> it might be nice for advanced users and not yet supported distributions

Understood.

I don't think advanced users ever prefer it to clean packaging but distros that aren't supported may need it.
