### ISSUE TITLE
Block panel doesn't block quick launch elements

### ISSUE THREAD

**Issue by stefonarch** [lxqt/lxqt#1746]
Not sure if it's a bug, but one could say "I have my panel blocked and it shouldn't be possible to remove icons from quick launch widget."

It happens that fast clicking 

##### Expected Behavior

Panel blocked: no changes possible
##### Current Behavior

It's possible to remove or add quick launch elements.

**Comment by tsujan** [comment]
> Not sure if it's a bug

IMO, it is. The behavior isn't self-consistent.

**Comment by tsujan** [comment]
This reminds me of another thing (about fast clicking): LXQt needs a setting for minimum drag distance. I didn't find any.

**Comment by stefonarch** [comment]
The "fast clicking" wasn't complete up there, but yes, it happens click and drag and then click on "remove" in the menu that opens.

**Comment by tsujan** [comment]
> but yes, it happens click and drag and then click on "remove" in the menu that opens.

I'd encountered this problem in KDE several years ago (when I was a KDE4 user). Have never encountered it in LXQt but a setting for DND distance would be nice.

**Comment by tsujan** [comment]
The fix is here: https://github.com/lxqt/lxqt-panel/pull/1180
