### ISSUE TITLE
Lubuntu/LXQt not parking HDD

### ISSUE THREAD

**Issue by heldernovais** [lxqt/lxqt#1747]
My external HDD is not parker/spundown as the system shutsdown.

##### Expected Behavior
I select "Shutdown" and the system parks the external hdd normally.

##### Current Behavior
I select "Shutdown" and it abruptly shuts the system down seconds thereafter, not even parking/spinning the hdd down. This ruins the disc.

##### Possible Solution
Perhaps change the shutdown scripts to park all the discs first?
umount /media/<user>/*
umount /dev/sd*
hdparm -y /dev/sd*

##### Steps to Reproduce (for bugs)
1. Press super
2. Shutdown
3. wait
4. hear the fast SQUEAK from the HDD.

##### Context
This ruins the hdd. Also, it is my main hdd (for work data) and I typically shut the system down right after I finish using it.

##### System Information
* Distribution & Version: Lubuntu 18.04 (as it came)

**Comment by tsujan** [comment]
I think you need to report your problem to systemd; it's responsible for shutdown.

**Comment by heldernovais** [comment]
Thank you.

**Comment by heldernovais** [comment]
Wouldn't the problem possibly be handled by the pcmanqt? Doesn't

**Comment by agaida** [comment]
Its not a systemd problem - it's an problem with the external hdd: Our problem is - are we responible for?
The german answer would be a clear "Jein" - if a user mount a device within the session - what to do on shutdown :D (Imho the best solution is to recommend SSDs)

**Comment by heldernovais** [comment]
It's not a problem with my HDD. With Windows 10, it works normally. The HDD spins down and there's no squeaking noise.

**Comment by heldernovais** [comment]
A few commands on shutdown would fix it. I just think it doesn't unmount it properly by default.

**Comment by agaida** [comment]
Guess what - i have no clue, but i don't think it's an LXQt problem.

**Comment by heldernovais** [comment]
Ach, kein Problem. Tschüss

**Comment by tsujan** [comment]
> i don't think it's an LXQt problem.

It isn't an LXQt problem but I'm not so optimistic about systemd either, although it has shown no symptom here for about a year.

**Comment by agaida** [comment]
one can reproduce it easy:
* in a running LXQt session - open a terminal and type `sudo systemctl stop sddm` - you should reach a tty
* shut down the machine

I would consider a machine running on a tty as fully 'On' so something else should care of - maybe udev. And even if we could do reliable - not our pŕoblem, i would guess udev or something else.

**Comment by tsujan** [comment]
> Wouldn't the problem possibly be handled by the pcmanqt?

As a file manager, pcmanfm-qt isn't responsible for shutdown. It can mount/unmount though.

**Comment by tsujan** [comment]
> not our pŕoblem

That's true. And I like that "ŕ".

**Comment by heldernovais** [comment]
> > Wouldn't the problem possibly be handled by the pcmanqt?
> 
> As a file manager, pcmanfm-qt isn't responsible for shutdown. It can mount/unmount though.

That's why I thought of it so fast. When the file manager/explorer is shutting down, ideally it would unmount all the discs first, no? This could give it some extra time for the spinning to slow down.

**Comment by tsujan** [comment]
> When the file manager/explorer is shutting down

No file manager should unmount anything on exiting and no sane file manager does that on Linux.

**Comment by agaida** [comment]
clearly no - file management has nothing to do with device management

**Comment by heldernovais** [comment]
It does mount the discs, though.

**Comment by heldernovais** [comment]
Maybe there could be an option to attach scripts to the shutdown button?

**Comment by tsujan** [comment]
> It does mount the discs, though.

If the user wants. Other than that, see fstab.

**Comment by tsujan** [comment]
Let me be clear: unmounting on exiting isn't an option. That's the worst behavior one might see in a file manager.

**Comment by agaida** [comment]
there are systemd targets for -  and https://ubuntuforums.org/archive/index.php/t-999324.html

**Comment by heldernovais** [comment]
Another thing (not worth opening a new thread about): Why does Featherpad not include a way of saving all files at once?

**Comment by agaida** [comment]
it can be a task for the DM - if the mount's in charge are user mounts. But unmounting user mounts means not in any way that the drive should be park or spin down

**Comment by agaida** [comment]
What is featherpad? Anything related to LXQt?

**Comment by heldernovais** [comment]
Isn't it the default text editor?

**Comment by agaida** [comment]
https://askubuntu.com/questions/56270/how-can-i-spin-down-external-hard-drive - btw, it is not udev, should be udisks

**Comment by tsujan** [comment]
> Isn't it the default text editor?

It is a text editor that can be used as the default one. It's optional.

As its developer, I think a text editor should never save all modified documents at once -- it would be dangerous -- but it should be able to say "No to All" at once. Moreover, FeatherPad has auto-saving.

Anyways, let's not talk about unrelated things here.

**Comment by heldernovais** [comment]
I first tried using it for programming when I moved onto Lubuntu but found that being the only thing keeping me from using it daily (also, full screen text is useful); but I still use it for general txt editing.
Thank you for making it, too.

**Comment by tsujan** [comment]
I'd really appreciate it if report the problems/suggestions related to FeatherPad at https://github.com/tsujan/FeatherPad/issues.

**Comment by tsujan** [comment]
@heldernovais On second thought, I decided to add "Save All Files" to FeatherPad V0.12.0. Users know what's dangerous for them and what's not.
