### ISSUE TITLE
Copy file / file name

### ISSUE THREAD

**Issue by alexzk1** [lxqt/lxqt#1749]
Ok, not really sure where to place. I just used Ubuntu 16 logged into lxqt session (default by apt-get install lxqt). Qt there is 5.9. Trying to copy file to usb-flash was killing file manager and dmesg showed nullptr in QtGui module somewhere.

So what I think is ... file was named using local lang on desktop (Ukrainian), card was FAT-32 I guess (default from shop), when I copied that file eventually by reloging to Unity it was named as "_______.______" on card. And system default LC_ is not same as lang of file name.
Somehow lxqt cannot handle this situation.

Sorry no more info as I'm not owner of that problem PC.

**Comment by tsujan** [comment]
You could ask random questions in various forums. This is a bug tracker and requires specific information that's mentioned in the template.
