### ISSUE TITLE
i was looking around settings and i acidentally did too much now my screen picture is kinda more blue

### ISSUE THREAD

**Issue by ViktorMYT** [lxqt/lxqt#1750]
i was looking around settings and i acidentally did too much now my screen picture is kinda more blue 

   there's no reset to default button
and i don't know how was it before can someone tell me is there a way to reset it to default config and would it mess up my linux distro, i should try to find where is config file located in, and what then delete it?? it would be good to add reset to default button to the next upgrade of the program    
                    
* OS: Ubuntu & 19.10
* DE: Lubuntu
* Kernel: 5.3.0-19-generic

**Comment by tsujan** [comment]
> there's no reset to default button

A reset button for what? For the whole DE?!

> would it mess up my linux distro

?!

Use a forum for questions.

**Comment by ViktorMYT** [comment]
no for brigtness settings app

**Comment by tsujan** [comment]
> no for brigtness settings app

OK. You could report the bug you've encountered or the feature you want at https://github.com/lxqt/lxqt-config/issues by *filling in the issue template*. The template is there for developers to know what's the problem/feature and how to fix/add it.
