### ISSUE TITLE
Task manager terminal icon change on bell

### ISSUE THREAD

**Issue by picorealm** [lxqt/lxqt#1752]
lxqt-panel 0.14.1
liblxqt   0.14.1
Qt        5.11.3
Debian GNU/Linux bullseye/sid amd64

Terminal application icon on the task manager changes to a bell icon when the terminal emits a bell (even when all notifications are disabled in e.g. konsole).

For example: open konsole and hit the backspace key to produce a bell event.

The icon for konsole on the task manager changes to a bell icon and does not change back to a terminal icon.

Also note that in lxqt Desktop Notifications settings under Advanced Settings -> Ignore these applications I have listed Konsole,konsole

**Comment by tsujan** [comment]
Can't reproduce it. The task bar icon doesn't change and Konsole is excluded from unattended notifications when added to the list.

Some info may be missing from your report. That wouldn't happen if you cared to fill in the template.

**Comment by Chiitoo** [comment]
It's a Konsole issue from some months ago.

To work around it, one can try changing the icon to something else than the default, in the Konsole profile settings, and see if that 'fixes' it for you.

See also: https://bugs.kde.org/show_bug.cgi?id=408458

**Comment by tsujan** [comment]
> It's a Konsole issue from some months ago.

Then, KDE has two bugs related to the current topic: one in its Plasma panel (= not seeing the icon change), the other in the Konsole (not reverting to the terminal icon after the bell).

**Comment by tsujan** [comment]
@Chiitoo I forgot to say that the real report is here: https://github.com/lxqt/lxqt/issues/1753. My conclusion: https://github.com/lxqt/lxqt/issues/1753#issuecomment-546595266

**Comment by Chiitoo** [comment]
Yeah... I noticed it right after replying, when moving on with my e-mail in chronological order.  ^^;

(Should have noticed since the mails about it were right above this one.  I blame sleepy.)

**Comment by tsujan** [comment]
The bug report you mentioned in your comment was a confirmation. Thanks!

Anyhow, the panel codes that set/change task button icons are robust; they can reveal problems like this.
