### ISSUE TITLE
[lxqt-config-brightness] Setting brightness from cmd line not working

### ISSUE THREAD

**Issue by luis-pereira** [lxqt/lxqt#1754]
Setting the brightness from the command line is not working. GUI is working fine.
```
[lpereira@l-pc]$ cat /sys/class/backlight/acpi_video0/brightness 
9
[lpereira@l-pc]$ cat /sys/class/backlight/acpi_video0/max_brightness 
9
[lpereira@l-pc]$ lxqt-config-brightness -s 10
[lpereira@l-pc]$ cat /sys/class/backlight/acpi_video0/brightness 
9
```

##### Expected Behavior
The brightness changes to the set level.

##### Current Behavior
The brightness isn't set.+

##### Possible Solution
Probably the app quits before the brightness is actually set.

##### Steps to Reproduce (for bugs)
See above 

##### System Information
* Distribution & Version:  5.3.7-2-MANJARO
* Kernel: 5.3.7-2-MANJARO
* Qt Version: 5.13.1
* liblxqt Version: git
* Package version: git

**Comment by MarcusE1W** [comment]
For me this works:
```
pkexec lxqt-backlight_backend --inc
pkexec lxqt-backlight_backend --dec
```

This has something to do with permissions, I am not an expert

**Comment by luis-pereira** [comment]
@MarcusE1W It works for me too.  It's not a permissions issue. The issue is in `lxqt-config-brightness` and also in liblxqt. I already fixed the liblxqt part (https://github.com/lxqt/liblxqt/commit/8bbb77285a0756c8663796e222d4317be1bf3a77). I'm testing the lxqt-config-brightness part. Will make a PR soon.

**Comment by luis-pereira** [comment]
@agaida It's a confirmed bug an the fix is at https://github.com/lxqt/lxqt-config/pull/588.
@MarcusE1W A fix is available at  https://github.com/lxqt/lxqt-config/pull/588.
