### ISSUE TITLE
"runner" does not display the actual command that will be run. Not helpful.

### ISSUE THREAD

**Issue by J-Dunn** [lxqt/lxqt#1756]
Calling up "runner" with Win-R shows a one line entrybox. 

If I type "monitor" is proposes "monitor settings" in a drop down list with just this entry. 

However, the two lines of text simple repeat "monitor settings" twice. This is redundant and unhelpful. I would expect the second line to show the actual command that is about to be run. 

This would inform the user of what is actually happening and inform a more capable user of how to get the same result from a command terminal. 

As an administrator I like to see what is being done in my place: ie what is actually run. 

In this particular case the the settings dialogue did not come up and I'm left dumb. If I can run the same from a terminal I may be able to get information about why the command fails. Without know the command, I can not do that. 

Suggested improvement : show the command in the second line, which currently is totally redundant. The same would presumably apply to other commands in this context. 

 "monitor settings"
" lxqt-config-monitor "

##### System Information
                                             --->
* Distribution & Version: 
lubuntu 19.10

I don't have the lib versions to hand since I'm not on that system now. I imagine this is not new nor version specific. If it's problem I will add further details later.

**Comment by tsujan** [comment]
They are `Name` and `GenericName` -- and are the same in the special case of `lxqt-config-monitor` (which could be changed in its desktop file).

> As an administrator I like to see what is being done in my place: ie what is actually run.

Runners have this behavior (KDE's runner is so too): they are like menus -- do you see a command in the main menu? You could see the commands by opening the desktop files...

As an administrator, you might want to use a terminal emulator (like QTerminal) more often.

**Comment by tsujan** [comment]
Moreover, if you type `lxqt-config-monitor` or just `config-monitor`, the item will be shown. So, there's really nothing to improve here.

**Comment by J-Dunn** [comment]
>  if you type lxqt-config-monitor or just config-monitor, 

Well that means knowing the answer in advance. If I know the commands, I would not be asking the runner to show them.

> As an administrator, you might want to use a terminal emulator (like QTerminal) more often.

I certainly would, that is exactly why I wanted to know the command which was behind the runner entry.  I have a terminal open and am blindly trying monitor-settings , monitorsettings etc. trying to guess what is hidden from the user.

> You could see the commands by opening the desktop files...

Well, I will look at that when I get the desktop to display correctly. The reason I needed to run monitor settings is because I only get half the desktop ( the RH side with no icons;) )  Chicken and egg.

**Comment by tsujan** [comment]
> Well that means knowing the answer in advance

Not true. My example shows why (`config-monitor`). You have multiple ways to find and *run* the app you want by using the runner; that's the runner's job.

> that is exactly why I wanted to know the command

→ /usr/share/applications.

**Comment by agaida** [comment]
ok, a highly sophisticated command like `grep -r Exec /usr/share/applications` is to much for a common admin. We should have known that.

**Comment by tsujan** [comment]
> grep -r Exec ...

Yes :)

Anyhow, Runner == Something that runs things. And our runner is good in that.

**Comment by agaida** [comment]
Only one remark - if one has the LibreOffice suite installed typing libre looks like that:
![](https://i.imgur.com/1thRNFa.png)

Cool, thats what i would expect and a bit more :P 

Now we get nasty - i know the LibreOffice Writer is named `lowriter`
![](https://i.imgur.com/9rWc21Q.png)

so what - i don't see anything we could do better in the current functionality - the only thing i can think of is to extend the functionality with a fast start thingy - i suggested this five years ago iirc - the only question is: do we really want this? I'm biased because i ask for times ago

**Comment by tsujan** [comment]
Yes, it also finds all executables in `PATH` but only if their names are typed completely. For "applications" directories, typing a part of the app/executable name is enough -- like in the main menu.

**Comment by agaida** [comment]
not completely true - for the history a partially input is sufficient

**Comment by tsujan** [comment]
>  for the history a partially input is sufficient

Right.

**Comment by J-Dunn** [comment]
This is probably the sort of thing where you can find examples to support what ever position you wish advance but at least there is a proper discussion now. 

I would have thought the name + generic name  was for showing eg. :
firefox  | internet browser
okular | universal document viewer
blender | 3D modelling ..... 

programs traditionally have command name which is not necessarily obviously linked to the functional description. That is the original purpose of generic names: to give a functional description for those who are not familiar with what , say Firefox, does. 

There are cases like the Libre Office suite where the name is not the corresponding command. That is not a general rule, though it is not alone either. 

In the case of monitor setting I see no value or reason for repeating the same information 


J-Dunn:
>     Well that means knowing the answer in advance
tsujan:
> Not true. My example shows why (config-monitor). 

That is just another form which you need to know in advance. 

I would have thought that name :  _lxqt-config-monitor_
and generic name : _monitor settings tool_ 
would be generally more informative than repeating the same thing twice. 

> They are Name and GenericName -- and are the same in the special case of lxqt-config-monitor

Which may be a _special_ case because this is normally handled a little better. Is there any real reason not remove this redundancy and make it more useful. I don't see anyone saying that there is a good reason for it being a dupe.

**Comment by tsujan** [comment]
@J-Dunn  `Name` and `GenericName` are 2 keys of a desktop entry (a file with `.desktop` as extension). They aren't created by LXQt Runner but just read by it.

> programs traditionally have command name...

"Command name"?! Why don't you open a desktop file from `/usr/share/applications` in a text editor?

**Comment by agaida** [comment]
Ok, sorry if I don't understand the whole thing - but I will try my very best.

there is only the application name and the install path - the rest is something in the desktop files. 

But you are free to suggest some things - maybe with a working Pull Request. Anyways - if LXQt don't fit your needs, there are other great Desktop Environments - try them, use them, if not satisfied, write something (code) and convince us that your ideas are great.

Disclaimer: The text above is only my personal opinion - nothing is written in stone here. Maybe a first step for adoption in the project would be that you convince me - after I'm convinced I would fight for. There will be a big BUT: Normally we get big and good ideas fast, the only discussions will be how to implement - nuff said.

**Comment by agaida** [comment]
gosh, i forget about: sometimes the simple solution would be to improve translations or the comment

**Comment by J-Dunn** [comment]
> They aren't created by LXQt Runner but just read by it.

So the content of .desktop files are still determined by lxqt project aren't they? 

I don't even user dumb-the-user-down tools a "runner" , I just got sent to it by someone elsewhere trying to help me out with a broken desktop display and was frustrated by that fact it failed to launch the application, gave no output, and yet was too dumb to provide a usable command. It seems dumb by design is part of the unified desktop paradigm, where every OS gets degraded to MS standards. 

Anyway I have better things to do than make a campaign issue out of this. I thought I was pointing out an oversight where useless duplicated content could provide something useful. Since defending the status quo seems more important than improving anything I'll leave it there.

**Comment by tsujan** [comment]
@J-Dunn I usually read 2-3 lines of a comment and, if they aren't helpful or don't make sense, I'll ignore the rest. In this case, I made an exception, trying to explain elementary concepts. That stops here.

**Comment by agaida** [comment]
@tsujan - there is this brand new feature in github: Delete issue ...

**Comment by Vladimir-csp** [comment]
Perhaps, changing `Name` and/or `GenericName` to more fitting (and different) values would solve this?
```
Name=LXQt Display Configurator
GenericName=Display Settings
```

**Comment by tsujan** [comment]
@Vladimir-csp 
Yes, that should be done but it isn't related to this report.

**Comment by tsujan** [comment]
> there is this brand new feature in github: Delete issue ...

@agaida, I usually ignore closed issues. In this case, I just tried to correct the reporter's false assumptions -- to no avail ;)
