### ISSUE TITLE
Encrypted volume on USB drive causes pcmanfm-qt to crash

### ISSUE THREAD

**Issue by daniel-s** [lxqt/lxqt#1757]
When inserting a USB drive with an encrypted partition (LUKS volume) the dialogue to enter the password opens, but is frozen. 

##### Expected Behavior

Normally:
1. The user inserts a USB drive.
2. The dialogue appears to enter the password to unlock the LUKS encrypted volume.
3. The user enters the password.
4. The volume is unlocked and available in pcmanfm-qt.

##### Current Behavior

Steps 1 and 2 from above occur as expected. At step 3 the user is unable to enter the password, the dialogue is frozen. In fact, all pcmanfm-qt windows are frozen, including causing the desktop background to go grey. A workaround is to kill -9 the pcmanfm-qt process. This causes the pcmanfm-qt process to be re-launched. On relaunch the *enter password* dialogue re-opens, the user is able to enter the password and successfully unlock the LUKS volume. The desktop background returns to its regular wallpaper.

Note, that from the time that kill -9 is used to kill the pcmanfm-qt process, before the pcmanfm-qt process is re-launched, if the user manually launches the pcmanfm-qt process (say by typing pcmanfm-qt into the shell), the frozen *enter password* problem happens again.

##### Steps to Reproduce (for bugs)

1. Create a LUKS encrypted volume on a USB drive. In this case it was a volume with two partitions, the first a regular fat32 partition and the 2nd an encrypted Linux (LUKS) partition. It may not be necessary to have the first fat32 partition on the USB drive. Format/setup partitions as necessary.
2. Enter the USB drive into the computer.

##### Context

Replicated on two systems running Debian buster and lxqt 0.14.1.

##### System Information

* Distribution & Version: Linux 4.19.0-6-amd64 #1 SMP Debian 4.19.67-2+deb10u2 (2019-11-11) x86_64 GNU/Linux
* Kernel: 
* Qt Version: 5.11.3+dfsg1-1+deb10u1
* liblxqt Version: 0.14.1-1
* Package version: 0.14.1-3

**Comment by tsujan** [comment]
Not reproducible. No hang, no crash; everything works OK:

![1](https://user-images.githubusercontent.com/981076/70022155-6b78f680-15a8-11ea-9149-885f07021347.png)

![2](https://user-images.githubusercontent.com/981076/70022162-76338b80-15a8-11ea-896c-cf0f1c9a845f.png)

There is a big difference between the latest release and the latest git version of pcmanfm-qt.
