### ISSUE TITLE
[Feature request] PCManFM-Qt should continue copying, despite interaction needed

### ISSUE THREAD

**Issue by ceever** [lxqt/lxqt#1759]
Current situation: When moving/copying files, the process stops if files are there files exist in the destination and asks for interaction (overwrite, rename, etc.)

Desired behaviour: When moving/copying files, the process should continue with the "unproblematic" files and queue any required interactions (overwrite, rename, etc.) meanwhile, until the user is ready to act. This would save time later, when the copying was going on and the user was not looking at it.

(Is this the right place to put this request?)

Cheers

**Comment by tsujan** [comment]
Please fill in the template at https://github.com/lxqt/pcmanfm-qt/issues when reporting an issue or requesting a feature in pcmanfm-qt. Don't forget to include the version you have.
