### ISSUE TITLE
lxqt falls when dragging a file

### ISSUE THREAD

**Issue by ljgdasfhk** [lxqt/lxqt#1760]
##### Steps to Reproduce (for bugs)

1. dragging a file on desktop
2. desktop fall
3. 
4. 

##### System Information

* Distribution & Version: Archlinux
* Kernel: x86_64 Linux 5.4.6-arch3-1
* Qt Version: 5.14.0
* liblxqt Version: 0.14.1
* Package version: 

lxqt falls when dragging a file

**Comment by tsujan** [comment]
LXQt team needs a clairvoyant.

**Comment by agaida** [comment]
nahhh - our questions are far to complex

**Comment by tsujan** [comment]
Yes ;)

But I do have telepathy. The Qt is upgraded in Arch but he didn't recompiled LXQt -- or Arch LXQt packages aren't recompiled -- against Qt 5.14.0. All of LXQt should crash then.

**Comment by yan12125** [comment]
> Arch LXQt packages aren't recompiled

Sorry I missed libfm-qt during the last Qt update - https://bugs.archlinux.org/task/64980.

**Comment by ljgdasfhk** [comment]
horizontal mouse scrolling no longer works in pcmanfm

**Comment by ljgdasfhk** [comment]
horizontal mouse scrolling no longer works in pcmanfm

**Comment by ljgdasfhk** [comment]
horizontal mouse scrolling no longer works in pcmanfm

**Comment by stefonarch** [comment]
> horizontal mouse scrolling no longer works in pcmanfm

on _your_ installation

**Comment by tsujan** [comment]
@stefonarch 
He means the compact view (I used my telepathic power again). I think it's caused by one of bugs in Qt 5.14.0; will investigate it later.

**Comment by tsujan** [comment]
@yan12125 Thanks! I didn't know that you maintained LXQt Arch packages (although I've seen you're the first one who finds problems after a Qt upgrade).

**Comment by stefonarch** [comment]
> He means the compact view

It's working fine here in all views...

**Comment by tsujan** [comment]
@stefonarch I investigated it on the code level right now. They've fixed an old bug related to horizontal scrolling in Qt 5.14.0 (contrary to my comment above). So, I changed the code and the problem was fixed. (Will make a PR.)

My guess: You don't have the latest git libfm-qt + pcmanfm-qt.

**Comment by tsujan** [comment]
@stefonarch 

BTW, I can see the same issue in FeatherNotes too -- and it has the same solution.

**Comment by tsujan** [comment]
Oh, and I found another nasty bug in Qt 5.14.0:

In all Qt apps, you should press `Alt` to wheel-scroll a horizontal scroll-bar *when the mouse cursor is exactly over it*.

**Comment by stefonarch** [comment]
> My guess: You don't have the latest git libfm-qt + pcmanfm-qt.

Have checked, it's all up-to-date...

**Comment by tsujan** [comment]
> Have checked, it's all up-to-date...

Something should be different on your system. Also, see https://github.com/lxqt/libfm-qt/issues/500

To be certain, I also tested under Enlightenment (I am under LXQt + KWin): exactly the same results.

**Comment by yan12125** [comment]
> I didn't know that you maintained LXQt Arch packages

Those were maintained by @jleclanche. I applied as a co-maintainer of LXQt-related packages not long ago ;)

**Comment by tsujan** [comment]
> Those were maintained by @jleclanche. I applied as a co-maintainer of LXQt-related packages not long ago ;)

Please keep up the good work! Arch is important when it comes to the bleeding edge.
