### ISSUE TITLE
Logout from local session kills xrdp session

### ISSUE THREAD

**Issue by sdittmar** [lxqt/lxqt#1762]
First, thank you for your effort of creating such a beautiful desktop! I just tried it with a brand-new Debian 10.2 installation and I love the clean menu, unlike the Debian-cluster-mess in LXDE. I also love that the desktop automatically recognizes the keyboard layout on a xrdp session - magic!

Unfortunately, I noticed an issue with the xrdp session. When I chose to logout from the local session, the remote xrdp session gets terminated (logout), but the local session stays on. Also the screen on the local session does not update after login. That means the login screen remains visible while the menu bar and the desktop icons are placed on top. Somewhat of an odd behavior. Again, this was on a clean new Debian 10.2 installation. I thought I mention it, so you can hopefully make this great desktop become a winner!

I already deleted the install to give LXDE another try. I will have to follow up with some system details. Please tell me what you need and I will help where I can.

**Comment by tsujan** [comment]
Check /etc/systemd/logind.conf → `KillUserProcesses`. It should be `yes`.

**Comment by sdittmar** [comment]
the entire logind.conf content is commented out. Not sure what the default is. But I can try to change the setting to yes and remove the hash.

[Login]
#NAutoVTs=6
#ReserveVT=6
#KillUserProcesses=no
#KillOnlyUsers=
#KillExcludeUsers=root
...

**Comment by sdittmar** [comment]
Setting KillUserProcess=yes and rebooting makes no difference.
The local login works fine until I xrdp into the same machine. When I than login to the machine locally, the login screen does not disappear and when I logout from the local session, the remote xrdp session terminates...

**Comment by agaida** [comment]
Not reproducible - and i use xrdp sessions on a daily base. At least with Windows Remote Desktop Connetcions and Remmina no bad things happen - as far as i remember the KDE client works also fine in that regard - so no LXQt bug, maybe a client side misconfiguration..

**Comment by tsujan** [comment]
> Not reproducible - and i use xrdp sessions on a daily base.

Good :)

> Setting KillUserProcess=yes and rebooting makes no difference.

It should be set, anyway.
