### ISSUE TITLE
Samba integration in pcmanfm-qt / GUI for smb.conf

### ISSUE THREAD

**Issue by stefonarch** [lxqt/lxqt#1763]
Actually there is no "right click → share this folder" option in the file manager.
If this would slow down much pcmanfm startup make it an option (default = off)?

Also a GUI for editing smb.conf would be a nice feature.

**Comment by tsujan** [comment]
I think SMB sharing is already possible by adding a simple custom action. If so, we don't need to do anything because *custom actions are there to be used*. I'll look into it.

As for GUI for `smb.conf`, it should be provided by an SMB front-end, not by us.

**Comment by stefonarch** [comment]
> I think SMB sharing is already possible by adding a simple custom action

Yes, that was an idea of me too, but this action would need write access to smb.conf and should also restart the daemons.

**Comment by tsujan** [comment]
> but this action would need write access to smb.conf and

I don't think so. Will tell you soon....

**Comment by tsujan** [comment]
OK, this is the simplest way (I tested it):

Make `smb-share.desktop` inside `~/.local/share/file-manager/actions` as follows and then restart pcmanfm-qt:

```
[Desktop Entry]
Type=Action
Icon=document-share
Name=Share with Samba
Profiles=profile-zero;

[X-Action-Profile profile-zero]
SelectionCount==1
MimeTypes=inode/directory;
Exec=net usershare add %w %f '' Everyone:R guest_ok=y
Name=Default profile
```

You could also create an executable bash script in `~/bin` and put its name in front of `Exec=`, so that not only the folder is shared but also an emblem is added to it. Emblems are added by:

```sh
emblem_name="emblem-favorite" # change this to your emblem name
for arg in "$@"; do
	gio set "$arg" -t stringv metadata::emblems "$emblem_name"
done
```
And the folder can be refreshed to show the emblem immediately by:

```
xte 'key F5'
```

You could also add a short sound to the end, create a notification, etc. That's the beauty of custom actions.

Don't forget to restart pcmanfm-qt after each change.

**Comment by tsujan** [comment]
If a documentation is added for custom actions (I think it should), this could serve as an example.

**Comment by stefonarch** [comment]
Tested, did not work. Investigating I see 

```
$ man net
....
USERSHARE
       Starting with version 3.0.23, a Samba server now supports the ability for non-root users to add
       user defined shares to be exported using the "net usershare" commands.

       To set this up, first set up your smb.conf by adding to the [global] section: usershare path =
       /usr/local/samba/lib/usershares Next create the directory /usr/local/samba/lib/usershares, change
       the owner to root and set the group owner to the UNIX group who should have the ability to create
       usershares, for example a group called "serverops". Set the permissions on
       /usr/local/samba/lib/usershares to 01770. (Owner and group all access, no access for others, plus
       the sticky bit, which means that a file in that directory can be renamed or deleted only by the
       owner of the file). Finally, tell smbd how many usershares you will allow by adding to the [global]
       section of smb.conf a line such as : usershare max shares = 100. To allow 100 usershare
       definitions. Now, members of the UNIX group "serverops" can create user defined shares on demand
       using the commands below.
```

Have to setup and test  still, there is some doc needed somewhere.

**Comment by tsujan** [comment]
> Tested, did not work.

Strange! It worked OK here.

> Investigating I see...

Yes, as the doc says, `net usershare` should work.

> Have to setup and test still

Use the command-line in terminal to see the probable error messages (replace `FOLDER_NAME` with a folder name and `PATH` with its full path, including its name; '' is just a pair of single quotes, not a double quote):

```sh
net usershare add FOLDER_NAME PATH '' Everyone:R guest_ok=y
```

**Comment by stefonarch** [comment]
Ok, it works with
 smb.conf
```
[global]
...
  usershare path = /usr/local/samba/lib/usershares
   usershare max shares = 20
   usershare allow guests = yes

```
and permissions as stated in `man net` nd restarting smb.service and nmd.service.

smbtree does not list the usershares I noticed, while in pcman →network they are seen

**Comment by tsujan** [comment]
I'm not an expert in setting up SMB. I just did it the Manjaro way, by installing `manjaro-settings-samba`). For me:

```
[global]
   workgroup = WORKGROUP
   dns proxy = no
   log file = /var/log/samba/%m.log
   max log size = 1000
   client max protocol = NT1
   server role = standalone server
   passdb backend = tdbsam
   obey pam restrictions = yes
   unix password sync = yes
   passwd program = /usr/bin/passwd %u
   passwd chat = *New*UNIX*password* %n\n *ReType*new*UNIX*password* %n\n *passwd:*all*authentication*tokens*updated*successfully*
   pam password change = yes
   map to guest = Bad Password
   usershare allow guests = yes
   name resolve order = lmhosts bcast host wins
   security = user
   guest account = nobody
   usershare path = /var/lib/samba/usershare
   usershare max shares = 100
   usershare owner only = yes
   force create mode = 0070
   force directory mode = 0070
```

With the above-mentioned custom action or, equivalently, command-line, Nautilus sees the folders as shared too. So, Nautilus should use the same way of sharing.

**Comment by stefonarch** [comment]
Afaik important for user share are the 3 lines I posted above, it did work only with all 3 of them.
Perfect would be some way to change the icon, and/or also right click action "if usershare yes" → remove from usershare or another way to manage/see them, I see it needs only a rm /usr/local/samba/lib/usershares/share-name

**Comment by tsujan** [comment]
> Perfect would be some way to change the icon...

All of them can be done by appropriate scripts in `~/bin`. I don't have a ready script for SMB because I use SFTP.

The limit of custom actions is the limit of bash scripting = no limit.

**Comment by stefonarch** [comment]
Well it was tricky to get the %w and %f working with en external script
https://github.com/stefonarch/custom-actions/blob/master/scripts/foldershare

**Comment by tsujan** [comment]
Nice.

In your script, you wrote, "folders that  have the same name as a system user cannot be shared with their name". That's correct; I didn't want to complicate the discussion by mentioning it. A solution, among many, is using a combination of `%n` and `%w`. `%n` is the username of the URI.
