### ISSUE TITLE
Disable screensaver 'activate' pop-up

### ISSUE THREAD

**Issue by heldernovais** [lxqt/lxqt#1764]
The screensaver is disabled by default by some programs so it doesn't interrupt the user when uncommon input methods are used. One of these programs is Retroarch.

The first problem I encounter is how xscreensaver doesn't read joystick input and still locks the screen after some time without using the keyboard. It also doesn't get disabled for some reason. As a workaround, I kill its daemon manually (through its GUI). 
The second problem comes when frequent messages pop-up telling me of how lxqt/lubuntu failed to 'activate' the screensaver. I need a way of disabling the pop-up without messing around with the session settings and so.

PS: Some weeks ago, I contacted the "jwz" (developer of xscreensaver) to look for joystick support but I received no reply, sadly.

##### Expected Behavior
No message pops-up OR having a way of disabling the pop-up when the daemon is manually killed.

##### Current Behavior
The message pops-up and there seems to be no way of disabling it.

##### Possible Solution
Configuration or a more modern screensaver/screen-locker system

##### Steps to Reproduce (for bugs)
---

##### Context
Uncommon input methods like joysticks (the non-"keyboard or mouse" kind) .

##### System Information
* Distribution & Version: Lubuntu 19.04 LTS
* Kernel: Linux 5.0.0-36-generic
* Qt Version: ...
* liblxqt Version:... 
* Package version: ...

**Comment by tsujan** [comment]
This isn't related to LXQt but to xscreensaver and, perhaps, lubuntu.
