### ISSUE TITLE
Taskbar widget problem

### ISSUE THREAD

**Issue by paulvonlux** [lxqt/lxqt#1770]
Taskbar widget does not work properly when i run MegaSync program

##### Current Behavior
MegaSync box floats around the taskbar, and on the desktop, doesn't hide at all

##### Steps to Reproduce (for bugs)
1. Install MegaSync
2.Restart PC

##### System Information

* Distribution & Version:  LUbuntu 19.10
* Kernel: 5.5.8
* Qt Version: 0.14.1

**Comment by tsujan** [comment]
> Install MegaSync

I don't think anyone here will install MegaSync to check a supposed problem in Panel. If what you vaguely described happens only with MegaSync, it's MegaSync's bug; if not, provide us with a real description of the problem.
