### ISSUE TITLE
LXQt UPDATE

### ISSUE THREAD

**Issue by paulvonlux** [lxqt/lxqt#1772]
I have see that the LXQt has not been updated for 4 years...is it still worth working on this or is it DEAD?

**Comment by tsujan** [comment]
LXQt is under active development continuously. What you see at https://github.com/lxqt/lxqt/releases isn't related to real releases. Read the release pages of individual components instead.

**Comment by tsujan** [comment]
And if you want the latest features/fixes, use a distro that makes that possible for you; Ubuntu doesn't.

**Comment by Rowisi** [comment]
@paulolieuthier dude, this is not a paid product to complain about it this way. This is a FREE product that was made to support Linux user. 

LXQT was made to be lightweight, de-bloated. If you want a a fully-featured desktop environment you can use GNOME or KDE and stop complaining.

**Comment by paulolieuthier** [comment]
@Rowisi you picked the wrong guy :grimacing:

**Comment by tsujan** [comment]
Yes. GitHub's auto-completion is good but sometimes confusing; once I replied to myself ;)

**Comment by Rowisi** [comment]
> @Rowisi you picked the wrong guy 😬

LOL, I just did @ paul and only one appeared. I though that @ auto-completion showns only users participating in the issue but it seems it also shows the ones who commited to the project too.
