### ISSUE TITLE
Pcmanfm-qt Black Theme 

### ISSUE THREAD

**Issue by paulvonlux** [lxqt/lxqt#1774]
pcmanfm-qt does not have a black theme ...peeps it's 2020 for fuck sake...

**Comment by tsujan** [comment]
Please....

If you don't don't know what a "themes" means and how it can be used, first consult the forums of your distro.

**Comment by paulvonlux** [comment]
> Please....
> 
> If you don't know what a "theme" means and how it can be used, first consult the forums of your distro.

I fucking write the kernel you idiot...don't tell me what a theme is or is not.

**Comment by tsujan** [comment]
Please don't "write the kernel". Learn elementary concepts first!

**Comment by agaida** [comment]
one can also provide us with contributions or much money

**Comment by tsujan** [comment]
> one can also provide us with contributions or much money

You add to his confusion by that ;) He thinks LXQt = Lubuntu and theme is something that should be made by the app.

> we should really close bugs with not filled out template without comment.

I do, most of the time. Nonsense like this apart, some reports with bad formats contain useful info.
