### ISSUE TITLE
Disabling Super/Meta/Windows key in global keys shortcuts doesn't properly unbind it

### ISSUE THREAD

**Issue by DanielSmedegaardBuus** [lxqt/lxqt#1775]
##### Expected Behavior

When editing ` ~/.config/lxqt/globalkeyshortcuts.conf` and setting the Meta key shortcut, which is bound by default (at least in Lubuntu 20.04, not sure where the distinctions all lie) to opening the application menu, to `Enabled=false`, I expect the behavior to be disabled, *and* the key to be completely unbound, available for use in other keyboard shortcut combos elsewhere.

##### Current Behavior

The Meta key action is disabled, but the "handler" for the key is still active, causing windows to lose focus when trying to use it in combination in other keyboard shortcuts, such as ones specified in Qterminal settings. See my initial question on askubuntu.com for more details:

https://askubuntu.com/questions/1219713/cannot-unbind-meta-super-key-in-lubuntu-20-04/1219714

##### Possible Solution

Removing the configuration from the configuration file, rather than `disabling` it has the desired effect. This, of course, is a workaround, but I assume that the actual behaviour is not as intended.

##### Steps to Reproduce (for bugs)

1. Set the Meta key action directive in aformentioned configuration file to `Enabled=false`
2. Open a (Qt?) app, e.g. Qterminal or PCManFM-Qt.
3. Press Meta, hold Meta, release Meta
4. Notice the blur/focus events being triggered (this, in the case of a Qterminal dropdown session, will cause the terminal to hide itself)

##### Context

I want to use the Meta key in my own keyboard shortcuts, and this behaviour prevents me from doing so.

##### System Information

* Distribution & Version: Lubuntu 20.04 Daily @ 2020-03-24
* Kernel: Linux nux 5.4.0-18-generic #22-Ubuntu SMP Sat Mar 7 18:13:06 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
* Qt Version: 5.12.5-5
* liblxqt Version: 0.14.1-0ubuntu2
* Package version: ?

**Comment by tsujan** [comment]
`lxqt-globalkeysd` is a daemon and you change shortcuts with `lxqt-config-globalkeyshortcuts`, not by manually editing a config file.

**Comment by drum445** [comment]
@tsujan, could we get a resolution for this as it is still an issue. On lubuntu 20.04, I can't use super as a modifier in `.config/openbox/lxqt-rc.xml`

**Comment by tsujan** [comment]
The correct report was https://github.com/lxqt/lxqt-globalkeys/issues/173 and the problem described by it was fixed in https://github.com/lxqt/lxqt-globalkeys/pull/174.
