### ISSUE TITLE
No LXQt Issue: Qt's Memory Usage Has Increased On Arch/Manjaro

### ISSUE THREAD

**Issue by tsujan** [lxqt/lxqt#1776]
I opened this page to mention a new change that I think shouldn't be overlooked. Feel free to add comments if you see it or, especially, if you know its cause.

Last week, after an upgrade in Manjaro Testing, I saw that all Qt apps started to use 6-8 MiB more memory. Since most of the updates come from Arch, I think the same change should be visible there. Later updates didn't change anything. I have Qt 5.14.1-3.

The change may not be related to the kernel. I still use LTS 4.19 because the 5.X kernels — up to 5.4, at least — have a nasty Intel bug.

EDIT: For example, Qps used ~10 MiB on starting before; now, it uses ~17 MiB on starting. FeatherPad used ~9 MiB; now it uses ~17 MiB; etc.

**Comment by travankor** [comment]
I think I noticed this too, going from QT5.13.2 to QT5.14.2 -- though memory usage has gone up 3-6 MiB for me.

**Comment by tsujan** [comment]
> I think I noticed this too, going from QT5.13.2 to QT5.14.2

Yes, it's the same with Qt 5.14.2 -- in Arch, at least.

**Comment by tsujan** [comment]
Here, it's a little increased with Qt 5.15 (≤ 100 KiB), independently of the widget style.

**Comment by travankor** [comment]
If you're using an Intel GPU, I have noticed increased memory usage with the iris driver compared to the "legacy" i965 driver (it's hardly legacy when it's outright more stable than the iris driver -- at least on Wayland). You can toggle your driver at runtime with `MESA_LOADER_DRIVER_OVERRIDE` variable. The memory increase seems to apply to all QT5 apps, although non-QT5 apps are affected too.

**Comment by tsujan** [comment]
@travankor 
Thanks for the explanation! I think you're right. The memory usage may have increased after a mesa upgrade (19.3.4-2 -> 20.0.1-0.1) because it's in the upgrade list I copied on my desktop that night (2020-03-07).

I've encountered no graphic problem after the upgrade. The extra memory usage isn't important here (RAM = 16 GiB). But, at last, we know the cause. Problem solved :)
