### ISSUE TITLE
http://lxqt.org is down !

### ISSUE THREAD

**Issue by StephaneBunel** [lxqt/lxqt#1777]
##### Steps to Reproduce (for bugs)

1. 
2. 
3. 
4. 

##### System Information

* Distribution & Version: 
* Kernel: 
* Qt Version: 
* liblxqt Version: 
* Package version:

**Comment by tsujan** [comment]
-> https://github.com/lxqt/lxqt.github.io/issues/41

**Comment by jubalh** [comment]
We have this already: https://github.com/lxqt/lxqt.github.io/issues/41
