### ISSUE TITLE
Question, possibly not issue: menu update is inaccurate, cannot update

### ISSUE THREAD

**Issue by alan12345678** [lxqt/lxqt#1778]
mind me asking here while the LXQT website, forum etc. are all down? I realise this isn't exactly a support site.

very recently installed LXQT with Openbox. Absolutely loving it except for the current most INTENSELY annoying thing:

whatever I do, the App Menu (as the first 'widget' on the taskbar) will not update or accurately show my installed programs!

My machine had XFCE on top of Arch, so I had a bunch of stuff installed etc. Then I add this as a separate DE and log in. All the other config stuff has gone brilliantly. I used the `obmenu-generator` successfully, so my right-click menus look wonderful. But the one that pops up on my taskbar - what I tend to call the 'main menu' has got very little to do with what's installed on my computer. Plus, it seems to have managed to double up on a couple of categories (Accessories,  System) which are listed twice, in different parts of the menu, and contain some duplicates of each other.

With the main LXQT website out of action I can't even ask in the forum if I'm being daft or have missed some obvious or simple config issue, or file edit, or tweak or something. Can't believe this is a bug, but I have NO clue right now why my menu is so out of whack.

**Comment by tsujan** [comment]
> mind me asking here

-> https://github.com/lxqt/lxqt.github.io/issues/41

> whatever I do, the App Menu (as the first 'widget' on the taskbar) will not update or accurately show my installed programs!

Because your installation is too old. Even 0.14.1 (the latest release) is very old.

I really recommend every user have the latest git LXQt if his/her distro makes that easy (Arch/Manjaro does).

**Comment by alan12345678** [comment]
thank you! Certainly don't mind having the git version, didn't know it was moving THAT fast, but great - anything that works :)

I'll get to that straight away :)

**Comment by tsujan** [comment]
> didn't know it was moving THAT fast

LXQt is being continuously developed and the git sources are stable 99% of the time. As a git user, you could contribute to LXQt by reporting latest issues, if any, and we would really appreciate that.

**Comment by wxl** [comment]
> Even 0.14.1 (the latest release) is very old

Just going to say, that's a bug not a feature! Come on, release a new version already! :)

**Comment by tsujan** [comment]
@wxl, see https://github.com/lxqt/lxqt.github.io/issues/41

As a developer, I can't control releases for the above reason (I'm starting to worry about Alf) but I can make git better. And the same for other devs...

**Comment by alan12345678** [comment]
I will be very happy to contribute if that helps, thank you.

If it helps to say this - I hugely appreciate devs and the people behind their projects making the time to respond. I realise you're busy, and there are priorities, but we're all people. If it will help to make LXQT better, I'm in.

p.s. I also happen to think, inside 2 days, that it is an absolutely SUPERB design concept in terms of making DE's etc. and will be extremely happy if I never have to look at Gtk apps EVER again! :)

*alan ansell figurative painting
Itzac
France*

**We are what we repeatedly do. Excellence is therefore not an act but a habit.
 Aristotle**




----- Original message -----

**Comment by wxl** [comment]
If releases are only in the hands of one person, that might be problematic, especially if we face a situation where that one person is incapable of doing their otherwise normal duties:

```
1512 [oftc] < mpmc_:#lxqt> Has anyone made sure if agaida is OK?
0658 [oftc] <+agaida:#lxqt> mpmc: i'm ok - but had a  lot to do in the company
0851 [oftc] < mpmc_:#lxqt> agaida: Oh good! Glad to hear you and your family are OK :)
```

**Comment by tsujan** [comment]
> If it will help to make LXQT better

It definitely will. We use what we make but couldn't see *all* aspects of a program if git users don't help us.

@wxl 
That was really good news. Did the chat happen recently?

> If releases are only in the hands of one person

I can speak only for myself:
I have to develop several libfm-qt based apps. I also have my own projects -- especially, FeatherPad and Kvantum take a lot of time. I also review other LXQt devs' works. And I reply to users too. REALLY, no extra time remains for me.

Making a release is not an easy job; I'm sure you know that.

**Comment by wxl** [comment]
@tsujan yeah that was today, so Alf is fine. That was my primary concern, to be honest. We live in strange times…

Anyways, I hear you in relation to releases and this probably isn't the place to have an ongoing discussion on it but it deserves discussing in some way. Releases are hard in general, but they're even more problematic for us, where the product is really a whole collection of related but separate components. This is all the more reason why we need organization to make it happen. However, there seem to be no clear goals or plans as it relates to releases. They just sort of happen. And apparently only via one person. If everyone was on the same page, working towards the same goals, with the same timelines, one could easily step in and do a release as needed. Heck, several people could work together on it.

**Comment by tsujan** [comment]
I release my own project in this way:

I start to work on features that users have requested or I like. Or I find bugs and start to fix them. After a while -- which can be from one to 2 months -- the program becomes quite different from what it was or important issues are found and fixed in it. So, I release it.

After each release, I may find minor issues and do small optimizations, so that a point release becomes necessary.

I always update my ChangeLogs whenever I make a commit. So that making a release is pretty easy for me.

Now, I don't know how this model works with a DE. If libfm-qt and pcmanfm-qt were separate from the rest of LXQt and I could release them, we'd have 0.16.X.  I once suggested updating ChangeLogs continuously but got to response.

@agaida organizes things so neatly when he makes a release. But he should also maintain Debian packages of not only LXQt but also other apps. Hes has other dev jobs too. Needless to say, he also checks PRs, test them, discuss about them, etc. If you ask him, he'll say, "that's easy...," but it's not. It takes A LOT of time and effort.

Add to this the fact all of us are human beings with our personal lives and problems. We don't talk about our life problems in LXQt issue trackers but they can be severe sometimes.

So, my answer: Contribution is highly appreciated.

**Comment by wxl** [comment]
Yes! I'd love to help with the releasing if I could. And I see that when releases happened they are well organized. But how we go from not having a release to having one is a process I have no understanding of, as you don't, either. That's what I am getting at. If we don't have contribution guidelines, everyone just shoots in the dark. And that often means they get shot down.

**Comment by tsujan** [comment]
I agree that we should discuss releases and be much more explicit about them.

If someone tells me how I can release libfm-qt, pcmanfm-qt, lxqt-archiver and lximage-qt, I'll do so regularly -- of course, after asking other developers about their opinions, especially @agaida.

**Comment by alan12345678** [comment]
just updated every LXQT to git version as I could find it, NO difference whatsoever to my still inaccurate menu.

**Comment by tsujan** [comment]
What do you mean by "inaccurate"? Aren't items updated when you install/uninstall apps? Have you upgraded the whole LXQt to its git components?...

It's important to be specific about problems.

**Comment by wxl** [comment]
@tsujan like i said this probably isn't the place to discuss releases, so perhaps we should open a new issue.

**Comment by tsujan** [comment]
@wxl, yes.

**Comment by alan12345678** [comment]
> What do you mean by "inaccurate"? Aren't items updated when you install/uninstall apps? Have you upgraded the whole LXQt to its git components?...
> 
> It's important to be specific about problems.

Appreciate that indeed, and in fact was trying to take screen caps of my start menu but errr... I can't see how to hold it open while I press "OK" on the capture! Words will have to suffice for now:

The menu has all the categories listed, but for example the two very top entries are both identical "Accessories". Each one expands to show different things. The top one has just four items (Compton appears numbers of times in my menus. I don't have it installed, but use Picom). Below the top "Accessories is a second "Accessories". This one contains the same four items, but listed within a much larger list of fifteen items. This list ALSO contains Compton, but it does contain Picom.

Below categories are accurate insofar as they represent the categories described in the .desktop files, but a category "System" actually contains just two items, but these two are present in the very top "Applications" menu.

I realise this means it's reading the .desktop files, but no way I'm editing all of those (only for them to possibly be updated).

Plus, despite the obmenu-generator having correctly written out a lovely "menu.xml" and which works correctly on right click, and which has all the icons showing (thus Openbox is presumably working fine), my LXQT menu has no icons.

I'll be happy to be more specific as required. Also to mention some other aspect of this:

I use Yay, but realising I might want to install a group, I simply used Pacman. But while Openbox seems to be just one single file, under Arch at least there appears to be no such thing as installing LXQT as a group - as I would  say for XFCE or Gnome. Thus I really don't know if I'm missing an essential package or not. I've read all the docs I could find FIRST, and believe I have everything I need. But no, I did NOT go through the list of packages found and simply choose to install every single one - there didn't seem any point.

If I can work out a way to take shots  of my start menu I'll post some pictures to illustrate.

**Comment by tsujan** [comment]
> and in fact was trying to take screen caps of my start menu

Set a delay with Sccreengrab.

> The top one has just four items

That depends on your installed apps.

> Compton appears numbers of times in my menus. I don't have it installed

You should have (inadvertently) made and left a desktop entry somewhere, Check `~.local/share/applications`.

> Below the top "Accessories is a second "Accessories".

That isn't caused by LXQt. Have you used a menu editor? It may have messed up with your menus.

> my LXQT menu has no icons.

OK. That's serious. Your installation shoukd be incomplete or problematic. You need, at least, git builds of the following sources, compiled and installed in this order:
```
libqtxdg
lxqt-build-tools
liblxqt
libfm-qt
pcmanfm-qt
lxqt-themes
lxqt-qtplugin
pavucontrol-qt
qtermwidget
qterminal
lximage-qt
lxqt-config
lxqt-globalkeys
lxqt-notificationd
lxqt-policykit
lxqt-powermanagement
lxqt-session
lxqt-sudo
lxqt-panel
lxqt-runner
screengrab
```
After that, you need to log out and log in. Also, don't forget to install Arch's Optional Dependencies.

**Comment by alan12345678** [comment]
aha! I have used Menulibre back in XFCE to edit the menu, but that was the XFCE menu. And what I did with it was really just to hide a few things - I never remove any items at all, merely keep them from displaying (exactly to avoid this issue of an app showing up in more than one place).

To rule this out as a source of problems, should I simply restore everything to default and uninstall it?

Going to check your list above and get on it!

**Comment by tsujan** [comment]
> but that was the XFCE menu

All menus are interrelated: XFCE, LXQt, Gnome, KDE.... Also, making an item hidden in KDE doesn't mean it won't be visible in Gnome, for example.

> To rule this out as a source of problems, should I simply restore everything to default and uninstall it?

AUR's git packages make you uninstall non-git packages. You can't have pcmanfm-qt and pcmafm-qt-git together, for example. The above-mentioned order is important.

I think AUR may have an lxqt-git "meta package" but I'm not an AUR maintainer.

**Comment by alan12345678** [comment]
I am very pleased to say already that despite I'm still building a few other git packages (I hadn't seen any need to have pavucontrol-qt for example, but I'm NOT gonna argue) you seem to have fixed BOTH my issues with the menu!!

First part of that was that I'd omitted to update the lxqt-theme to the git version! Even having done that,  and without even logging out, all my menu icons appeared!

And then, as if that wasn't exciting enough, I go to look at Menulibre and I can't believe what I'm seeing! The menu being shown in LXQT is the actual menu that Menulibre is showing me!!!

So in fact it was my XFCE all this time that had looked correct but in fact wasn't! So now I'm editing out this double "Accessories" category, and going through the rest of the menu... I haven't yet logged out, so the menu is not displaying correctly yet BUT... it does show that what I've been seeing in LXQT is what was in the actual menu! I'm hopeful therefore this will all get sorted out.

YAY!

I'll be honest - at this rate I can see myself uninstalling the entire other DE. I'm a bit of a purist, I hate having something if I don't need it, and for sure I don't want issues. I LOVE how well designed all this is, and how easy to work with etc. Will leave it a few days yet but good promising start.

THANK YOU for your help. Awesome :)

**Comment by tsujan** [comment]
happy to know that your problem is fixed.

When icons disappear  from menus/apps or an important component crashes, you could be sure that something's wrong with installation.

BTW, you need to update your installation when the second version of Qt changes. If you had Qt 5.14 and it's upgraded it to Qt 5.15, you need to recompile basic components of LXQt, at least:

```
libqtxdg
lxqt-build-tools
liblxqt
lxqt-qtplugin
```

**Comment by alan12345678** [comment]
thanks again - noted!

**Comment by tsujan** [comment]
You're welcome.
