### ISSUE TITLE
release documentation

### ISSUE THREAD

**Issue by wxl** [lxqt/lxqt#1779]
As discussed (offtopic) on #1778 @tsujan and I are of the opinion that we could use more clear documentation about how and when to do releases. 

I'm pretty sure the how is well sorted (but not ever written down from what I can tell) but the when has probably been a bit more organic. I think that latter issue could especially use development. I'm not saying that we adhere strictly to some time-based schedule, but there may be triggers to releases. What are those triggers? 

I think the more detailed this documentation, the more the burden of releasing can be shared among multiple people, which should make releases easier, which should mean more releases, and that's a very good thing. 

It certainly would save us the trouble (like on the aforementioned issue) of telling people that they should use git master because the releases are too darned old.

**Comment by tsujan** [comment]
Everyone, please don't hesitate to tell about your opinions on how we could release more easily and efficiently. If you think that git is enough, please tell why. If it isn't enough, how could we release LXQt components faster and more easily?

LXQt has its git users but many users don't know how to have git LXQt -- I've seen Arch users that have problem with git. Others may suppose that gt LXQt is as unstable as git KDE....

As far as I've seen, we get lots of useful reports only after a release.

**Comment by wxl** [comment]
Well, and many distros are just not geared well towards anything but released software, so another reason for regular releases.

However, Arch isn't one of them. I'm shocked by the comment that you say that some of them have a problem with git. Could you elaborate more on that?

If the useful reports come after a release, that certainly suggests a very good value in regular releases. The more releases, the more feedback, the more improved each subsequent release.

**Comment by tsujan** [comment]
> However, Arch isn't one of them. I'm shocked by the comment that you say that some of them have a problem with git. Could you elaborate more on that?

Git LXQt is maintained very well in AUR but I've seen many Arch users with less than minimal knowledge of their systems. Installing Arch doesn't make a magic ;)

> If the useful reports come after a release, that certainly suggests a very good value in regular releases.

I completely agree. I've experienced its usefulness first hand. Debian and Ubuntu users make sensible bug reports/feature requests after new releases.

I don't know how many times I've had to say, "your installation is too old."

**Comment by wxl** [comment]
I guess I'm just surprised to see Arch users that don't know what they're doing! 

Anyways I'd like to hear from others on this. Most importantly, we need to hear from @agaida since it sounds like he's been the one carrying the release torch.

**Comment by apt-ghetto** [comment]
It seems, that no release concept exists. I am new to the whole LXQt world. The only release that I have seen is 0.14.X from Lubuntu 18.10 onwards. In other words, I have no idea, how release management was handled before 0.14.

If I had to create a release concept, I would ask myself this:

- Is the release planning more time based or feature based? Or based on the mood of the release manager or the community?
  - Is there a list of milestones to reach the point for a new release?
  - Or is every year/6 months a new version released?
- What is the support status for the releases?
  - Is only the last stable release supported by LXQt?
  - Are there several supported releases?
  - Are there long term support releases? How long are they supported?
- Are security fixes and bug fixes backported to older releases?
  - Who does the work? The committer itself? Someone else?
- Are Pull requests for older releases accepted, without fixing the bug in master?

Based on the answers, it has quite different consequences for downstream.

**Comment by tsujan** [comment]
@apt-ghetto 
One thing is certain: We don't and can't support old releases — no LTS, no multiple-release support, no backport — we simply don't have the manpower. If releasing becomes more frequent (and I really hope so), "point releases" will be made to fix bugs in the latest release.

**Comment by luis-pereira** [comment]
IIRC our goal was/is a major release every six months more or less, followed by point (fix) releases to the latest major release. Considering the available manpower, aiming for more frequent releases/backports etc  is not realistic.

**Comment by tsujan** [comment]
@luis-pereira 
The current manpower could do much more efficiently if each developer can release the component(s) he works on after consulting others (or after asking @agaida).

For example, releasing lxqt-archiver should be a piece of cake. It shouldn't wait for only one person to do the whole job.

**Comment by wxl** [comment]
@Luis-Pereira we are about 9 months too late for our 6 month milestone, so maybe we can start with sticking to that!

**Comment by wxl** [comment]
Also what dictates when a point release comes out? Only for security and critical bug fixes or what?

**Comment by luis-pereira** [comment]
> The current manpower could do much more efficiently if each developer can release the component(s) he works on after consulting others (or after asking @agaida).

Of course it can.

**Comment by luis-pereira** [comment]
> @luis-pereira we are about 9 months too late for our 6 month milestone, so maybe we can start with sticking to that!

That would be a great start.

**Comment by luis-pereira** [comment]
> Also what dictates when a point release comes out? Only for security and critical bug fixes or what?

Security and critical bugs at least.

**Comment by tsujan** [comment]
I agree with @luis-pereira that point releases are for critical bugs and security. Also for that reason, it'll be great if each developer is able to make them by consulting others — instead of waiting for @agaida, who may have lots of other jobs to do. That will be a wok division, which will be benifit both users and developers (because of more helpful reports and less reports against outdated codes).

**Comment by tsujan** [comment]
FYI:

The first release by me: https://github.com/lxqt/lxqt-archiver/releases/tag/0.1.0. Please package it for your distros for us to get real feedback!

**Comment by yan12125** [comment]
Awesome! I published https://www.archlinux.org/packages/community-testing/x86_64/lxqt-archiver/.

From the perspective of a packager, the first thing I noticed for this release is that there are no GPG-signed source tarballs. Arch Linux enforces package authenticity by PGP key IDs (ex: line 22 in [PKGBUILD for lxqt-about](https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/lxqt-about))

Seems GPG-signing is done by https://github.com/lxqt/lxqt-release-foo/blob/master/scripts.d/archive.sh.

**Comment by tsujan** [comment]
@yan12125 
Thanks for telling me about GPG-signing! I'll consider it in next releases.

**Comment by tsujan** [comment]
OK, please tell if this is correct.

To make a release of an LXQt component (minus the general announcement, which isn't possible for now):

 1. Complete the CHANGELOG inside the source, make a PR and merge it.
 2. Make an annotated tag (the version) and push it.
 3. Create `PACKAGE-TAG.tar.xz` from the latest git source and also `PACKAGE-TAG.tar.xz.asc` by using `gpg`. (@agaida's [script](https://github.com/lxqt/lxqt-release-foo/blob/master/scripts.d/archive.sh) can be used for that.)
 4. Go to GitHub release page, edit the latest release (which is already created because of 2), add some explanation and upload `PACKAGE-TAG.tar.xz` and `PACKAGE-TAG.tar.xz.asc`.
 5. Release it!

@yan12125, am I missing anything, especially for Arch?

**Comment by yan12125** [comment]
> am I missing anything, especially for Arch?

Nothing :) Thanks for the note!

**Comment by jubalh** [comment]
> Create PACKAGE-TAG.tar.xz from the latest git source and also PACKAGE-TAG.tar.xz.asc by using gpg

Most distros will check against @agaida  and/or @jleclanche  GPG key though.
So we need to announce on an offical location which key we use this time.

**Comment by tsujan** [comment]
@jubalh 
Supposing that @agaida doesn't show up. about 3 weeks later, I'll start to release libfm-qt-0.15.0 and pcmanfm-qt-0.15.0 but only after telling everyone about it and asking for opinions and guidance.

**Comment by jubalh** [comment]
Okay, good to know. Do you plan to do a release of the whole of LXQt in the end or only some individual parts?

**Comment by tsujan** [comment]
Actually, I think its highly preferable (even a must) to release`lxqt-build-tools` first and then make libfm-qt's build depend on its new version (I should ask @luis-pereira about his PR). Then, we should release other components too.

My plan, so far:
 * Release lxqt-build-tools after deciding about @luis-pereira's PR.
 * Bump libfm-qt's ABI and release it.
 * Release pcmanfm-qt.

After than, other components could be released. But I should do some tests before doing anything. We also need to wait for @selairi to finish his works. I hope libfm-qt/pcmanfm-qt could be released 3 weeks later but other components might need to wait a little longer.

**Comment by wxl** [comment]
@tsujan that sort of sequencing is the sort of things the docs need. So should we create a wiki page to start collecting some of this stuff?

**Comment by tsujan** [comment]
@wxl 
I'm making a list of jobs for myself but I'll surely put it somewhere in https://github.com/lxqt when it's finished and tested.

**Comment by tsujan** [comment]
OK, the whole LXQt should be released on bumping lxqt-build-tools's version.

I update all changelogs in PRs whenever I find time (already made 2 PRs). Then I prepare summaries for release pages (previously, we did it in "lxqt.org" but it's better and cleaner to do it for each component in its own release page). The order of releasing is obvious but distro packaging should be done after all components are released (I'll tell everyone about it).

**Comment by tsujan** [comment]
@wxl 
This works (later we could put it — or, perhaps, a better version of it — somewhere):

# How To Release A New Version of LXQt

## Order

Preparing and releasing of LXQt components can be done in this order (only important components are listed and the order isn't strict near the end):
```
  lxqt-build-tools
  libqtxdg
  liblxqt
  libfm-qt
  pcmanfm-qt
  lxqt-qtplugin
  lximage-qt
  lxqt-archiver
  libsysstat
  lxqt-about
  lxqt-config
  lxqt-globalkeys
  lxqt-notificationd
  lxqt-policykit
  lxqt-powermanagement
  lxqt-session
  lxqt-sudo
  lxqt-panel
  lxqt-runner
  lxqt-themes
  qtermwidget
  qterminal
  lxqt-openssh-askpass
  lxqt-admin
  pavucontrol-qt
  screengrab
  qps
  …
```
You should have installed the latest git versions of all LXQt components and be satisfied with their performance before proceeding.

## Preparation

1. Prepare the components for their new releases by making PRs (with titles like "Pre-release changes") for:
    * Incrementing versions;
    * Incrementing ABI versions if relevant;
    * Incrementing versions of dependencies;
    * Incrementing the minimum Qt version only if needed; and
    * Updating CHANGELOGs.
2. Merge the above-mentioned PRs when ready and prepare release notes for release pages. Release notes can be extracted from change logs — from the most to the least exciting changes — so that the average user could understand them easily.

## Releasing

Release the components in the above-mentioned order. To do so, for each component:
  1. Make a signed tag (the version), verify it and push it.
  2. Create `PACKAGE-TAG.tar.xz` from the latest git source and also `PACKAGE-TAG.tar.xz.asc` by using `gpg`.
  3. Go to GitHub release page, edit the latest release (which has already been created because of 2), add its release note (which you've already made) and upload `PACKAGE-TAG.tar.xz` and `PACKAGE-TAG.tar.xz.asc`.
  4. Release it!

## Announcement

Announce the new version of LXQt with some highlights as the release note of `lxqt-about`.

Tell distro maintainers that they can start their jobs. If someone finds an issue in your work, fix it — of course, reluctantly because you're tired now.

**Comment by luis-pereira** [comment]
@wxl @tsujan @yan12125 @jubalh 
Copied @tsujan instructions to the [LXQt Wiki](https://github.com/lxqt/lxqt/wiki/) and created a[ How to release a new version section](https://github.com/lxqt/lxqt/wiki/How-To-Release-A-New-Version-of-LXQt).

**Comment by tsujan** [comment]
@luis-pereira, thanks a lot! I might make minor changes to it later.

@yan12125 @jubalh @wxl @luis-pereira
I finished the releasing of LXQt 0.15.0 and made a symbolic release of the super-project to include the general announcement: https://github.com/lxqt/lxqt/releases/tag/0.15.0

I double checked everything -- and hope that my double-checking hasn't had the inverse effect ;) -- but please check it and tell me if something is wrong.

@wxl Please tell Lubuntu team that the new version is ready; I didn't know whom I should call.

I hope Debian will have a new maintainer.

**Comment by tsujan** [comment]
Oh, there's one thing I wanted to tell maintainers:

Please add gnome-keyring to optional dependencies (Arch), Recommends (Debian-based) and ? (RPM based) for pcmanfm-qt 0.15.0! You could see the reason in the announcement and also on the release page of pcmanfm-qt.

**Comment by yan12125** [comment]
> Please add gnome-keyring to optional dependencies (Arch)

Seems password saving is done by gvfs, which [goes through libsecret](https://gitlab.gnome.org/GNOME/gvfs/-/blob/1.44.1/daemon/gvfskeyring.c#L264), so I added a virtual package `org.freedesktop.secrets` instead, following [a previous TODO in Arch](https://www.archlinux.org/todo/gnome-keyring-dependency-replacement-with-orgfreedesktopsecrets/).

**Comment by tsujan** [comment]
@yan12125 Your comment was illuminating. I haven't used `keepassxc` (have had `gnome-keyring` since years ago) but it seems to be Qt based, in which case, it's a better choice for providing   `org.freedesktop.secrets` under LXQt.

**Comment by yan12125** [comment]
> it's a better choice for providing `org.freedesktop.secrets` under LXQt

Maybe not :) It's not intended to be a complete system keyring, but just happens to also implements most features for the org.freedesktop.secrets interface. For example it does not support unlock at login like gnome-keyring does.

**Comment by tsujan** [comment]
> ... but just happens to also implements most features for the org.freedesktop.secrets interface.

Enough for us.

> For example it does not support unlock at login like gnome-keyring does.

Who wants that? ;)

Anyway, your choice (`org.freedesktop.secrets`) is the best under Arch.

**Comment by jubalh** [comment]
Thanks a lot for your work!

@tsujan could you maybe comment in the [release notes](https://github.com/lxqt/lxqt/releases/tag/0.15.0)  which GPG key is used for signing? Users/distros need a way to compare.

(btw `gpg --recv-keys 19DFDF3A579BD509DBB572D8BE793007AD22DF7E` didnt return anything. Do you have it only locally?)

**Comment by tsujan** [comment]
> Users/distros need a way to compare.

I followed [GitHb's help](https://help.github.com/en/github/authenticating-to-github/generating-a-new-gpg-key). Of course, if I didn't add my exported key to my GitHub account, GitHub wouldn't mark releases as "Verified".

Please be more specific if more than that is needed. @yan12125 [explicitly said it's enough](https://github.com/lxqt/lxqt/issues/1779#issuecomment-616246314) and Arch PKGBUILs don't seem to have a problem ([example](https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/pcmanfm-qt)).

**Comment by tsujan** [comment]
@yan12125, BTW, why is `xarchiver` is still added to [optdepends](https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/pcmanfm-qt)? We have `lxqt-archiver` V0.1.1 now.

**Comment by jubalh** [comment]
> Please be more specific if more than that is needed. @yan12125 explicitly said it's enough and Arch PKGBUILDs don't seem to have a problem (example).

They have:

```
validpgpkeys=(
	"169704C6FB490C6892C7F23C37E0AF1FDA48F373"  # Jerome Leclanche <jerome@leclan.ch>
	"7C733BA5F585AAD669E4D23A42C9C8D3AF5EA5E3"  # Alf Gaida <agaida@siduction.org>
	"19DFDF3A579BD509DBB572D8BE793007AD22DF7E"  # Pedram Pourang <tsujan2000@gmail.com>
)
```

And I need to do the same. For this reason I would need your whole public key, not just the ID.
If you published your GPG key to some keyserver I can get the public key from there with the ID, but I didn't find it.

**Comment by tsujan** [comment]
> If you published your GPG key to some keyserver

I only added it to my GitHub account, as GitHub didn't want me to do more. As I said, if anything more than GitHub's requirements is needed, please tell me specifically:
 * Do I need to add my exported key, that I've added to GitHub, to a keyserver?
 * Which keyserver?
 * If so, why doesn't GitHub show it as a public info on my GitHub account page?.

**Comment by yan12125** [comment]
Well, I just grab the public key with github API: https://api.github.com/users/tsujan/gpg_keys.

> BTW, why is xarchiver is still added to optdepends? We have lxqt-archiver V0.1.1 now.

Ah, I forgot about it. Will change tomorrow.

**Comment by tsujan** [comment]
> Well, I just grab the public key with github API

So, GitHub itself is the keyserver in question; isn't it?

> Ah, I forgot about it. Will change tomorrow.

Please don't forget about https://github.com/lxqt/lxqt-archiver/pull/153; you approved of it.

**Comment by jubalh** [comment]
> Well, I just grab the public key with github API: https://api.github.com/users/tsujan/gpg_keys.

wow I didnt know about such feature. Thanks!

**Comment by tsujan** [comment]
> wow I didnt know about such feature. Thanks!

I didn't either. May add it to How-To-Release documentation.

**Comment by tsujan** [comment]
Off topic: `\r\n` for new line is interesting in https://api.github.com/users/tsujan/gpg_keys ;) No wonder why GitHub is down once in a while (it was for an hour when I was preparing release notes).

**Comment by stefonarch** [comment]
Off topic too: just stumbled on this on arch:
```
stef@arch:~/git$ yaourt lxqt-panel
1 community/lxqt-panel 0.14.1-2 (lxqt)
    The LXQt desktop panel
2 aur/lxqt-panel-git 0.13.0.1104.gc6f910fd-1 (46) (0,00)
    The LXQt desktop panel

```

Shouldn't the git version have a more up to date numbering?

**Comment by tsujan** [comment]
Not being an Arch maintainer but having seen how Arch works, I guess `lxqt-panel 0.14.1-2` will be changed soon and `lxqt-panel-git 0.13.0.1104.gc6f910fd-1` isn't important because git PKGBUILDs get the latest git versions.

**Comment by yan12125** [comment]
> Please don't forget about lxqt/lxqt-archiver#153; you approved of it.

Both pcmanfm-qt and lxqt-archiver updated. Turns out I didn't add lxqt-archiver to my script :sweat_smile:

**Comment by voidpin** [comment]
@tsujan 
A few questions... Don't know if this is the right place to ask but, here we go.
As you know I've been working on the port of **LXQt** to NetBSD which, btw is now done and available to users :)
I'll start the work on 0.15.0 during the coming week and would like to know if,
1) you guys plan to bring lxqt.org back to life or should I change the fetch url to github?
2) why compton? Its deprecated and no longer available on NetBSD pcksrc, are you planning on changing to `picom`?
3) why the need for `screengrab`? `lximage-qt` can do screenshots, am I missing something?
4) Last but not least, can you please ensure that `option(WITH_INPUT "Build the 'lxqt-config-input'" ON)` in `lxqt-config` will always be possible to set to **OFF**? `libinput` does not exist on NetBSD and I don't believe it will.

Thanks for the new release!

**Comment by tsujan** [comment]
> you guys plan to bring lxqt.org back to life or should I change the fetch url to github?

You can't get LXQt components from anywhere other than GitHub. Developers and maintainers never relied on `lxqt.org`, simply because it has nothing for them.

> Why compton?

It was just an old suggestion that's still used by many. Openbox too. I have neither but KWin. LXQt is agnostic toward WM/compositor. In future, when Picom gets stable, it might replace Compton but the remote future will belong to Wayland. Take a look at the long discussion at https://github.com/lxqt/lxqt/issues/10 -- from bottom to top ;) It will surely continue.

> why the need for screengrab? lximage-qt can do screenshots

The Unix philosophy: Write programs that do one thing and do it well. The screenshot code of lximage-qt depends on X11 and has no future; most probably, we'll remove it. LXQt's screenshot utility is screengrab, which is made for taking screenshots.

> can you please ensure that option(WITH_INPUT "Build the 'lxqt-config-input'" ON) in lxqt-config will always be possible to set to OFF?

Please open an issue at https://github.com/lxqt/lxqt-config/issues. It was necessary that we rely on `libinput`; otherwise, the settings wouldn't be usable under Linux. @yan12125 is the expert in this area.

**Comment by voidpin** [comment]
@tsujan 
Thanks. I'll open an issue in `lxqt-config` as suggested, only would like to keep the **OFF** option available, that's all. I understand the Linux reasons, as I also use it on one machine :)

I'll package `screengrab` but not `compton`.

As for **Wayland**, I have it running on NetBSD but not with `wlroots`. The future will tell.

**Comment by tsujan** [comment]
> only would like to keep the OFF option available,

That should be easy. I admit I didn't know we don't have that option.

**Comment by tsujan** [comment]
FYI:

I searched for "lxqt 0.15.0" with google and had the impression that people have easily found the announcement at https://github.com/lxqt/lxqt/releases :) IMHO, that's the first place we should always have put the announcement (although it's good to have it on https://lxqt.github.io/ too).

**Comment by voidpin** [comment]
@tsujan yes, I had no problem finding it.
I've already started packaging.

**Comment by tsujan** [comment]
I haven't looked into it yet but does anyone know how translations are updated for each LXQt component? Which command?

**Comment by stefonarch** [comment]
You mean how new features get into .ts files? In CMakeLists.txt is set
`option(UPDATE_TRANSLATIONS "Update source translation translations/*.ts files" OFF)`

There was also something like -DCMAKE_UPDATE_TRANSLATIONS=ON while compiling but I think it's ignored.

**Comment by tsujan** [comment]
@stefonarch 
We started to comment simultaneously :) I meant updating the translations inside each source (previously and as a developer, I didn't care about translations but now, I should).

Minutes ago, I saw that everything had already been done cleanly in `lxqt-build-tools` → `lxqt-transupdate`. It's enough to run `lxqt-transupdate` to update translations of each source.

**Comment by wxl** [comment]
> * Do I need to add my exported key, that I've added to GitHub, to a keyserver?
> * Which keyserver?

It might be helpful to put it elsewhere. the [SKS pool](https://sks-keyservers.net/) is probably your best bet.

**Comment by tsujan** [comment]
> It might be helpful to put it elsewhere

You mean "elsewhere too"; it should be in GitHub.

**Comment by wxl** [comment]
Well elsewhere, by definition, acknowledges one places and points at one that is not like it, so yes :rofl:

**Comment by jubalh** [comment]
> Last but not least, can you please ensure that option(WITH_INPUT "Build the 'lxqt-config-input'" ON) in lxqt-config will always be possible to set to OFF? libinput does not exist on NetBSD and I don't believe it will.

@voidpin Well, like always: just because something doesnt exist on one distribution/os we won't change it. You can just set the setting yourself in your build scripts :)

**Comment by tsujan** [comment]
@jubalh 
I don't think it's easy to remove that part of lxqt-config in a build script (but I haven't tested). IMHO, we can add an option and set it OFF by default. It seems Gentoo users might need it too.

**Comment by jubalh** [comment]
I see, I thought just a switch can be used.

**Comment by voidpin** [comment]
@jubalh I think it has been a misunderstanding here.
Currently I **can** set it to ON or OFF using CMAKE_ARGS.
I was simply asking to please **keep it** like that. It seems my comment had caused some confusion, I'm sorry for that.

**Comment by tsujan** [comment]
> Currently I can set it to ON or OFF using CMAKE_ARGS

So, I was wrong. We don't need to change anything :) @jubalh, you were right.

**Comment by voidpin** [comment]
@tsujan yes, I was just asking to please keep it as is :)

**Comment by jubalh** [comment]
Thanks for clarifying @voidpin !

**Comment by tsujan** [comment]
Nice.

You might want to override the panel's icon theme with a set that has light (symbolic) icons. That's possible at the bottom of panel config dialog.

**Comment by yan12125** [comment]
Alright, apparently I was wrong and GPG public keys on some key servers is still necessary for some scenarios. An example is Arch Linux's reproducible builds server, which [uses `gpg` to fetch public keys](https://tests.reproducible-builds.org/archlinux/community/lxqt-build-tools/build1.log).

That is as simple as a command
```
gpg --keyserver pool.sks-keyservers.net --send-keys 19DFDF3A579BD509DBB572D8BE793007AD22DF7E
```
That should be enough as SKS server exchanges keys periodically.

@tsujan mind to add that?

**Comment by tsujan** [comment]
Please tell me where I should add it and I will tomorrow -- I'm not familiar with key servers.

**Comment by AlfredoRamos** [comment]
@tsujan on the terminal, using the command @yan12125 gives you.

They key will be synced to other key servers, so you only need to send it once.

Although it's possible getting the key directly from GitHub, I don't think is a good idea to rely only on that.

```shell
gpg --fetch-keys https://github.com/tsujan.gpg
```

**Comment by tsujan** [comment]
@AlfredoRamos 
Thanks! I did it and encountered no problem (received no error message in the terminal).

However, I can't find it with `--search-keys`. Have no clue why it's so.

**Comment by tsujan** [comment]
OK, after using `--search-keys` for more that 10 times, it worked at last. Weird!

**Comment by tsujan** [comment]
Back to the main subject:

We did it :) Thank you all for your suggestions, guidance and help, without which a release wouldn't be possible.

I'll clean up the explanations whenever I find the time, although they're usable as they are.

A few components need point releases, which I'll make in 2 weeks or so. Future releases will be straightforward.

**Comment by jubalh** [comment]
@tsujan do you know when you plan to do 0.15.1?
Not that I want to hurry or anything, I just wanted to plan my time so that I have time to package 0.15.1 quickly after the release :)

**Comment by tsujan** [comment]
@jubalh Only lxqt-panel, pcmanfm-qt/libfm-qt and lxqt-archiver need point releases (https://github.com/lxqt/lxqt.github.io/issues/43). Tomorrow, I'll release pcmanfm-qt, libfm-qt and lxqt-archiver. lxqt-panel may need to wait a little because of https://github.com/lxqt/lxqt-panel/pull/1404.

In general, whenever I want to make point or, especially, major releases, I'll ask everybody for their opinions and, when I make them, I'll tell you and @yan12125.

**Comment by jubalh** [comment]
Perfect! Thanks @tsujan !

**Comment by tsujan** [comment]
You're welcome.

**Comment by voidpin** [comment]
FYI, **LXQt-0.15.0**, including all the point releases until yesterday, has been imported and is now available for all NetBSD users.

**Comment by luis-pereira** [comment]
@tsujan translations can be extracted with the `lxqt-build-tools/lxqt-transupdate` script.
Will check if the  `-DCMAKE_UPDATE_TRANSLATIONS=ON` is still in place.

**Comment by luis-pereira** [comment]
The `-DCMAKE_UPDATE_TRANSLATIONS=ON` is still working

**Comment by tsujan** [comment]
@luis-pereira 
Yes, I've used it several times to update translations for translators and will do so once in a while.
