### ISSUE TITLE
[Feature request]: app menu: when an app is dragged to desktop: mark it as trusted

### ISSUE THREAD

**Issue by tuxayo** [lxqt/lxqt#1782]
##### Expected Behavior
- drag
- double click
- app opens

##### Current Behavior
- drag
- double click
- prompt asking whether to open or execute the file

##### Possible Solution
When an app is dragged to desktop: mark it as trusted

##### Context
I was trying to see how non-tech-savvy users could do a common task a putting an app shortcut on the desktop.
The aim to eventually switch to Debian LXQt at install parties. So I'm comparing various UX things between distros and UIs.

##### System Information
* Distribution & Version: Debian 10.3 and Lubuntu 19.10
* Kernel: 4.19.0 for Debian
* Qt Version: 5.11.3
* liblxqt Version: 0.14.1
* Package version: ???

**Comment by tsujan** [comment]
"trust" is a file manager concept, not a menu concept. None of desktop entries that are shown on the main menu is seen as trusted by pcmanfm-qt (try to launch them from `/usr/share/applications`).

Moreover, the "trust" attribute isn't copied for security reasons. Only if you trust a desktop entry and *move* it somewhere, it'll keep its "trust" attribute.

Simply right click the file and trust it.
