### ISSUE TITLE
I built from scratch according to the wiki. NO other issues, but I still have no menu icons

### ISSUE THREAD

**Issue by alan12345678** [lxqt/lxqt#1783]
having had issues on my first install/use (and despite some very useful help from here) I wasn't happy. I then noticed (doh!) the wiki and the preferred order. I uninstalled everything in reverse order, and upon new build deleted the caches, so everything was built again this morning from latest git.

##### Expected Behavior

Expected behaviour: when I mouse over menu items (root menu, Applications) I expect to see icons for groups and applications

##### Current Behavior

Space is reserved for icons, and the menu works. Changing themes has no effect, neither does restarting etc.

##### Steps to Reproduce (for bugs)

1. Boot computer with latest Arch.iso install medium (on USB)
2. Create minimal working Arch install, plus base-devel packages, sound etc. but no DE 
3. Follow all the steps on the wiki page to install LXQT packages in specific order
4. Log in via SDDM. Set broad theme choices, qt5ct etc. (noting that ENV is correctly set)
5. Desktop works fine - all apps as expected, except NO icons at all in menu. This could be related to the fact that if using `obmenu-generator` it does indeed generate the correct pipe menu and static menu, but NEITHER of these appear during mouse clicks. The present right-click menu is simply that used for pcmanfm-qt i.e. a bunch of commands used in the file manager main pane.

##### Context

Obvious answer: would like to know that my installation is correct and running as designed. It's a cosmetic issue finally, but annoying.

##### System Information

* Distribution & Version: ?? latest git?
* Kernel: Linux 5.6.4-arch1-1 x86_64
* Qt Version: 5.14.2
* liblxqt Version: 13.0.87
* Package version:

**Comment by tsujan** [comment]
It's simple: incomplete installation. Didn't we talk about that at https://github.com/lxqt/lxqt/issues/1778?

> Set broad theme choices, qt5ct etc.

`qt5ct` is or DEs that have poor Qt support — usually GTK-based DEs. You don't use it in KDE or LXQt, which their rich Qt plugns.

**Comment by alan12345678** [comment]
again thank you - helpful, as clearly I'm still being a bit dim.

I have a few things I need to get done this evening but after which I'm going to go through this AGAIN because I'm determined to get it right. I'm obviously not suggesting there's anything wrong with any software, clearly it's my lack of a sufficient understanding.

To ask therefore, because I suspect I'm not the only person a little confused still:

It's easy enough to get back to a plain Arch install with no DE. So, let's assume I want a fully working Openbox/LXQT installation, with obviously sound. I also want things like proper thumbnailing for music files - which are mounted into my home dir but via a separate internal HDD. I gather that pcmanfm has built in thumbnailing, but that it can be extended with other packages (`tumbler` etc.)?

Do you see how this might feel confusing for someone new to this DE? I don't want to break it, but I seem to have become lodged in this 'need' to install all sorts of other stuff.

So, assuming I deinstall everything later today, all the way back to just the basic Arch, xorg group, sound, firewall and connman, you're saying I should put ONLY the packages listed in the wiki AND NOTHING ELSE in order to have a properly functioning LXQT installation? Even if I want my theme to be `Adwaita Dark` (which I do very much want it to be)? That doesn't require ANYTHING other than me setting the ENV accordingly? Or is even that a step too far?

I'm very happy to read instructions and wikis, I'm just not sure what I should be reading - I sort of just jumped into installing this, and now working backwards haha :)

**Comment by tsujan** [comment]
The build order is explained here: https://github.com/lxqt/lxqt/wiki/Building-from-source#generalbuild-order. Of course, any DE is more than its build. For example, you need a good-enough icon set or basic packages like `gvfs` or `perl-file-mimeinfo` — otherwise, you'll get a poor UX — but that isn't specific to LXQt.

> I also want things like proper thumbnailing for music files

You mean video files or music files with images in them. A simple Internet search would tell you about `ffmpegthumbnailer`. For PDF and DjVu you need to make simple files inside `~/.local/share/thumbnailers`. For example, for DjVu:
```sh
[Thumbnailer Entry]
Exec=ddjvu -format=tiff -page=1 -size=%sx%s %i %o
MimeType=image/vnd.djvu+multipage;image/vnd.djvu;
```
And so on, and so forth.

> Do you see how this might feel confusing for someone new to this DE?

No I can't, especially for an Arch user. Arch is built so that its users can do anything with it. They get what they do, nothing more, nothing less. So, they need to know about various aspects of Linux much more than other users do. Arch has a rich documentation.

> I'm very happy to read instructions and wikis, I'm just not sure what I should be reading

Things about how thumbnails work, what's the difference between GLib and KIO (LXQt's file manager uses GLib), Qt styling,... in short, *everything you need to control your system*. That's Arch. You don't have time and want others to do it for you? Then, you could use Ubuntu, Fedora, OpenSUSE,...

**Comment by alan12345678** [comment]
okay, so... I was trying to keep brief the amount of text on my part but, so that it IS clear:

yes. I have the icon sets I want, I have added the additional packages to extend file type thumbnailing. YES I am in complete agreement with you that the point of rolling one's own is NOT to have to suffer seemingly daft decisions made by others (installing the Xubuntu iso on an old iMac for example... it installs in hybrid mode so the graphics drivers don't work properly).

I wasn't asking you to hold my hand, I was simply asking whether, if I follow that wiki order TO THE LETTER, I can expect everything to work. You seem to be confirming this. One thing that isn't clear though - Compton. Despite the package was retired in favour of Picom, and I gather the LXQT team are now maintaining Compton, I've no idea if it is installed as a dependency of `compton-conf` all I know is that I had no window transparency until I installed Picom. Unless umm... I'm expected to install the orphaned package Compton. Happy to do that, but again it wasn't clear.

Do please try to understand - and I offer this in the light of your own remark that we are using the things you make, therefore we might approach things differently - that all I'm trying to do is install a DE! You may find me irritating, or misinformed, but while I certainly do not know nearly as much about Arch or Linux in general as others, I've tinkered with many distros over the years, and have NEVER ever had anything like this amount of involvement in simply trying to get the DE to work.

I'm very happy from what I can see. I find QT and the modular approach both refreshing and amazingly good looking. But when I notice that, for example, you immediately steered me away from the official packages for LXQT and into the git channels, and which can be updated daily, I was already feeling that if problems occur, they might not be entirely my fault. Clearly my current issue is largely of my own making but as I say, I do appreciate you taking the time, as I really DO want to stick with LXQT.

I don't think I need a degree course on the differences between Glib and KIO simply to write email or watch youtube, but I note your comments.

I'll have another go later, and promise not to file any issues - unless something genuinely does break :)

**Comment by tsujan** [comment]
> I was simply asking whether, if I follow that wiki order TO THE LETTER, I can expect everything to work.

No! There's no magic to letters. Some knowledge is presupposed, especially for those who want to build things.

> You seem to be confirming this.

Quite the opposite. Please read my comment again.

> One thing that isn't clear though - Compton.

I wouldn't recommend Compton. There are much better compositors+WMs. But if you want to try Compton, you'll need to read its comprehensive documentation. LXQt is WM/compositor agnostic.

> I offer this in the light of your own remark that we are using the things you make,

I never said that. I might have said we (LXQt devs) use what we make, which means we "eat our own dog food." Arch users use what they make out of what developers make.

> I've tinkered with many distros over the years, and have NEVER ever had anything like this amount of involvement in simply trying to get the DE to work.

That's about Arch, not LXQt. You might want to discuss that in an Arch forum but don't expect friendly responses from Arch's community when you dispute Arch's philosophy ;) Really not related to LXQt or its bug tracker or even its forum (if it wasn't down temporarily) ...

**Comment by alan12345678** [comment]
I did find out what it was, so fyi:

When I first picked my settings, I used "system" as the theme option for Openbox, simply because that would inherit the panel colours from e.g. Numix-Frost (dark). All other OB themes gave pale grey or horrid bar colours, hideous oranges or blues for contrast colours.

But this has been my problem all along!! Simply choosing ANY other theme than "system" for Openbox and all the icons etc. all come back! Doh! I had simply never thought to look there or to seek to change that particular option, until this evening!

Still, I'm now familiar with how to install LXQT! :)

**Comment by tsujan** [comment]
> Simply choosing ANY other theme than "system" for Openbox....

I'm afraid Openbox has no effect whatsoever on icons of lxqt-panel's main menu. Openbox isn't a part of LXQt; it's just an old window manager that can be used with LXQt.

But that's pretty good for one day.

**Comment by alan12345678** [comment]
My apologies - I'm being careless again! I double checked... what I meant was, in changing the LXQT theme (!!!) from "system" the icons appear. NOT changing Openbox. Sorry. But I do understand what your comment meant i.e. that OB is just a display manager.

I'll try to be more careful if I have to give further feedback... clearly my issue IS with LXQT.

**Comment by tsujan** [comment]
If you are inside an LXQt session, you should have the following environment variables and their values (use `echo $VARIABLE_NAME` to check each of them):
```
XDG_CURRENT_DESKTOP=LXQt
DESKTOP_SESSION=/usr/share/xsessions/lxqt
QT_PLATFORM_PLUGIN=lxqt
QT_QPA_PLATFORMTHEME=lxqt
```
If not, something might not be right.

**Comment by alan12345678** [comment]
aah!
 Last one returns nothing i.e `QT_QPA_PLATFORMTHEME` has no value.

**Comment by alan12345678** [comment]
those all check out correctly.
