### ISSUE TITLE
Icon-based Dock

### ISSUE THREAD

**Issue by vdaita** [lxqt/lxqt#1790]
LXQT does not appear to provide an "icon-only" dock, similar to the ones you see in Gnome, KDE, and Deepin. Is there any way that I can customize LXQT-Panel so that it only shows a single icon for each application which you can pin? Are there alternative panels for lxqt that are capable of doing that?

**Comment by tsujan** [comment]
You could use any dock with LXQt, from cairo-dock to plank. LXQt is a DE, not an app suite.

But I prefer a second auto-hiding lxqt-panel with only Quick Launch and big icons:

![panel](https://user-images.githubusercontent.com/981076/81312142-842b9200-909b-11ea-9aac-7985b4e7ab5a.png)

**Comment by vdaita** [comment]
OK, thank you! From: tsujanSent: Thursday, May 7, 2020 11:23 AMTo: lxqt/lxqtCc: V Daita; AuthorSubject: Re: [lxqt/lxqt] Icon-based Dock (#1790) You could use any dock with LXQt, from cairo-dock to plank. LXQt is a DE, not an app suite.But I prefer a second auto-hiding lxqt-panel with only Quick Launch and big icons:—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
