### ISSUE TITLE
Lxqt.org is down

### ISSUE THREAD

**Issue by Nsikak1** [lxqt/lxqt#1793]
##### Expected Behavior

going to lxqt.org should work

##### Current Behavior

the whole site seems down
##### Steps to Reproduce (for bugs)

1. 
2. 
3. 
4. 

##### System Information

* Distribution & Version: 
* Kernel: 
* Qt Version: 
* liblxqt Version: 
* Package version:

**Comment by tsujan** [comment]
Please search in issues before opening one → https://github.com/lxqt/lxqt.github.io/issues/41
