### ISSUE TITLE
The homepage lxqt.org in this project description is down

### ISSUE THREAD

**Issue by radiocane** [lxqt/lxqt#1794]
As far as I can tell, right now (2020-05-12) the homepage of LXQt is lxqt.github.io
The (old? discontinued?) lxqt.org mentioned in this project description is down.

**Comment by tsujan** [comment]
Please, please, please... *search in closed issues first.*

https://github.com/lxqt/lxqt.github.io/issues/41

**Comment by jubalh** [comment]
Gosh.. I wonder when people will finally stop creating issues for this and SEARCH FIRST!!!

**Comment by radiocane** [comment]
People will finally stop creating issues for this when they'll stop being in a hurry and will take the time to do a second search.
And maybe when the issue will be resolved 😜

**Comment by Chiitoo** [comment]
On a positive note, all the issues must mean a bunch of people care about the project.  :]

**Comment by tsujan** [comment]
> a bunch of people care about the project.

Yes, I think they care about the project and that's appreciated but the project is alive, like before if not more. That site was just a facade ;)

**Comment by jubalh** [comment]
> People will finally stop creating issues for this when they'll stop being in a hurry and will take the time to do a second search.

So you are in a hurry and we have plenty of time to clean up duplicate issues? That's awesome..

> And maybe when the issue will be resolved stuck_out_tongue_winking_eye

The problem **is** resolved. We switched to GitHub Pages.
