### ISSUE TITLE
Mouse cursor goes outside of screen when using dual displays with different heights

### ISSUE THREAD

**Issue by miopa** [lxqt/lxqt#1795]
##### Expected Behavior

Mouse cursor is confined within the boundaries of the dual display screen

##### Current Behavior

Mouse cursor can go over the top/bottom of the screen in the display with smaller height

##### Possible Solution

This is a regression, the expected behavior was present in older versions.

##### Steps to Reproduce

1. Use dual displays with different heights
2. Move cursor up and down in the display with smaller height

##### Context

It seems that with this regression a "gray" desktop area is introduced, where cursor can go and objects can be placed, but can't be seen on the actual screen.

##### System Information

* Distribution & Version: Arch-Linux x86_64
* Kernel: 5.6.12
* Qt Version: 5.14.2
* liblxqt Version: 0.15.0
* Package version: 0.15.0-1

**Comment by miopa** [comment]
I'm suspecting that resolving this issue could also help fix #1787

**Comment by tsujan** [comment]
I can't reproduce this with KWin and by changing the resolution of one monitor (to make it smaller): the cursor never goes beyond the edges of any screen and that's independent of where I put the screens.

Which window manager do you use?

**Comment by hmollercl** [comment]
I had same problem with nvidia drivers but NOT with nouveau.  Nvidia handles my screen as a giant rectangle "containing" both screen. Nouveau handles it correctly. I'm not sure if it happens the same with other than openbox and/or lxqt.
@miopa which card/driver are you using?

**Comment by tsujan** [comment]
@hmollercl 
Interesting info.

I have Intel with `modesetting` but it doesn't make a difference when I use the Intel driver: the cursor never goes beyond virtual screen edges with KWin (haven't had time to try Openbox).

**Comment by miopa** [comment]
I have NVIDIA GT218M [NVS 3100M] with nouveau driver and openbox.
Displays are set like this
```
eDP-1:
 Mode: 1440x900
 Rate: 60.0014 Hz
 Rotation: None
 Position: 0x140
 Primary: True
 Enabled: True
VGA-1:
 Mode: 1680x1050
 Rate: 59.8833 Hz
 Rotation: None
 Position: 1454x0
 Primary: False
 Enabled: True
```
I'm sending a photo of the screen to explain better
![image](https://user-images.githubusercontent.com/701875/82101464-d78d8800-970c-11ea-9b15-cfde0c328371.png)

You can see on the top the mouse is starting to get out, but you can get the whole picture from the internal screenshot

![image](https://user-images.githubusercontent.com/701875/82100509-153ce180-970a-11ea-8b3d-2fa279a9df60.png)

**Comment by miopa** [comment]
After some more fiddling:

* Behavior is same with `xfwm4` and `fvwm2` instead of `openbox`

* when monitors are 'joined' (extended monitor starts at the pixel that corresponds to primary monitor resolution), mouse cursor is working as expected (confined within visible screen). First row of icons is still outside screen, now completely unreachable.

**Comment by Kharzette** [comment]
For me, my mouse stays confined, but icons on the smaller desktop are often in the phantom area above the monitor.

**Comment by tsujan** [comment]
LXQt can't cause this. It may be caused by window manager, graphics driver,... but not by LXQt.

**Comment by tsujan** [comment]
As for desktop items, see https://github.com/lxqt/pcmanfm-qt/issues/1753
