### ISSUE TITLE
lxqt desktop option to launch WM menu lost with 0.15.0 version

### ISSUE THREAD

**Issue by je-vv** [lxqt/lxqt#1796]
With prior version (0.14.1) and older, it was possible to allow accessing the window manager specific menu by the right click on the desktop.  There was an option on the advanced settings for desktop for tat purpose.  One could reach to it through the main menu preferences, on the desktop ones, or by accessing to that same desktop advance setting on the desktop right click.

That option is gone on 0.15.0.  It's pretty useful for me, when using fluxbox, particularly to reboot it through its menu.

Can you please bring thar option back?

##### System Information
* Distribution & Version:  Arch GNU+Linux latest version
* Kernel:  5.6.12
* Qt Version:  5.14.2
* liblxqt Version:  0.15.0
* fluxbox Version:  1.3.7

**Comment by tsujan** [comment]
Search in closed issues and PRs to know why.

**Comment by ito32bit** [comment]
@je-vv please see https://github.com/lxqt/pcmanfm-qt/issues/1112

**Comment by je-vv** [comment]
Thanks for the reference,actually https://github.com/lxqt/pcmanfm-qt/pull/937 is what I'm missing, since as I use Fluxbox, I'd like to use some fluxbox specific instructions from its menu (restart fluxbox being the most frequent one, but not the only one).  I created some fluxbox shortcuts/keys (they can't be lxqt ones since they're fluxbox specific) to do the more frequent operations I do, and for the rest, well, I guess I'll have be creating more of those, and restart fluxbox when in need.  The menus was very convenient.

As to wayland, well, by keeping track of https://github.com/lxqt/lxqt/issues/10, I really don't see lxqt working fine with a wayland compositor any time soon.  I have a lot of hope on wayfire, but lxqt isn't any close to work with it.  And I'd also like to wait some time to see in the end lxqt doesn't end up being forced to choose just a particular compositor any ways.  I just mentioned this since part of the reasoning to remove the WM menu support is looking ahead for wayland, but to be honest I don't see lxqt main path being wayland any time soon.  So to me the remotion sounds a little too soon.  But I guess I do have workarounds for not being able to access fluxbox functionality thorugh its menu...

@ito32bit, thanks a lot for the URL.  I did a quick search for the reasoning looking on github, and I didn't find anything that close (my bad search abilities I'd guess).  And the PR with the reasoning was included in the issue you pointed out, thanks again.

**Comment by tsujan** [comment]
> As to wayland, well, by keeping track of #10, I really don't see lxqt working fine with a wayland compositor any time soon.

We've made some components work under Wayland; pcmanfm-qt (and, of course, libfm-qt) is one of them. Since LXQt is modular, one can have a Wayland session with KDE, Wayfire, etc. and use pcmanfm-qt without problem.

Removing X11-specific code is a must but, in this case, it wasn't just about X11. That option worked with specific window managers -- some of which weren't developed anymore -- and not with others.
