### ISSUE TITLE
LXQt link in repositories is old (http://lxqt.org/)

### ISSUE THREAD

**Issue by ito32bit** [lxqt/lxqt#1797]
##### Current Behavior

Screenshot:  
![lxqt-link_mark](https://user-images.githubusercontent.com/52656419/82108668-118d7700-976b-11ea-9adf-80cae51a395b.png)

https://github.com/lxqt/lxqt
https://github.com/lxqt/lxqt-about
https://github.com/lxqt/qterminal
https://github.com/lxqt/lxqt-powermanagement
https://github.com/lxqt/qtermwidget
https://github.com/lxqt/lxqt-panel
https://github.com/lxqt/liblxqt
https://github.com/lxqt/libfm-qt
https://github.com/lxqt/lxqt-notificationd
https://github.com/lxqt/screengrab
https://github.com/lxqt/lxqt-globalkeys
https://github.com/lxqt/lxqt-session
https://github.com/lxqt/libqtxdg
https://github.com/lxqt/pavucontrol-qt
https://github.com/lxqt/lxqt-admin
https://github.com/lxqt/lxqt-openssh-askpass
https://github.com/lxqt/lxqt-runner
https://github.com/lxqt/lxqt-policykit
https://github.com/lxqt/libsysstat
https://github.com/lxqt/lxqt-qtplugin
https://github.com/lxqt/lxqt-build-tools
https://github.com/lxqt/lxqt-release-foo
https://github.com/lxqt/lxqt-l10n
https://github.com/lxqt/lxqt-common-deprecated
https://github.com/HelixBot

##### Possible Solution

Change http://lxqt.org/ -> https://lxqt.github.io/
or,
Remove link

##### Steps to Reproduce (for bugs)

1. Open url in browser

**Comment by tsujan** [comment]
Thanks. They should be corrected.

**Comment by tsujan** [comment]
@Chiitoo 
On the one hand, the future of "lxqt.org" is uncertain; on the other hand, GitHub repositories are the places where LXQt components are really developed and all the needed info can be found on their pages (I added and will add release notes too).

So, I can't see any reason why something like "lxqt.org" should go into packages, even if it was running.

**Comment by Chiitoo** [comment]
One advantage to it was having another (official) mirror for the sources, but indeed, I'll at least switch the homepage links to GitHub, and probably drop the download site until we know more.

Thanks!

**Comment by tsujan** [comment]
> One advantage to it was having another (official) mirror for the sources

We put each source in two places? Where, in addition to GitHub?

**Comment by Chiitoo** [comment]
There is/was 'downloads.lxqt.org'.

**Comment by tsujan** [comment]
You mean Alf synced them with GitHub?

We can have backups on GitLab but I don't know if that's needed. Is it?

**Comment by Chiitoo** [comment]
Yeah, I guess so, or in any case they were available from there as well.

Don't know if it's needed.  Licenses permitting, the Gentoo mirrors will have them too, after a while, and though I don't know how other distros do these things, I imagine they're not relying on one source either.

**Comment by tsujan** [comment]
If backups are needed, I think GitLab is a good place because, as far as I remember, it has automatic syncing with GitHub (although, it didn't work for me, the last time I checked) but I don't know about "read-only" -- we don't want to receive reports from 2 places.

**Comment by jubalh** [comment]
Yes agaida put the release tarballs on lxqt.org.

I'm also content with GitHub for the time being.

**Comment by tsujan** [comment]
> Yes agaida put the release tarballs on lxqt.org.

Oh, that couldn't be a real backup -- at least not what I had in mind (reports, commits, history,...).

**Comment by jubalh** [comment]
Yes it wasn't meant as such. It was just for people who wanted to get the tarballs. Packagers mostly :)

**Comment by tsujan** [comment]
Thanks for the clarification!

So, we've lost nothing. Unless all of us as well as some distros go into a parallel universe, there are lots of backups of the latest works in this one.

Off topic:
Does anyone know how Debian could have a maintainer? I know that we don't need to care about Debian -- Debian itself should -- but it's an important distro with many derivatives that get their packages from it (if I correctly remember).

**Comment by tsujan** [comment]
Replying to myself: According to https://wiki.debian.org/DebianMaintainer, unless a currently active Debian maintainer starts to package LXQt, Debian's average users won't have LXQt for a very long time.

**Comment by wxl** [comment]
@tsujan my goal is to get more Lubuntu Developers, or at least myself, certified as a Debian Developer, so that we could help out here. I didn't know about the whole DM thing, which seems to have less stringent requirements (Debian *is* kind of a pain with all their rules) so perhaps that will be something to look into.

**Comment by tsujan** [comment]
> my goal is to get more Lubuntu Developers, or at least myself, certified as a Debian Developer

Good to know that.

> Debian is kind of a pain with all their rules

I know. Was a Debian user for 8 years and, because of their rules, had to make deb packages of many programs for my personal use. I used Arch wiki to find answers for Debian -- and I always found them there, not in Debian wiki.

**Comment by luis-pereira** [comment]
Done.
Changed http://lxqt.org to https://lxqt.github.io. Except for https://github.com/HelixBot, it's a distinct user and I don't have access.

**Comment by tsujan** [comment]
Very good.
