### ISSUE TITLE
Feature request: Panel items identification by editable names

### ISSUE THREAD

**Issue by mileon** [lxqt/lxqt#1798]
##### Current Behavior
Panel items are listed with automated names. With many items is not easy (for me) to identify the items.

##### Possible Solution
Right click on panel item - > edit name

##### System Information
* Archlinux & all Updates from 19.05.2020 are installed
* Kernel: 5.6.13-arch1-1
* Qt Version: 5.14.2
* liblxqt Version:  0.15.0-2
* Package version: 0.15

**Comment by tsujan** [comment]
What do you mean by "Panel items identification"? Task manager items? They get their names from their corresponding windows and, because of that correspondence, renaming doesn't make sense.

Please be specific when reporting issues or making feature requests.
