### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by Thomas-N** [lxqt/lxqt#1799]
I recently installed Lubuntu 20.04 on my little netbook and noticed the Dutch translations were incomplete and sometimes incorrect. I thought I'd see if I could contribute, however, [the page about contributing translations](https://github.com/lxqt/lxqt/wiki/Translation) to LXQt has not been updated since 2018 and points to a seemingly non-existent Weblate instance.

What would be the recommended way to contribute translations?

**Comment by stefonarch** [comment]
Before weblate and lxqt.org went down the only way was to fork and make pull requests, and those  will be well accepted. 
Have a look at the revisions of the translate wiki
https://github.com/lxqt/lxqt/wiki/Translation/0dcb268bd77c7536330417d6ec2d56e674b94c44
At some point all translations except .desktop file were in a separate repo, but now there are again under the main component, eg https://github.com/lxqt/pcmanfm-qt/tree/master/pcmanfm/translations

**Comment by Thomas-N** [comment]
Thanks! I'll take a look at it.

**Comment by tsujan** [comment]
Translations are very welcome. You could use Qt Linguist and make PRs *against latest git sources*.

**Comment by yarons** [comment]
I understand that the domain is dead but that doesn't necessarily mean that the server is down, maybe we can setup a temporary domain and Let's Encrypt certificate and update all the links so the translators will be able to work in a more convenient way.
