### ISSUE TITLE
autostart bash script keeps running after logout

### ISSUE THREAD

**Issue by bkw777** [lxqt/lxqt#1800]
##### Expected Behavior

This is a question, maybe not a bug.

~/.config/autostart/foo.desktop starts a bash script wth a never-ending while-loop.
The script uses while & wait $!, so it still responds to signals immediately even while in the middle of "sleep 1h".

I would like the script to end when the user logs out. Not reboot, X would still be running, the display manager would still be running, but there is no more desktop sesion. All other children of that session have ended. I would like this to end too.

##### Current Behavior

The problem is the autostarted script keeps running after the user logs out.
Then at next login (without reboot) it starts up a new copy. They accumulate forever.
 but really, somehow it should end when everything else from that session ended. It's receiving no signals except 17 from it's own child processes, and 1 & 15 at power-off, but nothing at all at merely log-off.

##### Possible Solution

I have implimented "find predecessor & kill before start" logic in the script as a way to deal with this by brute force. It still leaves an unwanted acript running after logoff, it's just that the new instance can now find and kill the old instance so they don't accumulate beyond one per $DISPLAY

Is there something I can do within the script to detect that the session is gone? A gdbus command to look for something?

##### Steps to Reproduce (for bugs)

1. 
2. 
3. 
4. 

##### Context

This is part of a fork of "ukuu" which I did not write originally but am now maintaining.
It's a sleep loop that checks for new mainline kernel packages appearing on the ubuntu mainline ppa.
http://github.com/bkw777/mainline

I am sure that this is the wrong way to impliment such a background task. I didn't write it originally and I don't know how to write a correct version of something like that, at least not from scratch. If there is an example of some other app that works like that I could adapt it.

Thanks

##### System Information

* Distribution & Version: lubuntu xenial, bionic, cosmic, disco, eoan, ...
* Kernel:
* Qt Version: 
* liblxqt Version: all for at least the last year since I've been using this app. Today is 0.14.1
* Package version:

**Comment by tsujan** [comment]
Not related to LXQt. Logout is managed by systemd.  Set `KillUserProcesses` to `yes` in "/etc/systemd/logind.conf".

**Comment by bkw777** [comment]
I have to assume that would affect such things as ssh sessions and screen/tmux etc, and so was bad advice.
But if it's not any part of lxqt that reads the .conf/autostart directory to launch the apps, then it's not lxqt's problem to solve so thank you for the info.

**Comment by tsujan** [comment]
> But if it's not any part of lxqt that reads the .conf/autostart directory to launch the apps, then it's not lxqt's problem to solve

The name of that directory tells about its job in a self-explanatory way: auto-start, not auto-kill.

> I have to assume that would affect such things as ssh sessions and screen/tmux etc

Read systemd doc to know how to use a terminal multiplexer with `systemd-run`.

Anyhow, this place is LXQt's bug tracker. Questions like these belong to your ditro's forums.
