### ISSUE TITLE
Users panel locked, does not allow unlock

### ISSUE THREAD

**Issue by ApopheniaPays** [lxqt/lxqt#1801]
##### Expected Behavior

The user panel should allow me to make changes to the user accounts. It says "Unlock to change settings" but the "Unlock..." button is disabled and cannot be clicked. 

##### Current Behavior
1. Click "Unlock..." button
2. User stays locked

##### Possible Solution
Make "Unlock..." button functional.

##### Steps to Reproduce (for bugs)
1. Open "Users".
2. Click "Unlock..." button.
3. Nothing happens, user remains locked. 

##### Context
I need to set a user to be auto-logged in but the autologin setting is locked by this "feature".

##### System Information

* Distribution & Version: Ubuntu 20.04 LTS
* Kernel: I have absolutely no idea
* Qt Version: 5? 
* liblxqt Version:  I have absolutely no idea
* Package version:  I have absolutely no idea

**Comment by palinek** [comment]
Sorry, but what is "user panel" ? What application are you talking here about?

**Comment by tsujan** [comment]
@ApopheniaPays
This is the second time you expect telepathy from us.

> liblxqt Version: I have absolutely no idea

Then, LXQt has absolutely no idea what your problems is.

But if you have Ubuntu 20.04 LTS, most probably, your LXQt installation is outdated.
