### ISSUE TITLE
State of Wayland in LXQt 2020?

### ISSUE THREAD

**Issue by EarthlingX** [lxqt/lxqt#1804]
Dear LXQt-developers,

thank you very much for your awesome work! We really appreciate your efforts!

May I ask you about a rough schedule of implementing Wayland into LXQt? Is there anything in the pipe or planned already?

Looking forward to hearing from you! :+1:

**Comment by tsujan** [comment]
Read https://github.com/lxqt/lxqt/issues/10 (from end to start) to see why the Wayland situation is far from ideal, although improving. Moreover, we like to keep LXQt agnostic to WM/compositor as far as possible but Wayland might break that.

**Comment by tsujan** [comment]
And please note that the year (2020) isn't relevant. Wayland should become as usable as X11 is. We (LXQt team) aren't Wayland developers.
