### ISSUE TITLE
[Suggestion] Allow to change DPI settings on the fly

### ISSUE THREAD

**Issue by renom** [lxqt/lxqt#1805]
It'd be great to be able to change DPI settings without restarting everything. It can already be done for GTK apps in GNOME/Cinnamon. Is it possible to have this for Qt and GTK apps in Lxqt?

Use case: a laptop with Full HD screen, an external monitor is 4K UHD. Since there's no way to have per-monitor settings without Wayland, the only solution I've found is to change DPI settings depending on the current screen.

**Comment by tsujan** [comment]
https://github.com/lxqt/lxqt-config/issues/402 already exists. Please add your suggestion to it.
