### ISSUE TITLE
Panel menu entries are in the wrong order

### ISSUE THREAD

**Issue by jidak** [lxqt/lxqt#1807]
Most items in the menu are in alphabetical order, but some are not. The screenshots attached show that MPV and qps are in the wrong order. Other packages go in the wrong order when installed, such as Compton.

I can't find any way to change the menu order in `/etc/xdg/menus/lxqt-applications.menu`. None of the `.desktop` files are mentioned in that file.

There should be a way to edit the order of the menu items, but I can't find one.

LXQt 0.14.1
![menu](https://user-images.githubusercontent.com/66788998/84410205-d1a09f00-ac05-11ea-8093-67d7804b7740.jpg)
![menu2](https://user-images.githubusercontent.com/66788998/84410281-d7968000-ac05-11ea-851a-b59735c24c23.jpg)

**Comment by tsujan** [comment]
1. The alphabetical order is case-sensitive.
 2. LXQt 0.14.1 is outdated (although that isn't related to case-sensitivity).
 3. You could report it to your distro.

**Comment by jidak** [comment]
So is it not possible to change the menu order manually?

In Xfce this can be done via `/etc/xdg/menus/xfce-applications.menu` or `~/.config/menus/xfce-applications.menu`. Why is this not possible in LXQt?

**Comment by tsujan** [comment]
You've mistaken the main categories with items.
