### ISSUE TITLE
Panel: Disabling 'Visible thin margin for hidden panel' does not work

### ISSUE THREAD

**Issue by jidak** [lxqt/lxqt#1808]
If I set a panel to auto-hide, and disable 'Visible thin margin for hidden panel', there is still a margin visible.

The first screenshot is with the margin enabled and the second screenshot is with the margin disabled. As you can see, there is an identical margin in both screenshots.
![with visible thin margin](https://user-images.githubusercontent.com/66788998/84412432-25f84e80-ac07-11ea-8393-65c26435c147.jpg)
![without visible thin margin](https://user-images.githubusercontent.com/66788998/84412463-314b7a00-ac07-11ea-84ca-0f41adcbda56.jpg)

LXQt 0.14.1

**Comment by jidak** [comment]
This next screenshot has no panel. This is what it should look like with the margin disabled.
![no panel](https://user-images.githubusercontent.com/66788998/84412689-8091aa80-ac07-11ea-9557-916a4faecf2e.jpg)

**Comment by tsujan** [comment]
1. The invisible panel margin needs compositing, which apparently you don't have.
2. Please don't report issues of an outdated LXQt version (although this wasn't an issue).

**Comment by jidak** [comment]
Ok. Then it would be a good idea either to:
a. grey-out the option if there's no compositing;
b. Write 'Requires compositing' next to the option.
