### ISSUE TITLE
Custom .desktop entries not opening by menu 

### ISSUE THREAD

**Issue by aquaspy** [lxqt/lxqt#1809]
Well, the bug consists in: I can open my program with terminal, I can open it in the "other" application menu in pcmanfmqt(print below)

![image](https://user-images.githubusercontent.com/49214136/84612236-61f51300-ae96-11ea-9964-75e6964b89f8.png)

But the app does not start by the default menu (by default menu I mean the menu you can search in)
![image](https://user-images.githubusercontent.com/49214136/84612374-daf46a80-ae96-11ea-9663-135eddb815c3.png)

I am really not sure about what is happening here. This is my .desktop entry 
https://ghostbin.co/paste/hnx36
(It was working fine in XFCE and gnome)

##### System Information
                                                         --->
* Distribution & Version: 
* Kernel: arch lts (5.4.46)
* Qt Version: 5.15.0

**Comment by stefonarch** [comment]
Hm, you could try to replace  $HOME/.apps ecc in the exec line with the complete path.

**Comment by aquaspy** [comment]
> Hm, you could try to replace $HOME/.apps ecc in the exec line with the complete path.
> Any reason for not using
> `Exec=/home/user/.apps/waterfox/waterfox` ?

Just tried it, but seems like still not opening by the normal menu.

My reason to use $HOME insteada my user is that I create "universal" insatllers, that do not require user manual intervention.

**Comment by aquaspy** [comment]
> Hm, you could try to replace $HOME/.apps ecc in the exec line with the complete path.
> Any reason for not using
> `Exec=/home/user/.apps/waterfox/waterfox` ?

Just tried it and it worked! But why $HOME isn't working in lxqt? I usually use it because I don't want to manually set the user. Also, I create scripts for installing it, and those scripts are supposed to work with any user.

**Comment by tsujan** [comment]
Because you do it in an incorrect way. Try:
```
Exec=bash -c "$HOME/.apps/waterfox/waterfox"
```
See https://specifications.freedesktop.org/desktop-entry-spec/latest/ar01s07.html

**Comment by aquaspy** [comment]
> Because you do it in an incorrect way. Try:
> 
> ```
> Exec=bash -c "$HOME/.apps/waterfox/waterfox"
> ```
> 
> See https://specifications.freedesktop.org/desktop-entry-spec/latest/ar01s07.html

Sorry and thanks for helping!
