### ISSUE TITLE
lx-panel sensors widget display wrong colors using Kvantum theme

### ISSUE THREAD

**Issue by redtide** [lxqt/lxqt#1810]
Before setting the `QT_QPA_PLATFORMTHEME` to `lxqt` from `qt5ct` , the bar colors was respecting the settings, after the change it stopped working, as seen in the following snapshots.

before with `QT_QPA_PLATFORMTHEME=qt5ct`:
![sensors-qt5ct](https://user-images.githubusercontent.com/1171962/84631656-08b8ce00-aeee-11ea-85da-dcea7c8b0b62.png)

after using `QT_QPA_PLATFORMTHEME=lxqt`:
![sensors-lxqt](https://user-images.githubusercontent.com/1171962/84631669-0f474580-aeee-11ea-8116-1e98755d26af.png)

##### Expected Behavior
See the initial description.

##### Current Behavior
See the initial description.

##### Possible Solution
I don't know much about QT theming.

##### Steps to Reproduce (for bugs)
IDK if GTK Adwaita is relevant because those blue colors, I see changing the theme with Kvantum Manager to e.g. KvDarkRed sets all the bar colors to red instead.
All I did as suggested in a different issue was to modify `$HOME/.config/lxqt/session.conf` as descripted above.

##### Context
See the initial description.

##### System Information
* Distribution & Version: Archlinux
* Kernel: 5.6.15-arch1-1
* Qt Version: qt5-base 5.15.0-2
* liblxqt Version: liblxqt 0.15.1-1
* Package version: lxqt-panel 0.15.1-1

**Comment by tsujan** [comment]
You have chosen `kvantum` in LXQt Appearance Configuration → Widget Style → Qt Style. Change it to `Fusion` or `Breeze` and you'll see the bar colors again (log out and log in after that).

Being an SVG based style, Kvantum uses SVG elements for progress-bars, not simple colors.

However, your report shows a problem in the Sensors plugin: if it uses custom colors for progress-bars, it should use styleesheets in its code, not palettes of `QStyle`. So, the report is valid; I'll look into panel's code.

**Comment by tsujan** [comment]
Will be fixed when https://github.com/lxqt/lxqt-panel/pull/1418 is merged. Thanks for the report!

**Comment by redtide** [comment]
Thanks, quick fix! Do I leave the issue open or close it?

**Comment by tsujan** [comment]
Please leave it open. It'll be closed automatically when its corresponding PR is merged. Moreover, I'll make the PR's code a little better in a few minutes.
