### ISSUE TITLE
lxqt-panel-0.15.0 set to autohide - cursor over systray makes panel hide

### ISSUE THREAD

**Issue by peabee** [lxqt/lxqt#1812]
lxqt-panel-0.15.0
qt5-5.15.0

##### Expected Behavior
panel should not autohide when cursor over systray

##### Current Behavior
panel hides when cursor over systray (does not hide for any other widget)

##### Possible Solution
none known

##### Steps to Reproduce (for bugs)
1. make panel autohide
2. move cursor over systray

##### Context
difficult to select and activate systray apps

##### System Information
* Distribution & Version: Puppy with LXQt addon from Arch
* Kernel: 5.7.2
* Qt Version: 5.15.0
* liblxqt Version: 0.15.0-2.0
* Package version: lxqt-panel-0.15.0-1.0

http://murga-linux.com/puppy/viewtopic.php?p=1060909#1060909

**Comment by Chiitoo** [comment]
See also: https://github.com/lxqt/lxqt-panel/issues/1266

**Comment by tsujan** [comment]
The tray plugin is obsolete. Add Status Notifier to the panel.

**Comment by tsujan** [comment]
@luis-pereira, @yan12125, @jubalh, @Chiitoo,... everyone:

Any suggestion about how we could inform users that System Tray is obsolete and Status Notifier should be used? I'm not saying that it should be removed (should it?) but the current situation can be really confusing.

**Comment by luis-pereira** [comment]
We could show a info dialog when the user adds the systray plugin.
For already in use systrays, show a info dialog every time the plugin starts, with the option to not show it again.

**Comment by Chiitoo** [comment]
Well, removing it certainly would make people notice easier, but it might indeed be a bit heavy-handed, so to speak, especially considering that some applications can't use Status Notifier yet (mostly GTK+2 apps I guess, such as Claws Mail).

A notification dialog of some kind seems like a good idea to me too.

**Comment by jubalh** [comment]
> but it might indeed be a bit heavy-handed, so to speak, especially considering that some applications can't use Status Notifier yet (mostly GTK+2 apps I guess, such as Claws Mail).

Good that you say this. In this case I don't think it should be removed yet.

> We could show a info dialog when the user adds the systray plugin.
> For already in use systrays, show a info dialog every time the plugin starts, with the option to not show it again.

I like this approach.

**Comment by tsujan** [comment]
> I don't think it should be removed yet.

I agree.

But, IMHO, a dialog that's shown *every time* the plugin starts would be an extreme way of giving info. It would mean, "Don't use this or we'll annoy you!"

**Comment by luis-pereira** [comment]
> But, IMHO, a dialog that's shown _every time_ the plugin starts would be an extreme way of giving info. It would mean, "Don't use this or we'll annoy you!"

Hence the 'Do not show it again' option.

**Comment by tsujan** [comment]
OK.

Will try to add it before V0.16.0.

**Comment by peabee** [comment]
Thank you for your responses.
I will try to use Status Notifier (first time I have heard mention of such) however I suspect that there may be problems given that all the tray items are from Puppy Linux.
I hope that this will not be the killer which stops LXQt being compatible with Puppy Linux but I fear it may be!

**Comment by tsujan** [comment]
@peabee 
Only very old apps (usually, "dead" apps) may need the old systray. All other apps should put their tray icons inside Status Notifier if you install `dbusmenu` packages (`libdbusmenu-qt5` -- which is a dependency -- as well as other dbusmenu packages).

You could also add the old systray beside Status Notifier; they aren't incompatible. However, systray's code is based on X11 and won't be updated.

**Comment by peabee** [comment]
Yes - as I suspected - the Status Notifier does not display any of the systray items....
![Screenshot](https://user-images.githubusercontent.com/5926865/84796194-443bc100-aff0-11ea-947c-91c3b30f72a8.png)

**Comment by tsujan** [comment]
Please read my comment (about dbusmenu) above your last comment.

**Comment by peabee** [comment]
Have tried installing the suggested dbusmenu items - screenie shows top panel with systray; bottom panel with Status Notifier which is completely blank...... grateful for any further suggestions and guidance - thank you.

![Screenshot](https://user-images.githubusercontent.com/5926865/84882013-8b749100-b086-11ea-8e03-c8c2c0ae9adb.png)

**Comment by tsujan** [comment]
> bottom panel with Status Notifier which is completely blank

Please be more specific! What should be there?

> screenie shows top panel with systray

I don't know about `screenie`; I can't install it because it isn't in Arch repositories. Maybe it still uses the old tray, which isn't good. LXQt's screenshot utility is `screengrab`.

BTW, `libdbusmenu-gtk3` seems to be missing from your system.

**Comment by peabee** [comment]
Sorry - "screenie" is short for "screenshot" and means that the attached image shows the 2 panels.
What should be on the bottom panel if Status Notifier is to replace systray are the 5 icons on the top panel to the right of the screen and to the left of the clock - which are from left to right: sound volume, clipboard, network connect, storage use, and firewall.
libdbusmenu-gtk3 is not there because this Puppy Linux system does not include gtk3..... do I need it? LXQt is working (apart from systray) fine without it.

**Comment by tsujan** [comment]
> sound volume, clipboard, network connect, storage use, and firewall

I meant which apps? For example, to which clipboard manager does the clipboard icon belong?

I ask in order to test them here if possible.

> libdbusmenu-gtk3 is not there because this Puppy Linux system does not include gtk3

If you don't use GTK3 apps, you don't need libdbusmenu-gtk3.

**Comment by peabee** [comment]
A bit tricky as they are all Puppy Linux apps only available in .pet format - mainly from:
http://distro.ibiblio.org/puppylinux/pet_packages-slacko14.2/

retrovol
parcellite
netmon_wce
freememapplet
firewallstatus

if you can install .pets (??) the best version to try would be an "s700" version

**Comment by tsujan** [comment]
OK, I think `parcellite` is enough: it's a very old gtk2 clipboard manager, not compatible with up-to-date notification areas. `clipit` is also based on GTK2 but compatible.

All in all, if you insist on using very old programs, you'll have to use the old systray with all its limitations.

> if you can install .pets

I'm on an Arch based distro. Arch's repository may contain ancient apps too (like `retrovol`, from 2015!) but, except for `parcellite` and `retrovol`, I couldn't find the others in it.

You may not like this but, frankly, those apps are weird choices to me. Doesn't Puppy have packages for `CopyQ` or `Qlipper`, for example? Or, at least, `clipit`? Or why using `retrovol` when LXQt panel has a volume control plugin?

Back to a previous comment of yours:

> I hope that this will not be the killer which stops LXQt being compatible with Puppy Linux

If Puppy Linux is based on very old apps (that's a big *"if"* about which I have no idea at all), LXQt won't be compatible with it sooner or later.

**Comment by vitaly-zdanevich** [comment]
I tried to add widget `Status Notifier` but I see it as `Unknown` and tray is not exists for me.
![screen](https://user-images.githubusercontent.com/3514015/106925085-ccf2a300-6720-11eb-85ce-ae29c45ce29a.jpg)

**Comment by tsujan** [comment]
> I tried to add widget Status Notifier but I see it as Unknown 

Something should be wrong with the package your distro provides. Ask you distro about that!

In short:

 1. The systray plugin is obsolete. Use Status Notifier Plugin instead!
 2. If you have gtk3/gtk2 apps with tray icons, install `libappindicator` packages.
 3. If you have a very old gtk2 app that doesn't work with `libappindicator`, stop using it (or tolerate the problems it has with modern system trays).

**Comment by vitaly-zdanevich** [comment]
Installed `libappindicator`. But how to install `Status Notifier Plugin` widget for tray? I want to see `nm-applet`, looks like this is a GTK software.

**Comment by tsujan** [comment]
> But how to install Status Notifier Plugin widget for tray?

Status Notifier Plugin is a part of the Panel itself, not a separate app.

As I said, you may want to ask your distro as to why Status Notifier Plugin isn't included. Your distro should have a forum for asking questions.

**Comment by tsujan** [comment]
@Chiitoo, does Gentoo's package for lxqt-panel exclude Status Notifier Plugin? Or is there something else specific to Gentoo?

**Comment by vitaly-zdanevich** [comment]
Filled issue at https://bugs.gentoo.org/768666

I found official ebuild: https://github.com/gentoo/gentoo/blob/master/lxqt-base/lxqt-panel/lxqt-panel-0.16.1.ebuild

**Comment by tsujan** [comment]
> I found official ebuild:...

I have no knowledge of Gentoo or how ebuild works but Status Notifier Plugin *is* included in that ebuild, with `libdbusmenu-qt` as its dependency. So, perhaps you didn't have `libdbusmenu-qt` when you compiled lxqt-panel.

@Chiitoo is the expert in Gentoo.

**Comment by Chiitoo** [comment]
Indeed, 'libdbusmenu-qt' will be pulled in with USE="statusnotifier", and the plugin will then also be enabled during build.

**Comment by vitaly-zdanevich** [comment]
`libdbusmenu-qt` is installed, Gentoo automatically (according to ebuilds) handle dependencies.

**Comment by vitaly-zdanevich** [comment]
I found that `statusnotifier` USE flag was disabled for me, looks like this must be enabled by default in ebuild.

I rebuild, yes now in Widgets I see `Status Notifier Plugin (statusnotifier)`, but what about tray with `nm-applet`? Looks like `statusnotifier` is a different type of widget - only for notifications, not a replacement for obsolete systray.

**Comment by tsujan** [comment]
> Looks like statusnotifier is a different type of widget - only for notifications, not a replacement for obsolete systray

So wrong.

**Comment by Chiitoo** [comment]
I have been meaning to switch the default from 'tray' to 'statusnotifier', but keep forgetting about it.  Will probably do that at the next version bump at the latest, if I'm still the maintainer at that time.

The name made me think of something different back a while ago as well [1], and from the looks of it, if you want to blame someone or some thing for it, that should probably be freedesktop.org [2] for choosing it.  :]

1. https://github.com/lxqt/lxqt-panel/issues/1266#issuecomment-564237780
2. https://www.freedesktop.org/wiki/Specifications/StatusNotifierItem/

**Comment by wxl** [comment]
It sounds to me like this discussion entirely relates to issues within the scope of Gentoo, so it seems appropriate to move this entire discussion out of this issue and into that Gentoo bug.

**Comment by tsujan** [comment]
@wxl, yes, I told @vitaly-zdanevich twice. Distro-specific things just waste time here and it doesn't matter whether they're about Gentoo, Ubuntu, Arch,..

@Chiitoo, as for the name "Status Notifier", I agree that it isn't the best name `freedesktop.org` could have chosen, especially when the word "tray" has existed for a very long time. Anyway, we didn't coin it.

**Comment by vitaly-zdanevich** [comment]
I found that on Gentoo I need to build [nm-applet](https://packages.gentoo.org/packages/gnome-extra/nm-applet) with USE flag `appindicator`. Description of this flag: `Build in support for notifications using the libindicate or libappindicator plugin`.
