### ISSUE TITLE
Alt+F2 shortcut stopped working

### ISSUE THREAD

**Issue by alexandre1985** [lxqt/lxqt#1813]
I'm using ArchLinux x64.
After update, the shortcut Alt+F2 stop working.
The shorcut is set as Alt+F2 in Control Panel > Shortcuts
Running `lxqt-runner` gives me this error:
```
lxqt-runner: symbol lookup error: lxqt-runner: undefined symbol: _ZN2mu6ParserC2Ev
```

##### Steps to Reproduce (for bugs)

1. Press Alt+F2

##### Context

I want to lanch applicantions using the Alt+F2 shortcut
##### System Information

* `uname -a`: Linux acer 5.4.46-1-lts #1 SMP Wed, 10 Jun 2020 20:36:34 +0000 x86_64 GNU/Linux
* qt5-base Version: 5.15.0-3
* liblxqt Version: 0.15.1-1
* lxqt-runner: 0.15.0-1
* lxqt-session: 0.15.0-1

**Comment by tsujan** [comment]
See https://github.com/lxqt/lxqt-runner/issues/144 and its solution (not LXQt's fault).
