### ISSUE TITLE
Screengrab: Problem w/ Hidpi Scaling

### ISSUE THREAD

**Issue by nickgeoca** [lxqt/lxqt#1814]
When I do a print screen w/ rectangular region, it does not copy the appropriate region.

Hi, I changed this env variables for HiDPI mode.
GDK_DPI_SCALE
QT_SCALE_FACTOR

##### Expected Behavior

...

##### Current Behavior

It captures a magnified rectangular region. The bottom right of the screen can't be captured either.
![image](https://user-images.githubusercontent.com/2054736/84961318-cee7f300-b0b8-11ea-8427-b709c7250967.png)

##### Possible Solution

Not sure.

##### Steps to Reproduce (for bugs)

1. QT_SCALE_FACTOR=2
2. GDK_DPI_SCALE=1.5
3. Use the printscreen setting "Type: Screen Area"

##### Context

Trying to use screen capture with HiDPI settings.

##### System Information

* Distribution & Version: 20.04
* Kernel: 
* Qt Version: 
* liblxqt Version: 
* Package version:

**Comment by tsujan** [comment]
PrintScreen just call s an app. Which app in your LXQt session?

**Comment by tsujan** [comment]
OK, no need to a reply.

The screenshot utility that LXQt supports is only screengrab and I always suspected that its area capturing should have problems with scale factors (because of its code) but, not having a big screen, I hadn't tested.

Although the report was bad ("Distribution & Version: 20.04" -- what does that mean?!), it's valid.

**Comment by stefonarch** [comment]
> Although the report was bad ("Distribution & Version: 20.04" -- what does that mean?!), it's valid.

Lubuntu, but I think he refers to the screen capture tool in lximage-qt, it looks as screengrab isn't shipped by default.

@nickgeoca Could you specify and eventually test also with screebgrab?

**Comment by tsujan** [comment]
@stefonarch 
It isn't important whether lximage-qt's screenshot code has this problem; it's based on X11 and won't be touched -- if not removed sooner or later.

I was aware of screengrab's problem with scaling and used this report only as a reminder. Will fix it soon.
