### ISSUE TITLE
No icons shown after upgrade

### ISSUE THREAD

**Issue by raven-kg** [lxqt/lxqt#1815]
After upgrade my Lxqt instance from 0.14.1 to 0.15.0 it shows dialogs content without icons. Changing appearance settings doesn't help.

##### Current Behavior

http://img.sysadmins.ws/upload_image/e83de8231a5e3e420d272b0e74b03bb9.jpg
I tried to remove old ~/.config/lxqt and ~/.config/pcmanfm-qt directories, but it didn't help. Maybe I miss something?

##### Steps to Reproduce (for bugs)

1. Upgrade lxqt
2. Relogin
3. 
4. 

##### System Information

* Distribution & Version: CentOS 8.2
* Kernel: 4.18.0
* Qt Version: 5.12.5
* liblxqt Version: 0.15.1
* Package version: 
pcmanfm-qt-0.15.1-1.el8.x86_64
lxqt-archiver-0.2.0-1.2.x86_64
lxqt-globalkeys-0.15.0-1.el8.x86_64
libfm-1.3.1-1.el8.3.x86_64
lxqt-admin-0.15.0-1.el8.x86_64
libqtxdg-3.5.0-1.el8.x86_64
lxqt-themes-system-0.15.0-1.el8.noarch
lxqt-themes-0.15.0-1.el8.noarch
liblxqt-0.15.1-1.el8.x86_64
lxqt-session-0.15.0-1.el8.x86_64
lxqt-panel-0.15.1-1.el8.x86_64
lxqt-config-0.15.0-1.el8.x86_64
libfm-qt-0.15.1-1.el8.x86_64

**Comment by tsujan** [comment]
Obviously, there has been something wrong with your upgrade. I guess you haven't upgraded `lxqt-qtplugin`, which is among the most important packages.

I close this because it's a downstream question/issue but feel free to add comments.

**Comment by raven-kg** [comment]
Thank you @tsujan , it seems I really miss to install lxqt-qtplugin :smile:
