### ISSUE TITLE
can't add apps to quicklaunch widget

### ISSUE THREAD

**Issue by dumischbaenger** [lxqt/lxqt#1816]
In former releases I was able to drag and drop apps from the main menu to a quicklaunch widget. 

##### Expected Behavior

I should be able to grab an app icon from the main menu and drop it on the quicklaunch widget. This doesn't work anymore. 

##### Current Behavior

I can't grab an app from the main menu.

##### Steps to Reproduce (for bugs)

1.  open main menu
2. try to drag a menu entry
3. 
4. 

##### System Information

* Distribution & Version:  Tumbleweed
* Kernel: 5.6.14
* Qt Version: 5.15.0
* liblxqt Version: 0.15.1
* Package version: ?

**from the about dialogue:**

LXQt Desktop Toolbox - Technical Info
  LXQt About Version:     0.15.0
  LXQt Version:           0.15.1
  Qt:                     5.15.0
  Build type:             Release
  System Configuration:   /etc/xdg
  Share Directory:        /usr/share/lxqt
  Translations:           /usr/share/lxqt/translations

User Directories
  Xdg Data Home:          /home/bdonauba/.local/share
  Xdg Config Home:        /home/bdonauba/.config
  Xdg Data Dirs:          /usr/share
  Xdg Cache Home:         /home/bdonauba/.cache
  Xdg Runtime Home:       /run/user/554
  Xdg Autostart Dirs:     /etc/xdg/autostart<br>
/etc/autostart<br>
/usr/share/autostart
  Xdg Autostart Home:     /home/bdonauba/.config/autostart

**Comment by tsujan** [comment]
Not reproducible.

If there's a hidden factor, please find and add it for this to be reopened.
