### ISSUE TITLE
Screen tearing with nvidia

### ISSUE THREAD

**Issue by rtentser** [lxqt/lxqt#1818]
Arch Linux.

When i use stable drivers (440.82/100), i get some tearing, mostly in videos in windowed mode (in firefox & vlc) and games. `forceCompositionPipeline` fixes it for a price of some stuttering.

When i use vulkan-beta drivers (440.66.15/17), i get many tearing. `forceCompositionPipeline` (and `forceFullCompositionPipeline`) is broken. `layers.acceleration.force-enabled` is broken too (i use to fix most video tearing in firefox).

When i use beta drivers (450.51) i get contradictory results. When i checked it yesterday (i've built it from AUR) it've behaved as vulkan-beta. But today, after fresh install, it behaves as stable (i used precompiled package from chaotic-aur and installed xfce4 for testing purposes, so there can be some changes i don't know about).

I've tested all drivers with xfce4 and couldn't reproduce any tearing in videos at all even without `forceCompositionPipeline` enabled (didn't test games yet). So, it's not a drivers' problem.

**Comment by tsujan** [comment]
Your problems has nothing to do with LXQt. They're about the compositor you use.

> I've tested all drivers with xfce4 and couldn't reproduce any tearing in videos

Then, you could use xfce4's compositor/WM in LXQt.
