### ISSUE TITLE
Link to Fedora packages is incorrect

### ISSUE THREAD

**Issue by proski** [lxqt/lxqt#182]
A link named "Fedora" on lxqt.org actually points to http://download.opensuse.org/repositories/X11:/lxde:/lxqt/

**Comment by lpar** [comment]
They broke it again. http://download.opensuse.org/repositories/X11:/lxde:/lxqt:/fedora/ goes to an empty page.

**Comment by sfalken** [comment]
Oh, were we still maintaining that?   I thought someone else had started
building for Fedora.    I haven't even looked at it in a while, but I'll go
have a look if we're still providing the fedora packages....

On Fri, Jan 23, 2015 at 7:28 AM, mathew <notifications@github.com> wrote:

> They broke it again.
> http://download.opensuse.org/repositories/X11:/lxde:/lxqt:/fedora/ goes
> to an empty page.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lxde/lxqt/issues/182#issuecomment-71209375>.
>



-- 
=====================
And that's why, when J. Edgar Hoover asks if you're a god, you say yes!

**Comment by sfalken** [comment]
Ah, ok, that explains alot.   Give me a little time, and I'll have a new link, and some fresh packages

**Comment by theherk** [comment]
The link on the site is still empty, http://download.opensuse.org/repositories/X11:/lxde:/lxqt:/fedora/.

**Comment by sfalken** [comment]
lxqt is available in the main fedora repositories, let me see if I can come up with some sort of link.

**Comment by lpar** [comment]
Instructions on what to install with yum would probably be sufficient, as there isn't an obvious metapackage:

```
liblxqt.x86_64 : Core shared library for LXQt desktop suite
lxqt-about.x86_64 : About application for LXQt desktop suite
lxqt-config.x86_64 : Config tools for LXQt desktop suite
lxqt-policykit.x86_64 : PolicyKit agent for LXQt desktop suite
liblxqt.i686 : Core shared library for LXQt desktop suite
liblxqt-devel.i686 : Devel files for liblxqt
liblxqt-devel.x86_64 : Devel files for liblxqt
liblxqt-mount.i686 : Mount utility library for LXQt Desktop Suite
liblxqt-mount.x86_64 : Mount utility library for LXQt Desktop Suite
liblxqt-mount-devel.i686 : Devel files for liblxqt-mount
liblxqt-mount-devel.x86_64 : Devel files for liblxqt-mount
lxqt-common.noarch : Common resources for LXQt desktop suite
lxqt-globalkeys.i686 : Global keys utility for LXQt desktop suite
lxqt-globalkeys.x86_64 : Global keys utility for LXQt desktop suite
lxqt-globalkeys-devel.i686 : Developer files for lxqt-globalkeys
lxqt-globalkeys-devel.x86_64 : Developer files for lxqt-globalkeys
lxqt-notificationd.x86_64 : Notification daemon for LXQt desktop suite
lxqt-openssh-askpass.x86_64 : Askpass openssh transition dialog for LXQt desktop suite
lxqt-panel.x86_64 : Main panel bar for LXQt desktop suite
lxqt-panel-devel.i686 : Developer files for lxqt-panel
lxqt-panel-devel.x86_64 : Developer files for lxqt-panel
lxqt-powermanagement.x86_64 : Powermanagement daemon for LXQt desktop suite
lxqt-qtplugin.i686 : Qt plugin framework for LXQt Desktop Suite
lxqt-qtplugin.x86_64 : Qt plugin framework for LXQt Desktop Suite
lxqt-runner.x86_64 : Application runner agent for LXQt desktop suite
lxqt-session.x86_64 : Main session for LXQt desktop suite
lxqt-theme-fedora.noarch : Default Fedora theme for LXQt
pcmanfm-qt.x86_64 : LxQt file manager PCManFM
```

**Comment by heliocastro** [comment]
Just onstall the group:

Fedora 21: yum install @lxqt
Fedora 22 e rawhide: dnf install @lxqt

[]'s
