### ISSUE TITLE
Suggestion: lauch with dedicated GPU contextual menu

### ISSUE THREAD

**Issue by victor-bayas** [lxqt/lxqt#1820]
It would be very convenient for hybrid graphics laptop users (the so called gaming laptops) to have a conextual menu option to launch an app with the dedicated GPU, GNOME already has this and KDE has a discrete GPU tick in app properties. 

![optimus](https://user-images.githubusercontent.com/49411169/86304939-02a53b80-bbd6-11ea-90cf-2eda248102d4.png)
GNOME implementation

This feature is achieved by doing
`__NV_PRIME_RENDER_OFFLOAD=1 __GLX_VENDOR_LIBRARY_NAME=nvidia %command%`
for Nvidia GPUs (propietary driver required)

and
`DRI_PRIME=1 %command%`
for AMD GPUs

Thanks in advance

**Comment by tsujan** [comment]
The commands -- whatever they are -- should be in apps' desktop entries. You could easily create duplicate desktop entries with those commands, modify their names ("... with nvidia") and put them inside `~/.local/share/applications`; then, they'll appear in the main menu.

I'm totally against adding such special use cases to pcmanfm-qt's code. They require adding codes for distinguishing graphic drivers and inserting hard-coded commands that might not work a few months later: unimaginably ugly and impractical.
