### ISSUE TITLE
the lack of leaving Lubuntu in Suspend in fast-mode with keyboard-navigation

### ISSUE THREAD

**Issue by ralf3u** [lxqt/lxqt#1824]
I go many times a day in suspend mode; I customized the shortcuts:
Meta+x will let appear the logout session window with the different leaving options

problem
I have to press EVERY TIME 3x the arrow-right-key to be on the Suspend-icon

possible solution
1)
it would be great if I could decide the order of the icons, for example in the Session Settings (for example with the possible name "logout order icon")
maybe it would be good, if the order would be changed also in all areas:
- start-menu>Leave
- Meta-r: pulldown-menu (by the way: the icon hibernate does not appear there)
2)
it would be great if the first icon is already activated in the logout session window
- like in pcmanfm-qt when I open a file : the first file is already activated
- like in LXDE in the logout session window: the first entry is already activated

Now imagine:
1) if I would change the order of the icons, that suspend-icon is the first icon, and
2) if the first entry is automatically activated, then ...
EVERY TIME I just press Meta+x, and then just enter, and boom … Lubuntu is in suspend in fast-mode
- how cool it would be!

##### System Information
* Distribution & Version: Lubuntu 20.04
* Qt Version: 0.14.1

**Comment by stefonarch** [comment]
Imagine you'd make directly a shortcut for
 ` lxqt-leave --suspend`
 ;)

Personally I have dragged and dropped the suspend item from the menu to the quicklaunch widget on the panel.

**Comment by ralf3u** [comment]
answer to stefonarch:
- indeed, that's a perfect keyboard solution for suspend, and
- indeed, that's a perfect mouse solution!

but what about this:
maybe I would like to poweroff the computer, by visiting first the logout session window (so no shortcut, to be sure that I will no press the shortcut by accident); then I would put the poweroff-icon as first entry of the logout session window

so, the option of the customization of the order of the icons of the logout session window is still an interesting idea, that I would use

so, the title of this issue should be not any more:
"the lack of leaving Lubuntu in Suspend in fast-mode with keyboard-navigation"
but more something like this:
"customization of the order of the icons of the logout session window"

**Comment by ralf3u** [comment]
my intention is to open tomorrow a new issue with a new title and new content;
I will mention the issue-number here before I close this issue

**Comment by stefonarch** [comment]
> then I would put the poweroff-icon as first entry of the logout session window

Personally I never use the leave menu, but users have different tastes.

And for poweroff or else there is (in git version, not sure what distro ship it already) already this setting:
![schermata-13-22-12-54](https://user-images.githubusercontent.com/10681413/87349223-3ed18800-c556-11ea-832c-4317c290b17a.png)

**Comment by tsujan** [comment]
![power_keys](https://user-images.githubusercontent.com/981076/87350492-320c5e80-c56d-11ea-872e-f81a019b6716.png)

**Comment by ralf3u** [comment]
I close this issue now, because I opened a new issue with the number 1826.
