### ISSUE TITLE
Desktop frozen with wrong resolution after login

### ISSUE THREAD

**Issue by redtide** [lxqt/lxqt#1825]
It happens randomly, with an average frequency of 1/10, that after giving the password to SDDM, I get some screen portion of the desktop image background on a low resolution.
It seems like also stuck/frozen: I can't see the lxpanel nor mouse pointer.
As workaround I kill the session manager and restart.
This can happen, very rarely (3 times until now), also more than once on the same boot.

##### Expected Behavior
Have access to the desktop.

##### Current Behavior
See above, unfortunately I have no idea how to make a screenshot in that case.

##### Possible Solution
No idea, the only thing that comes to my mind is some race condition.

##### Steps to Reproduce (for bugs)
This is hard if not happens regularly: just boot the machine, then access with the session manager.

##### Context
N.A.

##### System Information
* Distribution & Version: Archlinux
* Kernel: 5.7.7-arch1-1
* Qt Version: qt5-base 5.15.0-4
* liblxqt Version: liblxqt 0.15.1-1
* Package version: sddm 0.18.1-2 xorg-server 1.20.8-2

**Comment by tsujan** [comment]
How can it be related to LXQt? It seems to be a graphic problem and can have 1001 causes. With the info you provided, nothing can be said.

**Comment by redtide** [comment]
IDK, maybe at least to see if there are other people with the same issue and find more details? I'm not pointing my finger on LXQt, OTOH from an user perspective it's something that has to do with the session, I surely don't know if management or environment.

**Comment by tsujan** [comment]
This is LXQt bug tracker. We use it for fixing bugs and implementing features. Your question can be asked in a distro forum, where some users may enjoy detective works and have time for long Q&As.
