### ISSUE TITLE
customization of the order of the icons of the logout session window

### ISSUE THREAD

**Issue by ralf3u** [lxqt/lxqt#1826]
problem
in the logout session window: I have to press the arrow-right-key 2x EVERY TIME I shutdown the computer
(by pressing the arrow-right-key 2x the poweroff-icon is activated)

possible solution
First:
it would be great if I could decide the order of the icons of the logout session window, for example in the Session Settings (for example with the possible name "logout order icon")
maybe it would be good, if the order would be changed also in all areas:
- logout session window
- start-menu>Leave
- Meta-r: pulldown-menu (by the way: the icon hibernate does not appear there)
at the moment in this three areas the order of the icons are all different

Second:
it would be great if the first icon is already activated in the logout session window
- like in pcmanfm-qt when I open a file : the first file is already activated
- like in LXDE in the logout session window: the first entry is already activated
if you prefer that no icon is activated as default in lxqt, it would be great to put at least a checkbox
in the Session Settings (for example with the possible name "logout order icon"), for example like this: activate the first entry

by the way:
- I know that I could use in the Terminal: poweroff
- I know that I could use the poweroff-symbol in the panel
- I know that I could use the poweroff-key of the computer
- I know that I could use a shortcut (what I don’t realize, to be sure that I will not press the shortcut by accident)
but I prefer my habits: Meta+x (my personal shortcut for the logout session window) and enter to poweroff (what I used many years in LXDE)

##### System Information
* Distribution & Version: Lubuntu 20.04
* Qt Version: 0.14.1

**Comment by palinek** [comment]
> I know that I could use a shortcut (what I don’t realize, to be sure that I will not press the shortcut by accident)

How about using it together with `xmessage` or `zenity`?

**Comment by tsujan** [comment]
I don't know why some people think that a program should be tailored exactly to their personal preferences, ignoring all other things that may be pertinent.

In `lxqt-leave`, the start focus is on the cancel button, which is a wise choice. Any other focus would mean giving priority to one action over the others. The user can reach any item by pressing two arrow keys, at most.

If the user feels that his time is wasted by `lxqt-leave`, he could use several other methods. But if he thinks that his habits should be fulfilled by this or that program, I'm afraid that's not a valid request.
