### ISSUE TITLE
World Clock Spaces

### ISSUE THREAD

**Issue by Bydo-Spore** [lxqt/lxqt#1828]
In World Clock Manual Format Configuration, it's impossible to have two or more consecutive spaces; or if it is possible, I can't find how to do it.

For example, `'ddd d MMM<space><space>h:mma'` is the same as `'ddd d<space>MMM h:mma'`.

Having more than one space can be useful to separate the time and the date.

**Comment by Bydo-Spore** [comment]
I meant `'ddd d MMM<space><space>h:mma'` is the same as `'ddd d MMM<space>h:mma'`.

**Comment by stefonarch** [comment]
&nbsp;&nbsp; should work
non-breaking space html

**Comment by tsujan** [comment]
This is rather a question about HTML and you could have found the answer on the Internet.

If your text isn't in HTML, multiple spaces will be seen as multiple sapces.

If your text is HTML-formatted, you need `'&nbsp;'` or `'&nbsp;&nbsp;'` or `'&nbsp;&nbsp;&nbsp;'`,..., as @stefonarch mentioned.
