### ISSUE TITLE
XDG_CURRENT_DESKTOP set late during login

### ISSUE THREAD

**Issue by gunnarhj** [lxqt/lxqt#1830]
Hi!

Version info:

    $ lxqt-about -v
    lxqt-about 0.14.1
    liblxqt   0.14.1
    Qt        5.12.5

Assume a file `/etc/profile.d/var-test.sh` with this contents:

    printenv | grep -E 'DESKTOP|XDG' > "$HOME/var-test.txt"

Then log in to an LXQt session (Debian) and find:

    $ cat $HOME/var-test.txt
    XDG_SEAT=seat0
    XDG_SESSION_TYPE=x11
    DESKTOP_SESSION=lxqt
    XDG_SESSION_CLASS=user
    XDG_SESSION_ID=2
    XDG_RUNTIME_DIR=/run/user/1000
    XDG_SESSION_DESKTOP=lxqt
    XDG_VTNR=2

i.e. `XDG_CURRENT_DESKTOP` was unset when the `/etc/profile.d` files were sourced. However:

    $ echo $XDG_CURRENT_DESKTOP
    LXQt

I'm involved in the maintenance of `im-config` which is a Debian package where we to some extent distinguish between desktops using `XDG_CURRENT_DESKTOP`. We found that it didn't work as expected for LXQt, and the above proved to be the explanation.

It would be good if `XDG_CURRENT_DESKTOP` could be set earlier in the login process. Other desktops do that.

Thanks!

**Comment by luis-pereira** [comment]
@gunnarhj 0.14.1 is old. 0.16 is out.

**Comment by gunnarhj** [comment]
@luis-pereira: Do you know that it's set earlier in 0.16 or do you hope? ;)

Since I'm not working with LXQt maintenance in Debian, I can't check it out easily. OTOH it's no urgency from my POV since we have worked around the issue for 0.14.1.

**Comment by luis-pereira** [comment]
Probably not.
`XDG_CURRENT_DESKTOP ` is set in `startlxqt`. Where, the other desktops you mentioned, do it ?.`

**Comment by gunnarhj** [comment]
> Where, the other desktops you mentioned, do it ?

TBH I don't know. All I can tell is that they set `XDG_CURRENT_DESKTOP` early enough to allow to check for it in e.g. `/etc/profile.d` scripts.

**Comment by ito32bit** [comment]
https://bugs.freedesktop.org/attachment.cgi?id=113899
> $XDG_CURRENT_DESKTOP should have been set by the login manager, according to the value of the DesktopNames found in the session file.

/usr/share/xsessions/lxqt.desktop:
```
[Desktop Entry]
Type=Application
Exec=startlxqt
TryExec=lxqt-session
DesktopNames=LXQt    # Added
Name=LXQt Desktop
Comment=Lightweight Qt Desktop
...
```
Debian and SDDM:
```sh
$ cat var-test.txt 
XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session3
DESKTOP_SESSION=lxqt
XDG_SEAT=seat0
XDG_SESSION_DESKTOP=LXQt
XDG_SESSION_TYPE=x11
XDG_CURRENT_DESKTOP=LXQt
XDG_SEAT_PATH=/org/freedesktop/DisplayManager/Seat0
XDG_SESSION_CLASS=user
XDG_VTNR=7
XDG_SESSION_ID=13
XDG_RUNTIME_DIR=/run/user/1000
```
I will make a PR.

**Comment by luis-pereira** [comment]
@gunnarhj Thanks for the good report.
