### ISSUE TITLE
lxqt-config-brightness/xrandrbrightness.cpp:  Possible null pointer dereference: crtc_info.

### ISSUE THREAD

**Issue by luis-pereira** [lxqt/lxqt#1831]
``` cpp
if(crtc_info == NULL && crtc_info->mode == XCB_NONE )
```
has something wrong: eitther crtc_info == NULL is redundant  or there is a possible null pointer dereference: `crtc_info`
Source: https://github.com/lxqt/lxqt-config/blob/master/lxqt-config-brightness/xrandrbrightness.cpp#L377
Spotted by ccpcheck.

##### Possible Solution
``` cpp
if(crtc_info != NULL && crtc_info->mode == XCB_NONE )
```
makes more sense. Possible coding typo ?

##### System Information

* Distribution & Version: not relevant
* Kernel: not relevant
* Qt Version: not relevant
* liblxqt Version: not relevant
* Package version: git

**Comment by luis-pereira** [comment]
@selairi Can you pls take a look ? You know the code better than anyone.

**Comment by tsujan** [comment]
@luis-pereira 
Most probably, the correct condition is:
```c++
if(crtc_info == NULL || crtc_info->mode == XCB_NONE )
```
BTW, I don't think @selairi receives email notifications. We shouldn't forget this with the next release; hence, the "release-blocker" label.

**Comment by tsujan** [comment]
@luis-pereira, would you please make a PR for it? That line is dangerous.

**Comment by luis-pereira** [comment]
Sure.
