### ISSUE TITLE
[Feature Request][lxqt-config-appearance] Colour Theming

### ISSUE THREAD

**Issue by tenplus1** [lxqt/lxqt#1832]
LxQt Appearance needs a new icon which adds the ability to select a Qt5 colour palette without having to resort to setting up Qt5 Settings and editing config files.

**Comment by tsujan** [comment]
Qt5 has no setting for color palette. If you mean `qt5ct`, it's a plugin that doesn't belong to Qt and isn't compatible with LXQt/KDE (you could use it in LXQt at the cost of LXQt's plugin and its features).

The git LXQt already has a button for setting the window color (→ https://github.com/lxqt/lxqt-config/pull/629).
