### ISSUE TITLE
Need more controls of lxqt widgets

### ISSUE THREAD

**Issue by cheuksing** [lxqt/lxqt#1833]
##### Expected Behavior
Since LXQT allows users to change its window manager, it makes sense to provide ways to have better integration with other WM. There are 2 possible use cases I can imagine:
1. WM handles all keybindings but wants to open the application menu widget through configured WM's shortcuts.
2. user is using other menu bars, e.g. polybar / i3bar / etc. but still want to use LXQT widget (KDE widget)

In my opinion, I think 2. is an important reason why people want to use their WM with a DE.

##### Current Behavior
There's no way to open/control widget through shortcuts or command line.

##### Possible Solution
Provide a CLI option to control widgets. e.g. A `plasmawindowd` equivalent of LXQT.
Or provide dbus info for LXQT default widgets.

* Distribution & Version: Lubuntu 20.04 LTS
* liblxqt Version: LXQT version: 0.14.1

**Comment by tsujan** [comment]
> Need more controls of lxqt widgets.... There's no way to open/control widget... Provide a CLI option to control widgets...

What do you mean by "widget"? Which widget?

> Since LXQT allows users to change its window manager, it makes sense to provide ways to have better integration with other WM.

As is mentioned so many times, LXQt is agnostic toward WM. If a WM is supposed to work under all DEs, it should provides ways to do so.

**Comment by cheuksing** [comment]
@tsujan 

> What do you mean by "widget"? Which widget?

It means those applets show within the LXQT panel. e.g,
![Image of calendar widget](https://manual.lubuntu.me/stable/_images/calendar-widget.png)

For all LXQT default widgets, see
https://manual.lubuntu.me/stable/5/5.1/lxqt-panel.html

> As is mentioned so many times, LXQt is agnostic toward WM. If a WM is supposed to work under all DEs, it should provide ways to do so.

WM is working under LXQT. However, there's no way to communicate between LXQT widgets and other applications.
Let's say I want to open the calendar widget above, from a 3rd party panel, or WM default panel (WM also ships with its own panel bar), there's no way to do it.

Here's are some examples of 3rd party panel,
https://github.com/polybar/polybar
https://gitlab.com/o9000/tint2

**Comment by tsujan** [comment]
> It means those applets show within the LXQT panel

Those are LXQt *Panel* widgets. They belong to lxqt-panel and aren't related to WM. You can change their appearance, make themes for them and change their settings.

Some LXQt Panel widgets register shortcuts that can be seen in `Global Actions Manager`. You can interact with them from anywhere. Some others don't.

> Let's say I want to open the calendar widget above, from a 3rd party panel, or WM default panel

Why should LXQt Panel's widgets be controlled by a 3rd party panel?! What's the relation to WM?

If you mean command-line options for interacting with Panel widgets, a similar request was made and rejected a long time ago at https://github.com/lxqt/lxqt/issues/672 (particularly, read https://github.com/lxqt/lxqt/issues/672#issuecomment-108617097).
