### ISSUE TITLE
2nd Panel on 2nd screen in persistent dual-monitor setup only displays on workspace 1 after monitors wake-up

### ISSUE THREAD

**Issue by ArenT1981** [lxqt/lxqt#1834]
I have a curious issue on my dual LG 4K monitor setup on my desktop PC using lxqt and my Radeon 5700XT GPU (both monitors connected via DisplayPort), under Fedora 32. I should also note that I had the exact same issue when running (presumably an older version of) lxqt on my system when I instead had Ubuntu 18.04LTS installed.

I have lxqt setup so that I have one panel on each monitor (at the top of each screen). I have used lxqt's monitor setting dialog to "save" my monitor setup and "keep monitors attached".

However, whenever I wake up my monitors after they go into power-saving mode/switch off, lxqt "loses" the panel on my second (right-hand) screen, **only displaying it on virtual desktop 1**. It disappears off my other virtual desktops (I currently have 5 virtual desktops configured). Note that the panel on my left-hand ("first") screen displays just fine across all virtual desktops as normal. This is a pity because otherwise it does a good job of correctly restoring the screens etc. in the correct place after wake-up. 

I am using the default openbox as my window manager with lxqt.

The only way to restore the right-panel to displaying across all virtual desktops on the right-hand monitor is to completely kill and restart `lxqt-panel`. Even manually re-jigging the display settings again doesn't cause it to be present across all virtual desktops as expected.

##### Expected Behavior

After monitors wake-up, the second panel on the second monitor displays persistently, as expected, on **all** virtual desktops/workspaces, not just desktop/workspace number 1.

##### Current Behavior

After monitors wake-up, the second panel on my second screen **only** displays on virtual desktop/workspace number 1. It does not appear/is invisible on all workspaces > 1 (i.e. if you have 5 workspaces, then it does not appear on workspaces 2-5). The number of workspaces does not matter; it only appears on number 1.

##### Possible Solution

My current workaround is to use a rather hackish script to kill and restart `lxqt-panel` (and its attached drop-down qterminal) and manually reset monitor configuration using `xrandr`:

```bash
killall lxqt-panel &
DROPDOWN_PID=`pgrep -a qterminal | grep drop | cut -f 1 -d ' '`
kill -TERM $DROPDOWN_PID &
sleep 1.5
lxqt-panel &
sleep 1.5
xrandr --output DP-2 --pos 0x0 --output DP-3 --pos 3860x0
qterminal --drop &
```
Using the above script to restart `lxqt-panel` in the current running lxqt session fixes the issue and at least means I do not have to logout/quit my current lxqt session and log back in again.

##### Steps to Reproduce (for bugs)

1. Have a dual 4K monitor setup, with a separate panel assigned to each. 
2. Allow the monitors to switch-off/go into power-saving mode.
3. Wake-up the displays.
4. See that panel number #2 on screen #2 only displays on the very first workspace/desktop, rather than across all virtual desktops.

##### Context

Losing the second panel on my second monitor across virtual desktops (other than the first) is an irritation/usability issue. Other than manually restarting lxqt-panel, the only way to get it back/displaying correctly is to entirely log out then log back into lxqt.

Keeping the monitors powered up is a waste of energy when I am taking a break from work during the day. I obviously not want to shut down the computer as I usually have an open session with lots of things running and want to be able to immediately resume work later.

##### System Information

* Distribution & Version: 0.14.1
* Kernel: 5.7.12-200.fc32.x86_64 (Fedora 32)
* Qt Version: 5.14.2
* liblxqt Version: 0.14.1 (release 6.fc32)
* Package version: lxqt-panel 0.14.1 (release 4.fc32)

Apart from this one issue, LXQt + Openbox + associated project tools is a brilliant DE in terms of functionality/cleanliness/efficiency/usability, so thanks for all your hard work.

**Comment by ArenT1981** [comment]
Whoops, I should have looked a bit closer at the changelog. I see LXQt is up to 0.15 but my Fedora version is 0.14.1, and that the following change is listed:

"Panel positioning is corrected with multiple screens."

Is it likely that this fix will apply specifically to this issue I'm having with a second panel disappearing across virtual desktops > 1? It is not so much a "positioning" issue (since it appears in the right place, simply that it doesn't appear on any of the other virtual desktops...). Hopefully the Fedora package maintainer will package 0.15 soon so I can see/test whether it fixes the issue...

**Comment by tsujan** [comment]
The LXQt version you have (0.14.1) is from 18 months ago. Many things have changed since then.

Here, I can't see a problem in the panel with 2 monitors, with or without a scale factor > 1 (instead of 4k monitors, which I don't have). There is a Qt issue that causes problems in drawing of desktop with dual monitor + scale factor > 1 (https://github.com/lxqt/pcmanfm-qt/issues/1145) but it doesn't affect the panel.

When you get the latest release, please add a comment if you encounter the same problem.
