### ISSUE TITLE
Can't escape from screensaver after wake up from suspend

### ISSUE THREAD

**Issue by Zoldszemesostoros** [lxqt/lxqt#1835]
##### Expected Behavior

After opening the laptop lid, the machine should wake up and work correctly.
##### Current Behavior

There is a screensaver image (blue and gray) and the mouse on the screen. Despite I'm moving the mouse, the screensaver don't disappears. Once I've seen a vibrating "Cannot get pointer" (It disappeared after a second, so I couldn't read it fully.) message in yellow at the top left corner.
##### Steps to Reproduce (for bugs)

Install lxqt, wait 15-20 minutes, suspend the computer, wait, then wake up the computer.
Unfortunately this bug doesn't appear every time, only 1-2 times of 10.

##### Context

This bug appears usually when I leave the computer sleeping for more than an hour.
##### System Information

* Distribution & Version: Lubuntu 20.04
* Kernel: 5.4.0-42-generic
* Qt Version: 
* liblxqt Version: 0.14.1-0ubuntu2
* Package version: 30

If it helps, I can attach journalctl logs.

**Comment by tsujan** [comment]
Sorry, 0.14.1 is too old.

In addition, the problem doesn't seem to be related to LXQt — "Cannot get pointer" isn't an LXQt message.

**Comment by Zoldszemesostoros** [comment]
OK, I'll test on a newer version, and go back if the issue still present.
> In addition, the problem doesn't seem to be related to LXQt — "Cannot get pointer" isn't an LXQt message.

This isn't the full error message, only some random words of it.

**Comment by tsujan** [comment]
> This isn't the full error message, only some random words of it.

What you described was about the screensaver; LXQt doesn't control how a screensaver works or how it disappears when the mouse cursor moves. Your problem may have various causes (compositor, graphic drivers, X11,...). I recommend you use Ubuntu forums.
