### ISSUE TITLE
Missing new power keys settings in *.ts files

### ISSUE THREAD

**Issue by stefonarch** [lxqt/lxqt#1836]
As title, for example italian translation is seen as 100% both in qt-linguist and weblate but see screen:

![schermata-19-07-57-14](https://user-images.githubusercontent.com/10681413/90597784-04f93e80-e1f2-11ea-90b1-e333672cbf67.png)

**Comment by tsujan** [comment]
New strings were added to the code but translation files aren't up-to-date. Will update them soon.

If you also encounter other cases of this, please report them. Thanks!
