### ISSUE TITLE
Bug on window while dragging one above another, when the below is freeze

### ISSUE THREAD

**Issue by terremoth** [lxqt/lxqt#1838]
Hello, there is something very annoying a while. The bug tells by it's own:

![screen](https://user-images.githubusercontent.com/11032344/91004868-bd850080-e5ab-11ea-984f-08a6a6d85b90.jpg)
![screen2](https://user-images.githubusercontent.com/11032344/91004872-beb62d80-e5ab-11ea-813e-0a42e6fd2739.jpg)

This remembers me Windows XP

##### Expected Behavior
Not "freezing" the windows over another window while dragging it. Just stay with its normal contents inside instead of get the other windows screen above. 
 
##### Current Behavior
It goes freezing the above window content inside the below screen 

##### Steps to Reproduce (for bugs)
Happens everytime when I log in into my Lubuntu 20.04, and asks that update/upgrade screen, when I accept it gets this freezing while dragging the other update screen 

1. log into Lubuntu 20.04 
2. wait for any notification to update appear
3. accept 
4. drag the update list window over the other window

##### Context
This makes the window manager look like something Windows XP bug

##### System Information
![image](https://user-images.githubusercontent.com/11032344/91005449-4fd9d400-e5ad-11ea-93ae-f5c3b86ef1fe.png)

![image](https://user-images.githubusercontent.com/11032344/91005700-e73f2700-e5ad-11ea-9ec7-b08d3e70e78a.png)

**Comment by tsujan** [comment]
There is no relation to LXQt. Please report Ubuntu problems to Ubuntu.
