### ISSUE TITLE
Empty translation *.ts files panel/plugin-statusnotifier

### ISSUE THREAD

**Issue by stefonarch** [lxqt/lxqt#1839]
Looks like not updated yet.
![schermata-27-18-02-37](https://user-images.githubusercontent.com/10681413/91466519-88203180-e88f-11ea-8eca-30ce09345637.png)

**Comment by tsujan** [comment]
Will update lxqt-panel's translation files soon. Thanks!

**Comment by tsujan** [comment]
Done. The ts files are up-to-date now.
