### ISSUE TITLE
enable/disable selection markers

### ISSUE THREAD

**Issue by alimoche** [lxqt/lxqt#1842]
A new configuration option to enable/disable selection markers would be very nice and make lxqt appearance more configurable. Selection markers might be very good for touch screens, tablets, etc. but for a desktop computer with a mouse  plus/minus signs might be confusing. Other desktop environments, e.g. KDE, have this option, you can turn on/off the selection markers.

##### Possible Solution

A check box like "Enable selection markers" in libfm-qt?

**Comment by tsujan** [comment]
Please read closed reports before opening reports.

What you call "selection marker" is in libfm-qt and, since its removal has no use whatsoever, no option is added for it. Options aren't added just because some users like/dislike something but for the sake of functionality.

**Comment by alimoche** [comment]
ok thank you, but I was not asking to remove it, but to make it optional instead of compulsory and thus make it easier to use

**Comment by tsujan** [comment]
A wise man once said:

Adding an option for the sake of having yet another option is not an option. Each option has a cost, which may be justified only by a functionality.

**Comment by alimoche** [comment]
I think this is the original feature request: https://github.com/lxqt/pcmanfm-qt/issues/132 adding an option there would make possible to have both i.e. previous behavior would not be lost and the user would be able to choose what to use, the following screenshot is an example from Dolphin file manager highlighted with a red box:

![selection-markers](https://user-images.githubusercontent.com/62967485/92399159-1c10b980-f12a-11ea-9daa-1d9e5aaa8ef0.png)

**Comment by stefonarch** [comment]
I don't know the cost of implementing this, but if there were a checkbox "Don't show selection markers" I would check it immediately, I always wondered about those huge  + and - signs and never got familiar to use them.

**Comment by tsujan** [comment]
@stefonarch

I don't want to start yet another discussion about this but since *you* added the last comment and I know you from your many good reports and contributions, I add a short explanation:

Options that only follow personal habits don't have a logic. The worst thing about them is that their proponents may know no limit. Here is an extreme example: https://github.com/lxqt/lxqt-qtplugin/issues/60. And there's always another person who has another personal habit.

**Comment by alimoche** [comment]
IMHO this has nothing to do with "personal habits", "no limit" or "extreme example", but it is more related to theming, configuring the look and feel of the desktop, usability, simplicity, flexibility, etc. and does not lose any functionality already implemented. The reason to add additional comments was because it seems it was not well explained, thank you anyway
