### ISSUE TITLE
Clean up double language files (*ru.ts *sk.ts)

### ISSUE THREAD

**Issue by stefonarch** [lxqt/lxqt#1843]
Weblate is indicating some double presences of *.ts files which should be avoided, for 
* sk_SK, sk
* ru, ru_RU.ts

The *.sk.ts files are 
 /lxqt-config/lxqt-config-appearance/translations/lxqt-config-appearance_sk.ts
 /lxqt-desktop/lxqt-runner/translations/lxqt-runner_sk.ts
 /lxqt-panel/panel/plugin-spacer/translations/spacer_sk.ts
 
The *ru_Ru.ts files are 

 /lxqt-configuration/lxqt-notificationd/src/translations/lxqt-notificationd_ru_RU.ts
 lxqt-panel/panel/plugin-tray/translations/tray_ru_RU.ts

Sometimes both versions are present, diff slightly and generate a warning.

Looking at the menu here
 
![schermata-14-15-40-13](https://user-images.githubusercontent.com/10681413/93095083-f728c300-f6a2-11ea-9896-fc01a2a039ab.png)

the *.sk.ts could be renamed e/o removed if *.sk_SK.ts is present.
For the  *ru.ts files maybe there is some discussion needed, keeping only ru or different versions like ru_RU or whatever exist.

**Comment by stefonarch** [comment]
@shlyakpavel Could you take a look here at the 2 russian files which is the "good one"?
https://github.com/lxqt/lxqt-notificationd/tree/master/src/translations

Is it ok to have only *_ru.ts files for russian languages?

**Comment by tsujan** [comment]
> Is it ok to have only *_ru.ts files for russian languages?

I don't know Russian but Kvantum, FeatherPad and FeatherNotes have `_ru.ts` files; also, we have `pcmanfm-qt_ru.ts` in pcmanfm-qt. So, the answer should be "yes".

**Comment by stefonarch** [comment]
Im think too, as for german and italian:
https://github.com/lxqt/lxqt/wiki/Translation#need-for-country-specific-translations
But those two mentioned here are different, so a look at them by an russian speaker  before deleting one would be good.

**Comment by shlyakpavel** [comment]
> Is it ok to have only *_ru.ts files for russian languages?

Yes
The xqt-notificationd_ru.ts is correct, the ru_RU can be removed

**Comment by stefonarch** [comment]
![schermata-09-10-12](https://user-images.githubusercontent.com/10681413/101750782-c7d1f880-3acf-11eb-9060-73adaef25526.png)
Will remove the 3 sk_SK files, all projects show those 3 errors in main page.
