### ISSUE TITLE
Monitor setting without spanning?

### ISSUE THREAD

**Issue by spease** [lxqt/lxqt#1847]
Is there a way to use Monitor Settings and prevent maximizing a window from spanning it across both external screens?

I tried the mailing list first, but then looked at the archives today and saw it looks pretty dead.

Thanks.

**Comment by tsujan** [comment]
Maximized windows don't span across screens. If they do for you, there may be a problem in the WM you use or you may have an outdated version of LXQt.

**Comment by spease** [comment]
Thanks.

LXQt version is 0.15.0
Window manager is openbox 3.6.1

I went through the openbox configuration tool (I believe obconf-qt) in Preferences, but didn't see anything overtly related to this. Previously I went through my X conf, but the only active conf file is

```Section "Module"
    Load "modesetting"
EndSection

Section "Device"
    Identifier "nvidia"
    Driver "nvidia"
    BusID "PCI:1:0:0"
    Option "AllowEmptyInitialConfiguration"
EndSection```

Unless there's a place to look besides `/etc/X11/xorg.conf.d`

I'm running Arch.

**Comment by tsujan** [comment]
I can't reproduce it with KWin or Openbox: When I maximize a window with either, it'll be maximized inside the screen of the window, even if a part of the window is inside another screen before maximization.

Apparently, there's a hidden factor in your case. Add a comment if you find it. Then, if it's reproducible, I'll reopen the issue.

**Comment by tsujan** [comment]
Oh, I didn't pay attention to nvidia in your last comment. nvidia does "magic" sometimes ;) Here I have Intel + modesetting.

**Comment by spease** [comment]
Yes, that seems reasonable - maybe TwinView or Xinerama (whatever it is) is being silently enabled by the X driver. I'll focus my efforts on there. Thanks.

**Comment by hmollercl** [comment]
> Yes, that seems reasonable - maybe TwinView or Xinerama (whatever it is) is being silently enabled by the X driver. I'll focus my efforts on there. Thanks.

I'm using nouveau in my 2-monitor setup becasue nvidia created a big rectangle and since my monitors are from different height it uses a rectangle from height = max(individual height) and was a mess.

**Comment by tsujan** [comment]
@hmollercl, thanks for the info!

So, nvidia can also hide the mouse cursor when two screens have different heights. I remember that we had an open issue about it; I couldn't reproduce it either.
