### ISSUE TITLE
About Regular Releases

### ISSUE THREAD

**Issue by tsujan** [lxqt/lxqt#1848]
I had an idea about releases:

The previous release was made in April. I suggest to release 0.16 in the first week of November and make releases regularly in April and November.

Previously, Alf implied that we should release LXQt when it's ready but "ready" is a too vague concept. IMHO, regular releases help us get more relevant reports, whether they're about bugs or new features — especially, from users of rolling distros.

Does that seem acceptable to you?

**Comment by palinek** [comment]
I agree with regular releases. For "release when it ready" we need to define a goal of readiness. Now we're lacking someone who would define the goal for next release.

**Comment by tsujan** [comment]
> Now we're lacking someone who would define the goal for next release.

Yes! The lack of enough manpower has always been a problem.

I think regular releases may bring more order to the process of development by hearing from users who have up-to-date installations.

**Comment by hmollercl** [comment]
It also gives more visibility to the project. Every new release is "covered by the press".

**Comment by wxl** [comment]
Ubuntu releases in April and October, so I think this timing would be good. It would mean we'd immediately have something to start working on at the end of our cycle/beginning of the new cycle. And since we are not a rolling release, having regular releases would be super helpful. It will mean less patches we have to wrestle with and it will mean more users using more recent software. Wonderful, great, fantastic idea!

**Comment by luis-pereira** [comment]
> I had an idea about releases:
> 
> The previous release was made in April. I suggest to release 0.16 in the first week of November and make releases regularly in April and November.

We don't have manpower for more releases. Those are good months as @wxl explained in his commend.
 
> Previously, Alf implied that we should release LXQt when it's ready but "ready" is a too vague concept. IMHO, regular releases help us get more relevant reports, whether they're about bugs or new features — especially, from users of rolling distros.
> 
> Does that seem acceptable to you?

More than acceptable.

**Comment by wxl** [comment]
Just one thing to add about person power: if I can be of help somehow with regards to releases, please let me know.

**Comment by tsujan** [comment]
Thank you all for your replies! I'm happy that regular releases are acceptable to you.

@wxl 
Good to know that it suits Ubuntu. As for making releases, it became easy to me after LXQt 0.15 — may take a few days but only twice a year; point releases are a piece of cake too. Although the job is easy, it's boring and small mistakes may happen. I'd appreciate it if my probable mistakes are told to me as soon as possible.

**Comment by wxl** [comment]
> Although the job is easy, it's boring and small mistakes may happen

Maybe this is something we could automate? I'd be willing to help with that if I know the specifics.

**Comment by tsujan** [comment]
> Maybe this is something we could automate?

It's so automated that guarantees lots of yawns ;) The needed folders and scripts are ready to be reused after small changes.

**Comment by jonesmz** [comment]
Could github actions be helpful with any of the required work?

**Comment by tsujan** [comment]
> Could github actions be helpful with any of the required work?

I don't think it can be automated more than what it is. The rest is about updating translations (by using a script), making good ChangeLogs, checking ABI/API, changing min. req. versions, and so on; they need a human brain and I'm happy about that ;)

**Comment by wxl** [comment]
> they need a human brain and I'm happy about that

Maybe not using *YOUR* brain might be a better idea, though? I'd personally rather see you use the little time you have continuing to improve LXQt than deal with such minutiae. If you're the only one you trust to do it, I understand, but just know that you don't have to wear all the hats :)

**Comment by tsujan** [comment]
> If you're the only one you trust to do it, I understand

No, I trust all LXQt developers for the job but I think only one dev should do it. I have 2 reasons:

First, an LXQt developer is needed because, for example, making ChangeLogs needs familiarity with the code or, sometimes, PRs may be needed quickly; and so on. Second, IMO, the coordination between 2 or more devs *for this straightforward job* would take extra time and energy from all of them.

**Comment by luis-pereira** [comment]
A bus factor of 1is not that great. And we already had to deal with it.

**Comment by tsujan** [comment]
@luis-pereira, the cause of our problem wasn't the number; it was that we didn't know how the person in question did all the jobs he did — making releases was only one of them; the simplest one. It wasn't his fault; we should have been more interested in what he did.

The process of releasing is as simple as https://github.com/lxqt/lxqt/issues/1779#issuecomment-617548853. Any LXQt developer could do it with his public key if I disappear ;)

To me, using Weblate has been much more complex and I hope that @stefonarch and @yan12125 will explain it in a step-by-step way.

**Comment by luis-pereira** [comment]
> @luis-pereira, the cause of our problem wasn't the number; it was that we didn't know how the person in question did all the jobs he did — making releases was only one of them; the simplest one. It wasn't his fault; we should have been more interested in what he did.

I didn't said it was his fault. It wasn't. But it lead to a single point of failure.

> The process of releasing is as simple as [#1779 (comment)](https://github.com/lxqt/lxqt/issues/1779#issuecomment-617548853). Any LXQt developer could do it with his public key if I disappear ;)
 
Sure. But the question here is more: is any developer are able to do it "easily" ?.
> 
> To me, using Weblate has been much more complex and I hope that @stefonarch and @yan12125 will explain it in a step-by-step way.

That kind demonstrates my last comment.

**Comment by tsujan** [comment]
>  is any developer are able to do it "easily" ?

Based on my experience, I think every developer will find it easy in a dull way ;)

**Comment by luis-pereira** [comment]
> > is any developer are able to do it "easily" ?
> 
> Based on my experience, I think every developer will find it easy in a dull way ;)


Sure. But we can have some documentation that helps to make it simpler.

**Comment by tsujan** [comment]
> But we can have some documentation that helps to make it simpler.

You're right. Documentations are important.

https://github.com/lxqt/lxqt/issues/1779#issuecomment-617548853 lacks a few details, especially about making signed tags and creating `PACKAGE-TAG.tar.xz` as well as `PACKAGE-TAG.tar.xz.asc` by using `gpg`. I'll add them to https://github.com/lxqt/lxqt/wiki/How-To-Release-A-New-Version-of-LXQt by making a PR later.

**Comment by yan12125** [comment]
> To me, using Weblate has been much more complex

The current flow is going to a Weblate repo (e.g., https://translate.lxqt-project.org/projects/lxqt-configuration/lxqt-config/), choose Manage -> Repository Maintenance and hit the Push button. (actually a PR is created instead of pushing directly to the repo) I feel that the Push action should happen automatically whenever a new translation is added/updated, so that the work of a release manager is just checking if there are still open pull requests from Weblate or not. I will investigate it when I find time.

Regarding the original proposal,

> The previous release was made in April. I suggest to release 0.16 in the first week of November and make releases regularly in April and November.

I'm +1 for this.

**Comment by stefonarch** [comment]
> I feel that the Push action should happen automatically whenever a new translation is added/updated, so that the work of a release manager is just checking if there are still open pull requests from Weblate or not.

The default behavior should be pushing every 24h (this is the default setting, could be changed) if they are new local commits:

```
 
cat ~log/weblate-celery-2.log | grep push
 
[2020-10-07 20:53:07,543: INFO/ForkPoolWorker-3] lxqt-configuration/pavucontrol-qt: skipped push: nothing to push
[2020-10-07 20:53:07,706: INFO/ForkPoolWorker-3] lxqt-configuration/pavucontrol-qt: skipped push: nothing to push
[2020-10-08 06:18:37,562: INFO/ForkPoolWorker-3] lxqt-configuration/pavucontrol-qt: skipped push: upstream not configured
[2020-10-08 06:18:37,657: INFO/ForkPoolWorker-3] lxqt-configuration/pavucontrol-qt: skipped push: upstream not configured
[2020-10-08 07:00:31,163: INFO/ForkPoolWorker-3] lxqt-desktop/lximage-qt: pushing to remote repo
 
```
There's a symlink to the celery logs in the home

**Comment by yan12125** [comment]
> The default behavior should be pushing every 24h (this is the default setting, could be changed) if they are new local commits:

Oops I forgot that fact. Then a release manager can indeed avoid bothering with Weblate.

**Comment by tsujan** [comment]
FYI

I started to make changelogs and release notes for a faster release in November. Please don't add exciting features to LXQt components; consider it like a "feature freeze".

**Comment by PCMan** [comment]
Thank you for bringing this up.
Totally agree with the regular release idea.
It's more convenient for the packagers.
New fixes can be delivered to the users regularly as well.
This really helps.
