### ISSUE TITLE
Panel mainmenu plugin inhibits handling of some global shortcuts

### ISSUE THREAD

**Issue by luis-pereira** [lxqt/lxqt#1849]
When the panel mainmenu plugin is selected (open menu) some shortcuts. e.g. power button, are not handled.

##### Expected Behavior
Shortcut keys should be handled with the mainmenu open or closed.

##### Current Behavior
At least some keys are not being handled.

##### Steps to Reproduce (for bugs)

1. Open the panel main menu.
2. Press the power button
3. The configured action should be executed. It isn't.

##### Context

It seems that the mainmenu plugin is somehow "filtering" the shortcuts. 

##### System Information

* Distribution & Version: Manjaro
* Kernel: not relevant
* Qt Version: 5.15.1
* liblxqt Version: git
* Package version: git

**Comment by tsujan** [comment]
I may have not understood this report correctly but all popup windows consume key presses and you can't use a shortcut when any of them is shown.

**Comment by luis-pereira** [comment]
@tsujan Yes, but the physical power button should work.

**Comment by tsujan** [comment]
Although I haven't used it in any code of mine, I think it's like other keys: `Qt::Key_PowerOff`.

When any Qt app (I mean real Qt, not Qt Quick) has an open menu, I can use neither global shortcuts nor the app's shortcuts. The same happens with GTK3 apps (if we don't consider Firefox and Chromium as GTK3 apps). And the same happens under KDE — with power button too. So, I think there's no bug to fix.

**Comment by luis-pereira** [comment]
It also happens with XFCE.
Closing although it's a unexpected.
