### ISSUE TITLE
Add Widget does nothing

### ISSUE THREAD

**Issue by clueo8** [lxqt/lxqt#1851]
Distro: archlinux

Linux eee-book 5.8.10-arch1-1.1 #1 SMP PREEMPT Fri, 25 Sep 2020 08:48:44 +0000 i686 GNU/Linux

liblxqt 0.15.1-1.0
lxqt-about 0.15.0-1.1
lxqt-admin 0.15.0-1.0
lxqt-archiver 0.2.0-1.0
lxqt-config 0.15.0-1.2
lxqt-globalkeys 0.15.0-1.0
lxqt-notificationd 0.15.0-1.2
lxqt-openssh-askpass 0.15.0-1.0
lxqt-panel 0.15.1-1.0
lxqt-policykit 0.15.0-1.0
lxqt-powermanagement 0.15.0-1.2
lxqt-qtplugin 0.15.1-2.0
lxqt-runner 0.15.0-3.0
lxqt-session 0.15.0-1.1
lxqt-sudo 0.15.0-1.0
lxqt-themes 0.15.0-1.0

qt5-base 5.15.1-3.0
qt5-declarative 5.15.1-1.0
qt5-location 5.15.1-1.0
qt5-svg 5.15.1-1.0
qt5-wayland 5.15.1-1.0
qt5-webchannel 5.15.1-1.0
qt5-webengine 5.15.1-3.0
qt5-x11extras 5.15.1-1.0

Installed lxqt group and breeze/oxygen-icons using pacman, trying to add widgets does not work.  I can remove, but not add to default panel or a new panel.

![screenshot](https://user-images.githubusercontent.com/7104071/95983561-d366b300-0def-11eb-87fd-7def5957816a.png)

**Comment by stefonarch** [comment]
This is unlike to be a LXQt issue and not even arch I think, could be permissions issue in your home directory.
I'd try creating a new user and check if the problem persists.

Otherwise just delete ~/.config/lxqt directory and relogin.
This will reset to default all settings except pcmanfm-qt.

**Comment by clueo8** [comment]
It seems that I'm just having an issue adding the **CPU monitor,** as I was able to add the color picker and backlight just fine.  Is there a dependency needed for the CPU monitor widget?

**Comment by stefonarch** [comment]
https://www.archlinux.org/packages/community/x86_64/lxqt-panel/
`libstatgrab (optional) - CPU monitor and Network monitor plugins
`

**Comment by clueo8** [comment]
Thank was it, thank you.
