### ISSUE TITLE
Promote @stefonarch as an LXQt member

### ISSUE THREAD

**Issue by yan12125** [lxqt/lxqt#1852]
##### Expected Behavior
@stefonarch is a member of the LXQt GitHub organization

##### Current Behavior
It is not the case

##### Possible Solution
Sending an invitation

Unfortunately I don't have the permission to add a new member to LXQt. I can visit https://github.com/orgs/lxqt/people but there is no "Invite member" button like what I see in another organization I created. Looks like only "owners" can add members [1]

[1] https://docs.github.com/en/free-pro-team@latest/github/setting-up-and-managing-organizations-and-teams/inviting-users-to-join-your-organization

##### Context

stefonarch has done fabulous work on creating the new Weblate instance [2] as well as several other infrastructure-related stuffs. The membership should better recognize contributions as well as making maintaining the infrastructure simpler.

[2] https://github.com/lxqt/lxqt/issues/1495

##### System Information
N/A

**Comment by tsujan** [comment]
Yes, IMO, @stefonarch should have been an LXQt member for a long time, even before his great work on Weblate. It seems that I don't have enough permissions either to invite members.

**Comment by yan12125** [comment]
@luis-pereira do you have invite permissions for LXQt?

**Comment by palinek** [comment]
Yes, Luis is the last (active) man standing :-S

**Comment by stefonarch** [comment]
Bus factor alarm ;)

**Comment by tsujan** [comment]
> Bus factor alarm ;)

Yes. At least two of us should have the required permissions — I always thought that was the case.

**Comment by luis-pereira** [comment]
Yes, I will take care of it.

--
Cumprimentos
Regards

A domingo, 18/10/2020, 20:18, tsujan <notifications@github.com> escreveu:

**Comment by luis-pereira** [comment]
@stefonarch Already sent an invitation.

**Comment by luis-pereira** [comment]
> Yes. At least two of us should have the required permissions — I always thought that was the case.

Me too. It was the case.

**Comment by tsujan** [comment]
@luis-pereira, thanks! It's good to know that you have admin access!

**Comment by luis-pereira** [comment]
> @luis-pereira, thanks! It's good to know that you have admin access!

@tsujan You and @yan12125 are now on the owners (admin) list.
@tsujan, Consider enabling 2FA.

**Comment by yan12125** [comment]
Thanks a lot @luis-pereira!

> @tsujan, Consider enabling 2FA.

Agreed - better to have 2FA for every member.

**Comment by luis-pereira** [comment]
> Agreed - better to have 2FA for every member.

Yes. Specially owners.

**Comment by tsujan** [comment]
@luis-pereira, 2FA would be a big obstacle to my work with GitHub.

The goal was having 2 admins among the members that have commented on this issue. You already had admin access (I didn't know that) and @yan12125 has it now. If my lack of 2FA is a security risk, please restore my previous permissions (write access without being an admin).

Please note that I understand your concerns. A too big bus factor can be a security threat in itself.

**Comment by stefonarch** [comment]
> @stefonarch Already sent an invitation.

Accepted, thank you all :)

**Comment by tsujan** [comment]
@stefonarch, you should receive email notifications when anything changes in LXQt (and issue is opened, a PR is made,...). The options are in your GitHub account settings.

Could you please also check and merge Weblate PRs when they arrive? I merged that last one a few minutes ago.

**Comment by stefonarch** [comment]
Ok, I'll take a look at the settings. But will be careful with merging atm.

**Comment by tsujan** [comment]
> But will be careful with merging atm.

Take your time.

Merging of Weblate PRs shouldn't need much care: I take a quick look at the changes by clicking "Files changed" button, then go back to the first tab and press "Squash and merge", provided that the format of changes is OK (that's always the case with Weblate).

As for other PRs, yes, more care is required.

**Comment by jubalh** [comment]
Welcome @stefonarch !

**Comment by yan12125** [comment]
Just a reminder: @stefonarch does not use 2FA yet

> 2FA would be a big obstacle to my work with GitHub.

@tsujan FWIW, currently I use KeePassXC TOTP with its Firefox addon. Filling 2FA is just two clicks of confirmation :)

**Comment by stefonarch** [comment]
> Just a reminder: @stefonarch does not use 2FA yet

I'm one of the few people  without smartphone, and having gauth in the same browser and PC isn't exactly 2FA ;)
But will look into this KeepassXC TOTP thing.

**Comment by Chiitoo** [comment]
I've used 'oathtool' as the authenticator app (http://www.nongnu.org/oath-toolkit/), and it has been convenient enough, I maybe guess.  :]

**Comment by stefonarch** [comment]
Well I saw oauth too already installed in my box  but better: 
GH 2FA can send just normal SMS to old legacy full Stallman-conform cellphones :) so I went that way.

**Comment by tsujan** [comment]
> @tsujan FWIW, currently I use KeePassXC TOTP with its Firefox addon

*For me*, 2FA is a self-torture. Apart from that, I don't have a smartphone and may rarely have my old mobile phone with me, having lived for more than 35 years in the cellphone-less era — stubbornly old-fashioned ;)

**Comment by stefonarch** [comment]
> @stefonarch, you should receive email notifications when anything changes in LXQt

Hm, I didn't get anything until now, but I see that I probably should change to "watch" each and every repo, I "watch" lxqt/lxqt already but doesn't include the others I think.

**Comment by tsujan** [comment]
> but I see that I probably should change to "watch" each and every repo

Oh, yes, I forget to tell you about that. Sorry!

**Comment by luis-pereira** [comment]
> I'm one of the few people without smartphone, and having gauth in the same browser and PC isn't exactly 2FA ;)
> But will look into this KeepassXC TOTP thing.

You don't need a smartphone. One that receives SMS's is all that is needed.

**Comment by stefonarch** [comment]
> One that receives SMS's is all that is needed

Yeah, I saw it already and set it up. Github is better than most internet banking nowadays...

**Comment by luis-pereira** [comment]
Some 2FA method is important, IMO.
We should make an effort to use it. Even the methods without a mobile phone provide an extra layer of security.
