### ISSUE TITLE
lxqt-config-monitor unreliable with twin 4K displays on Asus G14 laptop

### ISSUE THREAD

**Issue by spease** [lxqt/lxqt#1856]
I have a ROG Zephyrus G14 laptop connected to two 3840x2160 monitors. One (on the left connected to DP-0) has a refresh rate of 60 Hz, the other (on the right connected to HDMI-1-1) has a top refresh rate of 59.94 Hz. In trying to configure the setup properly, the lxqt-config-monitor utility displays unpredictable or unstable behavior. It is not clear how panel placement is determined, and in one case the panel disappears. More recently, the common behavior is for it to simply crash. I have not exhaustively tried every approach, but I have tried setting the left monitor as the primary, just setting the refresh rate, or restarting sddm, or rebooting the machine.

Despite lxqt-config-monitor crashing, I can manually adjust the layout with sddm.

##### Expected Behavior

Able to configure monitor setup.

##### Current Behavior

The application disappears when "Apply" or "Save" is pressed. Running through the console provides the following output.

```
$ lxqt-config-monitor
Connecting to KScreen...
Width x Height 5.18219 x 3.33849
Width x Height 2.59109 x 1.66924
Width x Height 5.18219 x 3.33849
minWidgetLength 221 maxMonitorSize 9600 scale 0.0230208
ion: pipeline execution error: process (2700) had a core dump
```

##### Steps to Reproduce (for bugs)

I am unsure what exactly the tipping point is.

##### System Information

* Distribution & Version: Arch Linux
* Kernel: Linux excalibur 5.9.1-arch1-1 #1 SMP PREEMPT Sat, 17 Oct 2020 13:30:37 +0000 x86_64 GNU/Linux
* Qt Version: 5.15.1-3
* liblxqt Version: 0.15.1-1
* Package version: lxqt-config 0.15.0-1

**Comment by tsujan** [comment]
The crash should have been fixed in git. If you can't use the git version, please wait for 0.16.0 (soon) and tell us whether the problem still persists.

**Comment by tsujan** [comment]
The fix: https://github.com/lxqt/lxqt-config/commit/f5c145032870ccd281ec4037ac75d4daff0b7037
