### ISSUE TITLE
Release Announcement for 0.16.0

### ISSUE THREAD

**Issue by tsujan** [lxqt/lxqt#1859]
If something important is missing or there is a mistake, please edit the following announcement. I want to add it to https://github.com/lxqt/lxqt when the release is complete.

@luis-pereira, would you please add it to https://lxqt.github.io/ after that, as with 0.15.0?

--------------------
The LXQt team announces the release of LXQt 0.16.0, the Lightweight Qt Desktop Environment.

# Highlights

## General

 Translation through Weblate is up and running again.

## LibFM-Qt / PCManFM-Qt

 * Options are added for switching to newly opened tab and opening tabs of last window.
 * File sorting is made more natural by treating dot as separator (like what GTK does — other aspects of file sorting aren't changed because Qt handles them best).
 * Several options are added to LXQt file dialog. All options are remembered.
 * DND into Desktop trash and also moving Desktop files into Desktop folders by DND are fixed.
 * An option is added for opening desktop folders inside the default file manager (which may not be PCManFM-Qt) when they are left clicked. By default, desktop folders are opened in PCManFM-Qt.
 * Several enhancements and fixes.

## LXQt Panel

 * Status Notifier supports customizable auto-hiding.
 * Task buttons can move windows to the next screen.
 * Main menu items have right-click menus for some actions.
 * The sizes and alignments of some plugins are fixed at startup.
 * An option is added for putting ungrouped task buttons of the same application next to each other.

## LXQt Configuration

 * Several Qt palette colors are added to lxqt-config-appearance. Qt styles that accept platform palettes (like Fusion) can be customized by lxqt-config-appearance.
 * "Default Applications" are added to lxqt-config-file-associations for setting the default web browser, file manager and email client.
 * The UI of lxqt-config-brightness is improved.
 * A crash is fixed in lxqt-config-monitor.

## LXQt Power Management

A Power keys section is added to the config dialog for customizing the actions of power, suspend and hibernation keys.

## QTerminal / QTermWidget

 * Closing of tabs by middle-clicking is made optional.
 * An option is added for opening the new tab to the right of the active tab.
 * The drop-down QTerminal is always put on the screen with the cursor.

## LXImage Qt

 * Images can be resized now.
 * Ambiguous shortcuts are prevented.
 * An action is added for copying file paths.
 * Start the app on the screen with the mouse cursor when opening images.
 * More image types are supported.
 * A depreciation notice is added to screenshot command line options.

## LXQt Archiver

 Now, `bsdtar` (belonging to `libarchive`) is used to open and extract RPM packages correctly.

## libQtXdg

 * QtXdg MimeApps Tool (qtxdg-mat) is enhanced to support setting/getting of the default email client, file manager and web browser.
 * Fixes.

## LXQt Desktop Notifications

 An option is added for showing notifications on the screen with the mouse pointer.

## PulseAudio Volume Control

 Random crashes are fixed when connecting to Bluetooth audio devices.

## LXQt Themes

 Three themes are added: Clearlooks, Leech and Kvantum.

## LXQt Session

 The Default Applications page is removed because default applications are now handled by the File Associations dialog more efficiently.

# Release Notes

Please see the release page of each LXQt component for its detailed release note.

**Comment by palinek** [comment]
Perfect... you are our hero.

**Comment by jubalh** [comment]
Looking good!

**Comment by luis-pereira** [comment]
@tsujan Sure.

**Comment by stefonarch** [comment]
Good work!
It's always hard to remember for me what's new, remembered and added the option in the taskbar for neighboring buttons.

**Comment by tsujan** [comment]
> added the option in the taskbar for neighboring buttons.

@stefonarch, thanks! I just changed it from coders' English to users' English.

**Comment by luis-pereira** [comment]
@tsujan progress can be seen [here](https://github.com/lxqt/lxqt.github.io/pull/49).

**Comment by tsujan** [comment]
@luis-pereira, thanks!

I've also prepared notes that will appear on release pages. They aren't as detailed as your notes (like that of libqtxdg) but might save you some time after the release. On the other hand, you might be more comfortable without them; I don't know....

**Comment by luis-pereira** [comment]
@tsujan Didn't know that. I was just copying the CHANGELOG.
Where are those release notes ?

**Comment by tsujan** [comment]
> Where are those release notes ?

They haven't been added yet. For each component, I'll add its release note to its release page, like https://github.com/lxqt/libqtxdg/releases/tag/3.5.0.

I'll start to release components in November 1 if everything goes fine. Today I caught a nasty cold (luckily, it wasn't COVID-19); otherwise, I'd finished the changelogs and translation updates.

**Comment by luis-pereira** [comment]
> They haven't been added yet. For each component, I'll add its release note to its release page, like https://github.com/lxqt/libqtxdg/releases/tag/3.5.0.

I completely forgot about release pages|

> 
> I'll start to release components in November 1 if everything goes fine. Today I caught a nasty cold (luckily, it wasn't COVID-19); otherwise, I'd finished the changelogs and translation updates.

Get well soon.

**Comment by stefonarch** [comment]
> I'll start to release components in November 1 if everything goes fine

Maybe take some more days for translators? I got about 10 emails for new strings now.

Get healthy soon again!

**Comment by tsujan** [comment]
> Maybe take some more days for translators?

I have no problem with that; can wait a few more days... Is November 4 good for you?

> Get healthy soon again!

9 hours of sleeping was the best cure :)

**Comment by tsujan** [comment]
@stefonarch 
A user asked me why some translations were blocked in LXQt Weblate. I replied I wasn't sure but the reason might be that the translations were being updated (by me) and it would take some time for Weblate to see them. Am I right?

**Comment by stefonarch** [comment]
> A user asked me why some translations were blocked in LXQt Weblate

All of the desktop files (lxqt-menu) is blocked, because @yan12125 and I have some better ideas to implement it. lx-image-qt was blocked for some hours because of merging conflicts, but this happens rarely and  happens automatically for all components. Weblate sees and receives immediately changes in source files.

**Comment by stefonarch** [comment]
> Is November 4 good for you

I'm done with Italian, but I saw you merged already translations in  other languages now. I think some day is enough, it's nice to ship a mostly translated 0.16

**Comment by tsujan** [comment]
OK. So, I'll start in November 4, instead of 1.

**Comment by yan12125** [comment]
Thanks a lot for the efforts! However, I'm quite busy these days and available for FOSS only on weekends. @jleclanche Could you help on updating LXQt packages on Arch Linux? If you're busy too, I can have a look since November 7.

> All of the desktop files (lxqt-menu) is blocked, ...

Thanks for the explanation! As a side note, those who are interested in details can have a look at https://github.com/lxqt/lxqt/issues/1044

---

By the way, should release notes for lximage-qt mention deprecation of its screenshot tool? (https://github.com/lxqt/lximage-qt/issues/334)

**Comment by tsujan** [comment]
>  I can have a look since November 7

November 7 is good. There's no haste.

> By the way, should release notes for lximage-qt mention deprecation of its screenshot tool?

Yes; I missed it. Will add it to changelog, release note and announcement. Thanks!

**Comment by jleclanche** [comment]
@yan12125 I'm not really using lxqt at the moment so if you can update the packages yourself that's better.

**Comment by stefonarch** [comment]
> November 7 is good. There's no haste.
 
Made an announcement in weblate.

**Comment by tsujan** [comment]
@stefonarch 
I meant November 7 *for Arch packaging*. I'll start releasing in November 4, as said in https://github.com/lxqt/lxqt/issues/1859#issuecomment-719932935

IMO, it's better not to delay a release for anything other than a "disastrous bug" that is suddenly found. Specially, if we delay it for translations. we could never finish it ;)

**Comment by tsujan** [comment]
Everything seems ready for the release now. @stefonarch , please don't merge any translation PR starting from tomorrow (November 4), until the release is finished.

**Comment by tsujan** [comment]
Done.

Please tell me if I've missed something!

**Comment by jubalh** [comment]
Thanks for your work @tsujan !
I updated all openSUSE packages to 0.16.0. They will now go into QA.

**Comment by tsujan** [comment]
@jubalh, thanks!

**Comment by tsujan** [comment]
lxqt-panel 0.16.1 is released. It fixes compilation with Qt 5.12 and 5.13; no other change.

**Comment by yan12125** [comment]
Thanks! My work progress for this week is better than I expected, so I upgraded Arch packages tonight. lxqt-panel is upgraded to 0.16.1, too.

**Comment by tsujan** [comment]
> so I upgraded Arch packages tonight.

Oh, so fast; I thought you'll do it the day after tomorrow.

With OpenSUSE and Arch having the latest release, it'll have its users soon :)

**Comment by McThump** [comment]
Roughly when do you expect 0.16 will be added to the Debian archives?

**Comment by jubalh** [comment]
Noone knows. As far as I know there is no active maintainer for LXQt on Debian anymore.

**Comment by tsujan** [comment]
> Roughly when do you expect 0.16 will be added to the Debian archives?

A good question we don't have a good answer for. Debian is an important distro. As @jubalh said, it doesn't have an LXQt maintainer -- it did until last year.

Considering that Debian is a conservative distro, I don't think it'll happen soon. But who knows? Maybe, Debian users could open an issue at Debian bug tracker and ask for LXQt packaging, mentioning that its current packages are obsolete.

**Comment by McThump** [comment]
Maybe I could help with this. I am new to Linux, coming from a Windows environment, so there would be a learning curve. Where could I learn more about what would be involved?

**Comment by tsujan** [comment]
In a nutshell, you need to master the Debian system. It requires a lot of time and practice; it's a professional job.

So, IMO, asking them may be a better approach.

**Comment by McThump** [comment]
Thanks. I will do that.

**Comment by McThump** [comment]
Here is a link to the bug: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=974100

**Comment by tsujan** [comment]
Good. Hopefully they'll do something about it. An active Debian maintainer for LXQt is really needed.

**Comment by palinek** [comment]
Do anyone know what happened to Alf? Did he get pissed of something and threw everything connected to FOSS away?

**Comment by jubalh** [comment]
> Do anyone know what happened to Alf? Did he get pissed of something and threw everything connected to FOSS away?

It was discussed on various issues here. If I remember correctly: noone really knows.

**Comment by stefonarch** [comment]
> Do anyone know what happened to Alf? Did he get pissed of something and threw everything connected to FOSS away?

Big mistery, last news from april was [this](https://github.com/lxqt/lxqt/issues/1829#issuecomment-614197861), and it explains nothing.

**Comment by tsujan** [comment]
> Do anyone know what happened to Alf?

This was the last news, from April 14: https://github.com/lxqt/lxqt/issues/1778#issuecomment-613622389 ("i'm ok - but had a  lot to do in the company"). After a while, it made his disappearance more mysterious to me.

**Comment by luis-pereira** [comment]
> Do anyone know what happened to Alf? Did he get pissed of something and threw everything connected to FOSS away?

I don't know.

**Comment by tsujan** [comment]
qterminal/qtermwidget and lxqt-config 0.16.1 are released. They fix regressions.

**Comment by yan12125** [comment]
Thanks! I updated them all in Arch Linux.

**Comment by tsujan** [comment]
@yan12125, @jubalh 

You may already know this: `libqtxdg` needs recompilation after upgrading to Qt 5.15.2; otherwise, some components (file association dialog, screengrab,...) will crash.

**Comment by yan12125** [comment]
Arch's Qt maintainer is diligent and has done it :) https://github.com/archlinux/svntogit-community/commit/6fcc4f5accc65fadcf524dec816e0a34db851e13

**Comment by jubalh** [comment]
openSUSE luckily rebuilds all packages once a dependency gets rebuilt/changed. Thanks for mentioning anyways @tsujan !
