### ISSUE TITLE
Translation site returns invalid response

### ISSUE THREAD

**Issue by ArthurBorsboom** [lxqt/lxqt#1862]
The lxqt readme provides a URL to a translation website at

[https://github.com/lxqt/lxqt#Translation](https://github.com/lxqt/lxqt#Translation)

![2020-11-16-105809_1949x672_scrot](https://user-images.githubusercontent.com/6639859/99239324-35557680-27fb-11eb-8d4d-2a1e00061adf.png)

The URL is called LXQt-Weblate and translates to

[https://translate.lxqt.project.org/](https://translate.lxqt.project.org/)

However on my system it return an invalid response.

![2020-11-16-105753_1322x691_scrot](https://user-images.githubusercontent.com/6639859/99239340-3ab2c100-27fb-11eb-9620-a9c4d08cac69.png)

Is this an SSL / certificate issue that needs fixing?

**Comment by stefonarch** [comment]
Thanks, it's a typo in the url, correct is:
https://translate.lxqt-project.org
Will fix it.

**Comment by stefonarch** [comment]
Closed by https://github.com/lxqt/lxqt/pull/1863
