### ISSUE TITLE
Regression: Issue #945 is back again (Claws-Mail SysTray-icon broken)

### ISSUE THREAD

**Issue by renegat73** [lxqt/lxqt#1864]
Regression of issue #945 since LXQt uptate to 0.16

Claws-Mail Icon in lxqt-panel is too big and without function until you open panel configuration  -> configure panel and close the dialog again.

##### System Information
* Distribution & Version: ArchLinux
* Kernel:  Linux  5.9.6-arch1-1 #1 SMP PREEMPT Thu, 05 Nov 2020 21:00:46 +0000 x86_64 GNU/Linux
* Qt Version: 5.15.1
* liblxqt Version: 0.16.0-1
* Package version: claws-mail 3.17.8-1

**Comment by tsujan** [comment]
It isn't a regression but a choice that was made at https://github.com/lxqt/lxqt-panel/commit/e826ea90528ad0b3566f3f407c087a9174793724 (also see https://github.com/lxqt/lxqt-panel/pull/1428).

The legacy/obsolete tray will be removed sooner or later. Old codes like that of Claws-Mail should be updated.

**Comment by renegat73** [comment]
Totally incomprehensible decision to me.
You totally needlessly remove a well working patch which many users did benefit from - what for? Why?
Even if you are planning to remove this legacy/obsolete tray sooner or later anyway?
Did this patch cause any drawbacks?
Do you think this is user-friendly?

**Comment by tsujan** [comment]
Did you even take a look at the links before ranting?

**Comment by renegat73** [comment]
Not every criticism is 'ranting'.

**Comment by renegat73** [comment]
Blueman icon now is also affected (blurred)...
![20201211-154550](https://user-images.githubusercontent.com/66755519/101917717-d7813800-3bc8-11eb-8fb9-14c7ee07a333.png)

**Comment by renegat73** [comment]
Issue still persists after quarter of a year...
Wouldn't it have been better to leave as it was?

**Comment by tsujan** [comment]
Reminder:

0.17.0 will come soon. Don't forget to tell the user in the GUI that systray is deprecated.

**Comment by tsujan** [comment]
Oh, it's already done :)

![obsolete](https://user-images.githubusercontent.com/981076/111902155-33bde880-8a51-11eb-85d9-249c3e803c26.png)
