### ISSUE TITLE
lxqt-session autostart fails to launch Python script in custom $PATH

### ISSUE THREAD

**Issue by pyl-zz** [lxqt/lxqt#1866]
##### Expected Behavior
lxqt-session provides an autostart mechanism based on the XDG specification, using *.desktop files lying in `$XDG_CONFIG_HOME/autostart/`.
In *.desktop files, the `Exec` key should be interpreted as relative to the `$PATH` environment variable.
Therefore the Application should be launched regardless of where the executable is located.

##### Current Behavior
I have a Python executable in my `~/.local/bin/`, `~/.local/bin/` is in my `$PATH` (which is set in my `~/.profile`)
The Python file is chmod +x, the shebang is setup properly, and the command works as expected when called from the shell. It is a "daemon" which stays around and is visible via `ps -u $(whoami)`
I have checked that my `$PATH` is already setup at the time of autostart.
Yet when the `Exec` key in the .desktop file is set to the simple command name, it doesn't launch.
The commands in `/usr/bin` however launch just fine.
If I provide the full path to the command, it works as expected again. It works with `~/.local/bin/command` as well (tilde expansion is performed)
It is to be noted that when I provide a `TryExec` key for the command in the .desktop file, the Application does not show up in the `lxqt-config-session` GUI tool. If I remove the `TryExec` key, it is shown again.

##### Possible Solution
Unfortunately, I don't know C++... I tried to have a look at the source however.
It seems the autostart applications are fired up using a `QProcess` object, which is given the first argument of the `Exec` key via its `::start()` method. (seen in `lxqtmodman.cpp`, line 479)
From my understanding, it should search the `$PATH`, yet somehow it doesn't.
I am puzzled.

##### Steps to Reproduce (for bugs)
```
# file is ~/.config/autostart/apodfetch.desktop #
[Desktop Entry]
Type=Application
Name=Apodfetch
Comment=Deamon fetching, retrieving, setting as X background the Nasa Apod
Exec=apodfetch
```
I could provide the Python code if needed, but I guess it wouldn't be very useful.
`lxqt-session` is invoked by `lxdm`. The configuration files are mostly stock, only a few modules are disabled (`lxqt-desktop`, `lxqt-globalkeyshortcuts`, `lxqt-powermanagement`)
The WM is Openbox.

##### Context
The behaviour described above is only a minor inconvenience, as the .desktop file can be rewritten to include an absolute path.
However, the file would need to be fixed if the command were to be moved to `/usr/local/bin` for example, which is not ideal.
If there is an easy fix it would be worth it, otherwise I think we could live with it.

##### System Information
* Distribution & Version: Voidlinux, rolling; glibc; lxqt-session is started by lxdm
* Kernel: Linux 5.8.18_1
* Qt Version: 5.15.1_3
* liblxqt Version: 0.16.0_1
* Package version: 0.16.0_1

**Comment by palinek** [comment]
> executable in my ~/.local/bin/, ~/.local/bin is in my $PATH (which is set in my ~/.profile)

~/.profile is a shell script executed/sourced by a "login" shell. It isn't something that should be treated by xdg session.

> I have checked that my $PATH is already setup at the time of autostart.

How did you check that? I doubt, that this is truth if the only place where the $PATH is updated to include ~/.local/bin is your ~/.profile.

**Comment by pyl-zz** [comment]
> ~/.profile is a shell script executed/sourced by a "login" shell. It isn't something that should be treated by xdg session.

But isn't the environment propagated when you login via a DM? I don't start any login shell after the lxdm login, and my `$PATH` is correctly set. I don't source my `~/.profile` at any point after that, not in my `~/.bashrc` and not anywhere else.

> How did you check that? I doubt, that this is truth if the only place where the $PATH is updated to include ~/.local/bin is your ~/.profile.

I autostarted a sh script that merely logged the value of my `$PATH`. Non-interactive shells don't source initialization files (bar `$BASH_ENV` for bash scripts, but my system uses dash as system shell), they use the environment they were invoked in.

**Comment by pyl-zz** [comment]
> I doubt, that this is truth if the only place where the $PATH is updated to include ~/.local/bin is your ~/.profile.

Actually, your comment made me realize something. I have `~/.local/bin` included in my $PATH. Usually it works just fine. I've just tried to explicitly include `/home/paul/.local/bin` in the $PATH, and it solved the problem.
So what's going on is clear now, the tilde expansion isn't performed in the `$PATH` when a process is started via a `QProcess`. I'm unsure whether that's the expected behaviour. Or if I should really have a tilde in my $PATH, anyway.
I'll try to check what the specifications are saying.

Thanks for your help!

**Comment by palinek** [comment]
> Sorry for bringing up a non-issue!

You don't need to be sorry. Even a non-bug, this is very well formed description and we see you were trying to analyze and solve your problem thoroughly.... not just shouting around.

**Comment by palinek** [comment]
> solved the problem.

Can you/we close this issue now?
