### ISSUE TITLE
lxqt-config-monitor -l results in Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by farberbrodsky** [lxqt/lxqt#1867]
##### Expected Behavior
When I run lxqt-config-monitor -l, it should not result in a segfault.

##### Current Behavior
[misha@localhost ~]$ lxqt-config-monitor -l
Segmentation fault (core dumped)

However, when I run lxqt-config-monitor and manually apply the last saved settings, it just works. I have no idea why.

##### Steps to Reproduce (for bugs)
1. Install Fedora LXQt, I have 3 monitors. one of which is rotated to the right.
2. Install NVidia drivers, I have an RTX 2060.
3. i3-gaps window manager.
4. lxqt-config-monitor -l

##### Context
I just can't put my monitors the right way without manually opening the program every time I log in. It's annoying.

##### System Information

* Distribution & Version: Fedora LXQt 33 x86_64
* Kernel: 5.9.11-200.fc33.x86_64
* Qt Version: qt 4.8.7-57.fc33
* liblxqt Version: 0.15.0-3.fc33
* Package version: 0.15.0-2.fc33

EDIT:

I solved it by switching to qt5ct. It was installed but not being used. When I set QT_QPA_PLATFORMTHEME to qt5ct, everything started working. Super weird.

**Comment by stefonarch** [comment]
```
$  lxqt-config-monitor -l
[load.applyBestSettings()] Finished
lxqt-config-monitor: Applying current settings...
Output:  "DP-1"
Output:  "HDMI-1"
Output:  "HDMI-2"
lxqt-config-monitor: Settings applied.
```
without qt5ct and without Nvidia. Could be Fedora issue?

**Comment by tsujan** [comment]
> without qt5ct and without Nvidia. Could be Fedora issue?

Under LXQt, `QT_QPA_PLATFORMTHEME` is `lxqt`. I guess @farberbrodsky doesn't use LXQt; hence needing to set `QT_QPA_PLATFORMTHEME` manually.

@farberbrodsky, if you have an LXQt session but `QT_QPA_PLATFORMTHEME` isn't set to `lxqt`, there's a problem with your installation.
