### ISSUE TITLE
Add new translation on Weblate

### ISSUE THREAD

**Issue by mkkDr2010** [lxqt/lxqt#1868]
I have translated  most components of lxqt in Bulgarian  and created a Webplate account. I want to upload the .ts file for corresponding module, but when I try to add Bulgarian as language there is message access denied and that I have not the permission to see the page. How can I upload the translations?

**Comment by stefonarch** [comment]
I see, thank you for reporting, it's the first time that an non-admin adds a new language.
I added you to a new "create translation group", please report if it's working.

**Comment by stefonarch** [comment]
I looked into it some more, and IMHO those permissions are not needed.
First step is  Languages > manage translated languages and select the language you desire to translate in and you will find it on top in all components.

Will remove the permission, but again: please report.

**Comment by mkkDr2010** [comment]
Still not working. I am not sure that I am doing it right. The language setting are correct, but when I choose for example libfmqt, Bulgarian is a not translated language and sits on top with leading + ahead. Clicking + still results Insufficient privileges to display this page.

**Comment by stefonarch** [comment]
You are right, I didn't click the + button in my test.
Check now please, users now have permission to add new language .

**Comment by mkkDr2010** [comment]
Its OK. I am working on upload. Thanks!

**Comment by stefonarch** [comment]
Thanks to you, we didn't notice that issue.

**Comment by zoli111** [comment]
I tried to add Hungarian translation to newly added modules but I ran into the same problem. It worked when this issue was closed but now it isn't.

**Comment by stefonarch** [comment]
It is by-user now, see info: https://translate.lxqt-project.org/projects/lxqt-desktop/#information
I upgraded your permissions now, report if it doesn't work please.

**Comment by zoli111** [comment]
It works for me now. Thank you.
