### ISSUE TITLE
Adapt to use Qt5.15 Qt::SplitBehavior - PR tracker

### ISSUE THREAD

**Issue by luis-pereira** [lxqt/lxqt#1870]
Getting rid of annoying warnings. 
PR's:

https://github.com/lxqt/qtermwidget/pull/377
https://github.com/lxqt/qterminal/pull/758
https://github.com/lxqt/pcmanfm-qt/pull/1258
https://github.com/lxqt/lxqt-panel/pull/1503
https://github.com/lxqt/lxqt-config/pull/688
https://github.com/lxqt/lxqt-admin/pull/222
https://github.com/lxqt/liblxqt/pull/272
https://github.com/lxqt/libfm-qt/pull/599

**Comment by palinek** [comment]
Copying comment from panel PR here:

We neither support previous releases of LXQt nor backport new features to them. We need to make our life easier (there are too few people maintaining lxqt).

Do we want to mess our code with these ugly #ifs? Why not just require v5.15?

**Comment by tsujan** [comment]
> Why not just require v5.15?

I, for one, have no problem with that in LXQt but there will be comments by angry users.

**Comment by luis-pereira** [comment]
> Copying comment from panel PR here:
> 
> We neither support previous releases of LXQt nor backport new features to them. We need to make our life easier (there are too few people maintaining lxqt).

This has nothing to do neither of those.

> Do we want to mess our code with these ugly #ifs? Why not just require v5.15?

Because it will alienate a probably a not so little portion of LXQt users.



It's interesting that we all new about the nasty warnings. This kind of fix is already deployed in some places and there were no issues raised.

**Comment by luis-pereira** [comment]
> I, for one, have no problem with that in LXQt but there will be comments by angry users.

For me personally, is great. But, it's not about me. It's about the users.

**Comment by tsujan** [comment]
>  it's not about me. It's about the users.

I agree that it isn't about us; hence talking about "angry users" ;) In my apps, I have lots of version checks to support old Qt versions. It isn't users' fault that Qt devs "deprecate" methods so quickly.

**Comment by palinek** [comment]
> This kind of fix is already deployed in some places and there were no issues raised.

Don't take me wrong. I'm not blaming you. I really appreciate, that you take care about a lot of boring work here-and-there.
I just think loud. Users have their apps in whatever version they are on. The change will only affect future releases and bleeding edge git users. If someone wants to stick with "rock stable" distro, he/she will not get any new releases anyway => so will not be affected by any of our current changes.
Does any major distribution stick to old version of Qt in its "future branch"?

**Comment by luis-pereira** [comment]
> I agree that it isn't about us; hence talking about "angry users" ;) In my apps, I have lots of version checks to support old Qt versions. It isn't users' fault that Qt devs "deprecate" methods so quickly.

IMO we can't afford the "luxury" of only supporting the latest Qt version. To be clear: I'm not talking about supporting past LXQt releases or backporting.

I also don't like the #ifdefs and even less doing the commits. But I noticed that, with the build logs so polluted, I simply don't bother to look at them.

**Comment by tsujan** [comment]
Supporting the previous LTS seems good. Avoiding version checks is impossible in the real world.

It's time to remove some (like `#if (QT_VERSION >= QT_VERSION_CHECK(5,12,0))` in libfm-qt).

**Comment by luis-pereira** [comment]
All merged.
