### ISSUE TITLE
LXQt forum issue

### ISSUE THREAD

**Issue by stefonarch** [lxqt/lxqt#1871]
The forum went offline https://github.com/lxqt/lxqt/issues/1829#issuecomment-741006182
##### Expected Behavior

There should be one.
##### Current Behavior

There is none.
##### Possible Solution

Github Discussions o forum on lxqt-project.org.

**Comment by tsujan** [comment]
→ https://github.com/lxqt/lxqt/discussions/1872#discussioncomment-176550
