### ISSUE TITLE
LXQt+AwesomeWM, windows only show as vertical lines

### ISSUE THREAD

**Issue by FitzM** [lxqt/lxqt#1877]
I've switched the window manager to AwesomeWM instead of openbox. At first switch there is no issue goecer at sometime during the change windows stop opening correctly and begin opening as vertical lines. They are the correct height as the chosen layout ( ie full screen/ master & stack) but is only 3 or 4 pixels wide. The window is only viewable if I switch it to full screen with a keyboard shortcut. 

-Switching back to LXQt + openbox, the issue does not persist. 

- AwesomeWM alone , the issue does not exist.  Also Awesome + Mate does not create the issue. 

I am on OpenSUSE Tumbleweed and have recently updated. 

I'm not sure what is causing the issue of where to even look.

**Comment by tsujan** [comment]
You may want to report it to AwesomeWM. Whether it works OK with Mate or not isn't relevant to LXQt but to AwesomeWM
