### ISSUE TITLE
Some SVG icons are not rendered correctly

### ISSUE THREAD

**Issue by oratosquilla-oratoria** [lxqt/lxqt#1882]
##### Expected Behavior
SVG icons should be rendered correctly.

##### Current Behavior
Some icons are not rendered correctly. For example, what the icon should look like:
![Screenshot at 2020-12-11 16-58-22](https://user-images.githubusercontent.com/15127577/101916760-4a85b100-3bbf-11eb-9593-8dab445ab489.png)
and how it's rendered:
![Screenshot at 2020-12-11 17-38-20](https://user-images.githubusercontent.com/15127577/101916784-52455580-3bbf-11eb-9247-3b67842cd29c.png)

##### Steps to Reproduce
1. Download the [icon.zip](https://github.com/lxqt/lxqt/files/5679869/icon.zip);
2. Extract it anywhere;
3. See its thumbnail in the lxqt file manager or/and
4. Replace any icon in any theme with this icon and see that it's rendered incorrectly too 'in the wild'.

##### Context
Icons are pretty important. It's nice when they rendered correctly :)

##### System Information
* Distribution & Version: Tested on Manjaro and Lubuntu 20.10 (binary packages), also master branch of this repository;
* Kernel: Tested on 5.4 and 5.8;
* Qt Version: 5.14.2 (Lubuntu) and 5.15.2 (Manjaro);
* liblxqt Version: 0.15.0 (Lubuntu) and 0.16.0 (Manjaro).

**Comment by tsujan** [comment]
Nothing can be done by LXQt. The problem is in Qt's rendering of SVG.

**Comment by tsujan** [comment]
BTW, you could consult so many SVG icon themes that are made for Qt to know what you can do with the SVG image and what not. Here, I fixed a part of your icon (didn't have time for more):

[manjaro-notifier-settings.svg.zip](https://github.com/lxqt/lxqt/files/5680242/manjaro-notifier-settings.svg.zip)
