### ISSUE TITLE
GTK 2 theme is not applied when it is located in ~/.local/share/themes/THEME_NAME

### ISSUE THREAD

**Issue by oratosquilla-oratoria** [lxqt/lxqt#1883]
##### Expected Behavior
A GTK 2 theme should work when it is put in ~/.local/share/themes/THEME_NAME.

##### Current Behavior
A GTK 2 theme does not work when it is put in ~/.local/share/themes/THEME_NAME. GTK 3 themes work. If the theme is put in /usr/share/themes/THEME_NAME, everything is ok.

##### Steps to Reproduce
1. Put a GTK 2 theme in ~/.local/share/themes/THEME_NAME;
2. Go to Appearance -> Widget style -> [x] Set GTK themes... -> GTK 2 Theme;
3. Choose the theme.

##### System Information
* Distribution & Version: Tested on Manjaro and Lubuntu 20.10 (binary packages), also master branch of this repository;
* Kernel: Tested on 5.4 and 5.8;
* Qt Version: 5.14.2 (Lubuntu) and 5.15.2 (Manjaro);
* liblxqt Version: 0.15.0 (Lubuntu) and 0.16.0 (Manjaro).

**Comment by tsujan** [comment]
GTK2 doesn't support `~/.local/share/themes/`.
