### ISSUE TITLE
Long  texts in weblate *.dsktop.yaml generate new line

### ISSUE THREAD

**Issue by stefonarch** [lxqt/lxqt#1884]
At some length weblate inserts a newline in `*.yaml `files

Example: https://translate.lxqt-project.org/translate/lxqt-configuration/lxqt-config-powermanagement-menu-entry/bg/?&offset=3
Looks all ok, but in the commit 
https://github.com/lxqt/lxqt-powermanagement/pull/220/files#diff-f3d7808ad0ae65617b0d1d628272d86cef39e06b4ed127b4b0946e844f99d26e

and in /usr/share/applications:
```
Name[bg]=Управление на захранването
GenericName[bg]=Настройки на управление на захранването
Comment[bg]=Настройки на поведение при бездействие, натиснат бутон за\

```

##### Possible Solution

Keep comment source texts short. 
Building  is not affected, and comments aren't shown anywhere afaik.

**Comment by tsujan** [comment]
> Keep comment source texts short.

I don't think that's a good solution. The length of the translated string can be long, depending on the language. We shouldn't force a limit on it here.

Also, we can't be sure that comments are never used; they might be used in LXQt at some point and may be used in other DEs (KDE?).

**Comment by tsujan** [comment]
Sorry if these are stupid questions: (1) Are we sure that Weblate does that? (2) If yes, is there an option for it?

**Comment by stefonarch** [comment]
1)  yes, tested it:
```
Desktop Entry/Name: "Impostazioni Openbox"
Desktop Entry/GenericName: "Impostazioni del gestore finestre"
Desktop Entry/Comment: "Configura il gestore finestre Openbox Configura il gestore\
  \ finestre Openbox Configura il gestore finestre Openbox Configura il gestore finestre\
  \ Openbox"
```
2) Didn't find one.

> The length of the translated string can be long, depending on the language. We shouldn't force a limit on it here.

Agree, but will affect only comments. I think this comment is the longest one we have allover:
`Various settings regarding Power Management like battery or idleness watcher
`

Looked for some yaml doc but didn't find anything useful. It's about 60 characters.
Parsing during compiling works fine, it just stops after \

**Comment by tsujan** [comment]
I'm not aware of any limitation on line length in YAML but I'm not a YAML expert.

However, perhaps Weblate uses [yamllint](https://github.com/adrienverge/yamllint) to check YAML files. yamllint seems to have a rule for limiting the line length.

If that's true, we need to remove or loosen that limitation because comments can be long, especially when they're translated.

**Comment by stefonarch** [comment]
`locate yammllint` on the server shows no result.
But anyway, it looks like comments are nowhere used by LXQt

**Comment by tsujan** [comment]
> But anyway, it looks like comments are nowhere used by LXQt

If a desktop file has no `GenericName`, its `Comment` appears on its tooltip in panel's main menu. And, as I implied above, there's no guarantee that `Comment` won't be used in other ways at some point.

I'm not saying that it's important but I have a bad feeling about damaging something in our codes just because an external tool doesn't work fine; it can't be a good compromise in the long run.

**Comment by stefonarch** [comment]
_> If a desktop file has no `GenericName`, its `Comment` appears on its tooltip in panel's main menu.

I raised several times the question, are you sure? I saw that for lxqt-leave Comment= was never shown if GenericName was missing and this was the case in 80% of the files. Cannot find the issue atm.

This addon I never saw, probably because it was not shown when there were no yaml files.
Will add it to  the yaml files, and all is fine.
![schermata-12-12-13:25](https://user-images.githubusercontent.com/10681413/101983843-bf1f2500-3c7d-11eb-809b-640ec5f2d7a5.png)

**Comment by tsujan** [comment]
> I raised several times the question, are you sure?

Sorry, I didn't see your questions! Take a look at the desktop file of Kvantum Manager. It has no `GenericName` and its `Comment` is shown as its tooltip in the main menu.

Make it "No line wrapping" as a safeguard.

Please also search for the newline setting. Weblate explanation made me worry; we don't want MS Windows newline in our files.

**Comment by stefonarch** [comment]
> Please also search for the newline setting. Weblate explanation made me worry; we don't want MS Windows newline in our files.

it's in the same window, didn't include it, but defaullts to  /
 It's newline syntax for yaml.
Anyway, now I set "no line break" 

Still wonder, here in 0.14.1 debian in leave submenu no comment is shown.

**Comment by tsujan** [comment]
> Still wonder, here in 0.14.1 debian in leave submenu no comment is shown.

If you manually edit the files, the panel may need a restart to see their new contents. Or, maybe, the panel is compiled with menu-cache...

Anyway, you solved the main problem. Thanks!

**Comment by stefonarch** [comment]
read above, edited, sure panel has to be restarted.

**Comment by tsujan** [comment]
> read above, edited

yes, I also meant no `GenericName` whatsoever.

**Comment by stefonarch** [comment]
Kvantum shows  always translated comments because there is no `GenericName=Manager for Kvantum themes` or whatever.

**Comment by stefonarch** [comment]
I noticed too late that the yaml addon was needed in plugin-colorpicker name&description too as the text exceeds 80 char, 6 files were already translated. The plugin works only with new translations, so 
1. remove translation, commit in weblate
2. readd translation, commit

https://github.com/lxqt/lxqt-panel/pull/1761/files
