### ISSUE TITLE
How can I avoid a confirmation pop up in lximage qt

### ISSUE THREAD

**Issue by tik9** [lxqt/lxqt#1885]
How can I avoid a confirmation pop up in lximage qt after deleting a file?

![image](https://user-images.githubusercontent.com/3178925/101952742-6efe7f00-3bf9-11eb-9e6d-6096112c3092.png)

Can you give a way to start?
I tried nothing so far, but wait for a starting info.

**Comment by tsujan** [comment]
> How can I avoid a confirmation pop up in lximage qt after deleting a file?

You can't. And the prompt — which is shown *before* deleting a file, not after it — is necessary because lximage-qt shouldn't do the job of a file manager without a prompt.

> Can you give a way to start?

I didn't understand this. Starting what?
