### ISSUE TITLE
LXQT git Submodule badly out of date

### ISSUE THREAD

**Issue by scsijon** [lxqt/lxqt#1888]
##### Expected Behavior
I was looking at using the git submodule to pull down the latest copy of lxqt

##### Current Behavior
Quite a bit of it is still pointing to 0.11 from 4 years ago.

##### Possible Solution
Looks like a manual update is needed (unfortunately)

##### Steps to Reproduce (for bugs)
1. git submodule init
2. git submodule update --remote --rebase

##### Context
I'm looking at what it actually needs to create a combined lxqt.sfs for Puppy/Easy/Quirky linux, and a future intent of a clang/musl/llvm version for a graphics (manga creation / scanlation / Video graphics ) design system, since i'm now 'officially' retired.  I have looked at and worked with Razor-qt back when it started as a stand-alone package, so i know it should be able to do what I need! And being on satellite out here, pulling individual pars and packages down, basically sucks. The actual packages I need are all available, it's the basic system that isn't how I want it.

**Comment by stefonarch** [comment]
> pulling individual pars and packages down, basically sucks.

In the mean time you could modify and use [my script](https://gist.github.com/stefonarch/f640197171070a82e548b76a85d62399.)

**Comment by scsijon** [comment]
thank you, i'll have a look at that.

**Comment by stefonarch** [comment]
I was not referring to the  script linked, I  compiled  some days ago in Vbox  with ubuntu to test and it compiles latest git.
```
git submodule init
git submodule update --remote --rebase
```
