### ISSUE TITLE
Another translation issue 

### ISSUE THREAD

**Issue by mkkDr2010** [lxqt/lxqt#1890]
I am not sure that this is lxqt related, but I noticed that in some applications standard buttons OK, Apply are not translated. For example Falkon. All dialogs   come with untranslated Cancel, OK, Apply buttons. 
![screen-1](https://user-images.githubusercontent.com/75447241/102191885-4f49ae00-3eba-11eb-84c4-d79b76c8b245.jpg)

**Comment by stefonarch** [comment]
You have to install `qt5-translations` (on arch, other distros may have different names) package, this is no LXQt issue.

**Comment by mkkDr2010** [comment]
It is already installed. Perhaps is a Falkon's issue.

**Comment by stefonarch** [comment]
Tested in falkon on arch, those button are translated. What distro are you using?

**Comment by tsujan** [comment]
Whether those buttons are translated or not has absolutely nothing to do with LXQt.

**Comment by mkkDr2010** [comment]
I am on arch, -Suy today. Lxqt from arch and some lxqt components build from git. Qt5 is latest from arch too. I really can’t track the issue. I think is some kind of Qt bug. I will leave the test system and will try again from start on other distro to test. 


Am Dienstag, Dezember 15, 2020, 2:41 PM schrieb Standreas <notifications@github.com>:




Tested in falkon on arch, those button are translated. What distro are you using?

**Comment by tsujan** [comment]
@mkkDr2010, LXQt has no role in translating that dialog.

**Comment by mkkDr2010** [comment]
Yes, I supposed, that was a try to find the cause. Sorry for bothering.



Am Dienstag, Dezember 15, 2020, 7:01 PM schrieb tsujan <notifications@github.com>:




@mkkDr2010, LXQt has no role in translating that dialog.

**Comment by stefonarch** [comment]
As tsujan already told you: no need for opening new ones, also in a closed issue commenting is possible.
There is also "discussions" for general questions.
Said this I've no idea why it doesn't work in your system, you could try testing a new user.

**Comment by mkkDr2010** [comment]
It was not intended to be a new issue. I just wanted to discuss the problem and did it wrong through git interface. 


Am Donnerstag, Dezember 17, 2020, 6:23 PM schrieb Standreas <notifications@github.com>:




As tsujan already told you: no need for opening new ones, also in a closed issue commenting is possible.
There is also "discussions" for general questions.
Said this I've no idea why it doesn't work in your system, you could try testing a new user.

**Comment by mkkDr2010** [comment]
After a couple of tries and errors, testing etc I tracked down the issue. Falkon relays on the KDE library for translation. In KDE those buttons are correctly translated, but not in other DE. I tested in Archlinux, Debian and Manjaro. I have no idea how that is working on your system unless you are on KDE. 
But for myself I found a workaround. I just added the Translator libraries and the correct path of qt translation program and loaded the translator in main.cpp of application. 
I also made a fork for future uses. 
With regards


     Am Donnerstag, 17. Dezember 2020, 18:23:59 MEZ hat Standreas <notifications@github.com> Folgendes geschrieben:  
 
 


As tsujan already told you: no need for opening new ones, also in a closed issue commenting is possible.
There is also "discussions" for general questions.
Said this I've no idea why it doesn't work in your system, you could try testing a new user.

**Comment by stefonarch** [comment]
Not sure if this is true, it's ok for me in arch and debian with not many  or no kde components.
