### ISSUE TITLE
Missing translation files for desktop entries and application entries for panel applets

### ISSUE THREAD

**Issue by mkkDr2010** [lxqt/lxqt#1893]
Hello, 
I build the whole lxqt DE from git and I noticed there are missing desktop entries for leave and subcategories. I tried to add the missing translations for Bulgarian, but again I have no permission to do that.

**Comment by stefonarch** [comment]
For the first, in the mean time we changed the permission settings, I added you now, it should work.

For the panel applets translations: I'm working on a PR, the files for the plugins need a cleanup before importing in weblate. This should be the last piece. If you notice something that is not translable please report.

**Comment by stefonarch** [comment]
Going through those hundreds files with some scripts I found:
```
Desktop Entry/Name:"World clock"
Desktop Entry/Comment:"World clock plugin"
```
I think this could be renamed now, as clock-plugin is gone. Many translations are more clear about.
Something like
```
Desktop Entry/Name:"Clock and Calendar"
Desktop Entry/Comment:"Displays a clock with calendar and can show also different time zones"
```
@tsujan @yan12125 @luis-pereira @palinek ?

**Comment by tsujan** [comment]
I think "World Clock" is a good name because it shows that it isn't just a simple clock. But I'll have no objection if everybody prefers another name.

**Comment by stefonarch** [comment]
"Wordclock" is always seen (in english) anyway:

![schermata-08-51-45](https://user-images.githubusercontent.com/10681413/102588886-6ed91480-410e-11eb-8e6c-f4e846dda517.png)

At least the comment should be improved.

**Comment by tsujan** [comment]
> At least the comment should be improved.

Yes, it could be shorter: "Displays a clock with calendar and time zones"

**Comment by stefonarch** [comment]
Another comment to improve:
```
Desktop Entry/Name: "Status Notifier Plugin"
Desktop Entry/Comment: "Status Notifier Plugin"
```

**Comment by tsujan** [comment]
Good point. Some users don't know it's the new tray and use the obsolete and dysfunctional systray plugin (which should be removed sooner or later).

I suggest something like this: "Provides the notification area (a.k.a. system tray)"

**Comment by tsujan** [comment]
Oh, the comment of "System tray" should be changed to:
```
Obsolete; use Status Notifier Plugin instead
```
I forgot to change it in 0.16.

**Comment by stefonarch** [comment]
This will have no effect on existing translations I think, because it's not a *.ts file (which will always change to "unfinished" when source is changing.
Or we replace all comments. Or we add it something  to Name=

**Comment by tsujan** [comment]
I didn't think in terms of translations — I'm not an expert in that area.

Comments are shown in the Add Plugins dialog and explain what the widgets are for. So, they're important. Particularly, the comments of Status Notifier Plugin and the obsolete System tray need changes, as suggested above.

**Comment by stefonarch** [comment]
So I'll reset the translated comments plugin-tray so  the new source comment will be displayed in all languages until translated again in weblate.

**Comment by stefonarch** [comment]
Done so far, but making one PR results in 540 changed files, and some directories have new updates from weblate and checking is impossible.
Will split the PR in several tranches.

**Comment by stefonarch** [comment]
I'd like to merge those 2 above and import them in weblate.
Grouping the PRs by 3 or 4   plugins there will be other 5 commits to close finally https://github.com/lxqt/lxqt/issues/1044

**Comment by stefonarch** [comment]
Question: I noticed now that some source titles words start all with uppercase and some not, better uppercase in title ("Show Desktop")?
![schermata-21-12-17:46](https://user-images.githubusercontent.com/10681413/102800854-bed90500-43b4-11eb-92a1-13e19c2e79e5.png)

**Comment by tsujan** [comment]
I'd noticed that too. I think it's better to capitalize all of them.

**Comment by stefonarch** [comment]
...and "plugin" in "status notifier plugin" should be removed too. 
Another 3 PR's to go. The first 2 are successfully imported already in weblate as "plugin-foo (Name & Description)"
https://translate.lxqt-project.org/projects/lxqt-panel/

**Comment by stefonarch** [comment]
Description for sysstat plugin can be improved too I think:
"System Statistics plugin"

And I noticed that otherwise than in mainmenu if no translated comment is present no description is shown, so for the  tray message translations should be ripristinated and added a (deprecated) to all.

**Comment by tsujan** [comment]
> Description for sysstat plugin can be improved too I think

"Shows a graph for network, CPU or memory"

>  if no translated comment is present no description is shown

So, the English strings should be added?

**Comment by stefonarch** [comment]
False alarm - comments were malformatted there, my fault.
`Desktop/Comment: ""` instead of `Desktop Entry/Comment: ""`
Preparing a PR.

**Comment by stefonarch** [comment]
Works as it should:



![schermata-22-12-11:39](https://user-images.githubusercontent.com/10681413/102879802-ae736980-444a-11eb-9e5d-39c0bcd9e1af.png)
