### ISSUE TITLE
Tested in falkon on arch, those buttons are translated. What distro are you using?

### ISSUE THREAD

**Issue by mkkDr2010** [lxqt/lxqt#1894]
Tested in falkon on arch, those buttons are translated. What distro are you using?

_Originally posted by @stefonarch in https://github.com/lxqt/lxqt/issues/1890#issuecomment-745293214_

**Comment by mkkDr2010** [comment]
Sorry for insisting, but I am stuck with this issue. I tasted yesterday with arch and debian and those items in QDialogbuttonBox are left in LXQt untranslated, but in KDE they are translated. You mentioned that in your system there is no such situation. What am I doing wrong. Today I builded the whole LXQt from git in new arch environment and the issue persist.

**Comment by tsujan** [comment]
@mkkDr2010, please never do these things:

 1. Opening an issue about an app that doesn't belong to LXQt; or
 2. Opening an issue as the continuation of a closed issue.

**Comment by mkkDr2010** [comment]
I understand you and it was not intended to be a new issue, I just wanted to share the experience. I am not a developer and I can not track the issue. Those QDialogBoxbuttons are not translated in LXQt but in KDE are translated. I noticed that KDE translation is related to qtbase.qm file too as should LXQt be. I tested this in fresh installed archlinux and debian. LXQt is intended to be a desktop environment and such situations lead to an inconsistency of interface. I hoped to get some directions from experts how to remedy it.

With best regard
     Am Donnerstag, 17. Dezember 2020, 18:02:46 MEZ hat tsujan <notifications@github.com> Folgendes geschrieben:  
 
 


@mkkDr2010, please never do these things:
   
   - Opening an issue about an app that doesn't belong to LXQt; or
   - Opening an issue as the continuation of a closed issue.
