### ISSUE TITLE
CMake error on lxqt-build-tools

### ISSUE THREAD

**Issue by zhrexl** [lxqt/lxqt#1895]
I used to build lxqt-notificationd just fine, its been a few months since I last tried but today after downloading again from github I tried to compile it but I got this error:

> CMake Error at /usr/share/cmake/lxqt-build-tools/modules/LXQtTranslateDesktop.cmake:62 (string):
>   string sub-command REPLACE requires at least four arguments.
>
> Call Stack (most recent call first):
>   autostart/CMakeLists.txt:4 (lxqt_translate_desktop)
> 
> 
> CMake Error at /usr/share/cmake/lxqt-build-tools/modules/LXQtTranslateDesktop.cmake:92 (string):
>   string sub-command REPLACE requires at least four arguments.
>
> Call Stack (most recent call first):
>   autostart/CMakeLists.txt:4 (lxqt_translate_desktop)

Line 62 of LXQtTranslateDesktop.cmake
`string(REPLACE ".in" "" _fileExt ${_fileExt})`

Line 92:
`string(REPLACE "." "" _fileType ${_fileExt})`

Is there something I'm missing here?

* Distribution & Version:  Arch Linux
* Kernel:  5.9.14
* Qt Version:  5.15.2
* liblxqt Version: 0.16.0
* Package version: git latest version master branch

**Comment by stefonarch** [comment]
Did you rebuild the first 3 components? There were changes.
https://github.com/lxqt/lxqt/wiki/Building-from-source#0

**Comment by zhrexl** [comment]
> Did you rebuild the first 3 components?

No, never did though. It used to work just intalling them with pacman. I tried reinstalling them in the correct order but I still get that error.

**Comment by stefonarch** [comment]
You could install them with AUR, probably it's enough only lxqt-build-tools.

**Comment by zhrexl** [comment]
> You could install them with AUR (package-name-git)

This solved it.
Thank you very much!
