### ISSUE TITLE
Is it possible to set default sink with GUI in LXQt? 

### ISSUE THREAD

**Issue by q4a** [lxqt/lxqt#1896]
##### Expected Behavior
LXQt should be modern DE and allow user to change simple configs without opening terminal and runing some commands.
I was expected, that LXQt provide some applet to set default sink for pulseaudio.
May be it's my problem and I removed something, but search did not help.

##### Current Behavior
You have to install come other applets or use terminal with commands like:
$ pactl list sinks | grep -E 'Sink|Name|Desc'
$ pactl set-default-sink 1

##### Possible Solution
I think, you should add some options to set default sink and source to [volume applet](https://user-images.githubusercontent.com/1950719/102642565-f2c2e900-416e-11eb-90af-442aadc15b9c.jpg)
Or may be just configure and preinstall some other applets like pasystray or indicator-sound-switcher.

##### Context
I plugged in USB sound card and want to test mic with output thought my mainboard's  sound card.
USB sound card become default to sink and source - that was expected.
But changing default sink was wiered:
- search "LXQt's default app to chage default sink" and like so did not help
- asking on oftc IRC #lxqt - nobody answered
- installing pasystray and indicator-sound-switcher did not help to change default sink.
- only terminal helped.

##### System Information
* Distribution & Version: I'm using Libuntu 20.04 with LXQt 0.14.1.
* Kernel: Linux i5 5.4.0-58-generic #64-Ubuntu SMP Wed Dec 9 08:16:25 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
* Qt Version: 5.12.8
* liblxqt Version: 0.14.1-0ubuntu2

**Comment by tsujan** [comment]
We have `pavucontrol-qt`. Making GUIs for all PulseAudio commands isn't LXQt's job.

Read https://www.freedesktop.org/wiki/Software/PulseAudio/FAQ/ and other freedesktop's documentations to know how to work with PulseAudio.

And please don't ask Ubuntu questions here. You can use Ubuntu forums.
