### ISSUE TITLE
Future of LXQt Qt5 support?

### ISSUE THREAD

**Issue by darkshram** [lxqt/lxqt#1902]
##### Expected Behavior
Currenty LXQt support Qt 5.12 and 5.15.

##### Current Behavior
Qt 5.15.2 is the latest stable Qt5 release, but reached EOL for non-paying users since December 7, 2020 (with Qt 6.0 release). There will be no more releases for the community version. Only paying customers of Qt will have 5.15 as LTS.
Qt 5.12 will have support until December 2021, which is almost a year with at least two more maintenance releases.
This means, Qt 5.12 is currently the only supported Qt5 branch for community users.

##### Context
I'm the maintainer of Qt, KDE and LXQt packages for my Linux distribution (ALDOS, a very small distro focused on Latin America users). We have been trying to decide between keeping Qt 5.12 (LTS) or to upgrade to Qt 5.15.2 (as requested by a _few_ users). But since Qt 5.15 is now EOL, our best judgement says to stay as long as possible with Qt 5.12.x, unless something really important requires Qt >= 5.15. For us, this means KDE Plasma (5.18 LTS, which requires Qt 5.12) and LXQt. Both DE are not default in the current ISO releases, but both are supported options. For us, LXQt is a popular choice for netbook users and low end systems.

So, basically I'm asking LXQt developers about future plans for LXQt, concerning the future Qt 5.x support status, so I can have a wider view and try to figure out what's the best thing to do for my Linux distribution. I already have prepared Qt 5.15.2 packages (on hold until a final decision) and currently working on Qt6 packages (nothing will require it yet, until [the next KDE Plasma LTS release which will be Qt6 based](https://community.kde.org/Schedules/Plasma_5#LTS_releases)).

I imagine next LXQt release will be around mid 2021. Will it keep supporting Qt 5.12.x? Will it require Qt 5.15 or will do the jump to Qt 6.x?

Thank you for reading. Hope you can give a good advice.

##### System Information
* Distribution & Version: ALDOS 1.4.15
* Kernel: 4.19.164
* Qt Version: Qt 5.12.10
* liblxqt Version: 0.16.0
* Package version: 0.16.x

**Comment by tsujan** [comment]
To make LXQt ready for Qt6, we need to remove and replace the methods that has become obsolete/deprecated in Qt5.15. No decision has been made about Qt5.12 yet but I don't think it could be supported by 0.17.

BTW, please ask your questions in the Discussions section, not as issues. For now, the "Convert to discussion" button has disappeared; this page should be converted when it comes back.

**Comment by tsujan** [comment]
LXQt 0.17 will be released in April and, apparently, Qt 5.12.5 will be supported.

Also, see https://github.com/lxqt/lxqt/discussions/1901
