### ISSUE TITLE
On Gentoo: do not start apps after connection to WiFi

### ISSUE THREAD

**Issue by vitaly-zdanevich** [lxqt/lxqt#1912]
I recorded it: https://youtu.be/rc4aZpC8Sp4

* LXQt version: 0.16.0
* Qt Version: 5.15.2
* liblxqt Version: 0.16.0

[Kernel 5.4.92](https://gitlab.com/vitaly-zdanevich-configs/linux-kernel-easynote-te69bm/-/blob/cd58cb99030b32c9f14a8a9926f53a721ca30ff6/.config)

**Comment by tsujan** [comment]
LXQt doesn't control network. Your problem is caused elsewhere. See https://github.com/lxqt/lxqt for the list of official LXQt components.

BTW, please use words to describe problems as clearly as possible. Videos and screenshots are good only as supplements, not as substitutes.

**Comment by vitaly-zdanevich** [comment]
But this is not about the network - this is about the issue that I cannot start apps.

**Comment by Chiitoo** [comment]
That does seem pretty funky.  I don't have wireless hardware to test things with, but what I would first try, is switch to the tty you run 'startx' in, and see if there are any messages regarding the applications trying to launch there (maybe check 'dmesg' too).

**Comment by vitaly-zdanevich** [comment]
Nothing in `dmesg` about it. `tty` is taken by X so I cannot read it.

**Comment by vitaly-zdanevich** [comment]
Now I can start apps again when in `nm-applet` I enabled automatic connection.
