### ISSUE TITLE
qterminal does not start the project in Qt Creator

### ISSUE THREAD

**Issue by AlexanderZhirov** [lxqt/lxqt#1914]
I am using **Lubuntu 20.04.02**. After installing **Qt Creator 4.14.0** based on **Qt 5.15.2**, I create a C ++ project with terminal support. In the default settings, there is one single **qterminal**. The project is built without errors. When starting the project, an error appears that the terminal cannot find the path:
`Cannot change to working directory '... my project path ... ': file or directory not found`
This is a similar problem from [before](https://stackoverflow.com/questions/24097221/qtcreator-returns-error-cannot-change-to-working-directory). There is a suggestion that this is due to PCMan. So I decided to write to the **lxqt** branch.

**Comment by tsujan** [comment]
How can this be QTermial's problem?!

**Comment by AlexanderZhirov** [comment]
Why not?

I installed XTerm and followed the same steps and the program started up.

I think you should pay attention to [this](https://forum.qt.io/topic/123557/cannot-change-to-working-directory-file-or-directory-not-found/3) problem:
> Shell program: "/opt/Qt/Tools/QtCreator/bin/../libexec/qtcreator/qtcreator_process_stub run /tmp/QtCreator.ZPtjNF/stub-socket **Для закрытия данного окна нажмите <ВВОД>...** /home/user/Programming/build-test-Desktop_Qt_5_15_2_GCC_64bit-Debug /tmp/QtCreator.kcxFmh 1130 /home/user/Programming/build-test-Desktop_Qt_5_15_2_GCC_64bit-Debug/test"

The highlighted message is displayed after the end of the program execution. There is a cliff somewhere in QTerminal. Here's the [proof](https://imgur.com/e4Bq0sg.png).
