### ISSUE TITLE
Problem with kbindicator

### ISSUE THREAD

**Issue by alex-theoto** [lxqt/lxqt#1917]
##### Current Behavior

When you use plugin-kbindicator on lxqt-panel, systemd's journal is flooded with errors
'QString::arg: Argument missing: true, us'
Even if you change your keyboard layout, similar errors appear. 
##### Possible Solution

Maybe there is a wrong configuration on 'Flags path pattern' 
##### Steps to Reproduce (for bugs)

1. Add keyboard state indicator. 
2. check your journalctl and you'll see it is flooded with errors related on kbindicator
##### System Information

* Distribution & Version: Fedora 33
* Kernel: 5.10.12
* Qt Version: 5.15.2
* liblxqt Version: 0.15.0
* Package version: 0.15.0-2

**Comment by stefonarch** [comment]
Cannot reproduce here both  on arch and debian, one using flags.

**Comment by tsujan** [comment]
Has never happened here either.

**Comment by tsujan** [comment]
And outdated LXQt versions aren't supported.

**Comment by stefonarch** [comment]
Checked un Lubuntu with 0.15, no messages too the `true` I see. Maybe check your settings.
![Uploading schermata-13-14-10.png…]()
