### ISSUE TITLE
Font renderer ugly in NetBeans with LXQT

### ISSUE THREAD

**Issue by kalilc** [lxqt/lxqt#1922]
Font rendering inside the program is really bad when using LXQT system. First we thought it was an old PC with Lubuntu, then somebody tried LXQT on Ubuntu 20.04 (another PC) and the problem came back. Then somebody with Linux Mint tested LXQT too, and we confirmed.

##### Expected Behavior

Normal/Default font rendering.

##### Current Behavior

Font renderer really ugly, can't work into the software. Eyestrain if you stare too much at it.

##### Possible Solution

Still haven't found out.

##### Steps to Reproduce (for bugs)

1.  Install NetBeans 12 or later
2. If not using LXQT, logout and change to it
3. Open NetBeans and create/load a .java file
4. See the text inside the program 

##### Context

We tried installing Lubuntu to have more resources on our old hardware, and the issue was then a problem, because NetBeans is our primary development environment, the system must be capable of running this IDE flawlessly and without any tweaks. 

##### System Information

* Distribution & Version: Last lubuntu LTS, Ubuntu 20.04, Mint (last LTS)
* Kernel: multiple
* Qt Version: last (installed/updated with apt)
* liblxqt Version: last (installed/updated with apt)
* Package version: last (installed/updated with apt)

**Comment by tsujan** [comment]
> Install NetBeans 12 or later

This isn't what "Steps to Reproduce" is about. You may want to report it to Ubuntu.

**Comment by wxl** [comment]
Also, if NetBeans is the only affected piece of software, one could argue the place to report it is actually with NetBeans.

**Comment by tsujan** [comment]
> Also, if NetBeans is the only affected...

Right.

I just meant "installing Arch/Fedora/Ubuntu..." isn't a way of reproducing anything.

**Comment by kalilc** [comment]
I thought since the problem happens with that software in this system, it could be worth to fix on system level. I can't blame a software that works for over 15 years in all other window system, i will blame the system.

Ubuntu default window manager works, other window managers works too, its LXQT problem.

**Comment by kalilc** [comment]
but im sorry for reporting the wrong way. whatever

**Comment by wxl** [comment]
> I can't blame a software that works for over 15 years in all other window system

Oh? What other systems did you test besides GNOME and LXQt?

**Comment by tsujan** [comment]
> I can't blame a software that works for over 15 years in all other window system, i will blame the system.

We don't work with "blames" here. Real bug reports are appreciated.

**Comment by kalilc** [comment]
> > I can't blame a software that works for over 15 years in all other window system
> 
> Oh? What other systems did you test besides GNOME and LXQt?

You name it, we have multiple distros in 100+ computers, using NetBeans since 2004... I couldn't name them all. 




> > I can't blame a software that works for over 15 years in all other window system, i will blame the system.
> 
> We don't work with "blames" here. Real bug reports are appreciated.


Why u fucks have to be so salty? Its not real blame, just saying the way I think, not trying to be aggressive. I lost all this time wroting this shit, its my first time trying to report something. but thanks for the waste of time, a-holes.

**Comment by wxl** [comment]
If this is your first time trying to report something, you should know that asking questions and clarifying is a common response. It's not saltiness. 

Using LXQt regularly and having no problems with font rendering, it's hard to believe that NetBeans misbehaving is LXQt's fault. I mean, Occam's Razor applies here. 

I'm sure if you had a little patience and willingness to actually invest time exploring this, you might actually get to the bottom of it.
