### ISSUE TITLE
About LXQt Homepage has Invalid URL

### ISSUE THREAD

**Issue by MattEding** [lxqt/lxqt#1926]
##### Expected Behavior

Open webpage to working website:
https://lxqt-project.org/

##### Current Behavior

The About LXQt dialog states:
Homepage: https://lxqt.org
Which is an invalid url.

##### Steps to Reproduce (for bugs)

1. Start Menu
2. About LXQt
3. Click url
4. 

##### System Information

LXQt Desktop Toolbox - Technical Info<p>
  LXQt About Version:     0.14.1
  LXQt Version:           0.14.1
  Qt:                     5.12.8
  Build type:             Release
  System Configuration:   /etc/xdg
  Share Directory:        /usr/share/lxqt
  Translations:           /usr/share/Lubuntu/lxqt/translations<br>
/usr/local/share/lxqt/translations<br>
/usr/share/lxqt/translations<br>
/var/lib/snapd/desktop/lxqt/translations

**Comment by tsujan** [comment]
→ https://github.com/lxqt/lxqt/releases

**Comment by stefonarch** [comment]
The (long) story is here https://github.com/lxqt/lxqt/issues/1829

**Comment by MattEding** [comment]
I guess I did not do my due diligence in researching the matter ahead of time, sorry about that. I had just assumed that my Lubuntu distro that I downloaded the other week would have had the most recent version.

**Comment by wxl** [comment]
@MattEding in general, I would not assume that out of any stable distribution. Really the only distros guaranteed to give you the absolute latest software are rolling distros. 

That said, if you've got issues with Lubuntu, I'd urge you to file bugs in Launchpad. We can always triage things upstream if they are indeed issues that aren't already fixed. `ubuntu-bug` is your friend.
