### ISSUE TITLE
[Important] Add new language

### ISSUE THREAD

**Issue by Aikatsui** [lxqt/lxqt#1930]
This is request to add "Sinhala" language to all LXQt projects and components listed on https://translate.lxqt-project.org/projects/

LXQt Desktop	
LXQt Configuration	
Andrew Bibb	
Tsujan	
zjes			
LXQt Panel

There're many components on each projects then make sure to enable the language for all otherwise it's annoying to inform again and again.

**Comment by stefonarch** [comment]
Languages can be added after request for permissions:
https://github.com/lxqt/lxqt/discussions/1876#discussioncomment-179032
I need to know your username.
