### ISSUE TITLE
Touchpad settings lost in Debain LXQt after suspend or hibernate

### ISSUE THREAD

**Issue by psilospiral** [lxqt/lxqt#1931]
##### Expected Behavior

Settings found in Application menu>Preferences>LXQt settings>Keyboard and Mouse>Mouse and Touchpad> should remain as selected after a machine suspend or hibernate resumes. (After waking up.)
##### Current Behavior

After settings in the Mouse and Touchpad area are set by the user (such as CHECKING 'Single click to activate items' or 'Natural scrolling') they revert to UNCHECKED after the system is placed into Suspend or Hibernate and then resumed to normal operational state.
##### Possible Solution

Ensure Mouse and Touchpad settings are preserved properly after a resume from Suspend or Hibernate.
##### Steps to Reproduce (for bugs)

1. CHECK 'Single click to activate items' in Application menu>Preferences>LXQt settings>Keyboard and Mouse>Mouse and Touchpad>
2. CHECK 'Natural scrolling' in the same menu box
3. Suspend or Hibernate the machine
4. Resume the machine
5. Notice 'Single click to activate items' and 'Natural scrolling' are now UNCHECKED.
##### Context

I have avoided Suspending or Hibernating my machine due to the need to use the mouse mechanical left/right click buttons to navigate the menu structure to change the settings back to 'Single click to activate items'.  I also have begun to close all applications and shutdown the machine instead of just quickly closing the lid, due to the need to adjust these settings every time I resume from a suspend/hibernate state.
##### System Information

* Distribution & Version: Debian 10 Buster
* Kernel: uname -r
4.19.0-14-amd64
* Qt Version: qmake --version
QMake version 3.1
Using Qt version 5.11.3 in /usr/lib/x86_64-linux-gnu
* liblxqt Version: 
* Package version:

**Comment by tsujan** [comment]
Not reproducible.

You left liblxqt/pckage version empty.

**Comment by psilospiral** [comment]
Would you please provide the command to retrieve this information?

**Comment by tsujan** [comment]
You could check your distro package manager.

[Debian Buster's LXQt](https://packages.debian.org/buster/lxqt-about) is ancient and not supported.

**Comment by psilospiral** [comment]
zcat /usr/share/doc/liblxqt0/changelog.Debian.gz
liblxqt0 - 0.14.1-1

**Comment by stefonarch** [comment]
I was using buster 32bit until some months ago, always hibernated and often suspended - never saw that issue.
I suspect an issue in your home directory, you could create a new userjust  to check.

**Comment by psilospiral** [comment]
stefonarch - thank you for your input.  Yesterday I performed a fresh install of the amd64 debian 11 bullseye weekly build net-install on the same machine - and experienced the same bug in the LXQt environment.  However, this time the 'Tap to click' and 'Natural scrolling' tick boxes would only uncheck after a Suspend - not a Hibernate...?!  Unfortunately, it is not 100% repeatable.  I also use an external bluetooth mouse and thought I found a situation that would make it repeatable related to suspend/hibernate when the mouse is connected (or not connected) - but have not been able to reproduce the issue consistently.  I'll keep taking notes/experimenting.  Something is causing this even with a fresh install - occasionally.    

tsujan - FWIW - debian bullseye is running 0.16.0 and I still experienced this issue.  I'll try to find a way to make this bug 100% repeatable and report back.

**Comment by tsujan** [comment]
@psilospiral 
I suspend this laptop on a regular basis (I shut it down only once in 2 weeks or so) and have never encountered any issue. But who knows? Bugs are always possible. We would appreciate it if you could give us a way of reproducing the issue. Then, this report will be reopened.

**Comment by psilospiral** [comment]
Thank you tsujan.  I am trying to determine exactly how to reproduce this issue consistently.  I'm also experimenting with a couple other physical machines I have laying around...
