### ISSUE TITLE
Crash of Gimp on Lubuntu with LXQT (looks like the only LXQT issue)

### ISSUE THREAD

**Issue by jarom256** [lxqt/lxqt#1932]
##### Current Behavior

When I start gimp, open an image, select an area on it, and I will use Ctrl+C, the Gimp will crash. I tried more gimp's versions (= the same behaviour), and more desktop environment (= no problem). When I run gimp from console, this is the output after the crash:

gimp_check_updates_callback: loading of https://www.gimp.org/gimp_versions.json failed: Operation not supported
The program 'gimp' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadWindow'.
  (Details: serial 66328 error_code 3 request_code 18 minor_code 0)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the --sync command line
   option to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)

(script-fu:5691): LibGimpBase-WARNING **: 11:20:25.665: script-fu: gimp_wire_read(): error

##### Steps to Reproduce (for bugs)

1. 
2. 
3. 
4. 

##### System Information

* Distribution & Version: Ubuntu 20.04.2 LTS \n \l
* Kernel: 5.4.0-66-generic
* Qt Version: 5.12.8+dfsg-0ubuntu1
* liblxqt Version: 0.14.3-1ubuntu2
* Package version: GIMP 2.10.22

**Comment by palinek** [comment]
See here pvanek/qlipper#108

**Comment by stefonarch** [comment]
Wow, I always wondered why it crashed here on arch, so I'm wiser now.
