### ISSUE TITLE
lxqt-sudo does not start backintime as root

### ISSUE THREAD

**Issue by mib-2020** [lxqt/lxqt#1936]
##### Expected Behavior
I am trying to run backintime under lubuntu 20.04 as root. I get the authentication dialog from lxqt-sudo and enter my password. 
backintime starts and I can backup my files.

##### Current Behavior
![lxqt-sudo](https://user-images.githubusercontent.com/60042105/110206709-a76fcb00-7e7f-11eb-94b1-a7bdfa189143.png)
After entering my password, nothing happens. I do not get any error message.

##### Possible Solution
-

##### Steps to Reproduce (for bugs)
-

##### Context
- Starting backintime as non-root works as expected.
- Starting featherpad from terminal "lxqt-sudo featherpad":
```
(0x7ffc606970d0) Warning: Icon theme "elementary" not found.
(0x7ffc606970d0) Warning: QXcbConnection: XCB error: 148 (Unknown), sequence: 186, resource id: 0, major code: 140 (Unknown), minor code: 20    
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
qt.qpa.xcb: QXcbConnection: XCB error: 148 (Unknown), sequence: 186, resource id: 0, major code: 140 (Unknown), minor code: 20
```
but works as expected.
- Starting plasma-discover or muon works as well

- Starting backintime from terminal "lxqt-sudo backintime":
```
(0x7ffc7ef68bc0) Warning: Icon theme "elementary" not found.
(0x7ffc7ef68bc0) Warning: QXcbConnection: XCB error: 148 (Unknown), sequence: 186, resource id: 0, major code: 140 (Unknown), minor code: 20             

Back In Time
Version: 1.2.1

Back In Time comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions; type `backintime --license' for details.
```

- Same behavior with "lxqt-sudo timeshift"

##### System Information
* Distribution & Version: Lubuntu 20.04.2 LTS
* Kernel: 5.4.0-66-generic
* Qt Version: 5.12.8
* liblxqt Version: 0.14.1
* Package version: ?

**Comment by tsujan** [comment]
This isn't related to LXQt. Not all GUI apps work directly with `sudo` front-ends.

Try `lxsudo dbus-run-session -- YOUR_APP`

**Comment by palinek** [comment]
The screenshot pasted above is not lxqt-sudo's one.
