### ISSUE TITLE
LxQT fails to configure monitor layout correctly.

### ISSUE THREAD

**Issue by MetaPhaze** [lxqt/lxqt#1965]
I have 3 monitors, from left to right, the center monitor is my primary monitor... 
If you do the math, and all 3 monitors are running at 1920x1080, it should be easy to deduct with reasoning how the monitors are set up... yet... when I use the LxQt configuration tool for monitor setup...
|<- 0-1919 ->||<- 1920-3839 ->||<- 3840-5759 ->|
  secondary        primary                tertiary
however this is not what is happening... 
I can not tell LxQt how to arrange my monitors even though i'm using nvidia and my own hand written xorg.conf config file that has worked for lxde for 15 years.

this is what seems to be happening 

|<- 0-1919 ->||<- 1920-3839 ->||<- 3840 - 5759 ->||<- 5760-7679 ->|
   secondary     dead space          primary                     tertiary

##### Expected Behavior
1. 
2. 
1. it should let me configure my monitors more intelligently... instead of trying to assume things.
2. it should let me enter my screen coordinates manually instead of trying to guess them.. because obviously that's not working.

##### Current Behavior
1. 
2. 
3. 

1. the screens do not mesh together, instead there is a dead spot about 1920x1080 between my secondary and primary screens as listed above.
2. make a better interface for configuring the screen.
3. screenshots won't help, but a video might, if you want one, i'll post it.

##### Steps to Reproduce (for bugs)

1. 
2. 
3. 
4. 

##### System Information

* Distribution & Version: 
* Kernel: 
* Qt Version: 
* liblxqt Version: 
* Package version: 

Gentoo linux, it doesn't have a version... been using the same install since 2005.1
kernel Linux: maynard 5.4.97-gentoo-MetaPhaze-MAYNARD-64-KVM-VBOX-SPARSE-XZ-FBS #1 SMP PREEMPT Fri Mar 26 21:03:16 CDT 2021 x86_64 Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz GenuineIntel GNU/Linux
Qt Version: Installed versions:  5.15.2-r2
liblxqt Version: Installed versions:  0.16.0
Package version: Built-From-Source.

**Comment by MetaPhaze** [comment]
configuring the left monitor as -1920 (x) doesn't do anything

**Comment by tsujan** [comment]
> it should let me enter my screen coordinates manually

LXQt monitor settings allows entering the coordinates. Which version do you have?

**Comment by tsujan** [comment]
Frankly, I didn't understand what the problem was. If you have a "dead space", you could remove it and save the setting.

> screenshots won't help, but a video might, if you want one, i'll post it.

Yes.

**Comment by MetaPhaze** [comment]
remove this bug, not a bug... i overlooked the "set position" option confusing it for virtual displays... the "dead space" was because in the set position settings the monitor icons were pulled far apart.

**Comment by MetaPhaze** [comment]
this is a drastic improvement to the old lxde monitor settings

**Comment by tsujan** [comment]
OK. Closing.
