### ISSUE TITLE
Bad rendering in LXQt QEMU

### ISSUE THREAD

**Issue by antonialoytorrens** [lxqt/lxqt#1971]
##### Expected Behavior

LXQt should be correctly displayed in QEMU.

##### Current Behavior

LXQt (panel and applications) is not correctly displayed in QEMU.

##### Steps to Reproduce (for bugs)

1. Run LXQt with QEMU emulation
2. Watch this video: [Click Here](https://gitlab.com/postmarketOS/pmaports/uploads/35c3cc4ad780a6ec22afad58c67a7783/lxqt-bug-qemu.mp4)
- Note that this cannot be reproduced on real hardware.

##### System Information

* Distribution & Version: Alpine Linux Edge
* Kernel: 5.10.28
* Qt Version: 5.15.3
* liblxqt Version: 0.16.0

**Comment by tsujan** [comment]
Not related to LXQt.

**Comment by antonialoytorrens** [comment]
Okay, thank you!

**Comment by palinek** [comment]
@antonialoytorrens You probably feel by yourself, that this issue is completely out of scope of LXQt. lxqt-panel is just an Qt app and doesn't do any specific rendering by itself. You probably need to go further to Qt, xcb, drivers...etc. to bisect your problem.

**Comment by antonialoytorrens** [comment]
I see. Thank you very much for the info @palinek . I appreciate it!
