### ISSUE TITLE
lxqt-panel task manager (taskbar) window grouping problem

### ISSUE THREAD

**Issue by renegat73** [lxqt/lxqt#1973]
Since latest updates:

qt5-base (5.15.2-5 -> 5.15.2+kde+r171-3)
qt5-declarative (5.15.2-1 -> 5.15.2+kde+r24-1)
qt5-svg (5.15.2-2 -> 5.15.2+kde+r5-1)
qt5-wayland (5.15.2-1 -> 5.15.2+kde+r11-1)

the lxqt-panels (0.16.1-1) task-manager (taskbar) does not work properly anymore:

Steps to reproduce:

With 'window grouping' enabled in task manager settings:

- open multiple instances of one application (pcmanfm-qt e.g.) in lxqt - they will be grouped to one button in taskbar.
- left click on the group-button - a list with the applications instances will appear above the buttons in task manager
- now move mouse - the list will vanish instantly. You'll have no chance to click on one of the buttons in the pop-up list making it impossible to access a particular instance of the app. 

Downgrading the qt5 packages mentioned above solves the issue for the moment.

##### Expected Behavior
You should be able to move the mouse pointer over the pop-up windows group list in taskbar.

##### Current Behavior
The grouped window pop-up vanishes as soon as you move the mouse. 
You cannot reach the widow group list!

##### Possible Solution
Till now only downgrading qt5 packages to previous versions

##### Steps to Reproduce (for bugs)

1. open multiple instances of one application (pcmanfm-qt e.g.) in lxqt - they will be grouped to one button in taskbar.
2. left click on the group-button - a list with the applications instances will appear above the buttons in task manager
3. now move mouse - the list will vanish instantly. You'll have no chance to click on one of the buttons in the pop-up list making it impossible to access a particular instance of the app. 

##### Context

When having multiple pcmanfm-qt instances open and you want to switch from one to another you'll need this windows group pop-up accessible.
At the moment only [alt]+[tab] works for this task.

##### System Information

* Distribution & Version: Arch Linux
* Kernel:  5.11.12-arch1-1 #1 SMP PREEMPT Wed, 07 Apr 2021 21:48:28 +0000 x86_64 GNU/Linux
* Qt Version: qt5 5.15.2+kde+r171-3
* liblxqt Version:  0.16.0-1
* Package version: ?

**Comment by tsujan** [comment]
→ https://github.com/lxqt/lxqt-panel/issues/1600
