### ISSUE TITLE
lxqt-runner FTBFS with menu-cache since 0.15.0

### ISSUE THREAD

**Issue by chris2553** [lxqt/lxqt#1975]
##### Expected Behavior
cmake should run successfully when building lxqt-runner

##### Current Behavior
A typo in CMakeLists.txt causes cmake to fail like this:
...
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Building with Qt5.15.2
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.2") 
CMake Error at CMakeLists.txt:60 (find_package):
  find_package called with invalid argument "$(LIBMENUCACHE_MINIMUM_VERSION}"
...

##### Possible Solution
This patch fixes it:

    --- lxqt-runner-0.15.0/CMakeLists.txt.orig      2020-04-26 19:07:53.314484777 +0100
    +++ lxqt-runner-0.15.0/CMakeLists.txt   2020-04-26 19:08:18.078485774 +0100
    @@ -57,7 +57,7 @@ endif ()
     
     if (USE_MENU_CACHE)
        # optionally use libmenu-cache from lxde to generate the application menu
    -    find_package(MenuCache "$(LIBMENUCACHE_MINIMUM_VERSION}" REQUIRED)
    +    find_package(MenuCache "${LIBMENUCACHE_MINIMUM_VERSION}" REQUIRED)
    endif()
     
     if (RUNNER_MATH)

##### Steps to Reproduce (for bugs)
1.  unpack the tarball
2. cd lxqt-runner-0.nn.0
3. mkdir build
4. cd build
5. cmake  -DUSE_MENU_CACHE=ON ..

##### Context
Without the patch above, lxqt-runner FTBFS at version 0.15.0, 0.16.0 and 0.17.0.  AS the file names in the patch above show, I discovered the problem when building 0.15.0. I meant to send the patch then, but forgot. Ditto 0.16.0. I built 0.17.0 yesterday a year after I made the patch, I've remembered to send it. Hoorah!

##### System Information
* Distribution & Version:  Linux From Scratch
* Kernel: 5.11.14
* Qt Version: 5.15.2
* liblxqt Version: 0.1{5,6,7}.0
* Package version: 0.1{5,6,7}.0

**Comment by tsujan** [comment]
menu-cache is not recommended. Sooner or later, it'll be removed from LXQt.

**Comment by luis-pereira** [comment]
Fixing it.
@tsujan That's why we didn't bump into it.
