### ISSUE TITLE
midnight commander under lxqt ugly color schema

### ISSUE THREAD

**Issue by jpVm5jYYRE1VIKL** [lxqt/lxqt#1976]
it is feels like that midnight commander under QTerminal almost unusable due to weird default color schema

##### Expected Behavior

It have to be better contrast colors

##### Current Behavior

Same midnight commander on same pc with different terminal appliations : 
Left part is QTerminal. Right part konsole from kde.
![mcissue](https://user-images.githubusercontent.com/22169129/115106563-d771ba00-9f65-11eb-81fe-768123dd3021.png)
Screenshot which illustrate that not only hidden (. leading) files affected with issue:
![mcissue](https://user-images.githubusercontent.com/22169129/115106704-962dda00-9f66-11eb-9542-4d343e41c44f.png)

##### Steps to Reproduce (for bugs)

1.  install Konsole
2.  install QTerminal
3.  switch on both to green on black schema
4. start mc in Konsole and QTerminal
5.  feel difference

##### Context

Issue block usage of midnight commander under QTerminal

##### System Information

* Qt Version: 5.14.2
* liblxqt Version: 0.15.0
* Package version:

**Comment by stefonarch** [comment]
Version of qterminal? liblxqt 0.15.0 is far old.
Just trying here, not any issue with my configuration.

![schermata-10-34-35](https://user-images.githubusercontent.com/10681413/115107041-c1b1c400-9f68-11eb-901d-b903a3c5d702.png)

**Comment by jpVm5jYYRE1VIKL** [comment]
Issue on green on black

**Comment by tsujan** [comment]
Not reproducible here either.
