### ISSUE TITLE
Is there a volume level popup similar to Gnome's Better OSD?

### ISSUE THREAD

**Issue by Raytle** [lxqt/lxqt#1978]
In other words, is there something like [Better OSD](https://extensions.gnome.org/extension/1345/better-osd/) for LXQt?

I noticed [Best volume OSD for Lubuntu](https://askubuntu.com/questions/1004276/best-volume-osd-for-lubuntu) had no responses.

##### System Information
* Lubuntu 20.04 LTS

**Comment by tsujan** [comment]
No.

Please use [Discussions](https://github.com/lxqt/lxqt/discussions) → Q&A if you have questions.
