### ISSUE TITLE
Inability to place panel in desired place on screen

### ISSUE THREAD

**Issue by enzedrailmaps** [lxqt/lxqt#1983]
##### Current Behavior

I had LXQT as the desktop environment for Debian Buster. In this version for my computer with 2 monitors I was able to create two panels at the top and bottom of one of the monitors only, a standard arrangement I use on my KDE computer to enable the second screen to be used at "full screen" all the time, with no panels displayed on it. There were problems with the right click menu not working after the panel at the top of the first monitor was created, but settings could be changed by editing the panel.conf file as a workaround.

In the latest version of LXQt supplied with Debian Bullseye, this bug has been "fixed" by preventing a panel from being placed at the top of the first monitor in a two monitor setup. It can only be placed at the bottom of the first monitor or the top, left or right of the second monitor. I disagree that the way to resolve this bug is to remove support for this configuration.

##### Possible Solution

Fix the bug properly instead of choosing not to support a panel configuration option that worked in previous versions of LXQt and is supported in other common windowing environments

##### Steps to Reproduce (for bugs)

1. Right click any panel 
2. The only options now available for positioning the panel are bottom of desktop 1 or top left right of desktop 2. All other positioning options have been removed from the menu.
3. The previously used panel config file is still being used but the software has obviously redefined the way it interprets the settings in the file so that panels will not be placed in the positions they were under the previous version i.e. a panel at the bottom and a panel at the top of the first screen, instead there will be by default a panel at the bottom of screen 1 and a panel at the top of screen 2.
4

##### Context
                       --->

##### System Information

* Distribution & Version: Debian Bullseye pre release (as at 2021-04-17)
* Kernel: 5.10
* Qt Version: 5.15
* liblxqt Version: 0.16.0-1
* Package version:

**Comment by tsujan** [comment]
Panels can't be positions between screens. That's by design and prevents nasty problems with different kinds of WMs.

> I disagree that the way to resolve this bug is to remove support for this configuration.

If you have another working solution, please make a PR.

**Comment by tsujan** [comment]
There were many problems and we had a hard time to find a working solution for all of them. An alternative solution would be appreciated if it does the same thing but in a better way.
