### ISSUE TITLE
midnight commander under lxqt 0.16 ugly color schema 

### ISSUE THREAD

**Issue by jpVm5jYYRE1VIKL** [lxqt/lxqt#1984]
Today was release new ubuntu 21.04 which include lxqt 0.16
Issue same as #1976 but now on 0.16 lxqt. 
##### Expected Behavior

Normal colors using midnight commander with green ob black color schema.

##### Current Behavior

Ugly color schema:
Left qterminal included in lxqt . Right Konsole from kde. Both of them using green on black schema.

![lxqt0 16](https://user-images.githubusercontent.com/22169129/115831393-d0d5bd80-a411-11eb-8322-4c48dfe267ae.png)

##### Possible Solution

Not solvable

##### Steps to Reproduce (for bugs)

    install Konsole
    install QTerminal
    switch on both to green on black schema
    start mc in Konsole and QTerminal
    feel difference

##### System Information

* Distribution & Version: 
Distributor ID: Ubuntu
Description:    Ubuntu 21.04
Release:        21.04
Codename:       hirsute

* Kernel:  5.11.0-16-generic
LXQt About Version | 0.16.0
LXQt Version | 0.16.0
Qt | 5.15.2
Build type | Release

* Package version:

**Comment by palinek** [comment]
Please, report the problem downstream -> Ubuntu. Choosing the default color scheme is distribution specific decision.

**Comment by tsujan** [comment]
> Today was release new ubuntu 21.04 which include lxqt 0.16

LXQt 0.16 is outdated.
