### ISSUE TITLE
How can I cause "When Idle then: Lockscreen [or Suspend]" to run a script of mine?

### ISSUE THREAD

**Issue by Raytle** [lxqt/lxqt#1995]
I am running **Lubuntu 20.04 LTS**

This issue seems similar to issue #919

I uninstalled `xdg-screensaver.` (The 1990's called. They want Jamie Zawinski's hideous looking screensaver back where it belongs: running alongside Netscape Navigator 4.08, the browser all the kool kids used to use).

To manually **suspend** my computer I run the following script...

```
i3lock -u -i /home/y/Pictures/01-Wallpaper.png &
sleep 4 &&
xtrlock &
sleep 2 &&
systemctl suspend

```

To manually **lock my screen** I run the following script...

i3lock -u -i /home/y/Pictures/02-Wallpaper.png &

sleep 4 &&
xtrlock &
sleep 2 &&
xset dpms force off

I would like either of the above scripts to run automatically when I choose...

LXQt Settings –> Power Management –> Idle–> When Idle then: Lockscreen

or

LXQt Settings –> Power Management –> Idle–> When Idle then: Suspend

How can I do this?

**Comment by Raytle** [comment]
Why did you close it?

**Comment by stefonarch** [comment]
Stumpled upon it, for the record: it can be done like this:
https://github.com/lxqt/lxqt/wiki/ConfigScreensavers#other-screenlockers-using-xautolock
