### ISSUE TITLE
Manjaro (arch) package "pkgconf" should be added to wiki page "Building from source"

### ISSUE THREAD

**Issue by selairi** [lxqt/lxqt#1998]
In "Building from source" wiki page:

[https://github.com/lxqt/lxqt/wiki/Building-from-source](https://github.com/lxqt/lxqt/wiki/Building-from-source)

If you try to compile LXQt in Manjaro (Arch based), the pkgconf package have to be intalled. Then instead:

`pacman --needed -S qt5-base qt5-svg qt5-tools qt5-x11extras`

shoul be:

`pacman --needed -S qt5-base qt5-svg qt5-tools qt5-x11extras pkgconf`

**Comment by stefonarch** [comment]
Thanks, done [here](https://github.com/lxqt/lxqt/wiki/Building-from-source#arch-linux) 
(and bumped minimal qt version required to 5.15)
