### ISSUE TITLE
A problem with lxqt-config-monitor

### ISSUE THREAD

**Issue by kogeke** [lxqt/lxqt#2001]
Hello.

I have a problem with connecting TV to my laptop with HDMI cable. If i start laptop first, then plug cable - no matters what i change in lxqt-config-monitor - all that I see on TV is black screen and when i move there cursor artifacts appear, also after doing something in lxqt-config-monitor i get screen tearing. Other way if I power on TV and plug it first then power on laptop - everything is fine, i have image on both screens and no tearing, but i cant change settings (desktop expands to right to TV, but i need to left).

Laptop lenovo IdeaPad z460 (1366x768, near 60Hz), nouveau driver, openbox VM, picom to beat screen tearing
TV Sony KDL-32R303C (1360x768, near 60Hz)
Arch, lxqt 0.17.0

**Comment by tsujan** [comment]
`lxqt-config-monitor` doesn't draw the screen. Check your driver and/or WM/compositor.

**Comment by kogeke** [comment]
Driver works correctly, as i can understand. Enabling/disabling picom does not have an effect. 
Wich way should i look? If i use same configuration on xfce, plasma, etc. its monitor settings app wors correctly.

**Comment by kogeke** [comment]
And why everythig is ok when i start laptop connected to TV?

**Comment by tsujan** [comment]
I don't know.

What I know is that (1) nouveau isn't as good as nvidia, although nvidia has problems too, and (2) openbox has bad multi-screen bugs that won't be fixed because it isn't developed anymore.

So, if you have Plasma, you could use KWin under LXQt, after disabling picom.

**Comment by kogeke** [comment]
Thatks for answer. Currently i use minimal installation with arch/lightdm/lxqt, i don't want use nvidia drivers, coz i had problems with it (geforce 310m) in past.

So you think, i can try switch to another WM?
What should i do with nouveau?

**Comment by tsujan** [comment]
If I were you, I kept nouveau and used KWin instead of openbox+picom.

When testing multi-screen, I tried Openbox a few times and it showed weird problems that didn't happen with KWin.

**Comment by kogeke** [comment]
I will try in the evening and reply.

**Comment by tsujan** [comment]
There's also another difference between your multi-screen and mine: I use Intel with kernel modesetting (no Intel driver).

I have nvidia too (with prime) but I never use it.

**Comment by kogeke** [comment]
Problem found. It's picom, removed it from autostart and now there are no problems on working laptop and TV and when power on.
Maybe will try play with settings of picom.
Thank you for advices.
