### ISSUE TITLE
Allow to switch to KDE filepicker as default.

### ISSUE THREAD

**Issue by ca3games** [lxqt/lxqt#2008]
##### Expected Behavior
Use KDE filepicker by default.

##### Current Behavior
Current LXQT file picker lacks thumbnails.

##### Possible Solution
Use KDE filepicker by default, or allow to set the KDE filepicker as default.

##### Steps to Reproduce (for bugs)
LXQT filepicker doesn't have thumbnails and I need to use lots of pictures with random filenames and is timeconsuming to simply select every filepath by each one in sequence to check the big thumbnail.

##### Context
Gnome filepicker is unusable without thumbnails and the gnome devs refuse to implement a 2004 issue about this.

##### System Information
Lubuntu 20.04

**Comment by stefonarch** [comment]
Options in "Add file dialog" using Falkon:
![schermata-25-5-9:14-01](https://user-images.githubusercontent.com/10681413/119455369-d3417500-bd39-11eb-95b0-cd5ac655566e.png)

Apps like firefox or thunderbird doesn't use native LXQt filepicker.
