### ISSUE TITLE
Missing menu client-list-combined-menu in LXQt 0.17.0

### ISSUE THREAD

**Issue by r-pf** [lxqt/lxqt#2009]
##### Expected Behavior

When adding the following XML-Element 
```xml
    <keybind key="W-Tab">
      <action name="ShowMenu">
        <menu>client-list-combined-menu</menu>
      </action>
    </keybind>
```
into `~/.config/openbox/lxqt-rc.xml` using LXQt 0.16.0 a menu like the following appears when pressing Windows+Tab
![grafik](https://user-images.githubusercontent.com/32121452/119724077-86ab8600-be6e-11eb-8ec6-ae06c4fb4a8e.png)

The menu shows all opened windows per Desktop.

##### Current Behavior

After update of my ArchLinux-Installation via `pacman -Syu` I have LXQt 0.17.0 and no menu like the one mentioned above appears when pressing Windows+Tab.

##### Steps to Reproduce (for bugs)

1. Add the following XML-Element 
```xml
    <keybind key="W-Tab">
      <action name="ShowMenu">
        <menu>client-list-combined-menu</menu>
      </action>
    </keybind>
```
into `~/.config/openbox/lxqt-rc.xml` 
2. Restart sysem or X to make sure the change above will be used
3. Press key-combination Windows+Tab
4. Works with LXQt 0.16.0, but not with newer LXQt 0.17.0

##### Context

The `client-list-combined-menu` helps me to get an overview of openend windows.
It also makes it easier to jump from one window of an desktop to an other window of an other desktop.

##### System Information

* Distribution & Version: ArchLinux, LXQt 0.17.0
* Kernel: Linux myHost 5.12.5-arch1-1 #1 SMP PREEMPT Wed, 19 May 2021 10:32:40 +0000 x86_64 GNU/Linux
* Qt Version: LXQt 0.17.0
* liblxqt Version: `pacman -Ss liblxqt` => community/liblxqt 0.17.0-1 [installed]
* Package version:

**Comment by tsujan** [comment]
We don't ship an openbox config anymore.

**Comment by r-pf** [comment]
Is there an alternative way which provides the information and possibility to swap the active window like `client-list-combined-menu` has done?

**Comment by tsujan** [comment]
Use Openbox's original config file. `lxqt-rc.xml` has no effect.

**Comment by r-pf** [comment]
@tsujan Thanks for your hint.
Using 
`~/.config/openbox/rc.xml` instead of 
`~/.config/openbox/lxqt-rc.xml` (which works fine with LXQt 0.16.0) solves my problem for LXQt 0.17.0.

The file `~/.config/openbox/rc.xml` appears after making a modification via menu Preferences ‣ LXQt settings ‣ Openbox Settings.

**Comment by tsujan** [comment]
> Using ~/.config/openbox/rc.xml instead of ~/.config/openbox/lxqt-rc.xml...

Exactly.

> The file ~/.config/openbox/rc.xml appears after making a modification via...

`obconf-qt` isn't developed anymore. The reason is twofold: Openbox isn't developed anymore (although it's quite usable) and (2) LXQt wants to remain WM-agnostic under X11.

I suggest you make changes to `~/.config/openbox/rc.xml` directly. Openbox has a comprehensive documentation.
