### ISSUE TITLE
Updating the wiki

### ISSUE THREAD

**Issue by iamthesenate1** [lxqt/lxqt#2014]
I have started to update the Binary Packages section of the wiki in my fork. As I couldn't make a PR (see #2013), I'm putting this here. 
I started making a table with the versions in all distros and deleteing Slackware (as it is heavily outdated).
Should I add the distros that are on the website too?
Anyway, here is the link: https://github.com/iamthesenate1/lxqt/wiki/Binary-packages.

**Comment by stefonarch** [comment]
Looks good to me, only debian and derivatives in the table need a 0.14/0.16 distinction as bullseye isn't released yet.

**Comment by stefonarch** [comment]
> Is the current version good to merge?

IMO ubuntu needs a separate row, as 0.17 will be in Ubuntu 21.10 
Debian maybe specify "bullseye" or "stable"?

**Comment by iamthesenate1** [comment]
Done!

**Comment by iamthesenate1** [comment]
?

**Comment by stefonarch** [comment]
I'd  change the building paragraph:

> If your distribution has an older package version, please do not report bugs on Github, but rather on their respective bug tracker. If you want the latest LXQt on such a distro you can build it using the scripts/instructions here. Note that for the latest git your distro must have Qt version ≤ 5.15. If your distro doesn't have that requirement, you can compile version 0.17.

Building instructions have already their own wiki page, so a link is enough, and the last phrase is not quite understandable (requirement _is_ qt 5.15 or higher and compiling is possible both for release and git checkouts.

The other things are ok, thanks!

**Comment by tsujan** [comment]
Also, things like "for the latest git your distro must have Qt version ≥ 5.15" change constantly (*and it should have been "≥", not "≤"*). Sooner or later, LXQt will need Qt ≥ 6.2.0.

**Comment by iamthesenate1** [comment]
I have simplified it quite a bit by pointing directly to the wiki article regarding the building from source.

**Comment by iamthesenate1** [comment]
I have now updated the wiki with these changes.
