### ISSUE TITLE
panel closes on hover to icon "Network Manager"

### ISSUE THREAD

**Issue by and-bulk** [lxqt/lxqt#2020]
OS: Arch linux
DE: lxqt

Auto hide set true

![image](https://user-images.githubusercontent.com/79831859/122753844-5a730180-d282-11eb-9898-27c59e97aab7.png)

panel closes on hover to icon "Network Manager", how can i fix that?

![image](https://user-images.githubusercontent.com/79831859/122753974-8db59080-d282-11eb-8f13-c0fe953212a0.png)

with other icons in panel, all works fine

**Comment by tsujan** [comment]
Don't use System Tray.
