### ISSUE TITLE
lxqt-rc.xml is not used by openbox again

### ISSUE THREAD

**Issue by renegat73** [lxqt/lxqt#2031]
openbox 3.6.1-7 
liblxqt 0.17.0-1
lxqt-session 0.17.1-1
ArchLinux 5.12.15-arch1-1 #1 SMP PREEMPT Wed, 07 Jul 2021 23:35:29 +0000 x86_64 GNU/Linux

I was running into trouble as suddenly all my keyboard shortcuts defined in openbox config file 'lxqt-rc.xml' were not working anymore.

I found that instead of the lxqt-rc.xml now the rc.xml configuration file of openbox is used again.

lxqt-rc.xml is ignored now, the native rc.xml is used.
Is this intended now?

There was an [identical issue](https://github.com/lxqt/lxqt/issues/1161) also reported by me some years ago wich was caused due to different versions in an  particular update but as the last update of lxqt was two month ago 0.16.0-1 -> 0.17.0-1 I don't think it's the same simple cause.

It is quite easy to reproduce:

$ mv lxqt-rc.xml rc.xml
Move rc.xml from ~/.config/openbox to ~
$ openbox --reconfigure
hit [Meta]+[e] and you'll get an error aboud child process kfmclient not found (defaults are used)
move rc.xml back to ~/.config/openbox
$ openbox --reconfigure
hit [Meta]+[e]: pcmanfm-qt opens

lxqt-rc.xml is ignored! It does not even matter if it is present.

**Comment by tsujan** [comment]
> Is this intended now?

Yes, it is. It's explained in several places. Sorry, I have no time to find them but in short: We don't make an exception for Openbox anymore.

**Comment by tsujan** [comment]
Oh, the reason is also mentioned in the best possible place: https://lxqt-project.org/release/2021/04/16/lxqt-0-17-0/
