### ISSUE TITLE
Error when starting xdg-screensaver lock

### ISSUE THREAD

**Issue by papoteur-mga** [lxqt/lxqt#2036]
When returning from suspend or hibernation, I get always this dialogue.

![image](https://user-images.githubusercontent.com/5154580/126025055-afff6805-f99d-4120-af92-c4526a41515a.png)

Error when starting xdg-screensaver lock. Check that you have a screenlocker/saver.

##### Expected Behavior
No dialogue

##### Current Behavior
Whatever I set, I have this dialogue.

##### Possible Solution
No idea

##### Context
I have tried different settings from energy saver. I had enabled "Configurer le comportement en cas d'inactivité" (Setting behaviour when idle) then disabled it, without change.
"Verrouiller l'écran avant de suspendre/hiberner" (before suspend/hibernate) is checked with 0 delay.
Xscreensaver is checked in Session settings/Automatic launch

##### System Information
* Distribution & Version: Mageia 8 migrated from Mageia 7
* Kernel: 5.10.46-desktop-1.mga
* Qt Version: 5.15.2
* liblxqt Version: 0.16.0
* Package version: lib64lxqt0-0.16.0-3.mga8

**Comment by tsujan** [comment]
Your LXQt installation is outdated.

**Comment by papoteur-mga** [comment]
Hello,
This can't be the only answer. Mageia 8 is only 4 monthes old and its policy is to not upgrade major pieces of software during the cycle life. We can't expect that LXQt will be stepped at each release. Or is LXQt provided only for rolling distributions?

**Comment by tsujan** [comment]
LXQt isn't responsible for downstream packaging. Mageia's problems should be reported to Mageia.

Also, take a look at https://github.com/lxqt/liblxqt/issues/257#issuecomment-636492677

**Comment by stefonarch** [comment]
I remember that I had the same issue with latest git on debian bullseye at fresh install some months ago.
As I don't use a screensaver on the laptop I disinstalled xscreensaver, and use a systemd service con slock for screen locking.

On my main PC xscreensaver works fine.
`xdg-screensaver lock
` does work for you?

**Comment by papoteur-mga** [comment]
> `xdg-screensaver lock ` does work for you?

Yes, it works.

**Comment by papoteur-mga** [comment]
> Also, take a look at [lxqt/liblxqt#257 (comment)](https://github.com/lxqt/liblxqt/issues/257#issuecomment-636492677)

This is more useful. Thanks.

**Comment by stefonarch** [comment]
So changing the message could be done as mentioned there.

**Comment by tsujan** [comment]
> So changing the message could be done as mentioned there.

I thought about the message. Our problem is that there's more than one screen locker/saver (which is good, BTW) and we don't want to limit the message to a particular app. The first sentence of the message is too technical. The second sentence is good but not enough.

**Comment by stefonarch** [comment]
Did some testings,  according to xdg-screensaver 1.1.3 supported screensaver/lockers are those:


```
detectDE
# Consider "xscreensaver" a separate DE
xscreensaver-command -version 2> /dev/null | grep XScreenSaver > /dev/null && DE="xscreensaver"
# Consider "gnome-screensaver" a separate DE
dbus-send --print-reply --dest=org.freedesktop.DBus /org/freedesktop/DBus org.freedesktop.DBus.GetNameOwner string:org.gnome.ScreenSaver > /dev/null 2>&1 && DE="gnome_screensaver"
# Consider "mate-screensaver" a separate DE
dbus-send --print-reply --dest=org.freedesktop.DBus /org/freedesktop/DBus org.freedesktop.DBus.GetNameOwner string:org.mate.ScreenSaver > /dev/null 2>&1 && DE="mate_screensaver"
# Consider "cinnamon-screensaver" a separate DE
dbus-send --print-reply --dest=org.freedesktop.DBus /org/freedesktop/DBus org.freedesktop.DBus.GetNameOwner string:org.cinnamon.ScreenSaver > /dev/null 2>&1 && DE="cinnamon"
# Consider "xautolock" a separate DE
xautolock -enable > /dev/null 2>&1 && DE="xautolock_screensaver"

```
Given the stuff most gnome|mate|cinnamon-screensaver depend on most people will end up with xscreensaver or do some hacks with i3lock or similar.

As this issue shows up then and when I think a wiki page about  screensaver/locker possibilities would be good.

**Comment by tsujan** [comment]
Or we can simply remove that dialog add a debug message instead of it.. Would it be really useful even if the screensaver/locker wasn't started?

**Comment by stefonarch** [comment]
Which dialog? The error message? During my tests I noticed it only shows up after suspend/hibernate, not if lock is used in powermanagement/lid action or using lock from menu.

**Comment by tsujan** [comment]
> The error message?

Yes. Is it useful at all?

**Comment by stefonarch** [comment]
Yeah, maybe just removing is the best - specially as it's only shown in 1/3 of the possible cases, in tthe other cases it just don't lock and stop.

 On a sidenote I discovered only today that xautolock is a general provider of screen lockers.

**Comment by tsujan** [comment]
> Yeah, maybe just removing is the best - specially as it's only shown in 1/4 of the possible use cases

Another reason for its removal could be that it's annoying when the locker really works — unless someone makes a patch that guarantees it's shown only when the locker doesn't work.

**Comment by stefonarch** [comment]
I remember that situation, but couldn't reproduce it now.

**Comment by papoteur-mga** [comment]
> During my tests I noticed it only shows up after suspend/hibernate,

The same for me.
Except this message, I didn't see anything going wrong.

**Comment by papoteur-mga** [comment]
Hello,
I run now Mageia 9 which has LXQt 1.3.0.
I still get the same message after hibernation.
XScreensaver is to the latest release v6.08.
