### ISSUE TITLE
Lid detection settings not working

### ISSUE THREAD

**Issue by YamiYukiSenpai** [lxqt/lxqt#2044]
Changing the lid detection settings  doesn't work.  I disabled it, and it's still making my laptop sleep when closing.  Changing to "Turn off monitor(s)" don't work either.
![Void-Flameshot_2021-07-27_12-41](https://user-images.githubusercontent.com/13153124/127194066-20cd7bd9-cd79-4ed5-b6a2-4f0740f66ec3.png)

##### Expected Behavior

Changing the settings should affect how the desktop will detect my lid.   Disabling Lid Watcher should disable sleeping.  Setting it to turn off my monitors shouldn't make it sleep as well.

##### Current Behavior

No matter the setting, the laptop will always sleep with lid closed.

##### Steps to Reproduce (for bugs)

1. LXQt Settings
2. Power Management
3. Change lid settings
4. Close the lid

##### Context

My laptop is currently docked on a shelf, and I only open it up to turn it on.  This issue made me leave it partially open, and have to make sure gravity won't shut it off.

##### System Information

* Distribution & Version: Void Linux
* Kernel: 5.12.19_1
* Qt Version: 5.15.2
* liblxqt Version: 0.17.0_1
* Package version: 0.17.0_1

**Comment by tsujan** [comment]
Not reproducible.

If you think there's more relevant info that you didn't mention in your report, please add them. The report can be re-opened.

**Comment by Zincr0** [comment]
Have this problem too, don't know where to look from logs, and there are no errors on GUI.

**Comment by stefonarch** [comment]
I understand that your problem is different (it never worked because disabled by distro).

**Comment by Zincr0** [comment]
The hibernate function was not configured, that doesn't explain why none of the lid settings did nothing.
