### ISSUE TITLE
Although this is not essentially an LXQt issue, does anyone have any idea how to fix the following issue in Ulauncher?

### ISSUE THREAD

**Issue by Raytle** [lxqt/lxqt#2048]
Although this is not essentially an LXQt issue, does anyone have any idea how to fix the following issue in Ulauncher?

[ How can I prevent my large title fonts from overlapping my subtitle fonts? #759 ](https://github.com/Ulauncher/Ulauncher/issues/759)

**Comment by stefonarch** [comment]
Please don't use "issues" for similar, we have https://github.com/lxqt/lxqt/discussions
