### ISSUE TITLE
when 2 instances of same app opened, could not switch to one of them

### ISSUE THREAD

**Issue by andy-chung** [lxqt/lxqt#2074]
When opening 2 instances of an app e.g. PCManFM, chromium, qterminal, could not switch to one of them.

##### Expected Behavior

should be able to click either one of the instance
##### Current Behavior

when mouse click the bottom task bar, 2 instance selection pop up. when move the mouse the 2 instance selection disappear 

##### Steps to Reproduce (for bugs)

1. open e.g. pcmanfm 
2. open again pcmanfm so there is 2 pcmanfm
3. try switch to one of them
4. 

##### System Information

* Distribution & Version: Fedora 34 LXQT
* Kernel: 5.13.14
* Qt Version: 5
* liblxqt Version: 0.16
* Package version:

**Comment by tsujan** [comment]
This is a downstream (packaging) issue. You could ask the maintainers of your distro to upgrade its LXQt packages or, at least, recompile them against the latest Qt version of your distro. Or you could switch to a distro with a better LXQt support.
