### ISSUE TITLE
If internet 3G drop connection crash taskbar

### ISSUE THREAD

**Issue by Augusto7743** [lxqt/lxqt#2079]
If 3G signal is weak and the connection is droped when clicking in internet icon in taskbar using mouse right button the network menu is displayed , but the menu is freeze stuck and the for more or less 10 seconds the OS is freeze stuck not being possible open the start menu and happen a taskbar crash. After the taskbar is reloaded not crashing the OS returning to normal.

**Comment by stefonarch** [comment]
Please[ fill out the template](https://github.com/lxqt/lxqt/issues/new?assignees=&labels=&template=bug_report.md&title=), it's there for a good reason - we cannot guess which version, which networkmanager ecc you are using.

**Comment by tsujan** [comment]
I close this because the reporter didn't care about anything.

**Comment by Augusto7743** [comment]
Oh excuse me.
That problem happen since LXQT 0.14.1 to current release.
Is how if the connection is dropped crashing LXQT network icon and taskbar.

**Comment by Augusto7743** [comment]
Oh excuse me.
That problem happen since LXQT 0.14.1 to current release.
Is how if the connection is dropped crashing LXQT network icon and taskbar.

**Comment by palinek** [comment]
There is no such thing as "LXQT network icon". First, you need to get more familiar with your environment to get know what applications you're using. Then you could report your issues more precisely. As for now we really can't guess what is happening with your system.

**Comment by Augusto7743** [comment]
more clearly ...
Lubuntu 20.04.3 and 21.04.
LXQT taskbar systray crash when 3G connection is disconnected by weak signal.
The user click in LXQT network icon and select in menu connect (3G internet).
3G is connected.
If the 3G connection is dropped by weak signal the user will try reconnect clicking in LXQT network icon.
The LXQT network will freeze stuck and in few seconds a taskbar crash and after the taskbar is reloaded not crashing others softwares.
Is how if LXQT network icon not has data about the current status 3G connection was dropped and trying to reconnect crash taskbar.

**Comment by tsujan** [comment]
> The user click in LXQT network icon...

As @palinek said, LXQT does **NOT** have a network icon.

**Comment by palinek** [comment]
Again, there is no such thing as **LXQT network icon**. Please, find out what application you're using for network management.
lxqt-panel (main menu, taskbar ...) can contain (and probably contains in your case) "Status notifier" and/or "System tray" area, where applications can show icons/information.

**Comment by stefonarch** [comment]
Right click on the icon > about: I'm quite sure it says "nm-tray". 21.04

![schermata-10-01-12-37-01](https://user-images.githubusercontent.com/10681413/135606667-a038acc1-2fc0-43b1-a6d8-ffadffc934d1.png)

**Comment by tsujan** [comment]
@stefonarch 
If you see any crash *in panel* with it, please attach the backtrace (`coredumpctl gdb lxqt-panel` and then, `where`).

**Comment by stefonarch** [comment]
It's an VM, I tried some things with the connection, but no crash of the panel.

**Comment by Augusto7743** [comment]
right click in systray in nm-applet.
I use Lubuntu being used LXQT.
The widgets used in systray not are related with LXQT ?
When crash I attach the log.
