### ISSUE TITLE
[Feature request] Mouse scroll page by page

### ISSUE THREAD

**Issue by Augusto7743** [lxqt/lxqt#2080]
Only is possible configure mouse scroll for a number of lines.
Not has any option to scroll page by page that is a default for OS.

**Comment by tsujan** [comment]
Each app may provide a way of scrolling page by page inside its view. It doesn't have anything to do with wheel scroll speed.

**Comment by tsujan** [comment]
In Qt, pressing SHIFT while wheel scrolling is done on the scrollbar usually causes page scrolling.

**Comment by Augusto7743** [comment]
If the user need scroll page by page the software coder need add that feature ?
I not known one software using QT allowing configure page by page.
I use LXQT for more than one year and not allowing configure page by page not is good.

**Comment by Augusto7743** [comment]
holding shift not is a solution
