### ISSUE TITLE
Leaving button options are not translated

### ISSUE THREAD

**Issue by maverick74** [lxqt/lxqt#2089]
I don't know if this is Lubuntu Specific Or LXQt specific but:
When i try to shutdown the computer the dialog window that pops up is only partially translated.

![dialog box](https://user-images.githubusercontent.com/14912461/137155301-ee932880-e9ad-490d-b75e-bbda90c2c214.jpg)

"Yes" / "No" buttons remain in English (from my experience with lubuntu it has always been this way)

* Distribution & Version: Lubuntu 21.10 + LXQt 0.17

**Comment by tsujan** [comment]
@maverick74
I don't install LXQt translations except for a few apps; lximage-qt is among them. I noticed that if I start it in Portuguese (with `LANGUAGE=pt lximage-qt`), the OK and Cancel buttons of its Preferences dialog won't be translated but if I start it in Spanish, French, Italian or German, they'll be translated.

So, my guess is that Qt's translations into Portuguese are incomplete.

**Comment by tsujan** [comment]
@maverick74

The following screenshots of `kvantumpreview` (which is completely independent of LXQt) confirm my suspicion. This one is in Portuguese:

![pt](https://user-images.githubusercontent.com/981076/137185166-3a322f74-ff9a-409b-b0a1-595ad395d416.png)

This in Spanish:

![es](https://user-images.githubusercontent.com/981076/137185252-4e1bca35-f9fa-4ab9-ad27-aa9077309ccc.png)

> is there a place i can help translate it (qt's weblate or something like it)?

My knowledge in that area is next to zero ;).

However, I convert your report to a Discussion for others to find it easily.
