### ISSUE TITLE
Choice of Window Manager now thwarted by change in 'desktop preferences' "Advanced" tab denying choice thereby

### ISSUE THREAD

**Issue by martinreid999** [lxqt/lxqt#2116]
##### Steps to Reproduce (for bugs)

1. 
2. 
3. 
4. 

##### System Information

* Distribution & Version: 
* Kernel: 
* Qt Version: 
* liblxqt Version: 
* Package version:

**Comment by martinreid999** [comment]
Not sure I found where to further describe in more detail the situation.  Currently I use MX linux almost exclusively but also Linux Mint.  Using LXQT on all my machines with Fluxbox window manager, under either MX Linux distro, or Linux Mint.  Have been able to enjoy this powerful combo of LXQT and Fluxbox, by simply choosing Fluxbox in this dialog box.  Then instead of Openbox menus when right clicking on desktop, I've been getting Fluxbox menu and can customize it as I please.  Choosing 'fluxbox' elsewhere under Window Manager selection in LXQT seems to do nothing - still have Openbox menus.   Only in this dialog box, which you get at the very bottom of the Openbox menu that comes up, allowed one to decide to use Fluxbox menus.     Now, I find myself having to stay with MX19.4 and not upgrade anything to MX21, because the version of LXQT rose to .161 instead of the .14 version I had with MX19.4.   Yet needing to upgrade.    This change by removing this choice in the dialog box forces use of Openbox with LXQT when some of us would much rather have Fluxbox, particularly MX linux users who are enjoying the extra benefits that MX Linux brings to the table for Fluxbox users.    Is there any way I can revert this change so I can continue using LXQT?  Otherwise I'm forced to abandon it and will have to use only MX-fluxbox on my machines, when I'd rather have LXQT with the Fluxbox menuing as which has been available.  Note that I'm able to get the Fluxbox menuing in Linux Mint when using LXQT desktop environment as well.  This gives either Linux Mint or MX Linux a very similar look and feel which I very much need as I have to use Mint for certain applications.

**Comment by tsujan** [comment]
I didn't understand your question but it seems you use a very old version of LXQt. LXQt doesn't prefer any WM over others anymore. Old options regarding Openbox and showing WM menu on desktop were removed a long time ago. You can use any DE-agnostic WM with LXQt. If you want to see menus of some WMs on desktop, uncheck Desktop in Session Settings and stop its process.

0.16 is outdated. The latest release is 1.0.0.

**Comment by martinreid999** [comment]
Dear Tsujan, 

With these linux distros, generally you can get what they have set up in their repositories as being "Stable". MX Linux is based on Debian Stable, and they wait a LONG time before adopting newer software and until they get a full handle on how to stabilize it with regards to their specific distro. Or at least, do enough testing with it to be confident it is in fact stable. 

So with MX-19.4 which was just upgraded last week to MX21, the maximum LXQT you could get with the "MX Package Installer" was LXQT .141. And that had the dialog box giving the 
option to use Fluxbox. Specifically, it stated " show menus by window managers when desktop is clicked " in the " Advanced " tab of " desktop preferences ". When clicking this, one could pick the Window Manager to use for this, so I picked "Fluxbox" instead of "Openbox", and as a result, for quite a while now, I've had Fluxbox menus when right clicking on the screen under LXQT. 

With the new MX-21 distro, you can only install LXQT .16 from the MX repositories, meaning, that's as far as they've tested and judged the app as stable with THEIR DISTRO. Like Debian, these guys are pretty conservative and wait some time to ensure anything running on this distro is stable. There are some distros which are even more conservative than this. They don't even give you the choice to go with the older .141 instead. You can't do it. 

Now one thing you can depend upon with MX-linux, if the app is in their "Stable Repo" part of their package manager system, you can depend upon it to simply work. They have another tab called "MX Test Repo". This is supposed to be somewhat dangerous. They also have a tab "Debian Backports" and "FlatPacks" tab as well. But I can only find on the new MX21, LXQT .16. And this MX21 with this new versio of the MX Package Installer just came out a couple days ago or so. 

Now installing LXQT otherwise, not in a distro's package manager, is not something that ordinary people can do - it takes a technical specialist to do complicated installs, and I'm not sure I have anyone at my facility that I can access who has these sort of creds. So unless I can find it as part of a distro's proven repository of apps tested well with their distro, I usually don't install it. 
I make exceptions. 

I find the combination of LXQT and Fluxbox extremely complimentary, and like this combination better than any other linux distro I've tried, period. But so far, I haven't found exactly how to get 
LXQT to give me Fluxbox as a window manager anymore with the new MX-21. I tried the "Basic Settings" tab of "Session Settings" in LXQT Settings, which gives very first thing a small choice of "Window Managers" to choose from. Choosing "Fluxbox" gets you absolutely nowhere. Going to "Desktop" of LXQT settings instead, to the "Advanced" tap, that's where you used to be able to click "show menus by window managers when desktop is clicked" and which was gone from this dialog box / tab by version .16. But that appears to users such as myself as being the only way to get LXQT to work with the window manager of my choice, Fluxbox. 

So my question is: Any way, with MX-21, for me to go back to LXQT version .141, so I can get my Fluxbox functionality back? Or, is there another way to fix LXQT so it actually allows me to use Fluxbox with it? Because it won't actually allow this anymore unless there is a fix or sequence of commands that will allow this again. Or, can I install LXQT 1.0 and get this functionality back that I had with MX-19.4 and LXQT .141? Specifically, able to use Fluxbox as my window manager and use their menuing? 

I feel this is a very key feature. It was one of the things that resulted in my choosing LXQT as the desktop environment on all of our PCs, this allowance of the use of Fluxbox menuing on the desktop. 

Martin

**Comment by stefonarch** [comment]
I cannot see any issue using fluxbox in any version as WM, the solution described by @tsujan  (disabling desktop) works fine.
![schermata-11-08-08-27](https://user-images.githubusercontent.com/10681413/140875045-61330080-992d-403c-ae29-0b6d0127db37.png)

**Comment by tsujan** [comment]
@martinreid999, please avoid writing long comments when you can explain something with a few words.

> Like Debian, these guys are pretty conservative and wait some time to ensure anything running on this distro is stable.

It isn't about ensuring stability, whether in Debian Stable or in other LTS distros. They just have this rule: "No upgrade for a long time!" Use an LTS distro if you don't want an upgrade and can tolerate the problems of its old programs or the lack of support for a long time.

Anyway, LXQt has no problem with any WM and @stefonarch specifically tested fluxbox.

**Comment by martinreid999** [comment]
Dear Tsujan,
Okay then, do you know what I need to do in order to make it work?   Because it won't work now that .141 changed to .16.Martin
----- Original Message -----

**Comment by martinreid999** [comment]
Dear Tsujan,

Attached is a doc which explains basically why this functionality that I had to use the right-click-on-desktop fluxbox menu capability disappeared after .141.Please read the attached as it clarifies that this was deliberately and intentionally removed while us users are being told LXQT is WM agnostic.  This has the effect of wasting LXQT's loyal followers' time in spades.   Please deliver this as a complaint from a loyal user about this sort of tact, to whoever should receive it.

Martin



----- Original Message -----

**Comment by martinreid999** [comment]
Dear Tsujan,
Note that under .16 version of LXQT which one can get if on the new MX-linux 21,  the IceWM sort of works when you choose it, but you still have Openbox right click menus on the screen.   You get the IceWM taskbar if you choose this under "Session Settings".   But if you choose Fluxbox, you don't get anythingMy understanding is the first distro which will have LXQT 1.0 is Lubuntu in 2022 and maybe Void linux in 2022.    And there is no guarantee that Fluxbox will work with that either.  I think when someone dispensed with the option in the "Advanced" tab to allow window managers to function on right-click on the desktop, they flushed anyone getting anything else than Openbox right-click desktop menuing under LXQT.    For me, the entire attraction of LXQT is it brought a synergy of functionality together with Fluxbox on both MX Linux and Linux Mint
I've been using the combination of MX-linux or Linux Mint some time using LXQT .141, and the earlier version of these distros, except, MX19.4 came out just several months ago, still having LXQT .141 in their repos and package manager.   Now I'm sorta forced to give IceWM a try, because at least this has some functionality working together with LXQT .16.Martin----- Original Message -----

**Comment by tsujan** [comment]
@martinreid999 
I explained everything in https://github.com/lxqt/lxqt/issues/2116#issuecomment-963712054. Again:

We removed WM context menus a long time ago because (1) Not all WMs had it; (2) It required X11 codes, which we avoid; (3) pcmanfm-qt's context menu was too important to be replaced by an alien one;....

That doesn't mean that you can't use Fluxbox with LXQt. It means you should say goodbye either to its context menu on desktop or to pcmanfm-qt's desktop functionality.

**Comment by tsujan** [comment]
> For me, the entire attraction of LXQT is...

Then, LXQt has lost its "entire attraction" for you. That will never change.

I didn't read all of your long comments, due to the lack of time, but I think you repeated the same thing again and again.

**Comment by martinreid999** [comment]
Dear Tsujan,
You know, I look at context menu you refer to as so important, and I don't see much there that has the claimed importance.  Which is why I like replacing it with the Fluxbox setup, which appears to be a lot more important.
Martin----- Original Message -----
