### ISSUE TITLE
Keyboard State Indicator widget not highlighting/coloring when Clearlooks or Leech themes are used

### ISSUE THREAD

**Issue by edwardp3** [lxqt/lxqt#2121]
Tried out the Clearlooks and Leech themes in LXQt (0.17.0, Lubuntu) to find that when any of the three key locks are pressed, the C-N-S in the widget does not change color or highlight. This is working with all of the other themes.

##### Expected Behavior
With the Clearlooks and Leech themes, when Caps/Num/Scroll lock(s) on, the widget should color or highlight the relevant letter.

##### Current Behavior
The letters in the widget are not changing color or being highlighted.

##### Steps to Reproduce (for bugs)
1. Select either Clearlooks or Leech themes. 
2. Press any or all of the Caps/Num/Scroll Lock keys.
3. The relevant letter (C-N-S) does not hchange color or become highlighted to show that the particular key is active.

##### System Information
                                                        
* Distribution & Version: Lubuntu 21.10, LXQt 0.17.0
* Kernel: 5.13.0-21-generic
* Qt Version: 5.15.2
* liblxqt Version: 0.17.0
* Package version:

**Comment by tsujan** [comment]
Already fixed in the latest release, 1.0.0.

**Comment by stefonarch** [comment]
While waiting for 1.0.0 you can download the latest themes as *zip and copy them to `~/.local/share/lxqt/themes/` so they will be used in first place.

**Comment by edwardp3** [comment]
Thanks. Noted and installed. I think I might simply install all of the themes in the latest .zip file.
