### ISSUE TITLE
new windows (and popups) get focus even when "Focus new windows" is de-selected

### ISSUE THREAD

**Issue by gregrwm** [lxqt/lxqt#2128]
##### Expected Behavior

Honor the selected option.

##### Current Behavior

New windows always get focus.

##### Steps to Reproduce (for bugs)

1. de-select "Focus new windows when they appear"
2. (select "Focus windows when the mouse pointer moves over them")
3. (select "Move focus under the mouse when switching desktops")
4. launch something eg xterm or qterminal from either appmenu or terminal

##### Context

want true and complete prevention of focus stealing so typing is never interrupted.

##### System Information

* Distribution & Version: 2080235520 2021-11-08 Mon 19:56:32 lubuntu/jammy-desktop-amd64.iso
* Kernel: Linux lubuntu 5.13.0-19-generic #19-Ubuntu SMP Thu Oct 7 21:58:00 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
* Qt Version: 0.17.0
* liblxqt Version: liblxqt0:amd64 (0.17.0-0ubuntu1)
* Package version:

**Comment by tsujan** [comment]
You're talking about a window manager, while LXQt doesn't have any WM.

**Comment by gregrwm** [comment]
according to the obconf-qt github page:

ObConf-Qt
Overview

ObConf-Qt is a Qt port of ObConf, a configuration editor for window manager OpenBox.

It is maintained by the LXQt project....

**Comment by gregrwm** [comment]
otoh obconf-qt does have it's own github and issues pages.  submitting this there.

**Comment by tsujan** [comment]
obconf-qt isn't developed anymore.

**Comment by stefonarch** [comment]
We should state that in the README.md

**Comment by tsujan** [comment]
More than that, we should archive this repository.
