### ISSUE TITLE
lxqt-admin helpers paths in codes

### ISSUE THREAD

**Issue by stefonarch** [lxqt/lxqt#2140]
### Discussed in https://github.com/lxqt/lxqt/discussions/2133

<div type='discussions-op-text'>

<sup>Originally posted by **hamzehnasajpour** November 21, 2021</sup>
Is there any specific reason to using absolute path to run `lxqt-admin-time-helper` [here](https://github.com/lxqt/lxqt-admin/blob/77c0944aa891f7fe51e01a687963c5381796a1f4/lxqt-admin-time/nosdtimedatectl.cpp#L132) and run the `lxqt-admin-user-helper` without path [here](https://github.com/lxqt/lxqt-admin/blob/77c0944aa891f7fe51e01a687963c5381796a1f4/lxqt-admin-user/usermanager.cpp#L212)? Both of them are correct, just saying for consistency.</div>

**Comment by tsujan** [comment]
The path should be removed from `NOSDTimeDateCtl::pkexec()`.
