### ISSUE TITLE
Changes in font-config should apply to gtk apps

### ISSUE THREAD

**Issue by Barba-Q** [lxqt/lxqt#2164]
Adjusting font sizes in the lxqt conifugarion tool only affects qt apps but not gtk apps. This can be fixed relatively easily by adjusting the ~./.gtkrc-2.0 accordingly. It would be much easier if changes from the lxqt configuration tool would have direct influence on it as well on the font.config.

**Comment by tsujan** [comment]
Not true. LXQt Appearance Configuration → Set GTK themes....

**Comment by Barba-Q** [comment]
> Not true. LXQt Appearance Configuration → Set GTK themes....

This set's themes yes, not font configurations.

**Comment by stefonarch** [comment]
Here this sets also fonts. Which version of LXQt are you using?

**Comment by Barba-Q** [comment]
> Here this sets also fonts (for gtk3). Which version of LXQt are you using?

I'm so sorry. It does exactly that. Somehow I have to switch around the gtk themes to have an effect on the fonts.

**Comment by tsujan** [comment]
LXQt is a Qt DE. Changing GTK settings isn't among the jobs of LXQt Appearance config (because the user may have a GTK DE installed alongside LXQt) but it will do it if the user enables the GTK option — font or theme makes no difference.

**Comment by stefonarch** [comment]
> Maybe a hint that changing GTK-theming also takes affect on font's would be nice anyway.

I noticed that, it's not obvious in the settings. Maybe one more  line below in the explanation:
"Also font settings will be applied" or similar.

**Comment by tsujan** [comment]
IMO, we should remove those parentheses; that part of the GUI has an unprofessional design. Instead, we can show a warning dialog as soon as the user checks that check-button and say in it whatever needs to be said.

**Comment by stefonarch** [comment]
> show a warning dialog as soon as the user checks that check-button and say in it whatever needs to be said.

Good idea!

**Comment by Barba-Q** [comment]
> Good idea!

Indeed
