### ISSUE TITLE
[Feature request] lxqt-panel export (and import) widget settings

### ISSUE THREAD

**Issue by formidablae** [lxqt/lxqt#2184]
**Is your feature request related to a problem? Please describe.**
This is not a problem, it's just an improvement.
Would it be possible to have an export (and import) settings for the panel (lxqt-panel)?

**Context**
After a system reinstall, setting all the widget custom settings takes time.

**Describe the solution you'd like**
It would be nice to have an export (and import) gui feature to save (and import) these custom settings to (from) an external file.

**Comment by tsujan** [comment]
Everything you want is inside `~/.config/lxqt`, `~/.config/pcmanfm-qt` and `~/.local/share/file-manager/actions`. Restore the contents of those folders from outside LXQt — or when the corresponding apps aren't running — and your settings will be restored.

That's the case for almost all apps.
