### ISSUE TITLE
Inability to place panel at bottom and missing icons at dual monitor setup.

### ISSUE THREAD

**Issue by chomwitt** [lxqt/lxqt#2189]
##### Expected Behavior

I have a dual monitor set up. 
![image](https://user-images.githubusercontent.com/1383580/153506164-71872466-601d-46b0-953b-3637e5280e5d.png)
I would expect to being able to set my panel to the bottom of my primary screen
and adding programs icons to the desktop to be visible.

##### Current Behavior

But after having set my monitors setup (as seen in the screenshot)  trying to use
**Configure Panel** there wasnt an option to position at the 'Bottom of desktop 1' but
only to the left.
Also adding new icons on the desktop i couldnt see them, As i found out
a virtual screen is created that i think creates a rectangle that contains my two
screens.

##### Possible Solution
I managed to solve one issue , that of positioning my panel to the bottom of the desktop 1 (the left monitor) but after 4-5 attemps where i did some small adjustments to the 'Monitor Settings' (i dont remember what) but  i remember that after one such trial the 'Configure Panel' changes the offered options of 'Left and Top' to only 'Left.

##### System Information
System: Host: enoush2o Kernel: 5.15.0-3-amd64 x86_64 bits: 64 Desktop: LXQt 0.16.1
              Distro: Devuan GNU/Linux 5 (daedalus/ceres)

**Comment by tsujan** [comment]
Sorry, 0.16.1 is outdated.
