### ISSUE TITLE
Drag n drop from "application menu" does not work

### ISSUE THREAD

**Issue by MauroMombelli** [lxqt/lxqt#219]
seems like the pointet url is empty, or maybe null. if you try to drag'n' drop to "quick panel"  you get an error that uri cannot be void, if you drag'n'drop to desktop it will try to copy all / to desktop.

**Comment by jotasprout** [comment]
Same problem. Just installed LXQt today.

**Comment by tsujan** [comment]
Replied here: https://github.com/lxqt/lxqt/issues/235#issuecomment-404629891
