### ISSUE TITLE
No apparent way to change tooltip transparency

### ISSUE THREAD

**Issue by bhilmers** [lxqt/lxqt#2193]
Hello. I cannot find a way to remove transparency from tooltips. I tried changing the alpha setting for QToolTip in /usr/share/lxqt/themes/ but this has no effect. The transparency is a problem when viewing websites as shown in the attached image.

OS: Ubuntu 20.04.3 LTS x86_64
Kernel: 5.15.15-76051515-generic 
LXQt: 0.14.1
WM: Openbox
WM Theme: Lubuntu Arc

![lubuntu-tooltip-transparency](https://user-images.githubusercontent.com/77466683/154578221-3bfecfeb-31a6-4453-b8e2-8ccf157e64c4.jpg)

**Comment by tsujan** [comment]
LXQt theme is only for LXQt panel and runner; it doesn't style your apps.
