### ISSUE TITLE
Laptop randomly freezes - no known pre-condition

### ISSUE THREAD

**Issue by carryonrewardless** [lxqt/lxqt#2198]
##### Expected Behavior
Laptop expected to keep running without freezing

##### Current Behavior
occasional but persistent freezes on my laptop since new about January 2021.  No mouse response, no keyboard response. Forced to power down.

##### Possible Solution
unknown

##### Steps to Reproduce (for bugs)
No known pre-requisite for freeze event
1. 
2. 
3. 
4. 

##### Context
Have changed from using Nvidia to Intel on-board graphics adapter.  No improvement.
Have reverted back to Nvidia with latest driver nvidia-driver-470

##### System Information

* Distribution & Version: Lubuntu 20.04
* Kernel: 5.4.0-89-generic
* Qt Version: ?  qt5-gtk-platformtheme qtbase-opensource-src Version 5.12.8+dfsg-0ubuntu2.1
* liblxqt Version: 0.14.1-0ubuntu2
* Package version: lxqt-core Version 30
* Hardware: cpu    product: Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
* 

 Hello
I get occasional but persistent freezes on my MSI GF65 laptop since new about January 2021.
Using 20.04 LXQT
5.4.0-89-generic #100-Ubuntu SMP Fri Sep 24 14:50:10 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
See bug report [Bug Report](https://bugs.launchpad.net/bugs/1951683) - nothing found.

Logfile from journalctl -b-1 > syslog22022-03-02.txt
[logfile at crash](https://pastebin.com/z0KqBKzt)

Can you identify a root cause?  Do you have other reports of freezes with no crashfile created?

Thanks

**Comment by tsujan** [comment]
LXQt doesn't have any component to control your graphics and your log doesn't show a problem in LXQt.

> Do you have other reports of freezes with no crashfile created?

No.
