### ISSUE TITLE
[Feature request] Fluxbox without Toolbar

### ISSUE THREAD

**Issue by GreenLunar** [lxqt/lxqt#2204]
I suggest to start fluxbox with the argument `-no-toolbar` because that toolbar and its different behaviour and appearance migh confuse users and might make LXQt project to appear less impressive to them, unless you want that toolbar to be used as a backup in case lxqt-panel and pcmanfm-qt crash or not installed.

```
-no-toolbar
   Do not use the toolbar
```
From: http://fluxbox.org/help/man-fluxbox.php

P.S. Please don't use `-no-slit`, I need it for Conky and DockApps

Thank you

**Comment by stefonarch** [comment]
We shouldn't support special options in WM's IMHOm and sure not by default. 

You could porbably  just create a custom launcher script with that option for fluxbox and use it as WM in the settings, or modify the fluxbox launcher itself if possible.

**Comment by GreenLunar** [comment]
**I forgot to mention**, there are TWO (2) SYSTRAYS and they are in conflict.

This means that a tray of Transmission might be hidden to an LXQt user, because the tray of Fluxbox (which is not visible and is under PCManFM's desktop shell) has catched it into its tray before the LXQt Panel.

This is a mess!

**Comment by GreenLunar** [comment]
I've a suggestion for you.
I'm trying to get into a compromise.

Current menu:
* fluxbox
* openbox
* xfwm4

New menu:
* fluxbox
* fluxbox (with toolbar)
* openbox
* xfwm4

**Comment by stefonarch** [comment]
The menu lists all known window managers installed and stop.

As I said: this could lead to  infinite option requests for all possible window managers and in your case a solution is easy achievable with a custom script.

**Comment by GreenLunar** [comment]
Isn't it in our best interest to make LXQt accesible even to non-technical users?

Yes, a solution can be obtained by:
```
#!/bin/bash
fluxbox -no-toolbar
```

Shouldn't we instead provide a list of WMs with the least of features (features that may conflict with LXQt) and provide documentation for advanced users?

**Comment by GreenLunar** [comment]
Use `.desktop` files like those in `/usr/share/xsessions/fluxbox.desktop`
https://docs.salixos.org/wiki/index.php/How_to_add_fluxbox_to_the_gdm_menu

A selection of `.desktop` files is the best solution, IMHO

**Comment by tsujan** [comment]
> don't want or are looking into the next DE after 10 seconds or less.

Or to the next WM.

LXQt is agnostic toward WMs and doesn't have a special handling for any.

**Comment by stefonarch** [comment]
I didn't think of it but editing `/usr/share/xsessions/fluxbox.desktop` directly should work too.

>Isn't it in our best interest to make LXQt accesible even to non-technical users?

This isa job for distro maintainers, non technical users will stick which the applications and WM provided by their distro.

> Shouldn't we instead provide a list of WMs with the least of features (features that may conflict with LXQt) and provide documentation for advanced users?

https://github.com/lxqt/lxqt/wiki/ConfigWindowManagers

**Comment by GreenLunar** [comment]
OK, I'm almost giving up.

I want to ask you a question.

Which DE is to most stable, most smooth, most lightweight and most end user intuitive for SBC and extremely weaker machines?

**Comment by GreenLunar** [comment]
> LXQt is agnostic toward WMs and doesn't have a special handling for any.

I see this word used often, also in [Calamares](https://calamares.io/).

> Calamares aims to be easy, usable, beautiful, pragmatic, inclusive and distribution-**agnostic**

What does agnostic mean in software?
