### ISSUE TITLE
[Feature request] Add description to Environment Variables

### ISSUE THREAD

**Issue by GreenLunar** [lxqt/lxqt#2208]
LXQt Session Settings -> Environment (Advanced)

| Variable Name | Value | Description |
| - | -  | - |
| GTK_CSD | 0 | Client-side decoration |
| GTK_OVERLAY_SCROLLING | 0 | Automatically hide scrollbars |
| EDITOR | nano | Default text editor |

**Comment by tsujan** [comment]
EVs don't contain descriptions and can be app-specific.

**Comment by GreenLunar** [comment]
1) I know.
2) I don't care.

Observation of file `'bashrc'
```
# Created by `pipx` on 2022-01-09 09:12:52
export PATH="$PATH:$HOME/.local/bin"
```
By looking at this, it gives me a little idea, similarly to python doc when we comment above class to convey to a programmer what it does.  Here's the idea:

The following text:
```
# Overlay scrollbars
# Created by `lxqt-config-session` on 2022-03-10 08:19:42
export GTK_OVERLAY_SCROLLING=0
```

Will be realized, by its first line, as a description in LXQt Session Settings -> Environment (Advanced):
```
Automatically hide scrollbars
```

A tooltip may display the rest/entire of the commented text.

**Comment by tsujan** [comment]
> I don't care.

Irrelevant. There's no description to be extracted from an EV.
