### ISSUE TITLE
Config file name with empty XDG_CURRENT_DESKTOP

### ISSUE THREAD

**Issue by luis-pereira** [lxqt/lxqt#2220]
Offending code:
https://github.com/lxqt/lxqt-config/blob/d11e93cea008432161907c96b749e4a28b2f6e58/lxqt-config-file-associations/mimetypeviewer.cpp#L153
https://github.com/lxqt/lxqt-config/blob/d11e93cea008432161907c96b749e4a28b2f6e58/lxqt-config-file-associations/mimetypeviewer.cpp#L472

Similar bug/fix to https://github.com/lxqt/libqtxdg/pull/279 and https://github.com/lxqt/libfm-qt/pull/766.
##### System Information

* Distribution & Version: 
* Kernel: 
* Qt Version: 
* liblxqt Version: git
* Package version:  git

**Comment by tsujan** [comment]
Nice catch!

Will make a PR soon.
