### ISSUE TITLE
power management: add option to turn display off after some inactivity time

### ISSUE THREAD

**Issue by goetzc** [lxqt/lxqt#223]
In `lxqt-config-powermanagement` there are options for laptop lid and idleness. 

It would be useful for battery life if the display could be configured to be turned off after some inactivity time. A default value would also be nice. Currently there are options for [Nothing, Lock screen, Suspend, Hibernate, Shutdown].

**Comment by goetzc** [comment]
I have seen something strange with this.  
DPMS disabled with `xset -dpms` doesn't prevent the display from turning off after ~10 minutes or so. Is this behavior hard-coded?

**Comment by tsujan** [comment]
I don't think so. I have `xset dpms 0 0 300` in my start-up script and use `xset -dpms` to manually disable it with a keyboard shortcut. Video players like VLC and SMPlayer do that automatically.

**Comment by tsujan** [comment]
However, I have "When idle then: Nothing" in Power Manager -> Idle. So, you may be right.

**Comment by goetzc** [comment]
I have the same option enabled in Power Manager :/ I have observed this behavior in an old setup and in a fresh one. There is something that turns off the display.

I'll test with the "Idleness watcher" disabled.

**Comment by tsujan** [comment]
Now we have backlight change when idle.
