### ISSUE TITLE
Unable to add network monitor to panel

### ISSUE THREAD

**Issue by GenericDataflow** [lxqt/lxqt#2230]
##### Expected Behavior
Right click panel > Configure panel> add plugin >select network monitor , click add widget >network monitor gets added to my panel

##### Current Behavior
Right click panel > Configure panel> add plugin >select network monitor , click add widget >Nothing happens The Windows stays open and i continue to press add widget to no avail.

##### Possible Solution
See Context

##### Steps to Reproduce (for bugs)

- Steps mentioned in behaviour
- visual representation https://postimg.cc/nX77HW9j

##### Context
After Updating (Pacman -Syu) restarted. Woke up loaded all good 3 hours later no widget no connection.
Started connection manually with if config and for some reason had to unblock wifi via rf-kill. This may not be related but both widget and wifi broke at same time. Creating a new panel yields the same bugs                                       --->

##### System Information
Arch Linux
* Distribution & Version: Arch 5.17.5
* Kernel: 5.17.5-zen1-1-zen
* Qt Version: 5.15.3
* liblxqt Version: 1.1.0-2
* Package version:1.1.0

**Comment by stefonarch** [comment]
`libstatgrab` is installed?

**Comment by tsujan** [comment]
Not reproducible.
