### ISSUE TITLE
Bluetooth mouse settings are not saved

### ISSUE THREAD

**Issue by dancojocaru2000** [lxqt/lxqt#2245]
##### Expected Behavior

Settings made in Preferences > Keyboard and Mouse > Mouse and Touchpad should be saved.

##### Current Behavior

Whenever the mouse disconnects and reconnects, the settings are reset.

##### Steps to Reproduce (for bugs)

1. Pair Bluetooth mouse to computer
2. Activate Natural Scrolling in settings 
3. Turn off the mouse / disconnect it from Bluetooth settings
4. Reconnect the mouse

##### Context

My main issue is natural scrolling, since I always use mice in that way.

##### System Information

* Distribution & Version: Fedora 36
* Kernel: 5.17.9-300.fc36.x86_64
* Qt Version: 5.15.3
* liblxqt Version: 1.0.0

**Comment by yan12125** [comment]
Could you paste your current `~/.config/lxqt/session.conf`? Mouse settings are stored using mouse names. I wonder if names are different every time for a bluetooth mouse.

**Comment by dancojocaru2000** [comment]
```
[General]
__userfile__=true
leave_confirmation=true
window_manager=openbox

[Environment]
GTK_CSD=0
GTK_OVERLAY_SCROLLING=0
LANG=en_GB.UTF-8
LC_MEASUREMENT=ro_RO.UTF-8
LC_MONETARY=ro_RO.UTF-8
LC_TIME=ro_RO.UTF-8

[Font]
antialias=true
dpi=96
hinting=true

[Keyboard]
beep=false
delay=500
interval=30
numlock=true

[Mouse]
acc_factor=20
acc_threshold=10
cursor_size=18
cursor_theme=breeze_cursors
left_handed=false

[Touchpad]
Designer%2520Mouse\accelSpeed=@Variant(\0\0\0\x87\0\0\0\0)
Designer%2520Mouse\naturalScrollingEnabled=1
Designer%2520Mouse\scrollingMethodEnabled=0
Designer%2520Mouse\tapToDragEnabled=-1
Designer%2520Mouse\tappingEnabled=-1
Keychron%2520Keychron%2520K2\accelSpeed=@Variant(\0\0\0\x87\0\0\0\0)
Keychron%2520Keychron%2520K2\naturalScrollingEnabled=0
Keychron%2520Keychron%2520K2\scrollingMethodEnabled=0
Keychron%2520Keychron%2520K2\tapToDragEnabled=-1
Keychron%2520Keychron%2520K2\tappingEnabled=-1
SynPS%252F2%2520Synaptics%2520TouchPad\accelSpeed=@Variant(\0\0\0\x87\0\0\0\0)
SynPS%252F2%2520Synaptics%2520TouchPad\naturalScrollingEnabled=1
SynPS%252F2%2520Synaptics%2520TouchPad\scrollingMethodEnabled=1
SynPS%252F2%2520Synaptics%2520TouchPad\tapToDragEnabled=1
SynPS%252F2%2520Synaptics%2520TouchPad\tappingEnabled=1
TPPS%252F2%2520IBM%2520TrackPoint\accelSpeed=@Variant(\0\0\0\x87\0\0\0\0)
TPPS%252F2%2520IBM%2520TrackPoint\naturalScrollingEnabled=1
TPPS%252F2%2520IBM%2520TrackPoint\scrollingMethodEnabled=4
TPPS%252F2%2520IBM%2520TrackPoint\tapToDragEnabled=-1
TPPS%252F2%2520IBM%2520TrackPoint\tappingEnabled=-1
```

Despite the `Designer%2520Mouse\naturalScrollingEnabled=1` line, after disconnecting and reconnecting the mouse, the Keyboard and Mouse settings shows this:

![Keyboard and Mouse page showing natural scrolling off](https://user-images.githubusercontent.com/9626761/170861478-ef5c706a-de73-44d4-adc8-ff4267562f06.png)

**Comment by yan12125** [comment]
Hmm, there is indeed a bug. Mouse settings are only applied when LXQt is started, but not when a mouse is re-connected.

> the Keyboard and Mouse settings shows this:

FYI, this dialog loads actual mouse settings from the system instead from config files.

**Comment by dancojocaru2000** [comment]
Indeed, I noticed that the mouse had natural scrolling turned on when logging in and, for a second, I thought the problem got fixed by itself. 

It seems like reconnection is the problem, and since my mouse automatically goes to sleep if I don't move it for some minutes, I notice it more often.

**Comment by yan12125** [comment]
Here is the fix: https://github.com/lxqt/lxqt-session/pull/438. Configurations are correctly reloaded after re-plugging my Unifying receiver. Bluetooth mice should work the same.
