### ISSUE TITLE
screengrab may not grab active window on another display

### ISSUE THREAD

**Issue by pfortin** [lxqt/lxqt#2251]
screengrab captures:
- dual monitors (full screen mode)
- screen area
- last selected area
just fine; but window mode will capture only the cursor on a black screen if the desired window is on the primary display. Moving the window to the non-primary display works.
See https://bugs.mageia.org/show_bug.cgi?id=30522  for further discussion.

##### Expected Behavior
Window mode should grab screen regardless of physical display it is on.

##### Current Behavior
See above

##### Steps to Reproduce (for bugs)
1.  start screengrab on multi-monitor system (2 monitors on reporter's system)
2.  set to Window
3.  try to grab window on primary display -- gets black screen and mouse cursor
4. move target window to non-primary display -- works.

##### Context
Must use "Screen area" or move window to get screen shot.

##### System Information
* Distribution & Version:   Mageia Cauldon (mga9)
* Kernel: 5.18.3-server-1.mga9
* Qt Version: 5
* liblxqt Version: not finding lib[64]lxqt -- I get this from ldd:
* $ ldd /usr/bin/screengrab | grep -i qt
        libQt5X11Extras.so.5 => /lib64/libQt5X11Extras.so.5 (0x00007fc276bb6000)
        libQt5Network.so.5 => /lib64/libQt5Network.so.5 (0x00007fc276a1e000)
        libQt5Xdg.so.3 => /lib64/libQt5Xdg.so.3 (0x00007fc2769d5000)
        libQt5DBus.so.5 => /lib64/libQt5DBus.so.5 (0x00007fc276947000)
        libQt5Widgets.so.5 => /lib64/libQt5Widgets.so.5 (0x00007fc276200000)
        libQt5Gui.so.5 => /lib64/libQt5Gui.so.5 (0x00007fc275a00000)
        libQt5Core.so.5 => /lib64/libQt5Core.so.5 (0x00007fc275400000)
        libQt5Xml.so.5 => /lib64/libQt5Xml.so.5 (0x00007fc2759bc000)
        libQt5XdgIconLoader.so.3 => /lib64/libQt5XdgIconLoader.so.3 (0x00007fc2760ad000)
        libQt5Svg.so.5 => /lib64/libQt5Svg.so.5 (0x00007fc27414f000)

* Package version: 
$ rpm -qa | grep screengrab
screengrab-2.4.0-2.mga9

**Comment by tsujan** [comment]
While I couldn't reproduce the problem as it was described in this report, I can reproduce more than one problem under certain conditions that aren't mentioned in the report, e.g., if the screengrab window and the window whose screenshot is going to be taken are on different screens. A black screenshot will be created only if "Include mouse pointer" is checked but, even without it, the active window might not be found correctly unless the cursor is on it (although not always).

So, there is a bug somewhere -- or perhaps there are several interrelated bugs.

**Comment by tsujan** [comment]
The fix is here: https://github.com/lxqt/screengrab/pull/305

The problem was caused by a small miscalculation. The fix also explains why the bug wasn't reproducible with a simple multi-screen setup, i.e., with the primary screen on the left, the secondary screen on the right. and the cursor inside the primary screen.
