### ISSUE TITLE
window manager does not remember position and size of the vokoscreenNG-window

### ISSUE THREAD

**Issue by ralf3u** [lxqt/lxqt#2256]
**steps to reproduce**
1 sudo apt install vokoscreen-ng
2 open vokoscreenNG
3 change postion and size of the window
4 close vokoscreenNG
5 open vokoscreenNG

**result**
vokoscreenNG-window has the same size and position like step 2

**expectation**
window manager should remember position and size of the vokoscreenNG-window

**remark**
the developer of vokoscreenNG wrote that the window manager is the problem https://github.com/vkohaupt/vokoscreenNG/issues/210#issuecomment-1150114471

**System**
Lubuntu 22.04
LXQt 1.1.0 via PPA

**Comment by stefonarch** [comment]
As you may know LXQt is WM agnostic, Lubuntu uses openbox.

**Comment by ralf3u** [comment]
@stefonarch If Lubuntu will not use any more openbox, then where can I configure the shortcuts for Wayland?

**Comment by stefonarch** [comment]
Why should Lubuntu stop using openbox, and what has this to do with wayand?

**Comment by ralf3u** [comment]
>Why should Lubuntu stop using openbox, and what has this to do with wayand?

I was thinking that in Lubuntu Wayland will replace Xorg as window manager and then openbox will not work any more because I thought that openbox belongs to Xorg.
So, with your question, I suppose that in Lubuntu, if one day Xorg will be replaced by Wayland, rc.xml will still work because openbox will still work. Is that correct?

**Comment by tsujan** [comment]
When LXQt officially gets a Wayland session (not soon), it'll also have an X11 session.

**Comment by stefonarch** [comment]
No, openbox does  not work on wayland. 
But it's useless to talk about when and if - LXQt is still far away from using a wayland  session still, so will Lubuntu. Please use discussions for general questions.
