### ISSUE TITLE
libfm-qt belongs in Stage II of the build process, not stage III where it's at now.

### ISSUE THREAD

**Issue by ArrayBolt3** [lxqt/lxqt#2267]
##### Expected Behavior
I should be able to follow the Wiki steps for compiling LXQt from source without encountering any build dependency errors so long as I follow the order of build stages.

##### Current Behavior
In Debian and Ubuntu, lxqt-qtplugin requires libfm-qt-dev as a build dependency, but lxqt-qtplugin and libfm-qt are both located in stage III. Attempting to build lxqt-qtplugin without making the proper files from libfm-qt available to the build process results in build failure.

##### Possible Solution
Move libfm-qt to Stage II, requiring users to build it before they build lxqt-qtplugin.

##### Steps to Reproduce (for bugs)
**NOTE!** I have not tested these exact reproduction steps, but I am very sure this will do the trick based on my experience with managing Debian's and Ubuntu's packaging. The exact steps I'm using would introduce copious amounts of "fluff" into the process that are likely to be obstructive to someone who just wants to verify a bug. If it turns out this bug is not reproducible with these steps, yell at me for it and I'll figure out how to reproduce it without having to bring the full complement of Debian packaging tools into the equation.

1. Compile and install the various LXQt components, starting with Stage 0, and stopping at Stage II.
2. Attempt to build and install lxqt-qtplugin. It will fail.
3. Attempt to build and install libfm-qt. It will succeed.
4. Once libfm-qt and all it's development files are installed, attempt to build and install lxqt-qtplugin again. It will succeed.

##### Context
Packaging LXQt for Debian requires that I have all the components packaged into neat little .deb files, to be installed on the fly during each build. I don't expect to have to have libfm-qt's files available for the lxqt-qtplugin build, since they're both in Stage III, yet the build fails unless I make libfm-qt's files available. Slows me down a bit, and doesn't match with the Wiki.

##### System Information
* Distribution & Version: Lubuntu 22.10 Kinetic Kudu Alpha
* Kernel: 5.15.0-27-generic
* Qt Version: 5.15.4
* liblxqt Version: 1.1.0
* Package version: 1.1.0

**Comment by tsujan** [comment]
The Wiki says [explicitly](https://github.com/lxqt/lxqt/wiki/Building-from-source#generalbuild-order), "... components have to be compiled in a particular order...", and `lxqt-qtplugin` is put after `lxqt-themes`. The stages aren't relevant to this.

**Comment by ArrayBolt3** [comment]
Immediately after the list of stages, it states, "These groups must be processed in this order but the order of components within the each group does not matter." Doesn't that mean that any package in a stage should only depend on packages in the previous stages?

**Comment by tsujan** [comment]
@stefonarch 
Would you please move `libfm-qt` to the bottom of "II" here: https://github.com/lxqt/lxqt/wiki/Building-from-source#generalbuild-order

**Comment by tsujan** [comment]
Never mind; did it myself.

@ArrayBolt3, thanks!
