### ISSUE TITLE
Input buttons in notifications are unclickable

### ISSUE THREAD

**Issue by 9W5iw** [lxqt/lxqt#2317]
##### Expected Behavior
input buttons in notifications should be clickable (like "do not show this notification again" in network manager)

![29098027-bb219946-7cba-11e7-91d1-d94eea727f63](https://user-images.githubusercontent.com/102693111/196385481-83df3c88-dd9f-43b3-a4cc-d9d3a59e52a5.png)

##### Current Behavior
When I click on a input button nothing happens. When I click on the body of notification nothing happens

##### Steps to Reproduce (for bugs)
Get Debian 11 with lxqt desktop and install it.
Use some app that uses notification with input buttons

##### Context
No ability to use bluemann to anything ==> no ability to use blutooth using gui

##### System Information
Fully updated Debian 11 with LXQT desktop only. HP 11 G4 chromebook  with full uefi firmware installed (mr chromebox firmware utility, newest version 2022.04.09)
* Distribution & Version: Debian 11 
* Kernel: linux-image-5.10.0-16-amd64
* Qt Version: 0.16.0 (from "about lxqt")
* liblxqt Version: liblxqt0 0.16.0-1
* Package version:

**Comment by tsujan** [comment]
> liblxqt Version: liblxqt0 0.16.0-1

It' outdated.

**Comment by FlRENADO** [comment]
this issue persists in debian 13 and devuan 6. I do not have anyway to trouble shoot this issue any further as this is the only result on google of any relevance.

**Comment by stefonarch** [comment]
I've two installations on debian (trixie, testing) and never encountered this issue even before, so there has to be some other element involved. You can try to run the attached script from a terminal, it will print the button actions you clicked in the notification popup.

[notification_test.py](https://github.com/user-attachments/files/30383735/notification_test.py)

**Comment by 9W5iw** [comment]
> I've two installations on debian (trixie, testing) and never encountered this issue even before, so there has to be some other element involved. You can try to run the attached script from a terminal, it will print the button actions you clicked in the notification popup.
> 
> [notification_test.py](https://github.com/user-attachments/files/30383735/notification_test.py)

I dont have a running lxqt enviroment anymore.

**Comment by stefonarch** [comment]
Maybe in another 4 years somebody encounters this issue again and will find the script...

**Comment by FlRENADO** [comment]
> I've two installations on debian (trixie, testing) and never encountered this issue even before, so there has to be some other element involved. You can try to run the attached script from a terminal, it will print the button actions you clicked in the notification popup.
> 
> [notification_test.py](https://github.com/user-attachments/files/30383735/notification_test.py)

Running the script produces the notification, and clicking the buttons is logged in the terminal output. However when I try to send a file to my laptop from my phone the buttons on the pairing quest notification are still unclickable. 

Are there any other applications that produce notifications with buttons I can check the functionality of? That would at least see if the issue is with blueman or not.

**Comment by stefonarch** [comment]
> Are there any other applications that produce notifications with buttons I can check the functionality of? That would at least see if the issue is with blueman or not.

Thunderbird email notifications (open, mark read), element and telegram notifications (open windows) are the ones I have.

**Comment by FlRENADO** [comment]
Thunderbird notifications seem to work fine, I can click activate and it will un-minimise the application and show the email. Clicking mark as read works and so does the delete button. I don't have element or telegram installed but I turned on notifications for discord and the view button on that works too. 

This would lead me to assume that the issue is confined to blueman?

**Comment by stefonarch** [comment]
> This would lead me to assume that the issue is confined to blueman?

I think so. The original report was about the first-run message too, but as you notice only blueman doesn't work.

**Comment by stefonarch** [comment]
Another check would be testing it on XFCE.

**Comment by FlRENADO** [comment]
I had a debian 12 install with xfce and I remember that working fine historically. My other laptop has xfce but on fedora also works fine with blueman. It is just this new laptop and my main pc which have this issue on lxqt.

I have an install on an old drive with debian 12 and lxqt, I can't remember if I had issues with that or not as I only used a usb bluetooth adapter with it a couple of times.
