### ISSUE TITLE
xdg-screensaver lock cannot work

### ISSUE THREAD

**Issue by Freed-Wu** [lxqt/lxqt#2318]
##### Expected Behavior

xdg-screensaver lock cannot work

##### Current Behavior

```sh
❯ xdg-screensaver lock
❯ echo $?
4
❯ dbus-send --session --dest=org.freedesktop.ScreenSaver --type=method_call /ScreenSaver org.freedesktop.ScreenSaver.Lock
❯ echo $?
0
```

##### Steps to Reproduce (for bugs)

1. `sudo pacman -S lxqt`
2. start lxqt
3. `xdg-screensaver lock`

##### System Information

* Distribution & Version: Arch
* Kernel: 6.0.2-arch1-1
* Qt Version: libQt5Xdg.so=3-64
* liblxqt Version: 1.1.0
* Package version: 1.1.0

**Comment by tsujan** [comment]
`xdg-screensaver` is owned by `xdg-utils`, not by LXQt.
