### ISSUE TITLE
Panel clock text going off-screen since Qt5

### ISSUE THREAD

**Issue by jleclanche** [lxqt/lxqt#232]
Probably only happens with "Show date below time on new line".

**Comment by goetzc** [comment]
I see something similar using the latest code from git:
![lxqt-panel_clock](https://cloud.githubusercontent.com/assets/2220440/5593532/0d6700f4-91e2-11e4-848d-bf2dff7b8dba.png)
The left screenshot is when the panel is started, the second is when I change a setting in the worldclock, and change it back as it was at the panel start.

**Comment by agaida** [comment]
right - the same thing i described in a former bug report as dancing panel - after changes in the plugin settings stylesheet seems not to be reapplied. after a panel restart the stylesheet is applied again - which results in a different look/behaviour.
