### ISSUE TITLE
after turning off worldclock in panel, is there a way to turn it on again?

### ISSUE THREAD

**Issue by msch74** [lxqt/lxqt#2324]
once the worlclock is turned off in the panel, there seems no chance to turn it on again?

LXQt: 0.17.0
Kernel: 5.15.0-52-generic

Distributor ID: Ubuntu
Description:    Ubuntu 22.04.1 LTS
Release:        22.04
Codename:       jammy

**Comment by ecsuarez** [comment]
Did you mean delete the world clock from the panel?

**Comment by msch74** [comment]
yes, delete the worldclock

**Comment by tsujan** [comment]
Please don't use the bug tracker for questions.
