### ISSUE TITLE
"Window Grouping" popup menu disappear while moving mouse

### ISSUE THREAD

**Issue by kyon328** [lxqt/lxqt#2348]
##### Expected Behavior
- mouse hover should show popup
- while moving mouse, popup menu should keep display, otherwise I can not click items on it

##### Current Behavior
- mouse hover not show popup, have to click that tab
- popup menu will auto disappear, so I can not click the items.

##### Possible Solution
- not use that window grouping function for now

##### Steps to Reproduce (for bugs)

1. in **Task Manager Settings**, check **Window grouping** and **Show popup on mouse hover**
2. open 2 firefox window
3. try to select one firefox window through task manager bar

I recorded a [gif](https://media4.giphy.com/media/rTaClhXfYLys1WkLqz/giphy.gif?cid=790b76111bcaa316691609e172ee3405e15e485830189a23&rid=giphy.gif&ct=g) to explain that bug

##### System Information
```
       _,met$$$$$gg.          kyon@localhost 
    ,g$$$$$$$$$$$$$$$P.       -------------- 
  ,g$$P"     """Y$$.".        OS: Debian GNU/Linux bookw 
 ,$$P'              `$$$.     Host: MS-7D31 2.0 
',$$P       ,ggs.     `$$b:   Kernel: 6.0.0-5-amd64 
`d$$'     ,$P"'   .    $$$    Uptime: 6 mins 
 $$P      d$'     ,    $$P    Packages: 2130 (dpkg) 
 $$:      $$.   -    ,d$$'    Shell: bash 5.2.2 
 $$;      Y$b._   _,d$P'      Resolution: 2560x1440 
 Y$$.    `.`"Y$$$$P"'         DE: LXQt 0.16.0 
 `$$b      "-.__              WM: KWin 
  `Y$$                        Theme: Breeze [GTK2/3] 
   `Y$$.                      Icons: breeze [GTK2/3] 
     `$$b.                    Terminal: qterminal 
       `Y$$b.                 Terminal Font: Monospace 1 
          `"Y$b._             CPU: 12th Gen Intel i9-129 
              `"""            GPU: Intel AlderLake-S GT1 
                              GPU: NVIDIA GeForce RTX 30 
                              Memory: 2209MiB / 64100MiB
```

**Comment by tsujan** [comment]
Not reproducible here.

Which window manager do you use?

**Comment by kyon328** [comment]
> Not reproducible here.
> 
> Which window manager do you use?

KWin, not KWin(X11)

**Comment by tsujan** [comment]
> KWin, not KWin(X11)

You mean that you use lxqt-panel under Wayland? If so, the problem should be either in KWin-Wayland or specific to Wayland; if not, you're using KWin-X11, which I use too.

**Comment by kyon328** [comment]
> Oh, sorry, I didn't see that you had LXQt 0.16.0. It's totally outdated.
what! so sorry I didn't notice that I am using the old version lxqt. 
I install debian testing and have done apt upgrade, I thought they will use most recent package in testing branch, didn't notice this before

**Comment by tsujan** [comment]
Debian Testing ("bookworm") has [LXQt 1.1.0](https://packages.debian.org/bookworm/lxqt-about) (the latest LXQt is 1.2.0). I think you may have missed an upgrade, but I'm not a Debian user.

**Comment by tsujan** [comment]
Please also note that Debian Testing has Qt 5.15, while LXQt 0.16 should have been compiled against a much older version of Qt. Therefore, not only you may see issues that didn't exit even in LXQt 0.16.0 but also you may encounter crashes.

**Comment by kyon328** [comment]
> Debian Testing ("bookworm") has [LXQt 1.1.0](https://packages.debian.org/bookworm/lxqt-about) (the latest LXQt is 1.2.0). I think you may have missed an upgrade, but I'm not a Debian user.

oh,! my fault, I did upgrade, but some that output said some lxqt packages have kept back, I missed this output info.
now I search that message, and do force update by
`sudo apt dist-upgrade -y`
and reboot, now this issue solved!
thanks alot

**Comment by kyon328** [comment]
> > KWin, not KWin(X11)
> 
> You mean that you use lxqt-panel under Wayland? If so, the problem should be either in KWin-Wayland or specific to Wayland; if not, you're using KWin-X11, which I use too.

sorry I dont know the difference, because there are 3 default window manager options in **LXQt Session Setting** (kwin, kwin_x11,xfwm4) I said I using KWin not X11 just simply means I choose the kwin option, not kwin_x11 option.

**Comment by tsujan** [comment]
> sorry I dont know the difference

Never mind; you surely use X11. Wayland wasn't your problem.
