### ISSUE TITLE
lxqt-panel, quick launch - cannot drop applications

### ISSUE THREAD

**Issue by ArthurBorsboom** [lxqt/lxqt#235]
When I try to drag and drop an icon of an application from the start menu onto the quick launcher, I get the following error message.

![lxqt-panel-quicklaunch-error](https://cloud.githubusercontent.com/assets/6639859/3610162/4f9427b6-0d87-11e4-8b33-5007bc40ab68.png)

**Comment by jotasprout** [comment]
I have the same problem. Just installed LXQt today.

**Comment by tsujan** [comment]
@jotasprout Since I always have the latest git LXQt, I can say that this bug doesn't exist anymore. It may exist in the latest release though because, after removing menu-cache, this fix was needed: https://github.com/lxqt/libqtxdg/pull/159

**Comment by jotasprout** [comment]
@tsujan How do I get/use the latest git LXQt? I'm comfortable with linux and the terminal but -- other than managing my own repos by myself with no branches -- I'm a git newbie.

**Comment by agaida** [comment]
the answer is dead simple - use arch/manjaro with the latest AUR or debian/sid, ubuntu/cosmic with the latest release - and if you are looking for adventures - use debian/sid with the experimental/snapshots repo

**Comment by tsujan** [comment]
> How do I get/use the latest git LXQt?

It depends on the distro. You couldn't have the latest LXQt on an old distro (older than a year). Some distros -- like Debian, Arch and Arch derivatives -- support the latest git LXQt. On other distros, the user should know how to compile from the git sources or, preferably, make installable packages from the latest git for his/her distro. That's quite possible with the latest Ubuntu (18.10) but you need to be experienced in working with deb packages.

So, I recommend you first ask the Ubuntu community about the existence of a repository for the latest LXQt. Sorry that I can't be of more help; I don't have a debian base distro.

**Comment by agaida** [comment]
hihihi, i was faster :D

**Comment by tsujan** [comment]
Ha ha.....

@agaida and I replied simultaneously and, practically, said the same thing ;)

**Comment by agaida** [comment]
and if i would be honest - i would really go the arch/manjaro/antergos way and use the AUR packaging - pimped up with some infamous script :sunglasses: (And please don't tell anyone that i maintain some packages in debian)

**Comment by tsujan** [comment]
Conclusion: The easiest way is to have an up-to-date Debian, Arch or Manjaro. However, it's possible with all up-to-date distros, although not so easily.

**Comment by agaida** [comment]
running LXQt-Git is bleeding edge - for mere humans who are not developers and want a stable system without surprises i would recommend any current distro that provide our latest release. If one want all the new and shiny bugs that wait for discovery: run bleeding with daily updates.
