### ISSUE TITLE
emacsclient popup frame is hidden when no window is shown

### ISSUE THREAD

**Issue by QiangF** [lxqt/lxqt#2362]
I am trying to use emacs as a popup selector with fuzzy matching, it only works when there is a window.

The popup emacs frame has desktop id -1.

I have put all the required files at
https://gist.github.com/QiangF/f3ca62cc24b5b5792393eeead07591d7

**Comment by QiangF** [comment]
This happens when the focus is on the desktop, it even works when the focus is on the lxqt-panel and all other windows are minimised.

**Comment by tsujan** [comment]
Do you mean "window decoration" by "frame"?

Also, a screen cast might be helpful.

**Comment by QiangF** [comment]
I think I have found the cause. It's openbox show desktop mode. In that mode, only window of dock type is shown, and of course the desktop. To solve it, we have to replace openbox or disable show desktop mode before run emacsclient.

**Comment by tsujan** [comment]
OK.

FYI, LXQt by no means has control over window decoration; that's the job of WM.
