### ISSUE TITLE
Volume icon is not the expected one

### ISSUE THREAD

**Issue by papoteur-mga** [lxqt/lxqt#2364]
##### Expected Behavior
Sound icon should be a speaker

##### Current Behavior
With Breeze theme, I get a red box with a cross in it and a appendix at bottom. By changing theme, I never get a speaker.

##### Steps to Reproduce (for bugs)
Installation in Mageia Cauldron
We provide a custom panel.conf : https://svnweb.mageia.org/packages/cauldron/lxqt-panel/current/SOURCES/panel.conf?view=markup

##### Context
At start

##### System Information
* Distribution & Version: Mageia Cauldron
* Qt Version: 5.15.7
* liblxqt Version: 1.2.0
* Package version: 1.2.1

**Comment by tsujan** [comment]
Not reproducible.

Maybe the icon is black on a black background in your case; change the LXQt theme to check that. If it isn't the case, you could add more info to this page. Also, a screenshot might help.

**Comment by papoteur-mga** [comment]
After further investigation, the icon displayed is dialog-error.
And I understood this is because sound backend is not started.
Ok for closing.

**Comment by tsujan** [comment]
> And I understood this is because sound backend is not started.

Yes, if the icon is dialog-error.
