### ISSUE TITLE
Rotate touchscreen with monitor

### ISSUE THREAD

**Issue by dieselnutjob** [lxqt/lxqt#2370]
**Is your feature request related to a problem? Please describe.**

If I rotate the screen (Monitor settings, Advanced, Rotation) then the touchscreen doesn't rotate with it.  This results in touchscreen presses not registering on the correct part of the screen when the screen is rotated.  This is important for touchscreen devices like tablet computers.

**Describe the solution you'd like**

Please rotate the touchscreen when the monitor is rotated, like KDE does.

**Describe eventual alternatives you've considered**

##### Context

I am testing RK3566 tablets with Linux on them.  LXQT work very nicely on the these devices but the touchscreen is not usable with the screen is rotated, which is necessary when the clip on keyboard/trackpad is used.

**Comment by dieselnutjob** [comment]
I forget to mention that one of my tablets has an HDMI output, so supports multiple screens.  It might be that the user wants to rotate/not rotate one monitor differently to the others.  Therefore there would need to be a way in monitor settings to define which monitor rotation would also rotate the touchscreen and which would not.  I guess....

**Comment by tsujan** [comment]
> like KDE does

A dev having a similar hardware is needed ;)

Having no touchscreen device, I don't know whether this question is relevant: Are you sure that it isn't related to WM? Have you tested with KWin under LXQt?

**Comment by dieselnutjob** [comment]
If I go to Configuration Center, Session Settings, Basic Settings, Window Manager  it already says kwin

**Comment by tsujan** [comment]
Thanks. So, the WM is irrelevant.

Hopefully a dev or contributor with a similar device will work on it.

**Comment by stefonarch** [comment]
Maybe useful in this context: https://gist.github.com/mildmojo/48e9025070a2ba40795c

**Comment by shlyakpavel** [comment]
> Hopefully a dev or contributor with a similar device will work on it.

I daily work with touchscreen devices and, based on my experience, this is an extremely complicated job. Let's say you have two monitors connected over HDMI and two touch sensors on them connected via USB. How do you know what input device belongs to what monitor? There's no automatic way to do that unless you know exact device IDs.

The other issue are both wayland and x11. On x11, one can use tslib, evdev or libinput for touch panel. All 3 have different rotation settings! Some of these even require transformation matrix that doesn't seem to be portable. I have also met some weird panels that require custom proprietary driver working in userspace and triggering uinput..
On wayland, things differ between compositors and I do not know a way to configure rotation that suits all environments.

**Comment by shlyakpavel** [comment]
I'd also point out that this issue seems to duplicate https://github.com/lxqt/lxqt/issues/1667

**Comment by tsujan** [comment]
> I'd also point out that this issue seems to duplicate #1667

Right.

**Comment by borisalekseev** [comment]
I ran into this problem when working with a lubuntu+ lxqt tablet. To automatically rotate the screen along with the touchscreen at startup, I did the following:

```bash
# rotate on startup
ROTATE_LEFT_FILE="$HOME/.config/autostart/auto-rotate-left.desktop"

cat > "$ROTATE_LEFT_FILE" <<EOL
[Desktop Entry]
Type=Application
Exec=xrandr -o left
NoDisplay=true
X-GNOME-Autostart-enabled=true
EOL

chmod +x "$ROTATE_LEFT_FILE"

# rotate touchscreen
SCREEN_CONF_FILE="/etc/X11/xorg.conf.d/99-touchscreen.conf"

sudo mkdir -p /etc/X11/xorg.conf.d/

sudo tee "$SCREEN_CONF_FILE" > /dev/null <<EOL
Section "InputClass"
        Identifier "ff_touchscreen"  # maybe different name in your device
        MatchIsTouchscreen "on"
        Driver "libinput"
	    Option "CalibrationMatrix" "0 -1 1 1 0 0 0 0 1"  # rotate left in my device, google it
EndSection
EOL
```

But the problem remained, because on my device, in $HOME/.config/autostart, there was also an autorun command that applied the lxqt config, it kept knocking down the screen orientation. I solved it by deleting it:

```bash
rm $HOME/.config/autostart/lxqt-config-monitor-autostart.desktop
```

**Comment by stefonarch** [comment]
I think Wayland configurations offer better possibilities, in any compositor. But Kwin should have a good GUI for it, but no idea on X11.

The .desktop file could be dis-activated also in "Session Settings → Autostart".
