### ISSUE TITLE
nm-tray calls xterm

### ISSUE THREAD

**Issue by eriefisher** [lxqt/lxqt#2379]
##### Expected Behavior

nm-tray>>edit connections>>nm-connection-editor
##### Current Behavior

nm-tray>>edit connection>>xterm -e nmtui
##### Possible Solution

I did not have xterm installed by default so nm-tray>>edit-connections did nothing. I suggest either pointing nm-tray>>edit-connection directly to an installed/prefered default terminal or even better point it to nm-connection-editor. Since it's being initiated in the graphical environment and the graphical tools are provided it would make sense that they work together
##### Steps to Reproduce (for bugs)

1. Right click on nm-tray, "select edit connection". If you have xterm installed it will open nmtui. If not, nothing will happen.
2. 0.5.0-1 amd64
3. 
4. 

##### Context

Unexpected behaviour. Mixes graphical and cli interactions uneccessarily.
##### System Information

* Distribution & Version: Siduction MOW, Debian Bookworm/sid
* Kernel: 6.1.10-1-siduction-amd64
* Qt Version: 5.15.8
* liblxqt Version: liblxqt1 1.2.0-5 amd64
* Package version: 0.5.0-1 amd64

**Comment by stefonarch** [comment]
nm-tray repo is here:
https://github.com/palinek/nm-tray

**Comment by eriefisher** [comment]
I and running the latest version from Debian/Sid. It appears to be the same version available through git. Am I wrong?
