### ISSUE TITLE
customization of the background-color of the application switcher

### ISSUE THREAD

**Issue by ralf3u** [lxqt/lxqt#2390]
I'm using a black/white display.
When I use the task-switcher with Alt+Tab, then I don't know which task is active when switching within the application switcher, because the background-color is too dark.
I tried to change LXQt-Theme. But the application switcher stays dark.

**Comment by tsujan** [comment]
Which LXQt theme, which version?

**Comment by tsujan** [comment]
Also, please attach a screenshot. Without it, we might speak about different things.

**Comment by ralf3u** [comment]
>Which LXQt theme, which version?

Sorry, I forgot to mention. Lubuntu 22.04.1 with LXQt 0.17.0. LXQt-Theme Light.

I didn't make a screenshot, else one can not see what I see, because the display is connected to a notebook. So, I made a photo from the display:

![display](https://user-images.githubusercontent.com/68117017/224158512-eb35ae8b-fdee-451a-b081-8c7149051730.jpg)

What I would like also to mention is that the font-size is also very small, and also the icons are very small. So, maybe it would be good, if also font-size and the icons could be customizable.

**Comment by tsujan** [comment]
LXQt doesn't have an app switcher. You need to find the app; If its name is `LXQt application switcher`, report the problem here: https://github.com/zjes/lxqt-appswitcher. It doesn't belong to LXQt.

**Comment by ralf3u** [comment]
@tsujan

Is there an alternative in LXQt for LXQt application switcher?
Which application-switcher do you use?

**Comment by tsujan** [comment]
Sadly, no. LXQt doesn't provide an app switcher.

> Which application-switcher do you use?

I use kwin, which has its own tools (more than one way) -- I like to use it with KWin's "hot corners".

**Comment by ralf3u** [comment]
I installed today Lubuntu 22.10 with LXQt 1.1.0. I changed the LXQt-Theme to Light (GTK theme Arc-Darker is default, that I don't change). Then everything is fine: In Firefox the tab that is in focus is in white, while the other tabs are gray. And in the lxqt-application-switcher I can see a rectangle around one icon, so I know which application is in focus. Then I go with the computer in suspend. After the suspend the theme is not like before: the background-color of the not-focused tabs are not the same (there are black, so can't read the title of the tabs), and in the application-switcher I can't see the rectangle around the icon because the background-color is too dark. Should I open a new issue, or do you say `No, there is no need because of this and that`?
By the way: In Lubuntu 22.04.1 there is the same problem.

**Comment by tsujan** [comment]
In no way LXQt can affect Firefox.

> Should I open a new issue, or do you say No, there is no need because of this and that?

You should use ubuntu/lubuntu bug tracker for things that aren't related to LXQt..

**Comment by stefonarch** [comment]
If you didn't compile yourself "lxqt-appswitcher" you are  using the appswitcher provided by the window manager (should be openbox on Lubuntu). LXQt themes do not affect those appswitchers, openbox theme probably do. https://discourse.lubuntu.me/ is the place to discuss those things probably.

**Comment by ralf3u** [comment]
@stefonarch 
>LXQt themes do not affect those appswitchers, openbox theme probably do.

This is what I did:
Main menu, Preferences, Openbox Settings:
In `Theme` I changed the value from `Lubuntu Arc` to `Breeze-ob`.
Now I can see again in the LXQt-application-switcher which application is in focus.

Thank you so much for your help!
