### ISSUE TITLE
Racecondition on window move moves window to (0,0)

### ISSUE THREAD

**Issue by ManuelSchneid3r** [lxqt/lxqt#2402]
##### Expected Behavior
If a window is moved by QWidget::move(x,y) with x,y not beeing 0, it should end up there.

##### Current Behavior
Window opens at 0,0

##### Steps to Reproduce (for bugs)
https://github.com/albertlauncher/plugins/issues/99#issuecomment-1488455053

##### Context
The issue mentioned contains a good amount of information.

##### System Information
```
            Qt version: 6.4.3
             Build ABI: x86_64-little_endian-lp64
  Arch (build/current): x86_64/x86_64
 Kernel (type/version): linux/6.2.8-arch1-1
                    OS: Arch Linux
     OS (type/version): arch/unknown
 $QT_QPA_PLATFORMTHEME: lxqt
         Platform name: xcb
                  Font: Sans Serif,9,-1,5,400,0,0,0,0,0,0,0,0,0,0,1
       Binary location: /usr/bin/albert
                  $PWD: /home/someusername
                $SHELL: /bin/zsh
                 $LANG: en_DK.UTF-8
              Language: C
                Locale: C
     $XDG_SESSION_TYPE: x11
  $XDG_CURRENT_DESKTOP: LXQt
      $DESKTOP_SESSION: lxqt
  $XDG_SESSION_DESKTOP: lxqt
            Icon theme: hicolor
```

@uffejakobsen can you please provide the last two liblxqt and its package version?

**Comment by tsujan** [comment]
LXQt doesn't position windows; the window manager does.

**Comment by tsujan** [comment]
FYI:

To circumvent WM problems, the geometry of a normal window can be set inside `showEvent()` with the first non-spontaneous show event.

As the last resort and with buggy WMs, the window can be positioned inside `moveEvent()` *very carefully*, by using a `QTimer::singleShot` and checking `QEvent::spontaneous()` before it (an infinite loop will happen without that check — this method is dangerous).
