### ISSUE TITLE
"Open directory" starts random apps instead

### ISSUE THREAD

**Issue by Marco-Sulla** [lxqt/lxqt#2406]
##### Steps to reproduce
1. open Firefox
2. Download a file
3. Click on the download icon
4. click on the folder icon next to the downloaded file name

##### Expected Behavior
Firefox should open PCMan at the directory of the downloaded file 

##### Current Behavior
Disk Usage Analyzer starts instead.

Disk Usage Analyzer is not started by all programs. For example, Nicotine starts Skype instead.

##### System Information
* Distribution & Version: Lubuntu 22.04
* Kernel: `Linux buzz 5.15.0-69-generic #76-Ubuntu SMP Fri Mar 17 17:19:29 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`
* Qt Version: libqt5core5a 5.15.3+dfsg-2ubuntu0.2
* liblxqt Version: 0.17.0-0ubuntu1
* Package version: firefox 111.0.1

**Comment by stefonarch** [comment]
0.17 is completely outdated, updating to 1.2 is recommended
https://lubuntu.me/jammy-backports-22-04-1-lxqt-1-2/

Btw it looks like a file associations issue in your installation.

**Comment by tsujan** [comment]
Also → https://github.com/lxqt/libqtxdg/issues/264

**Comment by Marco-Sulla** [comment]
> Btw it looks like a file associations issue in your installation.

Thank you, I changed it in "Start menu" -> Preferences -> LxQT settings -> File association -> inode -> directory. The file is not selected, but I can live with it.

PS: it's a bit strange, since I upgraded recently from 18.04 to 20.04 and then to 22.04. I had no problem with 18.04.
