### ISSUE TITLE
Background not updated

### ISSUE THREAD

**Issue by papoteur-mga** [lxqt/lxqt#2408]
##### Expected Behavior
The desktop background displayed is the one registered and referenced in settings

##### Current Behavior
If I replace the image that is referenced (the path isn't changed), the background stays with the previous image.

##### Context
I pointed the image to the background provided by the distribution. The distribution updated the image, but the background didn't change. I have to switch to another image, then come back to the first one to have to new one.

##### System Information
* Distribution & Version: Mageia cauldron
* Kernel: 6.2
* Qt Version: 5.15
* liblxqt Version: 1.3.0

**Comment by tsujan** [comment]
> If I replace the image that is referenced (the path isn't changed), the background stays with the previous image.

The app doesn't watch the image but uses its cache. Watching files would be justified only if it was worth the cost.

**Comment by papoteur-mga** [comment]
Is there a command that can be used from an external trigger to update the cache?

**Comment by tsujan** [comment]
The command-line option is `--set-wallpaper` (see `pcmanfm-qt --help`), but the code checks the path and other parameters and does nothing if they aren't changed. That's intentional, of course.

If you change/edit the image without changing its name/path, you could either restart Desktop in LXQt Session Settings or first change and then restore the path in front of `pcmanfm-qt --set-wallpaper `.

**Comment by papoteur-mga** [comment]
I see I wasn't clear enough in my first message. The cache is not updated even after a reboot.
My concern is as packager for LXQt in Mageia. We prepare a new release of Mageia, and I expect that users that use the default background see the difference after the upgrade and a reboot.
I don't understand what is `restarting Desktop in LXQt Session Settings`.

**Comment by tsujan** [comment]
> The cache is not updated even after a reboot.

That's bad. I'm opening an issue at https://github.com/lxqt/pcmanfm-qt/issues.

For now, remove the cache from `/home/pedram/.cache/pcmanfm-qt` and restart Desktop in Session Settings (no reboot or logout is needed).

> I don't understand what is restarting Desktop in LXQt Session Settings.

LXQt Session Settings → Basic Settings → LXQt Modules → Choose "Desktop", click "Stop" and then click "Start" after a second or so.

**Comment by tsujan** [comment]
Opened https://github.com/lxqt/pcmanfm-qt/issues/1764

**Comment by tsujan** [comment]
The fix is here: https://github.com/lxqt/pcmanfm-qt/pull/1765
