### ISSUE TITLE
switching between apps(Alt + Tab) allows apps from other desktops as well 

### ISSUE THREAD

**Issue by sapienfrom2000s** [lxqt/lxqt#2412]
If an app(say brave browser) is sent to another desktop(say 2) and we are working on desktop 1.

##### Expected Behavior

Using Alt + Tab shouldn't show the brave browser in the options.

##### Current Behavior

It shows brave browser in the options.

##### Steps to Reproduce (for bugs)

1. Open any number of apps including  X.
2. Send X to desktop 2
3. Be present in desktop 1.
4. Use keybinding Alt + Tab, you'll see X. 

##### Context

If I am working on a project but also have opened spotify. But I don't want to see spotify
while I am say switching between say terminal, firefox and sublime. I also don't want to close
spotify as it is playing my favourite songs.

##### System Information

* Distribution & Version: Lubuntu 22.04.2 LTS x86_64
* Kernel: 5.15.0-69-generic
* Qt Version: LXQt 0.17.1
* liblxqt Version: LXQt 0.17.1
* Package version: don't know

**Comment by stefonarch** [comment]
Virtual desktop and alt+tab windows switcher are handled by the window manager (openboxby default in Lubuntu) and not by LXQt. Maybe kwin has rules to exclude other  desktops for app switcher. 

Updating to 1.2 should be considered anyway.
https://lubuntu.me/jammy-backports-22-04-1-lxqt-1-2/
