### ISSUE TITLE
Add the Wing Menu to the "Third party apps" wiki page

### ISSUE THREAD

**Issue by Gnomasz** [lxqt/lxqt#2418]
##### Expected Behavior
There is an alternative menu plugin for lxqt-panel called [_Wing Menu_](https://github.com/elviosak/plugin-wingmenu). It has been a topic in _Discussions_ already. It would be nice if its visibility was improved by addition to the [_Third party apps_ page ](https://github.com/lxqt/lxqt/wiki/Third-party-apps) in the project's wiki.

##### Current Behavior
The plugin can only be discovered by diving into _Discussions_ or by very specific search queries.

##### Possible Solution
Adding the plugin to the _Complementary tools geared towards LXQt/UI_ section.

##### System Information
The [LXQt Wiki on Github](https://github.com/lxqt/lxqt/wiki)

**Comment by stefonarch** [comment]
Good point, while still waiting of @elviosak to reemerge.
Done https://github.com/lxqt/lxqt/wiki/Third-party-apps#wing-menu
