### ISSUE TITLE
lxqt-panel - - - it seems to die when its tasked to work hard

### ISSUE THREAD

**Issue by dabeegmon** [lxqt/lxqt#2440]
Greetings

Running some 32 lxqt packages according to my dpkg -l  list. 

On a Ryzen 7 5800X proc with a Radeon RX570X running 4 - 1920 x
1080 displays and 1 - 4k (3180x2160) running Linux 
6.1.0-9-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.27-1 (2023-05-08)
x86_64 GNU/Linux (Daedalus). In case it matters I've also got lxdm as
a window manager and I've got a total of 46 virtual desktops (ja more
than a few but its a great way to separate different projects/ideas so
I use it - - - LOTS!)

When I'm tasking the display manager - - -ie running something like FreeCAD 
the life of the display manager is measured in days. Last time it was 
less than 4 calendar days from reboot to reboot. 

Issue shows up when I return to my system and try to restart the desktop. 
The monitors come back to life but the panels have disappeared. (I am using 3 panels, 
one with the desktop switcher across the bottom, a second has system temperatures 
and date/time with the third listing the packages in use. 

I have spent time in the past and there are no limits imposed by Kwin (that I can find) 
or in any of the other parts of this chain.  

I it would be possible I would like to have a robust desktop where uptime is measured 
in months rather than in days. If there are things that I could test to assist any developer 
working on upgrading this area please advise. 

* Distribution & Version: 
answered in first paragraph
* Kernel: 
same
* Qt Version: 
5.15.8  (I think - - -t here is no Qt version - - - rather there are libqt5*** packages - - - lots!!!)
* liblxqt Version: 
1.2.0-8
* Package version: 
1.2.0-1

**Comment by tsujan** [comment]
I'm afraid this is neither a bug report nor a feature request. The template exists for a reason.

If you have general questions, use [Discussions](https://github.com/lxqt/lxqt/discussions).

**Comment by tsujan** [comment]
If you have problem when you use 46 virtual desktops with KWin, you might want to report it to its developers. As far as I remember, KWin supports 20 at most.

A bug report should be about an LXQt component and include a way of reproducing it, clearly and concisely.

**Comment by dabeegmon** [comment]
KWin does NOT have a listed virtual desktop limitation.

**Comment by tsujan** [comment]
→ kwin → /src/scripting/workspace_wrapper.h:

```cpp
    /**
     * The number of desktops currently used. Minimum number of desktops is 1, maximum 20.
     */
    Q_PROPERTY(int desktops READ numberOfDesktops WRITE setNumberOfDesktops NOTIFY numberDesktopsChanged)
```

→ https://develop.kde.org/docs/plasma/kwin/api/#kwinworkspacewrapper
