### ISSUE TITLE
Wifi does not work anymore

### ISSUE THREAD

**Issue by Marco-Sulla** [lxqt/lxqt#2449]
##### Current Behavior
I'm not able to connect to wifi after an update. I don't know which package update make the problem. 

##### Context
To fix the issue, I tried to upgrade from 20.04 to 22.04 with backports repo, but the problem persist.

As you can see in the image, wifi connection are not even listed:

![image](https://github.com/lxqt/lxqt/assets/13075999/1c68da87-df2c-44a0-8a6b-3ed77262922f)

Wifi is enabled and I tried also to scan for wifi networks. The OS never needed a proprietary driver, and a proprietary driver for wifi is not even listed.

##### System Information
* Distribution & Version: Ubuntu 22.04.2 LTS
* Kernel: `Linux 5.15.0-76-generic #83-Ubuntu SMP Thu Jun 15 19:16:32 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`
* Qt Version: 5.15.3-1
* liblxqt Version: 1.2.0-0ubuntu1~ppa1
* Package version: ?

**Comment by tsujan** [comment]
You might want to report this to Ubuntu. LXQt has no app of its own for connecting to Wifi (as it has no browser, media player, etc.).
