### ISSUE TITLE
[libfm-qt/pcmanfm-qt] Removing a bookmark from the side pane in pcmanfm-qt deletes bookmark in lxde-pcmanfm-gtk2

### ISSUE THREAD

**Issue by maplee0** [lxqt/lxqt#2450]
Hello. Why is it happening? Do both original pcmanfm/libfm and pcmanfm-qt/libfm-qt use the same data files? I thought it should have different conf and data files. Debian 11, pcmanfm-qt 0.16.

**Comment by stefonarch** [comment]
Here they are in `~/.config/gtk-3.0/bookmarks` and are shared by apps.
