### ISSUE TITLE
Desktop cannot launch applications after long periods of "idle"

### ISSUE THREAD

**Issue by JamesShriner** [lxqt/lxqt#2488]
##### Expected Behavior

Applications should launch without issue
##### Current Behavior

Applications do not launch.  Not from menu, not from lxqt-panel quick launchers, not from WM (fluxbox) root menu.  If an application is already open (such as qterminal), that application works; but no new instances.  attempting to launch applications from qterminal fails, but with error message:
Maximum number of clients reached
Error: cannot open display: :0
##### Possible Solution

This appears to be an issue with lxqt-config-monitor on a brand new installation to a refurbed Lenovo ThinkCentre m715q.  Brand new installations on other machines have no such issues.  Testing other LiveUSBs on the problem machine indicate the problem is limited to LXQT desktop.  Other Debian distros did not exhibit same behavior.
##### Steps to Reproduce (for bugs)

1. open qterminal (for troubleshooting after wake from idle)
2. Allow system to idle, and screen to darken
3. Wake system with mouse/keyboard event
4. attempt to launch new GUI application (menu, launcher, rootmenu.....all fail)
5. attempt to launch from terminal prompt (error message indicated above)
6. xrestop command indicates "monitoring 256 clients" (the maximum limit?) with NUMEROUS xerrors
7. lsof -U provides list of running files/processes on system
8. pkill "process name" (lxqt-conf according to lsof command)
9. xrestrop indicates "monitoring 40 clients" with NUMEROUS xerrors
10. application launch is restored (via all options, menu, launcher, root menu, and terminal)
11. allow system to idle and repeat ad nauseum

##### Context

This issue makes LXQT unusable on this machine....my PRIMARY machine.  It looks like a workaround is to increase the number of xclients allowed in xsession, but that seems like it will only "increase the headroom" and result in the same issue, but longer intervals
##### System Information

* Distribution & Version: Debian 12 Bookworm
* Kernel: 6.1.0-13
* Qt Version: 1.2
* liblxqt Version: ??  not sure where to find this
* Package version: ?? not sure where to find this
* Inxi -Fxz provides following (I suspect Ryzen5 RavenRidge/Vega hardware may be an issue here, and 2019 BIOS was updated to June 2023 BIOS, but with no change in behavor):
* System:
  Kernel: 6.1.0-13-amd64 arch: x86_64 bits: 64 compiler: gcc v: 12.2.0
    Desktop: LXQt v: 1.2.1 Distro: Debian GNU/Linux 12 (bookworm)
Machine:
  Type: Mini-pc System: LENOVO product: 10VHS17600 v: ThinkCentre M715q
    serial: <superuser required>
  Mobo: LENOVO model: 3130 v: SDK0J40697 WIN 3305183174933
    serial: <superuser required> UEFI: LENOVO v: M1XKT62A date: 06/21/2023
CPU:
  Info: quad core model: AMD Ryzen 5 PRO 2400GE w/ Radeon Vega Graphics
    bits: 64 type: MT MCP arch: Zen rev: 0 cache: L1: 384 KiB L2: 2 MiB
    L3: 4 MiB
  Speed (MHz): avg: 1574 high: 1600 min/max: 1600/3200 boost: enabled cores:
    1: 1538 2: 1600 3: 1454 4: 1600 5: 1600 6: 1600 7: 1600 8: 1600
    bogomips: 51104
  Flags: avx avx2 ht lm nx pae sse sse2 sse3 sse4_1 sse4_2 sse4a ssse3 svm
Graphics:
  Device-1: AMD Raven Ridge [Radeon Vega Series / Radeon Mobile Series]
    vendor: Lenovo driver: amdgpu v: kernel arch: GCN-5 bus-ID: 04:00.0
    temp: 48.0 C
  Display: x11 server: X.Org v: 1.21.1.7 driver: X: loaded: amdgpu
    unloaded: fbdev,modesetting,vesa dri: radeonsi gpu: amdgpu
    resolution: 1920x1080~60Hz
  API: OpenGL v: 4.6 Mesa 22.3.6 renderer: AMD Radeon Vega 11 Graphics
    (raven LLVM 15.0.6 DRM 3.49 6.1.0-13-amd64) direct-render: Yes
Audio:
  Device-1: AMD Raven/Raven2/Fenghuang HDMI/DP Audio driver: snd_hda_intel
    v: kernel bus-ID: 04:00.1
  Device-2: AMD ACP/ACP3X/ACP6x Audio Coprocessor driver: snd_pci_acp3x
    v: kernel bus-ID: 04:00.5
  Device-3: AMD Family 17h/19h HD Audio vendor: Lenovo driver: snd_hda_intel
    v: kernel bus-ID: 04:00.6
  API: ALSA v: k6.1.0-13-amd64 status: kernel-api
  Server-1: PulseAudio v: 16.1 status: active
Network:
  Device-1: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet
    vendor: Lenovo driver: r8169 v: kernel port: f000 bus-ID: 01:00.0
  IF: eth0 state: up speed: 1000 Mbps duplex: full mac: <filter>
  Device-2: Intel Wireless-AC 9260 driver: iwlwifi v: kernel bus-ID: 02:00.0
  IF: wlan0 state: down mac: <filter>
Bluetooth:
  Device-1: Intel Wireless-AC 9260 Bluetooth Adapter type: USB driver: btusb
    v: 0.8 bus-ID: 3-1.4:3
  Report: hciconfig ID: hci0 rfk-id: 1 state: up address: <filter> bt-v: 3.0
    lmp-v: 5.1
Drives:
  Local Storage: total: 238.47 GiB used: 21.17 GiB (8.9%)
  ID-1: /dev/nvme0n1 vendor: Samsung model: MZVLB256HAHQ-000L7
    size: 238.47 GiB temp: 34.9 C
Partition:
  ID-1: / size: 233.38 GiB used: 21.15 GiB (9.1%) fs: ext4 dev: /dev/nvme0n1p2
  ID-2: /boot/efi size: 299.4 MiB used: 20 MiB (6.7%) fs: vfat
    dev: /dev/nvme0n1p1
Swap:
  ID-1: swap-1 type: file size: 512 MiB used: 0 KiB (0.0%) file: /swapfile
  ID-2: swap-2 type: zram size: 13.84 GiB used: 0 KiB (0.0%) dev: /dev/zram0
Sensors:
  System Temperatures: cpu: 47.6 C mobo: N/A gpu: amdgpu temp: 47.0 C
  Fan Speeds (RPM): N/A
Info:
  Processes: 269 Uptime: 11h 54m Memory: 14.57 GiB used: 2.21 GiB (15.2%)
  Init: systemd target: graphical (5) Compilers: gcc: 12.2.0 Packages: 2084
  Shell: Bash v: 5.2.15 inxi: 3.3.26

**Comment by stefonarch** [comment]
This is hardly an LXQt issue but (my guess) an environment one:

> Error: cannot open display: :0

What do you see with `env |grep -i display` in this condition?

Moving to "Discussions".
