### ISSUE TITLE
Terminal dosen't open 

### ISSUE THREAD

**Issue by theblackattacker** [lxqt/lxqt#2493]
##### Context

The qterminal dosen't work at all , when i try to open it , it dosen't open ever .. 

i can't use the system without the Terminal 

other app open corectoly , but only the Terminal doesent open , sometimes when i keep pressing on the icon , it open only for less then a second then immediatly disappear 

##### System Information
LXQt Desktop Toolbox - Technical Info<p>
  LXQt About Version:     0.16.0
  LXQt Version:           0.16.0
  Qt:                     5.15.2
  Build type:             Release
  System Configuration:   /etc/xdg
  Share Directory:        /usr/share/lxqt
  Translations:           /home/w/.local/share/lxqt/translations<br>
/usr/local/share/lxqt/translations<br>
/usr/share/lxqt/translations

User Directories
  Xdg Data Home:          /home/w/.local/share
  Xdg Config Home:        /home/w/.config
  Xdg Data Dirs:          /home/w/.local/share:/usr/local/share:/usr/share
  Xdg Cache Home:         /home/w/.cache
  Xdg Runtime Home:       /run/user/
  Xdg Autostart Dirs:     /etc/autostart<br>
/etc/xdg/autostart<br>
/usr/share/autostart
  Xdg Autostart Home:     /home/w/.config/autostart

**Comment by tsujan** [comment]
0.16.0 is outdated. The latest release is 1.4.0. Please upgrade.

**Comment by theblackattacker** [comment]
how can i upgrade without using Terminal ?

**Comment by tsujan** [comment]
It depends on your distro.

**Comment by theblackattacker** [comment]
how can i send it to u ?

**Comment by theblackattacker** [comment]
and how can i get it

**Comment by tsujan** [comment]
You may have Ubuntu, Debian, Arch, Fedora...; these are called "distros", and each one of them has its own way of package management.

I'm converting this page to a discussion.... There are users who could explain these things to you much better, especially those with the same distro.
