### ISSUE TITLE
[lxqt-session] [lxqt-leave] Cannot shutdown with OpenRC

### ISSUE THREAD

**Issue by gfgit** [lxqt/lxqt#2496]
##### Expected Behavior

Hello, I'm testing LXQt on PostmarketOS which uses OpenRC init system.
LXQt is built from source at current master (1.4.0)
OpenRC has two commands: `poweroff` and `reboot` to shutdown and reboot.
Unfortunately they must be run from super user so `sudo poweroff` which is not suitable to be run from `lxqt-leave`.
Expected behavior is that `lxqt-leave` makes a DBus call to `lxqt-session` daemon which has super user priviledges.
Then the daemon executes custom commands defined at `/usr/share/lxqt/power.conf`

##### Current Behavior

Unfortunately `CustomProvider` power provider is added before `LXQtProvider` in [lxqtpower.cpp#L41](https://github.com/lxqt/liblxqt/blob/7eaea6c9461444f92799310040bc1a56d47880d2/lxqtpower/lxqtpower.cpp#L41)
This means:

1. `lxqt-leave` will try custom command and return true (the command starts succesfully, being detached it does not check exit code).
2. Session does not end because `poweroff` is not run as root
3. `lxqt-session` does not have a chance to execute the same `CustomProvider` as root because it's after in the providers list.
4. Nothing appens, session is still running

##### Possible Solution

The easiest solution is to change provider order/priority. `LXQtProvider` should be moved on top, before `CustomProvider`.
This changes behavior for already existing installations so must check if there are side effects.
It should not be a security vulnerability because command executed as root (`power.conf`) are stored in a file which only root can edit, so the root user could have run them already.

This has the added benefit that `LXQtProvider` also calls `logout(false)` before running the custom command, so it should give a chance to quit apps more gracefully (as comment says above function definition)

Other than that, I understand reusing code is good but I don't like this pattern of daemon and user dialog using the same exact code. This has led to `useLxqtSessionProvider` flag to avoid infinite recursion (or even crash?) of `LXQtProvider` calling itself.

##### Steps to Reproduce (for bugs)

1. Run `lxqt-leave` dialog
2. Press shutdown button
3. Nothing happens

##### Context
Must shutdown from terminal which is really annoying from a phone.

##### System Information

* Distribution & Version: PostmarketOS edge (Alpine Linux)
* Kernel: 3.4 on phone, 6.6 in QEMU
* Qt Version: 5.15
* liblxqt Version: 1.4.0
* Package version: 1.4.0

**Comment by tsujan** [comment]
This seems like a duplicate of https://github.com/lxqt/lxqt-session/issues/272

**Comment by gfgit** [comment]
I'm really confused about issues on main repository and issues on specific repositories.
Anyway this is about the CustomProvider, not the ConsoleKit

**Comment by tsujan** [comment]
> I'm really confused about issues on main repository and issues on specific repositories.

When users aren't sure to which components their reports are related, they might use this tracker.

**Comment by gfgit** [comment]
Closing in favor of better worded [lxqt/lxqt-session#485](https://github.com/lxqt/lxqt-session/issues/485)
