### ISSUE TITLE
lxqt does not respect configuration from /etc/lxqt and /etc/pcmanfm-qt/lxqt/settings.conf

### ISSUE THREAD

**Issue by doktor5000** [lxqt/lxqt#250]
What is currently being ignored from configs under /etc
- setting a wallpaper in /etc/pcmanfm-qt/lxqt/settings.conf -> it is not shown, neither is the one from the currently selected theme, also see https://github.com/lxde/lxde-qt/issues/156
  -> after right-click on desktop and setting the mode, wallpaper will be shown. That mode is already set in /etc/pcmanfm-qt/lxqt/settings.conf
- customizing the default panel in /etc/lxqt/panel.conf
  -> effectively I get the showdesktop widget and another quicklaunch widget, but quicklaunch widget does not contain the launchers it should contain - configuration is directly copy&pasted from ~/.config/lxqt/panel.conf so it's valid and should be working
- default panel conf in lxqt-panel tarball panel/resources/panel.conf uses different syntax for apps= then the one generate by lxqt-panel when configuring a panel. What is valid here? / or \ as separator, or are both valid? And what should be used, names of .desktop files or full path?

**Comment by agaida** [comment]
ancient - implemented in newer Qt versions
