### ISSUE TITLE
Not all available Adwaita icons are applied

### ISSUE THREAD

**Issue by isf63** [lxqt/lxqt#2504]
Upon creating a few PRs to add menus icons coexisting in the Adwaita and KDE icon themes to LXQt, I noticed when applying the Adwaita theme from Appearance Config that some icons do not get applied despite existing in the theme.

Examples:
- The top-right New Tab button in PCManFM-Qt is not applied - exists in `.../Adwaita/symbolic/actions/tab-new-symbolic.svg`.

- Menu icons are hardly populated with Adwaita - icons such as `edit-cut`, `edit-copy`, and `edit-paste` are not applied. However, they exist in `.../Adwaita/symbolic/actions/*-symbolic.svg`.

- Many more...

I don't know if this is reproducible or just on my installation. However, it may affect other icon themes besides Adwaita as well.

##### Possible Solution
Apply symbolic variants when non-symbolic icons are not available.

##### Steps to Reproduce (for bugs)
1. LXQt Appearance Config -> Apply Adwaita icons theme.
2. See examples above.

##### System Information
* Distribution & Version: Arch Linux
* Qt Version: 5.15.11+kde+r147
* liblxqt Version: 1.4.0

**Comment by tsujan** [comment]
LXQt follows `freedesktop.org`, not GNOME. In no way `tab-new-symbolic` should be used instead of `tab-new`.
