### ISSUE TITLE
Icons-only Task Manager and Global Menu

### ISSUE THREAD

**Issue by AzumaHazuki** [lxqt/lxqt#2513]
**Is your feature request related to a problem? Please describe.**

While not explicitly a problem I'm having, I think this would help increase LXQt's appeal to a wider base :) An icons-only task manager might even be able to be partly ported from the KDE plasmoid of the same name; it's the combination launcher/taskbar widget common to Windows and Plasma. The Global Menu also has a Plasma plasmoid and uses dbusmenu-qt, if I remember right.

**Describe the solution you'd like**

If possible, please implement the above two widgets. I imagine the taskbar would be harder than the global menu plugin, but am unfortunately not a programmer (or I'd do this myself!)

**Describe eventual alternatives you've considered**

There aren't really alternatives. Launcher + Taskbar in Icons-only mode doesn't have the combined functionality (i.e., launchers are always there and are separate from the taskbar proper) and there is no replacing a global menu.

##### Context

I like the old-school approach (my LXQt looks a lot like the GTK2 builds of Xfce, with 2 panels and icon+text taskbar), but most DEs by now have the above two features implemented. It would be a nice addition to LXQt. 

As far at theming these widgets in lxqt-panel.qss goes, the global menu shouldn't need anything much and can just inherit the text color from the user's palette automatically. The icons-only task manager could inherit #TaskBar QToolButton theme settings, including their pseudostates such as hovered, urgency, etc.

**Comment by tsujan** [comment]
Duplicate of https://github.com/lxqt/lxqt/issues/131 and https://github.com/lxqt/lxqt/issues/133

**Comment by stefonarch** [comment]
FYI: There is now a plugin for the taskbar:
https://github.com/xuzhen/dockbarx-lxqt-plugin
only theming has to be done fiddling as it doesn't follow qt stylesheets.

**Comment by stefonarch** [comment]
> It may be worth rewriting it in C++ Qt :)

It may be worth a real lot to many users ;)

**Comment by lq259** [comment]
This needs more attention.
