### ISSUE TITLE
[Feature Request] Provide a Hotspot Feature to Share Internet When Connected on Ethernet

### ISSUE THREAD

**Issue by Itsamanjain** [lxqt/lxqt#2518]
**Is your feature request related to a problem? Please describe.**
I want to share my internet connection with others when I'm connected through an Ethernet cable. Currently, this feature is not available.

**Describe the solution you'd like**
I would like a Hotspot feature that allows me to share my internet connection when connected via Ethernet. It should be easy to set up and use. For example, I could turn on the Hotspot feature in the settings and share my internet with others nearby.

**Describe eventual alternatives you've considered**
I haven't found any built-in alternatives on the system for sharing my Ethernet connection as a hotspot. Using third-party software might be an option, but having a native Hotspot feature would be more convenient.
Context

##context
This is important to me because there are times when others need internet access, and I want to provide a simple way to share my connection, especially when I'm using Ethernet. It would be useful in situations where Wi-Fi is not available or is unreliable.

**Comment by tsujan** [comment]
LXQt doesn't provide a app for Internet connection (as it its doesn't for web browsing, video playing,...). Use any app which does what you need.
