### ISSUE TITLE
lxqt-powermanagement cannot connect to X11 server

### ISSUE THREAD

**Issue by voiduser123321** [lxqt/lxqt#2519]
##### Expected Behavior

lxqt-powermanagement should connect to X11 server and, well, manage power events appropriately to it's settings.

##### Current Behavior

lxqt-powermanagement connection breaks shortly after it starts and thus it cannot turn off screen, dim the backlight and so on.

##### Steps to Reproduce (for bugs)

1.  Go to "LXQt Settings" -> "Session Settings" -> "Basic Settings"
2.  In "LXQt modules" turn off "Power Management"
3.  Restart LXQt session
4.  Open terminal, run lxqt-powermanagement and see the output

##### Context

I should probably note that I'm running Xorg as a regular user, via startx, without display manager. 

##### System Information

* Distribution & Version: Void Linux x86_64
* Kernel: 6.6.11
* Qt Version: 5.15.2
* liblxqt Version: 1.4.0
* Package version: 1.4.0

**Comment by voiduser123321** [comment]
Almost forgot to attach lxqt-powermanagement's output. Here goes:

>[user@void ~]$  lxqt-powermanagement 
>BatteryChanged discharging: false chargeLevel: 100 actionTime: QTime(Invalid)
>Inhibit got: 32
>Starting idlenesswatcher
>"PowerButton" "" ""
>"SuspendButton" "" ""
>"HibernateButton" "" ""
>The X11 connection broke (error 2). Did the X11 server die?

**Comment by stefonarch** [comment]
> via startx, without display manager

How do you start LXQt?

**Comment by voiduser123321** [comment]
@stefonarch, I've added this command to my .xinitrc:

> exec startlxqt

**Comment by voiduser123321** [comment]
I will test with lxdm tomorrow, though I'm running this setup for roughly a year and there was no such problem until September/October 2023, when there was an update for LXQt.

**Comment by voiduser123321** [comment]
Maybe it has something to do with the way Void maintainers built the package. Regardless, the test will hopefully shed some light on the issue.

**Comment by voiduser123321** [comment]
Well, I tested it with lxdm, and the results are exactly the same - same output and screen never dims, even though it should after 2 minutes, according to "Power Management" settings.

I did note, however, that Xorg command lines differ. Don't see how this can be related, but will post it here, just in case.
>lxdm:   /usr/libexec/Xorg -background none :0 vt07 -nolisten tcp -novtswitch -auth /var/run/lxdm/lxdm-:0.auth

>startx: /usr/libexec/Xorg -nolisten tcp :0 vt1 -keeptty -auth /tmp/serverauth.kCe4GfdoZU vt1

**Comment by voiduser123321** [comment]
It's been a while and the issue didn't get much traction since then. After that it dawned on me - there is an actual [separate entry](https://github.com/lxqt/lxqt-powermanagement/issues) for lxqt-powermanagement here on github, which I didn't notice at the time of posting. Should I move the issue there, maybe?

**Comment by tsujan** [comment]
> Should I move the issue there, maybe?

There's no need to that.

The issue you've encountered hasn't been reproducible. So, there isn't much to say, unless a new piece of info is found.

**Comment by voiduser123321** [comment]
Did a bit of digging around, and decided to actually check what "error 2" in that message actually means. Turns out, it's equiavalent to this error: 

> XCB_CONN_CLOSED_EXT_NOTSUPPORTED, when extension not supported.

, per this [link](https://xcb.freedesktop.org/manual/group__XCB__Core__API.html#ga70a6bade94bd2824db552abcf5fbdbe3). This info led me to investigate whether some of the xorg extensions are disabled on my laptop - and there are! - it's MIT-SCREEN-SAVER. Incidentally, this extension in enabled on another machine, my desktop PC - and lxqt-powermanagement works pretty much fine there. Makes me wonder...

**Comment by voiduser123321** [comment]
My guess was correct, enabling MIT-SCREEN-SAVER resolved the bug, X11 connection works as intended. Didn't mean to waste your time. Closing the issues.
