### ISSUE TITLE
Alt+F4 disables keyboard

### ISSUE THREAD

**Issue by sumdudinhell** [lxqt/lxqt#2520]
##### Expected Behavior

Alt+F4 should only close the active application

##### Current Behavior

Alt+F4 closes active application but also disables my keyboard

##### Possible Solution

Maybe check shortcuts?

##### Steps to Reproduce (for bugs)

1. Press Alt+F4
2. Active window closed
3. Keyboard disabled

##### Context

Well, sometimes I close applications with Alt+F4 because of windows muscle memory, but since the keyboard is disabled I can't resume my normal work. Alt+F4 is also useful for me to close unresponsive programs in case my cursor is trapped inside. I've also noticed that if I Fn lock (because I use a laptop) and then Alt+F4, it behaves as expected, without disabling my keyboard. The symbol under my laptop's F4 key looks like a rewind symbol, if that's any help.

##### System Information

* Distribution & Version: Lubuntu 22.04/EndeavourOS Galileo
* Kernel: 6.6.14-1-lts (EndeavourOS) 6.2 (Lubuntu 22.04)
* Qt Version: 6.5
* liblxqt Version: 1.4.0-1
* Package version: 1.4.0

**Comment by tsujan** [comment]
Report it to Lubuntu.

**Comment by stefonarch** [comment]
Maybe also a hardware issue, could not reproduce in Lubuntu Vbox. You can disable alt+f4 in openbox config file.

**Comment by sumdudinhell** [comment]
Okay, i'll disable Alt+F4. But I think it's still a lxqt issue since it happens in arch linux too, not just in Lubuntu

**Comment by stefonarch** [comment]
Logged into my LXQt openbox session, all fine. I think it's your keyboard, what if you press only F4?

**Comment by sumdudinhell** [comment]
If I Fn lock (the top F keys have other functions) and then Alt+F4, it doesn't disable my keyboard and it works as expected. If i don't Fn lock though, my keyboard is disabled unless i keep pressing Alt+F4, then it randomly comes back. I also noticed that it happens if I minimize the active window and press Alt+F4, it always happens. My keyboard is Spanish-Latin american, my laptop model being a Dell Inspiron 14-3467. And if I only press F4, nothing happens.

**Comment by stefonarch** [comment]
> If I Fn lock (the top F keys have other functions) and then Alt+F4, it doesn't disable my keyboard and it works as expected.

That's what I found here too: https://superuser.com/questions/22480/function-keys-on-dell-laptop-requires-fnf1-f12-default-is-multimedia-oem-key

You can change the default behavior for function keys in the BIOS.

**Comment by sumdudinhell** [comment]
I'll check if my BIOS has this function. Be right back.

**Comment by sumdudinhell** [comment]
It has something about Fn lock: Normal (functions are executed first) and inversed (F keys are executed first)
