### ISSUE TITLE
[Feature request]Network management GUI: Create TUN/TAP, Proxy all traffic

### ISSUE THREAD

**Issue by Pantyhose-X** [lxqt/lxqt#2527]
**Is your feature request related to a problem? Please describe.**
I’m in a country where the internet is very blocked, and upgrading OS or downloading software is a hassle, github gitlab Ping over time 300ms.

In thousands of Linux and BSD distributions, there is no single system desktop environment that proxies all traffic,
I use a proxychains and it’s a terrible proxy for the terminal, very slow.

**Describe the solution you'd like**

* System proxy: [Wintun](https://github.com/nulldotblack/wintun)
[ligolo-ng](https://github.com/nicocha30/ligolo-ng)
[wireguard TUN](https://github.com/WireGuard/wireguard-go/tree/master/tun)
[Universal TUN/TAP driver](https://vtun.info/)
[tun2socks](https://github.com/xjasonlyu/tun2socks)
[tun2proxy](https://github.com/blechschmidt/tun2proxy)
https://www.kernel.org/doc/html/v6.1/networking/tuntap.html
https://man.freebsd.org/cgi/man.cgi?query=tun
Network management GUI added option TUN 
TUN acts as an agent for existing agreements, HTTP proxy HTTPS proxy SOCKS proxy
Use TUN mode to proxy all traffic throughout the system, including terminals

**Comment by tsujan** [comment]
Not related to LXQt.
