### ISSUE TITLE
Redraw issues with fractional scaling

### ISSUE THREAD

**Issue by postmaker01** [lxqt/lxqt#2558]
Tested on Lubuntu 24.04 (LXQt 1.4.x), Debian with LXQt 1.3.x, and KDE Plasma with Openbox without Picom, XFWM4, and KWin. Artifacts appear on the desktop area and inside PCManFM-Qt.

Steps to reproduce:
Enable fractional scaling.
Preferences -> LXQt Settings -> Session Settings
   (Basic Settings tab) Global Screen Scaling: Scale factor: 1.50

or by using: QT_SCALE_FACTOR = 1.5
or by using: QT_SCREEN_SCALE_FACTORS = 1.5

A video is included.

https://github.com/lxqt/lxqt/assets/144814115/70ac7351-11bb-4af3-9cdf-01262157d5c6

**Comment by tsujan** [comment]
It's not LXQt issue but a known Qt problem.

**Comment by tsujan** [comment]
And its severity may depend on the Qt version: some bugs in fractional scaling were fixed in recent versions of Qt.

**Comment by stefonarch** [comment]
I can reproduce it under kwin_x11 and labwc, less severe (less ghost lines).

**Comment by postmaker01** [comment]
The KDE Plasma desktop area and Dolphin, compiled with the exact same Qt version, don't have this problem.

I didn't expect that the upcoming Lubuntu 24.04 LTS would already be outdated.

**Comment by tsujan** [comment]
> The KDE Plasma desktop area and Dolphin, compiled with the exact same Qt version, don't have this problem.

As far as I remember, fractional scale factors had this kind of issue where some kind of transparency was enabled. The desktop viewport is transparent.

**Comment by tsujan** [comment]
Interestingly enough, I can't reproduce it with the Kvantum widget style, even when I enable translucency in Kvantum Manager, but it happens with Fusion and Breeze. So, it may be related to how the widget style draws widgets (and that rubber-band rectangle).

Anyway, LXQt doesn't have anything to do with it.

**Comment by tsujan** [comment]
This video is made with a scale factor of 1.5, but it makes no difference which fractional scale factor I use with Kvantum:

[scale_factor.webm](https://github.com/lxqt/lxqt/assets/981076/7f25f0ed-2f76-42f0-8374-40df281a574a)

**Comment by stefonarch** [comment]
> I didn't expect that the upcoming Lubuntu 24.04 LTS would already be outdated.

Debian testing has only Qt6.4 atm while qt6.6 is the minimum so they need time to catch up.

**Comment by postmaker01** [comment]
I've installed the Kvantum widget style. It behaves similarly to the 'Windows' widget style. Redraw artifacts disappear, but the selection rectangle now has inconsistent, jumpy edges as seen in your video.

The Fusion and Breeze widget styles don't have this problem, but they suffer from redraw issues.

![selection_rectangle](https://github.com/lxqt/lxqt/assets/144814115/a2a3af3c-b615-4c9e-90b4-e5be796dc86a)

**Comment by tsujan** [comment]
> the selection rectangle now has inconsistent, jumpy edges

That's inevitable with Kvantum's code for `CE_RubberBand` and fractional scale factors (I don't know about Windows widget style) because it's about one pixel, which may be lost in rounding floats to integers — as artifacts are inevitable with Fusion or Breeze because tiny parts of drawing can't be updated by its code, again, due to rounding.

Anyhow, this shows that the widget style has a role, although not the full control.
