### ISSUE TITLE
"Date and time" config window can not be closed with "OK" or "Cancel"

### ISSUE THREAD

**Issue by papoteur-mga** [lxqt/lxqt#2576]
##### Expected Behavior
The window closes

##### Current Behavior
I can only close the window with the X at top right.

##### Steps to Reproduce (for bugs)
Launch config-lxqt, open "Date and time" (Date et heure in French)
Click on "OK button or "Annuler" (Cancel) button., there is no action.

##### System Information

* Distribution & Version: Mageia cauldron
* Kernel: Linux localhost 6.6.28-desktop-1.mga10
* Qt Version: 6.6.2
* liblxqt Version: 2.0.0
* Package version: 1.mga10.x86_64

**Comment by tsujan** [comment]
Not reproducible.
