### ISSUE TITLE
For those of us on X11 only[Feature request]

### ISSUE THREAD

**Issue by 0323pin** [lxqt/lxqt#2579]
**Is your feature request related to a problem? Please describe.**
For those of us on X11 only, can the dependency on `layer-shell-qt` be made optional?
We (NetBSD) got kf6 this week, so I've jumped into getting LXQt updated to 2.0.0

The first miss was `pcmanfm-qt` because, it needs `layer-shell-qt` to build. I've patched this out and the application builds and works just fine.

![2024-05-29-105843_1366x768_scrot](https://github.com/lxqt/lxqt/assets/90570748/43c10ea8-2ed0-4781-85f5-52813085d331)

I've later found the same on `lxqt-notificationd` and `lxqt-runner`, I'm not done, yet, so there could be more.
This got me thinking, why is this not optional? It would make life easier for those not willing or, unable to migrate to Wayland. 

**Describe the solution you'd like**
Dependency on `layer-shell-qt` optional for Wayland only. Allowing LXQt-2.0.0 and future versions to run on X11.

Thanks!

**Comment by marcusbritanicus** [comment]
@0323pin Compiling with layer-shell-qt support does not mean you have to use wayland. Other libs that LXQt uses will have some form of wayland dependency. So, you'll not gain anything from making layer-shell-qt optional. On contrary, the amount of code that will need to be added across the project will not be trivial, and can introduce new bugs.

Why not install layer-shell-qt? If it's not available in your package manager, you can compile and install it from sources.

**Comment by 0323pin** [comment]
> Why not install layer-shell-qt? If it's not available in your package manager, you can compile and install it from sources.

Correct, Plasma 6 hasn't been ported. We do have a `layer-shell-qt` package for Plasma 5, which btw hasn't been merged either.

I understand your position regarding added code complexity, as well as I understand our limitations but, thought I'd ask.

**Comment by tsujan** [comment]
> It would make life easier for those not willing or, unable to migrate to Wayland.

`layer-shell-qt` isn't about migrating to Wayland but supporting it, and making it optional, doesn't make life easier for anyone

**Comment by 0323pin** [comment]
> > It would make life easier for those not willing or, unable to migrate to Wayland.
> 
> `layer-shell-qt` isn't about migrating to Wayland but supporting it, and making it optional, doesn't make life easier for anyone

I guess we were writing at the same time. I did say I acknowledge your position.

**Comment by tsujan** [comment]
> I guess we were writing at the same time.

Yes, but I also wanted to emphasize that LXQt won't abandon X11. Those who  can't use Wayland or don't like it for any reason won't have problem with LXQt.

**Comment by 0323pin** [comment]
> Yes, but I also wanted to emphasize that LXQt won't abandon X11. Those who can't use Wayland or don't like it for any reason won't have problem with LXQt.

I got that, we need to package `layer-shell-qt` from Plasma 6.

**Comment by abatyiev** [comment]
I'm using Gentoo and the problem for me is that I have to build all Qt and other stuff with wayland enabled, pulling much more useless dependencies. So, it would be nice, if there would be a CMake option to disable that.

**Comment by Chiitoo** [comment]
> I'm using Gentoo and the problem for me is that I have to build all Qt and other stuff with wayland enabled, pulling much more useless dependencies. So, it would be nice, if there would be a CMake option to disable that.

I'm not sure that there are that many things, aside from the direct wayland dependencies for 'layer-shell-qt' which are 'wayland', 'qtwayland', 'wayland-protocols', and 'wayland-scanner'... but yeah, I am not a fan of the fact either when not using wayland at all, though if I remember right, these are pretty small packages (the wayland ones).

**Comment by abatyiev** [comment]
> > I'm using Gentoo and the problem for me is that I have to build all Qt and other stuff with wayland enabled, pulling much more useless dependencies. So, it would be nice, if there would be a CMake option to disable that.
> 
> I'm not sure that there are that many things, aside from the direct wayland dependencies for 'layer-shell-qt' which are 'wayland', 'qtwayland', 'wayland-protocols', and 'wayland-scanner'... but yeah, I am not a fan of the fact either when not using wayland at all, though if I remember right, these are pretty small packages (the wayland ones).
I thought that lxqt stands for "The Lightweight Qt Desktop Environment". Pulling useless stuff in is not "lightweight".

**Comment by 0323pin** [comment]
> and wayland-scanner

😞 another piece missing for us on NetBSD.

**Comment by Chiitoo** [comment]
> > and wayland-scanner
> 
> 😞 another piece missing for us on NetBSD.
> 
> **EDIT:** Could you point me to the correct source of `wayland-scanner? It doesn't look like it's widely adopted, https://repology.org/projects/?search=wayland-scanner&maintainer=&category=&inrepo=&notinrepo=&repos=&families=&repos_newest=&families_newest=
> 
> Also, I had a quick look at the Void and Arch packages and **none** of them mention `wayland-scanner`

It seems to have been split off of the main wayland package to help with issues regarding cross-compiling (in other words, same as building wayland with everything else 'false' except for '-Dscanner=true').

Apologies for the confusion caused there!

(As a sidey-note, some, or at least me, tend to read github comments via e-mail, and edits do not send a new e-mail.  :])

**Comment by stefonarch** [comment]
In fact it's part of the "wayland" package on arch:

```
$yay -Qi wayland
Name            : wayland
Version         : 1.22.0-1
Description     : A computer display server protocol
Architecture    : x86_64
URL             : https://wayland.freedesktop.org/
Licenses        : MIT
Groups          : None
Provides        : libwayland-client.so=0-64  libwayland-cursor.so=0-64
                  libwayland-egl.so=1-64  libwayland-server.so=0-64
Depends On      : glibc  libffi  expat  libxml2  default-cursors
Optional Deps   : None
Required By     : bemenu-wayland  cage  conky  egl-wayland  gammastep  grim
                  gst-plugins-bad-libs  gst-plugins-base-libs  gtk-layer-shell  gtk3
                  gtk4  hyprland  hyprlock  hyprpicker-git  kanshi  kguiaddons
                  kscreenlocker  kwayland  kwin  kwindowsystem  labwc-git
                  layer-shell-qt  libdecor  libkscreen  libplasma  libva  lswt  mesa
                  mesa-utils  mpv  plasma-desktop  plasma-integration  plasma-workspace
                  qt6-wayland  slurp-git  spectacle  sway  swaybg  swayidle  vlc
                  vulkan-intel  vulkan-radeon  vulkan-tools  waybar  wayfire-git
                  wayland-utils  waylandpp  waylock  webkit2gtk  webkit2gtk-4.1  wev
                  wf-recorder-git  wl-clipboard  wlopm  wlr-randr  wlrctl  wlroots
                  wlroots0.16  wlsunset-git  wofi  wpebackend-fdo  wshowkeys-git  wtype
                  wvkbd  wxwidgets-gtk3  xdg-desktop-portal-kde  xorg-xwayland
```

**Comment by 0323pin** [comment]
@Chiitoo and @stefonarch Thanks for the confirmation. We do build wayland with it enabled.

**Comment by 0323pin** [comment]
Still not available for users but, after some work packaging some missing dependencies, it's working fine.

![2024-06-07-123221_1366x768_scrot](https://github.com/lxqt/lxqt/assets/90570748/40073e97-9ae1-4e8b-ba04-d83fbf94da55)
