### ISSUE TITLE
The software takes too long to launch

### ISSUE THREAD

**Issue by pengxingwei** [lxqt/lxqt#2580]
QTerminal takes more than 3 seconds to start, and so does other software such as lximage, featherpad. Through strace tracking, it is found that they all take about 3 seconds to call futex.
[featherpad-trace.log](https://github.com/user-attachments/files/15510758/featherpad-trace.log)

##### System Information

* Distribution & Version: Lubuntu 24.04

**Comment by stefonarch** [comment]
Not reproducible here: all < 1sec.
Please report Lubuntu issues to the Lubuntu bugtracker.
