### ISSUE TITLE
LXQt crashes PCManFM autoclicks features after changing the color palette

### ISSUE THREAD

**Issue by cenosito** [lxqt/lxqt#2581]
##### Expected Behavior

When changing the color palette in LXQt, the setting to open folders with a single click in pcmanfm-qt should remain active.

##### Current Behavior

Every time the color palette is changed in LXQt, the setting to open folders with a single click in pcmanfm-qt gets deactivated, not working until close and open session.

##### Possible Solution

Ensure that changing the color palette does not affect the setting for opening folders with a single click in pcmanfm-qt.

##### Steps to Reproduce (for bugs)

1. Open LXQt settings.
2. Change the color palette.
3. Crash pcmanfm-qt features

##### Context

This issue affects my workflow as I prefer to open folders with a single click. Each time I change the color palette, I have to restart system.

##### System Information

* Distribution & Version:

Distributor ID: Ubuntu
Description:    Ubuntu 23.04
Release:        23.04
Codename:       lunar

* Kernel: 6.2.0-39-generic

* Qt Version: 
QMake version 3.1
Using Qt version 5.15.8 in /usr/lib/x86_64-linux-gnu

* liblxqt Version: 1.2.0-0ubuntu3

---

**Comment by stefonarch** [comment]
Not reproducible here (never was, as I changed often palette and never had issues with single click).  
 Version 1.2 is also quite outdated.
You may report this to Lubuntu bugtracker.
