### ISSUE TITLE
Bug of Wi-Fi window appearing where it shouldn't when I don't click on its icon

### ISSUE THREAD

**Issue by alvaro500** [lxqt/lxqt#2591]
##### Current Behavior

![Bug1Edited](https://github.com/user-attachments/assets/8dabda0c-98b3-4484-9726-d1672511980e)
![Bug 2Edited](https://github.com/user-attachments/assets/adb10a18-7c24-4d08-b1d6-7efd186a46a8)

##### Steps to Reproduce (for bugs)

1. First image: I click on, for example, the battery and that Wi-Fi window appears.
2. Second image: I left-click on the upper left part of the desktop and the same Wi-Fi window appears, taking into account the distance of the Wi-Fi icon from where its window appears when I don't even click on it
3. 
4. 

##### System Information

* Distribution & Version: LXQT last version
* Kernel: 6.1.0-23-amd64
* Qt Version: 
* liblxqt Version: 
* Package version:

**Comment by stefonarch** [comment]
That is an issue caused not by LXQt but by the window manager and I bet it is openbox. 
https://github.com/lxqt/lxqt/wiki/ConfigWindowManagers

**Comment by tsujan** [comment]
And that's a GTK menu, that doesn't belong to any LXQt app.
