### ISSUE TITLE
Improve visual representation of control element on dark themes

### ISSUE THREAD

**Issue by normal-max** [lxqt/lxqt#2595]
1) In pcmanfm with dark theme arrow buttons “back” “forward” have same color regardless from active or inactive state (possible or not possible go back, for exampe). In contrast arrow “up” looks like only active button.

Arrows are very thin and have very few color to notice difference if it exists.
This is easy to solve. Make arrows thicker, or set different color for active/inactive button background. Remove glossiness, make flat effect for inactive icon.

2) Highlighted window borders allow to separate window content with dark theme. LXQT/DE has no built-in compositor so content of window is not visually separated by color gradient (shades). Without distinct borders text on three overlapping windows mixes up. It is good when active window border is highlighted. With current versions of LXQT this problem is solved. But LXDE seems to have this issue.

3) Screengrab does not offer automatic names for screenshots. But names based on date are standard and rational.
Window of screengrab extends outside of screen borders.
Area selection of screenshot is not visible on dark theme.

Artix linux
Porteus
Screengrab v 2.6.0
LXQT 1.3

It looks like minor issue to report. But it lasts for years, and always pushed me back from installing LXQT/DE variant of distro. I guess other users as well. This can give impression of unfinished job. But project deserves better representation. So regardless of where do theme issues comes from (even if it is bad theme choice from distro creators) I think it is better for lxqt developers to do something. Because existing of such themes can harm project.

LXQT
![screen](https://github.com/user-attachments/assets/555d0432-d409-49b2-8288-42e82032e54b)

![Screenshot from 2024-08-06 11-09-19](https://github.com/user-attachments/assets/bdac6367-68bd-4bed-884d-b3ddfcabf4c4)
LXDE

**Comment by normal-max** [comment]
LXQT
![screen](https://github.com/user-attachments/assets/bcf6174e-c9ec-4486-ab7a-e47b6356aac2)

LXDE
![Screenshot from 2024-08-06 11-09-19](https://github.com/user-attachments/assets/2e55096b-2275-4921-9ee6-a7791ced4851)

**Comment by tsujan** [comment]
Arrows are icons and taken from the icon theme. How a disabled widget (button) looks is determined by the active widget style, not by the app.

Window borders are set by the WM.

LXDE isn't related to LXQt.

As for screengrab, please use https://github.com/lxqt/screengrab/issues

**Comment by normal-max** [comment]
I understand this may not be the fault of lxqt team. This is why I said regardless of where do theme issues comes from, result hurts project perception. If people from lxqt team know where better to address the issue they may do so.

**Comment by tsujan** [comment]
> This is why I said regardless of where do theme issues comes from

I'm afraid it's like saying "... regardless of where the WM comes from...."  LXQt doesn't (and won't) come with a widget style, WM or compositor of its own, and that's intentional. (We've continued that tradition to keep LXQt independent of Wayland compositors too). A problematic WM, theme or compositor has problems everywhere.

**Comment by normal-max** [comment]
I see my broad language led to misunderstanding.
I don’t suggest technical solution, like adding WM, icons or widget style. I don’t know who develops those parts and how lxqt team relates to those people. I can only point the problem and partly satisfy my curiosity. Solution could be social not technical. For example to contact people who create package, distro, theme and just give advice on theme selection or WM so lxqt has better representation.
At the end of the day user doesn’t know who is responsible for every element of his desktop. He just decides if he wants to use it.
