### ISSUE TITLE
Leech LXQt theme: World Clock widget is unreadable with light Qt Palette

### ISSUE THREAD

**Issue by Gnomasz** [lxqt/lxqt#2597]
The World Clock widget uses the "Window Text" color from the Qt Palette (set in the Widget Style settings page) for the panel text. This leads to the clock being unreadable if the Window Text is set to a dark color, which is common for light color palettes.

##### Expected Behavior
The World Clock widget is readable on the Leech theme regardless of the selected Qt Palette.

##### Current Behavior
The World Clock widget is unreadable on the Leech theme when Window Text in the Qt Palette is set to a dark color.

##### Possible Solution
The World Clock panel text color is hard-coded to be the same as the task-manager and/or application menu text color.

I think I can do this myself, but I'd rather check if this is indeed regarded as a bug, and not a feature.

##### Steps to Reproduce (for bugs)

1. Launch an LXQt session
2. Make sure the "World Clock" Widget appears on the panel
3. Open "Configure Panel"
4. Go to "Styling"
5. Make sure that Custom Styling is _not_ set
6. Open LXQt's "Appearance" settings
7. In the "Widget Style" pane, select a Qt palette with a dark "Window Text" color, for example the default palette.
8. In the "LXQt theme" pane, select the "Leech" theme.
9. Observe the "World Clock" widget

##### Context
I wanted to set a light widget theme with a dark panel and this issue appeared.

##### System Information

* Distribution & Version: OpenSUSE Tumbleweed
* Kernel: 6.9.7-1
* Qt Version: 6.7.2

* liblxqt Version: 2.0.0
* Package version: lxqt-panel 2.0.1

Screenshot with dark text:
![Leech theme dark text](https://github.com/user-attachments/assets/4f8e6a40-a746-4638-a10a-0bd6f096c0c1)

Screenshot with red text:
![Leech theme red text](https://github.com/user-attachments/assets/9ebf5cb9-c2f7-45e9-b81c-5e9680fe4df1)

**Comment by Bluey26** [comment]
Hi, i cannot reproduce it in here.

I usually change the Qt color palette from "default" to "dark" and i have never seen that issue. (OS: Archlinux)

Changing the current palette ("default") to Leech makes my panel dark, but all the text in it becomes white). Going back to the default theme makes text black again.

What happens if you log-out with the Leech theme activated? does the issue persist or the text is fixed=

For me, this sound as a not "refreshing of the text" as i was experiencing with https://github.com/lxqt/libfm-qt/issues/979

Does this also happens with other color palettes?

It may be important/useful to mention the libfm-qt version you have installed.

**Comment by tsujan** [comment]
> It may be important/useful to mention the libfm-qt version you have installed.

Panel doesn't depend or use libfm-qt.

> What happens if you log-out with the Leech theme activated?

The user can stop and start lxqt-panel from LXQt Session Settings instead of logging out and in.

**Comment by tsujan** [comment]
Anyway, @Bluey26 made a good point. Qt's on-the-fly palette change can't be complete in all cases. To make sure that there's really a problem in an LXQt theme, please restart the panel from LXQt Session Settings after changing the palette.

**Comment by stefonarch** [comment]
Here it was a comma which shouldn't have been there. You could test the fixes copying the theme folders  in `~/.local/share/lxqt/themes/`.

**Comment by Bluey26** [comment]
> You could test the fixes

Working in here, both themes now show the clock time in dark mode :smile:
