### ISSUE TITLE
KDE-Plasma theme: World Clock widget is unreadable with a dark Qt Palette

### ISSUE THREAD

**Issue by Gnomasz** [lxqt/lxqt#2598]
The World Clock widget on the "KDE-Plasma" LXQt theme uses the "Window Text" color from the Qt Palette (set in the Widget Style settings page) for the panel text. This leads to the clock being unreadable if the Window Text is set to a light color.

##### Expected Behavior
The World Clock widget is readable on the KDE-Plasma theme regardless of the selected Qt Palette.

##### Current Behavior
The World Clock widget is unreadable on the Leech theme when Window Text in the Qt Palette is set to a light color.

##### Possible Solution
The World Clock panel text color is set to be the same as the task-manager and/or application menu text color.

I think I can do this myself, but I'd rather check if this is indeed regarded as a bug, and not a feature.

##### Steps to Reproduce (for bugs)

1. Launch an LXQt session
2. Make sure the "World Clock" Widget appears on the panel
3. Open "Configure Panel"
4. Go to "Styling"
5. Make sure that Custom Styling is _not_ set
6. Open LXQt's "Appearance" settings
7. In the "Widget Style" pane, select a Qt palette with a light "Window Text" color, for example "Dark".
8. In the "LXQt theme" pane, select the "KDE-Plasma" theme.
9. Observe the "World Clock" widget

##### Context
I was just cross-checking [the similar issue with Leech theme](https://github.com/lxqt/lxqt/issues/2597). This is less likely to come up, as dark themes with light panels are not very popular [citation needed], but as I said, I can try and fix it myself.

##### System Information

* Distribution & Version: OpenSUSE Tumbleweed
* Kernel: 6.9.7-1
* Qt Version: 6.7.2
* liblxqt Version: 2.0.0
* Package version: lxqt-panel 2.0.1

Screenshot with light text:
![KDE-Plasma  theme, dark widget style](https://github.com/user-attachments/assets/65ae19d1-2d0a-4fca-a4ab-2d142f6d3e16)

Screenshot with red text:
![KDE-Plasma theme - red window text](https://github.com/user-attachments/assets/7f9f95b1-c15c-4790-a38a-ad8186c02f92)

**Comment by stefonarch** [comment]
Some themes can be used only with light themes, as of KDE-Plasma, Clearlooks and Light if I remember well. There are way more issues in them with a dark palette, still if I remember well, not only the clock but also other plugins.

This doesn't mean it can't be fixed though. But the easiest is using fusion+system theme for theming using palette.

**Comment by Bluey26** [comment]
I can verify this one, seems to be related to the LXQt theme called KDE-Plasma. After changing the theme and the color palette, the clock is not visible, as the first picture.

Regarding restarting the Panel module (as mentioned in https://github.com/lxqt/lxqt/issues/2597 ) this does not affect it, which may be indicating that the issue is something in the CSS.

**Comment by Gnomasz** [comment]
> Some themes can be used only with light themes, as of KDE-Plasma, Clearlooks and Light if I remember well. There are way more issues in them with a dark palette, still if I remember well, not only the clock but also other plugins.

Yeah, I was really looking for issues with dark panels and light themes. Given that Windows looks like that, I'd say that's a popular design. But checking the reverse combinations was just so quick that I didn't want to miss it. I might check other widgets some other day.

**Comment by stefonarch** [comment]
I meant mostly  that they look strange with a dark palette. Anyway, thanks for making us notice those issues :)
