### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by hugok79** [lxqt/lxqt#2608]
In almost all windows, the word in the button `Close` is not translated into Portuguese (Portugal).

![screen](https://github.com/user-attachments/assets/9906ad87-cf31-44eb-91f8-4e716c29b1fb)

**Comment by tsujan** [comment]
You need `qt6-translations` (or whatever its name is in your distro).

But, if I remember correctly, Qt had a problem with Portuguese, or perhaps another language. I'm sure we had a report about that.

Anyway, it's about Qt, not LXQt. Hence closing...

**Comment by stefonarch** [comment]
It  translated in italian or german, but not in Portuguese, in fact. But it `is` translated in ```
```
LANG=pt_BR.UTF-8
 lxqt-about
```
![immagine](https://github.com/user-attachments/assets/1f6eed7a-5670-4323-91b1-1ee91bfe6d01)

**Comment by hugok79** [comment]
> It translated in italian or german, but not in Portuguese, in fact. But it `is` translated in ```
> 
> ```
> LANG=pt_BR.UTF-8
>  lxqt-about
> ```
> 
> ![immagine](https://private-user-images.githubusercontent.com/10681413/365417564-1f6eed7a-5670-4323-91b1-1ee91bfe6d01.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU3ODUxMTUsIm5iZiI6MTcyNTc4NDgxNSwicGF0aCI6Ii8xMDY4MTQxMy8zNjU0MTc1NjQtMWY2ZWVkN2EtNTY3MC00MzIzLTkxYjEtMWVlOTFiZmU2ZDAxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA4VDA4NDAxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIzNDJkOTE5MzgwN2E2ZTUyOTAxMmIyMjg0MjE0NDVkOWVjNTdhM2IzYzliYTdhZGY0YzJjNDQ1NzY1OGI0NmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Afphy8uHvvW_xg0txhCbq6oLYuyDSXJqvkjdCLe-Stk)

* Perhaps it has something to do with the fact that Portugal has two language codes `pt`and `pt_PT` due to the variants of Portuguese that exist, such as Brazilian Portuguese...
* What if we tried using the `pt_PT`lang code instead of `pt`?

**Comment by hugok79** [comment]
Old Problem perhaps... https://wiki.qt.io/Talk:Wiki_Editing_Hints/pt

**Comment by hugok79** [comment]
In https://translate.lxqt-project.org/projects/lxqt-desktop/lxqt-about-menu-entry/ there is only `pt`, even Brazilian Portuguese`pt_BR` doesn't exist!

**Comment by hugok79** [comment]
Maybe if the `pt` is migrated to `pt_PT` it will solve the problem

**Comment by stefonarch** [comment]
It's strange, like here we have both pt_PT and pt_BR here: https://translate.lxqt-project.org/projects/lxqt-configuration/lxqt-config-session/ and it doesnt' work too. It does for es_Es.UTF.8 though.

I tried renaming it:

```
....
-- Installing: /usr/share/lxqt/translations/lxqt-about/lxqt-about_pt_BR.qm
-- Installing: /usr/share/lxqt/translations/lxqt-about/lxqt-about_pt_PT.qm
...

stef@archlinux:lxqt-about$ LANG=pt_PT.UTF-8
stef@archlinux:lxqt-about$ lxqt-about
stef@archlinux:lxqt-about$ LANG=pt.UTF-8
stef@archlinux:lxqt-about$ lxqt-about

```
Only `pt.UTF-8` works (and Brazil)...

**Comment by tsujan** [comment]
@stefonarch 
That Close button is translated by Qt, not by LXQt. As @hugok79's screenshot shows, there's no problem in LXQt's translation.

**Comment by stefonarch** [comment]
I know. But I noticed inconsistencies between our `*.ts` files: some are `*_pt.ts` some are `*_pt_PT.ts`.  We may have that elsewhere too, but it doesn't make a difference here.

**Comment by hugok79** [comment]
I know for sure that if it weren't for the Brazilian variant of Portuguese(`pt_BR`), the Portuguese (`pt`)language(which is the original language and the one spoken in Portugal) wouldn't have any problems at all.

**Comment by hugok79** [comment]
https://wiki.qt.io/Talk:Main/pt
