### ISSUE TITLE
In Appearance in Widget Style the Qt Style "Cleanlooks" does not exist any more after a system upgrade

### ISSUE THREAD

**Issue by ralf3u** [lxqt/lxqt#2628]
After an upgrade from Lubuntu 24.04 to Lubuntu 24.10 in Appearance in Widget Style the Qt Style "Cleanlooks" does not exist any more.

I tried in the terminal:
`sudo apt -y install qt5-style-plugin-cleanlooks`
Then I restarted the computer. 
There is still no entry "Cleanlooks" in Appearance in Widget Style in Qt Style .

**System**
Lubuntu 24.10
LXQt 2.0.0

**Comment by tsujan** [comment]
`lxqt-themes` includes Clearlooks, not Cleanlooks.

`qt5-style-plugin-cleanlooks` has nothing to do with LXQt.

**Comment by ralf3u** [comment]
>lxqt-themes includes Clearlooks, not Cleanlooks.

This I know.

>qt5-style-plugin-cleanlooks has nothing to do with LXQt.

Till Lubuntu 24.04, after having installed cleanlooks, cleanlooks was in the drop-down-list of Appearance in Widget Style the Qt Style. Now it is not there any more.

The qt-style cleanlooks is important for me because on an eink-display in text-mode cleanlooks is the best way to see in the file-manager PCManFM-Qt which tab has focus while I still can read the other tab-titles. Additional to that there is no artifact in the panel on a window that has focus – qt-style Breeze with lxqt-theme clearlooks there is a black beam in the panel on the window that has focus on an eink-display in text-mode.

Other qt-styles in combination with different lxqt-themes unfortunately don't offer this good behavior like cleanlooks.

An other way to solve the problem would be to know how to change the background-color of the tab-titles that are not in focus of PCManFM-Qt. Is there a possibility?

Thank you in advance for an answer.

**Comment by tsujan** [comment]
If you have a Qt6-based LXQt, you won't see Cleanlooks by installing `qt5-style-plugin-cleanlooks`, because it's for Qt5.

You might want to ask Lubuntu if they have a Cleanlooks style for Qt6. Anyway, this isn't related to LXQt.
