### ISSUE TITLE
lxqt-config-monitor crashes on debian 12

### ISSUE THREAD

**Issue by joachimheintz** [lxqt/lxqt#2629]
i cannot launch lxqt-config-monitor.

##### Expected Behavior

lxqt-config-monitor should start and let me configure the displays.

##### Current Behavior

when running in the terminal, this is the error message:
``$ lxqt-config-monitor
org.kde.kscreen: Invalid key in Output map:  "priority"
Connecting to KScreen...
Error: Config is invalid, probably backend couldn't load
```

##### Possible Solution
<!--- Not obligatory, but suggest a fix/reason for the bug.                --->
no idea unfortunately ...

##### Steps to Reproduce (for bugs)
<!--- Provide a link to a live example, or an unambiguous set of steps to  --->
<!--- reproduce this bug. Include code to reproduce, if relevant           --->
1. run `lxqt-config-monitor` in terminal
2. 
3. 
4. 

##### Context
<!--- How has this issue affected you? What are you trying to accomplish?  --->
<!--- Providing context helps us come up with a solution that is most      --->
<!--- useful in the real world                                             --->

##### System Information
<!--- Include as many relevant details about the system you experienced    --->
<!--- the bug in                                                           --->
* Distribution & Version: Debian 12
* Kernel: 6.1.0-26-amd64
* Qt Version: 5.15.8
* liblxqt Version: 0.16.0
* Package version:

**Comment by Chiitoo** [comment]
Version 0.16.0 is from 2020 I believe, and as such, slightly obsolete...

The Qt version seems better, which makes me think that Debian 12 itself is not obsolete, and just the LXQt packages are lagging, in which case this should be reported to Debian itself (could be fixed if they simply packaged a recent version of the LXQt packages).

**Comment by tsujan** [comment]
> ... and as such, slightly obsolete...

Prehistoric ;)

**Comment by stefonarch** [comment]
Check `~/.config/lxqt/lxqt-config-monitor.conf  ` file:  for ` Invalid key in Output map:  "priority"`` or just delete o rename it. Debian 12  has LXQt 1.2, you should do a full upgrade.

**Comment by tsujan** [comment]
> Debian 12 has LXQt 1.2

That's ancient too. We don't support old versions — because we can't.

**Comment by joachimheintz** [comment]
i replied the same evening but pushed the wrong email-send button, so here again.
at first, thanks for the very prompt reactions.
i did a dist-upgrade and at least the monitor settings do not crash any more.
and yes, i am on lxqt 1.2 now --- is it recommended to upgrade this and build lxqt myself?
are there descriptions?

**Comment by tsujan** [comment]
> is it recommended to upgrade this and build lxqt myself?

I'm not familiar with Debian 12 but guess that a later version of LXQt can't be compiled for it. If LXQt 1.2 prevents the crash for you, you could stay with it until a newer version comes to your distro.

However, the latest stable LXQt is 2.0.0 (2.1.0 will be released soon), and of course, the more recent a version is, the more bugfixes it contains.

**Comment by stefonarch** [comment]
It should be possible to build LXQt 1.4 on debian 12, downloading the tarballs from that release and building it in the right order, but I don't think it's worth the hassle of building all those packages.
