### ISSUE TITLE
Bitmap fonts are not displayed and rendered correctly after the recent qt 6.8 update

### ISSUE THREAD

**Issue by glu8716** [lxqt/lxqt#2630]
##### Expected Behavior

Bitmap fonts should display and render correctly.

##### Current Behavior

Bitmap fonts aren't displayed and rendered correctly. This results in random parts of the system having blurry text (for example tabs in PCManFM-Qt or some icons on the desktop) or text completely "invisible" in programs like Featherpad and QTerminal.

##### Steps to Reproduce (for bugs)

1. No particular steps, just set a bitmap font like Terminus and see the results.

##### Context

This started happening after the qt 6.8 update. Downgrading to 6.7.3 is the only workaround I could find.
There seem to be other similar bug reports in the KDE bug tracker like [this one](https://bugs.kde.org/show_bug.cgi?id=493051) and [this one](https://bugs.kde.org/show_bug.cgi?id=494790).

##### System Information

* Distribution & Version: Artix
* Kernel: 6.11.3
* Qt Version: 6.8
* liblxqt Version: 2.0.0
* Package version: everything on the latest available version from the Arch repos.

**Comment by tsujan** [comment]
As you may already know, LXQt doesn't render fonts; Qt does.

You could use [Discussion](https://github.com/lxqt/lxqt/discussions) for topics like this.

> This started happening after the qt 6.8 update.

Sadly, Qt 6.8 has more than one regression.
