### ISSUE TITLE
PCManFM-QT will not display open encryted direction contents.

### ISSUE THREAD

**Issue by jda10-az** [lxqt/lxqt#2633]
##### Expected Behavior

Encrypted a directory with ENCFS.  Opened with ENCFS and was unable to browse with PCManFM-QT.  ENKI and Dolphin could view the files but not PCManFM-QT.  I could not change permissions in PCManFM-QT properties to all access.  
I am running Fedora LXQT 41.

##### Steps to Reproduce (for bugs)

1. 
2. 
3. 
4. 

##### System Information

* Distribution & Version: 
* Kernel: 
* Qt Version: 
* liblxqt Version: 
* Package version:

**Comment by tsujan** [comment]
Not reproducible.

Make sure you've installed GVFS.
