### ISSUE TITLE
Message in file forbids me from disabling annoying sound.

### ISSUE THREAD

**Issue by InnateLotion** [lxqt/lxqt#2637]
Arch Linux
LXQt 2.0.0

When closing a GTK 3 program with an unsaved file, a dialogue appears and there's an annoying noise.

There are two ways to prevent it:

1. Disable all system sounds globally in pavucontrol-qt.
2. Add the string `gtk-enable-event-sounds = 0` to the file `~/.config/gtk-3.0/settings.ini`.

I don't want to disable all system sounds.
But I cannot edit `~/.config/gtk-3.0/settings.ini` because the file forbids me:

> # Created by lxqt-config-appearance (DO NOT EDIT!)

**Comment by tsujan** [comment]
> But I cannot edit....

Back up that file and edit it without changing its other settings. If you don't want your changes to be overwritten, go to `LXQt Appearance Configuration` → `GTK Style` and uncheck "Set GTK themes...

That's a side effect of messing with other toolkits, which I was always against. GTK (now its version 4) has its own tools and LXQt shouldn't touch it.
