### ISSUE TITLE
Icons missing in Configuration Center

### ISSUE THREAD

**Issue by QiangF** [lxqt/lxqt#2640]
![img_2024_11_12__21_46_11](https://github.com/user-attachments/assets/56d5092d-df1a-4a94-a3f9-df52a285829d)

I am using Archlinux. This is my session.conf

    [General]
    __userfile__=true
    power_actions_after_lock_delay=100
    window_manager=herbstluftwm

    [Environment]
    GTK_CSD=0
    GTK_IM_MODULE=fcitx
    GTK_OVERLAY_SCROLLING=0
    INPUT_METHOD=fcitx
    QT_IM_MODULE=fcitx
    QT_QPA_PLATFORMTHEME=lxqt
    SDL_IM_MODULE=fcitx
    XMODIFIERS="@@im=fcitx"

    [Mouse]
    cursor_size=22
    cursor_theme=Qogir-dark

**Comment by tsujan** [comment]
Provided that the packages you've installed are OK, you need to find what's missing from your installation and/or settings.

Also, check if you've chosen a rich enough icon set like breeze, oxygen, ...

**Comment by tsujan** [comment]
That's possible because `libqtxdg` always needs to be (re-)compiled against the current Qt version; otherwise, its package will be broken.
