### ISSUE TITLE
Cannot start YaST and other applications with lxqt-sudo under wayland

### ISSUE THREAD

**Issue by KayJay7** [lxqt/lxqt#2647]
##### Expected Behavior

Running `lxqt-sudo /sbin/yast2' should start the yast gui with elevated privileges, as it is possible with `xdg-su -c yast2'.
Moreover, the application should use the wayland backand ad not the x11 one.

##### Current Behavior

Running `lxqt-sudo /sbin/yast2' fails to start the applications and gives the following error on the console:

```
Authorization required, but no authorization protocol specified
 
Authorization required, but no authorization protocol specified
 
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
 
Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, xcb.
```

Like this application is trying to use the x11 backend, which is not supposed to run with root permissions under wayland, so it fails as expected. However, even setting `QT_QPA_PLATFORM=wayland` the application fails to start with a similar error.

lxqt-sudo clears most environment variabiels, but if I get it to let some through like this:
```
lxqt-sudo bash -c "XDG_SESSION_TYPE=$XDG_SESSION_TYPE XDG_RUNTIME_DIR=$XDG_RUNTIME_DIR /sbin/yast2"
```
the application starts, but even then, it doesn't use the correct theme, while the application run with `xdg-su` does.

##### Possible solutions

One solution is obviously to get packagers to ship a .desktop file that either passes the relevant variables through or uses xdg-su.

A better one would be to avoid clearing some of these `XDG_` variables necessary for the applications to work. 

##### Steps to Reproduce (for bugs)

1. On openSUSE Tumbleweed (with lxqt 2.1)
2. Setup and enter an lxqt+labwc wayland session
3. Running YaST either from the application menu or one of the commands above

##### System Information

* Distribution & Version:  openSUSE tumbleweed
* Kernel:  6.11.8
* Qt Version: 6.8.0
* liblxqt Version: 2.1.0
* Package version: lxqt-sudo 2.1.0

**Comment by tsujan** [comment]
That's because no graphical sudo works on Wayland.

However, you could do something like this cautiously:

```sh
xhost +SI:localuser:root
# Do your graphical sudo work here
xhost -SI:localuser:root
```

**Comment by tsujan** [comment]
If I were you, I'd report YaST's problem with Wayland to OpenSUSE. A GUI app shouldn't need to be launched as root to do root jobs but should get root privileges through `polkit` if needed.
