### ISSUE TITLE
[Feature request] build and run LXQt in a wayland-only environment

### ISSUE THREAD

**Issue by YukariChiba** [lxqt/lxqt#2650]
**Is your feature request related to a problem? Please describe.**

I've recently been packaging the LXQt package for [eweOS](https://os.ewe.moe), and since it's a Wayland-only (no X11-related libraries exist) distro, I'm expecting it to build successfully and run on a compositor like labwc.

However, LXQt does not yet have support for Wayland-only environments, and X11-related code does not have a macro definition that is turned off at compile time.

**Describe the solution you'd like**

I would like the LXQt project to introduce a CMake parameter to disable X11-related code, e.g. `WITHOUT_X11=ON`. This would isolate some of the existing X11-specific code. These codes do not work in the wayland environment and therefore do not affect functionality.

**Describe eventual alternatives you've considered**

I have tested LXQt with the X11-related code removed in the eweOS testing repository and have got a basically usable LXQt environment. However, the changes in our repository are too brute-force (simply remove the code) to be upstreamed. So here it is desired to upstream these modifications by way of compilation parameters.

Below is a rough list of projects that contain X11-specific code and need to be modified:

- lxqt-config (liblxqt-config-cursor needs to be disabled)
- lxqt-globalkeys
- lxqt-notificationd
- lxqt-panel
- lxqt-session
- pcmanfm-qt
- qterminal

![image_2024-11-19_08-28-11](https://github.com/user-attachments/assets/f01aec7a-b686-47ea-832c-9ba3db40ed94)

**Comment by tsujan** [comment]
>  LXQt does not yet have support for Wayland-only environments

And it won't. Period.

**Comment by tsujan** [comment]
BTW, If you change the codes in your distro, please tell your users not to report issues here.
