### ISSUE TITLE
A packaging bug in Gentoo

### ISSUE THREAD

**Issue by regicidalplutophage** [lxqt/lxqt#2651]
Hope you don't mind me filing this bug report here -- LXQt is listed as the package maintainer so I believe this will reach the right people regardless.

The bug concerns `lxqt-panel-2.1.1` and `lxqt-qtplugin-2.1.0` packages. The `DEPEND` variable of these ebuilds contains `dev-libs/libdbusmenu-lxqt` with no version specified. This would present no issue if testing packages are enabled globally, but if they're not, build fails because `libdbusmenu-lxqt-0.1.0` is installed by default, while `libdbusmenu-lxqt-0.2.0` is needed.

This would be solved by specifying the needed version in these ebuilds.

##### Expected Behavior

When installing LXQt 2.1.0 on a stable system portage would complain about packages being keyword-masked, unmasking them would allow testing version of LXQt to be installed.

##### Current Behavior

Builds fail, information on which package should be unmasked is not provided.

##### Possible Solution

Update `DEPEND` variable of `lxqt-panel-2.1.1` and `lxqt-qtplugin-2.1.0` ebuilds to have the correct version of `libdbusmenu-lxqt`

##### Steps to Reproduce (for bugs)

1.  emerge -va --autounmask =lxqt-base/lxqt-meta-2.1.0::gentoo
2.  dispatch-conf
3.  emerge -va  =lxqt-base/lxqt-meta-2.1.0::gentoo

##### Context

Packaging were probably tested on a system that has testing packages enabled globally, while I only enable testing for some select packages that I explicitly want to be as recent as possible.

##### System Information

* Distribution & Version: Gentoo stable
* Kernel: 
* Qt Version: 
* liblxqt Version: 
* Package version:

**Comment by tsujan** [comment]
Please report it to your distro.

> LXQt is listed as the package maintainer

LXQt doesn't maintain any package for any distro.

**Comment by Chiitoo** [comment]
> Hope you don't mind me filing this bug report here -- LXQt is listed as the package maintainer so I believe this will reach the right people regardless.

Where exactly did you see that?

The `LXQt` you see as the maintainer should be referring to the Gentoo Linux project with said name (though the "team" is just me currently), with the e-mail mentioned somewhere there as well.

For future reference, indeed file such issues on our bug tracker instead, where this was also reported already [1].  :]

1. https://bugs.gentoo.org/show_bug.cgi?id=944732

**Comment by regicidalplutophage** [comment]
> Where exactly did you see that?

https://packages.gentoo.org/packages/lxqt-base/lxqt-meta
I realize now that a few extra clicks would've saved me a lot of confusion.
