### ISSUE TITLE
 Fullscreen Application Exits Fullscreen and Switches to Another Desktop on Double-Clicking Title Bar

### ISSUE THREAD

**Issue by cvbuoibcvucvb8** [lxqt/lxqt#2652]
I am experiencing an issue on my LXQt system where fullscreen applications switch to another desktop when I double-click the title bar to restore the window from fullscreen. This unexpected behavior causes inconvenience when managing fullscreen apps.

Steps to Reproduce:

    Open any application in fullscreen mode.
    Double-click the title bar to restore the window from fullscreen.
    Observe that instead of simply restoring the window, the application switches to a different desktop.

Expected Behavior: Double-clicking the title bar of a fullscreen application should simply restore the window to its normal size and not switch to another desktop.

Actual Behavior: The fullscreen application exits fullscreen but instead of remaining on the current desktop, it switches to another desktop.

Additional Information:

    This issue occurs with multiple applications, not just one specific program.
    The issue started happening after a recent update or installation of LXQt/Openbox.
    I have checked window manager settings and desktop configurations, but the problem persists.

**Comment by tsujan** [comment]
The title-bar belongs to the window manager that you use, not to LXQt.

You could check the settings of your WM, report the problem to its developers if it isn't about a setting, or use another WM.
