### ISSUE TITLE
KDE apps not respecting dark theme choice upon opening

### ISSUE THREAD

**Issue by Vandino86** [lxqt/lxqt#2653]
##### Expected Behavior

When opening a KDE app (Kate, Konsole, Dolphin, etc.) in LXQt, the choice made in KDE System Settings --> Colors & Themes --> Global Theme should be respected. For example, if Breeze Dark is selected as the Global Theme, then Kate should open with dark colors (see pic below). If Breeze is selected instead (Breeze Light), then Kate should open up with bright colors.

![image](https://github.com/user-attachments/assets/3d172441-58d0-4f22-8707-84a351864f40)

##### Current Behavior

Despite me setting the Global Theme to Breeze Dark, KDE apps like Kate, Konsole, and Dolphin always have Breeze Light colors upon opening (see below).

![image](https://github.com/user-attachments/assets/14155ae6-6350-446b-8f04-31973627b4c4)

##### Steps to Reproduce (for bugs)

1. Open KDE System Settings.
2. Ensure that Breeze Dark is selected in Colors & Themes --> Global Theme. Apply the changes.
3. (Probably optional) Ensure that Breeze Dark is selected in Colors & Themes --> Colors. Apply the changes.
4. Open a KDE app such as Kate, Konsole, or Dolphin. It will be bright-colored instead of dark.

For Kate and Konsole, choosing Settings --> Window Color Scheme --> Default will make the app dark like it should be after opening. I cannot seem to do this in Dolphin, however.

##### System Information

* Distribution & Version: Void Linux (x86-64 musl)
* Kernel: 6.6.62
* Qt Version: 6.7.2
* liblxqt Version: 2.1.0
* lxqt-qtplugin Version: 2.1.0
* Package version: LXQt 2.1.0
* Window Manager: Openbox 3.6.1
* KDE Plasma Version: 6.2.0
* KDE Frameworks Version: 6.7.0
* KDE System Settings Version: 6.2.0
* Kate Version: 24.08.1
* Konsole Version: 24.08.1
* Dolphin Version: 24.08.1
* LXQt Appearance Settings:
  * Widget Style:
    * QT Style: Fusion
    * QT Palette: Ambiance
  * LXQt Theme: Ambiance

**Comment by stefonarch** [comment]
@tsujan will have more insights, setting breeze dark or light in `systemsettings` works fine here.

**Comment by tsujan** [comment]
> When opening a KDE app ... in LXQt, the choice made in KDE System Settings ... should be respected.

Totally incorrect. The "color scheme" of KDE's System Settings has effect with KDE's platform plugin, i.e., in Plasma. LXQt has and uses its own plugin.

That being said, some KDE apps may take some of their colors directly from KDE's "color scheme". That's a inconsistency in their codes.

**Comment by Vandino86** [comment]
I guess I should've figured that this is a KDE-side issue. I might put in a bug report for this over there, but I found a few that are similar:

https://bugs.kde.org/show_bug.cgi?id=463806
https://bugs.kde.org/show_bug.cgi?id=492593
https://bugs.kde.org/show_bug.cgi?id=493384
https://bugs.kde.org/show_bug.cgi?id=496174

**Comment by tsujan** [comment]
> I guess I should've figured that this is a KDE-side issue.

It isn't a KDE issue. KDE color schemes are for KDE's Qt plugin. If that plugin isn't active (as it can't be under LXQt), color schemes won't have effect — exactly as LXQt's palettes have effect only where LXQt's Qt plugin is active.

If there is a bug, it's in some KDE apps (e.g., QML ones) that use the KDE color scheme *directly* in their codes. However, KDE devs don't consider this as a bug (wrongly).

**Comment by Vandino86** [comment]
Thanks for the info. I decided to make a bug report for this in KDE's bug tracker anyway: https://bugs.kde.org/show_bug.cgi?id=496802

For what it's worth, I initially assumed this was a LXQt-side issue because I did not have this issue until recently, and I recently upgraded LXQt from 2.0.0 to 2.1.0. I suppose that this issue may have been introduced in version 24.08.1 of Kate, Konsole, and Dolphin.

I should also note that the colors in KDE System Settings app are completely FUBAR when running it in LXQt (see the screenshot below). I'm assuming this is a similar issue on KDE System Settings' side? I'll make a separate bug report for this in KDE's bug tracker if that's the case.

![image](https://github.com/user-attachments/assets/4b30de63-c62f-4093-aab2-bf5fc85bd59d)

**Comment by tsujan** [comment]
> because I did not have this issue until recently

You probably didn't have a complete/correct LXQt installation before and so, didn't use LXQt's Qt plugins.

> I should also note that the colors in KDE System Settings app are completely FUBAR when running it in LXQt

Set the environment variable `QT_QUICK_CONTROLS_STYLE` to `org.kde.desktop`. I think we've mentioned it in our Wiki.

**Comment by Vandino86** [comment]
I'll take all further inquiries about this over to the KDE app devs.

> Set the environment variable QT_QUICK_CONTROLS_STYLE to org.kde.desktop. I think we've mentioned it in our Wiki. KDE's systemsettings is one of those KDE apps I was talking about.

That fixed it. Thanks! It's indeed [in the wiki](https://github.com/lxqt/lxqt/wiki/Theming#fix-for-invisible-text-in-kde-plasma-systemsettings-with-dark-themes).

**Comment by Vandino86** [comment]
According to [a commenter on the KDE bug report](https://bugs.kde.org/show_bug.cgi?id=496802#c7):

> The issue here is on LXQt side: xdg-desktop-portal-lxqt doesn't support the XDG dark mode spec KColorSchemeWatcher uses to detect dark mode.
> 
> https://github.com/flatpak/xdg-desktop-portal/blob/main/data/org.freedesktop.portal.Settings.xml#L38

Should this bug report should be moved to [xdg-desktop-portal-lxqt](https://github.com/lxqt/xdg-desktop-portal-lxqt), then?

**Comment by tsujan** [comment]
> Should this bug report should be…

For the third and last time: this isn't a bug. If you want to use KDE's QML styling under LXQt or any other DE, set `QT_QUICK_CONTROLS_STYLE` and choose a proper KDE color scheme in their systemsettings. KDE color schemes belong to KDE, not LXQt.
