### ISSUE TITLE
Change the battery icons for panel plugin

### ISSUE THREAD

**Issue by jleclanche** [lxqt/lxqt#270]
The battery info plugin currently displays icons that look more critical than they really are. (Currently using oxygen icon theme so maybe things don't look the same on other themes)

"Low" should be <25%. "Critical" should be <10%. Anything else should display the approximately relevant number of notches. For example, currently, 99% battery has one missing notch; 25% has zero notches left, and <50% has 1 notch out of 4.

**Comment by tsujan** [comment]
Many things have changed about the battery icon. Closing...
