### ISSUE TITLE
LXQT does not apply GTK+ and GTK3 theme automatically.

### ISSUE THREAD

**Issue by easyaspi314** [lxqt/lxqt#283]
Normally, I set the theme and it works in other environments. However, I always login to the default theme. 

Workaround: 
Install MATE appearance and its settings daemon, (I think that you need to install the whole mate-core package) and set theme from mate-appearance-properties and add "mate-settings-daemon" to startup. 

I also found out that LXAppearance has no effect using this solution, but it never worked anyway. 

LXQT seems to work fine with this solution. The issue seems to come from the lack of a settings daemon.

**Comment by agaida** [comment]
done more or less now in lxqt-config-appearance
