### ISSUE TITLE
Files on the desktop cannot be removed by delete key, only by context menu

### ISSUE THREAD

**Issue by Gyges88** [lxqt/lxqt#289]
Files on the desktop cannot be removed by delete key, only by context menu ("Move to Trash").

Reproducability: always

**Comment by Gyges88** [comment]
Sorry for not coming back to it sooner, I didn't log in for a while...
Seems this one was not quite accurate... I didn't mean the files in the file manager but the icons on the desktop itself (representing the files in the desktop folder).
Anyway, this issue has been fixed in the meantime. Now the files on the desktop itself can be deleted by the delete key as well.
Keep up the good work!
Cheers

Gyges

**Comment by paulolieuthier** [comment]
@Gyges88 thanks!
