### ISSUE TITLE
lxqt-session segmentation fault

### ISSUE THREAD

**Issue by ghost** [lxqt/lxqt#310]
lxqt-session causes segmentation fault and system returns back to login screen. GDB gave what is causing segmentation fault(I don't have full log right now, but there was nothing important other than this):

```
    QScreen::handle() const
        in libQt5Gui.so.5.2.1
```

Playing with lxqt-session in xinit showed very interesting thing. If I run a qt application before lxqt-session, lxqt-session runs without a proplem. Even If I re-run lxqt-session after crash, It works.  So I added this in startlxqt before exec lxqt-session.

```
    (pcmanfm-qt -d) &
    sleep 3
```

This solution seems works.

KDE works without a problem.  I tried every login manager, I tried vanilla install and I tried installing along side with KDE, they changed nothing. I'm using linux mint. I got lxqt from lubuntu-daily ppa. 
Note that LXQT was working on my system, when It first came around.

**Comment by alexzk1** [comment]
To anybody coming from google:
I have rebuilt and reinstalled most of packages using system qt (like lxqt-qtplugin), but fixed by recompiling "libqtxdg" from GIT using system Qt.
So in short, if you had Qt version update, most likely you will have to recompile parts of lxqt.
