### ISSUE TITLE
PCmanFM-QT Feature parity

### ISSUE THREAD

**Issue by theredbaron1834** [lxqt/lxqt#333]
pcmanfm-qt is lacking almost all options, outside of simple clicking, with stuff in the places menu. IE, there is near nothing in the right click menu, as well as no middle click to open in new tab. While I don't often use the context menu there, I do use middle click a lot. This would make things much better, imo.

Also, being able to drag between tabs is quite nice as well. It works fine in -GTK, but not -QT. Granted, not much a problem as you can still copy/pasta, but I really like it in -GTK.

**Comment by PCMan** [comment]
@theredbaron1834 Would you please do me a favor?
List things that are lacking in the Qt version.
Even better, open different issues for them?
This can greatly speed up the development.
Thanks!

**Comment by theredbaron1834** [comment]
I added them.
[Middle click to open tab in places menu](https://github.com/lxde/lxqt/issues/445)
[Drag and drop moving a file in Pcmanfm-qt](https://github.com/lxde/lxqt/issues/446)
[Right click options missing in places menu](https://github.com/lxde/lxqt/issues/447)
and a new one I found
[PCmanFM-QT renaming place bookmarks does nothing](https://github.com/lxde/lxqt/issues/448)

**Comment by pmattern** [comment]
Just wondering whether there's any chance to move the numerous issues regarding PCManFM in this tracker to PCManFM's dedicated one.
This would ease things like following and avoiding duplicates pretty much, imho.

**Comment by tsujan** [comment]
All done a long time ago.
