### ISSUE TITLE
Show menus provided by window managers causes mouse wheel to send double events

### ISSUE THREAD

**Issue by rotech** [lxqt/lxqt#336]
When "Show menus provided by window managers when desktop is clicked" is enabled it causes the mouse wheel scrolling for changing desktops to send double events i.e. one wheel scroll will cause a jump from desktop 1->3.  Disabling this option returns mouse wheel desktop changing to normal behaviour, but then obviously I lose the WM menus.

**Comment by tsujan** [comment]
"Show menus provided by window managers..." is removed.
