### ISSUE TITLE
ShowDesktop widget does not work

### ISSUE THREAD

**Issue by dbluelle** [lxqt/lxqt#338]
Since the switch to KWindowSystem clicking on the "Show Desktop" Icon doesn't do anything.
I'm using ArchLinux with no other KF5 packages (except KWindowSystem) installed, 
so maybe there is some hidden dependency to other KF5 stuff?

**Comment by paulolieuthier** [comment]
Will be fixed in KWindowSystem 5.7.

**Comment by damianatorrpm** [comment]
Tried the KWindowSystem function on Fedora 21. Fixes the showDesktop behaviour with openbox AND mutter/gnome-shell (was affected by same bug)

**Comment by paulolieuthier** [comment]
@damianatorrpm thanks!

**Comment by paulolieuthier** [comment]
After 5 months, back to using KWindowSystem, as it's been fixed.

**Comment by jleclanche** [comment]
Very nice!
