### ISSUE TITLE
Create Link to Desktop

### ISSUE THREAD

**Issue by davls82** [lxqt/lxqt#342]
Is it not possible to create A Link of a Programm to Desktop because of an Error message that i cannot copy to destination Folder / .

**Comment by PCMan** [comment]
I cannot reproduce this with the latest pcmanfm-qt + libfm.
Create symlinks on the desktop with dnd works.
The only thing that does not work is dragging an icon from lxqt-panel menu and drop it on the desktop.
Dnd from the "menu://applications" folder to the desktop works in pcmanfm-qt.
Could you please confirm?

**Comment by agaida** [comment]
@tsujan ?

**Comment by tsujan** [comment]
Not valid now.

**Comment by tsujan** [comment]
And thanks for checking old reports!
