### ISSUE TITLE
pcmanfm-qt use wrong size for icons

### ISSUE THREAD

**Issue by gilir** [lxqt/lxqt#343]
When the theme has different sizes for the same icon, pcmanfm-qt picks the smallest one instead of the correct size.

To reproduce :
- Install the Lubuntu theme
- Set the Lubuntu theme in pcmanfm-qt preferences
- See that the icon use for folder view is grey, using the 16x16 icons. It should use the 48 ones.
- Go to /usr/share/icons/Lubuntu/places
- Remove the 16/ folder
- Set another theme in pcmanfm-qt preferences, and reset Lubuntu theme
- See that the icons are now blue, using the 22x22 ones. It still should use the 48 ones.

**Comment by PCMan** [comment]
Apparently this seems be a bug in QIcon implementation of Qt5.
We only pass the name of icon to Qt and it handles the rest. :(
I'm working on this bug to see if there's a workaround now.

**Comment by jleclanche** [comment]
@PCMan can you file it upstream please?

**Comment by rafaellaguna** [comment]
Sorry, I had to change icon definition to Threshold. But this is not 
definitive. Or can we "survive" this way?


Rafael Laguna
Lubuntu Artwork Team

On vie, 23 ene, 2015 at 6:15 , Jerome Leclanche 
<notifications@github.com> wrote:
> @PCMan can you file it upstream please?
> 
> —
> Reply to this email directly or view it on GitHub.
> 
=

**Comment by PCMan** [comment]
Weird, I can no longer reproduce this with Qt 5.4.
Would you please confirm that wether the bug still exist with pcmanfm-qt +
qt 5.4 or not?

**Comment by YamashitaRen** [comment]
I have this bug with pcmanfm-qt master and qt5.5 : http://pix.toile-libre.org/upload/original/1444322199.png
Configured icon size is 64.
Places indeed use the 64x icons. They use the 22x icons if I scale down the icon size to 24x.
Mimetypes always use the 22x icons.
