### ISSUE TITLE
lxqt-qtplugin not installable

### ISSUE THREAD

**Issue by ghost** [lxqt/lxqt#356]
The following packages have unmet dependencies:  
 lxqt-qtplugin : Depends: qtbase-abi-5-3-0 which is a virtual package.  
The following actions will resolve these dependencies:  
     Keep the following packages at their current version:  
1)     lxqt-qtplugin [Not Installed]  
Accept this solution? [Y/n/q/?] n
**\* No more solutions available ***

**Comment by MttCastelli** [comment]
I still have this problem: cann't install lxqt-qtplugin on vivid (require qtbase-abi-5-4-0 now)

**Comment by MttCastelli** [comment]
you must change lxqt-plugin to require qtbase-abi-5-4-1 virtual package instead, due to the recent qt5 stack update (libqt5core5a is now 5.4.1)

**Comment by pvanek** [comment]
the only proper solution is to modify the platform plugin not to use Qt's private stuff. We just faced this issue in opensuse as well...

**Comment by PCMan** [comment]
Unfortunately, it's hard not to use private stuff.
Without using them, some settings won't apply immediately.
Also Qt platform plugin is not designed to be API/ABI stable.
Too bad. :(

**Comment by pvanek** [comment]
Yes, I know. Luckily we were able to resolve it in suse build service. It is rebuilt automagically with every qt version bump.

**Comment by gilir** [comment]
Yes, "just" a rebuild from the Ubuntu PPA will fix the issue, but every update of Qt will have this effect, quite annoying when you are on a dev serie :-( (and too bad PPA don't have the suse magic :-))

**Comment by MttCastelli** [comment]
lubuntu-dev pakage has been update, so now it's fixed for vivid branch anyway. Thank you
