### ISSUE TITLE
Right click on a lxqt-menu item should open a submenu instead of starting the application

### ISSUE THREAD

**Issue by hterh** [lxqt/lxqt#383]
As in LXDE mouse right clicking should preferably open a submenu with 'add to desktop' and 'properties'.
At present right clicking opens the application thus has the same function as left clicking.

**Comment by pranavg189** [comment]
Any Help on how to process on this...?

**Comment by tsujan** [comment]
This good feature request has been buried under mediocre reports for years — one of the disadvantages of having a cluttered bug tracker (and the reason why I close useless reports in other places as soon as possible).

**Comment by stefonarch** [comment]
I wonder if there would be a way to trust the copied *.desktop file on the desktop automatically, atm it has the usual exclamation mark and needs trusting.
 Not that I'm cluttering my desktop, but many users do.

**Comment by tsujan** [comment]
> I wonder if there would be a way to trust the copied *.desktop file on the desktop automatically

Theoretically, yes; we could add a command-line option to pcmanfm-qt for trusting files and call it by using a detached `QProcess`. BTW, that shows I've thought about it ;)

Practically, it needs more code -- maybe, a lot of code -- and, of course, time. And when I think that the user can right click and trust those items in just a few seconds, a third problem arises: motivation ;)
