### ISSUE TITLE
Dropbox panel widget linked to audacious

### ISSUE THREAD

**Issue by hterh** [lxqt/lxqt#393]
LXQt on Lubuntu 14.10:
After installing dropbox the panel widget showed to be linked with audacious and plays files in dropbox folders.
This only in lxqt, because if switching back to lxde the widget acts in normal way (left clicking opens the dropbox subdirectory with PCManFM and right clicking sub menu for dropbox choices)

**Comment by gripped** [comment]
I had what seems to be a related issue whereby "show in folder" in chrome or "open destination folder" in qbittorrent was opening in k4dirstat. After removing k4dirstat, folders were opening in Firefox.
Before removing k4dirstat I had tried adding  
inode/directory=pcmanfm-qt.desktop 
to ~/.local/share/applications/mimeapps.list
but that did not help. 
I also tried using lxqt-config-file-associations (which did show k4dirstat as the default) to set inode/directory to pcmanfm-qt but the change would not stick. upon exiting and restarting  lxqt-config-file-associations k4dirstat would be the default again.

I fixed it in the end using the command
xdg-mime default  pcmanfm-qt.desktop inode/directory
which has sorted out chrome and qbittorent.

**Comment by Baltasarq** [comment]
Same problem here, with Lubuntu 16.10 after installing lxqt via apt.
I don't think the problem has nothing to with dropbox. For example, choosing "open folder" in the downloads tab of the browser would open audacious. Everything else trying to open a folder would end up opening audacious.

cat ~/.local/share/applications/mimeapps.list | grep directory
was returning nothing.

I tried lxqt-file-associations without any luck. After closing and reopening it, the same file association for inode/directories (audacious) was selected, no matter the number of times I changed it to PCManFM.

Next step was to add the following line to the top of the file ~/.local/share/applications/mimeapps.list:
inode/directory=pcmanfm-qt.desktop

That did not work at all, lxqt-file-associations was behaving the same way, and audacious was being open on every "open folder" action.

Then I noticed the [Default Apps] section in ~/.local/share/applications/mimeapps.list file, and added the line: inode/directory=pcmanfm-qt.desktop just under the header. And that solved it. Completely.

I agree that audacious has an issue here with folders, but lxqt-file-associations should work, or at least give a hint that it won't be able to change that file association.

**Comment by tsujan** [comment]
@Baltasarq 
Have you installed `libfile-mimeinfo-perl`? (see https://github.com/lxde/lxqt/issues/35#issuecomment-238838216)

**Comment by Baltasarq** [comment]
I did not install it manually. But yes, it is installed:

$ apt list libfile-mimeinfo-perl
Listing... Done
libfile-mimeinfo-perl/yakkety,yakkety,now 0.27-1 all [installed,automatic]

**Comment by tsujan** [comment]
@Baltasarq 
OK! I thought it might be related to https://github.com/lxde/lxqt/issues/35.

**Comment by agaida** [comment]
duplicated many times - xdg handling
