### ISSUE TITLE
Typo in the french translation of the menu

### ISSUE THREAD

**Issue by manjaro-lxqt** [lxqt/lxqt#398]
Hi,

I don't search all the typos (i self do a lot), but this really hurts, because it appears at the opening.

"vérouiller l'écran" instead of "Verrouiller l'écran". Is there a way to patch it for the moment ?

**Comment by pmattern** [comment]
Just tried to reproduce by searching the code and running LXQt with locale set to fr_FR.UTF-8. Both to no avail.
So manjaro-lxqt could you try and reproduce this with recent LXQt code and / or tell us where exactly this message can be seen?

Otherwise I'd suggest to close this issue.
