### ISSUE TITLE
Panel Context Menu state fail

### ISSUE THREAD

**Issue by ypnos** [lxqt/lxqt#412]
Closing menus (main menu or context menu) is broken. Let's assume a menu is open:
1. If closed by clicking into another window, the panel still acts as if the menu is open. For example, the hover in Desktop Switcher stays frozen, and the next mouse click on the panel is "ignored" (in reality, it makes the panel realize late that the menu was closed).
2. If closed by clicking onto the panel, the opposite takes place: While the menu closes, the mouse action is also evaluated. For example, when opening the main menu and clicking on the menu button again, the menu re-appears.

Both behaviours result in confusion by the user.

**Comment by agaida** [comment]
@all - is this still valid? If not please close.

**Comment by tsujan** [comment]
Not here.
