### ISSUE TITLE
Write .desktop files localization documentation

### ISSUE THREAD

**Issue by luis-pereira** [lxqt/lxqt#426]
It came from Razor, it works, but it never got documented.

**Comment by jubalh** [comment]
where should one do this?

**Comment by luis-pereira** [comment]
On Thu, Jan 8, 2015 at 12:41 PM, Michael Vetter
<notifications@github.com> wrote:
>
> where should one do this?

In an Contributing-translations wiki. Just like
https://github.com/lxde/lxqt/wiki/Contributing-code


-- 
        Luís Pereira

**Comment by jleclanche** [comment]
This should just be held until we have a working Pootle instance. I expect to get it to work by next month.

**Comment by luis-pereira** [comment]
On Wed, Jan 14, 2015 at 10:56 PM, Jerome Leclanche
<notifications@github.com> wrote:
>
> This should just be held until we have a working Pootle instance. I expect to get it to work by next month.


@jleclanche Sure. This issue is about the project_xx.desktop format
tough. It's not documented AFAIK.

-- 
        Luís Pereira

**Comment by stefonarch** [comment]
Well, only things that matters are:

`Name[xy]=` Name displayed in the menu, runner and pcmanfm-qt/applications
`GenericName[xy=]` Tooltip in menu
`Comment[xy]=` Nowhere seen (correct me if I'm wrong)
