### ISSUE TITLE
Recommended icon theme

### ISSUE THREAD

**Issue by jleclanche** [lxqt/lxqt#43]
I am getting very annoyed at Oxygen. The oxygen-icons developers are impossible to reach.

If we are to keep recommending Oxygen we need a better channel of communication between us. Otherwise we should find a suitable theme whose devs are more accessible imho.

**Comment by intialonso** [comment]
This is very subjective, we have lxqt themes with flat and gradient styles, different palettes, rounded and squared, etc. The icon theme should be in accordance with that.

For example, the Frost theme plays nicely with the Numix icon theme; the Ambiance one work as expected with the Ubuntu Mono Dark icons, and the Light theme been more blue takes a good advantage of the Elementary icons.

Now, none of this themes is really complete, most of them lack some icons; but if I must choose I will go with the Numix or Faenza families, they are the most complete and professional.

Maybe the Breeze theme (when completed) coul be a nice option.

**Comment by jeremywh7** [comment]
Fwiw, I installed breeze-icons 5.4.2-2 (Arch x64), and I like it; using Dark theme w/ Breeze Dark.

**Comment by MttCastelli** [comment]
Hey guys, I was a bit annoyed by Oxygen icon set and, in the other side, none of the 2 Breeze variants fit with LXQt (very clean here: openbox, fusion, Frost) IMHO... So I found this P**aper icon theme**, please have a look, and regards:

https://snwh.org/paper

**Comment by MttCastelli** [comment]
![2017-03-04-153100_1366x768_scrot](https://cloud.githubusercontent.com/assets/11462157/23579524/a8555308-00ef-11e7-8af4-d681e6e43324.png)
LXQt + paper

**Comment by Vladimir-csp** [comment]
I do not know why these are branded as gtk icon themes, since they are just icon themes:
http://www.ravefinity.com/p/vivacious-colors-gtk-icon-theme.html
http://www.ravefinity.com/p/vibrancy-colors-gtk-icon-theme.html
They are rather extensive and have multiple color variants.

**Comment by Esclapion** [comment]
I use antu dark and light. Very complete and light (svg).

![ess](https://cloud.githubusercontent.com/assets/3512979/23579594/e6b1b334-00f0-11e7-9156-dce63c32d1e3.png)

**Comment by agaida** [comment]
There is a new kid in town - papirus icon theme - works fine so far and with the latest changes in the panel i would suggest to switch to as default. Second choice: faenza icon theme. Breeze works now more or less fine too. Both papirus and breeze will introduce problems with symbolic icons. @intialonso  what do you think?

**Comment by stefonarch** [comment]
Maybe just adding a selection of icon themes to https://github.com/lxqt/lxqt/wiki/Themes ?
At the low ens this is done by packagers.
