### ISSUE TITLE
Lxqt-session memory leak (easily triggered by wine and specific games)

### ISSUE THREAD

**Issue by ilag11111** [lxqt/lxqt#442]
I've been having a few full system lockups forcing me to REISUB.   Based on what I see, lxqt-session has a memory leak which is only triggered under very specific circumstances.  In this latest case, I caught lxqt-session approaching 64.2% memory usage of 8GB after a few hours of playing a specific game in Wine.  I imagine a few more minutes of playing would be enough to trigger another system lockup.  Currently, I know of no other way to trigger the memory leak aside from playing a game which I believe is no longer sold.

Also, I'm having difficulties understanding how only a specific game ran in wine could possibly have any effect on the session manager.  I'm hoping lxqt's developers have a better idea of where to look.

Known to trigger the leak:
Deus Ex: Human Revolution (Steam, non Director's Cut)  [I imagine Director's Cut will have the same issue, but cannot confirm]
Wine version: Wine-Staging 1.7.34-1 [Probably will trigger with other wine versions]

Other games ran in wine don't appear to trigger this memory leak:
Insurgency [Source-engine]
The Elder Scrolls V: Skyrim

Upon closer inspection, as soon as I have control of the character in Deus Ex: Human Revolution, CPU usage of lxqt-session skyrockets and memory usage steadily increases, in proportion with [I'm assuming] how many polygons are on screen.  Load screens and the main menu do not have any effect on lxqt-session.  I find this to be extremely bizarre, and I hope lxqt's developers have more of a clue than I do.

Until it's fixed, I can just play an hour or two, then logout and log back in.

**Comment by ilag11111** [comment]
I have just discovered that turning off shadows in Human Revolution's option menu prevents the memory leak.  This is making even less sense.

**Comment by goetzc** [comment]
I have also experienced this memory leak of lxqt-session. I don't know how to reproduce this. I don't use Wine, but Arduino IDE (JAVA) most of the time, Firefox and Quod Libet.

Using the LXQt git packages from Arch Linux' AUR

**Comment by KaMiila** [comment]
I have also noticed this, it caused a huge ram overload while playing Neverwinter (the free-to-play mmorpg by perfectworld).  After about an hour or two of gameplay all of a sudden lxqt-session ate 8 gigs of ram, causing me to hit swap space.  I had to kill X.  I also noticed that after running wine games, lxqt-session will either continue to eat more ram or just hang there still consuming the ram it ate while the wine app was running.  It usually likes to hang around 2 gigs of ram on an 8 gig system.  Only in Neverwinter have I experienced it eat all my ram.  I have no idea what is causing this issue.  It seems odd to me that wine applications are causing a ram leak in lxqt-session.

I am running lxqt-session 0.9.0 x86_64.

Here is a link to my buildscript:
https://github.com/KaMiila/SlackBuilds/blob/master/lxqt/lxqt-session/lxqt-session.SlackBuild

I also run wine-1.7.29-x86_64  (it is a multilib wine install that has both 32 and 64 bit) *redundant comment ftw*

**Comment by keturn** [comment]
Was something done to address this, or did it just close due to inactivity?

I just had lxqt-session showing 5 GB resident memory. And yes, it was also while running a game under Wine.

- lxqt-session 0.13.0
- liblxqt   0.13.0
- Qt        5.9.5
- Ubuntu        18.10

**Comment by agaida** [comment]
Three years of literally nothing - what do you expect: All devs now playing wine games until the possible underlying wine bug is found and fixed?  Erm. No.

Feel free to open a new bug when it is sure that the bug is in LXQt. 

Sure means: The behaviour should be easy to reproduce, has not to be in any graphics or gl driver and not in wine.

@tsujan - what do you think?

**Comment by tsujan** [comment]
> Was something done to address this, or did it just close due to inactivity?

It's closed because the code has changed a lot since 2015 and there's no memory leak.

LXQt 0.13.0 is very old, BTW.

**Comment by tsujan** [comment]
> Feel free to open a new bug when it is sure that the bug is in LXQt.

He shouldn't open a bug with LXQt 0.13.

**Comment by tsujan** [comment]
Even in 2015, this bug should have been reported to Wine developers.

**Comment by agaida** [comment]
Thats why i wrote: Feel free, if the bug i on our side - suspect wine (first hand) or the graphics stack. Nothing we should care about unless it is proven as our fault,

**Comment by tsujan** [comment]
> suspect wine (first hand) or the graphics stack. 

Exactly.

**Comment by keturn** [comment]
How would a bug in wine or the graphics stack change the heap size of the lxqt-session process?

In any case, more details filed with launchpad, as you suggested: https://bugs.launchpad.net/ubuntu/+source/lxqt-session/+bug/1823416

**Comment by tsujan** [comment]
If you install `ksysguard`, you could right click a process, click "Detailed Memory Information" and see private and shared memories in a nice GUI.

**Comment by wxl** [comment]
Since based on lxqt/lxqt-session#256 we have confirmed this, should we not reopen this?

**Comment by tsujan** [comment]
I would if its title wasn't misleading. See @keturn's explanation here: https://github.com/lxqt/lxqt-session/pull/256#issuecomment-480529836

**Comment by wxl** [comment]
We could always rename it. Or is there another bug tracking this?

**Comment by tsujan** [comment]
There's no use to that. The real way of reproducing the problem is in the PR, not here. The PR doesn't include "closes...fixes...." either.
