### ISSUE TITLE
Feature Request: right-click on desktop bring up LXQT menu

### ISSUE THREAD

**Issue by DiscipleOfDante** [lxqt/lxqt#464]
There is an option in the LXQt settings to have right-click bring up the window manager menu. Perhaps it could be possible to also administer an option to bring up the LXQt start menu as well. It is a popular feature, and at the moment it is possible to bring up the Openbox menu, but the Openbox menu is not dynamic by default, and many LXQt users might not know how to configure Openbox properly.

**Comment by pmattern** [comment]
Seems like a reasonable idea to me.
I'd suggest to not handle Application menu's content as an alternative to LXQt's own desktop context menu but to simply include it as another item, though. It's done that way in Xfce where I find it pretty handy.
As a side-effect actions regarding the session - logout, shutdown and so on - are accessible from the desktop itself that way, too.

**Comment by tsujan** [comment]
-> https://github.com/lxqt/pcmanfm-qt/issues/10
