### ISSUE TITLE
Feature Request: SDDM Configurator

### ISSUE THREAD

**Issue by DiscipleOfDante** [lxqt/lxqt#465]
SDDM is quickly becoming THE Qt DM. It is already recommended in the channel message of the LXDE/LXQt irc channel, so perhaps there could be a configurator to allow users of LXQt a graphical means of configuring the DM.

**Comment by hagabaka** [comment]
I wrote an SDDM configuration GUI with Ruby/QML. It's still in alpha but feel free to check it out: https://github.com/hagabaka/sddm-config-editor

**Comment by hagabaka** [comment]
I'd just like to update that I've ported [sddm-config-editor](https://github.com/hagabaka/sddm-config-editor/tree/master/cpp) to C++.

**Comment by paulolieuthier** [comment]
@hagabaka awesome. Your work is very appreciated.

**Comment by agaida** [comment]
@hagabaka - do you still work on sddm-config-editor?

**Comment by hagabaka** [comment]
@agaida no, I have not worked on it in a long time, and probably won't in the foreseeable future.

**Comment by agaida** [comment]
would transfering it to LXQt be a option for you? (of course with full access to the repo - and the other LXQt things)

**Comment by hagabaka** [comment]
Sure, I'd be happy to do that.

**Comment by agaida** [comment]
cool - all you need to do is to go into repo settings and hit the transfer button

**Comment by agaida** [comment]
in case that don't work that easy, just poke me

**Comment by hagabaka** [comment]
OK, I've transferred it to lxqt.

**Comment by agaida** [comment]
@luis-pereira @palinek @PCMan  @tsujan - we finally have sddm-config-editor under our umbrella. So i guess we should polish and release it asap.

**Comment by tsujan** [comment]
@hagabaka, thank you very much!

**Comment by agaida** [comment]
i guess this can be closed now.
