### ISSUE TITLE
Improve lxqt-config-file-associations > Application Chooser performance

### ISSUE THREAD

**Issue by luis-pereira** [lxqt/lxqt#467]
The Other Applications is taking too long to get fully presentable to the user.

**Comment by paulolieuthier** [comment]
It should be cached.

**Comment by luis-pereira** [comment]
@paulolieuthier The performance bottleneck seems to be the Ui actually.

**Comment by PCMan** [comment]
There are several possible bottle necks of this part.
1. Loading the database (but normally this is cached so should be fast)
2. Parsing the mimeinfo file (however, this file is not very large in usual cases, so it should be fast enough most of the time)
3. Loading all of the icons (This one is most suspicious). Loading one icon takes about 1000 system calls according to current implementation in QIcon. In addition to the I/O, png decoding or even svg painting is required. You can try not to load the icons and see if things becomes faster. Then we can confirm this one.

**Comment by PCMan** [comment]
This can also caused by frequent repainting of the window.
You called QCoreApplication to process paint events when inserting items.
This results in repainting of the widget everytime you inserted an item.
Better to use QStandardItemModel with QTreeView so you can set the model to the view when you finish loading and the window is only updated once.

**Comment by PCMan** [comment]
Just cooked a PR for it.
https://github.com/lxde/lxqt-config/pull/38

**Comment by luis-pereira** [comment]
@PCMan I also believe that repainting is an performance bottleneck here, although I didn't yet tried it out. When I adapted the code to use QMimeType/XdgMimeType I tryed to get rid of QCoreApplication::processEvents()... but at that time Qt5 had some weird event loops bugs. I will give it another try.

**Comment by paulolieuthier** [comment]
@luis-pereira how do you think it could be further optimized?

**Comment by tsujan** [comment]
Not a problem anymore.
