### ISSUE TITLE
LXQt panel: dedicated panel object to handle session

### ISSUE THREAD

**Issue by pmattern** [lxqt/lxqt#477]
Actions regarding the session itself - logout, reboot and so on - should be provided by some kind of dedicated panel object, not just by Application menu and runner.
An object like this should provide a pop-up window offering all available actions, as e. g. seen with LXDE, not necessarily by default but at least as an option.

Pulling single items to quicklaunch isn't an alternative. Topic "Leave" from Application menu's top level can't be dragged into it and adding single items is taking way to much horizontal space.
It didn't matter whether this was implemented as a new panel plugin or as some special object that can be added to quicklaunch, much as it's done in LXDE (hence "panel object" not "plugin").

The simple fact that panel objects like this are available in all major desktop environments is providing quite some evidence that this is something needed, imho.

**Comment by paulolieuthier** [comment]
@pmattern there is a new `.desktop` file now, called `lxqt-leave.desktop`.  It calls `lxqt-leave --gui`, and that triggers a dialog with leave session options. What do you think of that?

**Comment by pmattern** [comment]
GUI `lxqt-leave --gui` plus lxqt-leave.desktop pulled into a Quick launcher instance are providing what I had in mind so basically this issue is solved.
I'd mostly agree with the polishing stated by antis81 in #579 which should be rather easy to handle I suppose. Something not that good is the interaction between `lxqt-leave --gui` and its desktop entry file on the one hand and the rest of the desktop on the other. Not sure how to do it better so just sharing my thoughts:

lxqt-leave.desktop doesn't really fit into submenu "Leave" as it's related to the other items therein regarding content but the GUI it invokes is of a different kind.

It could be placed in Application menu's top level instead.
Having both sub-menu "Leave" and lxqt-leave.desktop therein is some kind of duplicate and not really intuitive.
It would be sufficient to have only one of those two items accessible from Application menu. But in that case the other one couldn't get added to Quick launch any longer right now.

This could be circumvented by modifying Quick launcher such that items can't be added by drag & drop from Application menu only but also from within Quick launcher's context menu. But neither do I know whether this is feasible nor what a list of addable plugins should look like.
Modifying Quick launcher that way could be helpful independently from this issue, too.
As an alternative a new panel plugin could get created that's basically similar to Quick launcher but allows for adding the desktop entry files corresponding to binary lxqt-leave from its context menu.

To have all kinds of users' liking configurable conveniently both a modified Quick launch plugin as described in previous paragraph and a GUI to edit Application menu would be needed.
