### ISSUE TITLE
External monitor turns off after ~15 minutes, no powermanagement activated

### ISSUE THREAD

**Issue by Grarap** [lxqt/lxqt#494]
My external monitor (I'm not using my laptop's internal one) turns off after around 15 minutes (I can check what time exactly it takes if necessary) even though I tried
– disabling all settings in the power management settings (no settings that would turn off my monitor were activated anyways)
– stopping the power management service
– uninstalling the entire power management package.

Seeing that there's an issue reported here where somebody asks for power management to be able to disable the screen makes this issue especially strange since I already seem to have that feature.

I have KDE Plasma and many KDE applications installed and use some of them under Lxqt. Could that perhaps somehow drag in KDE's power management as a dependency (I would be surprised though…)? I looked at my process list but didn't find anything power or energy saving related except for the upower demon.

**Comment by rcmn** [comment]
Same here.I run a very "tight lxqt version" , the least kde,gtk application
as possible.It never really bothered me but my external monitor also turn
off after a while. ~15 min seems correct. Also I have all power management
option disabled. I have an Nvidia Quatro 1000M install with proprietary
drivers which come with it's own X server setting manager. But I cannot
find a power manager options.

On Wed, Feb 11, 2015 at 4:58 AM, Grarap <notifications@github.com> wrote:

> My external monitor (I'm not using my laptop's internal one) turns off
> after around 15 minutes (I can check what time exactly it takes if
> necessary) even though I tried
> – disabling all settings in the power management settings (no settings
> that would turn off my monitor were activated anyways)
> – stopping the power management service
> – uninstalling the entire power management package.
>
> Seeing that there's an issue reported here where somebody asks for power
> management to be able to disable the screen makes this issue especially
> strange since I already seem to have that feature.
>
> I have KDE Plasma and many KDE applications installed and use some of them
> under Lxqt. Could that perhaps somehow drag in KDE's power management as a
> dependency (I would be surprised though…)? I looked at my process list but
> didn't find anything power or energy saving related except for the upower
> demon.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lxde/lxqt/issues/494>.
>



-- 
R.

**Comment by surlykke** [comment]
2015-02-11 6:16 GMT+01:00 rcmn <notifications@github.com>:

> Same here.I run a very "tight lxqt version" , the least kde,gtk application
> as possible.It never really bothered me but my external monitor also turn
> off after a while. ~15 min seems correct. Also I have all power management
> option disabled. I have an Nvidia Quatro 1000M install with proprietary
> drivers which come with it's own X server setting manager. But I cannot
> find a power manager options.
>
>
> On Wed, Feb 11, 2015 at 4:58 AM, Grarap <notifications@github.com> wrote:
>
> > My external monitor (I'm not using my laptop's internal one) turns off
> > after around 15 minutes (I can check what time exactly it takes if
> > necessary) even though I tried
> > – disabling all settings in the power management settings (no settings
> > that would turn off my monitor were activated anyways)
> > – stopping the power management service
> > – uninstalling the entire power management package.
> >
> > Seeing that there's an issue reported here where somebody asks for power
> > management to be able to disable the screen makes this issue especially
> > strange since I already seem to have that feature.
> >
> > I have KDE Plasma and many KDE applications installed and use some of
> them
> > under Lxqt. Could that perhaps somehow drag in KDE's power management as
> a
> > dependency (I would be surprised though…)? I looked at my process list
> but
> > didn't find anything power or energy saving related except for the upower
> > demon.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/lxde/lxqt/issues/494>.
> >
>
>
>
> --
> R.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lxde/lxqt/issues/494#issuecomment-73835379>.
>
There's nothing in lxqt that can do this, to my knowledge, so it must be
something else. You wouldn't happen to be using systemd/logind and have an
IdleAction configured in /etc/systemd/logind.conf ?

br. Chr.

**Comment by rcmn** [comment]
cat  /etc/systemd/logind.conf
#  This file is part of systemd.
#
#  systemd is free software; you can redistribute it and/or modify it
#  under the terms of the GNU Lesser General Public License as published by
#  the Free Software Foundation; either version 2.1 of the License,
or

#  (at your option) any later
version.

#

# See logind.conf(5) for
details



[Login]

#NAutoVTs=6

#ReserveVT=6

#KillUserProcesses=no

#KillOnlyUsers=

#KillExcludeUsers=root

#InhibitDelayMaxSec=5

#HandlePowerKey=poweroff

#HandleSuspendKey=suspend

#HandleHibernateKey=hibernate

#HandleLidSwitch=suspend

#PowerKeyIgnoreInhibited=no

#SuspendKeyIgnoreInhibited=no

#HibernateKeyIgnoreInhibited=no

#LidSwitchIgnoreInhibited=yes

#IdleAction=ignore

#IdleActionSec=30min


I really don't know how power management works. But there is no way the
tool could overlook a settings in what ever file/application it suppose to
interface ?

On Wed, Feb 11, 2015 at 12:08 PM, Christian Surlykke <
notifications@github.com> wrote:

> 2015-02-11 6:16 GMT+01:00 rcmn <notifications@github.com>:
>
> > Same here.I run a very "tight lxqt version" , the least kde,gtk
> application
> > as possible.It never really bothered me but my external monitor also turn
> > off after a while. ~15 min seems correct. Also I have all power
> management
> > option disabled. I have an Nvidia Quatro 1000M install with proprietary
> > drivers which come with it's own X server setting manager. But I cannot
> > find a power manager options.
> >
> >
> > On Wed, Feb 11, 2015 at 4:58 AM, Grarap <notifications@github.com>
> wrote:
> >
> > > My external monitor (I'm not using my laptop's internal one) turns off
> > > after around 15 minutes (I can check what time exactly it takes if
> > > necessary) even though I tried
> > > – disabling all settings in the power management settings (no settings
> > > that would turn off my monitor were activated anyways)
> > > – stopping the power management service
> > > – uninstalling the entire power management package.
> > >
> > > Seeing that there's an issue reported here where somebody asks for
> power
> > > management to be able to disable the screen makes this issue especially
> > > strange since I already seem to have that feature.
> > >
> > > I have KDE Plasma and many KDE applications installed and use some of
> > them
> > > under Lxqt. Could that perhaps somehow drag in KDE's power management
> as
> > a
> > > dependency (I would be surprised though…)? I looked at my process list
> > but
> > > didn't find anything power or energy saving related except for the
> upower
> > > demon.
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/lxde/lxqt/issues/494>.
> > >
> >
> >
> >
> > --
> > R.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/lxde/lxqt/issues/494#issuecomment-73835379>.
> >
> There's nothing in lxqt that can do this, to my knowledge, so it must be
> something else. You wouldn't happen to be using systemd/logind and have an
> IdleAction configured in /etc/systemd/logind.conf ?
>
> br. Chr.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lxde/lxqt/issues/494#issuecomment-73839783>.
>



-- 
R.

**Comment by Grarap** [comment]
I am also using the proprietary driver from Nvidia and my logind is empty/everything commented out too. 
When I was still using KDE, I was able to disable KDE's power management when I was e.g. watching a movie and the external monitor did not turn off, so either the problem did not occur there or KDE's power management somehow blocked the 'feature' we're having trouble with now.

I could try using Nouveau again and see if the problem persists, but not before friday.

**Comment by Vladimir-csp** [comment]
Default dpms timeouts are hard-coded into X server.
Try creating an xorg.conf snippet to override:
/etc/X11/xorg.conf.d/15-default-flags.conf
```
Section "ServerFlags"
# disable low-level screensaver and screen DPMS poweroff
	Option "BlankTime"  "0"
	Option "StandbyTime" "0"
	Option "SuspendTime" "0"
	Option "OffTime"  "0"
EndSection

```

**Comment by Vladimir-csp** [comment]
Maybe lxqt-config-powermanagement should somehow show current X values for DPMS when idle handling is disabled.

**Comment by jleclanche** [comment]
We could show a warning if the user has [dpms set up in x11](https://wiki.archlinux.org/index.php/Display_Power_Management_Signaling#Modifying_DPMS_and_screensaver_settings_using_xset).

**Comment by Grarap** [comment]
I think KDE's way of just overriding DPMS, if active, is the preferable way of doing things, because there, power management just did what I expected it to do, I didn't have to know anything about DPMS.

**Comment by Thorn-Inurcide** [comment]
i have this issue as well, I created a tiny executable bash script that disables blanking and dpms, and I just manually activate the screensaver if i want it, usually i just turn my monitor off completely though. I have it auto starting with the session management tools.
#!/bin/bash
xset s off
xset -dpms

**Comment by goetzc** [comment]
Related issue #223.

**Comment by laurento** [comment]
I'd also suggest to have a look at the "caffeine" extension in Cinnamon. IMHO it has a pretty useful feature to automatically prevent the blankscreen to occur while some audio is reproduced.

**Comment by tsujan** [comment]
See #223

**Comment by mmortal03** [comment]
> See #223

@tsujan, I think the rationale used to resolve #223 did not end up resulting in a fix for *this* issue? This issue is sort of the *opposite* situation, if you follow me? That is, nothing has been done such that LXQt Power Management will override whatever is hard coded into X server (so as to resolve the conflict between DPMS and Idleness Watcher), as per the above comment. (At least we have the mentioned workaround that can be applied): https://github.com/lxqt/lxqt/issues/494#issuecomment-75027004

**Comment by tsujan** [comment]
@mmortal03
Would you please open an issue at https://github.com/lxqt/lxqt-powermanagement/issues, with a concise description of the problem? The title of this old report is misleading, as if an external monitor should exist.

IMHO, If the goal is overriding the hard-coded dpms timeouts of the X server, touching `xorg.conf` or starting power management with commands like `xset dpms 0 0 0` and `xset -dpms` won't be good solutions, but the daemon might simply check idleness every minute or so and break it if needed.

**Comment by tsujan** [comment]
This is what I have in mind:

After checking whether it's being run under X11, the daemon may be able to verify if DPMS is inactive (XCB_DPMS_DPMS_MODE_OFF) or not. If it's active, it'll deactivate it at startup. It can also check and deactivate it if needed each time its own timeout is reached.

It may also be possible to to the above-mentioned check every minute, but I guess it'll be an overkill.

Which X11 function does it (`xcb_dpms_force_level`?), I'm not sure yet, but there should be one.

**Comment by tsujan** [comment]
→ https://github.com/lxqt/lxqt-powermanagement/issues/374

**Comment by mmortal03** [comment]
@tsujan, I just installed Debian 12 with LXQt 1.2.0 fresh on different laptop hardware, and can't reproduce what was happening on the first laptop (which is also Debian 12 and LXQt 1.2.0). What's worse, I'm not having any luck retracing my steps to reproduce it on the first laptop, either. I'm going to have to do a fresh install on the first laptop to see if I can reproduce it from scratch. Maybe I originally overlooked something, or I just happened upon some weird edge case? Honestly, you'd think there'd be more people mentioning this lately if it was a common problem. Let's see if I can generate a clear test case before you spend any more time on this!

**Comment by tsujan** [comment]
@mmortal03 
Here, on Manjaro, `xset q` shows 600 for DPMS by default. Years ago, I'd set it to 0 in a startup script (as a way of avoiding the problem). After using the solution proposed at https://github.com/lxqt/lxqt-powermanagement/issues/374, I have 0 for timeouts, without that script.

> I just installed Debian 12 with LXQt 1.2.0 fresh...

Perhaps different distros have different defaults. But we can't rely on that; can we? Also, KDE seems to do the same thing.

**Comment by mmortal03** [comment]
Yeah, same on Debian, with 600 as the default for Standby, Suspend, and Off. 

But, to be sure, it's showing "DPMS is Disabled", on both laptops, so that can't be what was different in terms of it blanking before? Maybe it was never enabled and I just assumed?

I'd earlier added the "ServerFlags" from the comment above to the first laptop's xorg.conf.d folder, and I believed that those were what had finally solved the problem. But I've since removed those and the screen hasn't started going blank again -- so now I figure it couldn't have been that, either.

One additional detail, I had XScreenSaver disabled, and I had the Advanced settings "Fade to"/"Fade from Black" unchecked there, but those also aren't making any difference. 

The only thing I can think of is that when I modified the idle times in Idle Watcher, that something was causing those settings being made in the GUI to not consistently stick? 

The whole issue was that I swear they were set to "Nothing" but I was still experiencing the screen blanking after a period of time.

**Comment by tsujan** [comment]
> But, to be sure, it's showing "DPMS is Disabled"

DPMS will be enabled as soon as, for example, the screen is turned off.

> One additional detail, I had XScreenSaver disabled

XScreenSaver uses its own settings. I don't have it installed here.

> The whole issue was that I swear they were set to "Nothing" but...

With the proposed solution, if "Enable Idleness watcher" is checked, the screen should never get blank — unless XScreenSaver or another app makes it blank.

**Comment by tsujan** [comment]
Finally done in https://github.com/lxqt/lxqt-powermanagement/commit/74ec93212e614f53e5c9990c1ec5bd35c2bb5990

**Comment by mmortal03** [comment]
@tsujan , thanks for working on this. I read through the discussion on your commits. 

Unfortunately, I still haven't been able to reproduce the unexpected behavior that I saw before. At least going forward I'll know that whenever Debian gets the next version of LXQt that this should be fixed. :)

**Comment by mmortal03** [comment]
Ok, right after I gave up, I made a breakthrough. I've got steps to reproduce it now. 

I'm not able to directly test your commits to master, @tsujan , but maybe you can confirm that the following is fixed by your code?

Steps to reproduce: 
1.)  Open Power Management Settings and go to the Idle submenu. Make sure that Idleness Watcher is enabled and that "When idle on AC" set to "Nothing". Leave the settings window open.
2. ) Open a console and run "xset s off -dpms" to make sure DPMS is disabled.
3.) Run "xset q" to verify that DPMS is Disabled, and note that "Standby, Suspend, and Off" are set at 600 seconds.
4.) Go back to the Power Management Settings window, set "When idle on AC" to: "Turn off Monitor(s)", and set the option "AC Idle time" to: "03:00". Click away from the settings window, but leave it open.
5.) Wait three minutes without touching anything. The screen will go blank.
6.) Run "xset q" again, and you will see that DPMS has become Enabled after the screen went blank!
7.) Go to the Power Management Settings window and set "When idle on AC" back to: "Nothing". Click away from the settings window, but leave it open.
8.) Wait ten minutes (i.e. 600 seconds) without touching anything.

Actual Result: The screen goes blank.

Expected Result: The screen doesn't go blank, because the blanking of the screen after step 5 should never have caused DPMS to be Enabled. The user believes that, following step 7, that they have disabled the blanking of the screen, and are confused as to why this has not happened.

**Comment by tsujan** [comment]
> Run "xset q" again, and you will see that DPMS has become Enabled

As I mentioned [above](https://github.com/lxqt/lxqt/issues/494#issuecomment-1641512684) — and as [Arch wiki](https://wiki.archlinux.org/title/Display_Power_Management_Signaling) explains — the effect of `-dpms` would be reverted as soon as the monitor is turned off. That's how DPMS works.

> but maybe you can confirm that the following is fixed by your code?

The code doesn't make that mistake. So, yes, what you see is fixed.

**Comment by tsujan** [comment]
Your comment made me think that I might have missed one parameter. While the code sets the standby, suspend and off timeouts to zero, it doesn't touch the "screensaver" blanking timeout. It should also be set to zero. I'll add a PR for it soon. Thanks!.

**Comment by tsujan** [comment]
Also screensaver is suspended in https://github.com/lxqt/lxqt-powermanagement/pull/376. I don't think anything else remains to do.
