### ISSUE TITLE
Add brightness sortcuts by default

### ISSUE THREAD

**Issue by theredbaron1834** [lxqt/lxqt#504]
Having the ability to on a fresh install just press XF86MonBrightnessUp or XF86MonBrightnessDown and have them just work would be awesome. I know that you don't want to depend on outside software, but maybe if you have xbacklight installed, or whatever, use that.

With the talk of moving lxqt-config-monitor to KScreen, I thought maybe you could add the ability to set brightness by cli, thus allowing shortcuts to be added to Global Actions Manager without any outside programs. Right now I run a small script that does the same thing, but having them "just work" would be a nice addition.

**Comment by jleclanche** [comment]
This is something that is supported by ... well, I don't know what supports it. But on most of my devices, screen brightness works out of the box when hitting those keys. For some it doesn't. Kernel? Systemd? Who knows...

What device are you using where this doesn't currently work? What system do you have on it?

**Comment by theredbaron1834** [comment]
My current laptop is a macbook (2008 model). It doesn't work without using something, be it xbacklight, or whatever.

Also, on my Aspire One D257 it also doesn't work either (or at least didn't, I have used it in about 2 months). I used xbacklight and lxqt-globalkey to get it to work right.

**Comment by jleclanche** [comment]
@theredbaron1834 what system do you have? do you have systemd?

**Comment by Vladimir-csp** [comment]
On some devices behavior of brightness buttons depends on acpi_osi kernel boot parameter. This is the case for my ASUS U24E laptop.
Hardware can either handle these button inetnally, or pass them to OS. I keep xbacklight shortcuts in openbox just in case. It does not hurt. And if something changes an hardware will start passing brightness buttons to OS, it would still work.

**Comment by jleclanche** [comment]
If you have xbacklight bound to brightness buttons *and* the kernel handles it too, you have backlight being set twice and there's a flicker that goes with it since xbacklight is slightly slower... this is my problem. We still see the XF86- keybind being triggered even if it's handled elsewhere.

**Comment by pmattern** [comment]
Handling brightness by keyboard is actually already discussed in #36.
