### ISSUE TITLE
pcmanfm-qt : pressing Enter runs something

### ISSUE THREAD

**Issue by Esclapion** [lxqt/lxqt#534]
When nothing is selected (so Desktop  by default), pressing Enter runs something of the Desktop.

For example, I have a shortcut to hexchat on the desktop. If I open a window, but forget to select it, hexchat start when I press Enter. I often have the problem.

Difficult to explain, but annoying ;)

**Comment by tsujan** [comment]
Oh, this old report was forgotten because it wasn't reported at pcmanfm-qt's issue tracker.

It's the same with pcmanfm-qt window: nothing may be selected but always an item has the focus (some styles draw a dotted rectangle around focused items) and it'll be opened by pressing Enter.

I agree that this behavior is a little annoying and should be changed.

**Comment by stefonarch** [comment]
It runs the last   file which was selected with nothing selected, and this is true  for every pcmanfm-qt window, not only desktop.

**Comment by tsujan** [comment]
Please test https://github.com/lxqt/libfm-qt/pull/307 . It isn't as trivial as it looks. Dolphin has the same counterintuitive behavior but no one has noticed it!

**Comment by agaida** [comment]
the reason might be: dolphin don't paint the desktop

**Comment by tsujan** [comment]
> the reason might be: dolphin don't paint the desktop

It makes no difference. When its window is open and active, it's weird when a file is launched while no file is selected. Most people don't press `Enter` for no reason though.

**Comment by stefonarch** [comment]
The fix is working here, desktop and windows.

**Comment by tsujan** [comment]
Thanks for the feedback! I was a little worried about probable side effects, although I couldn't think of any. Anyhow, I don't see a side effect here.

**Comment by stefonarch** [comment]
Yeah, I don't handle much files atm, so I cannot tell about side effects too. Time will tell ;)
