### ISSUE TITLE
[lxqt-config] Wider filters

### ISSUE THREAD

**Issue by Vladimir-csp** [lxqt/lxqt#573]
Current lxqt-config interface is good, but it only shows applications which have both 'Settings' and 'LXQt' categories. This is an adequate default. But by accessing configuration center, user might expect to find other configuration tools for installed applications.
I propose adding a filter to lxqt-config top toolbar which shows only LXQt category by default, but can be widened if needed.
Anyway, configuration center is just an application menu which shows applications related to configuration, based on their categories.

**Comment by stefonarch** [comment]
> But by accessing configuration center, user might expect to find other configuration tools for installed applications.
This is now implemented in "other settings":
https://github.com/lxqt/lxqt-config/commit/1f5c3f71d3a844729038a50197b7a6469f5802f4

**Comment by tsujan** [comment]
> This is now implemented in "other settings":

"Other Settings" was a cool addition. This can be closed.
