### ISSUE TITLE
LXQt notificationd: truncated messages

### ISSUE THREAD

**Issue by pmattern** [lxqt/lxqt#595]
Under some circumstances the "Body" of messages (see "Basic Design" in [ Desktop Notifications Specification](https://developer.gnome.org/notification-spec/)) gets truncated without a real reason.

An example how to reproduce is pasting the following lines

```
Lorem ipsum dolor sit amet, consetetur
sadipscing elitr, sed diam nonumy eirmod
tempor invidunt ut labore et dolore magna
aliquyam erat, sed diam voluptua. At vero
eos et accusam et justo duo dolores et ea
rebum.
```

into a file notification.txt and invoke `notify-send "Some summary." "$(cat notification.txt)"`.
If width is set to 300px and spacing to 10px in lxqt-config-notificationd the text will be cut. It will be complete if either width is set to 390px due to which no additional wraps have to be added or spacing is set to 50px.

But as long as both the defined width and a sufficient amount of vertical space are available messages should never get truncated.

**Comment by pmattern** [comment]
Turns out the problem also exists in buttons within notifications like the following from `nm-applet` with the notifications' width set to 300px
![lxqt-notificationd_cut-text-in-buttons_300px](https://cloud.githubusercontent.com/assets/9860801/10707634/d27ac316-79f5-11e5-81ec-5f7820d2a764.png)
and 400px
![lxqt-notificationd_cut-text-in-buttons_400px](https://cloud.githubusercontent.com/assets/9860801/10707638/d96ce956-79f5-11e5-9bcb-3d6b7fd8e2a2.png)
respectively in `lxqt-config-notificationd`.

Buttons like this seem to be implemented as "Action" in terms of the specification linked in the first comment.

**Comment by agaida** [comment]
Solved long ago
