### ISSUE TITLE
LXQt notificationd: background elements should be transparent

### ISSUE THREAD

**Issue by pmattern** [lxqt/lxqt#596]
LXQt notificationd messages come along with some black background elements. It would look much better if those were transparent.

Most prominent one is spacing between messages.
![lxqt_notificationd_intransparent-background](https://cloud.githubusercontent.com/assets/9860801/7163592/2f8c85c2-e39b-11e4-8c8f-d3222b82f4d8.png)

Messages themselves seem to have a black rectangle as background, too. Parts of it can be seen at single messages' edges and corners. The latter only applies if there's another background with round corners like the grey one of theme Kde-plasma shown in the screenshot.

**Comment by paulolieuthier** [comment]
@pmattern which theme is that one?

**Comment by pmattern** [comment]
Kde-plasma. As stated in the message.

**Comment by paulolieuthier** [comment]
Oh, sorry. And the window manager?

**Comment by pmattern** [comment]
Oh, interesting: all findings so far with Openbox 3.5.2. Your question made me check KWin (5.2.2) - problem doesn't exist using it.

As I'm not sure whether there's some misunderstanding: The actual problem exists with all themes provided by lxqt-common. Just that corner thing is limited to those themes furnishing the messages with round corners.

**Comment by paulolieuthier** [comment]
What you want is a compositor. Openbox does not have compositing.

https://wiki.archlinux.org/index.php/Openbox#Compositing_effects

**Comment by Esclapion** [comment]
Yep, I use now compton and compton-conf with very good results.

**Comment by paulolieuthier** [comment]
Then we have a problem, indeed.

**Comment by palinek** [comment]
The background widget is transparent and for the transparency a compositing WM is needed (or standalone compositor). The same "issue" affects also other components.

**Comment by pmattern** [comment]
I had another look at this using different (non-) compositing window managers and indeed, compositing was the missing piece.

But this seems like a design worth re-considering to me:

LXQt is meant to be lightweight. Compositing does need additional resources, can very well cause performance penalties on resource-constrained devices but doesn't provide anything essential.
So it's pretty odd that it's needed to prevent something as common as several notificationd messages at once and according to palinek even more components from looking ugly.
Neither KDE Plasma nor Xfce do need compositing to display several desktop notifications at once reasonably.

**Comment by paulolieuthier** [comment]
It's true. Transparency is a very basic and should be provided.

**Comment by Esclapion** [comment]
Nope. if you disable the compositor in xfce, the taksbar is no more transparent, for example. I did now the try. But Xfce has an integrated compositor, than we can disable to improve performance.

**Comment by paulolieuthier** [comment]
Yeah, I mean the transparency between the notifications. How xfce without composition handles it?

**Comment by surlykke** [comment]
2015-04-15 23:13 GMT+02:00 Paulo Lieuthier <notifications@github.com>:

> Yeah, I mean the transparency between the notifications. How xfce without
> composition handles it?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lxde/lxqt/issues/596#issuecomment-93571160>.
>

Last time i checked (about the time notificationd was written (by Petr
Vanek)), Qt did not support transparency of top level widgets without a
compositor. That was Qt4. It may have changed for Qt5 but I doubt it - so
you'll have to do an awful lot of coding to get this.

br. Chr.

**Comment by pmattern** [comment]
> Last time ... Qt did not support transparency of top level widgets without a compositor.

So it would be even more interesting to figure out how the KDE folks are handling this (which I can't do myself, unfortunately):
![kde-plasma_several-notifications](https://cloud.githubusercontent.com/assets/9860801/7177260/737c3446-e425-11e4-8337-79d98cd27f09.png)
Plasma 5.2.2 using Openbox, no Compton installed.

Also, would be interesting to know which "other components" are effected as well. @palinek ?

**Comment by palinek** [comment]
AFIAK

**Comment by palinek** [comment]
let's see if we can do something with the transparency...

**Comment by Esclapion** [comment]
It can be "false" transparency. I can obtain that for example with urxvt, but it's not so good as "true", and it's probably heavy.

**Comment by paulolieuthier** [comment]
Plasma's approach is too different as it's QML-based.

**Comment by paulolieuthier** [comment]
I imagine we have a widget in which we create the notifications balloons, right? If we had totally independent widgets for the balloons, there wouldn't be a background to be transparent at all. But to do that, we'd have to handle all those widgets positioning when a new balloon wants to appear.

**Comment by palinek** [comment]
...and also all the moving of other ballons when one of them disappears

**Comment by paulolieuthier** [comment]
And the scrolling when too many ballons appear. Too bad.

**Comment by palinek** [comment]
@jleclanche please, share your opinion on this...

**Comment by jleclanche** [comment]
Our current approach is fine, but the black borders appear occasionally only for me which means something is wrong.

**Comment by palinek** [comment]
This is an oldie...we're not going to spend time and implement some pesudotransparency logic by our-self.
