### ISSUE TITLE
lxqt-config: integrate panel configuration dialog in Configuration Center

### ISSUE THREAD

**Issue by pmattern** [lxqt/lxqt#599]
It would be good to have dialog window "Configure Panel", right now accessible from panel's context menu only, accessible from "Configuration Center" (binary lxqt-config) as well.

If I'm not mistaken, it's the goal of Configuration Center to have all important configuration settings summarized at one single spot. Integrating panel's configuration GUI would hence simply fit in that concept.
Moreover this would keep the panel configurable if it's not accessible itself as lxqt-config can be launched from runner. This in turn is something I for one would have loved to have more than once when there were issues involving RandR.

On a side note the said dialog window might eventually get merged with "Manage Panel Widgets" depending on the outcome of #598.

**Comment by Vladimir-csp** [comment]
lxqt-config is just a specialized application browser, so panel configuration dialog should be accessible via .desktop file, either as a binary or as an argument to lxqt-panel.

**Comment by jleclanche** [comment]
I'm tentatively -1 on this

**Comment by excalibur1234** [comment]
i support this.

xfce also has ALL settings available in their configuration center.

if you leave a link to the panel settings out of the configuration center, why keep a link to the desktop settings (to set the wallpaper, etc.)?

**Comment by AcarBurak** [comment]
As long as you don't remove the config from the panel itself… since some users (me, for instance!) may use panel without the lxqt-desktop/session etc.

**Comment by stefonarch** [comment]
Not so trivial maybe, if there are more panels.

**Comment by tsujan** [comment]
> Not so trivial maybe, if there are more panels.

Correct. This report should have been closed years ago.
