### ISSUE TITLE
Application chooser

### ISSUE THREAD

**Issue by npmiller** [lxqt/lxqt#603]
Shouldn't the application chooser present in `lxqt-config/lxqt-config-file-associations` be moved to somewhere more generic where it can be used by other parts of LxQt (maybe liblxqt?). It would allow to have a real application chooser in `lxqt-config-session` for example, instead of opening a file picker in `/usr/bin`.

**Comment by Vladimir-csp** [comment]
Sounds logical!
I would also suggest adding a custom command option (in form of text input) to application chooser that would create user-level application with that command on the fly.

**Comment by Vladimir-csp** [comment]
There even may be some code reusability possibilities with #580.

**Comment by tsujan** [comment]
So many things have changed since 2015.
