### ISSUE TITLE
Stretchable spacer in lxqt-panel

### ISSUE THREAD

**Issue by Baltasarq** [lxqt/lxqt#631]
I use to show only icons of my applications in the task manager (no text, i.e., no window title). Using _LXDE_, I configure a spacer to stretch, so the open applications are centered on the panel (menu button and quick launch icons to the left, system tray to the right, that is left unchanged).

I've tried to change the panel's alignment to center, with no luck. BTW, changing that does not seem to change anything.

However, in **lxqt** I cannot do that, the spacer is not stretchable. Can that functionality be added?

**Comment by Baltasarq** [comment]
Today I have received an update for **lxqt-panel**, and the situation has changed a little bit. Now the icons for applications are not stacked to the left, it seems that although I've set the panel not to show any text, it still reserves more space than needed just for the icon. It is visually better, but I'd prefer to have all icons together in the middle of the panel, if possible.

**Comment by palinek** [comment]
Right now, you can achieve that partialy only by using multiple panels (assuming you are using panel on the bottom of screen), e.g:
- one: align left, size 30%
- two: align center, size 40% (this panel will hold only taskbar)
- three: align right, size 30%

**Comment by Baltasarq** [comment]
Hi,

> Right now, you can achieve that partialy only by using multiple panels
> (assuming you are using panel on the bottom of screen), e.g:
>
>    - one: align left, size 30%
>    - two: align center, size 40% (this panel will hold only taskbar)
>    - three: align right, size 30%
>
> Interesting, I assumed there could be only one panel, specially for the
same part of the screen. Yes, mine's at the bottom.

-- Baltasar

>

**Comment by palinek** [comment]
> Interesting, I assumed there could be only one panel, specially for the
same part of the screen. Yes, mine's at the bottom.

Nope. You can have multiple panels on the same screen edge. See this example:
![screenshot](https://cloud.githubusercontent.com/assets/10990929/7471673/03618b2a-f32a-11e4-826e-ddb109059162.png)

![screenshot](https://cloud.githubusercontent.com/assets/10990929/7471642/de0cca74-f329-11e4-8293-3d3ad2087294.png)

**Comment by agaida** [comment]
done
