### ISSUE TITLE
make trigger of message disappearance configurable

### ISSUE THREAD

**Issue by pmattern** [lxqt/lxqt#640]
In earlier versions of lxqt-notificationd messages used to disappear on hovering, that is after moving the mouse pointer first over a message and next to a different place on the desktop. This was considered undesirable behaviour and changed in lxde/lxqt-notificationd@3c38894. Recently on freenode #lxde we came to the conclusion the said "old" behaviour does have advantages and is something nice to have in many situations, though.

Thus it would be good to have a means to select between old and new behaviour, most likely from within `lxqt-config-notificationd`.

**Comment by jleclanche** [comment]
I'm -1 on this.
