### ISSUE TITLE
two problems regarding placement of dialog windows

### ISSUE THREAD

**Issue by pmattern** [lxqt/lxqt#643]
Dialog windows don't seem to consider auto-placement methods of window managers but get placed in displays' center. As a consequence they can overlap or cover each other besides sufficient space is available.
An example is to place Configuration Center in a display's upper left and open first "Desktop Notifications" and then "Desktop Preferences" by double-clicking.
This finding can be made using Openbox 3.5.2 or 3.6, KWin 5.3.1 or Xfwm 4.12. 3 in their respective default settings.

If dialog windows get moved within a screen by drag & drop their position gets automatically reverted to center by switching to another virtual desktop and back to the one displaying the windows in question. Windows can still be seen at the correct position for a fraction of a second but then jump back to the center.
This can be annoying if several windows of that kind are opened at once which in turn is a rather common setting considering the typical usage of dialog windows "Configure Panel" from panel's context menu and "Add Plugins" invoked from the former.
It doesn't matter whether virtual desktops are changed by mouse or keyboard shortcuts.
This finding is affecting Openbox only, neither KWin nor Xfwm, versions as stated above.

Not sure which kind of window exactly is affected. But all findings can be reproduced with dialog windows "Configure Panel" and "Add Plugins" as stated above as well as all topics summarized in "Configuration Center" right now.
Latest Git checkout of all LXQt components compiled against Qt 5.4.1 or 5.4.2 on Arch Linux i686 and x86_64.

**Comment by palinek** [comment]
> If dialog windows get moved within a screen by drag & drop their position gets automatically reverted to center by switching to another virtual desktop and back to the one displaying the windows in question.

Hm... I don't see such behaviour here.

**Comment by pmattern** [comment]
Strange as I can still see it.
As said above this finding is limited to Openbox and can't be seen with KWin or Xfwm. So it would be interesting to know which version of both Openbox and all other LXQt you're using. Also, could you post your rc.xml somewhere?

**Comment by palinek** [comment]
- openbox version:
```
$ openbox --version
Openbox 3.5.2
Copyright (c) 2004   Mikael Magnusson
Copyright (c) 2002   Dana Jansens

This program comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions. See the file COPYING for details.
```

- LXQt packages from siduction/lxqt (yesterday's build)
- [rc.xml](https://gist.github.com/palinek/fe1e0998cea915b40c6c)

**Comment by pmattern** [comment]
The rc.xml you've provided is setting up a single virtual desktop only
```
  <desktops>
    [...]
    <number>1</number>
    [...]
```
So either it's not the one you've been using or there's some misunderstanding...

**Comment by palinek** [comment]
Of course :) normaly i don't use multiple desktops. Only when testing something i increase number of desktops via obconf...i'll try to paste the rc.xml active when testing later...

**Comment by palinek** [comment]
@pmattern with [this](https://gist.github.com/palinek/eaee3a82add2e7c29bcb) configuration I didn't observe placement changing of dialogs while switching the desktops

**Comment by pmattern** [comment]
Another look into the second problem "jump back to center" on Arch Linux, Debian Testing, Lubuntu 15.05 and Siduction strongly suggests it exists as of Qt 5.*4* only.
rc.xml on the other hand seems totally unrelated.

**Comment by Vladimir-csp** [comment]
I'm confirming lxqt-config-* windows (at least some I've checked) jumping back to center on desktop switch. (Debian testing, no related rules in openbox).
No window should interfere with WM placement policy unless there is a specific need for that.

**Comment by tsujan** [comment]
Discussed elsewhere (can't find it in this mess): Qt forces dialog positioning, overriding the WM.
