### ISSUE TITLE
Appications Control+<something> shortcuts are blocked by lxqt-globalkeysd

### ISSUE THREAD

**Issue by anton7811** [lxqt/lxqt#648]
Even when I disable Control+F5 in global shortcuts manager I'm still not able to use it for page refresh in browser. I had to disable Global Keyboard Shortcut to make it working. As a result I missed a possibility to use any custom/standard global shortcuts in LXQt.
Playing with "multiple actions behaviour" didn't give any result. I tried to change property value and even restart lxqt-globalkeysd from session manager for this.

Environment:
Ubuntu 14.04 x86_64
LXQt: 0.9.0 (ppa:lubuntu-dev/lubuntu-daily)

P.S.: #331 already warns about using Control in standard shortcuts because of possible conflicts.

**Comment by palinek** [comment]
This was already discussed in lxde/lxqt#618 and (hopefuly) fixed in lxde/lxqt-globalkeys#13.
Don't know if it is already in the ppa

**Comment by anton7811** [comment]
Sorry for duplicate. Forgot to search trough closed issues as well.
Looks like it should be fixed. However I propose to wait for updates to verify and close this one.

**Comment by anton7811** [comment]
I noticed that my lxqt-globalkeysd is build at Wed, 20 May 2015 11:16:26 and the fix is merged to master at May 19. I would expect that the fix is in place however Control+F5 is still blocked by lxqt-globalkeysd.

deb package changelog contains only build date.

Is there any other way to check if the fix is included in ppa?

**Comment by palinek** [comment]
@anton7811 do you still facing this issue?

**Comment by anton7811** [comment]
Yes, still the same. Ones I enable lxqt-globalkeysd Ctrl+F5 stops to work in browsers even if there is no such shortcut in globalkeys.
I've found a workaround for myself. I'm using ~/.config/openbox/rc.xml to config necessary shortcuts.
However this doesn't allow me to use Alt+F2

**Comment by fenugrec** [comment]
Minor bump... still an issue with lxqt-globalkeys 0.12.0
