### ISSUE TITLE
lxqt-panel: Tray icon spacing

### ISSUE THREAD

**Issue by Vladimir-csp** [lxqt/lxqt#662]
Spacing between icons in tray is too large, eats up lots of space on small screen. See screenshot, it is almost half of the panel.
1-2 px should be enough, or please make an option to configure spacing.
![panel](https://cloud.githubusercontent.com/assets/4061903/7903712/8d8be976-07ed-11e5-8a09-c0aeed1fe415.png)

**Comment by palinek** [comment]
The padding/margin of tray icons is configured in theme, e.g. for frost:
```css
TrayIcon {
    border: 0px;
    margin: 2px;
    padding: 2px;
}
```
I'm not a graphic designer...so wouldn't touch that (there are many paddings/margins all around in the styles). Maybe someone can create some "condensed" theme.

**Comment by Vladimir-csp** [comment]
I think it is safe to set padding: 0px; margin: 1px;
All icons are clearly visible, bloat is reduced to minimum.
![panel_compact](https://cloud.githubusercontent.com/assets/4061903/7909906/c9401526-0858-11e5-989a-eb3051bf0c63.png)

**Comment by Esclapion** [comment]
It's also true for the quick launch icons, at the left side (if horizontal panel ;). Maybe more.

How to change that also ?

**Comment by tsujan** [comment]
Tray is deprecated (although we have https://github.com/lxqt/lxqt-panel/commit/68ac3adb67f435c445d3336c7ce247a63f0f6ed8) and Status Notification has the auto-hiding feature.
