### ISSUE TITLE
[lxqt-config-monitor] Unable to delete stored conifgurations

### ISSUE THREAD

**Issue by PCMan** [lxqt/lxqt#679]
In current lxqt-config-monitor, we can save different configurations with different names.
However, there are no ways to manage the stored configurations.
For example, we cannot delete or rename them.
This creates usability issues.

**Comment by selairi** [comment]
Ok. I will update it until kscreen version has been finished.

2015-06-06 6:50 GMT+02:00, PCMan <notifications@github.com>:

**Comment by agaida** [comment]
done long ago
