### ISSUE TITLE
[pcmanfm-qt] paste tilde in address bar (open ~/.local)

### ISSUE THREAD

**Issue by q4a** [lxqt/lxqt#689]
Can not paste address like "~/.local/share/applications" in address bar. pcmanfm-qt open root folder instead.
system: lubuntu 15.04, pcmanfm-qt 0.9.0+bzr326+201506112232~ubuntu15.04.1 from lubuntu-dev/lubuntu-daily.

**Comment by pmattern** [comment]
Confirmed running lxde/pcmanfm-qt@2ec4b07.
Personally I wouldn't consider this essential as typing /home/\<user\> is rather easy due to auto-completion. But it does work in Dolphin, PCManFM (GTK) as well as Thunar and hence seems to be a rather common feature.

**Comment by tsujan** [comment]
Implemented ages ago.
