### ISSUE TITLE
Expanding the wiki

### ISSUE THREAD

**Issue by jubalh** [lxqt/lxqt#702]
The wiki should get expanded. I encourage everybody to share all his knowledge he has about lxqt. it will help gainig new developers reduce the need for asking people for certain stuff. so everybody can contribute.

speaking of which, i found in https://github.com/lxde/lxqt-panel/blob/master/panel/ilxqtpanelplugin.h a comment: 
_See <a href=https://github.com/LXDE-Qt/lxde-qt/wiki/How-to-write-the-panel-plugin>
How to write the panel plugin</a> for more information about how to make your plugins._
Did this wiki get lost? Somebody still has it? Does it contain valuable information that could get updated and put in the new wiki?

**Comment by agaida** [comment]
it's still a wiki - so if anyone mind improving it ...
