### ISSUE TITLE
implement feedback of application launch

### ISSUE THREAD

**Issue by pmattern** [lxqt/lxqt#703]
I think it would be useful to have an optical notification like some special mouse cursor or panel icon as long as an application was launched but its actual GUI didn't come up yet.

Of course it's not an obligatory feature and should be handled as such in the configuration.
But it's something many users like to have and aside from this actually fitting lightweight DEs well. Those tend to run on not so powerful systems where launching takes rather long which makes it difficult to judge whether it is ongoing or failed. Optical notifications can be informative in situations like this and help to avoid launching multiple instances per application due to erroneously considering a launch to have failed, see e. g. [Mailing List](http://sourceforge.net/p/lxde/mailman/message/34178320/) recently.

Can't say much about the technical details, though.
The most widely adopted standard is freedesktop's [Startup Notification [Protocol]](http://freedesktop.org/wiki/Specifications/startup-notification-spec/) that comes with a reference implementation [startup-notification](http://freedesktop.org/wiki/Software/startup-notification/). These seem to be limited to the X window system.
In KDE, there's a feature called "Launch Feedback" but I couldn't find further information about it. Also, in Plasma 5 I couldn't get the mouse cursor to change while the panel icon works.
FWIW the feature is implemented in LXDE, too.

**Comment by jleclanche** [comment]
Man do I hate that spec. 

We should implement it somehow yes but first I'd like to see what's going to happen with wayland.

**Comment by agaida** [comment]
superceded by #1554
