### ISSUE TITLE
Directories from LXQt menu should not dropable to quicklaunch

### ISSUE THREAD

**Issue by agaida** [lxqt/lxqt#707]
unless they can be displayed as menu
![quicklaunch](https://cloud.githubusercontent.com/assets/1162845/8273742/73b7e35e-187a-11e5-907b-1c34a1db0848.jpg)

**Comment by pmattern** [comment]
I think this should be merged into lxde/lxqt-panel#149.

**Comment by paulolieuthier** [comment]
lxde/lxqt-panel#149 is a work in progress to make directories usable in quick launch. The problem is that the directory names are not always the same as the categories.
