### ISSUE TITLE
LXQt Configuration Center should not cripple icons and labels

### ISSUE THREAD

**Issue by agaida** [lxqt/lxqt#710]
See both entries for the alternatives system and nVidia settings
![settings icons](https://cloud.githubusercontent.com/assets/1162845/8273830/05249d52-187e-11e5-88d0-04bd52fd4c5b.png)

**Comment by pmattern** [comment]
Shouldn't this be merged into #501? That one doesn't cover the icons but does address the text already.

**Comment by agaida** [comment]
not reproducible anymore
