### ISSUE TITLE
lxqt-powermanagement: can not find delayed systray

### ISSUE THREAD

**Issue by Vladimir-csp** [lxqt/lxqt#724]
If lxqt-powermanagement (and some other components, I suspect) is launched before any systray, it will not show its icon when systray appear. Restarting systray provider (panel) does not help.
I know that lxqt-session has a feature to hold some sartup items until systray is available, but this is not standard case. Applications should handle missing/delayed systray by themselves.

**Comment by paulolieuthier** [comment]
Do you see another application behaving that way as well?

**Comment by palinek** [comment]
Actualy according to [qt doc](http://doc.qt.io/qt-5/qsystemtrayicon.html) the icon should appear "automagicaly":
```
If the system tray is unavailable when a system tray icon is constructed, but becomes available later, QSystemTrayIcon will automatically add an entry for the application in the system tray if the icon is visible.
```

**Comment by Vladimir-csp** [comment]
lxqt-powermanagement is the only lxqt trayicon application I use. Other than that qlipper also behaves the same way.

**Comment by surlykke** [comment]
Den 02/07/2015 5.00 PM skrev "Vladimir-csp" <notifications@github.com>:
>
> lxqt-powermanagement is the only lxqt trayicon application I use. Other
than that qlipper also behaves the same way.
>
I vaguely remember looking into this a couple of years ago. I think I
concluded that qt doesn't do as documented. I only tested with our systray,
though. (Well - razors systray, back then.)

Br. Chr.

**Comment by ArthurBorsboom** [comment]
Xpad, a GTK3 sticky notes application, used to have the same issue. To prevent the application from quitting due to the missing systray, Xpad has two counter measures built-in.

1. It uses "X-LXQt-Need-Tray=true" in its desktop file, so it gets launched after the lxqt-panel is loaded.
2. It has a configurable startup delay. 

Maybe these options might be useful?

**Comment by Vladimir-csp** [comment]
> Xpad has two counter measures built-in.

>    It uses "X-LXQt-Need-Tray=true" in its desktop file, so it gets launched after the lxqt-panel is loaded.
>    It has a configurable startup delay.

>Maybe these options might be useful?

These are not related or built-in to Xpad.

**Comment by ArthurBorsboom** [comment]
What I meant is:

"Applications should handle missing/delayed systray by themselves."

This is what Xpad does. But I am wondering if this helps you. :)

**Comment by Vladimir-csp** [comment]
Two things that you've listed are not related to systray handling by the application.
X-LXQt-Need-Tray is a hint to lxqt-session, and start delay is an unrelated function that just may help a bit if conditions are right. And Xpad does not even do any of that.

**Comment by ArthurBorsboom** [comment]
Xpad does have both of these options. I am quite sure of it, since I have implemented it myself :)

To prevent going off-topic to much, what would you like to have?

**Comment by Vladimir-csp** [comment]
OK, now I get it. You are Xpad developer, and Xpad in Debian is pretty outdated now.
To clarify my point on countermeasures:
1. `X-LXQt-Need-Tray=true` is technically not in application, but in its autostart entry, and is LXQt specific. It does not allow application to catch delayed systray by itself, but rather tells session manager not to start application until systray known to sessoin manager is up. Handy for broken apps that can not wait for systray on their own.
2. This is just a start delay, it is a handy feature and *can* be used to work around delayed systray on session startup or in some other cases. But a race condition can still ruin the attempt.

None of these countermeasures allow application itself to track systray. As in: launch xpad without session or tray, wait two weeks, launch some systray, voila: it got xpad in it. This is basically the intended QSystemTrayIcon behavior what was described in https://github.com/lxde/lxqt/issues/724#issuecomment-117828261, but fails in lxqt-powermanagement for some reason.

...and I've just checked my outdated xpad 4.1 by launching it without a systray and then launching systray (tint2) later. It worked. So, why those countermeasures were implemented in the first place? Xpad successfully tracks systray without them.

Sorry for all the offtopic.

**Comment by ArthurBorsboom** [comment]
> So, why those countermeasures were implemented in the first place?

I recall Xpad was not waiting for the systray, thus I implemented workarounds.
Maybe the difference lies in GTK2 (Xpad <= 4.1) and GTK3 (Xpad > 4.1)?

However, your original question was lxqt-powermanagement should be waiting for the systray due to the use of QSystemTrayIcon, but it does not. Is that right?

**Comment by Vladimir-csp** [comment]
To be chronologically correct, I've filed the issue about lxqt-powermanagement not waiting for systray correctly. Then @palinek pointed out that QSystemTrayIcon documentation states it should provide that behavior by default, but for some reason it does not.

**Comment by ArthurBorsboom** [comment]
Ah, okay. At least I understand your issue. So, now the stories come together. :)

If the issue is an upstream issue and should, but will not be resolved upstream, then it might be an option to implement some of the provided (semi) workarounds like in Xpad or even better ones.

Since I have no Qt development experience, I'm afraid I can't help you more than this.
Good luck.

**Comment by paulolieuthier** [comment]
Just to give some light here: Qt 5 applications using QSystemTrayIcon in LXQt (and in KDE) use the new protocol (status notifier item). I'm not sure if that helps, I'm just saying.
