### ISSUE TITLE
lxqt-panel: volume plugin: adjustment stepping wrong

### ISSUE THREAD

**Issue by ypnos** [lxqt/lxqt#727]
When I configure the step size to '2' the following happens:
- volume up key: adjusts by +1
- volume down key: adjusts by -3
- mouse wheel up: adjusts by +5
- mouse wheel down: adjusts by -7

First I wonder why the mouse wheel is not doing the same thing as the keyboard.
Second obviously the behavior is wrong. It was not like this in an earlier version. Testing with current git right now.

**Comment by pmattern** [comment]
Confirmed on Arch Linux x86_64 running latest Git code as well.

**Comment by ypnos** [comment]
Is this a Qt bug? When having the popup open, focusing on the slider, then pressing up and down, we observe the same behavior. In the qtpanel code the slider is autonomous in how he handles the input (step size is a Qt slider property).

**Comment by paulolieuthier** [comment]
@ypnos the problem is with our pulseaudio code. Pulseaudio doesn't go from 0 to 100, it has a wider scale. So we have to normalize it. Are you sure it was right before? I know it was different, but IIRC, it was already wrong before.

**Comment by ypnos** [comment]
I think your comment refers to #739

**Comment by paulolieuthier** [comment]
You're right :disappointed:.
