### ISSUE TITLE
lxqt-notificationd: shortcuts to close/bring back message

### ISSUE THREAD

**Issue by Vladimir-csp** [lxqt/lxqt#767]
Please add keyboard shortcuts to lxqt-notificaiond to close or bring back messages (one by one).
I propose defaults: `Super+Backspace` for closing messages and `Ctrl+Super+Backspace`

**Comment by jleclanche** [comment]
I'm -1 on defining one by default, but would be OK with a PR that implements an optional shortcut to close *all* (not one).

**Comment by tsujan** [comment]
Superseded by https://github.com/lxqt/lxqt/issues/1573
