### ISSUE TITLE
password of network shares not stored

### ISSUE THREAD

**Issue by ArthurBorsboom** [lxqt/lxqt#774]
Although I am not sure if this is a bug or a configuration issue, for some reason pcmanfm-qt combined with gvfs-smb, does not store the passwords I enter for Windows (SMB) shares, even though I select "remember forever".

![2015-08-06-101632_490x345_scrot](https://cloud.githubusercontent.com/assets/6639859/9107004/7615041a-3c24-11e5-95e4-fdd69d28e0c9.png)

Any idea how to accomplish this?

**Comment by pmattern** [comment]
Same findings with FTP and SFTP, regarding the latter both passwords of the remote user or an eventual local certificate used to authenticate.
So it seems all kinds of network shares are affected. Adjusting title accordingly.

**Comment by paulolieuthier** [comment]
@ArthurBorsboom does gnome-keyring help you?

**Comment by ArthurBorsboom** [comment]
I believe I have the gnome-keyring installed, but maybe it is misconfigured.

Is the gnome-keyring used by pcmanfm-qt / gvfs? If so, I guess it has to be
a (optional) dependency.

**Comment by Salzi** [comment]
Is there a work around for this?
It's a bit annoying to enter the credits every day.
Thanks for any hint

**Comment by Aanok** [comment]
Have there been any developments?

**Comment by Folatt** [comment]
I would like to ask the same thing. 
I'm having the same issue with owncloud. Gnome-keyring works fine, but I don't like solving issues by using packages that have the name of other desktop environments in it.
I have zero knowledge of keyrings or keys, so what I'm saying next is probably really stupid, 
but I see python-keyring existing in my package manager. Can't lxqt integrate that as password storer for such apps?

**Comment by chrislovessushi** [comment]
This appears to still be an issue.

**Comment by tsujan** [comment]
First, sorry for the late reply.

This part of libfm-qt code is incomplete. I think @PCMan has a plan for it. Recently, he has been very busy with porting the old API to C++11 and making libfm-qt independent of libfm. That's partly done but there's still a lot of work to do.

**Comment by McThump** [comment]
Any chance of getting the priority of this elevated? I am migrating users from Windows to Debian / LXQt. Users not being able to conveniently save credentials for network shares is forcing me to install Nautilus for them.

**Comment by tsujan** [comment]
> Any chance of getting the priority of this elevated?

You just did so. Old reports that are in a wrong place may be be buried under others. This one was forgotten (the right place was https://github.com/lxqt/pcmanfm-qt/issues).

The fix is here: https://github.com/lxqt/libfm-qt/pull/535 . It needs `gnome-keyring` to work.
