### ISSUE TITLE
libfm libtool didn't use LDFLAGS ?

### ISSUE THREAD

**Issue by comicfans** [lxqt/lxqt#778]
I try to build libfm (--with-extra-only) with address sanitizer (which requires flags -fsanitize=address when linking)

seems the link script is in generated libtool:360

`\$CC -shared \$pic_flag \$libobjs \$deplibs \$compiler_flags \$wl-soname \$wl\$soname \$wl-version-script \$wl\$output_objdir/\$libname.ver -o \$lib`

**Comment by agaida** [comment]
not our problem anymore
