### ISSUE TITLE
should libfm compile with G_DISABLE_CHECKS force undefined? 

### ISSUE THREAD

**Issue by comicfans** [lxqt/lxqt#782]
libfm use many glib check macro (g_return_val_if_fail/g_return_if_fail) and depends on it's return value
(but these macro should be used to check undefined behaviour)

if G_DISABLE_CHECKS is defined, all these macro is replaced by empty statement (see gmessage.h)
this makes libfm behavior changed unexcepted. 
for example

FmFileInfo\* fm_file_info_ref(FmFileInfo\* fi)
{
    g_return_val_if_fail(fi != NULL, NULL);
    g_atomic_int_inc(&fi->n_ref);
    return fi;
}

will crash if G_DISABLE_CHECKS is defined and fi==NULL

**Comment by LStranger** [comment]
If any kind of crash happens then code that crashes should be fixed, not
workaround on bugged code enabled. Though it can be enabled simply with
an option --enable-debug for configure script.

**Comment by comicfans** [comment]
if that's the case, I think libfm should replace all g_return_val_if_fail/g_return_if_fail macro with manual check. currently user can trigger this sort of bug. 
steps:
1.access Network folder
2.access a nfs shared folder (maybe I havn't permission to read or I didn't have nfs cient support installed)
3. pcmanfm-qt warn me "unsupported location"
4.g_return_val_if_fail checking is skipped and pcmanfm-qt crashes in libfm.

**Comment by LStranger** [comment]
>if that's the case, I think libfm should replace all g_return_val_if_fail/g_return_if_fail macro with manual check. currently user can trigger this sort of bug. 

Well, if NULL is acceptable value then in documentation that is clearly
marked as (allow-none) but that in not the case for fm_file_info_ref(),
i.e. whenever that function is called it MUST be ensured that argument
isn't NULL, by caller, not inside the function, that's requirement. It's
what I meant when I wrote it should be fixed in the code.

>steps:
>1.access Network folder
>2.access a nfs shared folder (maybe I havn't permission to read or I didn't have nfs cient support installed)
>3. pcmanfm-qt warn me "unsupported location"

It's where pcmanfm-qt should NEVER call fm_file_info_ref() in the first
place, this invalid usage of libfm API should be fixed there, not in the
libfm. I'm sorry.

**Comment by LStranger** [comment]
To be more precise, g_return*if_fail macros are for diagnostics only,
they generate CRITICAL messages, and critical means exactly - the API
usage is invalid and should be fixed ASAP, those messages should never
appear in any production code, only in beta builds, which certainly
should enable debugging flags as I already suggested.

**Comment by agaida** [comment]
not our problem anymore
