### ISSUE TITLE
power button has no effect -> should call "lxqt-leave"

### ISSUE THREAD

**Issue by antis81** [lxqt/lxqt#789]
In LXDE based Lubuntu versions (like in 14.04 LTS), pressing the PC's power button calls `lubuntu-logout` (aka `lxsession-logout`). In LXQt, ~~it does nothing~~ calling `lxqt-leave` is what I expect on a desktop system. 

On my system, sometimes, a direct shutdown is triggered (don't know why).

System (for me always the same :smile:):

| Component | Version |
| --- | --- |
| Hardware | Macbook 2,1 (late 2007, plastic) |
| Distro | Lubuntu 15.04 (Linux kernel 3.19-26) |
| LXQt | >0.9 from lubuntu-daily ppa |

**Comment by pmattern** [comment]
> System (for me always the same ):

Sure. But we can't memorise the systems of all folks filing issues here.

**Comment by antis81** [comment]
@pmattern Yes, I know :) - That's why I copied the info. Oh, I see there's a line-break missing - will be corrected in a second.

**Comment by antis81** [comment]
@jleclanche A recent Kernel update (3.19.0-27) for Lubuntu, at least revived the power button (it now powers off the computer and has a reason to exist again :smile:). Would be great though, if LXQt shows the `lxqt-leave` dialog instead, as stated in issue description.

Further I attached an external keyboard including a "second" power button, which is still dead. I don't think it's LXQt related though.

**Comment by pmattern** [comment]
> Further I attached an external keyboard including a "second" power button, which is still dead. 

Sometimes stuff like that is handled at the firmware level (BIOS, UEFI).

**Comment by antis81** [comment]
@pmattern Thanks, I'll have a look at my EFI (no 'U' -> old MacBook 2,1). This also could be related to the key mapping (`pommed` for me). Anyway, support of the second power button is unrelated to this issue or LXQt environment - don't mind.

**Comment by antis81** [comment]
@jleclanche FYI - Sorry, I was wrong. The kernel update (actually **3.19.0-28** - not 27) **didn't fix** the power button (still not reacting most of the time). Anyway, this issue is not about fixing kernel related stuff … nothing to really worry about.
