### ISSUE TITLE
Management of the desktop icons

### ISSUE THREAD

**Issue by Esclapion** [lxqt/lxqt#812]
(Sorry if it already exists, but i can't find that)

How to have the trash icon (and maybe others) on the desktop ? It was possible with pcmanfm and users request that.

**Comment by agaida** [comment]
yeah, that one would be nice to have - and some more users will ask :)

**Comment by nbvcxz** [comment]
Also feel lack of this after change from pcmanfm (gtk)

**Comment by MttCastelli** [comment]
+1 asking for

**Comment by goetzc** [comment]
Also, for Management of the desktop icons, it would be great to be able to hide all icon, including files and folders.

**Comment by tsujan** [comment]
> Also, for Management of the desktop icons, it would be great to be able to hide all icon, including files and folders.

+1 Some users may not want icons on their desktops. I'll look into it.

**Comment by goetzc** [comment]
Is it possible to disable this behavior from within a config file? Or only by disabling pcmanfm-qt desktop management (and loosing the wallpaper)?

**Comment by tsujan** [comment]
> I found a workaround, just choose an empty folder for Desktop in LXQt's session settings -> Locations

Yes! So, there's no need to change anything in the code; pcmanfm-qt already has that feature.

**Comment by goetzc** [comment]
>Yes! So, there's no need to change anything in the code; pcmanfm-qt already has that feature.
A GUI with all those options would be nice to have.

**Comment by tsujan** [comment]
Oh, I'd overlooked the "trash icon" part! IMO, such a feature will be needed even if its implementation isn't easy.

**Comment by Vladimir-csp** [comment]
'Trash', 'Computer', etc. are all skeuomorphic lies.
...of which at least trash has an underlying spec and actual purpose.
I wish there could be some more reality-based user-side interfaces. Like a pane showing /media (or /media/$USER these days) directory with existing and potential mounts instead of a fake 'Computer' thingy. Or a trash pane which groups files by filesystems they are actually on.
Intuitive+functional+educational instead of intuitive+functional+misleading with piece of ghost of MS Bob.
Just a bunch of thoughts to consider.

**Comment by tsujan** [comment]
@Vladimir-csp 
Let's first make just a trash icon with empty/full states and a proper right-click menu on desktop.

I'm waiting for https://github.com/lxde/pcmanfm-qt/pull/355 to be decided because it not only will have a file shared by trash implementation but also might be needed by it.

**Comment by agaida** [comment]
@tsujan - we should not forget about that. :)

**Comment by tsujan** [comment]
It looks so complex that my Unconscious distracts me from it ;) But yes, now it's a good time to think about it more seriously. At least, there's no justification for ignoring it anymore.

**Comment by AndyHee** [comment]
> +1 Some users may not want icons on their desktops. I'll look into it.
So currently it's not possible to turn off desktop icons?

**Comment by tsujan** [comment]
> So currently it's still not possible to turn off desktop icons?

Don't you use pcmanfm-qt?

**Comment by AndyHee** [comment]
Yes, I'm using pcmanfm-qt. How to disable them?

**Comment by tsujan** [comment]
Right click on an empty space of desktop and check "Hide Desktop Items" (or its translation). It'll be remembered.

This issue isn't closed because it's also about a trash icon, which isn't implemented yet.

**Comment by AndyHee** [comment]
Thank you for your swift response!

I'm on lxqt 0.11.1. There appears no possibility to bring up a menu by clicking on the desktop.

**Comment by tsujan** [comment]
Your installed pcmanfm-qt should be too old: https://github.com/lxqt/pcmanfm-qt/releases

**Comment by AndyHee** [comment]
OK, thanks for clarifying this.

**Comment by agaida** [comment]
@tsujan - any idea about the trash bin? - btw, maybe an related issue: open pcmanfm-qt, type trash:/// in the bar - the content of the trash bin will be displayed. Now open pcmanfm-qt trash:/// from the command line.

**Comment by tsujan** [comment]
> Now open pcmanfm-qt trash:/// from the command line.

Oh, that's definitely a bug!

> any idea about the trash bin?

I may be wrong but I think it isn't elementary and needs a lot of thinking. Sooner or later -- most probably, later ;) -- I'll think about it.

**Comment by tsujan** [comment]
> At least, there's no justification for ignoring it anymore.

Replying to myself: There were several things that were more important IMO and my free time was exhausted that way.

**Comment by agaida** [comment]
My argument would be: with working virtual filesystems like trash:/// etc the trashbin should be easy to implement.

**Comment by tsujan** [comment]
Preliminary thoughts:

We should first know what Trash on Desktop can be. All items on Desktop are files/folders. Trash would be either a desktop entry (hence a file too) or something totally new and so, different from other items. In the first case, we have to find how to interact with it and update its icon when Trash is emptied/filled in other ways (impossible?). In the second case,...., I don't know yet; perhaps, we should extend the desktop code. Anyway, it doesn't seem easy to me.

**Comment by agaida** [comment]
you are right - and i have a kind of hint (how others do it) - plank (the dock) has an trash bin as plugin - it seems to work partly with LXQt. but it open / instead of trash:// - so maybe it will be better to ignore the request right now and fix our base (pcmanfm-qt/libfm-qt) first for virtual file systems (or whatever it is called)

**Comment by tsujan** [comment]
Don't get me wrong; adding a trash item to desktop is an interesting challenge to me. The fact is that whenever I start to think about it, more important things about libfm-qt/pcmanfm-qt start to occupy my mind -- maybe an unconscious defense mechanism ;)

**Comment by agaida** [comment]
imho a good defense mechanism - btw we urgently need an xeyes plugin  for the panel to be a fully mature desktop environment :dark_sunglasses: 

//me hide and crawl away

**Comment by agaida** [comment]
xeyes as panel plugin is really of no use - but nearly desktop environments provide it :)

**Comment by tsujan** [comment]
I had a reason not to use it anywhere ;) Maybe, it can compensate for a bad cursor theme but, in the hierarchy of priorities, it goes far below Trash on Desktop -- even below an item-view based main "menu", IMO.

Frankly, lots of features are missing but we can live without some for now. We have only a few active devs :(

**Comment by That-Random-Guy** [comment]
I know this issue isn't a priority and all--which I can agree with considering all the other things that need to be looked at--but this is something that _can_ eventually happen, correct?

**Comment by tsujan** [comment]
> but this is something that can eventually happen, correct?

A developer who's interested in such things should do it. Frankly, I'm not motivated, using Desktop for files that I want to access quickly, checking "Hide desktop items" when not, and accessing Trash through pcmanfm-qt's window.

**Comment by tsujan** [comment]
EDIT: It was an interesting challenge first but lost its attractiveness totally once I started to think about it more seriously ;) The amount of work wasn't proportional to the real use.

**Comment by agaida** [comment]
erm - ok - the very most pieces should be in place i hope. (enhanchements in pcmafm-qt) - so we should really fix it. Ok, i added this just for fun
```
 @agaida agaida added the high-priority label on 15 Jul
```

**Comment by agaida** [comment]
maybe i should add an rc-critical on it

**Comment by tsujan** [comment]
@agaida See https://github.com/lxqt/lxqt/issues/812#issuecomment-425576851

You know that I may do many things when I feel they're needed. The split view was a recent example. But a Trash icon on Desktop?!

**Comment by agaida** [comment]
from 2015 - and i miss it too:
How to have the trash icon (and maybe others) on the desktop ? It was possible with pcmanfm and users request that. (First post) - and to be honest: I was just to lazy to file this bug in 2013/14

**Comment by tsujan** [comment]
Let me explain it a little. Something like Trash isn't a usual item. Adding it needs very deep changes to the code of views in libfm-qt. The ideas was interesting to me at first but image when you start to do a huge amount of work to reach a result that doesn't have any real use (to you, at least). You simple stop!

Now, at some point, I may find out that it's easy to do. That's unlikely but if the miracle happens, why not? Or someone who's not influenced by my wrong ideas may find an elegant and easy way to do it.

**Comment by agaida** [comment]
tbh - we have a "trash icon" in pcmanfm-qt already - is it really a big problem to make a desktop "copy" of it - iirc the desktop is an pcmanfm-process

**Comment by tsujan** [comment]
> tbh - we have a "trash icon" in pcmanfm-qt already

You know that I know that ;) It's very different; it's just an item in the side-pane and its implementation was straightforward in some sense.

Our libfm-qt views have another story. A long time ago, PCMan removed the desktop specific codes and derived desktop from the the code of windowed views. There's no room for an unusual item like Trash in that code, as far as I see (and I hope I'm wrong).

**Comment by tsujan** [comment]
After giving it more thought, I think this may be possible in pcmanfm-qt:

If a desktop entry with the exact name `Trash.desktop` is found on Desktop and if its contents are:
```
[Desktop Entry]
Type=Application
Icon=user-trash
Name=Trash
GenericName=Trash
Comment=open trash in PCManFM
Categories=FileManager;Utility;Core;GTK;
Exec=pcmanfm-qt trash:///
StartupNotify=true
Terminal=false
MimeType=x-directory/normal;inode/directory;
```
then, a trash monitor could be set up so that the line `Icon=user-trash` could be updated when trash becomes full or empty. Also, its right-click menu should be changed and its icon should be updated on starting Desktop.

The good news: libfm-qt isn't touched and the user can create or delete the item.
The bad news: A LOT OF WORK for just a trash icon.

**Comment by agaida** [comment]
hmm - not only for a trash icon - also for network, user dir, computer 

/me run and hide

**Comment by tsujan** [comment]
Network, user dir and computer can be simple desktop files -- they don't need any file monitor. If they do, a more fundamental work will be needed in libfm-qt.

**Comment by eirenicon** [comment]
@tsujan I tried this on yesterday's build (which I made for testing) it does not access trash:/// but rather simply accesses /

> [Desktop Entry]
>Type=Application
>Icon=user-trash
>Name=Trash
>GenericName=Trash
>Comment=open trash in PCManFM
>Categories=FileManager;Utility;Core;GTK;
>Exec=pcmanfm-qt trash:///
>StartupNotify=true
>Terminal=false
>MimeType=x-directory/normal;inode/directory;

**Note** I then added "PLANK" to the desktop and added their trash icon it also does not access trash:///  but rather only /

My guess is that this is a bug.

**Comment by tsujan** [comment]
@eirenicon You did it with your *latest git LXQt*?!

Here, with the latest git pcmanfm-qt, the above desktop file opens Trash, not `/`.

**Comment by tsujan** [comment]
@eirenicon I'm afraid if you did it with your yesterday build, there should be a mistake in your build. I can't explain your observation in another way.

**Comment by eirenicon** [comment]
I certainly have no idea. I just followed the instructions Alf provided 
on github.

Given the interface issues I have encountered, I have to say a localized 
build problem makes perfect sense. I just am not certain how I'd fix 
whatever went wrong.  This actually reinforces why I wanted access to a 
clean build before running user tests.  Having a user test run against 
an unstable base will almost always yield random results... sorry.

Pax vobiscum,
...mark

------------------------------------------------------------------------

*Mark F. Rabideau,* *Owner/ Manager of:
PEP, Inc. & eirenicon l.l.c. +1.303.660.9400*
711 Nob Hill Trail - Franktown, Colorado USA - 80116
Former CMMI Institute Authorized High Maturity SCAMPI Lead Appraiser # 
0100059-00
SIX SIGMA Master Black Belt Certificate #3167140TY463591U
*PEP, Inc*.:_http://www.pep-inc.com_ <http://www.pep-inc.com/> 
*eirenicon l.l.c.*:_http://www.eirenicon.org_ 
<http://www.eirenicon.org/> */Envision-It!/*: 
_http://www.envision-it.org_ <http://www.envision-it.org/>

/*"*//*The privilege of a lifetime is being who you are.*//*"
*//*- Joseph Campbell*/

------------------------------------------------------------------------

/*The information transmitted is intended only for the person or entity 
to which it is addressed and may contain confidential and/or privileged 
material. Any review, retransmission, dissemination or other use of, or 
taking of any action in reliance upon, this information by persons or 
entities other than the intended recipient is prohibited. If you 
received this in error, please contact the sender and delete the 
material from any computer.*/

**Comment by tsujan** [comment]
@eirenicon 
Are ibfm-qt and pcmanfm-qt upgraded too? I don't think so but I can't be sure. Did you use something like `yaourt -S PACKAGE-git` for all components?

**Comment by tsujan** [comment]
@eirenicon

Under Manjaro, it's as easy as `yaourt -S PACKAGE-git` for all components, from the first to the last and in that order.

**Comment by eirenicon** [comment]
I'll give it a go... to see what happens.

Pax vobiscum,
...mark

------------------------------------------------------------------------

*Mark F. Rabideau,* *Owner/ Manager of:
PEP, Inc. & eirenicon l.l.c. +1.303.660.9400*
711 Nob Hill Trail - Franktown, Colorado USA - 80116
Former CMMI Institute Authorized High Maturity SCAMPI Lead Appraiser # 
0100059-00
SIX SIGMA Master Black Belt Certificate #3167140TY463591U
*PEP, Inc*.:_http://www.pep-inc.com_ <http://www.pep-inc.com/> 
*eirenicon l.l.c.*:_http://www.eirenicon.org_ 
<http://www.eirenicon.org/> */Envision-It!/*: 
_http://www.envision-it.org_ <http://www.envision-it.org/>

/*"*//*The privilege of a lifetime is being who you are.*//*"
*//*- Joseph Campbell*/

------------------------------------------------------------------------

/*The information transmitted is intended only for the person or entity 
to which it is addressed and may contain confidential and/or privileged 
material. Any review, retransmission, dissemination or other use of, or 
taking of any action in reliance upon, this information by persons or 
entities other than the intended recipient is prohibited. If you 
received this in error, please contact the sender and delete the 
material from any computer.*/

**Comment by eirenicon** [comment]
Here is what I used:


    About this repository

This is a superproject which contains all LXQt components. After 
checking out this repo please do the following to initialize git submodules.

|git submodule init git submodule update --remote --rebase |

Note: We require git >= 1.8.5


Pax vobiscum,
...mark

------------------------------------------------------------------------

*Mark F. Rabideau,* *Owner/ Manager of:
PEP, Inc. & eirenicon l.l.c. +1.303.660.9400*
711 Nob Hill Trail - Franktown, Colorado USA - 80116
Former CMMI Institute Authorized High Maturity SCAMPI Lead Appraiser # 
0100059-00
SIX SIGMA Master Black Belt Certificate #3167140TY463591U
*PEP, Inc*.:_http://www.pep-inc.com_ <http://www.pep-inc.com/> 
*eirenicon l.l.c.*:_http://www.eirenicon.org_ 
<http://www.eirenicon.org/> */Envision-It!/*: 
_http://www.envision-it.org_ <http://www.envision-it.org/>

/*"*//*The privilege of a lifetime is being who you are.*//*"
*//*- Joseph Campbell*/

------------------------------------------------------------------------

/*The information transmitted is intended only for the person or entity 
to which it is addressed and may contain confidential and/or privileged 
material. Any review, retransmission, dissemination or other use of, or 
taking of any action in reliance upon, this information by persons or 
entities other than the intended recipient is prohibited. If you 
received this in error, please contact the sender and delete the 
material from any computer.*/

**Comment by tsujan** [comment]
@eirenicon The best and safest way of having the latest git versions of anything is the distro way: the Arch way in Arch/Manjaro, the Debian way in Debian/Ubuntu, etc. If you don't build and install `pkg.tar.xz` packages, you might encounter various problems later. It's important that the package manager knows what's installed. Therefore, before doing anything, you need to master `pacman`.

If you've installed things manually, `pacman` won't overwrite them by default; you should tell it to do so (a trouble with manual installation that can be overcome easily).

A difference of Arch/Manjaro with ditros like Debian, Ubuntu, Fedora and OpenSUSE is that you don't need to wait for others to do the job for you. Building and installing one's own packages is the easiest with Arch -- as I mentioned elsewhere.

**Comment by eirenicon** [comment]
Good enough. I can easily do that.

Pax vobiscum,
...mark

------------------------------------------------------------------------

*Mark F. Rabideau,* *Owner/ Manager of:
PEP, Inc. & eirenicon l.l.c. +1.303.660.9400*
711 Nob Hill Trail - Franktown, Colorado USA - 80116
Former CMMI Institute Authorized High Maturity SCAMPI Lead Appraiser # 
0100059-00
SIX SIGMA Master Black Belt Certificate #3167140TY463591U
*PEP, Inc*.:_http://www.pep-inc.com_ <http://www.pep-inc.com/> 
*eirenicon l.l.c.*:_http://www.eirenicon.org_ 
<http://www.eirenicon.org/> */Envision-It!/*: 
_http://www.envision-it.org_ <http://www.envision-it.org/>

/*"*//*The privilege of a lifetime is being who you are.*//*"
*//*- Joseph Campbell*/

------------------------------------------------------------------------

/*The information transmitted is intended only for the person or entity 
to which it is addressed and may contain confidential and/or privileged 
material. Any review, retransmission, dissemination or other use of, or 
taking of any action in reliance upon, this information by persons or 
entities other than the intended recipient is prohibited. If you 
received this in error, please contact the sender and delete the 
material from any computer.*/

**Comment by agaida** [comment]
To be honest - i would like to have this in the release that goes into the next debian stable. And i would be more than a bit pissed if we don't manage it. So it has to be in the 0.14 release. Really.

I don't want to release 0.14. without. And when this means that we miss the debian deadline this will mean that 0.13 is in stable for the next two years. Might sound unkind but i'm serious about.

**Comment by tsujan** [comment]
I should see how it's done with the gtk based pcmanfm (if it's done). I think, at first, it was done by using a desktop file (as I suggested above) but later, that method was proven to be inefficient.

PCMan might solve this problem easily but, as someone who had never used LXDE and works on several projects, I can't promise anything other than saying I'll investigate it.

**Comment by tsujan** [comment]
> Might sound unkind but i'm serious about.

Not to me. I respect your decisions, as I've said on other occasions. But, sadly, every day has only 24 hours.

**Comment by agaida** [comment]
if anything else fails we should ask @PCMan for help - and as i said, i need to force it a bit because of the transition freeze of debian in January - so the release must be out and packaged, at least two libs has to go through NEW - i think i can get the packages into sid without a transition - but we need time for NEW as all the other maintainer will wake up an try to get their stuff through new  - and i don't want to miss a date because we are to lazy.

**Comment by agaida** [comment]
To be clear about: We can release all the things with point releases if some important changes are needed or we finish things that justify points. No problem until the soft freeze. But i want to be on the safe side if we really need a transition.

**Comment by PCMan** [comment]
The discusssion thread is pretty long now.:)
Anything I can help?

**Comment by tsujan** [comment]
@PCMan How can we add "virtual" items like Trash, Computer, etc. to `FolderModel`?

**Comment by PCMan** [comment]
@agaida There is an easy alternative to virtual items:
Just create a file trash-can.desktop in ~/Desktop
You can do the same for computer, network, etc. If you want, you can let the user config this in the desktop settings dialog (I rememberd that I left some check boxes as placeholders in the past)

To add "Empty trash" option to the trash can, there are two possible hacks:
1. Let Fm::FileMenu support actions defined in GDesktopAppInfo:
FYI: https://developer.gnome.org/gio/stable/gio-Desktop-file-based-GAppInfo.html#g-desktop-app-info-launch-action
So we can add different actions like "Empty Trash Can" to the trash-can.desktop

2. Write a desktop action that mathces basename = 'trash-can.desktop' and mime-type = "desktop entry file", and set its Exec=to "gvfs-rm trash:///*" (or implement deleting files via command line in pcmanfm, and set its title to "Empty Trash Can".
We actually support custom actions while very few people know this:
The spec: https://web.archive.org/web/20180627170128/www.nautilus-actions.org/?q=node/377

**Comment by tsujan** [comment]
> I rememberd that I left some check boxes as placeholders in the past

They were kept to for hiding *side-pane's* items for computer, network, etc. in future but, months ago, I added that functionality for all Places and Devices items by right clicking (like in Dolphin); so those checkboxes weren't needed anymore. However, they could be re-introduced with a different functionality.

> Just create a file trash-can.desktop in ~/Desktop...

Yes, something like that was/is used by classic GTK DEs. Will look into it.

I was rather thinking of a "cleaner" approach by modifying `FolderModel` but it doesn't seem to be worth the effort.

**Comment by tsujan** [comment]
@agaida I made the trash desktop entry update its icon on Trash jobs: https://www.dropbox.com/s/95xp9fwv15w2nsj/trash.mkv?dl=0

I did it as I'd suggested in https://github.com/lxqt/lxqt/issues/812#issuecomment-425593806 -- namely, without touching libfm-qt.

The other items can be simple desktop entries without special handling.

Several things should still be added and I'll add them in my free time; don't know when it'll be finished but it shouldn't take very long.

**Comment by agaida** [comment]
@tsujan @PCMan - now i'm happy again :grin:

**Comment by Vladimir-csp** [comment]
@PCMan wow, I just want to praise you for suggesting a way to implement these fake skeuomorphic entities in a way that is slightly less fake than usual.

**Comment by tsujan** [comment]
> now i'm happy again

Didn't do it as in https://github.com/lxqt/lxqt/issues/812#issuecomment-436237041 ;) I stole PCMan's method in libfm-qt. The most important thing about a trash icon is updating it; other jobs are routine (and boring).

**Comment by PCMan** [comment]
@tsujan a less hackish way to do the icon update.
1. install an file monitor on trash:/// (as what we did in Fm::PlacesModel) in Application.
2. do icon update based on info in the GFileInfo object.
3. Future refactor: move this stuff to a dedicated Fm::TrashCanManager class and hide the gio implementation details inside, and it can be used elsewhere rather than hard-coded in PlacesModel.

In this way, it's not part of the trash jobs. Also if the files in trash can are removed by other programs, this still works.

**Comment by tsujan** [comment]
@PCMan

> install an file monitor on trash:/// (as what we did i n Fm::PlacesModel) in Application.

I did it exactly in that way :)

> Future refactor: move this trash status monitoring stuff to a dedicated Fm::TrashCanManager class 

A job for future, I think.

**Comment by tsujan** [comment]
A good aspect of this approach is that we can easily have these:

![full](https://user-images.githubusercontent.com/981076/48084787-e3da8000-e20d-11e8-8196-a8b5224cddc6.png)
![empty](https://user-images.githubusercontent.com/981076/48084810-eb9a2480-e20d-11e8-9cbb-f395aa448c82.png)

**Comment by tsujan** [comment]
Update:

Please note that this is more than meets the eye. For example, we should trust our new desktop entries -- I mean the "trust" flag -- but shouldn't trust them only based on their names. All such desktop entries should be optional. I'm even searching for a way of hiding them when viewed from pcmanfm-qt's window (but that may not be possible).

So, it may take a while but not too long. Tomorrow, I'll continue the work.

**Comment by tsujan** [comment]
Update:

Finished, at last! Optional Trash (complete functionality, including DND) + Home + Computer + Network. As I expected, it's a relatively heavy patch but limited to `DesktopWindow`. Will test it a for a day before making a PR.

**Comment by tsujan** [comment]
Made the PR [here](https://github.com/lxqt/pcmanfm-qt/pull/810) because, tomorrow, I might not have time and it should be tested soon if it's going to be in the next release.

However, please test it as long as possible because it's a big patch.

**Comment by agaida** [comment]
https://github.com/lxqt/pcmanfm-qt/issues/811 - Follow up.

Thanks, Looks great.
