### ISSUE TITLE
Better UI to create shortcuts/app files (missing app to create a desktop shortcut)

### ISSUE THREAD

**Issue by q4a** [lxqt/lxqt#820]
As I remember I was able to create/edit desktop shortcut with lxshortcut in gtk version.
Is there app to help me create/edit desktop shortcut with same simple steps in lxqt?

**Comment by stefonarch** [comment]
You can simply  drop  icons from "applications" section on the left from
PCmanFM on the desktop.

Il 11/09/2015 19:52, q4a ha scritto:

**Comment by q4a** [comment]
Thanks for help, but i want to create new menu://applications entry (new .desktop file).
I tried to copy my binary "CopyAgent" file to "menu://applications/office", but result is empty .desktop file (see attached png).

PS I'm using ubuntu 15.03 amd64 with ppa:lubuntu-dev/lubuntu-daily

**Comment by pmattern** [comment]
Personally I think copying an arbitrary desktop entry file e. g. from `/usr/share/applications`, editing and moving back to that folder or to `~/.local/share/applications` is more convenient than any GUI.
But this is of course a matter of taste.

Also note that some basic functionality is available that you may use as kind of workaround:
LXQt is using freedesktop's [Autostart Specification](http://www.freedesktop.org/wiki/Specifications/autostart-spec) which is why `lxqt-config-session` (Application menu - Preferences - LXQt settings - Session Settings) is placing a new desktop entry file in `~/.config/autostart` if `Add` from `Autostart` is selected.
This desktop entry file is not of the sophisticated kind and has to be moved, though.

Nevertheless to my knowledge a Qt application to edit those menu entries isn't available so all in all this issue seems worth discussing to me.

**Comment by Vladimir-csp** [comment]
If Desktop entry editing application would be concieved, it would be logical to make it more universal. With the ability to toss entries between global/user application pool and autostart pool. 
I once thought of a concept named 'Undefied' (as in **Un**iversal **De**sktop **FI**le **Ed**itor). Even made an icon for it and tried to mash something together with bash and zenity, but obviously it didn't go well.
The full concept is: two-pane editor showing relations (overrides) between global (on the left) and user (on the right) desktop entries in user-friendly way (relationship icons between panes). Actions for entries would include overriding global with user, updating global, tossing application to global or user autostart, editing fields, etc. It could work for both application entries and autostart entries, enhancing (mostly replacing) session properties too.
If anyone wants to take a concept and/or name, I would be glad.

**Comment by Vladimir-csp** [comment]
> Personally I think copying an arbitrary desktop entry file e. g. from /usr/share/applications, editing and moving back to that folder or to ~/.local/share/applications is more convenient than any GUI.
But this is of course a matter of taste.

It is good if user knows the concept of desktop entries and where they should be placed. If not, GUI should reflect the concept in intuitive way.

**Comment by Vladimir-csp** [comment]
In case anyone is interested, here is a sketch:
![undefied_concept](https://cloud.githubusercontent.com/assets/4061903/9833350/45ac9a50-599c-11e5-810d-b04d40b8232a.png)

**Comment by jleclanche** [comment]
@Vladimir-csp That is far, far too complex. Anyway ideally we won't need a desktop file "creator" at all. What is it @q4a is actually trying to achieve?

**Comment by q4a** [comment]
Users want to do simple things with easy predictable way.
May file managers (including Windows Explorer and Nautilus) allow to:
1. Create link with context menu of file (via Right click).
2. Edit link in properties.
Check this for Nautilus: http://www.howtogeek.com/92840/create-shortcuts-for-your-favorite-or-most-used-folders-in-ubuntu/

My suggestions:
1. Create link.
Linux users are accustomed with symbolic links, but Windows users - with .desktop files. 
- Best way I can see for now is create submenu "Create link" or "Make link" (after "Open with ..." submenu) with 3 options:
A) Create .desktop file here
B) Create .desktop file to menu. It will create .desktop file to ~/.local/share/applications with empty category ("Categories=")
C) Create symlink
May be you will see better solution or any other options in submenu like "Create .desktop file on desktop"

2. Edit .desktop file.
2.1. On desktop: add new tab and allow user to edit icon with picking png, ico, etc file.
2.2. In "Start menu":
- Best way: allow drag’n’drop items from one category to another and right click with edit option same as in new tab from 2.1.
I know that this is Light DE, so there is another way:
- Simple way - right click on "Start button" should allow to move submenu item with arrows and edit each item like in 2.1, but without right click.

So main idea: make things easy for regular users:
1. They should not search where .desktop file is located (~/.local/share/applications or /usr/local/share/applications or other)
2. They should not edit .desktop file in text editor. Choosing category from existing and icon file from file system files is better way. IMHO.

**Comment by jleclanche** [comment]
I agree that we need a better UI to create shortcuts/app files but a desktop file editor doesn't make  it easy for users, it just makes it slightly easier for people who know the system already.

**Comment by q4a** [comment]
Yes. I (or you/moderator) can change topic to "Better UI to create shortcuts/app files", but we all agree, that something should be changed to better way.

**Comment by Vladimir-csp** [comment]
IMHO, naming menu entry that creates a desktop entry as "create link" is confusing and in fact an outright lie. "Create launcher" would be more appropriate in this case.

And the editor window (second) in mockup fits here, as it is pretty simple compared to the main window.

**Comment by Cybermaxrus** [comment]
Hello! Please add the ability to create shortcuts for files and folders in the LXQT. I want to create my Linux and Freebsd distributions and choose between Mate and LXQT. I want to choose LXQT because of QT, but the Mate can make shortcuts.

**Comment by tsujan** [comment]
Desktop right-click menu → Create Launcher:

![launcher](https://user-images.githubusercontent.com/981076/78950009-ad7bf100-7ae2-11ea-8320-86457db906c3.png)
