### ISSUE TITLE
lxqt-panel: keyboard layout application tracking

### ISSUE THREAD

**Issue by Vladimir-csp** [lxqt/lxqt#822]
There is a minor issue with keyboard layout switching, it seems to fail to track gksu prompt.
My situation with layouts us,ru:
- Starting from a bare X root window I switch to 'ru',
- then I call gmrun via openbox shortcut: layout correctly switches to 'en' for new window of new app.
- call `gksudo synaptic` in gmrun, window closes, layout switches back to 'ru' for root window.
- gksu prompt appears, but layout does not switch to 'en' for it.

I'm comaring this behavior to gxkb, which correctly tracks every applications' windows including gksu prompt.

**Comment by zjes** [comment]
Application or window switching policy?

**Comment by Vladimir-csp** [comment]
Application.

**Comment by zjes** [comment]
Can you try to switch to window mode? 
I'm afraid that this prompt has root window application name.

**Comment by Vladimir-csp** [comment]
Same thing with window mode. 
But gxkb tracks it somehow (it is designed to 'just work' in application mode).

**Comment by Vladimir-csp** [comment]
I was wrong, gxkb fails in this situation too. Not sure why I thought differently.

**Comment by stefonarch** [comment]
Tested, keyboards witching works now fine in global, application and window mode with gksu.
