### ISSUE TITLE
[pcmanfm-qt] icons for rename and compress ?

### ISSUE THREAD

**Issue by Esclapion** [lxqt/lxqt#844]
Sorry, because it's more a question than an issue, but i tried a dozen of themes and none displays an icon for those both operations when right-clicking on a folder or a file.
What can be please the name of those icons, if some are associated to that ?

**Comment by palinek** [comment]
Based on [this](https://github.com/lxde/pcmanfm-qt/blob/master/libfm-qt/filemenu.cpp#L211) & [this](https://github.com/lxde/pcmanfm-qt/blob/master/libfm-qt/filemenu.cpp#L173) there are no icons for those menu entries...

**Comment by Esclapion** [comment]
OK, thanks for the answer. I search that since a long time. A bit a pity...

I close.

**Comment by pmattern** [comment]
Problem exists in other desktop environments and file managers as well. In PCManFM GTK / LXDE and qtFM both icons are are missing, in Thunar topic "rename" doesn't feature an icon while "compressing" isn't available, in Dolphin "rename" has its icon and "compress" is missing.

The underlying [Icon Naming Specification](http://www.freedesktop.org/wiki/Specifications/icon-naming-spec/) doesn't define icon names `*rename*` or `*compress*`.

All in all this seems like an upstream issue an eventual solution of which would have to get implemented downstream, though.

Anyway definitely something that should be considered in the long run IMO, so reopening.

**Comment by tsujan** [comment]
Please don't reopen!
