### ISSUE TITLE
Do not use ~/.icons in cursor theme config

### ISSUE THREAD

**Issue by jleclanche** [lxqt/lxqt#885]
liblxqt-config-cursor/selectwnd.cpp writes the default cursor theme to ~/.icons. It should write to $XDG_DATA_DIR/icons instead

**Comment by Vladimir-csp** [comment]
It will still read `~/.icons` for backwards compatibility, I presume?

**Comment by jleclanche** [comment]
That's done elsewhere, lxqt-config doesn't read any of that.

**Comment by PCMan** [comment]
Please don't touch it.
The path is used by libXcursor by default.
Icon themes do follow the xdg specs while there are no existing standards for cursors.
The de facto standard is Xcursor at the moment.
Please don't break backward compatibility.

**Comment by jleclanche** [comment]
@PCMan Looked at the code, you're right, but then I'd rather we change the `$XCURSOR_PATH` environment variable:

http://cgit.freedesktop.org/xorg/lib/libXcursor/tree/src/library.c#n32

**Comment by PCMan** [comment]
FYI: Both of .icons and $XCURSOR_PATH are documented in the man page.
http://www.x.org/archive/current/doc/man/man3/Xcursor.3.xhtml#heading7
KDE configuration tools AFAIK, touches ~/.icons/deafult as well.
If it's not broken, I'd prefer not to fix it.

**Comment by PCMan** [comment]
The most important thing is, when the official man page states that the default path is ~/icons, and we don't support it, that's obviously wrong. So anyway we have to support ~/.icons whether you set $XCURSOR_PATH or not. I'd say let's close the issue.

**Comment by jleclanche** [comment]
@PCMan I don't get the logic. it's not exactly widely known how xcursor works. 

In any case someone should probably submit a patch to support `$XDG_DATA_DIR` in xcursor. I'll take care of it.
