### ISSUE TITLE
[lxqt-config-locale] inconsistent preview

### ISSUE THREAD

**Issue by Vladimir-csp** [lxqt/lxqt#887]
When 'Detailed settings' is checked, the preview is wrong, despite all is set to 'no change'.

![lcl](https://cloud.githubusercontent.com/assets/4061903/11075729/e8f17f2a-8807-11e5-8ec1-3f1e6ca63e2b.png)

**Comment by pmattern** [comment]
Confirmed.

The sample strings in section `Examples` are displayed in English for apparently no reason as soon as `Detailed Settings` is checked.
(@Vladimir-csp This is what you were referring to in your somewhat sparse description, right?)

**Comment by Vladimir-csp** [comment]
Yes, I hoped the screenshot did all the talking )

**Comment by tsujan** [comment]
See https://github.com/lxqt/lxqt-config/issues/824#issuecomment-1086340055
