### ISSUE TITLE
[lxqt-config-locale] Handle $LANGUAGE variable

### ISSUE THREAD

**Issue by Vladimir-csp** [lxqt/lxqt#890]
lxqt-config-locale does not handle `$LANGUAGE` variable. If variable is set, it results in apparent failure of overriding locale in lxqt-config-locale, because `$LANGUAGE` still references system-wide locale and applications use that.

```
$ locale
LANG=ru_RU.UTF-8
LANGUAGE=en_DK:en
LC_CTYPE="ru_RU.UTF-8"
LC_NUMERIC="ru_RU.UTF-8"
LC_TIME=en_DK.UTF-8
LC_COLLATE="ru_RU.UTF-8"
LC_MONETARY="ru_RU.UTF-8"
LC_MESSAGES="ru_RU.UTF-8"
LC_PAPER="ru_RU.UTF-8"
LC_NAME="ru_RU.UTF-8"
LC_ADDRESS="ru_RU.UTF-8"
LC_TELEPHONE="ru_RU.UTF-8"
LC_MEASUREMENT="ru_RU.UTF-8"
LC_IDENTIFICATION="ru_RU.UTF-8"
LC_ALL=
```

**Comment by Vladimir-csp** [comment]
To be clear, systemwide I have `LANG=en_DK.UTF-8`, `LANGUAGE=en_DK:en`.

Then I set `LANG=ru_RU.UTF-8` in session via lxqt-config-locale and LANGUAGE does not change, which causes problems. This is what the bug is about.

LC_TIME was overridden by hand via ~/.xsessionrc because one of the problems described in #886

**Comment by Rrhapsod** [comment]
Same here, for pt-br language. The system keeps in english.

**Comment by stefonarch** [comment]
Hm, I can switch to english or german (after restarting the session)   in LXQt with 
`/etc/locale.conf 
LANG=it_IT.UTF-8
`

**Comment by agaida** [comment]
LANGUAGE should not be set firsthand - and if one do so one should know why ...

* https://superuser.com/questions/392439/lang-and-language-environment-variable-in-debian-based-systems

and esp.
* https://www.gnu.org/software/gettext/manual/html_node/Locale-Environment-Variables.html#Locale-Environment-Variables
* https://www.gnu.org/software/gettext/manual/html_node/The-LANGUAGE-variable.html#The-LANGUAGE-variable
