### ISSUE TITLE
High DPI

### ISSUE THREAD

**Issue by tsujan** [lxqt/lxqt#916]
Please consider setting `Qt::AA_UseHighDpiPixmaps` to `true` for all LXQT apps as is done in some KDE apps.

**Comment by tsujan** [comment]
I think this is also related to #914.

I don't have a high DPI screen myself but the result could be tested with ordinary monitors too.

**Comment by stephens2424** [comment]
I have a high dpi monitor I can test with if need be.

**Comment by tsujan** [comment]
Yes, please report any issue you encounter, preferably under this ticket!

**Comment by stephens2424** [comment]
It's fairly unusable as is. Definitely eye straining even to just debug stuff. The attached screenshot is what I was looking at in a 15" screen space:

![screenshot from 2016-03-13 12-26-55](https://cloud.githubusercontent.com/assets/488895/13730805/6e8ea7be-e917-11e5-978b-b08e2f3b4450.png)

**Comment by tsujan** [comment]
Oh, I should have been more specific:

Forget about gtk and qt4 apps! Run Qt5 apps *belonging to LXQT* (like PCManFM) from terminal but after this line:
````
export QT_DEVICE_PIXEL_RATIO=2
````
For running components (like PCManFM, when it draws desktop), you'll first need to stop them from Configuration Center → Session Settings → Basic Settings → LXQT modules.

You could also change Configuration Center → Appearance → Font → Resolution from 96 to 192.

There aren't many apps for test but you should have Qt5 ≥ 5.5.1.

**Comment by stephens2424** [comment]
Opening PCManFM from the terminal with  env variable makes some elements work ok, like the select box and its picker, but fonts and menus are still too small. I already had the font DPI setting set to 192 and I'm not finding the LXQT modules section.

![screenshot from 2016-03-13 16-26-21](https://cloud.githubusercontent.com/assets/488895/13732127/67880ba6-e938-11e5-8e6f-c13329195bb8.png)

Sorry, I'm fairly new to anything linux off the command line... but I'm happy to keep trying things.

**Comment by tsujan** [comment]
@stephens2424 Thanks! Your screenshot revealed a bug.

**Comment by agaida** [comment]
as hidpi screens become more and more common i would like to set it to high prio

**Comment by tsujan** [comment]
It's easy to implement. If it isn't in pcmanfm-qt yet, I'll make a PR.

**Comment by agaida** [comment]
fine - will we need the two or three lines in every binary? I think i saw some of that stuff in some files when i implemented the cli interface

**Comment by tsujan** [comment]
> will we need the two or three lines

Yes!

**Comment by agaida** [comment]
hmm - i think we can take the list i made for cli

**Comment by agaida** [comment]
Binaries:
* compton-conf -- 
* lximage-qt -- 
* lxqt-about -- 
* lxqt-admin-time -- 
* lxqt-admin-user -- 
* lxqt-config -- already done
* lxqt-config-appearance -- 
* lxqt-config-brightness -- 
* lxqt-config-file-associations --
* lxqt-config-globalkeyshortcuts -- 
* lxqt-config-input -- 
* lxqt-config-locale -- 
* lxqt-config-monitor -- 
* lxqt-config-notificationd --
* lxqt-config-powermanagement -- 
* lxqt-config-session -- 
* lxqt-globalkeysd -- 
* lxqt-leave -- 
* lxqt-notificationd -- 
* lxqt-openssh-askpass -- 
* lxqt-panel -- 
* lxqt-policykit-agent -- 
* lxqt-powermanagement -- 
* lxqt-runner -- 
* lxqt-session -- 
* lxqt-sudo -- 
* obconf-qt -- 
* pavucontrol-qt -- 
* pcmanfm-qt -- 
* qterminal -- already done

**Comment by tsujan** [comment]
Thanks for the list!

BTW, this is mostly about icons -- for them not to be blurry with hdpi -- otherwise, they already work with `QT_SCALE_FACTOR=2 myApp`. *The important thing is a setting for hdpi factor in lxqt-config,* so that every Qt5 widget is scaled on login. I can't see it anywhere.

**Comment by agaida** [comment]
we don't set it right now i guess - but let us add the line to all apps with visible windows first. Even if no icons are involved, it shouldn't hurt

**Comment by fulalas** [comment]
I have access to a Macbook Pro with Retina display, so I can test on it if you want. :)

**Comment by agaida** [comment]
fulalas - thank you, we will come back to you if all the needed things are merged (see @tsujan's note)

**Comment by agaida** [comment]
@tsujan all set's should be in place, your turn :D

**Comment by tsujan** [comment]
> @tsujan all set's should be in place, your turn

You mean adding an option to lxqt-config? I think @luis-pereira and @palinek have more knowledge in that area.

**Comment by agaida** [comment]
:) - ok, i know that i have none of the needed knowledge.

**Comment by tsujan** [comment]
For the sake of clarity, this is an app that supports hdpi (all icons are clear with `QT_SCALE_FACTOR=2`):

![hdpi1](https://user-images.githubusercontent.com/981076/27602233-4c44cac4-5b87-11e7-91ca-0a09a672d920.png)

And this is an app that doesn't (icons are blurry or small):

![hdpi2](https://user-images.githubusercontent.com/981076/27602260-7133409a-5b87-11e7-9b68-eb84650510b9.png)

**Comment by agaida** [comment]
this is the knowledge i have - but i'm not really able to implement some new things in forms and so on. That must wait a year or so, slowly catching up.

**Comment by palinek** [comment]
> The important thing is a setting for hdpi factor in lxqt-config, so that every Qt5 widget is scaled on login. I can't see it anywhere.

You mean a GUI configuration to set env. variable QT_SCALE_FACTOR? This can be achieved in the `lxqt-config-session`, not?

**Comment by tsujan** [comment]
> You mean a GUI configuration to set env. variable QT_SCALE_FACTOR? This can be achieved in the lxqt-config-session, not?

Yes, it can! Adding a row for it would be great.

**Comment by tsujan** [comment]
@agaida You did very well.

**Comment by palinek** [comment]
> > You mean a GUI configuration to set env. variable QT_SCALE_FACTOR? This can be achieved in the lxqt-config-session, not?

> Yes, it can! Adding a row for it would be great.

I don't follow... what row are you talking about? The `lxqt-config-session` is providing the "Environment" tab in which you already can add whatever variable you wish.

**Comment by Vladimir-csp** [comment]
A couple of questions:
Can Qt or GTK decide on scaling on the fly by looking into current X DPI values?
Setting high DPI mode on session environment level in a separate variable is a bit strange architecturally, because: 1. displays can change, DPI can change, 2. there is already DPI value to work with.

**Comment by tsujan** [comment]
> I don't follow... what row are you talking about?

A variable name without value. Not all users know the names of such EVs.

@Vladimir-csp I don't have hdpi but I don't think changing display settings is done as often as changing a window size, for example.

**Comment by tsujan** [comment]
@palinek In general, it's good to do so for all variables that may be used usually. Users may not have even heard about "environment variables", let alone the one related to Qt scaling factor.

**Comment by Vladimir-csp** [comment]
> A variable name without value. Not all users know the names of such EVs.

This would set variable to empty, what if user tried to set some of them elsewhere?
Hight DPI settings would better go into dedicated place in lxqt-config-session (of course results will also show up in environment variables, but this is perfectly logical).

**Comment by tsujan** [comment]
> This would set variable to empty

Not necessarily. The code should be so that if a value is empty, the default value will be used -- 1 in this case.

> Hight DPI settings would better go into dedicated place in lxqt-config-session

The subject matter of a discussion between you and @palinek ;)

**Comment by nickgeoca** [comment]
I set the QT_SCALE_FACTOR=2 in lxqt-config-session. It fixes some dpi problems, but not others. Making the panel at the bottom fewer pixels caused some cropping.

![screenshot_3](https://user-images.githubusercontent.com/2054736/37304854-c2dcd390-2600-11e8-9983-f63585764279.png)

**Comment by agaida** [comment]
@tsujan - what is needed to close that bug - all lxqt applications should be able to process highdpi - so the "only" thing missed is some UI  - would this fit better in a new and explicit bug?

**Comment by tsimonq2** [comment]
> @agaida If all LXQt apps support HDPI, this can be closed; the rest is Qt's responsibility.

What about configuration for it?

**Comment by tsujan** [comment]
> What about configuration for it?

Yes, but not related to this report.
