### ISSUE TITLE
Skins for desktop clock

### ISSUE THREAD

**Issue by GreenLunar** [lxqt/lxqt#929]
Make desktop clock easily skin-able like [Cairo-Clock](https://github.com/stephane/cairo-clock).

https://github.com/Razor-qt/razor-qt/issues/540

**Comment by pmattern** [comment]
Err, a desktop clock doesn't exist so far in LXQt, does it? So implementing a clock would be needed in the first place before any theming can get discussed, no?

**Comment by paulolieuthier** [comment]
It existed in Razor.
