### ISSUE TITLE
[lxqt-config] - add a frame to the icon view

### ISSUE THREAD

**Issue by ghost** [lxqt/lxqt#947]
the should be a frame around or a line after the icon view to look better on bright themes:

![aaa](https://cloud.githubusercontent.com/assets/3780774/12696034/5e205ba4-c75f-11e5-8e61-7d32494111ac.png)

looks a lot better after adding a bottom border:

![bbb](https://cloud.githubusercontent.com/assets/3780774/12696040/9905b520-c75f-11e5-80cd-67294b7e4af9.png)

**Comment by tsujan** [comment]
Please use Fusion when sending screenshots of such issues: `lxqt-config-appearance -style fusion`, which gives this:

![2016-01-30-18 26 56-scrot](https://cloud.githubusercontent.com/assets/981076/12696403/5a3954e4-c77f-11e5-812d-e4f0dd438ef9.png)

**Comment by tsujan** [comment]
BTW, Kvantum could work around it if you set a frame around ItemView:

![2016-01-30-18 39 42-scrot](https://cloud.githubusercontent.com/assets/981076/12696485/249c5550-c781-11e5-87a4-03730f903141.png)

**Comment by sixsixfive** [comment]
>BTW, Kvantum could work around it if you set a frame around ItemView:

its even simpier just add this qss to your LXQt-theme: https://github.com/sixsixfive/other-themes/blob/master/LXQt/aalglatt/lxqt-config.qss

anyway I would prefer a real fix than work around something ;)

**Comment by tsujan** [comment]
Nothing to fix. It depends on the theme.
