### ISSUE TITLE
liblxqt-config-cursor: Please fix up the used licenses if possible

### ISSUE THREAD

**Issue by agaida** [lxqt/lxqt#969]
```
liblxqt-config-cursor/cfgfile.h: *No copyright* WTFPL WTFPL (v2)
liblxqt-config-cursor/main.cpp: *No copyright* WTFPL WTFPL (v2)
liblxqt-config-cursor/selectwnd.h: *No copyright* WTFPL WTFPL (v2)
liblxqt-config-cursor/thememodel.h: GPL (v3)
liblxqt-config-cursor/main.h: *No copyright* WTFPL WTFPL (v2)
liblxqt-config-cursor/itemdelegate.cpp: GPL (v3)
liblxqt-config-cursor/selectwnd.cpp: *No copyright* WTFPL WTFPL (v2)
liblxqt-config-cursor/crtheme.h: GPL (v3)
liblxqt-config-cursor/previewwidget.cpp: GPL (v2)
liblxqt-config-cursor/thememodel.cpp: GPL (v3)
liblxqt-config-cursor/warninglabel.cpp: LGPL (v2.1 or later)
liblxqt-config-cursor/previewwidget.h: GPL (v2)
liblxqt-config-cursor/xcr/xcrtheme.h: *No copyright* WTFPL WTFPL (v2)
liblxqt-config-cursor/xcr/xcrxcur.cpp: *No copyright* WTFPL WTFPL (v2)
liblxqt-config-cursor/xcr/xcrxcur.h: *No copyright* WTFPL WTFPL (v2)
liblxqt-config-cursor/xcr/xcrthemefx.cpp: *No copyright* WTFPL WTFPL (v2)
liblxqt-config-cursor/xcr/xcrthemefx.h: *No copyright* WTFPL WTFPL (v2)
liblxqt-config-cursor/xcr/xcrimg.h: *No copyright* WTFPL WTFPL (v2)
liblxqt-config-cursor/xcr/xcrthemexp.cpp: *No copyright* WTFPL WTFPL (v2)
liblxqt-config-cursor/xcr/xcrtheme.cpp: *No copyright* WTFPL WTFPL (v2)
liblxqt-config-cursor/xcr/xcrthemexp.h: *No copyright* WTFPL WTFPL (v2)
liblxqt-config-cursor/xcr/xcrimg.cpp: *No copyright* WTFPL WTFPL (v2)
liblxqt-config-cursor/crtheme.cpp: GPL (v3)
liblxqt-config-cursor/warninglabel.h: LGPL (v2.1 or later)
liblxqt-config-cursor/cfgfile.cpp: *No copyright* WTFPL WTFPL (v2)
liblxqt-config-cursor/itemdelegate.h: GPL (v3)
```

I'm ok with any WTFPL oder LGPL+ License, i'm not ok with double licensed files (GPL2 or GPL3 ) without later clause. Belive it or not, but this can turn out to be a shoot in both feets later. Really, 20 files, 30 licenses should not be the way to go.

**Comment by jleclanche** [comment]
Anything WTFPL we can (and should) relicense to GPL3.

**Comment by agaida** [comment]
I have no problem with the WTFPL v2, is a known and FSF approved free license and will ever be compatible with any upcoming GPL. But some people might be offended. So we could do this. But i fear another thing. GPL3 files without later clause might be not compatible with a possible successor of GPL3. Have seen this before with GPL2 (kernel anyone?) and was in this trap before. So i had to ask upstream for relicensing the files in charge. In our case it's not a problem.

**Comment by jleclanche** [comment]
It's not about being offended, I just want us to keep our licensing simple.

**Comment by jleclanche** [comment]
Regarding later clauses, I agree, which is why I always label as "GPL3+".

**Comment by agaida** [comment]
i would prefer lgpl-2.1+, then gpl2+ if possible - both include the later 3 license. And if a problem with some particular things in (L)GPL2 show up there is the chance to use the sources at wish with the later license. This could prevent problems with other code written in (L)GPL2 only. But that means too, that we should keep our portfolio of used licences clean. the wtfpl was never a problem, this license works with all other licenses. With or without relicensing. And therefore i prefer to leave it like it is. Otherwise we could do harm to someone who is forking our relicensed code in the sense of taking the freedom of the wtfpl away from him with no reason.

**Comment by jleclanche** [comment]
> Otherwise we could do harm to someone who is forking our relicensed code in the sense of taking the freedom of the wtfpl away from him with no reason.

I strongly dislike that we have bits and pieces of the code under completely different licenses. If someone wants to fork our code, that's fine, gpl allows for that. But if that's the case I do not want anyone (including us) to have to deal with looking up licenses file by file.

A clean, single license for a single component is far friendlier than having *parts* of the code under "freeer" licenses.
