### ISSUE TITLE
Task panel improvements

### ISSUE THREAD

**Issue by birdie-github** [lxqt/lxqt#98]
Bugs:
1) Start Menu folders can be moved onto it, but nothing happens when I click these attached folders.

Feature requests:
1) It must have locked/unlocked state.
2) When it's unlocked all widgets must have a special graphical hook, so when I mouse press it (without releasing a mouse), then the selected widget can be allowed to be moved left and right.

**Comment by stefonarch** [comment]
1) no issue for years
Feature requests:
1) solved time ago (lock panel)
2) possible with right click > move
