### ISSUE TITLE
lxqt-config-session/Default Applications: paths selected by file chooser don't get saved

### ISSUE THREAD

**Issue by RalfJung** [lxqt/lxqt#984]
Steps to reproduce:
- Open lxsession configuration
- Pick some absolute path for the default browser or terminal, e.g. `home/r/bin/firefox/firefox`.
- Quit config
- Open config again

Actual behavior:
- The config now shows just `firefox`.
- After logging out and back in, `BROWSER` is set to `firefox` and tools like `sensible-browser` do not work.

Expected behavior:
- The full path should be properly preserved.

This is with LXQt 0.10 on Debian.

**Comment by jleclanche** [comment]
If you're using lxqt-session you should not be using lxsession-config

**Comment by jleclanche** [comment]
cc @gilir

**Comment by RalfJung** [comment]
Eh... okay, I guess I'm not what exactly I am using. I am using the "session settings" offered in "Preferences - LXQt settings". qps calls this `lxqt-session-config`. I guess all I did wrong is use the wrong name in the title of the issue?

**Comment by jleclanche** [comment]
ok, that's something else then

**Comment by pmattern** [comment]
Confirmed, albeit a bit different than depicted above.

In `lxqt-config-session` - "Default Applications" (left pane) - "{Terminal Emulation,Web Browser}" (right pane) absolute paths aren't saved at all when they are selected by dialogue window "Select a {terminal emulator,web browser}" as launched by buttons `Search...`. The usual dialogue "Some settings will not take effect until the next log in." doesn't appear upon making changes that way either.
Everything is working as expected when absolute paths are filed manually or when a binary gets selected from the drop-down menu at the form's right end.

Arch Linux running recent VCS checkouts of LXQt including lxde/lxqt-session@1e7f82c as well as LXQt 0.10 from the official repositories on Debian testing (same findings).

Notes:
The binary is called `lxqt-config-session`. Took the liberty to change the title another time to have it more concise.
Eventually we'll stop setting environment variables $TERM and $BROWSER in favour of tools relying on the "MIME Applications Specification" see e. g. #433. Personally, I don't know any other tools except the various `sensible-*` of Debian making use of those variables. And besides used by other distributions as well these tools seem a bit questionable to me, in particular as they're basically some kind of alternative to the more sophisticated alternative system only. So do you by any chance happen to know any other tool or application still relying on these variables?

**Comment by RalfJung** [comment]
> So do you by any chance happen to know any other tool or application still relying on these variables, in particular BROWSER?

No, I don't. And you could always set BROWSER to xdg-open such that it uses the XDG mechanism. (In fact, that's what I am going to do right now; and I hope I will remember this and never change BROWSER again^^).

**Comment by pmattern** [comment]
> set BROWSER to xdg-open [...] that's what I am going to do

You did notice the workaround I've been posing above?

**Comment by RalfJung** [comment]
About entering the complete path directly? I did. But I need to set the default browser the XDG-way anyway for other applications to work. So then I'd rather use only the XDG configuration, and not think about BROWSER anymore.

**Comment by agaida** [comment]
same thing as #1560?

**Comment by stefonarch** [comment]
Looks so.

**Comment by agaida** [comment]
solved with  lxqt/lxqt-session#176
