### ISSUE TITLE
lxqt-confupdate doesn't exists

### ISSUE THREAD

**Issue by selairi** [lxqt/lxqt#993]
lxqt-session calls to lxqt-confupdate in startConfUpdate() method from lxqtmodman.cpp, but I can find lxqt-confupdate. What is lxqt-confupdate?

I have realized that lxqt-common default settings of openbox are not used. Should lxqt-confupdate apply those settings?

I want lxqt-common default settings for openbox to be applied. I could fix it by myself, but I need some answers.

Thanks

**Comment by palinek** [comment]
IMO this is something rather oudated:
- https://github.com/lxde/lxqt-session/commit/f6b8e7cd
- https://github.com/Razor-qt/razor-qt/tree/master/razorqt-confupdate

**Comment by palinek** [comment]
> I have realized that lxqt-common default settings of openbox are not used.

What do you mean by that?

**Comment by selairi** [comment]
> 
>   >  I have realized that lxqt-common default settings of openbox are not used.
> 
> What do you mean by that?
> 

lxqt-common has got some files about Openbox. Openbox settings are in the "rc.xml.in" file. This file defines Openbox key shortcuts or themes when is used by LXQt. But this file is not used by Openbox when you start a LXQt session. Openbox uses "~/.config/openbox/rc.xml" instead. 

Openbox has got "--config-file" argument. "--config-file" argument specifies the path to the config file to use. I guess that lxqt-session should start Openbox and sets "--config-file" argument to "~/.config/lxqt/openbox/rc.xml" with special settings for LXQt.

Currently if you use Openbox, you will not be able to redefine some key shortcuts in lxqt-globalkeys, because they are already defined in "~/.config/openbox/rc.xml".

**Comment by palinek** [comment]
> Openbox settings are in the "rc.xml.in" file. 

IMO the `rc.xml.in` and `menu.xml` are just an examples of openbox configuration and as so installed into *.../share/lxqt/openbox* dir -> https://github.com/lxde/lxqt-common/blob/master/config/CMakeLists.txt#L10.

@jleclanche, @PCMan ?

**Comment by selairi** [comment]
I have added a few lines in lxqt-session in order to load default Openbox settings. 

Openbox settings for LXQt will be in "~/.config/lxqt/openbox", Openbox (no LXQt session) saves its settings in "~/.config/openbox" .

You can change Openbox settings for LXQt in "lxqt-common/config/openbox/rc.xml". I have erased some key shortcuts already defined in lxqt-globalkeys.
