### ISSUE TITLE
[lxqt-panel] statusnotifier plugin broken : crash QT5 systray enabled apps 

### ISSUE THREAD

**Issue by bignaux** [lxqt/lxqt#995]
Since QT 5.5 , Qt choose Status Notifier as default tray. Then, if statusnotifier is enable, all QT5 apps build on QT5 segfault on setContextMenu(). Workaround : disable it and keep only old tray plugin.

Env : LxQT 0.10.0-r1 / QT 5.7.0_alpha
Tested apps :  qtox, cmst, transmission-qt ,  QT 5.7 build.

ref : https://github.com/tux3/qTox/wiki/Tray-icon

**Comment by paulolieuthier** [comment]
I use Qt5 version of QTransmission and status notifier with no problems here.

**Comment by paulolieuthier** [comment]
@bignaux how did you install LXQt? Did you install lxqt-qtplugin??
